export const MINISTORY_KANJIS_N2: Record<string, MinistoryRubyKanji> = {
  "創": { kanji: "創", meaning: "create・Start・originate", rubyWord: "創{つく}る", wordMeaning: "to create" },
  "勝": { kanji: "勝", meaning: "victory", rubyWord: "勝{か}つ", wordMeaning: "to win" },
  "負": { kanji: "負", meaning: "defeat", rubyWord: "負{ま}ける", wordMeaning: "to lose" },
  "種": { kanji: "種", meaning: "Seed・Kind・type・species", rubyWord: "種{しゅ}類{るい}", wordMeaning: "Kind・type" },
  "放": { kanji: "放", meaning: "To let go", rubyWord: "放{はな}す", wordMeaning: "to let go・to release", wordSentence: "手を放す"},
  "題": { kanji: "題", meaning: "Topic・Subject・Problem・Question", rubyWord: "問{もん}題{だい}", wordMeaning: "question・problem" },
  "等": { kanji: "等", meaning: "Class・Rank・And so on・Etc.", rubyWord: "等{など}", wordMeaning: "and so on・etc.", wordSentence: "パン、ケーキ等を買いました。"},
  "歓": { kanji: "歓", meaning: "Delight・Joy", rubyWord: "歓{かん}迎{げい}", wordMeaning: "welcome", wordSentence: "日本へ歓迎します。" },
  "迎": { kanji: "迎", meaning: "To welcome・To receive (someone)", rubyWord: "迎{むか}える", wordMeaning: "to welcome・to go pick someone up", wordSentence: "駅まで友だちを迎えに行く。" },
  "評": { kanji: "評", meaning: "Evaluate・Criticism・Comment", rubyWord: "評{ひょう}価{か}", wordMeaning: "Evaluation" },
  "判": { kanji: "判", meaning: "Judgement・Signature・Decision", rubyWord: "判{はん}断{だん}", wordMeaning: "Judgement・Decision" },
  "栄": { kanji: "栄", meaning: "Glory・Prosperity・Honor", rubyWord: "栄{さか}える", wordMeaning: "To prosper・To be honored", wordSentence: "この町は昔とても栄えた。" },
  "養": { kanji: "養", meaning: "Take care of・Support・Raise", rubyWord: "養{やしな}う", wordMeaning: "to support・to raise・to provide for", wordSentence: "家族を養う。" },
  "臭": { kanji: "臭", meaning: "Smell・Stink", rubyWord: "臭{くさ}い", wordMeaning: "smelly・stinky" },
  "賞": { kanji: "賞", meaning: "Prize・Award", rubyWord: "賞{しょう}金{きん}", wordMeaning: "prize money" },
  "農": { kanji: "農", meaning: "Agriculture・Farming", rubyWord: "農{のう}業{ぎょう}", wordMeaning: "agriculture" },
  "粗": { kanji: "粗", meaning: "Coarse・Rough・Crude", rubyWord: "粗{あら}い", wordMeaning: "rough・coarse" },
  "末": { kanji: "末", meaning: "End・Future", rubyWord: "末{すえ}", wordMeaning: "the end・the future" },
  "訳": { kanji: "訳", meaning: "Translation・Reason・Circumstance", rubyWord: "訳{わけ}", wordMeaning: "reason・circumstance", wordSentence: "どういう訳？" },
  "支": { kanji: "支", meaning: "Branch・Support・Sustain", rubyWord: "支{ささ}える", wordMeaning: "to support・to sustain" },
  "感": { kanji: "感", meaning: "Feeling・Sensation・Emotion", rubyWord: "感{かん}じる", wordMeaning: "to feel" },
  "染": { kanji: "染", meaning: "Dye・stain・Infect・Catch (a cold)", rubyWord: "染{そ}める", wordMeaning: "to dye" },
  "症": { kanji: "症", meaning: "Symptom・Illness", rubyWord: "症{しょう}状{じょう}", wordMeaning: "symptom" },
  "流": { kanji: "流", meaning: "Stream・Flow・Current", rubyWord: "流{なが}れる", wordMeaning: "to flow" },
  "制": { kanji: "制", meaning: "Control・Restrain・System", rubyWord: "制{せい}度{ど}", wordMeaning: "system・institution" },
  "限": { kanji: "限", meaning: "Limit・Restrict", rubyWord: "限{かぎ}る", wordMeaning: "to limit・to restrict" },
  "精": { kanji: "精", meaning: "Spirit・Energy・Refined", rubyWord: "精{せい}神{しん}", wordMeaning: "spirit・energy・mind", wordSentence: "精神が強い。" },
  "算": { kanji: "算", meaning: "Calculate・Count", rubyWord: "算{さん}数{すう}", wordMeaning: "Mathematics・arithmetic" },
  "貯": { kanji: "貯", meaning: "Save・Store", rubyWord: "貯{た}める", wordMeaning: "to save (money)", wordSentence: "お金を貯める。" },
  "与": { kanji: "与", meaning: "Give・Grant・Bestow", rubyWord: "与{あた}える", wordMeaning: "to give・to grant・to bestow" },
  "装": { kanji: "装", meaning: "Wear・Equip・Dress・Pretend", rubyWord: "装{よそお}う", wordMeaning: "to dress up・to pretend" },
  "返": { kanji: "返", meaning: "Return・Reply", rubyWord: "返{かえ}す", wordMeaning: "to return (something)・to reply" },
  "数": { kanji: "数", meaning: "Number・Count", rubyWord: "数{かぞ}える", wordMeaning: "to count" },
  "頂": { kanji: "頂", meaning: "Receive・Top・Summit", rubyWord: "頂{いただ}く", wordMeaning: "to receive (humble form)" },
  "戴": { kanji: "戴", meaning: "Receive・Wear on the head", rubyWord: "戴{いただ}く", wordMeaning: "to receive (humble form)" },
  "商": { kanji: "商", meaning: "Commerce・Trade・Sell", rubyWord: "商{しょう}店{てん}", wordMeaning: "shop・store" },
  "販": { kanji: "販", meaning: "Sell・Market", rubyWord: "販{はん}売{ばい}", wordMeaning: "sale" },
  "封": { kanji: "封", meaning: "Seal・Enclose", rubyWord: "封{ふう}筒{とう}", wordMeaning: "envelope", wordSentence: "封筒に手紙を入れる。" },
  "済": { kanji: "済", meaning: "Finish・Settle・Relieve", rubyWord: "済{す}む", wordMeaning: "to finish・to be settled", wordSentence: "支払い済み" },
  "各": { kanji: "各", meaning: "Each・Every", rubyWord: "各{かく}駅{えき}停{てい}車{しゃ}", wordMeaning: "local train (stops at every station)" },
  "格": { kanji: "格", meaning: "Rank・Status・Standard", rubyWord: "性{せい}格{かく}", wordMeaning: "Personality・Character" },
  "製": { kanji: "製", meaning: "Manufacture・Make・Made in", rubyWord: "日{に}本{ほん}製{せい}", wordMeaning: "Made in Japan" },
  "扱": { kanji: "扱", meaning: "Handle・Deal with", rubyWord: "扱{あつか}う", wordMeaning: "to handle・to deal in", wordSentence: "この店は各種の電化製品を取り扱っています。" },
  "条": { kanji: "条", meaning: "Article・Clause・Condition", rubyWord: "条{じょう}文{ぶん}", wordMeaning: "article・clause (in a law or contract)" },
  "件": { kanji: "件", meaning: "Matter・Case・Item", rubyWord: "事{じ}件{けん}", wordMeaning: "incident・crime" },
  "指": { kanji: "指", meaning: "Finger・To point", rubyWord: "指{さ}す", wordMeaning: "to point" },
  "定": { kanji: "定", meaning: "Fix・Decide・Determine・Set", rubyWord: "決{けっ}定{てい}", wordMeaning: "decision" },
  "銭": { kanji: "銭", meaning: "Money・Coin", rubyWord: "銭{せん}湯{とう}", wordMeaning: "Public bath" },
  "硬": { kanji: "硬", meaning: "Hard・Stiff", rubyWord: "硬{かた}い", wordMeaning: "hard・stiff" },
  "貨": { kanji: "貨", meaning: "Cargo・Freight・Currency", rubyWord: "貨{か}物{もつ}", wordMeaning: "cargo" },
  "紙": { kanji: "紙", meaning: "Paper", rubyWord: "紙{かみ}袋{ぶくろ}", wordMeaning: "paper bag" },
  "幣": { kanji: "幣", meaning: "Paper money", rubyWord: "紙{し}幣{へい}", wordMeaning: "banknote・paper money" },
  "購": { kanji: "購", meaning: "Purchase", rubyWord: "購{こう}読{どく}", wordMeaning: "subscription (magazine, newspaper)" },
  "価": { kanji: "価", meaning: "Value・Price", rubyWord: "原{げん}価{か}", wordMeaning: "Original price・Production cost" },
  "為": { kanji: "為", meaning: "Do・Make", rubyWord: "行{こう}為{い}", wordMeaning: "action・to act" },
  "替": { kanji: "替", meaning: "Exchange・Replace", rubyWord: "替{か}える", wordMeaning: "to exchange・to replace" },
  "関": { kanji: "関", meaning: "Barrier・Connection・Relation", rubyWord: "関{かん}係{けい}", wordMeaning: "relation・connection" },
  "税": { kanji: "税", meaning: "Tax", rubyWord: "消{しょう}費{ひ}税{ぜい}", wordMeaning: "consumption tax" },
  "落": { kanji: "落", meaning: "Fall・Drop", rubyWord: "落{お}ちる", wordMeaning: "to fall・to drop" },
  "残": { kanji: "残", meaning: "Remain・Leftover", rubyWord: "残{のこ}る", wordMeaning: "to remain・to be left over" },
  "充": { kanji: "充", meaning: "Fill・Full・Sufficient", rubyWord: "充{じゅう}実{じつ}", wordMeaning: "full・sufficient" },
  "座": { kanji: "座", meaning: "Seat・Sit", rubyWord: "座{すわ}る", wordMeaning: "to sit" },
  "束": { kanji: "束", meaning: "Bundle・Bunch・group", rubyWord: "約{やく}束{そく}", wordMeaning: "Promise" },
  "贈": { kanji: "贈", meaning: "Give (a gift)・Present", rubyWord: "贈{おく}り物{もの}", wordMeaning: "gift" },
  "概": { kanji: "概", meaning: "Outline・General", rubyWord: "概{がい}要{よう}", wordMeaning: "Summary・General idea・Overview" },
  "絶": { kanji: "絶", meaning: "Discontinue・Cut off・Absolute", rubyWord: "絶{ぜっ}対{たい}", wordMeaning: "absolutely" },
  "版": { kanji: "版", meaning: "Edition・Printing block・Version", rubyWord: "新{しん}版{ばん}", wordMeaning: "new edition" },
  "予": { kanji: "予", meaning: "Beforehand・In advance", rubyWord: "予{よ}定{てい}", wordMeaning: "Plan・Schedule" },
  "追": { kanji: "追", meaning: "Chase・Drive away・Follow", rubyWord: "追{つい}加{か}", wordMeaning: "addition・to add・to append", wordSentence: "注文を追加する" },
  "損": { kanji: "損", meaning: "Loss・Damage", rubyWord: "損{そん}する", wordMeaning: "To lose・To be at a loss" },
  "得": { kanji: "得", meaning: "Gain・Profit", rubyWord: "得{とく}する", wordMeaning: "To gain・To be profitable" },
  "終": { kanji: "終", meaning: "End・Finish", rubyWord: "終{お}わる", wordMeaning: "to end・to finish" },
  "了": { kanji: "了", meaning: "Completion・Finish", rubyWord: "完{かん}了{りょう}", wordMeaning: "completion", wordSentence: "ダウンロード完了" },
  "質": { kanji: "質", meaning: "Quality・Nature・Substance", rubyWord: "質{しつ}問{もん}", wordMeaning: "Question・Inquiry" },
  "展": { kanji: "展", meaning: "Unfold・Expand・Exhibit", rubyWord: "展{てん}開{かい}", wordMeaning: "Development・Expansion" },
  "示": { kanji: "示", meaning: "Show・Indicate・Point out", rubyWord: "表{ひょう}示{じ}", wordMeaning: "Display (on screen/sign)", wordSentence: "画面に表示される" },
  "確": { kanji: "確", meaning: "Certain・Sure・Confirm", rubyWord: "確{かく}認{にん}", wordMeaning: "confirmation" },
  "私": { kanji: "私", meaning: "Private・I・Me", rubyWord: "私{わたし}", wordMeaning: "I・me" },
  "全": { kanji: "全", meaning: "Whole・All", rubyWord: "全{ぜん}部{ぶ}", wordMeaning: "all・whole" },
  "身": { kanji: "身", meaning: "Body・Oneself", rubyWord: "自{じ}身{しん}", wordMeaning: "oneself", wordSentence: "自分自身でやる" },
  "揃": { kanji: "揃", meaning: "Complete・Gather・Get ready", rubyWord: "揃{そろ}う", wordMeaning: "to be complete・to gather" },
  "表": { kanji: "表", meaning: "Surface・Table・Chart・Express", rubyWord: "発{はっ}表{ぴょう}", wordMeaning: "Presentation・Announcement" },
  "背": { kanji: "背", meaning: "Back・Height", rubyWord: "背{せ}が高{たか}い", wordMeaning: "tall (of a person)" },
  "伸": { kanji: "伸", meaning: "Stretch・Extend・Grow", rubyWord: "伸{の}ばす", wordMeaning: "to stretch・to extend" },
  "呼": { kanji: "呼", meaning: "Call・Invite・Breathe", rubyWord: "呼{よ}ぶ", wordMeaning: "to call (out to someone)" },
  "吸": { kanji: "吸", meaning: "Suck・Inhale・Breathe", rubyWord: "吸{す}う", wordMeaning: "to inhale・to breathe", wordSentence: "タバコを吸う" },
  "識": { kanji: "識", meaning: "Knowledge・Awareness・Recognition", rubyWord: "知{ち}識{しき}", wordMeaning: "knowledge" },
  "逆": { kanji: "逆", meaning: "Reverse・Opposite・Contrary", rubyWord: "逆{さか}さ", wordMeaning: "upside down・in reverse" },
  "衣": { kanji: "衣", meaning: "Clothing・Garment", rubyWord: "衣{い}類{るい}", wordMeaning: "clothing" },
  "料": { kanji: "料", meaning: "Material・Fee・Charge", rubyWord: "料{りょう}理{り}", wordMeaning: "cuisine・cooking" },
  "整": { kanji: "整", meaning: "Arrange・Organize・Tidy up", rubyWord: "整{せい}理{り}", wordMeaning: "to arrange・to tidy up" },
  "理": { kanji: "理", meaning: "Logic・Reason・Science", rubyWord: "理{り}由{ゆう}", wordMeaning: "reason" },
  "回": { kanji: "回", meaning: "Times・Revolve・Turn・Occurrence", rubyWord: "一{いっ}回{かい}", wordMeaning: "once・a time" },
  "収": { kanji: "収", meaning: "Income・Collect・Receive", rubyWord: "収{しゅう}入{にゅう}", wordMeaning: "income" },
  "余": { kanji: "余", meaning: "Surplus・Excess・Too much", rubyWord: "余{よ}裕{ゆう}", wordMeaning: "extra time・margin" },
  "義": { kanji: "義", meaning: "Righteousness・Justice・Meaning", rubyWord: "義{ぎ}務{む}", wordMeaning: "duty・obligation" },
  "美": { kanji: "美", meaning: "Beauty・Beautiful", rubyWord: "美{び}容{よう}院{いん}", wordMeaning: "beauty salon" },
  "断": { kanji: "断", meaning: "Cut off・Refuse・Decide", rubyWord: "断{ことわ}る", wordMeaning: "to refuse" },
  "批": { kanji: "批", meaning: "Criticism・Comment", rubyWord: "批{ひ}評{ひょう}", wordMeaning: "criticism" },
  "敏": { kanji: "敏", meaning: "Sensitive・Quick・Clever", rubyWord: "敏{びん}感{かん}", wordMeaning: "sensitive" },
  "地": { kanji: "地", meaning: "Ground・Earth・Place", rubyWord: "地{ち}下{か}鉄{てつ}", wordMeaning: "subway" },
  "妊": { kanji: "妊", meaning: "Pregnancy", rubyWord: "妊{にん}娠{しん}", wordMeaning: "pregnancy" },
  "婦": { kanji: "婦", meaning: "Woman・Married Woman", rubyWord: "婦{ふ}人{じん}", wordMeaning: "woman・married woman" },
  "巻": { kanji: "巻", meaning: "Roll・Volume・Curl", rubyWord: "一{いっ}巻{けん}", wordMeaning: "volume 1" },
  "抜": { kanji: "抜", meaning: "Pull out・Extract・Omit", rubyWord: "〜抜{ぬ}き", wordMeaning: "Without", wordSentence: "砂糖抜きでお願いします" },
  "我": { kanji: "我", meaning: "I・Myself", rubyWord: "我{が}慢{まん}", wordMeaning: "patience・endurance" },
  "慢": { kanji: "慢", meaning: "Pride・Boast・Arrogance", rubyWord: "我{が}慢{まん}", wordMeaning: "patience・endurance" },
  "試": { kanji: "試", meaning: "Try・Test・Attempt", rubyWord: "試{し}験{けん}", wordMeaning: "test・experiment" },
  "着": { kanji: "着", meaning: "Arrive・Wear・Put on", rubyWord: "着{き}る", wordMeaning: "to wear・to put on" },
  "客": { kanji: "客", meaning: "Guest・Customer", rubyWord: "お客{きゃく}様{さま}", wordMeaning: "customer" },
  "観": { kanji: "観", meaning: "View・Look・Appearance", rubyWord: "観{かん}光{こう}", wordMeaning: "sightseeing" },
  "組": { kanji: "組", meaning: "Group・Set・Team", rubyWord: "組{く}む", wordMeaning: "to form・to put together" },
  "調": { kanji: "調", meaning: "Investigate・Check・Adjust", rubyWord: "調{しら}べる", wordMeaning: "to check・to look up" },
  "節": { kanji: "節", meaning: "Joint・Season・Section・Occasion", rubyWord: "季{き}節{せつ}", wordMeaning: "Season" },
  "派": { kanji: "派", meaning: "Faction・Group・Style", rubyWord: "〜派{は}", wordMeaning: "– type・~ preference group", wordSentence: "甘いもの派・犬派 / 猫派" },
  "透": { kanji: "透", meaning: "Transparent・See through", rubyWord: "透{す}ける", wordMeaning: "To be see-through・transparent" },
  "眼": { kanji: "眼", meaning: "Eye", rubyWord: "眼{め}鏡{がね}", wordMeaning: "glasses" },
  "鏡": { kanji: "鏡", meaning: "Mirror", rubyWord: "鏡{かがみ}", wordMeaning: "mirror", wordSentence: "鏡を見る" },
  "効": { kanji: "効", meaning: "Effect・Efficacy", rubyWord: "有{ゆう}効{こう}", wordMeaning: "valid・effective", wordSentence: "有効期限: 2023年12月31日" },
  "果": { kanji: "果", meaning: "Fruit・Result・Effect", rubyWord: "結{けっ}果{か}", wordMeaning: "result・outcome" },
  "薄": { kanji: "薄", meaning: "Thin・Weak・Light", rubyWord: "薄{うす}い", wordMeaning: "thin・weak・light" },
  "割": { kanji: "割", meaning: "Divide・Split・Discount", rubyWord: "割{わ}る", wordMeaning: "to divide・to split" },
  "容": { kanji: "容", meaning: "Contain・Form・Appearance", rubyWord: "内{ない}容{よう}", wordMeaning: "content" },
  "濃": { kanji: "濃", meaning: "Concentrated・Thick・Dark", rubyWord: "濃{こ}い", wordMeaning: "concentrated・thick・dark" },
  "剃": { kanji: "剃", meaning: "Shave", rubyWord: "剃{そ}る", wordMeaning: "to shave" },
  "脱": { kanji: "脱", meaning: "Take off・Escape・Get out of", rubyWord: "脱{ぬ}ぐ", wordMeaning: "to take off (clothes)", wordSentence: "靴を脱ぐ" },
  "無": { kanji: "無", meaning: "Nothing・Without", rubyWord: "無{む}料{りょう}", wordMeaning: "free of charge" },
  "抵": { kanji: "抵", meaning: "Resist・Oppose", rubyWord: "抵{てい}抗{こう}", wordMeaning: "resistance" },
  "抗": { kanji: "抗", meaning: "Resist・Oppose", rubyWord: "抵{てい}抗{こう}", wordMeaning: "resistance" },
  "夫": { kanji: "夫", meaning: "Husband・Man", rubyWord: "夫{おっと}", wordMeaning: "husband" },
  "知": { kanji: "知", meaning: "Know・Wisdom・Intellect", rubyWord: "知{し}る", wordMeaning: "to know" },
  "幅": { kanji: "幅", meaning: "Width・Breadth・Range", rubyWord: "幅{はば}", wordMeaning: "width・range" },
  "独": { kanji: "独", meaning: "Alone・Germany", rubyWord: "独{どく}立{りつ}", wordMeaning: "independence" },
  "特": { kanji: "特", meaning: "Special・Particular", rubyWord: "特{とく}別{べつ}", wordMeaning: "special" },
  "統": { kanji: "統", meaning: "Unite・Integrate・Overall", rubyWord: "統{とう}一{いつ}", wordMeaning: "unification" },
  "領": { kanji: "領", meaning: "Territory・Jurisdiction・Domain", rubyWord: "領{りょう}収{しゅう}書{しょ}", wordMeaning: "Receipt" },
  "欧": { kanji: "欧", meaning: "Europe", rubyWord: "欧{おう}州{しゅう}", wordMeaning: "Europe" },
  "米": { kanji: "米", meaning: "Rice・America", rubyWord: "米{べい}国{こく}", wordMeaning: "America" },
  "個": { kanji: "個", meaning: "Individual・Counter for small objects", rubyWord: "個{こ}", wordMeaning: "counter for small objects" },
  "性": { kanji: "性", meaning: "Gender・Nature・property", rubyWord: "性{せい}格{かく}", wordMeaning: "Personality・Character" },
  "答": { kanji: "答", meaning: "Answer・Reply", rubyWord: "答{こた}える", wordMeaning: "to answer・to reply" },
  "満": { kanji: "満", meaning: "Full・Satisfied・Full moon", rubyWord: "満{み}足{た}す", wordMeaning: "to satisfy" },
  "剰": { kanji: "剰", meaning: "Surplus・Excess", rubyWord: "剰{じょう}余{よ}", wordMeaning: "surplus・excess" },
  "生": { kanji: "生", meaning: "Life・Birth・Raw", rubyWord: "生{なま}", wordMeaning: "raw" },
  "産": { kanji: "産", meaning: "Produce・Give birth", rubyWord: "産{う}む", wordMeaning: "to give birth" },
  "和": { kanji: "和", meaning: "Harmony・Peace・Japanese style", rubyWord: "平{へい}和{わ}", wordMeaning: "Peace・Harmony" },
  "普": { kanji: "普", meaning: "Universal・General・Usual", rubyWord: "普{ふ}通{つう}", wordMeaning: "ordinary・common" },
  "段": { kanji: "段", meaning: "Step・Level", rubyWord: "階{かい}段{だん}", wordMeaning: "stairs" },
  "姿": { kanji: "姿", meaning: "Figure・Appearance・Form", rubyWord: "姿{すがた}", wordMeaning: "figure・appearance" },
  "勢": { kanji: "勢", meaning: "Force・Energy・Vigor", rubyWord: "勢{いきお}い", wordMeaning: "force・energy" },
  "玄": { kanji: "玄", meaning: "Mysterious・Deep・Dark", rubyWord: "玄{げん}関{かん}", wordMeaning: "entrance", wordSentence: "玄関で靴を脱ぐ" },
  "履": { kanji: "履", meaning: "Wear (on the feet)・Put on (shoes)", rubyWord: "履{は}く", wordMeaning: "to wear (shoes, pants, skirt)" },
  "差": { kanji: "差", meaning: "Difference・Distinction・Gap", rubyWord: "差{さ}す", wordMeaning: "to hold up・to put up", wordSentence: "傘を差す" },
  "遣": { kanji: "遣", meaning: "Send・Dispatch・Use", rubyWord: "派{は}遣{けん}", wordMeaning: "dispatch・temporary worker" },
  "機": { kanji: "機", meaning: "Machine・Opportunity・Aircraft", rubyWord: "飛{ひ}行{こう}機{き}", wordMeaning: "aircraft" },
  "破": { kanji: "破", meaning: "Break・Tear・Ruin", rubyWord: "破{やぶ}る", wordMeaning: "to break・to tear" },
  "微": { kanji: "微", meaning: "Subtle・Slight・tiny・Minute", rubyWord: "微{び}妙{みょう}", wordMeaning: "subtle・delicate" },
  "妙": { kanji: "妙", meaning: "Subtle・Strange・Excellent", rubyWord: "微{び}妙{みょう}", wordMeaning: "subtle・delicate" },
  "反": { kanji: "反", meaning: "Anti-・Oppose・Rebel・reverse", rubyWord: "反{はん}対{たい}", wordMeaning: "opposition" },
  "応": { kanji: "応", meaning: "Respond・Answer・Reaction", rubyWord: "応{おう}じる", wordMeaning: "to respond・to answer", wordSentence: "状況に応じて変える" },
  "解": { kanji: "解", meaning: "Untie・Solve・Understand", rubyWord: "解{と}く", wordMeaning: "to solve・to understand" },
  "凍": { kanji: "凍", meaning: "Freeze・Frozen", rubyWord: "凍{こお}る", wordMeaning: "to freeze" },
  "能": { kanji: "能", meaning: "Ability・Talent・function", rubyWord: "可{か}能{のう}", wordMeaning: "possible" },
  "圧": { kanji: "圧", meaning: "Pressure・Push・Overwhelm", rubyWord: "圧{あつ}力{りょく}", wordMeaning: "pressure" },
  "縮": { kanji: "縮", meaning: "Shrink・Contract・Shorten", rubyWord: "縮{ちぢ}む", wordMeaning: "to shrink", wordSentence: "服が縮んだ" },
  "軽": { kanji: "軽", meaning: "Light (weight)・Easy", rubyWord: "軽{かる}い", wordMeaning: "light (not heavy)", wordSentence: "荷物が軽い" },
  "革": { kanji: "革", meaning: "Leather・Reform", rubyWord: "革{かわ}", wordMeaning: "leather", wordSentence: "革のバッグ" },
  "命": { kanji: "命", meaning: "Life", rubyWord: "命{いのち}", wordMeaning: "life", wordSentence: "命は大切だ" },
  "経": { kanji: "経", meaning: "Pass・Manage・Experience", rubyWord: "経{けい}験{けん}", wordMeaning: "experience", wordSentence: "日本での経験" },
  "卓": { kanji: "卓", meaning: "Table・Outstanding", rubyWord: "食{しょく}卓{たく}", wordMeaning: "dining table", wordSentence: "食卓を囲む" },
  "省": { kanji: "省", meaning: "Reflect・Omit・Ministry", rubyWord: "反{はん}省{せい}する", wordMeaning: "to reflect on oneself", wordSentence: "失敗を反省する" },
  "駄": { kanji: "駄", meaning: "Useless・Waste", rubyWord: "無{む}駄{だ}", wordMeaning: "waste・useless", wordSentence: "時間の無駄だ" },
  "講": { kanji: "講", meaning: "Lecture・Explain", rubyWord: "講{こう}座{ざ}", wordMeaning: "course・lecture", wordSentence: "日本語講座を受ける" },
  "消": { kanji: "消", meaning: "Erase・Extinguish", rubyWord: "消{け}す", wordMeaning: "to erase・to turn off", wordSentence: "電気を消す" },
  "変": { kanji: "変", meaning: "Change・Strange", rubyWord: "変{か}える", wordMeaning: "to change", wordSentence: "設定を変える" },
  "換": { kanji: "換", meaning: "Exchange・Replace", rubyWord: "交{こう}換{かん}する", wordMeaning: "to exchange", wordSentence: "情報を交換する" },
  "課": { kanji: "課", meaning: "Section・Assignment", rubyWord: "課{か}題{だい}", wordMeaning: "assignment・task", wordSentence: "課題を出す" },
  "提": { kanji: "提", meaning: "Propose・Present", rubyWord: "提{てい}案{あん}する", wordMeaning: "to propose", wordSentence: "新しい案を提案する" },
  "投": { kanji: "投", meaning: "Throw・Submit", rubyWord: "投{とう}稿{こう}する", wordMeaning: "to post・submit", wordSentence: "記事を投稿する" },
  "稿": { kanji: "稿", meaning: "Manuscript・Draft", rubyWord: "原{げん}稿{こう}", wordMeaning: "manuscript・draft", wordSentence: "原稿を書く" },
  "不": { kanji: "不", meaning: "Not・Negative", rubyWord: "不{ふ}安{あん}", wordMeaning: "anxiety・uneasy", wordSentence: "将来が不安だ" },
  "運": { kanji: "運", meaning: "Luck・Carry", rubyWord: "運{うん}", wordMeaning: "luck", wordSentence: "運がいい" },
  "司": { kanji: "司", meaning: "Director・Control", rubyWord: "司{し}会{かい}", wordMeaning: "host・moderator", wordSentence: "司会をする" },
  "器": { kanji: "器", meaning: "Container・Device・Ability", rubyWord: "電{でん}気{き}機{き}器{き}", wordMeaning: "electrical appliance", wordSentence: "電気機器を使う" },
  "壊": { kanji: "壊", meaning: "Break", rubyWord: "壊{こわ}れる", wordMeaning: "to break", wordSentence: "パソコンが壊れた" },
  "対": { kanji: "対", meaning: "Opposite・Against", rubyWord: "対{たい}象{しょう}", wordMeaning: "target・subject", wordSentence: "子供が対象だ" },
  "象": { kanji: "象", meaning: "Image・Phenomenon", rubyWord: "現{げん}象{しょう}", wordMeaning: "phenomenon", wordSentence: "不思議な現象だ" },
  "編": { kanji: "編", meaning: "Compile・Edit", rubyWord: "編{へん}集{しゅう}", wordMeaning: "editing・compilation", wordSentence: "動画を編集する" },
  "集": { kanji: "集", meaning: "Gather・Collect", rubyWord: "集{あつ}める", wordMeaning: "to gather・collect", wordSentence: "情報を集める" },
  "共": { kanji: "共", meaning: "Together・Both", rubyWord: "共{きょう}有{ゆう}する", wordMeaning: "to share", wordSentence: "ファイルを共有する" },
  "有": { kanji: "有", meaning: "Have・Exist", rubyWord: "有{ゆう}名{めい}", wordMeaning: "famous", wordSentence: "有名な人だ" },
  "修": { kanji: "修", meaning: "Fix・Repair・Study", rubyWord: "修{しゅう}正{せい}する", wordMeaning: "to correct・fix", wordSentence: "ミスを修正する" },
  "正": { kanji: "正", meaning: "Correct・Right", rubyWord: "正{ただ}しい", wordMeaning: "correct・right", wordSentence: "答えが正しい" },
  "及": { kanji: "及", meaning: "Reach・Extend", rubyWord: "普{ふ}及{きゅう}", wordMeaning: "to spread・become widespread", wordSentence: "スマホが普及している" },
  "探": { kanji: "探", meaning: "Search・Look for", rubyWord: "探{さが}す", wordMeaning: "to search・look for", wordSentence: "鍵を探す" },
  "占": { kanji: "占", meaning: "Fortune・Occupy", rubyWord: "占{うらな}う", wordMeaning: "to tell fortune", wordSentence: "未来を占う" },
  "需": { kanji: "需", meaning: "Demand", rubyWord: "需{じゅ}要{よう}", wordMeaning: "demand", wordSentence: "需要が高い" },
  "齢": { kanji: "齢", meaning: "Age", rubyWord: "年{ねん}齢{れい}", wordMeaning: "age", wordSentence: "年齢を確認する" },
  "別": { kanji: "別", meaning: "Separate・Different", rubyWord: "別{べつ}", wordMeaning: "separate・different", wordSentence: "別の日に行く" },
  "率": { kanji: "率", meaning: "Rate・Ratio", rubyWord: "確{かく}率{りつ}", wordMeaning: "probability", wordSentence: "確率が高い" },
  "旦": { kanji: "旦", meaning: "Morning・Once", rubyWord: "一{いっ}旦{たん}", wordMeaning: "once・for now", wordSentence: "一旦停止する" },
  "保": { kanji: "保", meaning: "Protect・Keep", rubyWord: "保{ほ}証{しょう}", wordMeaning: "guarantee", wordSentence: "保証がある" },
  "証": { kanji: "証", meaning: "Proof・Evidence", rubyWord: "証{しょう}明{めい}", wordMeaning: "proof・verification", wordSentence: "身分を証明する" },
  "具": { kanji: "具", meaning: "Tool・Means", rubyWord: "具{ぐ}体{たい}的{てき}", wordMeaning: "concrete・specific", wordSentence: "具体的に説明する" },
  "合": { kanji: "合", meaning: "Fit・Combine", rubyWord: "合{あ}う", wordMeaning: "to fit・match", wordSentence: "サイズが合う" },
  "舗": { kanji: "舗", meaning: "Shop・Store", rubyWord: "店{てん}舗{ぽ}", wordMeaning: "shop・store", wordSentence: "新しい店舗ができた" },
  "採": { kanji: "採", meaning: "Adopt・Pick", rubyWord: "採{さい}用{よう}する", wordMeaning: "to hire・adopt", wordSentence: "新しい社員を採用する" },
  "成": { kanji: "成", meaning: "Become・Achieve", rubyWord: "作{さく}成{せい}する", wordMeaning: "to create", wordSentence: "資料を作成する" },
  "改": { kanji: "改", meaning: "Change・Reform", rubyWord: "改{かい}善{ぜん}する", wordMeaning: "to improve", wordSentence: "サービスを改善する" },
  "挿": { kanji: "挿", meaning: "Insert", rubyWord: "挿{そう}入{にゅう}する", wordMeaning: "to insert", wordSentence: "画像を挿入する" },
  "削": { kanji: "削", meaning: "Delete・Cut", rubyWord: "削{さく}除{じょ}する", wordMeaning: "to delete", wordSentence: "データを削除する" },
  "除": { kanji: "除", meaning: "Remove・Exclude", rubyWord: "取{と}り除{のぞ}く", wordMeaning: "to remove", wordSentence: "不要な部分を取り除く" },
  "更": { kanji: "更", meaning: "Change・Renew", rubyWord: "変{へん}更{こう}する", wordMeaning: "to change", wordSentence: "設定を変更する" },
  "設": { kanji: "設", meaning: "Set・Establish", rubyWord: "設{せっ}定{てい}する", wordMeaning: "to set・configure", wordSentence: "アプリを設定する" },
  "映": { kanji: "映", meaning: "Reflect・Project", rubyWord: "映{えい}画{が}", wordMeaning: "movie", wordSentence: "映画を見る" },
  "再": { kanji: "再", meaning: "Again・Re", rubyWord: "再{さい}起{き}動{どう}", wordMeaning: "to restart", wordSentence: "パソコンを再起動する" },
  "起": { kanji: "起", meaning: "Wake・Rise", rubyWord: "起{お}きる", wordMeaning: "to wake up", wordSentence: "朝早く起きる" },
  "動": { kanji: "動", meaning: "Move", rubyWord: "動{うご}く", wordMeaning: "to move", wordSentence: "機械が動く" },
  "優": { kanji: "優", meaning: "Kind・Excellent", rubyWord: "優{やさ}しい", wordMeaning: "kind・gentle", wordSentence: "彼は優しい人だ" },
  "否": { kanji: "否", meaning: "Deny・No", rubyWord: "否{ひ}定{てい}する", wordMeaning: "to deny", wordSentence: "意見を否定する" },
  "配": { kanji: "配", meaning: "Distribute・Arrange", rubyWord: "配{はい}達{たつ}", wordMeaning: "delivery", wordSentence: "荷物を配達する" },
  "超": { kanji: "超", meaning: "Super・Exceed", rubyWord: "超{ちょう}", wordMeaning: "super・very", wordSentence: "超便利だ" },
  "類": { kanji: "類", meaning: "Type・Kind", rubyWord: "種{しゅ}類{るい}", wordMeaning: "type・kind", wordSentence: "いろいろな種類がある" },
  "添": { kanji: "添", meaning: "Attach・Add", rubyWord: "添{てん}付{ぷ}する", wordMeaning: "to attach", wordSentence: "ファイルを添付する" },
  "付": { kanji: "付", meaning: "Attach・Add", rubyWord: "付{つ}ける", wordMeaning: "to attach・add", wordSentence: "名前を付ける" },
  "量": { kanji: "量", meaning: "Amount・Quantity", rubyWord: "容{よう}量{りょう}", wordMeaning: "capacity", wordSentence: "容量が大きい" },
  "過": { kanji: "過", meaning: "Exceed・Pass", rubyWord: "過{す}ぎる", wordMeaning: "to exceed", wordSentence: "時間が過ぎる" },
  "未": { kanji: "未", meaning: "Not yet", rubyWord: "未{み}満{まん}", wordMeaning: "less than", wordSentence: "18歳未満は不可" },
  "宅": { kanji: "宅", meaning: "Home・House", rubyWord: "自{じ}宅{たく}", wordMeaning: "home", wordSentence: "自宅で仕事する" },
  "親": { kanji: "親", meaning: "Parent・Close", rubyWord: "親{おや}", wordMeaning: "parent", wordSentence: "親に電話する" },
  "頼": { kanji: "頼", meaning: "Rely・Request", rubyWord: "頼{たの}む", wordMeaning: "to ask・request", wordSentence: "友達に頼む" },
  "用": { kanji: "用", meaning: "Use・Purpose", rubyWord: "用{よう}途{と}", wordMeaning: "use・purpose", wordSentence: "用途を確認する" },
  "途": { kanji: "途", meaning: "Way・Route", rubyWord: "途{と}中{ちゅう}", wordMeaning: "on the way", wordSentence: "途中で止まる" },
  "部": { kanji: "部", meaning: "Part・Section", rubyWord: "部{ぶ}分{ぶん}", wordMeaning: "part", wordSentence: "この部分を見る" },
  "接": { kanji: "接", meaning: "Connect・Touch", rubyWord: "接{せつ}続{ぞく}する", wordMeaning: "to connect", wordSentence: "Wi-Fiに接続する" },
  "続": { kanji: "続", meaning: "Continue・Connect", rubyWord: "続{つづ}ける", wordMeaning: "to continue", wordSentence: "勉強を続ける" },
  "劣": { kanji: "劣", meaning: "Inferior", rubyWord: "劣{れっ}化{か}", wordMeaning: "deterioration", wordSentence: "品質が劣化する" },
  "適": { kanji: "適", meaning: "Suitable・Fit", rubyWord: "適{てき}切{せつ}", wordMeaning: "appropriate", wordSentence: "適切な対応をする" },
  "拡": { kanji: "拡", meaning: "Expand", rubyWord: "拡{かく}張{ちょう}する", wordMeaning: "to expand", wordSentence: "機能を拡張する" },
  "張": { kanji: "張", meaning: "Stretch・Expand", rubyWord: "張{は}る", wordMeaning: "to stretch・stick", wordSentence: "ポスターを張る" },
  "相": { kanji: "相", meaning: "Mutual・Phase", rubyWord: "相{そう}互{ご}", wordMeaning: "mutual", wordSentence: "相互に影響する" },
  "互": { kanji: "互", meaning: "Mutual・Each other", rubyWord: "互{たが}いに", wordMeaning: "each other", wordSentence: "互いに助け合う" },
  "許": { kanji: "許", meaning: "Permit・Allow", rubyWord: "許{ゆる}す", wordMeaning: "to forgive・allow" },
  "可": { kanji: "可", meaning: "Possible・Allow", rubyWord: "可{か}能{のう}", wordMeaning: "possible", wordSentence: "利用が可能だ" },
  "華": { kanji: "華", meaning: "Splendor・Flower・Gorgeous", rubyWord: "華{はな}やか", wordMeaning: "gorgeous・showy", wordSentence: "華やかな雰囲気だ" },
  "契": { kanji: "契", meaning: "Contract・Pledge", rubyWord: "契{けい}約{やく}する", wordMeaning: "to sign a contract", wordSentence: "会社と契約する" },
  "約": { kanji: "約", meaning: "Promise・Approximate", rubyWord: "約{やく}束{そく}", wordMeaning: "promise", wordSentence: "約束を守る" },
  "工": { kanji: "工", meaning: "Craft・Work", rubyWord: "工{く}夫{ふう}する", wordMeaning: "to devise・come up with ideas", wordSentence: "料理を工夫する" },
  "底": { kanji: "底", meaning: "Bottom・Base", rubyWord: "底{そこ}", wordMeaning: "bottom", wordSentence: "箱の底を見る" },
  "側": { kanji: "側", meaning: "Side", rubyWord: "内{うち}側{がわ}", wordMeaning: "inside", wordSentence: "内側を見る" },
  "逃": { kanji: "逃", meaning: "Escape", rubyWord: "逃{に}げる", wordMeaning: "to escape", wordSentence: "すぐ逃げる" },
  "構": { kanji: "構", meaning: "Structure・Build", rubyWord: "構{こう}造{ぞう}", wordMeaning: "structure", wordSentence: "建物の構造" },
  "造": { kanji: "造", meaning: "Build・Make", rubyWord: "製{せい}造{ぞう}", wordMeaning: "manufacturing", wordSentence: "工場で製造する" },
  "発": { kanji: "発", meaning: "Emit・Start", rubyWord: "発{はつ}熱{ねつ}", wordMeaning: "heat generation", wordSentence: "発熱が起きる" },
  "熱": { kanji: "熱", meaning: "Heat", rubyWord: "熱{ねつ}", wordMeaning: "heat・fever", wordSentence: "熱がある" },
  "処": { kanji: "処", meaning: "Process・Deal", rubyWord: "処{しょ}理{り}する", wordMeaning: "to process", wordSentence: "データを処理する" },
  "速": { kanji: "速", meaning: "Fast", rubyWord: "速{はや}い", wordMeaning: "fast", wordSentence: "動きが速い" },
  "風": { kanji: "風", meaning: "Wind・Style", rubyWord: "風{ふう}景{けい}", wordMeaning: "scenery", wordSentence: "きれいな風景だ" },
  "景": { kanji: "景", meaning: "Scenery・View", rubyWord: "風{ふう}景{けい}", wordMeaning: "scenery", wordSentence: "風景を楽しむ" },
  "像": { kanji: "像", meaning: "Image・Figure", rubyWord: "映{えい}像{ぞう}", wordMeaning: "image・video", wordSentence: "映像を見る" },
  "焦": { kanji: "焦", meaning: "Burn", rubyWord: "焦{あせ}る", wordMeaning: "to panic・be in a hurry", wordSentence: "時間がなくて焦る" },
  "易": { kanji: "易", meaning: "Easy", rubyWord: "易{やさ}しい", wordMeaning: "easy", wordSentence: "この問題は易しい" },
  "加": { kanji: "加", meaning: "Add", rubyWord: "加{か}工{こう}する", wordMeaning: "to process・modify", wordSentence: "画像を加工する" },
  "盛": { kanji: "盛", meaning: "Prosper・Serve (food)", rubyWord: "盛{も}る", wordMeaning: "to serve (food)・pile up", wordSentence: "ご飯を盛る" },
  "援": { kanji: "援", meaning: "Help・Assist", rubyWord: "応{おう}援{えん}する", wordMeaning: "to support・cheer", wordSentence: "チームを応援する" },
  "化": { kanji: "化", meaning: "Change・Transform", rubyWord: "変化", wordMeaning: "change・transformation", wordSentence: "変化が起こる" },
  "粧": { kanji: "粧", meaning: "Makeup・Adornment", rubyWord: "化{け}粧{しょう}", wordMeaning: "makeup", wordSentence: "毎日化粧する" },
  "活": { kanji: "活", meaning: "Active・Life", rubyWord: "生{せい}活{かつ}", wordMeaning: "daily life", wordSentence: "日本で生活する" },
  "記": { kanji: "記", meaning: "Record・Write", rubyWord: "日{にっ}記{き}", wordMeaning: "diary", wordSentence: "毎日日記を書く" },
  "号": { kanji: "号", meaning: "Number・Symbol", rubyWord: "番{ばん}号{ごう}", wordMeaning: "number", wordSentence: "番号を書く" },
  "印": { kanji: "印", meaning: "Mark・Stamp", rubyWord: "印{いん}刷{さつ}", wordMeaning: "to print", wordSentence: "資料を印刷する" },
  "刷": { kanji: "刷", meaning: "Print", rubyWord: "印{いん}刷{さつ}", wordMeaning: "printing", wordSentence: "印刷が終わる" },
  "報": { kanji: "報", meaning: "Report・Inform", rubyWord: "報{ほう}告{こく}", wordMeaning: "to report", wordSentence: "上司に報告する" },
  "沿": { kanji: "沿", meaning: "Along", rubyWord: "沿{そ}う", wordMeaning: "to follow・along", wordSentence: "ルールに沿う" },
  "顧": { kanji: "顧", meaning: "Look back・Customer", rubyWord: "顧{こ}客{きゃく}", wordMeaning: "customer", wordSentence: "顧客を大切にする" },
  "候": { kanji: "候", meaning: "Season・Condition", rubyWord: "候{こう}補{ほ}", wordMeaning: "candidate", wordSentence: "候補を選ぶ" },
  "補": { kanji: "補", meaning: "Supplement・Assist", rubyWord: "補{ほ}足{そく}", wordMeaning: "supplement・addition", wordSentence: "説明を補足する" },
  "案": { kanji: "案", meaning: "Plan・Idea", rubyWord: "案{あん}内{ない}", wordMeaning: "guidance", wordSentence: "道を案内する" },
  "析": { kanji: "析", meaning: "Analyze", rubyWord: "分{ぶん}析{せき}", wordMeaning: "analysis", wordSentence: "データを分析する" },
  "略": { kanji: "略", meaning: "Abbreviate・Omit", rubyWord: "省{しょう}略{りゃく}", wordMeaning: "to omit・abbreviate", wordSentence: "説明を省略する" },
  "太": { kanji: "太", meaning: "Thick・Fat", rubyWord: "太{ふと}い", wordMeaning: "thick", wordSentence: "この線は太い" },
  "鼓": { kanji: "鼓", meaning: "Drum", rubyWord: "太{たい}鼓{こ}", wordMeaning: "drum", wordSentence: "太鼓をたたく" },
  "詰": { kanji: "詰", meaning: "Stuff・Pack・Corner", rubyWord: "詰{つ}める", wordMeaning: "to pack・stuff", wordSentence: "荷物を詰める" },
  "武": { kanji: "武", meaning: "Warrior・Military", rubyWord: "武{ぶ}器{き}", wordMeaning: "weapon", wordSentence: "武器を使う" },
  "卑": { kanji: "卑", meaning: "Mean・Low", rubyWord: "卑{ひ}怯{きょう}", wordMeaning: "cowardly・mean", wordSentence: "卑怯なやり方だ" },
  "怯": { kanji: "怯", meaning: "Fear", rubyWord: "怯{おび}える", wordMeaning: "to be afraid", wordSentence: "音に怯える" },
  "攻": { kanji: "攻", meaning: "Attack", rubyWord: "攻{こう}撃{げき}", wordMeaning: "attack", wordSentence: "敵を攻撃する" },
  "撃": { kanji: "撃", meaning: "Strike・Attack", rubyWord: "攻{こう}撃{げき}", wordMeaning: "attack", wordSentence: "攻撃を受ける" },
  "斬": { kanji: "斬", meaning: "Cut・Slash", rubyWord: "斬{き}る", wordMeaning: "to cut・slash", wordSentence: "刀で斬る" },
  "素": { kanji: "素", meaning: "Plain・Basic", rubyWord: "素{す}敵{てき}", wordMeaning: "lovely・nice", wordSentence: "素敵な人だ" },
  "公": { kanji: "公", meaning: "Public・Official", rubyWord: "公{こう}園{えん}", wordMeaning: "park", wordSentence: "公園で遊ぶ" },
  "味": { kanji: "味", meaning: "Taste・Flavor", rubyWord: "味{あじ}", wordMeaning: "taste", wordSentence: "味がいい" },
  "仲": { kanji: "仲", meaning: "Relationship・Companion", rubyWord: "仲{なか}間{ま}", wordMeaning: "companion・friend", wordSentence: "仲間と話す" },
  "間": { kanji: "間", meaning: "Interval・Space", rubyWord: "時{じ}間{かん}", wordMeaning: "time", wordSentence: "時間がない" },
  "勇": { kanji: "勇", meaning: "Brave・Courage", rubyWord: "勇{ゆう}気{き}", wordMeaning: "courage", wordSentence: "勇気を出す" },
  "登": { kanji: "登", meaning: "Climb・Appear", rubyWord: "登{とう}場{じょう}", wordMeaning: "to appear", wordSentence: "新キャラが登場する" },
  "場": { kanji: "場", meaning: "Place・Scene", rubyWord: "場{ば}所{しょ}", wordMeaning: "place", wordSentence: "場所を確認する" },
  "徴": { kanji: "徴", meaning: "Sign・Feature", rubyWord: "特{とく}徴{ちょう}", wordMeaning: "feature・characteristic", wordSentence: "特徴がはっきりしている" },
  "必": { kanji: "必", meaning: "Must・Certain", rubyWord: "必{ひっ}要{よう}", wordMeaning: "necessary", wordSentence: "準備が必要だ" },
  "殺": { kanji: "殺", meaning: "Kill", rubyWord: "殺{ころ}す", wordMeaning: "to kill", wordSentence: "敵を殺す" },
  "技": { kanji: "技", meaning: "Skill・Technique", rubyWord: "技{わざ}", wordMeaning: "skill・technique", wordSentence: "すごい技だ" },
  "叫": { kanji: "叫", meaning: "Shout", rubyWord: "叫{さけ}ぶ", wordMeaning: "to shout", wordSentence: "大声で叫ぶ" },
  "王": { kanji: "王", meaning: "King", rubyWord: "王{おう}", wordMeaning: "king", wordSentence: "王になる" },
  "争": { kanji: "争", meaning: "Fight・Dispute", rubyWord: "争{あらそ}う", wordMeaning: "to fight・to argue", wordSentence: "意見を争う" },
  "治": { kanji: "治", meaning: "Govern・Heal", rubyWord: "治{なお}す", wordMeaning: "to cure・fix", wordSentence: "病気を治す" },
  "古": { kanji: "古", meaning: "Old", rubyWord: "古{ふる}い", wordMeaning: "old", wordSentence: "古い建物だ" },
  "代": { kanji: "代", meaning: "Generation・Era", rubyWord: "時{じ}代{だい}", wordMeaning: "era・period", wordSentence: "古い時代の話だ" },
  "役": { kanji: "役", meaning: "Role・Duty", rubyWord: "役{やく}", wordMeaning: "role", wordSentence: "重要な役をする" },
  "演": { kanji: "演", meaning: "Perform・Act", rubyWord: "演{えん}じる", wordMeaning: "to act・perform", wordSentence: "ドラマで演じる" },
  "論": { kanji: "論", meaning: "Discuss・Theory", rubyWord: "評{ひょう}論{ろん}", wordMeaning: "criticism・review", wordSentence: "映画評論を読む" },
  "醜": { kanji: "醜", meaning: "Ugly", rubyWord: "醜{みにく}い", wordMeaning: "ugly", wordSentence: "醜い姿だ" },
  "者": { kanji: "者", meaning: "Person", rubyWord: "者{もの}", wordMeaning: "person", wordSentence: "強い者が勝つ" },
  "賛": { kanji: "賛", meaning: "Praise・Approve", rubyWord: "賛{さん}成{せい}", wordMeaning: "to agree・approve", wordSentence: "意見に賛成する" },
  "空": { kanji: "空", meaning: "Sky・Empty", rubyWord: "空{そら}", wordMeaning: "sky", wordSentence: "空を見上げる" },
  "想": { kanji: "想", meaning: "Think・Imagine", rubyWord: "想{そう}像{ぞう}", wordMeaning: "to imagine", wordSentence: "未来を想像する" },
  "幼": { kanji: "幼", meaning: "Young・Childish", rubyWord: "幼{おさな}い", wordMeaning: "young・childish", wordSentence: "まだ幼い子供だ" },
  "稚": { kanji: "稚", meaning: "Immature・Childish", rubyWord: "幼{よう}稚{ち}", wordMeaning: "childish・immature", wordSentence: "幼稚な考えだ" },
  "載": { kanji: "載", meaning: "Publish・Place", rubyWord: "載{の}せる", wordMeaning: "to publish・put", wordSentence: "記事を載せる" },
  "才": { kanji: "才", meaning: "Talent・Years old", rubyWord: "才{さい}", wordMeaning: "years old", wordSentence: "10才の子供だ" },
  "雑": { kanji: "雑", meaning: "Misc・Rough", rubyWord: "雑{ざつ}誌{し}", wordMeaning: "magazine", wordSentence: "雑誌を読む" },
  "誌": { kanji: "誌", meaning: "Magazine・Record", rubyWord: "日{にっ}誌{し}", wordMeaning: "journal・log", wordSentence: "日誌を書く" },
  "劇": { kanji: "劇", meaning: "Drama・Play", rubyWord: "演{えん}劇{げき}", wordMeaning: "theater・play", wordSentence: "演劇を見る" },
  "筋": { kanji: "筋", meaning: "Line・Plot", rubyWord: "粗{あら}筋{すじ}", wordMeaning: "outline・plot", wordSentence: "物語の粗筋を説明する" },
  "芝": { kanji: "芝", meaning: "Grass・Theater", rubyWord: "芝{しば}居{い}", wordMeaning: "play・acting", wordSentence: "芝居を見る" },
  "居": { kanji: "居", meaning: "Stay・Exist", rubyWord: "居{い}る", wordMeaning: "to be (animate)", wordSentence: "部屋にいる" },
  "異": { kanji: "異", meaning: "Different・Strange", rubyWord: "異{こと}なる", wordMeaning: "to differ", wordSentence: "文化が異なる" },
  "脅": { kanji: "脅", meaning: "Threaten", rubyWord: "脅{おど}す", wordMeaning: "to threaten", wordSentence: "相手を脅す" },
  "謎": { kanji: "謎", meaning: "Mystery", rubyWord: "謎{なぞ}", wordMeaning: "mystery", wordSentence: "謎を解く" },
  "開": { kanji: "開", meaning: "Open・Develop", rubyWord: "開{ひら}く", wordMeaning: "to open", wordSentence: "ドアを開く" },
  "議": { kanji: "議", meaning: "Discuss", rubyWord: "議{ぎ}論{ろん}", wordMeaning: "to discuss", wordSentence: "問題を議論する" },
  "刑": { kanji: "刑", meaning: "Punishment・Penalty", rubyWord: "刑{けい}", wordMeaning: "punishment", wordSentence: "重い刑を受ける" },
  "警": { kanji: "警", meaning: "Police・Warn", rubyWord: "警{けい}察{さつ}", wordMeaning: "police", wordSentence: "警察に連絡する" },
  "察": { kanji: "察", meaning: "Guess・Sense", rubyWord: "観{かん}察{さつ}", wordMeaning: "observation", wordSentence: "動物を観察する" },
  "説": { kanji: "説", meaning: "Explain・Theory", rubyWord: "説{せつ}明{めい}", wordMeaning: "to explain", wordSentence: "内容を説明する" },
  "当": { kanji: "当", meaning: "Hit・Apply", rubyWord: "当{あ}たる", wordMeaning: "to hit・to apply", wordSentence: "ボールが当たる" },
  "初": { kanji: "初", meaning: "First・Beginning", rubyWord: "初{はじ}め", wordMeaning: "beginning", wordSentence: "初めて行く" },
  "娯": { kanji: "娯", meaning: "Entertainment", rubyWord: "娯{ご}楽{らく}", wordMeaning: "entertainment", wordSentence: "娯楽が必要だ" },
  "偵": { kanji: "偵", meaning: "Spy・Detect", rubyWord: "探{たん}偵{てい}", wordMeaning: "detective", wordSentence: "探偵になる" },
  "宝": { kanji: "宝", meaning: "Treasure", rubyWord: "宝{たから}", wordMeaning: "treasure", wordSentence: "宝を見つける" },
  "却": { kanji: "却", meaning: "Return・Reject", rubyWord: "返{へん}却{きゃく}", wordMeaning: "to return (formal)", wordSentence: "商品を返却する" },
  "射": { kanji: "射", meaning: "Shoot", rubyWord: "射{い}る", wordMeaning: "to shoot", wordSentence: "矢を射る" },
  "職": { kanji: "職", meaning: "Job・Profession", rubyWord: "職{しょく}業{ぎょう}", wordMeaning: "profession", wordSentence: "職業を選ぶ" },
  "業": { kanji: "業", meaning: "Work・Business", rubyWord: "作{さ}業{ぎょう}", wordMeaning: "work・task", wordSentence: "作業を始める" },
  "泥": { kanji: "泥", meaning: "Mud", rubyWord: "泥{どろ}", wordMeaning: "mud", wordSentence: "泥だらけになる" },
  "棒": { kanji: "棒", meaning: "Stick・Thief (slang)", rubyWord: "泥{どろ}棒{ぼう}", wordMeaning: "thief", wordSentence: "泥棒を捕まえる" },
  "盗": { kanji: "盗", meaning: "Steal", rubyWord: "盗{ぬす}む", wordMeaning: "to steal", wordSentence: "お金を盗む" },
  "翼": { kanji: "翼", meaning: "Wing", rubyWord: "翼{つばさ}", wordMeaning: "wing", wordSentence: "鳥の翼が大きい" },
  "奇": { kanji: "奇", meaning: "Strange・Odd", rubyWord: "奇{き}妙{みょう}", wordMeaning: "strange・mysterious", wordSentence: "奇妙な話だ" },
  "実": { kanji: "実", meaning: "Real・Truth", rubyWord: "実{じっ}際{さい}", wordMeaning: "actually・in reality", wordSentence: "実際は違う" },
  "鑑": { kanji: "鑑", meaning: "Judge・Appraise", rubyWord: "図{ず}鑑{かん}", wordMeaning: "illustrated book", wordSentence: "図鑑を見る" },
  "幽": { kanji: "幽", meaning: "Faint・Ghostly", rubyWord: "幽{ゆう}霊{れい}", wordMeaning: "ghost", wordSentence: "幽霊を見た" },
  "霊": { kanji: "霊", meaning: "Spirit・Ghost", rubyWord: "霊{れい}", wordMeaning: "spirit", wordSentence: "霊が現れる" },
  "恐": { kanji: "恐", meaning: "Fear", rubyWord: "恐{おそ}れる", wordMeaning: "to fear", wordSentence: "失敗を恐れる" },
  "怖": { kanji: "怖", meaning: "Fear", rubyWord: "怖{こわ}い", wordMeaning: "scary", wordSentence: "とても怖い話だ" },
  "驚": { kanji: "驚", meaning: "Surprise", rubyWord: "驚{おどろ}く", wordMeaning: "to be surprised", wordSentence: "結果に驚く" },
  "推": { kanji: "推", meaning: "Recommend・Support", rubyWord: "推{お}し", wordMeaning: "favorite・one you support", wordSentence: "推しを応援する" },
  "魔": { kanji: "魔", meaning: "Demon・Magic", rubyWord: "魔{ま}法{ほう}", wordMeaning: "magic", wordSentence: "魔法を使う" },
  "法": { kanji: "法", meaning: "Method・Law", rubyWord: "方{ほう}法{ほう}", wordMeaning: "method", wordSentence: "いい方法を考える" },
  "冒": { kanji: "冒", meaning: "Risk・Dare", rubyWord: "冒{ぼう}険{けん}", wordMeaning: "adventure", wordSentence: "冒険に出る" },
  "険": { kanji: "険", meaning: "Dangerous", rubyWord: "険{けわ}しい", wordMeaning: "steep・dangerous", wordSentence: "険しい山道だ" },
  "徹": { kanji: "徹", meaning: "Thorough・All night", rubyWord: "徹{てつ}夜{や}", wordMeaning: "all night", wordSentence: "徹夜で勉強する" },
  "夜": { kanji: "夜", meaning: "Night", rubyWord: "夜{よる}", wordMeaning: "night", wordSentence: "夜に出かける" },
  "剣": { kanji: "剣", meaning: "Sword", rubyWord: "剣{けん}", wordMeaning: "sword", wordSentence: "剣を使う" },
  "請": { kanji: "請", meaning: "Request", rubyWord: "請{せい}求{きゅう}", wordMeaning: "to request・claim", wordSentence: "料金を請求する" },
  "求": { kanji: "求", meaning: "Seek・Request", rubyWord: "求{もと}める", wordMeaning: "to seek・request", wordSentence: "助けを求める" },
  "晝": { kanji: "晝", meaning: "Daytime", rubyWord: "晝{ひる}", wordMeaning: "daytime", wordSentence: "晝に出かける" },
  "端": { kanji: "端", meaning: "Edge・End", rubyWord: "端{はし}", wordMeaning: "edge・end", wordSentence: "机の端に置く" },
  "券": { kanji: "券", meaning: "Ticket", rubyWord: "券{けん}", wordMeaning: "ticket", wordSentence: "映画券を買う" },
  "式": { kanji: "式", meaning: "Style・Ceremony・Formula", rubyWord: "式{しき}", wordMeaning: "ceremony・style", wordSentence: "結婚式に出る" },
  "躍": { kanji: "躍", meaning: "Leap・Be active", rubyWord: "躍{おど}る", wordMeaning: "to dance・leap", wordSentence: "音楽に合わせて躍る" },
  "貼": { kanji: "貼", meaning: "Stick・Paste", rubyWord: "貼{は}る", wordMeaning: "to stick・paste", wordSentence: "ポスターを貼る" },
  "泉": { kanji: "泉", meaning: "Spring・Fountain", rubyWord: "温{おん}泉{せん}", wordMeaning: "hot spring", wordSentence: "温泉に入る" },
  "復": { kanji: "復", meaning: "Restore・Return", rubyWord: "復{ふく}習{しゅう}", wordMeaning: "Review", wordSentence: "毎日復習する" },
  "視": { kanji: "視", meaning: "Look・View", rubyWord: "視{み}る", wordMeaning: "to look", wordSentence: "画面を視る" },
  "告": { kanji: "告", meaning: "Inform・Announce", rubyWord: "告{つ}げる", wordMeaning: "to inform", wordSentence: "結果を告げる" },
  "医": { kanji: "医", meaning: "Medical", rubyWord: "医{い}者{しゃ}", wordMeaning: "doctor", wordSentence: "医者に行く" },
  "芸": { kanji: "芸", meaning: "Art・Performance", rubyWord: "芸{げい}術{じゅつ}", wordMeaning: "art", wordSentence: "芸術が好きだ" },
  "薦": { kanji: "薦", meaning: "Recommend", rubyWord: "薦{すす}める", wordMeaning: "to recommend", wordSentence: "この本を薦める" },
  "務": { kanji: "務", meaning: "Duty・Task", rubyWord: "務{つと}める", wordMeaning: "to serve・work", wordSentence: "会社で務める" },
  "抽": { kanji: "抽", meaning: "Lottery・Extract", rubyWord: "抽{ちゅう}選{せん}", wordMeaning: "lottery・drawing", wordSentence: "抽選に当たる" },
  "選": { kanji: "選", meaning: "Choose・Select", rubyWord: "選{えら}ぶ", wordMeaning: "to choose", wordSentence: "好きな色を選ぶ" },
  "神": { kanji: "神", meaning: "God・Spirit", rubyWord: "神{かみ}", wordMeaning: "god", wordSentence: "神を信じる" },
  "話": { kanji: "話", meaning: "Talk・Story", rubyWord: "話{はな}す", wordMeaning: "to talk", wordSentence: "友達と話す" },
  "架": { kanji: "架", meaning: "Build", rubyWord: "架{か}空{くう}", wordMeaning: "fictional", wordSentence: "架空の物語だ" },
  "教": { kanji: "教", meaning: "Teach", rubyWord: "教{おし}える", wordMeaning: "to teach", wordSentence: "日本語を教える" },
  "激": { kanji: "激", meaning: "Intense・Violent", rubyWord: "激{はげ}しい", wordMeaning: "intense・fierce", wordSentence: "雨が激しい" },
  "裏": { kanji: "裏", meaning: "Back・Reverse", rubyWord: "裏{うら}切{ぎ}る", wordMeaning: "to betray", wordSentence: "仲間を裏切る" },
  "切": { kanji: "切", meaning: "Cut", rubyWord: "切{き}る", wordMeaning: "to cut", wordSentence: "紙を切る" },
  "常": { kanji: "常", meaning: "Normal・Usual", rubyWord: "常{つね}", wordMeaning: "usual・always", wordSentence: "常に考える" },
  "広": { kanji: "広", meaning: "Wide・Spread", rubyWord: "広{ひろ}がる", wordMeaning: "to spread", wordSentence: "景色が広がる" },
  "存": { kanji: "存", meaning: "Exist", rubyWord: "存{そん}在{ざい}", wordMeaning: "existence", wordSentence: "その問題は存在する" },
  "在": { kanji: "在", meaning: "Exist・Be present", rubyWord: "在{あ}る", wordMeaning: "to exist (inanimate)", wordSentence: "机の上に本が在る" },
  "利": { kanji: "利", meaning: "Advantage・Benefit", rubyWord: "利{り}用{よう}", wordMeaning: "to use", wordSentence: "サービスを利用する" },
  "進": { kanji: "進", meaning: "Advance", rubyWord: "進{すす}む", wordMeaning: "to advance", wordSentence: "前に進む" },
  "重": { kanji: "重", meaning: "Heavy", rubyWord: "重{おも}い", wordMeaning: "heavy", wordSentence: "荷物が重い" },
  "備": { kanji: "備", meaning: "Prepare・Equip", rubyWord: "備{そな}える", wordMeaning: "to prepare", wordSentence: "災害に備える" },
  "移": { kanji: "移", meaning: "Move", rubyWord: "移{うつ}る", wordMeaning: "to move・transfer", wordSentence: "画面が移る" },
  "魅": { kanji: "魅", meaning: "Charm", rubyWord: "魅{み}力{りょく}", wordMeaning: "charm・attraction", wordSentence: "この街の魅力" },
  "永": { kanji: "永", meaning: "Eternal", rubyWord: "永{えい}遠{えん}", wordMeaning: "eternity", wordSentence: "永遠に続く" },
  "遠": { kanji: "遠", meaning: "Far", rubyWord: "遠{とお}い", wordMeaning: "far", wordSentence: "駅が遠い" },
  "順": { kanji: "順", meaning: "Order", rubyWord: "順{じゅん}番{ばん}", wordMeaning: "turn・order", wordSentence: "順序を守る" },
  "序": { kanji: "序", meaning: "Order・Beginning", rubyWord: "序{じょ}盤{ばん}", wordMeaning: "early stage", wordSentence: "序盤は簡単だ" },
  "影": { kanji: "影", meaning: "Shadow・Influence", rubyWord: "影{かげ}", wordMeaning: "shadow", wordSentence: "影が伸びる" },
  "響": { kanji: "響", meaning: "Echo・Affect", rubyWord: "響{ひび}く", wordMeaning: "to echo・to affect", wordSentence: "心に響く" },
  "帝": { kanji: "帝", meaning: "Emperor", rubyWord: "皇{こう}帝{てい}", wordMeaning: "emperor", wordSentence: "皇帝になる" },
  "民": { kanji: "民", meaning: "People・Nation", rubyWord: "国{こく}民{みん}", wordMeaning: "citizens", wordSentence: "国民が集まる" },
  "族": { kanji: "族", meaning: "Tribe・Family", rubyWord: "家{か}族{ぞく}", wordMeaning: "family", wordSentence: "家族と過ごす" },
}