export const KANJI_YDC_LESSON_8: Array<KanjiYDC> = [
  {
    kanji: '休',
    onyomi: ['きゅう'],
    kunyomi: ['やす'],
    meaning: ['To Rest'],
    examples: [
      {
        reading: '休む',
        kana: 'やすむ',
        meaning: ['To rest', 'To be absent'],
        sentence: '休んでください。',
        type: 'main',
      },
      {
        reading: '休み',
        kana: 'やすみ',
        meaning: ['Absense', 'Holiday'],
        sentence: '休みが欲しいです。',
        type: 'main',
      },
      {
        reading: '夏休み',
        kana: 'なつやすみ',
        meaning: ['Summer vacation'],
        sentence: '夏休みに日本に行きます。',
        type: 'secondary',
      },
      {
        reading: '昼休み',
        kana: 'ひるやすみ',
        meaning: ['Lunch break'],
        sentence: '昼休みに日本語を勉強します。',
        type: 'secondary',
      },
      {
        reading: '休日',
        kana: 'きゅうじつ',
        meaning: ['Holiday'],
        sentence: '休日に日本語を勉強します。',
        type: 'secondary',
      },
      {
        reading: '休講',
        kana: 'きゅうこう',
        meaning: ['Class cancellation'],
        sentence: '休講になりました。',
        type: 'secondary',
      },
      {
        reading: '定休日',
        kana: 'ていきゅうび',
        meaning: ['Holiday (of a store)'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '走',
    onyomi: ['そう'],
    kunyomi: ['はし'],
    meaning: ['To Run'],
    examples: [
      {
        reading: '走る',
        kana: 'はしる',
        meaning: ['To run'],
        sentence: '走ってください。',
        type: 'main',
      },
      {
        reading: 'ご馳走',
        kana: 'ごちそう',
        meaning: ['Feast', 'Treat'],
        sentence: 'ご馳走を食べます。',
        type: 'secondary',
      },
      {
        reading: '脱走',
        kana: 'だっそう',
        meaning: ['Escape (from prison)'],
        sentence: '脱走しました。',
        type: 'secondary',
      },
      {
        reading: '逃走',
        kana: 'とうそう',
        meaning: ['Run away'],
        sentence: '逃走しました。',
        type: 'secondary',
      },
      {
        reading: '走行',
        kana: 'そうこう',
        meaning: ['Running', 'Moving'],
        sentence: '走行中です。',
        type: 'secondary',
      },
      {
        reading: '暴走族',
        kana: 'ぼうそうぞく',
        meaning: ['Motorcycle gang'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '師走',
        kana: 'しわす',
        meaning: ['December'],
        sentence: '師走に日本に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '起',
    onyomi: ['き'],
    kunyomi: ['お'],
    meaning: ['To Get Up'],
    examples: [
      {
        reading: '起きる',
        kana: 'おきる',
        meaning: ['To get up'],
        sentence: '毎日７時に起きて朝ご飯を食べる。',
        type: 'main',
      },
      {
        reading: '起こす',
        kana: 'おこす',
        meaning: ['To wake someone up'],
        sentence: '母は私を起こしました。',
        type: 'main',
      },
      {
        reading: '起こる',
        kana: 'おこる',
        meaning: ['To happen'],
        sentence: '何が起こりましたか。',
        type: 'secondary',
      },
      {
        reading: '起立する',
        kana: 'きりつする',
        meaning: ['To stand up'],
        sentence: '起立してください。',
        type: 'secondary',
      },
      {
        reading: '起床',
        kana: 'きしょう',
        meaning: ['Wake up'],
        sentence: '起床しました。',
        type: 'secondary',
      },
      {
        reading: '起源',
        kana: 'きげん',
        meaning: ['Origin'],
        sentence: '起源を調べてください。',
        type: 'secondary',
      },
      {
        reading: '起業する',
        kana: 'きぎょうする',
        meaning: ['To start a business'],
        sentence: '起業しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '貝',
    onyomi: [],
    kunyomi: ['かい', 'がい'],
    meaning: ['Shellfish'],
    examples: [
      {
        reading: '貝',
        kana: 'かい',
        meaning: ['Shellfish'],
        sentence: '貝を食べます。',
        type: 'main',
      },
      {
        reading: '貝殻',
        kana: 'かいがら',
        meaning: ['Shell'],
        sentence: '貝殻を拾います。',
        type: 'secondary',
      },
      {
        reading: '巻貝',
        kana: 'まきがい',
        meaning: ['Spiral shell'],
        sentence: '巻貝を見つけました。',
        type: 'secondary',
      },
      {
        reading: '貝細工',
        kana: 'かいざいく',
        meaning: ['Shellwork'],
        sentence: '貝細工を作ります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '買',
    onyomi: ['ばい'],
    kunyomi: ['か'],
    meaning: ['To Buy'],
    examples: [
      {
        reading: '買う',
        kana: 'かう',
        meaning: ['To buy'],
        sentence: '何を買いましたか。',
        type: 'main',
      },
      {
        reading: '買い物',
        kana: 'かいもの',
        meaning: ['Shopping'],
        sentence: '買い物に行きます。',
        type: 'secondary',
      },
      {
        reading: '買い占める',
        kana: 'かいしめる',
        meaning: ['To buy all'],
        sentence: '買い占めました。',
        type: 'secondary',
      },
      {
        reading: '売買',
        kana: 'ばいばい',
        meaning: ['Buying and selling'],
        sentence: '売買があります。',
        type: 'secondary',
      },
      {
        reading: '買収する',
        kana: 'ばいしゅうする',
        meaning: ['To buy', 'To bribe'],
        sentence: '買収しました。',
        type: 'secondary',
      },
      {
        reading: '買い手',
        kana: 'かいて',
        meaning: ['Buyer'],
        sentence: 'あの方は買い手です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '売',
    onyomi: ['ばい'],
    kunyomi: ['う'],
    meaning: ['To Sell'],
    examples: [
      {
        reading: '売る',
        kana: 'うる',
        meaning: ['To sell'],
        sentence: '何を売りましたか。',
        type: 'main',
      },
      {
        reading: '売れる',
        kana: 'うれる',
        meaning: ['To be sold'],
        sentence: '売れました。',
        type: 'main',
      },
      {
        reading: '売り切れる',
        kana: 'うりきれる',
        meaning: ['To be sold out'],
        sentence: '売り切れました。',
        type: 'main',
      },
      {
        reading: '売り場',
        kana: 'うりば',
        meaning: ['Counter', 'Sales floor'],
        sentence: '大学に行きます。',
        type: 'secondary',
      },
      {
        reading: '売店',
        kana: 'ばいてん',
        meaning: ['Stand', 'Kiosk'],
        sentence: '売店があります。',
        type: 'secondary',
      },
      {
        reading: '自動販売機',
        kana: 'じどうはんばいき',
        meaning: ['Vending machine'],
        sentence: '自動販売機で買いました。',
        type: 'secondary',
      },
      {
        reading: '大売り出し',
        kana: 'おおうりだし',
        meaning: ['Big sale'],
        sentence: '大売り出しです。',
        type: 'secondary',
      },
      {
        reading: '商売',
        kana: 'しょうばい',
        meaning: ['Business', 'Trade'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '読',
    onyomi: ['どく', 'とく', 'とう'],
    kunyomi: ['よ'],
    meaning: ['To Read'],
    examples: [
      {
        reading: '読む',
        kana: 'よむ',
        meaning: ['To read'],
        sentence: '何を読みましたか。',
        type: 'main',
      },
      {
        reading: '読み物',
        kana: 'よみもの',
        meaning: ['Reading material'],
        sentence: '読み物があります。',
        type: 'secondary',
      },
      {
        reading: '読書',
        kana: 'どくしょ',
        meaning: ['Reading'],
        sentence: '読書が好きです。',
        type: 'secondary',
      },
      {
        reading: '読者',
        kana: 'どくしゃ',
        meaning: ['Reader'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '句読点',
        kana: 'くとうてん',
        meaning: ['Punctuation'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '愛読書',
        kana: 'あいどくしょ',
        meaning: ['Favorite book'],
        sentence: 'これは私の愛読書です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '書',
    onyomi: ['しょ'],
    kunyomi: ['か', 'が'],
    meaning: ['To Write'],
    examples: [
      {
        reading: '書く',
        kana: 'かく',
        meaning: ['To write'],
        sentence: '何を書きましたか。',
        type: 'main',
      },
      {
        reading: '図書館',
        kana: 'としょかん',
        meaning: ['Library'],
        sentence: '図書館に行きます。',
        type: 'secondary',
      },
      {
        reading: '辞書',
        kana: 'じしょ',
        meaning: ['Dictionary'],
        sentence: '辞書を使います。',
        type: 'secondary',
      },
      {
        reading: '教科書',
        kana: 'きょうかしょ',
        meaning: ['Textbook'],
        sentence: '教科書を使います。',
        type: 'secondary',
      },
      {
        reading: '読書',
        kana: 'どくしょ',
        meaning: ['Reading'],
        sentence: '読書が好きです。',
        type: 'secondary',
      },
      {
        reading: '書道',
        kana: 'しょどう',
        meaning: ['Calligraphy'],
        sentence: '書道を習います。',
        type: 'secondary',
      },
      {
        reading: '肩書き',
        kana: 'かたがき',
        meaning: ['Title', 'Degree'],
        sentence: '肩書きを教えてください。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '帰',
    onyomi: ['き'],
    kunyomi: ['かえ', 'がえ'],
    meaning: ['To Return'],
    examples: [
      {
        reading: '帰る',
        kana: 'かえる',
        meaning: ['To return'],
        sentence: '何時に帰りますか。',
        type: 'main',
      },
      {
        reading: '帰国',
        kana: 'きこく',
        meaning: ['Return to one\'s home country'],
        sentence: '帰国しました。',
        type: 'secondary',
      },
      {
        reading: '帰り',
        kana: 'かえり',
        meaning: ['Return'],
        sentence: '帰りが遅いです。',
        type: 'secondary',
      },
      {
        reading: '行き帰り',
        kana: 'いきかえり',
        meaning: ['Round trip'],
        sentence: '行き帰りがあります。',
        type: 'secondary',
      },
      {
        reading: '日帰り旅行',
        kana: 'ひがえりりょこう',
        meaning: ['Day trip'],
        sentence: '日帰り旅行に行きます。',
        type: 'secondary',
      },
      {
        reading: '帰宅',
        kana: 'きたく',
        meaning: ['Return home'],
        sentence: '帰宅しました。',
        type: 'secondary',
      },
      {
        reading: '帰化',
        kana: 'きか',
        meaning: ['Naturalization'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '勉',
    onyomi: ['べん'],
    kunyomi: [],
    meaning: ['To make efforts'],
    examples: [ 
      {
        reading: '勉強する',
        kana: 'べんきょうする',
        meaning: ['To study'],
        sentence: '勉強してください。',
        type: 'main',
      },
      {
        reading: '勤勉な',
        kana: 'きんべんな',
        meaning: ['Diligent'],
        sentence: '勤勉な学生です。',
        type: 'secondary',
      },
      {
        reading: '勉学',
        kana: 'べんがく',
        meaning: ['Study (hard)'],
        sentence: '勉学が大変です。 (もっともっと勉強する)',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '弓',
    onyomi: ['きゅう'],
    kunyomi: ['ゆみ'],
    meaning: ['Bow'],
    examples: [
      {
        reading: '弓',
        kana: 'ゆみ',
        meaning: ['Bow'],
        sentence: '弓を使います。',
        type: 'secondary',
      },
      {
        reading: '弓矢',
        kana: 'ゆみや',
        meaning: ['Bow and arrow'],
        sentence: '弓矢を使います。',
        type: 'secondary',
      },
      {
        reading: '弓道',
        kana: 'きゅうどう',
        meaning: ['Kyudo (Japanese Archery)'],
        sentence: '弓道を習います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '虫',
    onyomi: ['ちゅう'],
    kunyomi: ['むし'],
    meaning: ['Insect'],
    examples: [
      {
        reading: '虫',
        kana: 'むし',
        meaning: ['Insect'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '虫歯',
        kana: 'むしば',
        meaning: ['Cavity', 'Decayed tooth'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '弱虫',
        kana: 'よわむし',
        meaning: ['Coward', 'Weakling'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '昆虫',
        kana: 'こんちゅう',
        meaning: ['Insect'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '強',
    onyomi: ['きょう', 'ごう'],
    kunyomi: ['つよ', 'し'],
    meaning: ['Strong'],
    examples: [
      {
        reading: '強い',
        kana: 'つよい',
        meaning: ['Strong'],
        sentence: 'あの方は強いです。',
        type: 'main',
      },
      {
        reading: '勉強する',
        kana: 'べんきょうする',
        meaning: ['To study'],
        sentence: '勉強してください。',
        type: 'main',
      },
      {
        reading: '強いる',
        kana: 'しいる',
        meaning: ['To force'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '強気',
        kana: 'つよき',
        meaning: ['Aggressive'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '強制する',
        kana: 'きょうせいする',
        meaning: ['To force'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '強調する',
        kana: 'きょうちょうする',
        meaning: ['To emphasize'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '強盗',
        kana: 'ごうとう',
        meaning: ['Robber', 'Robbery'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '強化する',
        kana: 'きょうかする',
        meaning: ['To strengthen', 'To reinforce'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '持',
    onyomi: ['じ'],
    kunyomi: ['も'],
    meaning: ['To Hold'],
    examples: [
      {
        reading: '持つ',
        kana: 'もつ',
        meaning: ['To hold'],
        sentence: '何を持っていますか。',
        type: 'main',
      },
      {
        reading: 'お金持ち',
        kana: 'おかねもち',
        meaning: ['Rich person'],
        sentence: 'あの方はお金持ちです。',
        type: 'main',
      },
      {
        reading: '気持ち',
        kana: 'きもち',
        meaning: ['Feeling', 'Mood'],
        sentence: '気持ちが悪いです。',
        type: 'main',
      },
      {
        reading: '持ち物',
        kana: 'もちもの',
        meaning: ['Belongings'],
        sentence: '持ち物を確認してください。',
        type: 'secondary',
      },
      {
        reading: '持ち上げる',
        kana: 'もちあげる',
        meaning: ['To lift'],
        sentence: '持ち上げてください。',
        type: 'secondary',
      },
      {
        reading: '支持する',
        kana: 'しじする',
        meaning: ['To support'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '維持する',
        kana: 'いじする',
        meaning: ['To maintain'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '持続する',
        kana: 'じぞくする',
        meaning: ['To continue', 'To last'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '名',
    onyomi: ['めい', 'みょう'],
    kunyomi: ['な'],
    meaning: ['Name'],
    examples: [
      {
        reading: '名前',
        kana: 'なまえ',
        meaning: ['Name'],
        sentence: '名前を教えてください。',
        type: 'main',
      },
      {
        reading: '有名な',
        kana: 'ゆうめいな',
        meaning: ['Famous'],
        sentence: '有名な人です。',
        type: 'secondary',
      },
      {
        reading: '平仮名',
        kana: 'ひらがな',
        meaning: ['Hiragana'],
        sentence: '平仮名を勉強します。',
        type: 'secondary',
      },
      {
        reading: '名刺',
        kana: 'めいし',
        meaning: ['Business card'],
        sentence: '名刺を持っています。',
        type: 'secondary',
      },
      {
        reading: '氏名',
        kana: 'しめい',
        meaning: ['Full name'],
        sentence: '氏名を書いてください。',
        type: 'secondary',
      },
      {
        reading: '苗字',
        kana: 'みょうじ',
        meaning: ['Family name'],
        sentence: '苗字を教えてください。',
        type: 'secondary',
      },
      {
        reading: '名詞',
        kana: 'めいし',
        meaning: ['Noun'],
        sentence: '名詞を勉強します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '語',
    onyomi: ['ご'],
    kunyomi: ['かた'],
    meaning: ['Language'],
    examples: [
      {
        reading: '日本語',
        kana: 'にほんご',
        meaning: ['Japanese language'],
        sentence: '日本語を勉強します。',
        type: 'main',
      },
      {
        reading: '中国語',
        kana: 'ちゅうごくご',
        meaning: ['Chinese language'],
        sentence: '中国語を勉強します。',
        type: 'main',
      },
      {
        reading: '英語',
        kana: 'えいご',
        meaning: ['English language'],
        sentence: '英語を勉強します。',
        type: 'main',
      },
      {
        reading: '敬語',
        kana: 'けいご',
        meaning: ['Honorific language'],
        sentence: '敬語を使います。',
        type: 'main',
      },
      {
        reading: '外国語',
        kana: 'がいこくご',
        meaning: ['Foreign language'],
        sentence: '外国語を勉強します。',
        type: 'secondary',
      },
      {
        reading: '単語',
        kana: 'たんご',
        meaning: ['Vocabulary'],
        sentence: '単語を覚えます。',
        type: 'secondary',
      },
      {
        reading: '語る',
        kana: 'かたる',
        meaning: ['To talk', 'To tell'],
        sentence: '話を語ります。',
        type: 'secondary',
      },
      {
        reading: '主語',
        kana: 'しゅご',
        meaning: ['Subject (of a sentence)'],
        sentence: '主語を教えてください。',
        type: 'secondary',
      },
    ],
  },
]