export const KANJI_YDC_LESSON_6: Array<KanjiYDC> = [
  {
    kanji: '大',
    onyomi: ['だい', 'たい'],
    kunyomi: ['おお'],
    meaning: ['Big', 'Large'],
    examples: [
      {
        reading: '大きい',
        kana: 'おおきい',
        meaning: ['Big', 'Large'],
        sentence: '大きいですね。',
        type: 'main',
      },
      {
        reading: '大学',
        kana: 'だいがく',
        meaning: ['University'],
        sentence: '大学に行きます。',
        type: 'main',
      },
      {
        reading: '大学生',
        kana: 'だいがくせい',
        meaning: ['University student'],
        sentence: '大学生がいます。',
        type: 'main',
      },
      {
        reading: '大人',
        kana: 'おとな',
        meaning: ['Adult'],
        sentence: '大人ですね。',
        type: 'main',
      },
      {
        reading: '大好きな',
        kana: 'だいすきな',
        meaning: ['Favorite'],
        sentence: '大好きな食べ物は何ですか。',
        type: 'main',
      },
      {
        reading: '大使館',
        kana: 'たいしかん',
        meaning: ['Embassy'],
        sentence: '大使館に行きます。',
        type: 'secondary',
      },
      {
        reading: '大切な',
        kana: 'たいせつな',
        meaning: ['Precious'],
        sentence: '大切な人です。',
        type: 'secondary',
      },
      {
        reading: '大家',
        kana: 'おおや',
        meaning: ['Landlord'],
        sentence: '大家にお金を払います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '小',
    onyomi: ['しょう'],
    kunyomi: ['ちい', 'こ', 'お'],
    meaning: ['Small', 'Little'],
    examples: [
      {
        reading: '小さい',
        kana: 'ちいさい',
        meaning: ['Small', 'Little'],
        sentence: '小さいですね。',
        type: 'main',
      },
      {
        reading: '小学生',
        kana: 'しょうがくせい',
        meaning: ['Elementary school student'],
        sentence: '小学生がいます。',
        type: 'main',
      },
      {
        reading: '小学校',
        kana: 'しょうがっこう',
        meaning: ['Elementary school'],
        sentence: '小学校に行きます。',
        type: 'secondary',
      },
      {
        reading: '小説',
        kana: 'しょうせつ',
        meaning: ['Novel'],
        sentence: '小説を読みます。',
        type: 'secondary',
      },
      {
        reading: '小包',
        kana: 'こづつみ',
        meaning: ['Parcel'],
        sentence: '小包を送ります。',
        type: 'secondary',
      },
      {
        reading: '小麦',
        kana: 'こむぎ',
        meaning: ['Wheat'],
        sentence: '小麦を食べます。',
        type: 'secondary',
      },
      {
        reading: '小川',
        kana: 'おがわ',
        meaning: ['Small Stream'],
        sentence: '小川を見ます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '高',
    onyomi: ['こう'],
    kunyomi: ['たか', 'だか'],
    meaning: ['High', 'Tall'],
    examples: [
      {
        reading: '高い',
        kana: 'たかい',
        meaning: ['High', 'Expensive'],
        sentence: '高いですね。',
        type: 'main',
      },
      {
        reading: '高校',
        kana: 'こうこう',
        meaning: ['High school'],
        sentence: '高校に行きます。',
        type: 'secondary',
      },
      {
        reading: '高校生',
        kana: 'こうこうせい',
        meaning: ['High school student'],
        sentence: '高校生がいます。',
        type: 'secondary',
      },
      {
        reading: '最高',
        kana: 'さいこう',
        meaning: ['The best'],
        sentence: '最高ですね。',
        type: 'secondary',
      },
      {
        reading: '高級',
        kana: 'こうきゅう',
        meaning: ['High rank'],
        sentence: '高級なホテルです。',
        type: 'secondary',
      },
      {
        reading: '高める',
        kana: 'たかめる',
        meaning: ['To heighten'],
        sentence: '高めてください。',
        type: 'secondary',
      },
      {
        reading: '円高',
        kana: 'えんだか',
        meaning: ['Strong yen'],
        sentence: '円高です。',
        type: 'secondary',
      },
      {
        reading: '残高',
        kana: 'ざんだか',
        meaning: ['Account Balance'],
        sentence: '残高を確認します。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '安',
    onyomi: ['あん'],
    kunyomi: ['やす'],
    meaning: ['Cheap'],
    examples: [
      {
        reading: '安い',
        kana: 'やすい',
        meaning: ['Cheap'],
        sentence: '安いですね。',
        type: 'main',
      },
      {
        reading: '安心する',
        kana: 'あんしんする',
        meaning: ['To feel relieved'],
        sentence: '安心してください。',
        type: 'secondary',
      },
      {
        reading: '安全',
        kana: 'あんぜん',
        meaning: ['Safety'],
        sentence: '安全です。',
        type: 'secondary',
      },
      {
        reading: '不安な',
        kana: 'ふあんな',
        meaning: ['Worried'],
        sentence: '不安な気持ちです。',
        type: 'secondary',
      },
      {
        reading: '安定',
        kana: 'あんてい',
        meaning: ['Stability'],
        sentence: '安定しています。',
        type: 'secondary',
      },
      {
        reading: '安易な',
        kana: 'あんいな',
        meaning: ['Easy'],
        sentence: '安易な考えです。',
        type: 'secondary',
      },
      {
        reading: '目安',
        kana: 'めやす',
        meaning: ['Rough guideline'],
        sentence: '目安を立てます。',
        type: 'secondary',
      },
      {
        reading: '円安',
        kana: 'えんやす',
        meaning: ['Weak yen'],
        sentence: '円安です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '新',
    onyomi: ['しん'],
    kunyomi: ['あたら', 'あら', 'にい'],
    meaning: ['New'],
    examples: [
      {
        reading: '新しい',
        kana: 'あたらしい',
        meaning: ['New'],
        sentence: '新しいですね。',
        type: 'main',
      },
      {
        reading: '新聞',
        kana: 'しんぶん',
        meaning: ['Newspaper'],
        sentence: '新聞を読みます。',
        type: 'main',
      },
      {
        reading: '新幹線',
        kana: 'しんかんせん',
        meaning: ['Bullet train'],
        sentence: '新幹線に乗ります。',
        type: 'secondary',
      },
      {
        reading: '新年',
        kana: 'しんねん',
        meaning: ['New year'],
        sentence: '新年です。',
        type: 'secondary',
      },
      {
        reading: '新鮮な',
        kana: 'しんせんな',
        meaning: ['Fresh'],
        sentence: '新鮮な魚です。',
        type: 'secondary',
      },
      {
        reading: '新たな',
        kana: 'あらたな',
        meaning: ['New'],
        sentence: '新たな計画です。',
        type: 'secondary',
      },
      {
        reading: '新潟',
        kana: 'にいがた',
        meaning: ['Niigata'],
        sentence: '新潟に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '古',
    onyomi: ['こ'],
    kunyomi: ['ふる'],
    meaning: ['Old'],
    examples: [
      {
        reading: '古い',
        kana: 'ふるい',
        meaning: ['Old'],
        sentence: '古いですね。',
        type: 'main',
      },
      {
        reading: '中古',
        kana: 'ちゅうこ',
        meaning: ['Secondhand'],
        sentence: '中古の車です。',
        type: 'secondary',
      },
      {
        reading: '古本',
        kana: 'ふるほん',
        meaning: ['Old book'],
        sentence: '古本を読みます。',
        type: 'secondary',
      },
      {
        reading: '使い古す',
        kana: 'つかいふるす',
        meaning: ['To wear out'],
        sentence: '使い古しています。',
        type: 'secondary',
      },
      {
        reading: '考古学',
        kana: 'こうこがく',
        meaning: ['Archaeology'],
        sentence: '考古学を勉強します。',
        type: 'secondary',
      },
      {
        reading: '古代',
        kana: 'こだい',
        meaning: ['Ancient times'],
        sentence: '古代の遺跡です。',
        type: 'secondary',
      },
      {
        reading: '古都',
        kana: 'こと',
        meaning: ['Old capital'],
        sentence: '古都です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '元',
    onyomi: ['げん', 'がん'],
    kunyomi: ['もと'],
    meaning: ['Origin', 'Source'],
    examples: [
      {
        reading: '元気な',
        kana: 'げんきな',
        meaning: ['Healthy', 'Energetic'],
        sentence: '元気ですね。',
        type: 'main',
      },
      {
        reading: '元日',
        kana: 'がんじつ',
        meaning: ['the first day of the year'],
        sentence: '元日です。',
        type: 'secondary',
      },
      {
        reading: '足元',
        kana: 'あしもと',
        meaning: ['At one’s feet'],
        sentence: '足元に気をつけます。',
        type: 'secondary',
      },
      {
        reading: '地元',
        kana: 'じもと',
        meaning: ['Local'],
        sentence: '地元の人です。',
        type: 'secondary',
      },
      {
        reading: '三次元',
        kana: 'さんじげん',
        meaning: ['Three dimensions'],
        sentence: '三次元の世界です。',
        type: 'secondary',
      },
      {
        reading: '元',
        kana: 'げん',
        meaning: ['Yuan (currency)'],
        sentence: '元を両替します。',
        type: 'secondary',
      },
      {
        reading: '紀元前',
        kana: 'きげんぜん',
        meaning: ['B.C.'],
        sentence: '紀元前です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '気',
    onyomi: ['き', 'け'],
    kunyomi: [],
    meaning: ['Spirit', 'Mood'],
    examples: [
      {
        reading: '元気な',
        kana: 'げんきな',
        meaning: ['Healthy', 'Energetic'],
        sentence: '元気ですね。',
        type: 'main',
      },
      {
        reading: '気を付ける',
        kana: 'きをつける',
        meaning: ['To be careful'],
        sentence: '会話をします。',
        type: 'main',
      },
      {
        reading: '天気',
        kana: 'てんき',
        meaning: ['Weather'],
        sentence: '天気がいいです。',
        type: 'secondary',
      },
      {
        reading: '電気',
        kana: 'でんき',
        meaning: ['Electricity'],
        sentence: '電気を使います。',
        type: 'secondary',
      },
      {
        reading: '気持ち',
        kana: 'きもち',
        meaning: ['Feeling'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '人気',
        kana: 'にんき',
        meaning: ['Popular'],
        sentence: '人気があります。',
        type: 'secondary',
      },
      {
        reading: '気に入る',
        kana: 'きにいる',
        meaning: ['To be fond of'],
        sentence: '気に入っています。',
        type: 'secondary',
      },
      {
        reading: '気配',
        kana: 'けはい',
        meaning: ['Sign', 'Indication'],
        sentence: '気配があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '多',
    onyomi: ['た'],
    kunyomi: ['おお'],
    meaning: ['Many'],
    examples: [
      {
        reading: '多い',
        kana: 'おおい',
        meaning: ['Many'],
        sentence: '多いですね。',
        type: 'main',
      },
      {
        reading: '多分',
        kana: 'たぶん',
        meaning: ['Probably'],
        sentence: '多分です。',
        type: 'main',
      },
      {
        reading: '多少',
        kana: 'たしょう',
        meaning: ['More or less', 'A little', 'Somewhat'],
        sentence: '多少あります。',
        type: 'secondary',
      },
      {
        reading: '滅多に',
        kana: 'めったに',
        meaning: ['Rarely'],
        sentence: '滅多にありません。',
        type: 'secondary',
      },
      {
        reading: '多数決',
        kana: 'たすうけつ',
        meaning: ['Decision by majority'],
        sentence: '多数決をします。',
        type: 'secondary',
      },
      {
        reading: '多数',
        kana: 'たすう',
        meaning: ['Large number'],
        sentence: '多数の人です。',
        type: 'secondary',
      },
      {
        reading: '多量',
        kana: 'たりょう',
        meaning: ['Large quantity'],
        sentence: '多量の食べ物です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '少',
    onyomi: ['しょう'],
    kunyomi: ['すく', 'すこ'],
    meaning: ['little'],
    examples: [ 
      {
        reading: '少しい',
        kana: 'すくしい',
        meaning: ['Little'],
        sentence: '少しいですね。',
        type: 'main',
      },
      {
        reading: '少ない',
        kana: 'すくない',
        meaning: ['Few'],
        sentence: '少ないですね。',
        type: 'main',
      },
      {
        reading: '少年',
        kana: 'しょうねん',
        meaning: ['Boy'],
        sentence: '少年がいます。',
        type: 'secondary',
      },
      {
        reading: '少女',
        kana: 'しょうじょ',
        meaning: ['Girl'],
        sentence: '少女がいます。',
        type: 'secondary',
      },
      {
        reading: '少々',
        kana: 'しょうしょう',
        meaning: ['A little'],
        sentence: '少々お待ちください。',
        type: 'secondary',
      },
      {
        reading: '減少',
        kana: 'げんしょう',
        meaning: ['Decrease'],
        sentence: '減少しています。',
        type: 'secondary',
      },
      {
        reading: '少量',
        kana: 'しょうりょう',
        meaning: ['Small quantity'],
        sentence: '少量の食べ物です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '広',
    onyomi: ['こう'],
    kunyomi: ['ひろ', 'びろ'],
    meaning: ['Wide', 'Spacious'],
    examples: [
      {
        reading: '広い',
        kana: 'ひろい',
        meaning: ['Wide', 'Spacious'],
        sentence: '広いですね。',
        type: 'main',
      },
      {
        reading: '広島',
        kana: 'ひろしま',
        meaning: ['Hiroshima'],
        sentence: '広島に行きます。',
        type: 'secondary',
      },
      {
        reading: '広告',
        kana: 'こうこく',
        meaning: ['Advertisement'],
        sentence: '広告を見ます。',
        type: 'secondary',
      },
      {
        reading: '広場',
        kana: 'ひろば',
        meaning: ['Open space'],
        sentence: '広場に行きます。',
        type: 'secondary',
      },
      {
        reading: '広がる',
        kana: 'ひろがる',
        meaning: ['(Something) spreads'],
        sentence: '広がっています。',
        type: 'secondary',
      },
      {
        reading: '広める',
        kana: 'ひろめる',
        meaning: ['To spread (Something)'],
        sentence: '広めてください。',
        type: 'secondary',
      },
      {
        reading: '広さ',
        kana: 'ひろさ',
        meaning: ['Width'],
        sentence: '広さを測ります。',
        type: 'secondary',
      },
      {
        reading: '背広',
        kana: 'せびろ',
        meaning: ['Business Jacket'],
        sentence: '背広を着ます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '早',
    onyomi: ['そう', 'さっ'],
    kunyomi: ['はや', 'ばや'],
    meaning: ['Early'],
    examples: [
      {
        reading: '早い',
        kana: 'はやい',
        meaning: ['Early'],
        sentence: '早いですね。',
        type: 'main',
      },
      {
        reading: '早く',
        kana: 'はやく',
        meaning: ['Early'],
        sentence: '早く起きます。',
        type: 'main',
      },
      {
        reading: '早口',
        kana: 'はやくち',
        meaning: ['Fast talker'],
        sentence: '早口ですね。',
        type: 'secondary',
      },
      {
        reading: '素早い',
        kana: 'すばやい',
        meaning: ['Quick'],
        sentence: '素早いですね。',
        type: 'secondary',
      },
      {
        reading: '早送り',
        kana: 'はやおくり',
        meaning: ['Fast forward'],
        sentence: '早送りします。',
        type: 'secondary',
      },
      {
        reading: '早める',
        kana: 'はやめる',
        meaning: ['To hasten'],
        sentence: '早めてください。',
        type: 'secondary',
      },
      {
        reading: '早速',
        kana: 'さっそく',
        meaning: ['At once'],
        sentence: '早速行きます。',
        type: 'secondary',
      },
      {
        reading: '早朝',
        kana: 'そうちょう',
        meaning: ['Early morning'],
        sentence: '早朝です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '長',
    onyomi: ['ちょう'],
    kunyomi: ['なが'],
    meaning: ['Long'],
    examples: [
      {
        reading: '長い',
        kana: 'ながい',
        meaning: ['Long'],
        sentence: '長いですね。',
        type: 'main',
      },
      {
        reading: '社長',
        kana: 'しゃちょう',
        meaning: ['Company president'],
        sentence: '社長です。',
        type: 'secondary',
      },
      {
        reading: '部長',
        kana: 'ぶちょう',
        meaning: ['Department manager'],
        sentence: '部長です。',
        type: 'secondary',
      },
      {
        reading: '身長',
        kana: 'しんちょう',
        meaning: ['Height'],
        sentence: '身長が高いです。',
        type: 'secondary',
      },
      {
        reading: '長男',
        kana: 'ちょうなん',
        meaning: ['Eldest son'],
        sentence: '長男です。',
        type: 'secondary',
      },
      {
        reading: '長方形',
        kana: 'ちょうほうけい',
        meaning: ['Rectangle'],
        sentence: '長方形です。',
        type: 'secondary',
      },
      {
        reading: '長さ',
        kana: 'ながさ',
        meaning: ['Length'],
        sentence: '長さを測ります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '明',
    onyomi: ['めい', 'みょう'],
    kunyomi: ['あか', 'あき', 'あ'],
    meaning: ['Bright'],
    examples: [
      {
        reading: '明るい',
        kana: 'あかるい',
        meaning: ['Bright'],
        sentence: '明るいですね。',
        type: 'main',
      },
      {
        reading: '明日',
        kana: 'あした・あす・みょうにち',
        meaning: ['Tomorrow'],
        sentence: '明日は何をしますか。',
        type: 'main',
      },
      {
        reading: '説明',
        kana: 'せつめい',
        meaning: ['Explanation'],
        sentence: '説明をします。',
        type: 'secondary',
      },
      {
        reading: '証明書',
        kana: 'しょうめいしょ',
        meaning: ['Certificate'],
        sentence: '証明書を取ります。',
        type: 'secondary',
      },
      {
        reading: '明後日',
        kana: 'あさって・みょうごにち',
        meaning: ['To expect', 'To hope for'],
        sentence: '期待しています。',
        type: 'secondary',
      },
      {
        reading: '打ち明ける',
        kana: 'うちあける',
        meaning: ['To confide'],
        sentence: '打ち明けてください。',
        type: 'secondary',
      },
      {
        reading: '明ける',
        kana: 'あける',
        meaning: ['To dawn'],
        sentence: '明けています。',
        type: 'secondary',
      },
      {
        reading: '明らか',
        kana: 'あきらか',
        meaning: ['Obvious', 'Clear'],
        sentence: '明らかです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '好',
    onyomi: ['こう'],
    kunyomi: ['す', 'この'],
    meaning: ['Like'],
    examples: [
      {
        reading: '好きな',
        kana: 'すきな',
        meaning: ['Like'],
        sentence: '好きな食べ物は何ですか。',
        type: 'main',
      },
      {
        reading: '大好きな',
        kana: 'だいすきな',
        meaning: ['Favorite'],
        sentence: '大好きな食べ物は何ですか。',
        type: 'main',
      },
      {
        reading: '好み',
        kana: 'このみ',
        meaning: ['Taste', 'Preference'],
        sentence: '好みがあります。',
        type: 'secondary',
      },
      {
        reading: '好む',
        kana: 'このむ',
        meaning: ['To like'],
        sentence: '好みます。',
        type: 'secondary',
      },
      {
        reading: 'お好み焼き',
        kana: 'おこのみやき',
        meaning: ['Okonomiyaki'],
        sentence: 'お好み焼きを食べます。',
        type: 'secondary',
      },
      {
        reading: '好意',
        kana: 'こうい',
        meaning: ['Good will', 'Fondness'],
        sentence: '好意を持っています。',
        type: 'secondary',
      },
      {
        reading: '好感',
        kana: 'こうかん',
        meaning: ['Good Feeling'],
        sentence: '好感を持っています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '友',
    onyomi: ['ゆう'],
    kunyomi: ['とも'],
    meaning: ['Friend'],
    examples: [
      {
        reading: '友達',
        kana: 'ともだち',
        meaning: ['Friend'],
        sentence: '友達がいます。',
        type: 'main',
      },
      {
        reading: '友人',
        kana: 'ゆうじん',
        meaning: ['Friend'],
        sentence: '友人がいます。',
        type: 'secondary',
      },
      {
        reading: '親友',
        kana: 'しんゆう',
        meaning: ['Best friend'],
        sentence: '親友です。',
        type: 'secondary',
      },
      {
        reading: '友情',
        kana: 'ゆうじょう',
        meaning: ['Friendship'],
        sentence: '友情があります。',
        type: 'secondary',
      },
      {
        reading: '友好',
        kana: 'ゆうこう',
        meaning: ['Goodwill'],
        sentence: '友好関係です。',
        type: 'secondary',
      },
    ],
  },
]