export const KANJI_YDC_LESSON_4: Array<KanjiYDC> = [
  {
    kanji: '田',
    onyomi: ['でん'],
    kunyomi: ['た', 'だ'],
    meaning: ['Rice field'],
    examples: [
      {
        reading: '田中さん',
        kana: 'たなかさん',
        meaning: ['Mr. Tanaka'],
        sentence: '田中さんは日本人です。',
        type: 'main',
      },
      {
        reading: '山田さん',
        kana: 'やまださん',
        meaning: ['Mr. Yamada'],
        sentence: '山田さんは日本人です。',
        type: 'secondary',
      },
      {
        reading: '田舎',
        kana: 'いなか',
        meaning: ['Countryside'],
        sentence: '私は田舎に住んでいます。',
        type: 'secondary',
      },
      {
        reading: '田んぼ',
        kana: 'たんぼ',
        meaning: ['Rice field'],
        sentence: '田んぼで働いています。',
        type: 'secondary',
      },
      {
        reading: '田植え',
        kana: 'たうえ',
        meaning: ['Rice planting'],
        sentence: '田植えを手伝ってください。',
        type: 'secondary',
      },
      {
        reading: '水田',
        kana: 'すいでん',
        meaning: ['Paddy field'],
        sentence: '水田で働いています。',
        type: 'secondary',
      },
      {
        reading: '田園',
        kana: 'でんえん',
        meaning: ['Rural area'],
        sentence: '田園風景が好きです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '力',
    onyomi: ['りょく', 'りき'],
    kunyomi: ['ちから'],
    meaning: ['Power', 'Strength'],
    examples: [
      {
        reading: '力',
        kana: 'ちから',
        meaning: ['Power', 'Strength'],
        sentence: '力を使ってください。',
        type: 'main',
      },
      {
        reading: '学力',
        kana: 'がくりょく',
        meaning: ['Academic ability'],
        sentence: '学力が高いです。',
        type: 'secondary',
      },
      {
        reading: '電力',
        kana: 'でんりょく',
        meaning: ['Electric power'],
        sentence: '電力が足りません。',
        type: 'secondary',
      },
      {
        reading: '重力',
        kana: 'じゅうりょく',
        meaning: ['Gravity'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '協力する',
        kana: 'きょうりょくする',
        meaning: ['To cooperate'],
        sentence: '協力してください。',
        type: 'secondary',
      },
      {
        reading: '努力',
        kana: 'どりょく',
        meaning: ['Effort'],
        sentence: '努力してください。',
        type: 'secondary',
      },
      {
        reading: '力学',
        kana: 'りきがく',
        meaning: ['Dynamics'],
        sentence: '力学の勉強をしています。',
        type: 'secondary',
      },
      {
        reading: '視力',
        kana: 'しりょく',
        meaning: ['Eyesight'],
        sentence: '視力が悪いです。',
        type: 'secondary',
      }
    ],
  },
  {
    kanji: '男',
    onyomi: ['だん', 'なん'],
    kunyomi: ['おとこ'],
    meaning: ['Man'],
    examples: [
      {
        reading: '男の子',
        kana: 'おとこのこ',
        meaning: ['Boy'],
        sentence: '男の子がいます。',
        type: 'main',
      },
      {
        reading: '男の人',
        kana: 'おとこのひと',
        meaning: ['Man'],
        sentence: '男の人がいます。',
        type: 'main',
      },
      {
        reading: '男性',
        kana: 'だんせい',
        meaning: ['Male'],
        sentence: '男性が多いです。',
        type: 'secondary',
      },
      {
        reading: '男子学生',
        kana: 'だんしがくせい',
        meaning: ['Male student'],
        sentence: '男子学生がいます。',
        type: 'secondary',
      },
      {
        reading: '長男',
        kana: 'ちょうなん',
        meaning: ['Eldest son'],
        sentence: '長男がいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '女',
    onyomi: ['じょ', 'にょ', 'にょう'],
    kunyomi: ['おんな', 'め'],
    meaning: ['Woman'],
    examples: [
      {
        reading: '女の子',
        kana: 'おんなのこ',
        meaning: ['Girl'],
        sentence: '女の子がいます。',
        type: 'main',
      },
      {
        reading: '女の人',
        kana: 'おんなのひと',
        meaning: ['Woman'],
        sentence: '女の人がいます。',
        type: 'main',
      },
      {
        reading: '少女',
        kana: 'しょうじょ',
        meaning: ['Girl'],
        sentence: '少女がいます。',
        type: 'secondary',
      },
      {
        reading: '女性',
        kana: 'じょせい',
        meaning: ['Female'],
        sentence: '女性が多いです。',
        type: 'secondary',
      },
      {
        reading: '彼女',
        kana: 'かのじょ',
        meaning: ['Girlfriend', 'She'],
        sentence: '彼女がいます。',
        type: 'secondary',
      },
      {
        reading: '長女',
        kana: 'ちょうじょ',
        meaning: ['Eldest daughter'],
        sentence: '長女がいます。',
        type: 'secondary',
      },
      {
        reading: '女房',
        kana: 'にょうぼう',
        meaning: ['Wife'],
        sentence: '女房がいます。',
        type: 'secondary',
      },
      {
        reading: '女神',
        kana: 'めがみ',
        meaning: ['Goddess'],
        sentence: '女神がいます。',
        type: 'secondary',
      }
    ],
  },
  {
    kanji: '子',
    onyomi: ['し', 'す'],
    kunyomi: ['こ', 'ね'],
    meaning: ['Child'],
    examples: [
      {
        reading: '男の子',
        kana: 'おとこのこ',
        meaning: ['Boy'],
        sentence: '男の子がいます。',
        type: 'main',
      },
      {
        reading: '女の子',
        kana: 'おんなのこ',
        meaning: ['Girl'],
        sentence: '女の子がいます。',
        type: 'main',
      },
      {
        reading: '子供',
        kana: 'こども',
        meaning: ['Child'],
        sentence: '子供がいます。',
        type: 'secondary',
      },
      {
        reading: '電子辞書',
        kana: 'でんしじしょ',
        meaning: ['Electronic dictionary'],
        sentence: '電子辞書を使っています。',
        type: 'secondary',
      },
      {
        reading: '女子学生',
        kana: 'じょしがくせい',
        meaning: ['Female student'],
        sentence: '女子学生がいます。',
        type: 'secondary',
      },
      {
        reading: '男子学生',
        kana: 'だんしがくせい',
        meaning: ['Male student'],
        sentence: '男子学生がいます。',
        type: 'secondary',
      },
      {
        reading: '様子',
        kana: 'ようす',
        meaning: ['Condition', 'State'],
        sentence: '様子を見てください。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '学',
    onyomi: ['がく','がっ'],
    kunyomi: ['まな'],
    meaning: ['Study', 'Learning'],
    examples: [
      {
        reading: '学生',
        kana: 'がくせい',
        meaning: ['Student'],
        sentence: '学生がいます。',
        type: 'main',
      },
      {
        reading: '学校',
        kana: 'がっこう',
        meaning: ['School'],
        sentence: '学校に行きます。',
        type: 'main',
      },
      {
        reading: '学ぶ',
        kana: 'まなぶ',
        meaning: ['To learn'],
        sentence: '日本語を学びます。',
        type: 'secondary',
      },
      {
        reading: '大学',
        kana: 'だいがく',
        meaning: ['University'],
        sentence: '大学に行きます。',
        type: 'secondary',
      },
      {
        reading: '学部',
        kana: 'がくぶ',
        meaning: ['Faculty','Department'],
        sentence: 'どの学部に行きますか。',
        type: 'secondary',
      },
      {
        reading: '学習',
        kana: 'がくしゅう',
        meaning: ['Learning'],
        sentence: '学習しています。',
        type: 'secondary',
      },
      {
        reading: '学者',
        kana: 'がくしゃ',
        meaning: ['Scholar'],
        sentence: '学者がいます。',
        type: 'secondary',
      },
      {
        reading: '文学',
        kana: 'ぶんがく',
        meaning: ['Literature'],
        sentence: '文学が好きです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '生',
    onyomi: ['せい', 'しょう','じょう'],
    kunyomi: ['い', 'う', 'お', 'き', 'なま', 'は'],
    meaning: ['Life', 'Birth'],
    examples: [
      {
        reading: '生まれる',
        kana: 'うまれる',
        meaning: ['To be born'],
        sentence: '私は日本で生まれました。',
        type: 'main',
      },
      {
        reading: '生きる',
        kana: 'いきる',
        meaning: ['To live'],
        sentence: '生きることが大切です。',
        type: 'main',
      },
      {
        reading: '先生',
        kana: 'せんせい',
        meaning: ['Teacher'],
        sentence: '先生がいます。',
        type: 'main',
      },
      {
        reading: '学生',
        kana: 'がくせい',
        meaning: ['Student'],
        sentence: '学生がいます。',
        type: 'main',
      },
      {
        reading: '中学校',
        kana: 'ちゅうがっこう',
        meaning: ['Junior high school'],
        sentence: '中学校に行きます。',
        type: 'secondary',
      },
      {
        reading: '高校',
        kana: 'こうこう',
        meaning: ['High school'],
        sentence: '高校に行きます。',
        type: 'secondary',
      },
      {
        reading: '大学',
        kana: 'だいがく',
        meaning: ['University'],
        sentence: '大学に行きます。',
        type: 'secondary',
      },
      {
        reading: '校長',
        kana: 'こうちょう',
        meaning: ['Principal'],
        sentence: '校長先生がいます。',
        type: 'secondary',
      },
      {
        reading: '誕生日',
        kana: 'たんじょうび',
        meaning: ['Birthday'],
        sentence: '誕生日おめでとう。',
        type: 'secondary',
      },
      {
        reading: '生える',
        kana: 'はえる',
        meaning: ['To grow', 'To come out'],
        sentence: '髪が生えてきました。',
        type: 'secondary',
      },
      {
        reading: '一生',
        kana: 'いっしょう',
        meaning: ['Lifetime'],
        sentence: '一生懸命頑張ります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '先',
    onyomi: ['せん'],
    kunyomi: ['さき'],
    meaning: ['Ahead'],
    examples: [
      {
        reading: '先生',
        kana: 'せんせい',
        meaning: ['Teacher'],
        sentence: '先生がいます。',
        type: 'main',
      },
      {
        reading: '先月',
        kana: 'せんげつ',
        meaning: ['Last month'],
        sentence: '先月の給料が少なかった。',
        type: 'main',
      },
      {
        reading: '先週',
        kana: 'せんしゅう',
        meaning: ['Last week'],
        sentence: '先週の金曜日に会いました。',
        type: 'secondary',
      },
      {
        reading: '先輩',
        kana: 'せんぱい',
        meaning: ['Senior'],
        sentence: '先輩に教えてもらいました。',
        type: 'secondary',
      },
      {
        reading: '先日',
        kana: 'せんじつ',
        meaning: ['The other day'],
        sentence: '先日、友達に会いました。',
        type: 'secondary',
      },
      {
        reading: '先祖',
        kana: 'せんぞ',
        meaning: ['Ancestor'],
        sentence: '先祖がいます。',
        type: 'secondary',
      },
      {
        reading: '先に',
        kana: 'さきに',
        meaning: ['Ahead'],
        sentence: '先に行ってください。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '何',
    onyomi: ['か'],
    kunyomi: ['なに', 'なん',],
    meaning: ['What'],
    examples: [
      {
        reading: '何',
        kana: 'なに',
        meaning: ['What'],
        sentence: '何をしていますか。',
        type: 'main',
      },
      {
        reading: '何か',
        kana: 'なにか',
        meaning: ['Something'],
        sentence: '何か食べたいです。',
        type: 'main',
      },
      {
        reading: '何人',
        kana: 'なんにん',
        meaning: ['How many people'],
        sentence: '何人で行きますか。',
        type: 'main',
      },
      {
        reading: '何時',
        kana: 'なんじ',
        meaning: ['What time'],
        sentence: '何時に会いましょうか。',
        type: 'main',
      },
      {
        reading: '何でも',
        kana: 'なんでも',
        meaning: ['Anything'],
        sentence: '何でも食べます。',
        type: 'secondary',
      },
      {
        reading: '何度',
        kana: 'なんど',
        meaning: ['How many times'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '幾何学',
        kana: 'きかがく',
        meaning: ['Geometry'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '父',
    onyomi: ['ふ'],
    kunyomi: ['ちち'],
    meaning: ['Father'],
    examples: [ 
      {
        reading: 'お父さん',
        kana: 'おとうさん',
        meaning: ['Father'],
        sentence: 'お父さんがいます。',
        type: 'main',
      },
      {
        reading: '父の日',
        kana: 'ちちのひ',
        meaning: ['Father\'s day'],
        sentence: '父の日にプレゼントをあげます。',
        type: 'main',
      },
      {
        reading: '祖父',
        kana: 'そふ',
        meaning: ['Grandfather'],
        sentence: '祖父がいます。',
        type: 'secondary',
      },
      {
        reading: '父母',
        kana: 'ふぼ',
        meaning: ['Parents'],
        sentence: '父母がいます。',
        type: 'secondary',
      },
      {
        reading: '祖父母',
        kana: 'そふぼ',
        meaning: ['Grandparents'],
        sentence: '祖父母がいます。',
        type: 'secondary',
      },
      {
        reading: '叔父',
        kana: 'おじ',
        meaning: ['Uncle'],
        sentence: '叔父がいます。',
        type: 'secondary',
      },
      {
        reading: '伯父',
        kana: 'おじ',
        meaning: ['Uncle'],
        sentence: '伯父がいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '母',
    onyomi: ['ぼ'],
    kunyomi: ['はは'],
    meaning: ['Mother'],
    examples: [
      {
        reading: 'お母さん',
        kana: 'おかあさん',
        meaning: ['Mother'],
        sentence: 'お母さんがいます。',
        type: 'main',
      },
      {
        reading: '母の日',
        kana: 'ははのひ',
        meaning: ['Mother\'s day'],
        sentence: '母の日にプレゼントをあげます。',
        type: 'main',
      },
      {
        reading: '祖母',
        kana: 'そぼ',
        meaning: ['Grandmother'],
        sentence: '祖母がいます。',
        type: 'secondary',
      },
      {
        reading: '父母',
        kana: 'ふぼ',
        meaning: ['Parents'],
        sentence: '父母がいます。',
        type: 'secondary',
      },
      {
        reading: '祖父母',
        kana: 'そふぼ',
        meaning: ['Grandparents'],
        sentence: '祖父母がいます。',
        type: 'secondary',
      },
      {
        reading: '母語',
        kana: 'ぼご',
        meaning: ['Mother tongue'],
        sentence: '母語は日本語です。',
        type: 'secondary',
      },
      {
        reading: '叔母',
        kana: 'おば',
        meaning: ['Aunt'],
        sentence: '叔母がいます。',
        type: 'secondary',
      },
      {
        reading: '伯母',
        kana: 'おば',
        meaning: ['Aunt'],
        sentence: '伯母がいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '年',
    onyomi: ['ねん'],
    kunyomi: ['とし'],
    meaning: ['Year'],
    examples: [
      {
        reading: '三年生',
        kana: 'さんねんせい',
        meaning: ['Third year student'],
        sentence: '三年生がいます。',
        type: 'main',
      },
      {
        reading: '一年',
        kana: 'いちねん',
        meaning: ['One year'],
        sentence: '一年間日本に住んでいます。',
        type: 'main',
      },
      {
        reading: '今年',
        kana: 'ことし',
        meaning: ['This year'],
        sentence: '今年は良い年です。',
        type: 'main',
      },
      {
        reading: '去年',
        kana: 'きょねん',
        meaning: ['Last year'],
        sentence: '去年の夏は暑かった。',
        type: 'main',
      },
      {
        reading: '年',
        kana: 'とし',
        meaning: ['Year'],
        sentence: '何年生まれですか。',
        type: 'main',
      },
      {
        reading: '毎年',
        kana: 'まいとし・まいねん',
        meaning: ['Every year'],
        sentence: '毎年日本に行きます。',
        type: 'main',
      },
      {
        reading: '来年',
        kana: 'らいねん',
        meaning: ['Next year'],
        sentence: '来年はどこに行きますか。',
        type: 'secondary',
      },
      {
        reading: '青少年',
        kana: 'せいじょうねん',
        meaning: ['Juvenile', 'Youth'],
        sentence: '年齢を教えてください。',
        type: 'secondary',
      },
      {
        reading: '中年',
        kana: 'ちゅうねん',
        meaning: ['Middle-aged'],
        sentence: '中年になりました。',
        type: 'secondary',
      },
      {
        reading: '年中',
        kana: 'ねんじゅう',
        meaning: ['Throughout the year'],
        sentence: '年中無休です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '去',
    onyomi: ['きょ', 'こ'],
    kunyomi: ['さ'],
    meaning: ['Past', 'Leave'],
    examples: [
      {
        reading: '去年',
        kana: 'きょねん',
        meaning: ['Last year'],
        sentence: '去年の夏は暑かった。',
        type: 'main',
      },
      {
        reading: '過去',
        kana: 'かこ',
        meaning: ['Past'],
        sentence: '過去のことは忘れました。',
        type: 'secondary',
      },
      {
        reading: '去る',
        kana: 'さる',
        meaning: ['To leave'],
        sentence: '去る日本に行きます。',
        type: 'secondary',
      },
      {
        reading: '消去する',
        kana: 'しょうきょする',
        meaning: ['To erase'],
        sentence: '消去してください。',
        type: 'secondary',
      },
      {
        reading: '除去する',
        kana: 'じょきょする',
        meaning: ['To remove', 'To eliminate'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '毎',
    onyomi: ['まい'],
    kunyomi: [],
    meaning: ['Every'],
    examples: [
      {
        reading: '毎日',
        kana: 'まいにち',
        meaning: ['Every day'],
        sentence: '毎日日本語を勉強します。',
        type: 'main',
      },
      {
        reading: '毎月',
        kana: 'まいつき',
        meaning: ['Every month'],
        sentence: '毎月日本に行きます。',
        type: 'main',
      },
      {
        reading: '毎年',
        kana: 'まいとし・まいねん',
        meaning: ['Every year'],
        sentence: '毎年日本に行きます。',
        type: 'main',
      },
      {
        reading: '毎週',
        kana: 'まいしゅう',
        meaning: ['Every week'],
        sentence: '毎週日本語を勉強します。',
        type: 'secondary',
      },
      {
        reading: '毎晩',
        kana: 'まいばん',
        meaning: ['Every night'],
        sentence: '毎晩日本語を勉強します。',
        type: 'secondary',
      },
      {
        reading: '毎朝',
        kana: 'まいあさ',
        meaning: ['Every morning'],
        sentence: '毎朝日本語を勉強します。',
        type: 'secondary',
      },
      {
        reading: '毎度',
        kana: 'まいど',
        meaning: ['Each time'],
        sentence: '毎度ありがとうございます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '王',
    onyomi: ['おう'],
    kunyomi: [],
    meaning: ['King'],
    examples: [
      {
        reading: '国王',
        kana: 'こくおう',
        meaning: ['King'],
        sentence: '国王がいます。',
        type: 'secondary',
      },
      {
        reading: '王様',
        kana: 'おうさま',
        meaning: ['King'],
        sentence: '王様がいます。',
        type: 'secondary',
      },
      {
        reading: '女王',
        kana: 'じょおう',
        meaning: ['Queen'],
        sentence: '女王がいます。',
        type: 'secondary',
      },
      {
        reading: '王女',
        kana: 'おうじょ',
        meaning: ['Princess'],
        sentence: '王女がいます。',
        type: 'secondary',
      },
      {
        reading: '王子',
        kana: 'おうじ',
        meaning: ['Prince'],
        sentence: '王子がいます。',
        type: 'secondary',
      },
      {
        reading: '王国',
        kana: 'おうこく',
        meaning: ['Kingdom'],
        sentence: '王国があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '国',
    onyomi: ['こく', 'ごく', 'こっ'],
    kunyomi: ['くに'],
    meaning: ['Country'],
    examples: [
      {
        reading: '国',
        kana: 'くに',
        meaning: ['Country'],
        sentence: '日本は素晴らしい国です。',
        type: 'main',
      },
      {
        reading: '外国',
        kana: 'がいこく',
        meaning: ['Foreign country'],
        sentence: '外国に行きます。',
        type: 'main',
      },
      {
        reading: '中国',
        kana: 'ちゅうごく',
        meaning: ['China'],
        sentence: '中国に行きます。',
        type: 'main',
      },
      {
        reading: '韓国',
        kana: 'かんこく',
        meaning: ['South Korea'],
        sentence: '韓国に行きます。',
        type: 'secondary',
      },
      {
        reading: '国会',
        kana: 'こっかい',
        meaning: ['The Diet'],
        sentence: '国会議員がいます。',
        type: 'secondary',
      },
      {
        reading: '国際',
        kana: 'こくさい',
        meaning: ['International'],
        sentence: '国際交流が大切です。',
        type: 'secondary',
      },
      {
        reading: '国籍',
        kana: 'こくせき',
        meaning: ['Nationality'],
        sentence: '国籍は日本です。',
        type: 'secondary',
      },
      {
        reading: '国内',
        kana: 'こくない',
        meaning: ['Domestic'],
        sentence: '国内に住んでいます。',
        type: 'secondary',
      },
    ],
  },
]