export const NIHONGO_NO_MORI_MOJI_GOI_N2: JLPTReview[] = [
  {
    kanji: "賞",
    kana: "しょう",
    english: "prize・ award・reward",
    explanation: "Used to refer to recognition given for achievement in various fields.",
    example: "彼の作品は必ず{賞}を取るだろう。\nHis work is sure to win a prize.",
  },
  {
    kanji: "金賞",
    kana: "きんしょう",
    english: "gold medal・first prize",
    explanation: "The highest award given in competitions or contests.",
    example: "彼女は大会で{金賞}を受賞した。\nShe received the gold medal at the competition.",
  },
  {
    kanji: "賞状",
    kana: "しょうじょう",
    english: "certificate of award",
    explanation: "A document that certifies the receipt of an award or prize.",
    example: "彼は優秀な成績で{賞状}をもらった。\nHe received a certificate of award for his excellent performance.",
  },
  {
    kanji: "札",
    kana: "さつ",
    english: "bill・note・tag",
    explanation: "Refers to paper money or a tag used for identification.",
    example: "彼はミスをしないように、注意してお{札}を数えた。\nHe carefully counted the bills to avoid making mistakes.",
  },
  {
    kanji: "礼",
    kana: "れい",
    english: "thanks・etiquette・bow",
    explanation: "Used to express gratitude or refer to manners and customs.",
    example: "彼は丁寧に{礼}を言った。\nHe expressed his thanks politely.",
  },
  {
    kanji: "姿",
    kana: "すがた",
    english: "figure・appearance・form",
    explanation: "Refers to the shape or appearance of a person or object.",
    example: "彼女が歩いている{姿}が窓から見えた。\nI saw her figure walking from the window.",
  },
  {
    kanji: "姿勢",
    kana: "しせい",
    english: "posture・attitude・stance",
    explanation: "Refers to the way one holds their body or their attitude towards something.",
    example: "彼は常に前向きな{姿勢}を持っている。\nHe always has a positive attitude.",
  },
  {
    kanji: "根",
    kana: "ね",
    english: "root・origin・basis",
    explanation: "Refers to the fundamental source or basis of something.",
    example: "草は{根}から抜かないと、すぐに生えてきてしまう。\nIf you don't pull the grass out from the root, it will quickly grow back.",
  },
  {
    kanji: "幹",
    kana: "みき",
    english: "trunk・main part・stem",
    explanation: "Refers to the main stem of a tree or the central part of something.",
    example: "木の{幹}は太くて丈夫だ。\nThe trunk of the tree is thick and sturdy.",
  },
  {
    kanji: "茎",
    kana: "くき",
    english: "stem・stalk",
    explanation: "Refers to the slender part of a plant that supports leaves and flowers.",
    example: "花の{茎}が折れてしまった。\nThe stem of the flower has broken.",
  },
  {
    kanji: "劇",
    kana: "げき",
    english: "drama・play・theatre",
    explanation: "Refers to a performance or play, often involving acting and storytelling.",
    example: "週末、彼女と{劇}を観に行く予定だ。\nI plan to go see a play with her this weekend.",
  },
  {
    kanji: "木造",
    kana: "もくぞう",
    english: "wooden structure・made of wood",
    explanation: "Refers to buildings or structures constructed primarily from wood.",
    example: "{木造}のアパートは地震に弱いことがある。\nWooden apartments can be vulnerable to earthquakes.",
  },
  {
    kanji: "目印",
    kana: "めじるし",
    english: "landmark・sign・mark",
    explanation: "A recognizable feature or sign used for navigation or identification.",
    example: "自分のかさがどれかわかるように{目印}をつけた。\nI put a mark on my umbrella so I could recognize it.",
  },
  {
    kanji: "候補",
    kana: "こうほ",
    english: "candidate・nominee・prospect",
    explanation: "Refers to a person or thing being considered for a position or award.",
    example: "彼女はオリンピック出場選手の{候補}に選ばれた。\nShe was selected as a candidate for the Olympic team.",
  },
  {
    kanji: "破片",
    kana: "はへん",
    english: "fragment・piece・shard",
    explanation: "Refers to a small piece or fragment of a larger object that has broken.",
    example: "ガラスの{破片}で指を切ってしまった。\nI cut my finger on a shard of glass.",
  },
  {
    kanji: "予防",
    kana: "よぼう",
    english: "prevention・precaution",
    explanation: "Refers to actions taken to prevent illness or accidents.\n悪いこと前に準備すること。",
    example: "風邪を{予防}するために、マスクを買った。\nI bought a mask to prevent catching a cold.",
  },
  {
    kanji: "防ぐ",
    kana: "ふせぐ",
    english: "to prevent・to defend・to protect",
    explanation: "To take measures to stop something undesirable from happening.\n悪いことから守ること。",
    example: "火事を{防ぐ}ために、消火器を設置した。\nWe installed fire extinguishers to prevent fires.",
  },
  {
    kanji: "公共",
    kana: "こうきょう",
    english: "public・community",
    explanation: "Refers to things that are shared by the community or accessible to all people.",
    example: "{公共}の場ではマナーを守りましょう。\nLet's have good manners in public places.",
  },
  {
    kanji: "情景",
    kana: "じょうけい",
    english: "scene・view・landscape",
    explanation: "Refers to a picturesque or emotional scene or view.",
    example: "昔聴いていた曲を聴くと、そのころの{情景}が目に浮かぶ。\nWhen I listen to a song I used to hear, the scenes from that time come to mind.",
  },
  {
    kanji: "装置",
    kana: "そうち",
    english: "device・equipment・apparatus",
    explanation: "Refers to a piece of equipment or machinery designed for a specific purpose.",
    example: "飛行機には安全を守るための{装置}がある。\nThere is equipment on the airplane to ensure safety.",
  },
  {
    kanji: "気配",
    kana: "けはい",
    english: "sign・indication・presence",
    explanation: "Refers to a sign or indication of something, often related to atmosphere or presence.",
    example: "涼しい日が続き、秋の{気配}が感じられる。\nWith the continuation of cool days, one can feel the signs of autumn.",
  },
  {
    kanji: "気配り",
    kana: "きくばり",
    english: "consideration・thoughtfulness・attentiveness",
    explanation: "The act of being considerate and attentive to the needs of others.",
    example: "彼女はいつも周りへの{気配り}を忘れない。\nShe always remembers to be considerate of those around her.",
  },
  {
    kanji: "民家",
    kana: "みんか",
    english: "private house・residential house",
    explanation: "Refers to a house where people live, as opposed to public buildings.",
    example: " 使われていない{民家}をレストランとして利用する。\nI'll use an unused private house as a restaurant.",
  },
  {
    kanji: "現状",
    kana: "げんじょう",
    english: "current situation・status quo",
    explanation: "Refers to the present state or condition of something.",
    example: "上司に仕事の{現状}を報告した。\nI reported the current situation of the work to my boss.",
  },
  {
    kanji: "入居",
    kana: "にゅうきょ",
    english: "moving in・occupancy",
    explanation: "Refers to the act of moving into a new residence or building.",
    example: "すぐ{入居}できる部屋を探しています。\nI am looking for a room that I can move into immediately.",
  },
  {
    kanji: "封筒",
    kana: "ふうとう",
    english: "envelope",
    explanation: "A flat paper container used to enclose letters or documents.",
    example: "お金が入った{封筒}を彼に渡した。\nI gave him an envelope containing money.",
  },
  {
    kanji: "対象",
    kana: "たいしょう",
    english: "target・object・subject",
    explanation: "Refers to the object or subject of an action or study.",
    example: "この調査は女性を{対象}に行っています。\nThis survey is conducted targeting women.",
  },
  {
    kanji: "火災",
    kana: "かさい",
    english: "fire disaster・conflagration",
    explanation: "Refers to a large and destructive fire.",
    example: "家の近くで{火災}が起きたようだ。\nIt seems that a fire disaster occurred near the house.",
  },
  {
    kanji: "専攻",
    kana: "せんこう",
    english: "major・specialization",
    explanation: "Refers to the main field of study chosen by a student at a university.",
    example: "大学では文学を{専攻}していました。\nI majored in literature at university.",
  },
  {
    kanji: "受診",
    kana: "じゅしん",
    english: "medical consultation・seeing a doctor",
    explanation: "Refers to the act of visiting a medical professional for examination or treatment.",
    example: "おなかの調子が悪いので、内科を{受診}した。\nI visited the internal medicine department because my stomach was not feeling well.",
  },
  {
    kanji: "外科",
    kana: "げか",
    english: "surgery・surgical department",
    explanation: "A medical specialty that involves operative procedures to treat diseases or injuries.",
    example: "彼は{外科}で働いている医者です。\nHe is a doctor working in the surgical department.",
  },
  {
    kanji: "視察",
    kana: "しさつ",
    english: "inspection・observation visit",
    explanation: "Refers to a visit made to observe and evaluate a situation or condition.",
    example: "新しく工場を建てる場所へ{視察}に行った。\nI went to inspect the site where a new factory will be built.",
  },
  {
    kanji: "持参",
    kana: "じさん",
    english: "bringing・carrying",
    explanation: "Refers to the act of bringing or carrying something with oneself.\n自分で何かを持って行くこと。",
    example: "会議には資料を{持参}してください。\nPlease bring the materials to the meeting.",
  },
  {
    kanji: "警告",
    kana: "けいこく",
    english: "warning・advice・caution",
    explanation: "Refers to a statement or signal that indicates a potential danger or problem.",
    example: "スピードの出しすぎは危険だと{警告}された。\nI was warned that speeding is dangerous.",
  },
  {
    kanji: "製造",
    kana: "せいぞう",
    english: "manufacturing・production",
    explanation: "Refers to the process of making goods or products, especially on a large scale.\n作ること。",
    example: "彼女は小さな部品を{製造}する工場で働いている。\nShe works at a factory that manufactures small parts.",
  },
  {
    kanji: "講演",
    kana: "こうえん",
    english: "lecture・speech・talk",
    explanation: "Refers to a formal talk given to an audience on a specific topic.",
    example: "新しい働き方について{講演}する。\nI will give a lecture about new ways of working.",
  },
  {
    kanji: "講演会",
    kana: "こうえんかい",
    english: "lecture meeting・seminar",
    explanation: "An event where a lecture or speech is given to an audience.",
    example: "有名な作家の{講演会}に参加した。\nI attended a lecture meeting by a famous author.",
  },
  {
    kanji: "増加",
    kana: "ぞうか",
    english: "increase・growth・rise",
    explanation: "Refers to the act of becoming larger in number or amount.",
    example: "最近、観光客の数が{増加}している。\nRecently, the number of tourists is increasing.",
  },
  {
    kanji: "減少",
    kana: "げんしょう",
    english: "decrease・reduction・decline",
    explanation: "Refers to the act of becoming smaller in number or amount.",
    example: "今年は事故の数が{減少}した。\nThe number of accidents decreased this year.",
  },
  {
    kanji: "参照",
    kana: "さんしょう",
    english: "reference・consultation",
    explanation: "Refers to the act of looking at or consulting information for guidance.",
    example: "次のページにあるグラフを{参照}してください。\nPlease refer to the graph on the next page.",
  },
  {
    kanji: "参考",
    kana: "さんこう",
    english: "reference・consultation・guidance",
    explanation: "Refers to information or materials used for guidance or consultation.",
    example: "この本は研究の{参考}になる。\nThis book is useful for research reference.",
  },
  {
    kanji: "照明",
    kana: "しょうめい",
    english: "lighting・illumination",
    explanation: "Refers to the use of light to illuminate a space or object.",
    example: "部屋の{照明}を明るくした。\nI brightened the lighting in the room.",
  },
  {
    kanji: "照らす",
    kana: "てらす",
    english: "to illuminate・to shine on",
    explanation: "To light up or shine light on something.",
    example: "懐中電灯で道を{照らす}。\nI illuminate the path with a flashlight.",
  },
  {
    kanji: "照らし合わせる",
    kana: "てらしあわせる",
    english: "to cross-check・to compare",
    explanation: "To compare two or more pieces of information to ensure accuracy or consistency.",
    example: "データを{照らし合わせる}ことで、誤りを見つけた。\nBy cross-checking the data, I found an error.",
  },
  {
    kanji: "収納",
    kana: "しゅうのう",
    english: "storage・putting away",
    explanation: "Refers to the act of storing or putting away items in an organized manner.\n決まった場所に物を入れておくという意味だ",
    sameMeaning: "しまうっていう意味もある。",
    example: "寒くなってきたので夏服を箱に{収納}する。\nAs it is getting colder, I will store my summer clothes in a box.",
  },
  {
    kanji: "収める",
    kana: "おさめる",
    english: "to obtain・to achieve・to settle",
    explanation: "To obtain results, achieve success, or settle disputes.",
    example: "彼は試験で良い成績を{収める}ことができた。\nHe was able to achieve good results in the exam.",
  },
  {
    kanji: "納める",
    kana: "おさめる",
    english: "to pay・to supply・to store",
    explanation: "To pay taxes or fees, to supply goods, or to store items properly.",
    example: "税金を期日までに{納める}必要がある。\nIt is necessary to pay taxes by the deadline.",
  },
  {
    kanji: "張る",
    kana: "はる",
    english: "to stretch・to stick・to affix",
    explanation: "To stretch something tight, to stick or affix something to a surface.",
    example: "二人で協力してテントを{張る}。\nWe work together to pitch the tent.",
  },
  {
    kanji: "折る",
    kana: "おる",
    english: "to fold・to break・to bend",
    explanation: "To fold paper or fabric, to break something, or to bend an object.",
    example: "紙を三つに{折る}。\nI fold the paper into three parts.",
  },
  {
    kanji: "補う",
    kana: "おぎなう",
    english: "to supplement・to compensate・to make up for",
    explanation: "To add something to make up for a deficiency or to compensate for a lack.\n足りないところ足すという意味だ。",
    example: "運動しているときは、十分な水分を{補う}と良い。\nWhen exercising, it is good to supplement with enough water.",
  }
];