export const NIHONGO_NO_MORI_MOJI_GOI_N2: JLPTReview[] = [
  {
    kanji: "賞",
    kana: "しょう",
    english: "prize・ award・reward",
    explanation: "Used to refer to recognition given for achievement in various fields.",
    example: "彼の作品は必ず{賞}を取るだろう。\nHis work is sure to win a prize.",
  },
  {
    kanji: "金賞",
    kana: "きんしょう",
    english: "gold medal・first prize",
    explanation: "The highest award given in competitions or contests.",
    example: "彼女は大会で{金賞}を受賞した。\nShe received the gold medal at the competition.",
  },
  {
    kanji: "賞状",
    kana: "しょうじょう",
    english: "certificate of award",
    explanation: "A document that certifies the receipt of an award or prize.",
    example: "彼は優秀な成績で{賞状}をもらった。\nHe received a certificate of award for his excellent performance.",
  },
  {
    kanji: "札",
    kana: "さつ",
    english: "bill・note・tag",
    explanation: "Refers to paper money or a tag used for identification.",
    example: "彼はミスをしないように、注意してお{札}を数えた。\nHe carefully counted the bills to avoid making mistakes.",
  },
  {
    kanji: "礼",
    kana: "れい",
    english: "thanks・etiquette・bow",
    explanation: "Used to express gratitude or refer to manners and customs.",
    example: "彼は丁寧に{礼}を言った。\nHe expressed his thanks politely.",
  },
  {
    kanji: "姿",
    kana: "すがた",
    english: "figure・appearance・form",
    explanation: "Refers to the shape or appearance of a person or object.",
    example: "彼女が歩いている{姿}が窓から見えた。\nI saw her figure walking from the window.",
  },
  {
    kanji: "姿勢",
    kana: "しせい",
    english: "posture・attitude・stance",
    explanation: "Refers to the way one holds their body or their attitude towards something.",
    example: "彼は常に前向きな{姿勢}を持っている。\nHe always has a positive attitude.",
  },
  {
    kanji: "根",
    kana: "ね",
    english: "root・origin・basis",
    explanation: "Refers to the fundamental source or basis of something.",
    example: "草は{根}から抜かないと、すぐに生えてきてしまう。\nIf you don't pull the grass out from the root, it will quickly grow back.",
  },
  {
    kanji: "幹",
    kana: "みき",
    english: "trunk・main part・stem",
    explanation: "Refers to the main stem of a tree or the central part of something.",
    example: "木の{幹}は太くて丈夫だ。\nThe trunk of the tree is thick and sturdy.",
  },
  {
    kanji: "茎",
    kana: "くき",
    english: "stem・stalk",
    explanation: "Refers to the slender part of a plant that supports leaves and flowers.",
    example: "花の{茎}が折れてしまった。\nThe stem of the flower has broken.",
  },
  {
    kanji: "劇",
    kana: "げき",
    english: "drama・play・theatre",
    explanation: "Refers to a performance or play, often involving acting and storytelling.",
    example: "週末、彼女と{劇}を観に行く予定だ。\nI plan to go see a play with her this weekend.",
  },
  {
    kanji: "木造",
    kana: "もくぞう",
    english: "wooden structure・made of wood",
    explanation: "Refers to buildings or structures constructed primarily from wood.",
    example: "{木造}のアパートは地震に弱いことがある。\nWooden apartments can be vulnerable to earthquakes.",
  },
  {
    kanji: "目印",
    kana: "めじるし",
    english: "landmark・sign・mark",
    explanation: "A recognizable feature or sign used for navigation or identification.",
    example: "自分のかさがどれかわかるように{目印}をつけた。\nI put a mark on my umbrella so I could recognize it.",
  },
  {
    kanji: "候補",
    kana: "こうほ",
    english: "candidate・nominee・prospect",
    explanation: "Refers to a person or thing being considered for a position or award.",
    example: "彼女はオリンピック出場選手の{候補}に選ばれた。\nShe was selected as a candidate for the Olympic team.",
  },
  {
    kanji: "破片",
    kana: "はへん",
    english: "fragment・piece・shard",
    explanation: "Refers to a small piece or fragment of a larger object that has broken.",
    example: "ガラスの{破片}で指を切ってしまった。\nI cut my finger on a shard of glass.",
  },
  {
    kanji: "予防",
    kana: "よぼう",
    english: "prevention・precaution",
    explanation: "Refers to actions taken to prevent illness or accidents.\n悪いこと前に準備すること。",
    example: "風邪を{予防}するために、マスクを買った。\nI bought a mask to prevent catching a cold.",
  },
  {
    kanji: "防ぐ",
    kana: "ふせぐ",
    english: "to prevent・to defend・to protect",
    explanation: "To take measures to stop something undesirable from happening.\n悪いことから守ること。",
    example: "火事を{防ぐ}ために、消火器を設置した。\nWe installed fire extinguishers to prevent fires.",
  },
  {
    kanji: "公共",
    kana: "こうきょう",
    english: "public・community",
    explanation: "Refers to things that are shared by the community or accessible to all people.",
    example: "{公共}の場ではマナーを守りましょう。\nLet's have good manners in public places.",
  },
  {
    kanji: "情景",
    kana: "じょうけい",
    english: "scene・view・landscape",
    explanation: "Refers to a picturesque or emotional scene or view.",
    example: "昔聴いていた曲を聴くと、そのころの{情景}が目に浮かぶ。\nWhen I listen to a song I used to hear, the scenes from that time come to mind.",
  },
  {
    kanji: "装置",
    kana: "そうち",
    english: "device・equipment・apparatus",
    explanation: "Refers to a piece of equipment or machinery designed for a specific purpose.",
    example: "飛行機には安全を守るための{装置}がある。\nThere is equipment on the airplane to ensure safety.",
  },
  {
    kanji: "気配",
    kana: "けはい",
    english: "sign・indication・presence",
    explanation: "Refers to a sign or indication of something, often related to atmosphere or presence.",
    example: "涼しい日が続き、秋の{気配}が感じられる。\nWith the continuation of cool days, one can feel the signs of autumn.",
  },
  {
    kanji: "気配り",
    kana: "きくばり",
    english: "consideration・thoughtfulness・attentiveness",
    explanation: "The act of being considerate and attentive to the needs of others.",
    example: "彼女はいつも周りへの{気配り}を忘れない。\nShe always remembers to be considerate of those around her.",
  },
  {
    kanji: "民家",
    kana: "みんか",
    english: "private house・residential house",
    explanation: "Refers to a house where people live, as opposed to public buildings.",
    example: " 使われていない{民家}をレストランとして利用する。\nI'll use an unused private house as a restaurant.",
  },
  {
    kanji: "現状",
    kana: "げんじょう",
    english: "current situation・status quo",
    explanation: "Refers to the present state or condition of something.",
    example: "上司に仕事の{現状}を報告した。\nI reported the current situation of the work to my boss.",
  },
  {
    kanji: "入居",
    kana: "にゅうきょ",
    english: "moving in・occupancy",
    explanation: "Refers to the act of moving into a new residence or building.",
    example: "すぐ{入居}できる部屋を探しています。\nI am looking for a room that I can move into immediately.",
  },
  {
    kanji: "封筒",
    kana: "ふうとう",
    english: "envelope",
    explanation: "A flat paper container used to enclose letters or documents.",
    example: "お金が入った{封筒}を彼に渡した。\nI gave him an envelope containing money.",
  },
  {
    kanji: "対象",
    kana: "たいしょう",
    english: "target・object・subject",
    explanation: "Refers to the object or subject of an action or study.",
    example: "この調査は女性を{対象}に行っています。\nThis survey is conducted targeting women.",
  },
  {
    kanji: "火災",
    kana: "かさい",
    english: "fire disaster・conflagration",
    explanation: "Refers to a large and destructive fire.",
    example: "家の近くで{火災}が起きたようだ。\nIt seems that a fire disaster occurred near the house.",
  },
  {
    kanji: "専攻",
    kana: "せんこう",
    english: "major・specialization",
    explanation: "Refers to the main field of study chosen by a student at a university.",
    example: "大学では文学を{専攻}していました。\nI majored in literature at university.",
  },
  {
    kanji: "受診",
    kana: "じゅしん",
    english: "medical consultation・seeing a doctor",
    explanation: "Refers to the act of visiting a medical professional for examination or treatment.",
    example: "おなかの調子が悪いので、内科を{受診}した。\nI visited the internal medicine department because my stomach was not feeling well.",
  },
  {
    kanji: "外科",
    kana: "げか",
    english: "surgery・surgical department",
    explanation: "A medical specialty that involves operative procedures to treat diseases or injuries.",
    example: "彼は{外科}で働いている医者です。\nHe is a doctor working in the surgical department.",
  },
  {
    kanji: "視察",
    kana: "しさつ",
    english: "inspection・observation visit",
    explanation: "Refers to a visit made to observe and evaluate a situation or condition.",
    example: "新しく工場を建てる場所へ{視察}に行った。\nI went to inspect the site where a new factory will be built.",
  },
  {
    kanji: "持参",
    kana: "じさん",
    english: "bringing・carrying",
    explanation: "Refers to the act of bringing or carrying something with oneself.\n自分で何かを持って行くこと。",
    example: "会議には資料を{持参}してください。\nPlease bring the materials to the meeting.",
  },
  {
    kanji: "警告",
    kana: "けいこく",
    english: "warning・advice・caution",
    explanation: "Refers to a statement or signal that indicates a potential danger or problem.",
    example: "スピードの出しすぎは危険だと{警告}された。\nI was warned that speeding is dangerous.",
  },
  {
    kanji: "製造",
    kana: "せいぞう",
    english: "manufacturing・production",
    explanation: "Refers to the process of making goods or products, especially on a large scale.\n作ること。",
    example: "彼女は小さな部品を{製造}する工場で働いている。\nShe works at a factory that manufactures small parts.",
  },
  {
    kanji: "講演",
    kana: "こうえん",
    english: "lecture・speech・talk",
    explanation: "Refers to a formal talk given to an audience on a specific topic.",
    example: "新しい働き方について{講演}する。\nI will give a lecture about new ways of working.",
  },
  {
    kanji: "講演会",
    kana: "こうえんかい",
    english: "lecture meeting・seminar",
    explanation: "An event where a lecture or speech is given to an audience.",
    example: "有名な作家の{講演会}に参加した。\nI attended a lecture meeting by a famous author.",
  },
  {
    kanji: "増加",
    kana: "ぞうか",
    english: "increase・growth・rise",
    explanation: "Refers to the act of becoming larger in number or amount.",
    example: "最近、観光客の数が{増加}している。\nRecently, the number of tourists is increasing.",
  },
  {
    kanji: "減少",
    kana: "げんしょう",
    english: "decrease・reduction・decline",
    explanation: "Refers to the act of becoming smaller in number or amount.",
    example: "今年は事故の数が{減少}した。\nThe number of accidents decreased this year.",
  },
  {
    kanji: "参照",
    kana: "さんしょう",
    english: "reference・consultation",
    explanation: "Refers to the act of looking at or consulting information for guidance.",
    example: "次のページにあるグラフを{参照}してください。\nPlease refer to the graph on the next page.",
  },
  {
    kanji: "参考",
    kana: "さんこう",
    english: "reference・consultation・guidance",
    explanation: "Refers to information or materials used for guidance or consultation.",
    example: "この本は研究の{参考}になる。\nThis book is useful for research reference.",
  },
  {
    kanji: "照明",
    kana: "しょうめい",
    english: "lighting・illumination",
    explanation: "Refers to the use of light to illuminate a space or object.",
    example: "部屋の{照明}を明るくした。\nI brightened the lighting in the room.",
  },
  {
    kanji: "照らす",
    kana: "てらす",
    english: "to illuminate・to shine on",
    explanation: "To light up or shine light on something.",
    example: "懐中電灯で道を{照らす}。\nI illuminate the path with a flashlight.",
  },
  {
    kanji: "照らし合わせる",
    kana: "てらしあわせる",
    english: "to cross-check・to compare",
    explanation: "To compare two or more pieces of information to ensure accuracy or consistency.",
    example: "データを{照らし合わせる}ことで、誤りを見つけた。\nBy cross-checking the data, I found an error.",
  },
  {
    kanji: "収納",
    kana: "しゅうのう",
    english: "storage・putting away",
    explanation: "Refers to the act of storing or putting away items in an organized manner.\n決まった場所に物を入れておくという意味だ",
    sameMeaning: "しまうっていう意味もある。",
    example: "寒くなってきたので夏服を箱に{収納}する。\nAs it is getting colder, I will store my summer clothes in a box.",
  },
  {
    kanji: "収める",
    kana: "おさめる",
    english: "to obtain・to achieve・to settle",
    explanation: "To obtain results, achieve success, or settle disputes.",
    example: "彼は試験で良い成績を{収める}ことができた。\nHe was able to achieve good results in the exam.",
  },
  {
    kanji: "納める",
    kana: "おさめる",
    english: "to pay・to supply・to store",
    explanation: "To pay taxes or fees, to supply goods, or to store items properly.\nUsually used as a set with tax related words.",
    example: "税金を期日までに{納める}必要がある。\nIt is necessary to pay taxes by the deadline.",
  },
  {
    kanji: "張る",
    kana: "はる",
    english: "to stretch・to stick・to affix",
    explanation: "To stretch something tight, to stick or affix something to a surface.",
    example: "二人で協力してテントを{張る}。\nWe work together to pitch the tent.",
  },
  {
    kanji: "折る",
    kana: "おる",
    english: "to fold・to break・to bend",
    explanation: "To fold paper or fabric, to break something, or to bend an object.",
    example: "紙を三つに{折る}。\nI fold the paper into three parts.",
  },
  {
    kanji: "補う",
    kana: "おぎなう",
    english: "to supplement・to compensate・to make up for",
    explanation: "To add something to make up for a deficiency or to compensate for a lack.\n足りないところ足すという意味だ。",
    example: "運動しているときは、十分な水分を{補う}と良い。\nWhen exercising, it is good to supplement with enough water.",
  },
  {
    kanji: "賄う",
    kana: "まかなう",
    english: "to cover expenses・to provide for・to manage",
    explanation: "To cover expenses, provide for needs, or manage resources effectively.\n必要なものを用意すること\nお金とか食べ物などに対して使うこと。",
    example: "彼はアルバイトで学費を{賄って}いる。\nHe manages to cover his tuition fees with a part-time job.",
  },
  {
    kanji: "養う",
    kana: "やしなう",
    english: "to nurture・to support・to cultivate",
    explanation: "To nurture or support the growth and development of someone or something.",
    example: "親は子供を{養う}責任がある。\nParents have the responsibility to nurture their children.",
  },
  {
    kanji: "栄養",
    kana: "えいよう",
    english: "nutrition・nourishment",
    explanation: "Refers to the substances that provide nourishment and are essential for growth and health.",
    example: "バランスの取れた食事は良い{栄養}をもたらす。\nA balanced diet provides good nutrition.",
  },
  {
    kanji: "破れる",
    kana: "やぶれる",
    english: "to be torn・to be defeated・to break",
    explanation: "To become torn, to be defeated in a competition, or to break apart.",
    example: "お気に入りの服が{破れて}しまった。\nMy favorite clothes got torn.",
  },
  {
    kanji: "壊れる",
    kana: "こわれる",
    english: "to be broken・to be damaged",
    explanation: "To become broken or damaged, typically referring to objects or machinery.",
    example: "古い時計が{壊れて}しまった。\nThe old clock broke down.",
  },
  {
    kanji: "乱れる",
    kana: "みだれる",
    english: "to be disordered・to be disturbed・to be messy",
    explanation: "To become disordered, disturbed, or messy, often referring to appearance or behavior.",
    sameMeaning: "ぐちゃぐちゃになるという意味もある",
    example: "風で髪が{乱れて}しまった。\nMy hair got messy because of the wind.",
  },
  {
    kanji: "塞ぐ",
    kana: "ふさぐ",
    english: "to block・to close・to cover",
    explanation: "To block, close, or cover an opening or passage.",
    example: "穴を{塞いで}ください。\nPlease block the hole.",
  },
  {
    kanji: "繋ぐ",
    kana: "つなぐ",
    english: "to connect・to link・to tie",
    explanation: "To connect, link, or tie things together.",
    example: "二人は公園で手を{繋いで}歩いていた。\nThe two were walking hand in hand in the park.",
  },
  {
    kanji: "稼ぐ",
    kana: "かせぐ",
    english: "to earn・to make money・to work",
    explanation: "To earn money or income through work or business activities.\n自分で働いたりしてお金を集めること。",
    example: "彼は一生懸命働いてお金を{稼いで}いる。\nHe is working hard to earn money.",
  },
  {
    kanji: "除く",
    kana: "のぞく",
    english: "to remove・to exclude・to eliminate",
    explanation: "To remove, exclude, or eliminate something from a group or situation.",
    example: "この内容は一部を{除いて}全て真実です。\nThis content is all true except for a part.",
  },
  {
    kanji: "省く",
    kana: "はぶく",
    english: "to omit・to eliminate・to economize",
    explanation: "To omit, eliminate, or economize by cutting out unnecessary parts.",
    example: "時間を節約するために、詳細な説明を{省いた}。\nTo save time, I omitted the detailed explanation.",
  },
  {
    kanji: "退く",
    kana: "しりぞく",
    english: "to retreat・to withdraw・to step back",
    explanation: "To retreat, withdraw, or step back from a position or situation.",
    example: "危険を感じたので、その場から{退いた}。\nFeeling danger, I withdrew from the scene.",
  },
  {
    kanji: "抜く",
    kana: "ぬく",
    english: "to pull out・to extract・to omit",
    explanation: "To pull out, extract, or omit something from a place or context.",
    example: "虫歯を{抜く}ために歯医者に行った。\nI went to the dentist to have my cavity pulled out.",
  },
  {
    kanji: "無くす",
    kana: "なくす",
    english: "to lose・to get rid of・to eliminate",
    explanation: "To lose something, get rid of it, or eliminate it from one's possession.",
    example: "彼は鍵を{無くして}しまった。\nHe lost his keys.",
  },
  {
    kanji: "離す",
    kana: "はなす",
    english: "to separate・to detach・to let go",
    explanation: "To separate, detach, or let go of something or someone.",
    example: "子供の手を{離さない}でください。\nPlease do not let go of the child's hand.",
  },
  {
    kanji: "距離",
    kana: "きょり",
    english: "distance・range",
    explanation: "Refers to the physical space between two points or objects.",
    example: "駅から家までの{距離}は約2キロです。\nThe distance from the station to the house is about 2 kilometers.",
  },
  {
    kanji: "限り",
    kana: "かぎり",
    english: "limit・extent・as far as",
    explanation: "Refers to the extent or limit of something, often indicating the maximum or minimum.",
    example: "小学生に{限り}、入場料は無料です。\nAdmission is free for elementary school students only.",
  },
  {
    kanji: "区切り",
    kana: "くぎり",
    english: "division・boundary・pause",
    explanation: "Refers to a division or boundary between sections, or a pause in speech or writing.",
    example: "文章の{区切り}をつけるために、改行を入れた。\nI inserted a line break to create a division in the text.",
  },
  {
    kanji: "嵌まる",
    kana: "はまる",
    english: "to fit・to be stuck・to be addicted",
    explanation: "To fit into a space, to be stuck in a situation, or to be addicted to something.",
    example: "この鍵はこの穴に{嵌る}。\nThis key fits into this hole.",
  },
  {
    kanji: "催す",
    kana: "もよおす",
    english: "to hold (an event)・to feel (symptoms)・to organize",
    explanation: "To hold an event or gathering, to feel symptoms of illness, or to organize something.",
    example: "来月、部長の送別会を{催す}予定です。\nWe plan to hold a farewell party for the manager next month.",
  },
  {
    kanji: "記す",
    kana: "しるす",
    english: "to write down・to note・to record",
    explanation: "To write down, note, or record information for future reference.",
    example: "重要なポイントをノートに{記す}。\nI write down important points in my notebook.",
  },
  {
    kanji: "日記",
    kana: "にっき",
    english: "diary・journal",
    explanation: "A personal record of daily events, thoughts, and experiences.",
    example: "毎晩、{日記}をつける習慣がある。\nI have a habit of keeping a diary every night.",
  },
  {
    kanji: "試す",
    kana: "ためす",
    english: "to try・to test・to experiment",
    explanation: "To try something out, test its effectiveness, or conduct an experiment.",
    example: "新しいレシピを{試して}みる。\nI will try out a new recipe.",
  },
  {
    kanji: "試験",
    kana: "しけん",
    english: "exam・test・examination",
    explanation: "A formal assessment of knowledge or skills in a particular subject.",
    example: "来週、数学の{試験}がある。\nI have a math exam next week.",
  },
  {
    kanji: "破る",
    kana: "やぶる",
    english: "to tear・to break・to violate",
    explanation: "To tear something apart, break a rule, or violate an agreement.",
    example: "彼は約束を{破って}しまった。\nHe broke his promise.",
  },
  {
    kanji: "勧める",
    kana: "すすめる",
    english: "to recommend・to advise・to encourage",
    explanation: "To recommend something, advise someone, or encourage action.",
    example: "友達に{勧められて}、ランニングを始めた。\nI started running because my friend recommended it.",
  },
  {
    kanji: "認める",
    kana: "みとめる",
    english: "to recognize・to admit・to approve",
    explanation: "To recognize someone's efforts, admit a fact, or approve a request.",
    example: "彼の才能を{認める}。\nI recognize his talent.",
  },
  {
    kanji: "求める",
    kana: "もとめる",
    english: "to seek・to request・to demand",
    explanation: "To seek help, request information, or demand action.",
    example: "助けを{求める}ために、警察に連絡した。\nI contacted the police to seek help.",
  },
  {
    kanji: "応える",
    kana: "こたえる",
    english: "to respond・to answer・to meet (expectations)",
    explanation: "To respond to a request, answer a question, or meet expectations.",
    example: "親の期待に{応える}ために努力する。\nI strive to meet my parents' expectations.",
  },
  {
    kanji: "反応",
    kana: "はんのう",
    english: "reaction・response",
    explanation: "Refers to a response or reaction to a stimulus, event, or situation.",
    example: "彼の提案に対する皆の{反応}は良かった。\nEveryone's reaction to his proposal was positive.",
  },
  {
    kanji: "異なる",
    kana: "ことなる",
    english: "to differ・to vary・to be different",
    explanation: "To be different from something else or to vary in characteristics.",
    example: "私と妹は、顔はそっくりだが性格は{異なる}。\nMy sister and I look alike, but our personalities are different.",
  },
  {
    kanji: "連なる",
    kana: "つらなる",
    english: "to extend・to stretch・to line up",
    explanation: "To extend in a line, stretch out, or be lined up in a series.",
    example: "山々が遠くまで{連なって}いる。\nThe mountains extend far into the distance.",
  },
  {
    kanji: "重なる",
    kana: "かさなる",
    english: "to overlap・to pile up・to coincide",
    explanation: "To overlap with each other, pile up, or coincide in time.",
    example: "予定が{重なって}しまい、困っている。\nMy schedules have overlapped, and I'm in trouble.",
  },
  {
    kanji: "改める",
    kana: "あらためる",
    english: "to change・to reform・to revise",
    explanation: "To change one's behavior, reform a system, or revise a document.",
    example: "組織のルールを{改める}。\nI will revise the organization's rules.",
  },
  {
    kanji: "貯める",
    kana: "ためる",
    english: "to save・to accumulate・to store",
    explanation: "To save money, accumulate resources, or store items for future use.",
    example: "毎月少しずつお金を{貯める}。\nI save money little by little every month.",
  },
  {
    kanji: "含める",
    kana: "ふくめる",
    english: "to include・to contain・to involve",
    explanation: "To include something in a group, contain certain elements, or involve others in an activity.",
    example: "参加者全員をリストに{含める}。\nI will include all participants in the list.",
  },
  {
    kanji: "荒い",
    kana: "あらい",
    english: "rough・wild・coarse",
    explanation: "Describes something that is rough in texture, wild in behavior, or coarse in nature.",
    example: "彼は言葉づかいが{荒い}。\nHe has a rough way of speaking.",
  },
  {
    kanji: "性格が荒い",
    kana: "せいかくがあらい",
    english: "to have a rough personality・to be hot-tempered",
    explanation: "Describes someone who has a rough or harsh personality, often quick to anger.",
    example: "彼は{性格が荒い}ので、注意が必要だ。\nHe has a rough personality, so caution is necessary.",
  },
  {
    kanji: "硬い",
    kana: "かたい",
    english: "hard・solid・stiff",
    explanation: "Describes something that is hard in texture, solid in form, or stiff in movement.\n体がやわらかくないと言いたい時使う。石のようにかたい、周りから力を入れても形が変わらないようなかたさに使う漢字です。",
    example: "ストレッチをしないと体が{硬く}なる。\nIf you don't stretch, your body becomes stiff.",
  },
  {
    kanji: "固い",
    kana: "かたい",
    english: "firm・solid・unyielding",
    explanation: "Describes something that is firm in structure, solid in composition, or unyielding in nature.\n簡単に離れないかたさに使う。",
    example: "このパンは外側が{固い}。\nThe outside of this bread is firm.",
  },
  {
    kanji: "堅い",
    kana: "かたい",
    english: "reliable・serious・steadfast",
    explanation: "Describes someone who is reliable in character, serious in demeanor, or steadfast in principles.\n確実ですぐに壊れないようなものに使う。",
    example: "彼は{堅い}性格で、約束を守る。\nHe has a reliable personality and keeps his promises.",
  },
  {
    kanji: "渋い",
    kana: "しぶい",
    english: "astringent・bitter・restrained",
    explanation: "Describes a taste that is astringent or bitter, or a style that is restrained and understated.",
    example: "このお茶は{渋くて}飲めない。\nThis tea is too bitter to drink.",
  },
  {
    kanji: "酷い",
    kana: "ひどい",
    english: "terrible・awful・severe",
    explanation: "Describes something that is terrible in quality, awful in condition, or severe in nature.",
    example: "彼の行動は{酷い}。\nHis behavior is terrible.",
  },
  {
    kanji: "暗い",
    kana: "くらい",
    english: "dark・gloomy・dim",
    explanation: "Describes a lack of light, a gloomy atmosphere, or a dim environment.",
    example: "部屋が{暗くて}何も見えない。\nThe room is so dark that I can't see anything.",
  },
  {
    kanji: "薄い",
    kana: "うすい",
    english: "thin・weak・light",
    explanation: "Describes something that is thin in thickness, weak in intensity, or light in color.",
    example: "資料を印刷したが、文字が{薄くて}読めない。\nI printed the document, but the text is too light to read.",
  },
  {
    kanji: "大幅",
    kana: "おおはば",
    english: "large-scale・significant・substantial",
    explanation: "Refers to something that is large in scale, significant in impact, or substantial in amount.",
    example: "出発時間が、{大幅}に変更された。\nThe departure time was changed significantly.\n大幅に変更される is very often used as a set. Often used with 時間が..., 予定が..., 値段が...",
  },
  {
    kanji: "幅",
    kana: "はば",
    english: "width・breadth・range",
    explanation: "Refers to the measurement of how wide something is, or the range of options available.",
    example: "この川の{幅}は約10メートルです。\nThe width of this river is about 10 meters.",
  },
  {
    kanji: "大福",
    kana: "だいふく",
    english: "daifuku (Japanese sweet)・mochi filled with sweet bean paste",
    explanation: "A traditional Japanese sweet made of mochi (glutinous rice cake) filled with sweet red bean paste.",
    example: "{大福}は日本の人気のお菓子です。\nDaifuku is a popular Japanese sweet.",
  },
  {
    kanji: "深刻",
    kana: "しんこく",
    english: "serious・severe・grave",
    explanation: "Describes a situation or problem that is serious in nature, severe in impact, or grave in consequences.",
    example: "今年は雨が少なく、{深刻な}水不足となった。\nThis year, there was little rain, leading to a serious water shortage.",
  },
  {
    kanji: "巨大",
    kana: "きょだい",
    english: "huge・gigantic・enormous",
    explanation: "Describes something that is huge in size, gigantic in scale, or enormous in magnitude.",
    example: "海で遊んでいたら、{巨大な}たこが現れた。\nWhile playing in the sea, a huge octopus appeared.",
  },
  {
    kanji: "巨人",
    kana: "きょじん",
    english: "giant・Titan",
    explanation: "Refers to a mythical or fictional giant being, often depicted as large and powerful.\nとても大きい人や生き物のこと。巨大な人。",
    example: "昔話にはよく{巨人}が登場する。\nGiants often appear in fairy tales.",
  },
  {
    kanji: "豊富",
    kana: "ほうふ",
    english: "abundant・plentiful・rich",
    explanation: "Describes something that is abundant in quantity, plentiful in resources, or rich in variety.",
    sameMeaning: "たくさんある・いっぱいある",
    example: "この地域は、魚や貝が{豊富}にとれることで有名だ。\nThis area is famous for its abundant fish and shellfish.",
  },
  {
    kanji: "富士山",
    kana: "ふじさん",
    english: "Mount Fuji",
    explanation: "The highest mountain in Japan, known for its iconic symmetrical cone shape and cultural significance.",
    example: "{富士山}は日本で一番高い山です。\nMount Fuji is the tallest mountain in Japan.",
  },
  {
    kanji: "安価",
    kana: "あんか",
    english: "inexpensive・cheap・affordable",
    explanation: "Describes something that is inexpensive in cost, cheap in price, or affordable for most people.",
    example: "{安価な}食材を使って、おいしい料理を作るのが得意だ。\nI am good at making delicious dishes using inexpensive ingredients.",
  },
  {
    kanji: "安値",
    kana: "やすね",
    english: "low price・cheap price",
    explanation: "Refers to a price that is low or inexpensive compared to the usual market value.",
    example: "この店は{安値}で商品を提供している。\nThis store offers products at low prices.",
  },
  {
    kanji: "存分",
    kana: "ぞんぶん",
    english: "to one's heart's content・fully・satisfactorily",
    explanation: "Refers to doing something to the fullest extent or to one's heart's content.",
    example: "久しぶりの旅行を{存分}に楽しみたい。\nI want to fully enjoy my trip after a long time.",
  },
  {
    kanji: "満足",
    kana: "まんぞく",
    english: "satisfaction・contentment・fulfillment",
    explanation: "Refers to a state of being satisfied, content, or fulfilled with something.",
    example: "美味しい料理を食べて、{満足}した。\nI was satisfied after eating delicious food.",
  },
  {
    kanji: "存分に味わう",
    kana: "ぞんぶんにあじわう",
    english: "to savor to the fullest・to enjoy thoroughly",
    explanation: "To fully savor or enjoy something, often referring to food or experiences.",
    example: "旅行先の美味しい料理を{存分に味わう}。\nI will savor the delicious food at my travel destination to the fullest.",
  },
  {
    kanji: "全く〜ない",
    kana: "まったく〜ない",
    english: "not at all・completely not",
    explanation: "Used to emphasize that something is completely absent or does not happen at all.",
    sameMeaning: "全然〜ない・0％〜ない",
    example: "伊藤さんは、食べ物に{全く}関心が{ない}。\nMr. Ito has no interest in food at all.",
  },
  {
    kanji: "しばらく",
    kana: "しばらく",
    english: "for a while・for some time・a short period",
    explanation: "Refers to a short period of time or a temporary duration.\n少しの間っていう意味だ。",
    example: "{しばらく}休憩してから、また仕事を始めよう。\nLet's take a break for a while and then start working again.",
  },
  {
    kanji: "早速",
    kana: "さっそく",
    english: "immediately・right away・without delay",
    explanation: "Refers to doing something immediately or without any delay.\nすぐに何かをするという意味だ。",
    example: "では{早速}、作業を始めましょう。\nWell then, let's start the work right away.",
  },
  {
    kanji: "常に",
    kana: "つねに",
    english: "always・constantly・regularly",
    explanation: "Refers to something that happens regularly or is a constant occurrence.\nいつもっていう意味だ。",
    example: "祖母からもらった指輪を{常に}身に着けている。\nI always wear the ring I received from my grandmother.",
  },
  {
    kanji: "常時",
    kana: "じょうじ",
    english: "at all times・constantly・regularly",
    explanation: "Refers to something that occurs at all times or is constantly maintained.\nいつもっていう意味だ。",
    example: "この施設は{常時}監視カメラが作動している。\nThis facility has surveillance cameras operating at all times.",
  }
];