export const NIHONGO_NO_MORI_JLPT_N2: JLPTReview[] = [
  {
    kanji: "胃",
    kana: "い",
    english: "Stomach",
    explanation: "Refers to the stomach, an organ in the digestive system.",
    example: "彼は{胃}の調子が悪い。\nHe has a stomachache.",
  },
  {
    kanji: "裏",
    kana: "うら",
    english: "Back・Reverse side",
    explanation: "Refers to the back side or reverse side of something.",
    example: "この紙の{裏}に書いてください。\nPlease write on the back of this paper.",
  },
  {
    kanji: "噂",
    kana: "うわさ",
    english: "Rumor",
    explanation: "Refers to a piece of information or a story that is passed from person to person, often without confirmation of its truth.",
    example: "彼女についての{噂}を聞いた。\nI heard a rumor about her.",
  },
  {
    kanji: "餌",
    kana: "えさ",
    english: "Feed・Bait",
    explanation: "Refers to food given to animals or bait used to catch fish.",
    example: "魚に{餌}をあげる。\nI feed the fish.",
  },
  {
    kanji: "枝",
    kana: "えだ",
    english: "Branch・Twig",
    explanation: "Refers to a branch or twig of a tree.",
    example: "鳥が{枝}にとまっている。\nA bird is perched on the branch.",
  },
  {
    kanji: "襟",
    kana: "えり",
    english: "Collar",
    explanation: "Refers to the collar of a shirt or jacket.",
    example: "シャツの{襟}が汚れている。\nThe collar of the shirt is dirty.",
  },
  {
    kanji: "課",
    kana: "か",
    english: "Section・Lesson・Department",
    explanation: "Refers to a section or department within an organization.",
    example: "営業{課}で働いています。\nI work in the sales department.",
  },
  {
    kanji: "壁",
    kana: "かべ",
    english: "Wall",
    explanation: "Refers to a wall, a vertical structure that defines and sometimes protects an area.",
    example: "{壁}に絵を掛ける。\nI hang a picture on the wall.",
  },
  {
    kanji: "雷",
    kana: "かみなり",
    english: "Thunder・Lightning",
    explanation: "Refers to the natural phenomenon of thunder and lightning during a storm.",
    example: "{雷}が鳴っている。\nThe thunder is rumbling.",
  },
  {
    kanji: "缶",
    kana: "かん",
    english: "Can・Tin",
    explanation: "Refers to a metal container used for storing food or drinks.",
    example: "{缶}ジュースを買った。\nI bought a can of juice.",
  },
  {
    kanji: "雲",
    kana: "くも",
    english: "Cloud",
    explanation: "Refers to a visible mass of condensed water vapor floating in the atmosphere.",
    example: "空に{雲}が浮かんでいる。\nThere are clouds floating in the sky.",
  },
  {
    kanji: "煙",
    kana: "けむり",
    english: "Smoke",
    explanation: "Refers to the visible vapor and gases produced by burning or combustion.",
    example: "{煙}が立ち上っている。\nSmoke is rising.",
  },
  {
    kanji: "塩",
    kana: "しお",
    english: "Salt",
    explanation: "Refers to a mineral used for seasoning and preserving food.",
    example: "料理に{塩}を加える。\nI add salt to the dish.",
  },
  {
    kanji: "島",
    kana: "しま",
    english: "Island",
    explanation: "Refers to a landmass surrounded by water.",
    example: "夏に{島}へ旅行する。\nI will travel to an island in the summer.",
  },
  {
    kanji: "城",
    kana: "しろ",
    english: "Castle・Fortress",
    explanation: "Refers to a large fortified building or group of buildings.",
    example: "有名な{城}を見学した。\nI visited a famous castle.",
  },
  {
    kanji: "隅",
    kana: "すみ",
    english: "Corner",
    explanation: "Refers to the point or area where two lines or surfaces meet.",
    example: "部屋の{隅}に置く。\nI place it in the corner of the room.",
  },
  {
    kanji: "咳",
    kana: "せき",
    english: "Cough",
    explanation: "Refers to the act of expelling air from the lungs with a sudden sound.",
    example: "風邪で{咳}が出る。\nI have a cough because of a cold.",
  },
  {
    kanji: "底",
    kana: "そこ",
    english: "Bottom・Base",
    explanation: "Refers to the lowest part or point of something.",
    example: "箱の{底}に何かある。\nThere is something at the bottom of the box.",
  },
  {
    kanji: "像",
    kana: "ぞう",
    english: "Statue・Image",
    explanation: "Refers to a three-dimensional representation of a person or animal.",
    example: "有名な{像}を見た。\nI saw a famous statue.",
  },
  {
    kanji: "毒",
    kana: "どく",
    english: "Poison・Toxin",
    explanation: "Refers to a substance that can cause harm or death if ingested or absorbed.",
    example: "そのキノコは{毒}がある。\nThat mushroom is poisonous.",
  },
  {
    kanji: "謎",
    kana: "なぞ",
    english: "Mystery・Riddle",
    explanation: "Refers to something that is difficult to understand or explain.",
    example: "その事件は{謎}に包まれている。\nThe case is shrouded in mystery.",
  },
  {
    kanji: "鍋",
    kana: "なべ",
    english: "Pot・Pan",
    explanation: "Refers to a cooking vessel used for boiling or simmering food.",
    example: "{鍋}でスープを作る。\nI make soup in a pot.",
  },
  {
    kanji: "波",
    kana: "なみ",
    english: "Wave",
    explanation: "Refers to a moving ridge or swell on the surface of water.",
    example: "海の{波}が高い。\nThe waves in the sea are high.",
  },
  {
    kanji: "涙",
    kana: "なみだ",
    english: "Tears",
    explanation: "Refers to the drops of clear, salty liquid produced by the eyes when crying.",
    example: "彼女は{涙}を流した。\nShe shed tears.",
  },
  {
    kanji: "庭",
    kana: "にわ",
    english: "Garden・Yard",
    explanation: "Refers to an area of land, often near a house, used for growing plants or for outdoor activities.",
    example: "{庭}で花を育てる。\nI grow flowers in the garden.",
  },
  {
    kanji: "箸",
    kana: "はし",
    english: "Chopsticks",
    explanation: "Refers to a pair of small, slender sticks used as eating utensils in many Asian countries.",
    example: "{箸}でご飯を食べる。\nI eat rice with chopsticks.",
  },
  {
    kanji: "畑",
    kana: "はたけ",
    english: "Field・Farm",
    explanation: "Refers to a piece of land used for growing crops or vegetables.",
    example: "{畑}で野菜を育てる。\nI grow vegetables in the field.",
  },
  {
    kanji: "羽",
    kana: "はね",
    english: "Feather・Wing",
    explanation: "Refers to the light, flat structures that cover the bodies of birds and enable them to fly.",
    example: "鳥の{羽}が美しい。\nThe bird's feathers are beautiful.",
  },
  {
    kanji: "幅",
    kana: "はば",
    english: "Width・Breadth",
    explanation: "Refers to the measurement of something from side to side.",
    example: "この道の{幅}は広い。\nThe width of this road is wide.",
  },
  {
    kanji: "膝",
    kana: "ひざ",
    english: "Knee",
    explanation: "Refers to the joint between the thigh and the lower leg in humans.",
    example: "{膝}を曲げる。\nI bend my knee.",
  },
  {
    kanji: "袋",
    kana: "ふくろ",
    english: "Bag・Sack",
    explanation: "Refers to a flexible container used for carrying or storing items.",
    example: "買い物{袋}を持っている。\nI have a shopping bag.",
  },
  {
    kanji: "骨",
    kana: "ほね",
    english: "Bone",
    explanation: "Refers to the rigid organs that make up the skeleton of vertebrates.",
    example: "犬が{骨}をかじっている。\nThe dog is chewing on a bone.",
  },
  {
    kanji: "棒",
    kana: "ぼう",
    english: "Rod・Stick",
    explanation: "Refers to a long, thin, cylindrical object.",
    example: "釣り竿の{棒}が折れた。\nThe fishing rod broke.",
  },
  {
    kanji: "孫",
    kana: "まご",
    english: "Grandchild",
    explanation: "Refers to the child of one's son or daughter.",
    example: "彼は三人の{孫}がいる。\nHe has three grandchildren.",
  },
  {
    kanji: "湖",
    kana: "みずうみ",
    english: "Lake",
    explanation: "Refers to a large body of water surrounded by land.",
    example: "美しい{湖}を訪れた。\nI visited a beautiful lake.",
  },
  {
    kanji: "胸",
    kana: "むね",
    english: "Chest・Breast",
    explanation: "Refers to the front part of the body between the neck and the abdomen.",
    example: "{胸}が痛い。\nMy chest hurts.",
  },
  {
    kanji: "床",
    kana: "ゆか",
    english: "Floor",
    explanation: "Refers to the lower surface of a room on which one stands.",
    example: "{床}を掃除する。\nI clean the floor.",
  },
  {
    kanji: "寮",
    kana: "りょう",
    english: "Dormitory",
    explanation: "Refers to a building where students or workers live and sleep.",
    example: "大学の{寮}に住んでいる。\nI live in a university dormitory.",
  },
  {
    kanji: "量",
    kana: "りょう",
    english: "Quantity・Amount",
    explanation: "Refers to the amount or number of something.",
    example: "水の{量}を測る。\nI measure the amount of water.",
  },
  {
    kanji: "列",
    kana: "れつ",
    english: "Line・Row",
    explanation: "Refers to a series of people or things arranged in a straight line.",
    example: "バスの{列}に並ぶ。\nI line up for the bus.",
  },
  {
    kanji: "合図",
    kana: "あいず",
    english: "Signal・Sign",
    explanation: "Refers to a gesture, action, or sound that conveys information or instructions.",
    example: "出発の{合図}を送る。\nI give the signal to depart.",
  },
  {
    kanji: "以外",
    kana: "いがい",
    english: "Except・Other than・With the exception of",
    explanation: "Refers to something that is not included or is different from what has been mentioned.",
    example: "彼{以外}は全員来た。\nEveryone except him came.",
  },
  {
    kanji: "以後",
    kana: "いご",
    english: "After that・From now on",
    explanation: "Refers to the time following a specific point or event.",
    example: "会議は午後2時{以後}に始まる。\nThe meeting starts after 2 PM.",
  },
  {
    kanji: "以降",
    kana: "いこう",
    english: "From...onward・Thereafter",
    explanation: "Refers to the time from a specific point onward.",
    example: "来週{以降}、忙しくなる。\nI will be busy from next week onward.",
  },
  {
    kanji: "維持",
    kana: "いじ",
    english: "Maintenance・Preservation",
    explanation: "Refers to the act of keeping something in good condition or continuing a certain state.",
    example: "健康を{維持}するために運動する。\nI exercise to maintain my health.",
  },
  {
    kanji: "意識",
    kana: "いしき",
    english: "Consciousness・Awareness",
    explanation: "Refers to the state of being aware of and able to think about one's own existence, thoughts, and surroundings.",
    example: "彼は{意識}を失った。\nHe lost consciousness.",
  },
  {
    kanji: "以前",
    kana: "いぜん",
    english: "Before・Ago・Previously",
    explanation: "Refers to a time before the present or a specific event.",
    example: "彼に会ったのは{以前}のことだ。\nI met him a long time ago.",
  },
  {
    kanji: "位置",
    kana: "いち",
    english: "Position・Location",
    explanation: "Refers to the place or location of something.",
    example: "駅の{位置}を確認する。\nI check the location of the station.",
  },
  {
    kanji: "一流",
    kana: "いちりゅう",
    english: "First-class・Top-notch",
    explanation: "Refers to something or someone of the highest quality or rank.",
    example: "彼は{一流}の料理人だ。\nHe is a first-class chef.",
  },
  {
    kanji: "一般",
    kana: "いっぱん",
    english: "General・Common",
    explanation: "Refers to something that is common or applies to most people or things.",
    example: "{一般}の人々に公開する。\nIt is open to the general public.",
  },
  {
    kanji: "以内",
    kana: "いない",
    english: "Within・Inside of",
    explanation: "Refers to a limit or boundary that should not be exceeded.",
    example: "10分{以内}に戻ります。\nI will return within 10 minutes.",
  },
  {
    kanji: "田舎",
    kana: "いなか",
    english: "Countryside・Rural area",
    explanation: "Refers to areas outside of cities and towns, often characterized by farming and open spaces.",
    example: "{田舎}での生活は静かだ。\nLife in the countryside is peaceful.",
  },
  {
    kanji: "印刷",
    kana: "いんさつ",
    english: "Printing",
    explanation: "Refers to the process of producing text and images on paper using a printing press or printer.",
    example: "書類を{印刷}する。\nI print the documents.",
  },
  {
    kanji: "飲料",
    kana: "いんりょう",
    english: "Beverage・Drink",
    explanation: "Refers to liquids that can be consumed, such as water, tea, or juice.",
    example: "{飲料}水を買う。\nI buy drinking water.",
  },
  {
    kanji: "宇宙",
    kana: "うちゅう",
    english: "Universe・Space",
    explanation: "Refers to the vast expanse that contains all matter and energy, including planets, stars, and galaxies.",
    example: "{宇宙}の謎を解明する。\nI explore the mysteries of the universe.",
  },
  {
    kanji: "営業",
    kana: "えいぎょう",
    english: "Business・Sales・Operations",
    explanation: "Refers to the activities involved in running a business or selling products and services.",
    example: "{営業}成績を上げる。\nI improve sales performance.",
  },
  {
    kanji: "栄養",
    kana: "えいよう",
    english: "Nutrition・Nourishment",
    explanation: "Refers to the process of providing or obtaining the food necessary for health and growth.",
    example: "{栄養}バランスの良い食事をする。\nI eat a nutritionally balanced diet.",
  },
  {
    kanji: "演奏",
    kana: "えんそう",
    english: "Performance・Musical performance",
    explanation: "Refers to the act of performing music or a musical piece.",
    example: "ピアノを{演奏}する。\nI perform on the piano.",
  },
  {
    kanji: "遠慮",
    kana: "えんりょ",
    english: "Restraint・Hesitation・Courtesy",
    explanation: "Refers to the act of holding back or being considerate of others' feelings.",
    example: "{遠慮}せずに食べてください。\nPlease eat without hesitation.",
  },
  {
    kanji: "往復",
    kana: "おうふく",
    english: "Round trip・Return",
    explanation: "Refers to a journey to a place and back again.",
    example: "東京への{往復}切符を買う。\nI buy a round-trip ticket to Tokyo.",
  },
  {
    kanji: "応募",
    kana: "おうぼ",
    english: "Application・Entry",
    explanation: "Refers to the act of applying for a job, position, or opportunity.",
    example: "新しい仕事に{応募}する。\nI apply for a new job.",
  },
  {
    kanji: "応用",
    kana: "おうよう",
    english: "Application・Practical use",
    explanation: "Refers to the practical use or implementation of knowledge or skills.",
    example: "理論を{応用}する。\nI apply the theory in practice.",
  },
  {
    kanji: "大勢",
    kana: "おおぜい",
    english: "Crowd・Many people",
    explanation: "Refers to a large number of people gathered together.",
    example: "{大勢}の人が集まった。\nA crowd of people gathered.",
  },
  {
    kanji: "親子",
    kana: "おやこ",
    english: "Parent and child",
    explanation: "Refers to the relationship between a parent and their child.",
    example: "{親子}で遊園地に行く。\nI go to the amusement park with my child.",
  },
  {
    kanji: "絵画",
    kana: "かいが",
    english: "Painting・Picture",
    explanation: "Refers to a visual artwork created using paint on a surface such as canvas or paper.",
    example: "美術館で{絵画}を鑑賞する。\nI appreciate paintings at the art museum.",
  },
  {
    kanji: "会計",
    kana: "かいけい",
    english: "Accounting・Bill・Payment",
    explanation: "Refers to the process of managing financial records or the act of settling a bill.",
    example: "レストランで{会計}をする。\nI pay the bill at the restaurant.",
  },
  {
    kanji: "解決",
    kana: "かいけつ",
    english: "Solution・Resolution",
    explanation: "Refers to the act of finding a solution to a problem or resolving an issue.",
    example: "問題を{解決}する。\nI solve the problem.",
  },
  {
    kanji: "解説",
    kana: "かいせつ",
    english: "Explanation・Commentary",
    explanation: "Refers to the act of providing an explanation or commentary on a topic.",
    example: "試合の{解説}を聞く。\nI listen to the commentary of the game.",
  },
  {
    kanji: "回収",
    kana: "かいしゅう",
    english: "Collection・Recovery",
    explanation: "Refers to the act of collecting or retrieving something.",
    example: "ゴミを{回収}する。\nI collect the garbage.",
  },
  {
    kanji: "開始",
    kana: "かいし",
    english: "Start・Commencement",
    explanation: "Refers to the act of beginning or starting something.",
    example: "試合が{開始}される。\nThe game will start.",
  },
  {
    kanji: "開場",
    kana: "かいじょう",
    english: "Opening of a venue・Admission",
    explanation: "Refers to the act of opening a place for public access or admission.",
    example: "コンサート会場が{開場}する。\nThe concert venue opens.",
  },
  {
    kanji: "開店",
    kana: "かいてん",
    english: "Opening of a store・Shop opening",
    explanation: "Refers to the act of opening a store or shop for business.",
    example: "新しい店が{開店}する。\nA new store is opening.",
  },
  {
    kanji: "回数",
    kana: "かいすう",
    english: "Number of times・Frequency",
    explanation: "Refers to the count or frequency of occurrences of an event or action.",
    example: "運動の{回数}を増やす。\nI increase the number of times I exercise.",
  },
  {
    kanji: "価格",
    kana: "かかく",
    english: "Price・Cost",
    explanation: "Refers to the amount of money required to purchase something.",
    example: "商品の{価格}を調べる。\nI check the price of the product.",
  },
  {
    kanji: "各地",
    kana: "かくち",
    english: "Various places・Everywhere",
    explanation: "Refers to different locations or areas.",
    example: "{各地}でイベントが開催される。\nEvents are held in various places.",
  },
  {
    kanji: "各国",
    kana: "かっこく",
    english: "Each country・Various countries",
    explanation: "Refers to different countries around the world.",
    example: "{各国}の文化を学ぶ。\nI learn about the cultures of various countries.",
  },
  {
    kanji: "確認",
    kana: "かくにん",
    english: "Confirmation・Verification",
    explanation: "Refers to the act of confirming or verifying information or details.",
    example: "予約の{確認}をする。\nI confirm the reservation.",
  },
  {
    kanji: "火災",
    kana: "かさい",
    english: "Fire・Conflagration",
    explanation: "Refers to a large and destructive fire.",
    example: "建物で{火災}が発生した。\nA fire broke out in the building.",
  },
  {
    kanji: "花壇",
    kana: "かだん",
    english: "Flower bed・Flower garden",
    explanation: "Refers to a designated area for growing flowers.",
    example: "{花壇}に花を植える。\nI plant flowers in the flower bed.",
  },
  {
    kanji: "価値",
    kana: "かち",
    english: "Value・Worth",
    explanation: "Refers to the importance, usefulness, or worth of something.",
    example: "この絵は高い{価値}がある。\nThis painting has high value.",
  },
  {
    kanji: "家庭",
    kana: "かてい",
    english: "Home・Family",
    explanation: "Refers to the place where one lives and the people who live together as a family.",
    example: "{家庭}を大切にする。\nI cherish my family.",
  },
  {
    kanji: "花瓶",
    kana: "かびん",
    english: "Vase",
    explanation: "Refers to a container used for holding cut flowers.",
    example: "{花瓶}に花を飾る。\nI arrange flowers in the vase.",
  },
  {
    kanji: "髪型",
    kana: "かみがた",
    english: "Hairstyle・Hairdo",
    explanation: "Refers to the way in which a person's hair is cut and styled.",
    example: "新しい{髪型}に変える。\nI change to a new hairstyle.",
  },
  {
    kanji: "観客",
    kana: "かんきゃく",
    english: "Audience・Spectators",
    explanation: "Refers to the people who watch or attend a performance, event, or show.",
    example: "多くの{観客}が集まった。\nA large audience gathered.",
  },
  {
    kanji: "環境",
    kana: "かんきょう",
    english: "Environment・Surroundings",
    explanation: "Refers to the natural world or the conditions in which a person, animal, or plant lives or operates.",
    example: "{環境}を守るために努力する。\nI strive to protect the environment.",
  },
  {
    kanji: "関係",
    kana: "かんけい",
    english: "Relationship・Connection",
    explanation: "Refers to the way in which two or more people or things are connected or related to each other.",
    example: "彼との{関係}を大切にする。\nI cherish my relationship with him.",
  },
  {
    kanji: "歓迎",
    kana: "かんげい",
    english: "Welcome・Reception",
    explanation: "Refers to the act of greeting or receiving someone warmly.",
    example: "新入社員を{歓迎}する。\nI welcome the new employees.",
  },
  {
    kanji: "感激",
    kana: "かんげき",
    english: "Deep emotion・Being deeply moved・appreciation",
    explanation: "Refers to the feeling of being deeply touched or moved by something.",
    example: "彼の言葉に{感激}した。\nI was deeply moved by his words.",
  },
  {
    kanji: "観光",
    kana: "かんこう",
    english: "Sightseeing・Tourism",
    explanation: "Refers to the activity of visiting places of interest for pleasure.",
    example: "{観光}地を巡る。\nI tour sightseeing spots.",
  },
  {
    kanji: "看護",
    kana: "かんご",
    english: "Nursing・Caregiving",
    explanation: "Refers to the profession or act of providing care and support to the sick or injured.",
    example: "病院で{看護}の仕事をする。\nI work in nursing at the hospital.",
  },
  {
    kanji: "観察",
    kana: "かんさつ",
    english: "Observation・Watching",
    explanation: "Refers to the act of carefully watching or examining something.",
    example: "動物の行動を{観察}する。\nI observe the behavior of animals.",
  },
  {
    kanji: "感謝",
    kana: "かんしゃ",
    english: "Gratitude・Thanks",
    explanation: "Refers to the feeling of being thankful or appreciative.",
    example: "皆さんに心から{感謝}します。\nI sincerely thank everyone.",
  },
  {
    kanji: "感心",
    kana: "かんしん",
    english: "Admiration・Being impressed",
    explanation: "Refers to the feeling of admiration or being impressed by something or someone.",
    example: "彼の努力に{感心}した。\nI was impressed by his effort.",
  },
  {
    kanji: "関心",
    kana: "かんしん",
    english: "Interest・Concern",
    explanation: "Refers to the feeling of wanting to learn more about something or being concerned about it.",
    example: "環境問題に{関心}を持つ。\nI have an interest in environmental issues.",
  },
  {
    kanji: "完成",
    kana: "かんせい",
    english: "Completion・Accomplishment",
    explanation: "Refers to the act of finishing or completing something.",
    example: "新しい建物が{完成}した。\nThe new building has been completed.",
  },
  {
    kanji: "乾燥",
    kana: "かんそう",
    english: "Dryness・Dehydration",
    explanation: "Refers to the state of being dry or the process of removing moisture.",
    example: "肌の{乾燥}を防ぐ。\nI prevent skin dryness.",
  },
  {
    kanji: "感想",
    kana: "かんそう",
    english: "Impressions・Thoughts・Feedback",
    explanation: "Refers to the thoughts or feelings one has after experiencing something.",
    example: "映画の{感想}を聞かせてください。\nPlease tell me your impressions of the movie.",
  },
  {
    kanji: "感動",
    kana: "かんどう",
    english: "Deeply moved・Emotionally touched",
    explanation: "Refers to the state of being deeply moved or emotionally affected by something.",
    example: "彼の演説に{感動}した。\nI was deeply moved by his speech.",
  },
  {
    kanji: "館内",
    kana: "かんない",
    english: "Inside the building・Within the hall",
    explanation: "Refers to the interior of a building or facility.",
    example: "{館内}は禁煙です。\nSmoking is prohibited inside the building.",
  },
  {
    kanji: "外出",
    kana: "がいしゅつ",
    english: "Going out・Leaving home",
    explanation: "Refers to the act of going outside or leaving one's home.",
    example: "午後に{外出}する予定です。\nI plan to go out in the afternoon.",
  },
  {
    kanji: "外食",
    kana: "がいしょく",
    english: "Eating out・Dining out",
    explanation: "Refers to the act of eating meals at restaurants or outside the home.",
    example: "週末に{外食}することが多い。\nI often eat out on weekends.",
  },
  {
    kanji: "画家",
    kana: "がか",
    english: "Painter・Artist",
    explanation: "Refers to a person who creates paintings or visual artworks.",
    example: "有名な{画家}の作品を鑑賞する。\nI appreciate the works of a famous painter.",
  },
  {
    kanji: "学部",
    kana: "がくぶ",
    english: "Faculty・Department of a university",
    explanation: "Refers to a division within a university or college that specializes in a particular field of study.",
    example: "経済学{部}に所属している。\nI belong to the Faculty of Economics.",
  },
  {
    kanji: "学期",
    kana: "がっき",
    english: "Semester・Term",
    explanation: "Refers to a division of the academic year in schools and universities.",
    example: "新しい{学期}が始まる。\nThe new semester begins.",
  },
  {
    kanji: "楽器",
    kana: "がっき",
    english: "Musical instrument",
    explanation: "Refers to a device used to produce musical sounds.",
    example: "ピアノは人気のある{楽器}です。\nThe piano is a popular musical instrument.",
  },
  {
    kanji: "我慢",
    kana: "がまん",
    english: "Patience・Endurance・Perseverance",
    explanation: "Refers to the ability to endure difficult situations or control one's emotions.",
    example: "痛みを{我慢}する。\nI endure the pain.",
  },
  {
    kanji: "機械",
    kana: "きかい",
    english: "Machine・Mechanism",
    explanation: "Refers to a device or apparatus that performs a specific function or task.",
    example: "新しい{機械}を導入する。\nI introduce a new machine.",
  },
  {
    kanji: "期間",
    kana: "きかん",
    english: "Period・Duration",
    explanation: "Refers to a specific length of time during which something occurs or is valid.",
    example: "契約の{期間}を延長する。\nI extend the duration of the contract.",
  },
  {
    kanji: "企業",
    kana: "きぎょう",
    english: "Enterprise・Company・Corporation",
    explanation: "Refers to a business organization or company engaged in commercial activities.",
    example: "大手{企業}で働く。\nI work for a major corporation.",
  },
  {
    kanji: "期限",
    kana: "きげん",
    english: "Deadline・Time limit",
    explanation: "Refers to the latest time or date by which something must be completed or submitted.",
    example: "レポートの{期限}を守る。\nI meet the deadline for the report.",
  },
  {
    kanji: "基礎",
    kana: "きそ",
    english: "Foundation・Basis",
    explanation: "Refers to the fundamental principles or groundwork of a subject or skill.",
    example: "数学の{基礎}を学ぶ。\nI learn the basics of mathematics.",
  },
  {
    kanji: "規則",
    kana: "きそく",
    english: "Rules・Regulations",
    explanation: "Refers to the established guidelines or principles that govern behavior or actions.",
    example: "学校の{規則}を守る。\nI follow the school rules.",
  },
  {
    kanji: "期待",
    kana: "きたい",
    english: "Expectation・Anticipation",
    explanation: "Refers to the belief or hope that something will happen or be achieved.",
    example: "彼の成功を{期待}している。\nI have high expectations for his success.",
  },
  {
    kanji: "北側",
    kana: "きたがわ",
    english: "North side・Northern side",
    explanation: "Refers to the side or direction facing north.",
    example: "家の{北側}に庭がある。\nThere is a garden on the north side of the house.",
  },
  {
    kanji: "㷌宅",
    kana: "きたく",
    english: "Returning home・Going home",
    explanation: "Refers to the act of going back to one's home.",
    example: "仕事の後で{帰宅}する。\nI return home after work.",
  },
  {
    kanji: "切符",
    kana: "きっぷ",
    english: "Ticket・Pass",
    explanation: "Refers to a piece of paper or card that allows entry to an event or transportation.",
    example: "電車の{切符}を買う。\nI buy a train ticket.",
  },
  {
    kanji: "記念",
    kana: "きねん",
    english: "Commemoration・Memorial",
    explanation: "Refers to the act of remembering or honoring a significant event or person.",
    example: "結婚{記念}日に旅行する。\nI travel on our wedding anniversary.",
  },
  {
    kanji: "基本",
    kana: "きほん",
    english: "Basic・Fundamental",
    explanation: "Refers to the essential or foundational aspects of something.",
    example: "英語の{基本}を学ぶ。\nI learn the basics of English.",
  },
  {
    kanji: "希望",
    kana: "きぼう",
    english: "Hope・Wish・Desire",
    explanation: "Refers to the feeling of wanting something to happen or be true.",
    example: "将来の{希望}を持つ。\nI have hopes for the future.",
  },
  {
    kanji: "競争",
    kana: "きょうそう",
    english: "Competition・Rivalry",
    explanation: "Refers to the act of competing or striving against others to achieve a goal.",
    example: "市場での{競争}が激しい。\nThe competition in the market is intense.",
  },
  {
    kanji: "共通",
    kana: "きょうつう",
    english: "Common・Shared",
    explanation: "Refers to something that is shared or held in common by multiple people or groups.",
    example: "彼らには多くの{共通}点がある。\nThey have many things in common.",
  },
  {
    kanji: "協力",
    kana: "きょうりょく",
    english: "Cooperation・Collaboration",
    explanation: "Refers to the act of working together with others to achieve a common goal.",
    example: "チームで{協力}してプロジェクトを進める。\nWe cooperate as a team to advance the project.",
  },
  {
    kanji: "距離",
    kana: "きょり",
    english: "Distance・Range",
    explanation: "Refers to the amount of space between two points or locations.",
    example: "駅までの{距離}は遠い。\nThe distance to the station is far.",
  },
  {
    kanji: "記録",
    kana: "きろく",
    english: "Record・Documentation",
    explanation: "Refers to the act of documenting or keeping a record of information or events.",
    example: "新しい{記録}を作る。\nI set a new record.",
  },
  {
    kanji: "近所",
    kana: "きんじょ",
    english: "Neighborhood・Vicinity",
    explanation: "Refers to the area surrounding one's home or a specific location.",
    example: "{近所}の人と仲良くする。\nI get along with the people in my neighborhood.",
  },
  {
    kanji: "技術",
    kana: "ぎじゅつ",
    english: "Technology・Technique・Skill",
    explanation: "Refers to the application of scientific knowledge for practical purposes or the ability to perform tasks effectively.",
    example: "新しい{技術}を開発する。\nI develop new technology.",
  },
  {
    kanji: "草花",
    kana: "くさばな",
    english: "Plants and flowers",
    explanation: "Refers to various types of vegetation, including grasses and flowers.",
    example: "{草花}を育てるのが趣味です。\nMy hobby is growing plants and flowers.",
  },
  {
    kanji: "工夫",
    kana: "くふう",
    english: "Device・Scheme・Ingenuity",
    explanation: "Refers to the act of devising or coming up with a clever solution or idea.",
    example: "時間を節約するために{工夫}する。\nI devise ways to save time.",
  },
  {
    kanji: "区別",
    kana: "くべつ",
    english: "Distinction・Differentiation",
    explanation: "Refers to the act of recognizing or making a distinction between different things.",
    example: "重要なものとそうでないものを{区別}する。\nI distinguish between important and unimportant things.",
  },
  {
    kanji: "苦労",
    kana: "くろう",
    english: "Hardship・Trouble・Effort",
    explanation: "Refers to the difficulties or challenges one faces in life or work.",
    example: "彼は多くの{苦労}を乗り越えた。\nHe overcame many hardships.",
  },
  {
    kanji: "訓練",
    kana: "くんれん",
    english: "Training・Drill",
    explanation: "Refers to the process of learning or practicing skills through instruction and exercise.",
    example: "新入社員に{訓練}を行う。\nI conduct training for new employees.",
  },
  {
    kanji: "偶然",
    kana: "ぐうぜん",
    english: "Coincidence・By chance",
    explanation: "Refers to an event that happens unexpectedly or without planning.",
    example: "彼と{偶然}会った。\nI met him by chance.",
  },
  {
    kanji: "経営",
    kana: "けいえい",
    english: "Management・Administration",
    explanation: "Refers to the act of overseeing and controlling the operations of a business or organization.",
    example: "会社を{経営}する。\nI manage a company.",
  },
  {
    kanji: "計画",
    kana: "けいかく",
    english: "Plan・Project",
    explanation: "Refers to a detailed proposal or scheme for achieving a specific goal or objective.",
    example: "旅行の{計画}を立てる。\nI make a plan for the trip.",
  },
  {
    kanji: "警官",
    kana: "けいかん",
    english: "Police officer・Cop",
    explanation: "Refers to a member of the police force responsible for maintaining law and order.",
    example: "交差点で{警官}が交通整理をしている。\nA police officer is directing traffic at the intersection.",
  },
  {
    kanji: "経験",
    kana: "けいけん",
    english: "Experience・Practice",
    explanation: "Refers to the knowledge or skills gained through involvement in events or activities.",
    example: "海外での{経験}が役立つ。\nMy experience abroad is useful.",
  },
  {
    kanji: "経済",
    kana: "けいざい",
    english: "Economy・Economics",
    explanation: "Refers to the system of production, distribution, and consumption of goods and services in a society.",
    example: "国の{経済}を発展させる。\nI develop the country's economy.",
  },
  {
    kanji: "警察",
    kana: "けいさつ",
    english: "Police・Police department",
    explanation: "Refers to the organization responsible for maintaining public order and enforcing laws.",
    example: "{警察}に通報する。\nI report to the police.",
  },
  {
    kanji: "携帯",
    kana: "けいたい",
    english: "Mobile phone・Cell phone・Carrying",
    explanation: "Refers to a portable telephone that can be used for communication on the go.",
    example: "{携帯}電話を持っている。\nI have a mobile phone.",
  },
  {
    kanji: "経由",
    kana: "けいゆ",
    english: "Going Via・By way of",
    explanation: "Refers to the route or path taken to reach a destination.",
    example: "東京{経由}で大阪に行く。\nI go to Osaka via Tokyo.",
  },
  {
    kanji: "景色",
    kana: "けしき",
    english: "Scenery・Landscape・View",
    explanation: "Refers to the natural features of a landscape or the visual appearance of a place.",
    example: "山の{景色}が美しい。\nThe mountain scenery is beautiful.",
  },
  {
    kanji: "結局",
    kana: "けっきょく",
    english: "After all・In the end",
    explanation: "Refers to the final outcome or result after considering all factors.",
    example: "{結局}、彼が正しかった。\nAfter all, he was right.",
  },
  {
    kanji: "結構",
    kana: "けっこう",
    english: "Splendid・Fine・Enough・Quite・Satisfactory",
    explanation: "Refers to something that is satisfactory or sufficient.",
    example: "その提案は{結構}です。\nThat proposal is fine.",
  },
  {
    kanji: "健康",
    kana: "けんこう",
    english: "Health・Well-being",
    explanation: "Refers to the state of being free from illness or injury and maintaining physical and mental well-being.",
    example: "毎日運動して{健康}を保つ。\nI exercise daily to maintain my health.",
  },
  {
    kanji: "検査",
    kana: "けんさ",
    english: "Inspection・Examination・Checkup",
    explanation: "Refers to the act of examining or inspecting something to ensure it meets certain standards or criteria.",
    example: "病院で健康{検査}を受ける。\nI undergo a health checkup at the hospital.",
  },
  {
    kanji: "建設",
    kana: "けんせつ",
    english: "Construction・Building",
    explanation: "Refers to the process of building or erecting structures such as buildings, roads, or bridges.",
    example: "新しい橋を{建設}する。\nI construct a new bridge.",
  },
  {
    kanji: "建築",
    kana: "けんちく",
    english: "Architecture・Construction",
    explanation: "Refers to the art and science of designing and constructing buildings and other physical structures.",
    example: "有名な建築家の作品を見る。\nI see the works of a famous architect.",
  },
  {
    kanji: "芸術",
    kana: "げいじゅつ",
    english: "Art・Fine arts",
    explanation: "Refers to creative expressions such as painting, sculpture, music, and literature.",
    example: "{芸術}作品を鑑賞する。\nI appreciate works of art.",
  },
  {
    kanji: "原因",
    kana: "げんいん",
    english: "Cause・Origin・Source・Reason",
    explanation: "Refers to the reason or factor that leads to a particular outcome or event.",
    example: "事故の{原因}を調査する。\nI investigate the cause of the accident.",
  },
  {
    kanji: "原稿",
    kana: "げんこう",
    english: "Manuscript・Draft",
    explanation: "Refers to a written document or text that is prepared for publication or presentation.",
    example: "論文の{原稿}を提出する。\nI submit the manuscript of my thesis.",
  },
  {
    kanji: "言語",
    kana: "げんご",
    english: "Language",
    explanation: "Refers to a system of communication used by a particular community or country.",
    example: "新しい{言語}を学ぶ。\nI learn a new language.",
  },
  {
    kanji: "減少",
    kana: "げんしょう",
    english: "Decrease・Reduction",
    explanation: "Refers to the act of becoming smaller or less in quantity, size, or intensity.",
    example: "人口が{減少}している。\nThe population is decreasing.",
  },
  {
    kanji: "講演",
    kana: "こうえん",
    english: "Lecture・Speech",
    explanation: "Refers to a formal talk or presentation given to an audience on a specific topic.",
    example: "有名な教授の{講演}を聞く。\nI listen to a lecture by a famous professor.",
  },
  {
    kanji: "高温",
    kana: "こうおん",
    english: "High temperature",
    explanation: "Refers to a temperature that is significantly above normal or average levels.",
    example: "夏は{高温}になることが多い。\nIt often gets very hot in summer.",
  },
  {
    kanji: "効果",
    kana: "こうか",
    english: "Effect・Impact",
    explanation: "Refers to the result or outcome produced by a particular action or event.",
    example: "新しい薬の{効果}を確認する。\nI check the effect of the new medicine.",
  },
  {
    kanji: "交換",
    kana: "こうかん",
    english: "Exchange・Swap",
    explanation: "Refers to the act of giving one thing and receiving another in return.",
    example: "名刺を{交換}する。\nI exchange business cards.",
  },
  {
    kanji: "後期",
    kana: "こうき",
    english: "Later period・Latter term・Final stage",
    explanation: "Refers to the latter part of a period or term.",
    example: "大学の{後期}に入る。\nI enter the latter term of university.",
  },
  {
    kanji: "講義",
    kana: "こうぎ",
    english: "Lecture・Class",
    explanation: "Refers to a formal presentation or talk given by a teacher or professor to students.",
    example: "毎週月曜日に{講義}がある。\nThere is a lecture every Monday.",
  },
  {
    kanji: "公共",
    kana: "こうきょう",
    english: "Public・Community",
    explanation: "Refers to something that is open or accessible to all members of society.",
    example: "{公共}の場でのマナーを守る。\nI observe manners in public places.",
  },
  {
    kanji: "工業",
    kana: "こうぎょう",
    english: "Industry・Manufacturing",
    explanation: "Refers to the sector of the economy that involves the production of goods and services.",
    example: "{工業}製品を輸出する。\nI export industrial products.",
  },
  {
    kanji: "航空",
    kana: "こうくう",
    english: "Aviation・Flight",
    explanation: "Refers to the operation and navigation of aircraft.",
    example: "{航空}会社で働く。\nI work for an airline company.",
  },
  {
    kanji: "広告",
    kana: "こうこく",
    english: "Advertisement・Commercial",
    explanation: "Refers to a public notice or announcement promoting a product, service, or event.",
    example: "新製品の{広告}を見る。\nI see the advertisement for the new product.",
  },
  {
    kanji: "工事",
    kana: "こうじ",
    english: "Construction work・Engineering work",
    explanation: "Refers to the process of building or repairing structures such as buildings, roads, or bridges.",
    example: "道路の{工事}が行われている。\nConstruction work is being carried out on the road.",
  },
  {
    kanji: "紅茶",
    kana: "こうちゃ",
    english: "Black tea",
    explanation: "Refers to a type of tea that is more oxidized than green, oolong, and white teas.",
    example: "{紅茶}を飲むのが好きです。\nI like to drink black tea.",
  },
  {
    kanji: "交通",
    kana: "こうつう",
    english: "Traffic・Transportation",
    explanation: "Refers to the movement of vehicles, people, or goods from one place to another.",
    example: "{交通}事故に注意する。\nI pay attention to traffic accidents.",
  },
  {
    kanji: "行動",
    kana: "こうどう",
    english: "Action・Behavior",
    explanation: "Refers to the way in which a person acts or conducts themselves.",
    example: "社会的な{行動}を学ぶ。\nI learn social behavior.",
  },
  {
    kanji: "後半",
    kana: "こうはん",
    english: "Latter half・Second half",
    explanation: "Refers to the second part of a period or event.",
    example: "試合の{後半}が始まる。\nThe second half of the game begins.",
  },
  {
    kanji: "後方",
    kana: "こうほう",
    english: "Rear・Backside",
    explanation: "Refers to the back or rear part of something.",
    example: "車の{後方}を確認する。\nI check the rear of the car.",
  },
  {
    kanji: "交流",
    kana: "こうりゅう",
    english: "Exchange・Interaction",
    explanation: "Refers to the act of interacting or exchanging ideas, culture, or information with others.",
    example: "国際的な{交流}を促進する。\nI promote international exchange.",
  },
  {
    kanji: "混雜",
    kana: "こんざつ",
    english: "Congestion・Crowding",
    explanation: "Refers to a state of being crowded or congested, often causing discomfort or difficulty in movement.",
    example: "駅が{混雜}している。\nThe station is crowded.",
  },
  {
    kanji: "合格",
    kana: "ごうかく",
    english: "Passing (an exam)・Success",
    explanation: "Refers to the act of successfully meeting the requirements of an examination or test.",
    example: "試験に{合格}する。\nI pass the exam.",
  },
  {
    kanji: "合計",
    kana: "ごうけい",
    english: "Total・Sum",
    explanation: "Refers to the overall amount or sum of multiple items or values.",
    example: "買い物の{合計}金額を計算する。\nI calculate the total amount of my shopping.",
  },
  {
    kanji: "最終",
    kana: "さいしゅう",
    english: "Final・Last",
    explanation: "Refers to the last or concluding part of a series or sequence.",
    example: "電車の{最終}に乗る。\nI take the last train.",
  },
  {
    kanji: "最初",
    kana: "さいしょ",
    english: "Beginning・First",
    explanation: "Refers to the initial or starting point of something.",
    example: "物語の{最初}の部分を読む。\nI read the beginning part of the story.",
  },
  {
    kanji: "財布",
    kana: "さいふ",
    english: "Wallet・Purse",
    explanation: "Refers to a small, flat case used for carrying money and personal items.",
    example: "新しい{財布}を買う。\nI buy a new wallet.",
  },
  {
    kanji: "作業",
    kana: "さぎょう",
    english: "Work・Operation・Task",
    explanation: "Refers to the act of performing a specific task or job.",
    example: "工場で{作業}をする。\nI work in a factory.",
  },
  {
    kanji: "作者",
    kana: "さくしゃ",
    english: "Author・Creator",
    explanation: "Refers to a person who creates or writes literary or artistic works.",
    example: "有名な{作者}の本を読む。\nI read books by a famous author.",
  },
  {
    kanji: "作家",
    kana: "さっか",
    english: "Writer・Novelist・Artist",
    explanation: "Refers to a person who writes literary works such as novels, stories, or essays.",
    example: "彼は有名な{作家}です。\nHe is a famous writer.",
  },
  {
    kanji: "算数",
    kana: "さんすう",
    english: "Arithmetic・Mathematics",
    explanation: "Refers to the branch of mathematics that deals with basic operations such as addition, subtraction, multiplication, and division.",
    example: "子供たちは学校で{算数}を学ぶ。\nChildren learn arithmetic at school.",
  },
  {
    kanji: "賛成",
    kana: "さんせい",
    english: "Agreement・Approval",
    explanation: "Refers to the act of agreeing with or approving a proposal, idea, or opinion.",
    example: "彼の意見に{賛成}する。\nI agree with his opinion.",
  },
  {
    kanji: "材料",
    kana: "ざいりょう",
    english: "Material・Ingredient",
    explanation: "Refers to the substances or components used to make or create something.",
    example: "料理の{材料}を買う。\nI buy ingredients for cooking.",
  },
  {
    kanji: "雜誌",
    kana: "ざっし",
    english: "Magazine・Periodical",
    explanation: "Refers to a publication that contains articles, stories, and advertisements, typically issued regularly.",
    example: "新しい{雜誌}を読む。\nI read a new magazine.",
  },
  {
    kanji: "資源",
    kana: "しげん",
    english: "Resources・Natural resources",
    explanation: "Refers to materials or substances that are useful or valuable, often found in nature.",
    example: "環境{資源}を大切にする。\nI value environmental resources.",
  },
  {
    kanji: "指示",
    kana: "しじ",
    english: "Instruction・Indication",
    explanation: "Refers to the act of giving directions or guidance on how to do something.",
    example: "先生の{指示}に従う。\nI follow the teacher's instructions.",
  },
  {
    kanji: "姿勢",
    kana: "しせい",
    english: "Posture・Attitude",
    explanation: "Refers to the way in which a person holds their body or the attitude they adopt towards something.",
    example: "良い{姿勢}を保つ。\nI maintain good posture.",
  },
  {
    kanji: "失敗",
    kana: "しっぱい",
    english: "Failure・Mistake",
    explanation: "Refers to the act of not achieving a desired outcome or making an error.",
    example: "試験に{失敗}する。\nI fail the exam.",
  },
  {
    kanji: "指定",
    kana: "してい",
    english: "Designation・Specification",
    explanation: "Refers to the act of officially choosing or specifying something for a particular purpose.",
    example: "会議の場所を{指定}する。\nI designate the location for the meeting.",
  },
  {
    kanji: "支店",
    kana: "してん",
    english: "Branch (office/store)",
    explanation: "Refers to a subsidiary or division of a larger organization, such as a bank or company.",
    example: "銀行の{支店}で口座を開設する。\nI open an account at the bank branch.",
  },
  {
    kanji: "指導",
    kana: "しどう",
    english: "Guidance・Coaching",
    explanation: "Refers to the act of providing direction, advice, or instruction to help someone improve or succeed.",
    example: "学生に学習の{指導}をする。\nI provide learning guidance to students.",
  },
  {
    kanji: "始発",
    kana: "しはつ",
    english: "First train/bus",
    explanation: "Refers to the first departure of a train or bus service for the day.",
    example: "{始発}の電車に乗る。\nI take the first train.",
  },
  {
    kanji: "芝生",
    kana: "しばふ",
    english: "Lawn・Grass",
    explanation: "Refers to an area of short, mowed grass, typically found in gardens or parks.",
    example: "公園の{芝生}でピクニックをする。\nI have a picnic on the lawn in the park.",
  },
  {
    kanji: "習慣",
    kana: "しゅうかん",
    english: "Habit・Custom",
    explanation: "Refers to a regular practice or behavior that is often repeated.",
    example: "毎朝ジョギングするのが私の{習慣}です。\nJogging every morning is my habit.",
  },
  {
    kanji: "就職",
    kana: "しゅうしょく",
    english: "Employment・Getting a job",
    explanation: "Refers to the act of finding and starting a job or career.",
    example: "大学卒業後に{就職}する。\nI get a job after graduating from university.",
  },
  {
    kanji: "収入",
    kana: "しゅうにゅう",
    english: "Income・Earnings",
    explanation: "Refers to the money received from work, investments, or other sources.",
    example: "毎月の{収入}を増やす。\nI increase my monthly income.",
  },
  {
    kanji: "終了",
    kana: "しゅうりょう",
    english: "End・Completion",
    explanation: "Refers to the act of bringing something to a close or finishing it.",
    example: "会議を{終了}する。\nI end the meeting.",
  },
  {
    kanji: "祝日",
    kana: "しゅくじつ",
    english: "National Holiday・Public holiday",
    explanation: "Refers to a day designated for celebration or commemoration, often recognized by the government.",
    example: "{祝日}には休みがあります。\nThere is a holiday on public holidays.",
  },
  {
    kanji: "手術",
    kana: "しゅじゅつ",
    english: "Surgery・Operation",
    explanation: "Refers to a medical procedure involving an incision or manipulation of body tissues to treat a condition or injury.",
    example: "明日{手術}を受ける予定です。\nI am scheduled to undergo surgery tomorrow.",
  },
  {
    kanji: "手段",
    kana: "しゅだん",
    english: "Means・Method",
    explanation: "Refers to a way or method of achieving a particular goal or objective.",
    example: "目的を達成するための{手段}を考える。\nI think of means to achieve the goal.",
  },
  {
    kanji: "主張",
    kana: "しゅちょう",
    english: "Claim・Assertion・Insistence",
    explanation: "Refers to the act of stating or asserting one's opinion or position on a matter.",
    example: "彼は自分の意見を強く{主張}した。\nHe strongly asserted his opinion.",
  },
  {
    kanji: "出勤",
    kana: "しゅっきん",
    english: "Going to work・Attendance",
    explanation: "Refers to the act of going to one's workplace or job.",
    example: "毎朝9時に{出勤}する。\nI go to work at 9 a.m. every morning.",
  },
  {
    kanji: "出身",
    kana: "しゅっしん",
    english: "Hometown・Origin",
    explanation: "Refers to the place where a person was born or raised.",
    example: "彼は東京{出身}です。\nHe is from Tokyo.",
  },
  {
    kanji: "種類",
    kana: "しゅるい",
    english: "Type・Kind・Category",
    explanation: "Refers to a specific class or category of things that share common characteristics.",
    example: "果物の{種類}が豊富です。\nThere is a wide variety of fruits.",
  },
  {
    kanji: "紹介",
    kana: "しょうかい",
    english: "Introduction・Referral",
    explanation: "Refers to the act of presenting or recommending someone or something to others.",
    example: "友達を{紹介}する。\nI introduce my friend.",
  },
  {
    kanji: "招待",
    kana: "しょうたい",
    english: "Invitation",
    explanation: "Refers to the act of inviting someone to an event or gathering.",
    example: "パーティーに{招待}される。\nI am invited to a party.",
  },
  {
    kanji: "消費",
    kana: "しょうひ",
    english: "Consumption・Expenditure",
    explanation: "Refers to the act of using up goods or services, often in relation to economic activity.",
    example: "エネルギーの{消費}を減らす。\nI reduce energy consumption.",
  },
  {
    kanji: "証明",
    kana: "しょうめい",
    english: "Proof・Certification",
    explanation: "Refers to the act of providing evidence or documentation to verify a fact or claim.",
    example: "身分証明書を提示する。\nI present my identification card.",
  },
  {
    kanji: "正面",
    kana: "しょうめん",
    english: "Front・Facade",
    explanation: "Refers to the front or forward-facing part of something, such as a building or object.",
    example: "建物の{正面}に入口がある。\nThe entrance is at the front of the building.",
  },
  {
    kanji: "食欲",
    kana: "しょくよく",
    english: "Appetite・Desire to eat",
    explanation: "Refers to the natural desire or craving for food.",
    example: "運動後は{食欲}が増す。\nMy appetite increases after exercise.",
  },
  {
    kanji: "書類",
    kana: "しょるい",
    english: "Documents・Papers・Files",
    explanation: "Refers to written or printed materials that provide information or evidence.",
    example: "必要な{書類}を提出する。\nI submit the necessary documents.",
  },
  {
    kanji: "資料",
    kana: "しりょう",
    english: "Materials・Data・Documents",
    explanation: "Refers to information or resources used for study, research, or reference.",
    example: "会議のための{資料}を準備する。\nI prepare materials for the meeting.",
  },
  {
    kanji: "進学",
    kana: "しんがく",
    english: "Advancing to a higher level of education・Entering a higher education institution",
    explanation: "Refers to the act of continuing one's education by moving on to a higher level, such as from high school to university.",
    example: "大学に{進学}する。\nI advance to university.",
  },
  {
    kanji: "進行",
    kana: "しんこう",
    english: "Progress・Advance",
    explanation: "Refers to the act of moving forward or making progress in a process or activity.",
    example: "プロジェクトが順調に{進行}している。\nThe project is progressing smoothly.",
  },
  {
    kanji: "申請",
    kana: "しんせい",
    english: "Application・Request",
    explanation: "Refers to the act of formally requesting or applying for something, such as a job, permit, or service.",
    example: "ビザを{申請}する。\nI apply for a visa.",
  },
  {
    kanji: "心臓",
    kana: "しんぞう",
    english: "Heart (organ)",
    explanation: "Refers to the muscular organ that pumps blood throughout the body.",
    example: "彼は{心臓}の病気を患っている。\nHe has a heart disease.",
  },
  {
    kanji: "進歩",
    kana: "しんぽ",
    english: "Progress・Advancement",
    explanation: "Refers to the act of making improvements or advancements in a particular area or field.",
    example: "科学技術の{進歩}が著しい。\nThe progress of science and technology is remarkable.",
  },
  {
    kanji: "森林",
    kana: "しんりん",
    english: "Forest・Woodland",
    explanation: "Refers to a large area covered chiefly with trees and undergrowth.",
    example: "{森林}保護の重要性を理解する。\nI understand the importance of forest conservation.",
  },
  {
    kanji: "時期",
    kana: "じき",
    english: "Time period・Season・Timing",
    explanation: "Refers to a specific period or season when something occurs or is expected to happen.",
    example: "花の{時期}を見計らう。\nI time it to see the flowers bloom.",
  },
  {
    kanji: "時給",
    kana: "じきゅう",
    english: "Hourly wage・Pay per hour",
    explanation: "Refers to the amount of money earned for each hour of work.",
    example: "アルバイトの{時給}が上がった。\nMy part-time job's hourly wage has increased.",
  },
  {
    kanji: "事件",
    kana: "じけん",
    english: "Incident・Event・Case",
    explanation: "Refers to a specific occurrence or event, often of significance or importance.",
    example: "警察は{事件}を調査している。\nThe police are investigating the incident.",
  },
  {
    kanji: "時刻",
    kana: "じこく",
    english: "Time・Hour・Moment",
    explanation: "Refers to a specific point in time, often indicated by a clock or schedule.",
    example: "電車の{時刻}を確認する。\nI check the train schedule.",
  },
  {
    kanji: "持参",
    kana: "じさん",
    english: "Bringing・Carrying",
    explanation: "Refers to the act of bringing or carrying something with oneself.",
    example: "必要な書類を{持参}する。\nI bring the necessary documents.",
  },
  {
    kanji: "事情",
    kana: "じじょう",
    english: "Circumstances・Situation・Conditions",
    explanation: "Refers to the specific conditions or factors that affect a situation or event.",
    example: "個人的な{事情}で参加できない。\nI cannot participate due to personal circumstances.",
  },
  {
    kanji: "実家",
    kana: "じっか",
    english: "One's parental home・Family home",
    explanation: "Refers to the home where one's parents or family live.",
    example: "{実家}に帰る。\nI return to my family home.",
  },
  {
    kanji: "実験",
    kana: "じっけん",
    english: "Experiment・Test",
    explanation: "Refers to a scientific procedure undertaken to make a discovery or test a hypothesis.",
    example: "新しい薬の{実験}を行う。\nI conduct experiments on a new medicine.",
  },
  {
    kanji: "実行",
    kana: "じっこう",
    english: "Execution・Implementation",
    explanation: "Refers to the act of putting a plan or idea into action.",
    example: "計画を{実行}に移す。\nI put the plan into action.",
  },
  {
    kanji: "実用",
    kana: "じつよう",
    english: "Practical use・Utility",
    explanation: "Refers to the quality of being useful or functional in everyday life.",
    example: "この道具は{実用}的です。\nThis tool is practical.",
  },
  {
    kanji: "実力",
    kana: "じつりょく",
    english: "Ability・Capability・Real strength",
    explanation: "Refers to a person's true ability or competence in a particular area.",
    example: "彼の{実力}は本物だ。\nHis ability is genuine.",
  },
  {
    kanji: "自慢",
    kana: "じまん",
    english: "Pride・Boast",
    explanation: "Refers to the act of taking pride in or boasting about one's achievements or qualities.",
    example: "彼は自分の成績を{自慢}している。\nHe is boasting about his grades.",
  },
  {
    kanji: "事務",
    kana: "じむ",
    english: "Office work・Clerical work",
    explanation: "Refers to administrative tasks and duties performed in an office setting.",
    example: "会社で{事務}を担当する。\nI am in charge of clerical work at the company.",
  },
  {
    kanji: "渋滞",
    kana: "じゅうたい",
    english: "Traffic jam・Congestion",
    explanation: "Refers to a situation where vehicles are unable to move freely due to heavy traffic.",
    example: "道路が{渋滞}している。\nThe road is congested.",
  },
  {
    kanji: "受験",
    kana: "じゅけん",
    english: "Taking an exam・Entrance exam",
    explanation: "Refers to the act of sitting for an examination, often for admission to a school or program.",
    example: "大学の入学試験を{受験}する。\nI take the university entrance exam.",
  },
  {
    kanji: "需要",
    kana: "じゅよう",
    english: "Demand・Need",
    explanation: "Refers to the desire or need for goods or services in a market.",
    example: "新製品の{需要}が高まっている。\nThe demand for the new product is increasing.",
  },
  {
    kanji: "順番",
    kana: "じゅんばん",
    english: "Order・Turn・Sequence",
    explanation: "Refers to the arrangement or sequence in which things occur or are done.",
    example: "名前の{順番}で呼ばれる。\nI am called in the order of names.",
  },
  {
    kanji: "準備",
    kana: "じゅんび",
    english: "Preparation・Arrangement",
    explanation: "Refers to the act of getting ready or making arrangements for an event or activity.",
    example: "旅行の{準備}をする。\nI prepare for the trip.",
  },
  {
    kanji: "上司",
    kana: "じょうし",
    english: "Boss・Superior",
    explanation: "Refers to a person who holds a higher position in a workplace or organization.",
    example: "{上司}に報告する。\nI report to my boss.",
  },
  {
    kanji: "乘車",
    kana: "じょうしゃ",
    english: "Riding a vehicle・Boarding",
    explanation: "Refers to the act of getting on or riding a vehicle, such as a train or bus.",
    example: "電車に{乘車}する。\nI board the train.",
  },
  {
    kanji: "状態",
    kana: "じょうたい",
    english: "Condition・State・Status",
    explanation: "Refers to the current situation or condition of something or someone.",
    example: "機械の{状態}を確認する。\nI check the condition of the machine.",
  },
  {
    kanji: "冗談",
    kana: "じょうだん",
    english: "Joke・Jesting",
    explanation: "Refers to a humorous or playful remark or action intended to amuse others.",
    example: "彼の{冗談}に笑う。\nI laugh at his joke.",
  },
  {
    kanji: "神社",
    kana: "じんじゃ",
    english: "Shinto shrine",
    explanation: "Refers to a place of worship in the Shinto religion, often dedicated to kami (deities or spirits).",
    example: "{神社}でお参りする。\nI visit a Shinto shrine.",
  },
  {
    kanji: "人体",
    kana: "じんたい",
    english: "Human body",
    explanation: "Refers to the physical structure of a human being, including organs, tissues, and systems.",
    example: "{人体}の構造を学ぶ。\nI study the structure of the human body.",
  },
  {
    kanji: "睡眠",
    kana: "すいみん",
    english: "Sleep",
    explanation: "Refers to the natural state of rest in which the body and mind are inactive.",
    example: "十分な{睡眠}を取る。\nI get enough sleep.",
  },
  {
    kanji: "数学",
    kana: "すうがく",
    english: "Mathematics・Math",
    explanation: "Refers to the abstract science of numbers, quantity, and space.",
    example: "大学で{数学}を専攻する。\nI major in mathematics at university.",
  },
  {
    kanji: "数字",
    kana: "すうじ",
    english: "Number・Numeral",
    explanation: "Refers to a symbol or figure used to represent a quantity or value.",
    example: "電話番号の{数字}を覚える。\nI memorize the digits of the phone number.",
  },
  {
    kanji: "正解",
    kana: "せいかい",
    english: "Correct answer・Right solution",
    explanation: "Refers to the accurate or correct response to a question or problem.",
    example: "試験の{正解}を確認する。\nI check the correct answers for the exam.",
  },
  {
    kanji: "制限",
    kana: "せいげん",
    english: "Restriction・Limit",
    explanation: "Refers to the act of limiting or controlling something within certain boundaries.",
    example: "速度{制限}を守る。\nI obey the speed limit.",
  },
  {
    kanji: "清掃",
    kana: "せいそう",
    english: "Cleaning・Sanitation",
    explanation: "Refers to the act of cleaning or maintaining cleanliness in a space or environment.",
    example: "毎日オフィスを{清掃}する。\nI clean the office every day.",
  },
  {
    kanji: "制服",
    kana: "せいふく",
    english: "Uniform",
    explanation: "Refers to a standard set of clothing worn by members of an organization or group.",
    example: "学校の{制服}を着る。\nI wear the school uniform.",
  },
  {
    kanji: "設備",
    kana: "せつび",
    english: "Equipment・Facilities",
    explanation: "Refers to the necessary tools, machinery, or infrastructure used for a specific purpose.",
    example: "新しい{設備}を導入する。\nI introduce new equipment.",
  },
  {
    kanji: "先日",
    kana: "せんじつ",
    english: "The other day・A few days ago",
    explanation: "Refers to a recent day in the past, often used to mention something that happened not long ago.",
    example: "{先日}、友達と会った。\nI met my friend the other day.",
  },
  {
    kanji: "宣伝",
    kana: "せんでん",
    english: "Advertisement・Publicity",
    explanation: "Refers to the act of promoting or publicizing a product, service, or event to attract attention.",
    example: "新製品の{宣伝}を行う。\nI advertise the new product.",
  },
  {
    kanji: "先輩",
    kana: "せんぱい",
    english: "Senior・Upperclassman・Mentor",
    explanation: "Refers to a person who has more experience or seniority in a particular field or organization.",
    example: "{先輩}にアドバイスをもらう。\nI get advice from my senior.",
  },
  {
    kanji: "専門",
    kana: "せんもん",
    english: "Specialty・Field of study",
    explanation: "Refers to a specific area of expertise or study in which a person has specialized knowledge.",
    example: "彼の{専門}は経済学です。\nHis specialty is economics.",
  },
  {
    kanji: "前後",
    kana: "ぜんご",
    english: "Before and after・Front and back・Around",
    explanation: "Refers to the time or position surrounding a particular event or object.",
    example: "会議の{前後}に準備をする。\nI prepare before and after the meeting.",
  },
  {
    kanji: "前半",
    kana: "ぜんはん",
    english: "First half・Initial stage",
    explanation: "Refers to the first part of a period or event.",
    example: "試合の{前半}が終了する。\nThe first half of the game ends.",
  },
  {
    kanji: "倉庫",
    kana: "そうこ",
    english: "Warehouse・Storage",
    explanation: "Refers to a building or space used for storing goods or materials.",
    example: "商品の{倉庫}を管理する。\nI manage the warehouse for products.",
  },
  {
    kanji: "掃除",
    kana: "そうじ",
    english: "Cleaning・Tidying up",
    explanation: "Refers to the act of cleaning or tidying a space or area.",
    example: "部屋を{掃除}する。\nI clean the room.",
  },
  {
    kanji: "送信",
    kana: "そうしん",
    english: "Transmission・Sending",
    explanation: "Refers to the act of sending or transmitting information, messages, or data.",
    example: "メールを{送信}する。\nI send an email.",
  },
  {
    kanji: "想像",
    kana: "そうぞう",
    english: "Imagination・Conception",
    explanation: "Refers to the act of forming mental images or concepts of things that are not present or real.",
    example: "未来の生活を{想像}する。\nI imagine life in the future.",
  },
  {
    kanji: "早朝",
    kana: "そうちょう",
    english: "Early morning・Dawn",
    explanation: "Refers to the early hours of the morning, typically before sunrise.",
    example: "{早朝}にジョギングする。\nI go jogging in the early morning.",
  },
  {
    kanji: "相当",
    kana: "そうとう",
    english: "Considerable・Equivalent・Appropriate",
    explanation: "Refers to a significant amount or degree, or something that is suitable or fitting.",
    example: "彼は{相当}な努力をした。\nHe made considerable effort.",
  },
  {
    kanji: "送料",
    kana: "そうりょう",
    english: "Shipping fee・Postage",
    explanation: "Refers to the cost associated with sending goods or packages from one place to another.",
    example: "商品の{送料}を支払う。\nI pay the shipping fee for the product.",
  },
  {
    kanji: "外側",
    kana: "そとがわ",
    english: "Outside・Exterior",
    explanation: "Refers to the outer part or surface of something.",
    example: "建物の{外側}を掃除する。\nI clean the outside of the building.",
  },
  {
    kanji: "尊敬",
    kana: "そんけい",
    english: "Respect・Esteem",
    explanation: "Refers to the act of showing admiration or regard for someone or something.",
    example: "先生を{尊敬}する。\nI respect my teacher.",
  },
  {
    kanji: "増加",
    kana: "ぞうか",
    english: "Increase・Growth",
    explanation: "Refers to the act of becoming larger or greater in size, amount, or degree.",
    example: "売上が{増加}する。\nSales increase.",
  },
  {
    kanji: "滞在",
    kana: "たいざい",
    english: "Stay・Residence",
    explanation: "Refers to the act of remaining in a place for a period of time.",
    example: "ホテルに{滞在}する。\nI stay at a hotel.",
  },
  {
    kanji: "体操",
    kana: "たいそう",
    english: "Gymnastics・Exercise",
    explanation: "Refers to physical exercises or activities designed to improve strength, flexibility, and overall fitness.",
    example: "毎朝{体操}をする。\nI do exercises every morning.",
  },
  {
    kanji: "大量",
    kana: "たいりょう",
    english: "Large quantity・Massive amount",
    explanation: "Refers to a very large amount or number of something.",
    example: "水を{大量}に消費する。\nI consume a large quantity of water.",
  },
  {
    kanji: "体力",
    kana: "たいりょく",
    english: "Physical strength・Stamina",
    explanation: "Refers to the physical power and endurance of a person.",
    example: "スポーツには{体力}が必要です。\nPhysical strength is necessary for sports.",
  },
  {
    kanji: "誕生",
    kana: "たんじょう",
    english: "Birth・Creation",
    explanation: "Refers to the act of being born or the beginning of something.",
    example: "赤ちゃんが{誕生}する。\nA baby is born.",
  },
  {
    kanji: "代金",
    kana: "だいきん",
    english: "Payment・Price・Cost",
    explanation: "Refers to the amount of money required to pay for goods or services.",
    example: "商品の{代金}を支払う。\nI pay the cost of the product.",
  },
  {
    kanji: "代表",
    kana: "だいひょう",
    english: "Representative・Delegate",
    explanation: "Refers to a person who represents or acts on behalf of a group or organization.",
    example: "会社の{代表}として会議に出席する。\nI attend the meeting as a company representative.",
  },
  {
    kanji: "団体",
    kana: "だんたい",
    english: "Group・Organization",
    explanation: "Refers to a group of people or an organization formed for a specific purpose.",
    example: "スポーツの{団体}に参加する。\nI participate in a sports group.",
  },
  {
    kanji: "地下",
    kana: "ちか",
    english: "Underground・Basement",
    explanation: "Refers to a location or area that is below the surface of the ground.",
    example: "駅の{地下}に行く。\nI go to the underground station.",
  },
  {
    kanji: "遅刻",
    kana: "ちこく",
    english: "Tardiness・Being late",
    explanation: "Refers to the act of arriving late or not being on time for an appointment or event.",
    example: "会議に{遅刻}する。\nI am late for the meeting.",
  },
  {
    kanji: "知識",
    kana: "ちしき",
    english: "Knowledge・Information",
    explanation: "Refers to the information, understanding, and skills acquired through experience or education.",
    example: "新しい{知識}を学ぶ。\nI learn new knowledge.",
  },
  {
    kanji: "調査",
    kana: "ちょうさ",
    english: "Investigation・Survey",
    explanation: "Refers to the act of examining or studying something carefully to gather information.",
    example: "市場の{調査}を行う。\nI conduct a market survey.",
  },
  {
    kanji: "調子",
    kana: "ちょうし",
    english: "Condition・State・Tone",
    explanation: "Refers to the current state or condition of something, often related to health or performance.",
    example: "体の{調子}が良い。\nMy physical condition is good.",
  },
  {
    kanji: "頂上",
    kana: "ちょうじょう",
    english: "Summit・Top・Peak",
    explanation: "Refers to the highest point or peak of a mountain or hill.",
    example: "山の{頂上}に登る。\nI climb to the summit of the mountain.",
  },
  {
    kanji: "通学",
    kana: "つうがく",
    english: "Commuting to school",
    explanation: "Refers to the act of traveling to and from school on a regular basis.",
    example: "毎日電車で{通学}する。\nI commute to school by train every day.",
  },
  {
    kanji: "通勤",
    kana: "つうきん",
    english: "Commuting to work",
    explanation: "Refers to the act of traveling to and from one's workplace on a regular basis.",
    example: "バスで{通勤}する。\nI commute to work by bus.",
  },
  {
    kanji: "通訳",
    kana: "つうやく",
    english: "Interpretation・Interpreter",
    explanation: "Refers to the act of translating spoken language from one language to another.",
    example: "会議で{通訳}をする。\nI interpret at the meeting.",
  },
  {
    kanji: "通路",
    kana: "つうろ",
    english: "Aisle・Passageway",
    explanation: "Refers to a walkway or passage that allows people to move through an area.",
    example: "映画館の{通路}を歩く。\nI walk down the aisle in the movie theater.",
  },
  {
    kanji: "定員",
    kana: "ていいん",
    english: "Capacity・Fixed number of people",
    explanation: "Refers to the maximum number of people allowed in a space or facility.",
    example: "バスの{定員}は50人です。\nThe bus has a capacity of 50 people.",
  },
  {
    kanji: "低下",
    kana: "ていか",
    english: "Decline・Decrease",
    explanation: "Refers to the act of becoming lower or less in amount, quality, or value.",
    example: "体力が{低下}する。\nPhysical strength declines.",
  },
  {
    kanji: "定期",
    kana: "ていき",
    english: "Fixed term・Regular・Periodic・Commuter pass",
    explanation: "Refers to something that occurs at regular intervals or a pass used for regular commuting.",
    example: "{定期}券を購入する。\nI buy a commuter pass.",
  },
  {
    kanji: "停電",
    kana: "ていでん",
    english: "Power outage・Blackout",
    explanation: "Refers to a temporary loss of electrical power in a specific area.",
    example: "突然の{停電}が起きた。\nA sudden power outage occurred.",
  },
  {
    kanji: "手帳",
    kana: "てちょう",
    english: "Notebook・Planner・Diary",
    explanation: "Refers to a small book used for writing notes, schedules, or personal thoughts.",
    example: "毎日{手帳}に予定を書き込む。\nI write my schedule in my planner every day.",
  },
  {
    kanji: "鉄道",
    kana: "てつどう",
    english: "Railway・Railroad",
    explanation: "Refers to a system of tracks and trains used for transportation of people and goods.",
    example: "{鉄道}で旅行する。\nI travel by railway.",
  },
  {
    kanji: "手袋",
    kana: "てぶくろ",
    english: "Gloves",
    explanation: "Refers to a piece of clothing worn on the hands for warmth or protection.",
    example: "寒い日に{手袋}を着ける。\nI wear gloves on a cold day.",
  },
  {
    kanji: "転勤",
    kana: "てんきん",
    english: "Job transfer・Relocation",
    explanation: "Refers to the act of being transferred to a different location or branch within a company.",
    example: "来月{転勤}することになった。\nI am going to be transferred next month.",
  },
  {
    kanji: "天井",
    kana: "てんじょう",
    english: "Ceiling",
    explanation: "Refers to the upper interior surface of a room or building.",
    example: "部屋の{天井}が高い。\nThe ceiling of the room is high.",
  },
  {
    kanji: "電球",
    kana: "でんきゅう",
    english: "Light bulb",
    explanation: "Refers to a device that produces light when electricity passes through it.",
    example: "電球が切れたので交換する。\nI replace the light bulb because it burned out.",
  },
  {
    kanji: "伝言",
    kana: "でんごん",
    english: "Message・Communication",
    explanation: "Refers to a piece of information or communication conveyed from one person to another.",
    example: "友達に{伝言}を伝える。\nI convey a message to my friend.",
  },
  {
    kanji: "当日",
    kana: "とうじつ",
    english: "The day・That day",
    explanation: "Refers to the specific day on which an event or activity takes place.",
    example: "{当日}に会場に行く。\nI go to the venue on the day of the event.",
  },
  {
    kanji: "登場",
    kana: "とうじょう",
    english: "Appearance・Entry・Debut",
    explanation: "Refers to the act of appearing or entering a scene, often in a performance or event.",
    example: "新しいキャラクターが{登場}する。\nA new character makes an appearance.",
  },
  {
    kanji: "到着",
    kana: "とうちゃく",
    english: "Arrival",
    explanation: "Refers to the act of reaching a destination or arriving at a place.",
    example: "空港に{到着}する。\nI arrive at the airport.",
  },
  {
    kanji: "都会",
    kana: "とかい",
    english: "City・Urban area",
    explanation: "Refers to a large and densely populated area characterized by buildings, infrastructure, and cultural activities.",
    example: "{都会}での生活は便利です。\nLife in the city is convenient.",
  },
  {
    kanji: "特徴",
    kana: "とくちょう",
    english: "Characteristic・Feature",
    explanation: "Refers to a distinguishing quality or attribute that sets something apart from others.",
    example: "この製品の{特徴}を説明する。\nI explain the features of this product.",
  },
  {
    kanji: "登山",
    kana: "とざん",
    english: "Mountain climbing・Hiking",
    explanation: "Refers to the activity of climbing or hiking up mountains.",
    example: "週末に{登山}に行く。\nI go mountain climbing on the weekend.",
  },
  {
    kanji: "土地",
    kana: "とち",
    english: "Land・Plot・Soil",
    explanation: "Refers to a specific area of ground or property, often used for building or agriculture.",
    example: "新しい{土地}を購入する。\nI buy a new plot of land.",
  },
  {
    kanji: "途中",
    kana: "とちゅう",
    english: "On the way・In the middle of",
    explanation: "Refers to being in the process of going somewhere or doing something.",
    example: "帰り{途中}で買い物をする。\nI do some shopping on the way home.",
  },
  {
    kanji: "徒歩",
    kana: "とほ",
    english: "On foot・Walking",
    explanation: "Refers to the act of traveling by walking rather than using a vehicle.",
    example: "駅まで{徒歩}で行く。\nI go to the station on foot.",
  },
  {
    kanji: "独立",
    kana: "どくりつ",
    english: "Independence・Self-reliance",
    explanation: "Refers to the state of being self-sufficient and not dependent on others.",
    example: "若いうちに{独立}したい。\nI want to become independent while I am young.",
  },
  {
    kanji: "仲間",
    kana: "なかま",
    english: "Companion・Comrade・Colleague",
    explanation: "Refers to a person who is part of a group or shares common interests or activities.",
    example: "友達は大切な{仲間}です。\nFriends are important companions.",
  },
  {
    kanji: "中身",
    kana: "なかみ",
    english: "Contents・Inside・Filling",
    explanation: "Refers to the inner part or substance of something.",
    example: "箱の{中身}を確認する。\nI check the contents of the box.",
  },
  {
    kanji: "納得",
    kana: "なっとく",
    english: "Consent・Understanding・Agreement",
    explanation: "Refers to the act of accepting or agreeing to something after understanding it.",
    example: "説明に{納得}する。\nI am convinced by the explanation.",
  },
  {
    kanji: "日時",
    kana: "にちじ",
    english: "Date and time",
    explanation: "Refers to the specific day and time when an event or activity is scheduled to occur.",
    example: "会議の{日時}を確認する。\nI check the date and time of the meeting.",
  },
  {
    kanji: "日常",
    kana: "にちじょう",
    english: "Everyday life・Daily routine",
    explanation: "Refers to the regular activities and routines that make up a person's daily life.",
    example: "{日常}生活を楽しむ。\nI enjoy my everyday life.",
  },
  {
    kanji: "日光",
    kana: "にっこう",
    english: "Sunlight・Sunshine",
    explanation: "Refers to the light and warmth produced by the sun.",
    example: "{日光}を浴びる。\nI bask in the sunlight.",
  },
  {
    kanji: "日程",
    kana: "にってい",
    english: "Schedule・Itinerary",
    explanation: "Refers to a planned list of events or activities with specific dates and times.",
    example: "旅行の{日程}を立てる。\nI make a travel itinerary.",
  },
  {
    kanji: "入門",
    kana: "にゅうもん",
    english: "Introduction (to)・Beginner's course",
    explanation: "Refers to the act of entering or starting to learn about a new subject or field.",
    example: "プログラミングの{入門}コースを受講する。\nI take an introductory course in programming.",
  },
  {
    kanji: "入力",
    kana: "にゅうりょく",
    english: "Input・Data entry",
    explanation: "Refers to the act of entering data or information into a computer or system.",
    example: "コンピュータにデータを{入力}する。\nI input data into the computer.",
  },
  {
    kanji: "人数",
    kana: "にんずう",
    english: "Number of people・Headcount",
    explanation: "Refers to the total count of individuals in a group or gathering.",
    example: "パーティーの{人数}を確認する。\nI check the number of people for the party.",
  },
  {
    kanji: "値段",
    kana: "ねだん",
    english: "Price・Cost・Value",
    explanation: "Refers to the amount of money required to purchase goods or services.",
    example: "商品の{値段}を調べる。\nI check the price of the product.",
  },
  {
    kanji: "寝坊",
    kana: "ねぼう",
    english: "Oversleeping・Sleeping in",
    explanation: "Refers to the act of sleeping longer than intended, often resulting in being late.",
    example: "今日は{寝坊}してしまった。\nI overslept today.",
  },
  {
    kanji: "年齢",
    kana: "ねんれい",
    english: "Age・Years old",
    explanation: "Refers to the number of years a person has lived since birth.",
    example: "彼の{年齢}は25歳です。\nHe is 25 years old.",
  },
  {
    kanji: "農業",
    kana: "のうぎょう",
    english: "Agriculture・Farming",
    explanation: "Refers to the practice of cultivating land and raising crops or livestock for food production.",
    example: "{農業}は重要な産業です。\nAgriculture is an important industry.",
  },
  {
    kanji: "配達",
    kana: "はいたつ",
    english: "Delivery・Distribution",
    explanation: "Refers to the act of transporting and delivering goods or packages to a specified location.",
    example: "荷物を{配達}する。\nI deliver the package.",
  },
  {
    kanji: "発音",
    kana: "はつおん",
    english: "Pronunciation",
    explanation: "Refers to the way in which a word or language is spoken or articulated.",
    example: "英語の{発音}を練習する。\nI practice English pronunciation.",
  },
  {
    kanji: "発生",
    kana: "はっせい",
    english: "Occurrence・Outbreak・Generation",
    explanation: "Refers to the act of something happening or coming into existence.",
    example: "地震が{発生}した。\nAn earthquake occurred.",
  },
  {
    kanji: "発展",
    kana: "はってん",
    english: "Development・Expansion・Progress",
    explanation: "Refers to the process of growth, advancement, or improvement in a particular area or field.",
    example: "経済の{発展}が続いている。\nThe economic development continues.",
  },
  {
    kanji: "発売",
    kana: "はつばい",
    english: "Release・Launch・Sale",
    explanation: "Refers to the act of making a product or service available for purchase or use.",
    example: "新しいスマートフォンが{発売}される。\nA new smartphone is released.",
  },
  {
    kanji: "売店",
    kana: "ばいてん",
    english: "Kiosk・Stand・Booth",
    explanation: "Refers to a small shop or stall that sells goods, often located in public places.",
    example: "駅の{売店}でお土産を買う。\nI buy souvenirs at the kiosk in the station.",
  },
  {
    kanji: "比較",
    kana: "ひかく",
    english: "Comparison・Contrast",
    explanation: "Refers to the act of examining the similarities and differences between two or more things.",
    example: "製品の性能を{比較}する。\nI compare the performance of the products.",
  },
  {
    kanji: "非常",
    kana: "ひじょう",
    english: "Emergency・Extraordinary",
    explanation: "Refers to a situation that requires immediate action or attention due to its urgency or severity.",
    example: "{非常}事態に備える。\nI prepare for emergencies.",
  },
  {
    kanji: "否定",
    kana: "ひてい",
    english: "Denial・Negation",
    explanation: "Refers to the act of rejecting or refusing to accept something as true or valid.",
    example: "彼の意見を{否定}する。\nI deny his opinion.",
  },
  {
    kanji: "避難",
    kana: "ひなん",
    english: "Evacuation・Taking refuge",
    explanation: "Refers to the act of moving to a safe place to avoid danger or harm.",
    example: "地震の際に{避難}する。\nI evacuate during an earthquake.",
  },
  {
    kanji: "秘密",
    kana: "ひみつ",
    english: "Secret・Confidentiality",
    explanation: "Refers to information that is kept hidden or private from others.",
    example: "その話は{秘密}にしておいてください。\nPlease keep that story a secret.",
  },
  {
    kanji: "表紙",
    kana: "ひょうし",
    english: "Cover (of a book)・Front page",
    explanation: "Refers to the outer covering or front page of a book or magazine.",
    example: "本の{表紙}を飾る。\nI decorate the cover of the book.",
  },
  {
    kanji: "表面",
    kana: "ひょうめん",
    english: "Surface・Exterior",
    explanation: "Refers to the outermost layer or appearance of an object or material.",
    example: "水の{表面}に波が立つ。\nWaves form on the surface of the water.",
  }
];