export const NIHONGO_NO_MORI_JLPT_N2: JLPTReview[] = [
  {
    kanji: "胃",
    kana: "い",
    english: "Stomach",
    explanation: "Refers to the stomach, an organ in the digestive system.",
    example: "彼は胃の調子が悪い。\nHe has a stomachache.",
  },
  {
    kanji: "裏",
    kana: "うら",
    english: "Back・Reverse side",
    explanation: "Refers to the back side or reverse side of something.",
    example: "この紙の裏に書いてください。\nPlease write on the back of this paper.",
  },
  {
    kanji: "噂",
    kana: "うわさ",
    english: "Rumor",
    explanation: "Refers to a piece of information or a story that is passed from person to person, often without confirmation of its truth.",
    example: "彼女についての噂を聞いた。\nI heard a rumor about her.",
  },
  {
    kanji: "餌",
    kana: "えさ",
    english: "Feed・Bait",
    explanation: "Refers to food given to animals or bait used to catch fish.",
    example: "魚に餌をあげる。\nI feed the fish.",
  },
  {
    kanji: "枝",
    kana: "えだ",
    english: "Branch・Twig",
    explanation: "Refers to a branch or twig of a tree.",
    example: "鳥が枝にとまっている。\nA bird is perched on the branch.",
  },
  {
    kanji: "襟",
    kana: "えり",
    english: "Collar",
    explanation: "Refers to the collar of a shirt or jacket.",
    example: "シャツの襟が汚れている。\nThe collar of the shirt is dirty.",
  },
  {
    kanji: "課",
    kana: "か",
    english: "Section・Lesson・Department",
    explanation: "Refers to a section or department within an organization.",
    example: "営業課で働いています。\nI work in the sales department.",
  },
  {
    kanji: "壁",
    kana: "かべ",
    english: "Wall",
    explanation: "Refers to a wall, a vertical structure that defines and sometimes protects an area.",
    example: "壁に絵を掛ける。\nI hang a picture on the wall.",
  },
  {
    kanji: "雷",
    kana: "かみなり",
    english: "Thunder・Lightning",
    explanation: "Refers to the natural phenomenon of thunder and lightning during a storm.",
    example: "雷が鳴っている。\nThe thunder is rumbling.",
  },
  {
    kanji: "缶",
    kana: "かん",
    english: "Can・Tin",
    explanation: "Refers to a metal container used for storing food or drinks.",
    example: "缶ジュースを買った。\nI bought a can of juice.",
  },
  {
    kanji: "雲",
    kana: "くも",
    english: "Cloud",
    explanation: "Refers to a visible mass of condensed water vapor floating in the atmosphere.",
    example: "空に雲が浮かんでいる。\nThere are clouds floating in the sky.",
  },
  {
    kanji: "煙",
    kana: "けむり",
    english: "Smoke",
    explanation: "Refers to the visible vapor and gases produced by burning or combustion.",
    example: "煙が立ち上っている。\nSmoke is rising.",
  },
  {
    kanji: "塩",
    kana: "しお",
    english: "Salt",
    explanation: "Refers to a mineral used for seasoning and preserving food.",
    example: "料理に塩を加える。\nI add salt to the dish.",
  },
  {
    kanji: "島",
    kana: "しま",
    english: "Island",
    explanation: "Refers to a landmass surrounded by water.",
    example: "夏に島へ旅行する。\nI will travel to an island in the summer.",
  },
  {
    kanji: "城",
    kana: "しろ",
    english: "Castle・Fortress",
    explanation: "Refers to a large fortified building or group of buildings.",
    example: "有名な城を見学した。\nI visited a famous castle.",
  },
  {
    kanji: "隅",
    kana: "すみ",
    english: "Corner",
    explanation: "Refers to the point or area where two lines or surfaces meet.",
    example: "部屋の隅に置く。\nI place it in the corner of the room.",
  },
  {
    kanji: "咳",
    kana: "せき",
    english: "Cough",
    explanation: "Refers to the act of expelling air from the lungs with a sudden sound.",
    example: "風邪で咳が出る。\nI have a cough because of a cold.",
  },
  {
    kanji: "底",
    kana: "そこ",
    english: "Bottom・Base",
    explanation: "Refers to the lowest part or point of something.",
    example: "箱の底に何かある。\nThere is something at the bottom of the box.",
  },
  {
    kanji: "像",
    kana: "ぞう",
    english: "Statue・Image",
    explanation: "Refers to a three-dimensional representation of a person or animal.",
    example: "有名な像を見た。\nI saw a famous statue.",
  },
  {
    kanji: "毒",
    kana: "どく",
    english: "Poison・Toxin",
    explanation: "Refers to a substance that can cause harm or death if ingested or absorbed.",
    example: "そのキノコは毒がある。\nThat mushroom is poisonous.",
  },
  {
    kanji: "謎",
    kana: "なぞ",
    english: "Mystery・Riddle",
    explanation: "Refers to something that is difficult to understand or explain.",
    example: "その事件は謎に包まれている。\nThe case is shrouded in mystery.",
  },
  {
    kanji: "鍋",
    kana: "なべ",
    english: "Pot・Pan",
    explanation: "Refers to a cooking vessel used for boiling or simmering food.",
    example: "鍋でスープを作る。\nI make soup in a pot.",
  },
  {
    kanji: "波",
    kana: "なみ",
    english: "Wave",
    explanation: "Refers to a moving ridge or swell on the surface of water.",
    example: "海の波が高い。\nThe waves in the sea are high.",
  },
  {
    kanji: "涙",
    kana: "なみだ",
    english: "Tears",
    explanation: "Refers to the drops of clear, salty liquid produced by the eyes when crying.",
    example: "彼女は涙を流した。\nShe shed tears.",
  },
  {
    kanji: "庭",
    kana: "にわ",
    english: "Garden・Yard",
    explanation: "Refers to an area of land, often near a house, used for growing plants or for outdoor activities.",
    example: "庭で花を育てる。\nI grow flowers in the garden.",
  },
  {
    kanji: "箸",
    kana: "はし",
    english: "Chopsticks",
    explanation: "Refers to a pair of small, slender sticks used as eating utensils in many Asian countries.",
    example: "箸でご飯を食べる。\nI eat rice with chopsticks.",
  },
  {
    kanji: "畑",
    kana: "はたけ",
    english: "Field・Farm",
    explanation: "Refers to a piece of land used for growing crops or vegetables.",
    example: "畑で野菜を育てる。\nI grow vegetables in the field.",
  },
  {
    kanji: "羽",
    kana: "はね",
    english: "Feather・Wing",
    explanation: "Refers to the light, flat structures that cover the bodies of birds and enable them to fly.",
    example: "鳥の羽が美しい。\nThe bird's feathers are beautiful.",
  },
  {
    kanji: "幅",
    kana: "はば",
    english: "Width・Breadth",
    explanation: "Refers to the measurement of something from side to side.",
    example: "この道の幅は広い。\nThe width of this road is wide.",
  },
  {
    kanji: "膝",
    kana: "ひざ",
    english: "Knee",
    explanation: "Refers to the joint between the thigh and the lower leg in humans.",
    example: "膝を曲げる。\nI bend my knee.",
  },
  {
    kanji: "袋",
    kana: "ふくろ",
    english: "Bag・Sack",
    explanation: "Refers to a flexible container used for carrying or storing items.",
    example: "買い物袋を持っている。\nI have a shopping bag.",
  },
  {
    kanji: "骨",
    kana: "ほね",
    english: "Bone",
    explanation: "Refers to the rigid organs that make up the skeleton of vertebrates.",
    example: "犬が骨をかじっている。\nThe dog is chewing on a bone.",
  },
  {
    kanji: "棒",
    kana: "ぼう",
    english: "Rod・Stick",
    explanation: "Refers to a long, thin, cylindrical object.",
    example: "釣り竿の棒が折れた。\nThe fishing rod broke.",
  },
  {
    kanji: "孫",
    kana: "まご",
    english: "Grandchild",
    explanation: "Refers to the child of one's son or daughter.",
    example: "彼は三人の孫がいる。\nHe has three grandchildren.",
  },
  {
    kanji: "湖",
    kana: "みずうみ",
    english: "Lake",
    explanation: "Refers to a large body of water surrounded by land.",
    example: "美しい湖を訪れた。\nI visited a beautiful lake.",
  },
  {
    kanji: "胸",
    kana: "むね",
    english: "Chest・Breast",
    explanation: "Refers to the front part of the body between the neck and the abdomen.",
    example: "胸が痛い。\nMy chest hurts.",
  },
  {
    kanji: "床",
    kana: "ゆか",
    english: "Floor",
    explanation: "Refers to the lower surface of a room on which one stands.",
    example: "床を掃除する。\nI clean the floor.",
  },
  {
    kanji: "寮",
    kana: "りょう",
    english: "Dormitory",
    explanation: "Refers to a building where students or workers live and sleep.",
    example: "大学の寮に住んでいる。\nI live in a university dormitory.",
  },
  {
    kanji: "量",
    kana: "りょう",
    english: "Quantity・Amount",
    explanation: "Refers to the amount or number of something.",
    example: "水の量を測る。\nI measure the amount of water.",
  },
  {
    kanji: "列",
    kana: "れつ",
    english: "Line・Row",
    explanation: "Refers to a series of people or things arranged in a straight line.",
    example: "バスの列に並ぶ。\nI line up for the bus.",
  },
  {
    kanji: "合図",
    kana: "あいず",
    english: "Signal・Sign",
    explanation: "Refers to a gesture, action, or sound that conveys information or instructions.",
    example: "出発の合図を送る。\nI give the signal to depart.",
  },
  {
    kanji: "以外",
    kana: "いがい",
    english: "Except・Other than・With the exception of",
    explanation: "Refers to something that is not included or is different from what has been mentioned.",
    example: "彼以外は全員来た。\nEveryone except him came.",
  },
  {
    kanji: "以後",
    kana: "いご",
    english: "After that・From now on",
    explanation: "Refers to the time following a specific point or event.",
    example: "会議は午後2時以後に始まる。\nThe meeting starts after 2 PM.",
  },
  {
    kanji: "以降",
    kana: "いこう",
    english: "From...onward・Thereafter",
    explanation: "Refers to the time from a specific point onward.",
    example: "来週以降、忙しくなる。\nI will be busy from next week onward.",
  },
  {
    kanji: "維持",
    kana: "いじ",
    english: "Maintenance・Preservation",
    explanation: "Refers to the act of keeping something in good condition or continuing a certain state.",
    example: "健康を維持するために運動する。\nI exercise to maintain my health.",
  },
  {
    kanji: "意識",
    kana: "いしき",
    english: "Consciousness・Awareness",
    explanation: "Refers to the state of being aware of and able to think about one's own existence, thoughts, and surroundings.",
    example: "彼は意識を失った。\nHe lost consciousness.",
  },
  {
    kanji: "以前",
    kana: "いぜん",
    english: "Before・Ago・Previously",
    explanation: "Refers to a time before the present or a specific event.",
    example: "彼に会ったのは以前のことだ。\nI met him a long time ago.",
  },
  {
    kanji: "位置",
    kana: "いち",
    english: "Position・Location",
    explanation: "Refers to the place or location of something.",
    example: "駅の位置を確認する。\nI check the location of the station.",
  },
  {
    kanji: "一流",
    kana: "いちりゅう",
    english: "First-class・Top-notch",
    explanation: "Refers to something or someone of the highest quality or rank.",
    example: "彼は一流の料理人だ。\nHe is a first-class chef.",
  },
  {
    kanji: "一般",
    kana: "いっぱん",
    english: "General・Common",
    explanation: "Refers to something that is common or applies to most people or things.",
    example: "一般の人々に公開する。\nIt is open to the general public.",
  },
  {
    kanji: "以内",
    kana: "いない",
    english: "Within・Inside of",
    explanation: "Refers to a limit or boundary that should not be exceeded.",
    example: "10分以内に戻ります。\nI will return within 10 minutes.",
  },
  {
    kanji: "田舎",
    kana: "いなか",
    english: "Countryside・Rural area",
    explanation: "Refers to areas outside of cities and towns, often characterized by farming and open spaces.",
    example: "田舎での生活は静かだ。\nLife in the countryside is peaceful.",
  },
  {
    kanji: "印刷",
    kana: "いんさつ",
    english: "Printing",
    explanation: "Refers to the process of producing text and images on paper using a printing press or printer.",
    example: "書類を印刷する。\nI print the documents.",
  },
  {
    kanji: "飲料",
    kana: "いんりょう",
    english: "Beverage・Drink",
    explanation: "Refers to liquids that can be consumed, such as water, tea, or juice.",
    example: "飲料水を買う。\nI buy drinking water.",
  },
  {
    kanji: "宇宙",
    kana: "うちゅう",
    english: "Universe・Space",
    explanation: "Refers to the vast expanse that contains all matter and energy, including planets, stars, and galaxies.",
    example: "宇宙の謎を解明する。\nI explore the mysteries of the universe.",
  },
  {
    kanji: "営業",
    kana: "えいぎょう",
    english: "Business・Sales・Operations",
    explanation: "Refers to the activities involved in running a business or selling products and services.",
    example: "営業成績を上げる。\nI improve sales performance.",
  },
  {
    kanji: "栄養",
    kana: "えいよう",
    english: "Nutrition・Nourishment",
    explanation: "Refers to the process of providing or obtaining the food necessary for health and growth.",
    example: "栄養バランスの良い食事をする。\nI eat a nutritionally balanced diet.",
  },
  {
    kanji: "演奏",
    kana: "えんそう",
    english: "Performance・Musical performance",
    explanation: "Refers to the act of performing music or a musical piece.",
    example: "ピアノを演奏する。\nI perform on the piano.",
  },
  {
    kanji: "遠慮",
    kana: "えんりょ",
    english: "Restraint・Hesitation・Courtesy",
    explanation: "Refers to the act of holding back or being considerate of others' feelings.",
    example: "遠慮せずに食べてください。\nPlease eat without hesitation.",
  },
  {
    kanji: "往復",
    kana: "おうふく",
    english: "Round trip・Return",
    explanation: "Refers to a journey to a place and back again.",
    example: "東京への往復切符を買う。\nI buy a round-trip ticket to Tokyo.",
  },
  {
    kanji: "応募",
    kana: "おうぼ",
    english: "Application・Entry",
    explanation: "Refers to the act of applying for a job, position, or opportunity.",
    example: "新しい仕事に応募する。\nI apply for a new job.",
  },
  {
    kanji: "応用",
    kana: "おうよう",
    english: "Application・Practical use",
    explanation: "Refers to the practical use or implementation of knowledge or skills.",
    example: "理論を応用する。\nI apply the theory in practice.",
  },
  {
    kanji: "大勢",
    kana: "おおぜい",
    english: "Crowd・Many people",
    explanation: "Refers to a large number of people gathered together.",
    example: "大勢の人が集まった。\nA crowd of people gathered.",
  },
  {
    kanji: "親子",
    kana: "おやこ",
    english: "Parent and child",
    explanation: "Refers to the relationship between a parent and their child.",
    example: "親子で遊園地に行く。\nI go to the amusement park with my child.",
  },
  {
    kanji: "絵画",
    kana: "かいが",
    english: "Painting・Picture",
    explanation: "Refers to a visual artwork created using paint on a surface such as canvas or paper.",
    example: "美術館で絵画を鑑賞する。\nI appreciate paintings at the art museum.",
  },
  {
    kanji: "会計",
    kana: "かいけい",
    english: "Accounting・Bill・Payment",
    explanation: "Refers to the process of managing financial records or the act of settling a bill.",
    example: "レストランで会計をする。\nI pay the bill at the restaurant.",
  },
  {
    kanji: "解決",
    kana: "かいけつ",
    english: "Solution・Resolution",
    explanation: "Refers to the act of finding a solution to a problem or resolving an issue.",
    example: "問題を解決する。\nI solve the problem.",
  },
  {
    kanji: "解説",
    kana: "かいせつ",
    english: "Explanation・Commentary",
    explanation: "Refers to the act of providing an explanation or commentary on a topic.",
    example: "試合の解説を聞く。\nI listen to the commentary of the game.",
  },
  {
    kanji: "回収",
    kana: "かいしゅう",
    english: "Collection・Recovery",
    explanation: "Refers to the act of collecting or retrieving something.",
    example: "ゴミを回収する。\nI collect the garbage.",
  },
  {
    kanji: "開始",
    kana: "かいし",
    english: "Start・Commencement",
    explanation: "Refers to the act of beginning or starting something.",
    example: "試合が開始される。\nThe game will start.",
  },
  {
    kanji: "開場",
    kana: "かいじょう",
    english: "Opening of a venue・Admission",
    explanation: "Refers to the act of opening a place for public access or admission.",
    example: "コンサート会場が開場する。\nThe concert venue opens.",
  },
  {
    kanji: "開店",
    kana: "かいてん",
    english: "Opening of a store・Shop opening",
    explanation: "Refers to the act of opening a store or shop for business.",
    example: "新しい店が開店する。\nA new store is opening.",
  },
  {
    kanji: "回数",
    kana: "かいすう",
    english: "Number of times・Frequency",
    explanation: "Refers to the count or frequency of occurrences of an event or action.",
    example: "運動の回数を増やす。\nI increase the number of times I exercise.",
  },
  {
    kanji: "価格",
    kana: "かかく",
    english: "Price・Cost",
    explanation: "Refers to the amount of money required to purchase something.",
    example: "商品の価格を調べる。\nI check the price of the product.",
  }
];