export const VOCABS_N2: TVocabJLPT[] = [
  {
    word: "一家",
    reading: "いっか", 
    meaning: "a family, a household",
    example: "一家の大黒柱",
    exampleReading: "いっかのだいこくばしら",
    exampleMeaning: "the head of a family",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ ファミリー  ", "= 一家団欒 [いっかだんらん] family gathering"],
  },
  {
    word: "存在",
    reading: "そんざい",
    meaning: "existence, being",
    example: "家族は本当にありがたい存在だ。",
    exampleReading: "かぞくはほんとうにありがたいそんざいだ。",
    exampleMeaning: "Family is truly a precious existence.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "向き合う",
    reading: "むきあう",
    meaning: "to face each other, to confront",
    example: "家族みんなで問題に向き合っている。", 
    exampleReading: "かぞくみんなでもんだいにむきあっている。",
    exampleMeaning: "The whole family is facing the problem together.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "つくづく",
    reading: "つくづく",
    meaning: "deeply, greatly, thoroughly",
    example: "最近、家族のありがたさをつくづくと感じる。", 
    exampleReading: "さいきん、かぞくのありがたさをつくづくとかんじる。",
    exampleMeaning: "Recently, I feel deeply grateful for my family.",
    type: ["adverb"],
    _JLPT: true,
    info: "Used to express a deep or thorough feeling about something. Particle と is often used with it.",
    extra: ["+ しみじみ deeply", ""],
  },
  {
    word: "養う",
    reading: "やしなう",
    meaning: "To rpovide for, to support", 
    example: "父は一生懸命に働いて、家族を養っている。",
    exampleReading: "ちちはいっしょうけんめいにはたらいて、かぞくをやしなっている。",
    exampleMeaning: "My father works hard to support(provide for) the family.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "役目",
    reading: "やくめ",
    meaning: "role, duty, responsibility",
    example: "子どもを育てることが親の役目だ。",
    exampleReading: "こどもをそだてることがおやのやくめだ。",
    exampleMeaning: "Raising children is the parent's responsibility.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "甘える",
    reading: "あまえる",
    meaning: "to behave like a spoiled child, to depend on",
    example: "妹は子どもの頃から、母に甘えている。",
    exampleReading: "いもうとはこどものころから、ははにあまえている。",
    exampleMeaning: "My younger sister has been depending on our mother since childhood.",
    type: ["る verb"],
    _JLPT: true,
    extra: ["+ 甘え Lack of self-reliance", "+ 甘やかす To spoil"],
  },
  {
    word: "世間知らず",
    reading: "せけんしらず",
    meaning: "naive, inexperienced, ignorant of the world",
    example: "父に「おまえは世間知らずだ」と言われた。",
    exampleReading: "ちちに「おまえはせけんしらずだ」といわれた。",
    exampleMeaning: "My father told me, 'You are naive.'",
    type: ["noun", "な adjective"],
    _JLPT: true,
    info: "ず patters works like ないで pattern, indicating a lack of something. Often used with particle に.",
  },
  {
    word: "躾",
    reading: "しつけ",
    meaning: "discipline, training, upbringing",
    example: "子どもの躾は、親の義務だ。",
    exampleReading: "こどものしつけは、おやのぎむだ。",
    exampleMeaning: "Disciplining children is the parent's duty.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ しつける To discipline, to train"],
  },
  {
    word: "義務",
    reading: "ぎむ",
    meaning: "duty, obligation",
    example: "親には子どもを育てる義務がある。",
    exampleReading: "おやにはこどもをそだてるぎむがある。",
    exampleMeaning: "Parents have the duty to raise their children.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "言いつける",
    reading: "いいつける",
    meaning: "to tell, to order, to instruct",
    example: "兄は妹のいたずらを母に言いつけた。",
    exampleReading: "あにはいもうとのいたずらをははにいいつけた。",
    exampleMeaning: "My older brother told our mother about my younger sister's mischief.",
    type: ["る verb"],
    _JLPT: true, 
  },
  {
    word: "自立",
    reading: "じりつ",
    meaning: "independence, self-reliance",
    example: "兄は自立して、一人暮らしをしている。",
    exampleReading: "あにはじりつして、ひとりぐらしをしている。",
    exampleMeaning: "My older brother is independent and living alone.",
    type: ["noun", "する verb"],
    _JLPT: true, 
  },
  {
    word: "言います",
    reading: "いいます",
    meaning: "to start saying",
    example: "妹はアメリカに語学留学したいと言い出した。",
    exampleReading: "いもうとはアメリカにごがくりゅうがくしたいといいだした。",
    exampleMeaning: "My younger sister started saying she wants to study language in America.",
    type: ["う verb"],
    _JLPT: true, 
  },
  {
    word: "意思",
    reading: "いし",
    meaning: "intention, will, purpose",
    example: "親に自分の意思を伝えるのは難しい。", 
    exampleReading: "おやにじぶんのいしをつたえるのはむずかしい。",
    exampleMeaning: "It's difficult to tell my own intentions to my parents.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "尊重",
    reading: "そんちょう",
    meaning: "respect, esteem",
    example: "両親はいつも、私の意見を尊重してくれる。",
    exampleReading: "りょうしんはいつも、わたしのいけんをそんちょうしてくれる。",
    exampleMeaning: "My parents always respect my opinions.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "説得",
    reading: "せっとく",
    meaning: "convincing, persuasion", 
    example: "父は私の留学に反対だったが、母が説得してくれた。",
    exampleReading: "ちちはわたしのりゅうがくにはんたいだったが、ははがせっとくしてくれた。",
    exampleMeaning: "My father was against my studying abroad, but my mother persuaded him.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "納得",
    reading: "なっとく",
    meaning: "acknowledgement, understanding, agreement",
    example: "父は私の留学を、やっと納得してくれた。",
    exampleReading: "ちちはわたしのりゅうがくを、やっとなっとくしてくれた。",
    exampleMeaning: "My father finally agreed to my studying abroad.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "逆らう",
    reading: "さからう",
    meaning: "to go against, to oppose",
    example: "惹いときは、よく親に塗らった。\n強い風に逆らって歩く。", 
    exampleReading: "ときは、よくおやにさからった。\nつよいかぜにさからってあるく。",
    exampleMeaning: "In my youth, I often went against my parents.\nI walk against the strong wind.",
    type: ["う verb"],
    _JLPT: true,
    info: "Used to indicate going against someone or opposing something.",
    extra: ["+ 抵抗 [ていこう] resistance"],
  },
  {
    word: "反省",
    reading: "はんせい",
    meaning: "reflection, reconsideration",
    example: "昔親に逆らったことを、今は反省している。",
    exampleReading: "むかしおやにさからったことを、いまははんせいしている。",
    exampleMeaning: "I now reflect on the times I went against my parents in the past.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 反省会 [はんせいかい] reflection meeting"],
  },
  {
    word: "放っておく",
    reading: "ほうっておく",
    meaning: "to leave alone", 
    example: "父はいちいちうるさい。放っておいてほしい。",
    exampleReading: "ちちはいちいちうるさい。ほうっておいてほしい。",
    exampleMeaning: "My father is so annoying. I wish he would leave me alone.",
    type: ["う verb"],
    _JLPT: true,
    info: "いちいち - 'One by one', 'each and every (little) thing, いちいち文句を言う - 'to complain about every little thing'.\nうるさい can figuratively mean 'annoying' or 'bothersome'.",
  },
  {
    word: "介護",
    reading: "かいご",
    meaning: "nursing care, caregiving",
    example: "家族みんなで祖母を護している。",
    exampleReading: "かぞくみんなでそぼをかいごしている。",
    exampleMeaning: "The whole family is taking care of our grandmother.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 介護士 [かいごし] caregiver / nurse"], 
  },
  {
    word: "世代",
    reading: "せだい",
    meaning: "generation, era",
    example: "世代が違うと、話が合わないこともある。",
    exampleReading: "せだいがちがうと、はなしがあわないこともある。",
    exampleMeaning: "It's difficult to communicate among different generations.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "継ぐ",
    reading: "つぐ",
    meaning: "to inherit, to succeed",
    example: "来年、父の会社を継ぐことになった。",
    exampleReading: "らいねん、ちちのかいしゃをつぐことになった。",
    exampleMeaning: "Next year, I will inherit my father's company.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 受け継ぐ [うけつぐ] to inherit",],
  },
  {
    word: "妊娠",
    reading: "にんしん",
    meaning: "pregnancy",
    example: "姉は妊娠して、来月出産する。", 
    exampleReading: "あねはにんしんして、らいげつしゅっさんする。",
    exampleMeaning: "My older sister is pregnant and will give birth next month.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 産婦人科 [さんふじんか]", "+ 妊婦 [にんぷ] pregnant woman"],
  },
  {
    word: "出産",
    reading: "しゅっさん",
    meaning: "childbirth",
    example: "実家の近くの病院で出産することにした。", 
    exampleReading: "じっかのちかくのびょういんでしゅっさんすることにした。",
    exampleMeaning: "I decided to give birth at a hospital near my parents' home.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 出産祝い [しゅっさんいわい] baby gift"],
  },
  {
    word: "産む",
    reading: "うむ",
    meaning: "to give birth",
    example: "姉は二十歳のときに長男を産んだ。", 
    exampleReading: "あねははたちのときにながしょをうんだ。",
    exampleMeaning: "My older sister gave birth to her first son when she was twenty.",
    type: ["う verb"],
    _JLPT: true,
    info: "長男 [ちょうなん] means 'first son'",
    extra: ["+ 産まれる [うまれる] to be born"],
  },
  {
    word: "高学歷",
    reading: "こうがくれき",
    meaning: "high academic background, well-educated",
    example: "彼は高学歴で、いい会社に就職した。",
    exampleReading: "かれはこうがくれきで、いいかいしゃにしゅうしょくした。",
    exampleMeaning: "He has a high academic background and got a good job.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高学年",
    reading: "こうがくねん",
    meaning: "upper grades (in school), higher grade",
    example: "高学年になると、勉強が難しくなる。",
    exampleReading: "こうがくねんになると、べんきょうがむずかしくなる。",
    exampleMeaning: "When you reach the upper grades, studying becomes more difficult.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高収入",
    reading: "こうしゅうにゅう", 
    meaning: "high income, high salary",
    example: "彼は高収入の仕事に就いている。",
    exampleReading: "かれはこうしゅうにゅうのしごとについている。",
    exampleMeaning: "He has a job with a high income.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "高性能",
    reading: "こうせいのう",
    meaning: "high performance, high efficiency",
    example: "このパソコンは高性能で、仕事がはかどる。",
    exampleReading: "このパソコンはこうせいのうで、しごとがはかどる。",
    exampleMeaning: "This computer has high performance, making work more efficient.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高気压",
    reading: "こうきあつ",
    meaning: "high pressure (weather)",
    example: "今日は高気圧で、天気がいい。",
    exampleReading: "きょうはこうきあつで、てんきがいい。",
    exampleMeaning: "Today, the weather is good due to high pressure.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高血圧",
    reading: "こうけつあつ",
    meaning: "high blood pressure",
    example: "高血圧は健康に悪い影響を与える。",
    exampleReading: "こうけつあつはけんこうにわるいえいきょうをあたえる。",
    exampleMeaning: "High blood pressure has a negative impact on health.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "仲良し",
    reading: "なかよし", 
    meaning: "close friend, good relationship",
    example: "彼とは小学校からの仲良しだ。",
    exampleReading: "かれとはしょうがっこうからのなかよしだ。",
    exampleMeaning: "He has been my close friend since elementary school.",
    type: ["noun", "な adjective"],
    _JLPT: true,
  },
  {
    word: "縁",
    reading: "えん", 
    meaning: "fate, destiny, connection",
    example: "縁があって、彼女と親友になれた。",
    exampleReading: "えんがあって、かのじょとしんゆうになれた。",
    exampleMeaning: "By fate, I became close friends with her.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ニックネーム",
    reading: "ニックネーム",
    meaning: "nickname",
    example: "彼と私はニックネームで呼び合っている。", 
    exampleReading: "かれとわたしはニックネームでよびあっている。",
    exampleMeaning: "He and I call each other by our nicknames.",
    type: ["noun"],
    _JLPT: true,
    info: "呼び合う [よびあう] to call each other.",
    extra: ["= 愛称 [あいしょう] nickname", "= あだ名 [あだな] nickname"],
  },
  {
    word: "大半",
    reading: "たいはん", 
    meaning: "most of, majority",
    example: "一日の大半の時間を友達と過ごしている。",
    exampleReading: "いちにちのたいはんのじかんをともだちとすごしている。",
    exampleMeaning: "I spend most of my day with my friends.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "恵まれる",
    reading: "めぐまれる",
    meaning: "to be blessed with, to be endowed with",
    example: "私は、いつも友人に恵まれている。", 
    exampleReading: "わたしは、いつもゆうじんにめぐまれている。",
    exampleMeaning: "I am always blessed with friends.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "頼る",
    reading: "たよる",
    meaning: "to depend on, to rely on", 
    example: "私達は親友なのだから、困ったときは頼ってほしい。",
    exampleReading: "わたしたちはしんゆうなのだから、こまったときはたよってほしい。",
    exampleMeaning: "Since we are close friends, I want you to rely on me when you're in trouble.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 頼りにする [たよりにする] to rely on","+ 頼りになる [たよりになる] to be reliable, dependable"],
  },
  {
    word: "頼もしい",
    reading: "たのもしい",
    meaning: "dependable, reliable, trustworthy",
    example: "彼女は何でも相談できる頼もしい存在だ。", 
    exampleReading: "かのじょはなんでもそうだんできるたのもしいそんざいだ。",
    exampleMeaning: "She is a reliable person I can talk to about anything.",
    type: ["い adjective"],
    _JLPT: true,
    info: "相談 [そうだん] means 'consultation' or 'discussion'.\n存在 [そんざい] means 'existence' or 'being'.",
  },
  {
    word: "見習う",
    reading: "みならう",
    meaning: "to follow the example of, to learn from, to emulate",
    example: "私には見習うべき友人が何人かいる。", 
    exampleReading: "わたしにはみならうべきゆうじんがなんにんかいる。",
    exampleMeaning: "I have several friends whom I should emulate.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 見習い [みならい] apprentice, trainee"]
  },
  {
    word: "打ち問ける",
    reading: "うちとける",
    meaning: "to confess, to become friendly, to open one's heart",
    example: "親友だけに秘密を打ち明けた。", 
    exampleReading: "しんゆうだけにひみつをうちあけた。",
    exampleMeaning: "I confided my secret only to my close friend.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "励ます",
    reading: "はげます",
    meaning: "to encourage, to cheer up",
    example: "私が試験に落ちたとき、友達が励ましてくれた。",
    exampleReading: "わたしがしけんにおちたとき、ともだちがはげましてくれた。",
    exampleMeaning: "When I failed the exam, my friend encouraged me.",
    type: ["う verb"],
    _JLPT: true,
    info: "落ちる [おちる] means 'to fail' or 'to fall'.",
  },
  {
    word: "あえて",
    reading: "あえて",
    meaning: "daringly, boldly, intentionally",
    example: "大切な友達だから、あえて厳しい忠告もする。",
    exampleReading: "たいせつなともだちだから、あえてきびしいちゅうこくもする。",
    exampleMeaning: "Because they are a precious friend, I intentionally give them strict advice.",
    type: ["adverb"],
    _JLPT: true, 
    info: "あえて is used to indicate doing something intentionally or boldly, often against the norm or expectations.\n忠告 [ちゅうこく] means 'advice' or 'counsel'.",
  },
  {
    word: "慰める",
    reading: "なぐさめる", 
    meaning: "to comfort, to console",
    example: "友達が悲しんでいるとき、私は慰めるために側にいる。",
    exampleReading: "ともだちがかなしんでいるとき、わたしはなぐさめるためにそばにいる。",
    exampleMeaning: "When my friend is sad, I stay by their side to comfort them.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "察する",
    reading: "さっする", 
    meaning: "to infer, to sense, to guess",
    example: "友達の気持ちを察して、何も言わないことにした。",
    exampleReading: "ともだちのきもちをさっして、なにもいわないことにした。",
    exampleMeaning: "I sensed my friend's feelings and decided not to say anything.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "思いやり",
    reading: "おもいやり",
    meaning: "thoughtfulness, consideration, compassion",
    example: "周りの人への思いやりを大切にしたい。",
    exampleReading: "まわりのひとへのおもいやりをたいせつにしたい。",
    exampleMeaning: "I want to cherish thoughtfulness towards those around me.",
    type: ["noun"],
    _JLPT: true, 
    extra: ["+ 思いやる [おもいやる] to be considerate, to care for"],
  },
  {
    word: "何気ない",
    reading: "なにげない", 
    meaning: "casual",
    example: "友達との何気ない会話が楽しい。",
    exampleReading: "ともだちとのなにげないかいわがたのしい。",
    exampleMeaning: "Casual conversations with friends are enjoyable.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "からかう",
    reading: "からかう",
    meaning: "to tease, to make fun of",
    example: "彼女ができて、友達にからかわれた。",
    exampleReading: "かのじょができて、ともだちにからかわれた。",
    exampleMeaning: "I got a girlfriend and was teased by my friends.",
    type: ["う verb"],
    _JLPT: true,
    info: "からかう can also mean 'to joke around' or 'to playfully tease'.", 
  },
  {
    word: "幹事",
    reading: "かんじ",
    meaning: "organizer, person in charge",
    example: "仲間の飲み会では、いつも私が幹事だ。",
    exampleReading: "なかまののみかいでは、いつもわたしがかんじだ。",
    exampleMeaning: "I am always the organizer for our group drining gatherings.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "呼び出す",
    reading: "よびだす",
    meaning: "to send for, to summon, to call out", 
    example: "夜遅く、親友に「飲みに行こう」と呼びされた。",
    exampleReading: "よるおそく、しんゆうによみにいこうとよびだされた。",
    exampleMeaning: "Late at night, my close friend called me out to go drinking.",
    type: ["う verb"],
    _JLPT: true,
    info: "夜遅く [よるおそく] means 'late at night'.",
  },
  {
    word: "呼び止める",
    reading: "よびとめる",
    meaning: "to call out to stop someone, to stop someone by calling them",
    example: "アパートの前で管理人さんに呼び止められた。",
    exampleReading: "アパートのまえでかんりにんさんによびとめられた。",
    exampleMeaning: "I was stopped by the building manager in front of the apartment.",
    type: ["る verb"],
    _JLPT: true, 
    info: "管理人 [かんりにん] means 'building manager' or 'superintendent', especially of an apartment building, dormitory, or office.",
  },
  {
    word: "盛り上がる",
    reading: "もりあがる",
    meaning: "to get excited, to liven up, to surge", 
    example: "パーティーは盛り上がって、夜中まで続いた。\n地震で道が盛り上がった。",
    exampleReading: "パーティーはもりあがって、よなかまでつづいた。\nじしんでみちがもりあがった。",
    exampleMeaning: "The party got lively and continued until midnight.\nThe road rose up due to the earthquake.",
    type: ["う verb"],
    _JLPT: true,
    info: "1 - become excited 2 - expand and rise (surge)"
  },
  {
    word: "あきれる",
    reading: "あきれる",
    meaning: "to be shocked, to be astounded, to be amazed",
    example: "友達の行動にあきれて、何も言えなかった。",
    exampleReading: "ともだちのこうどうにあきれて、なにもいえなかった。",
    exampleMeaning: "I was so shocked by my friend's behavior that I couldn't say anything.",
    type: ["る verb"],
    _JLPT: true, 
    info: "行動 [こうどう] means 'behavior' or 'action'.",
  },
  {
    word: "ふざける",
    reading: "ふざける",
    meaning: "to joke, to fool around, to mess around",
    example: "友達とふざけていたら、転んで足の骨を折った。",
    exampleReading: "ともだちとふざけていたら、ころんであしのほねをおった。",
    exampleMeaning: "While fooling around with my friends, I fell and broke my leg.",
    type: ["る verb"],
    _JLPT: true,
    info: "転ぶ [ころぶ] means 'to fall down' or 'to tumble'.\n足の骨を折る [あしのほねをおる] means 'to break a leg'.",
  },
  {
    word: "久しい",
    reading: "ひさしい",
    meaning: "long time, long-awaited",
    example: "高校時代のクラスメートと久しく会っていない。",
    exampleReading: "こうこうじだいのクラスメートとひさしくあっていない。",
    exampleMeaning: "I haven't seen my high school classmates in a long time.",
    type: ["い adjective"],
    _JLPT: true,
    extra: ["+ 久しぶり [ひさしぶり] long time no see", "+ 久々 [ひさびさ] long time"], 
  },
  {
    word: "初対面",
    reading: "しょたいめん",
    meaning: "first meeting, first encounter",
    example: "初対面の人と話すのは緊張する。",
    exampleReading: "しょたいめんのひととはなすのはきんちょうする。",
    exampleMeaning: "I get nervous when talking to someone for the first time.",
    type: ["noun"], 
    _JLPT: true,
    info: "緊張 [きんちょう] means 'nervousness' or 'tension'.",
  },
  {
    word: "自己紹介",
    reading: "じこしょうかい",
    meaning: "self-introduction",
    example: "合コンでお互いに自己介をした。",
    exampleReading: "ごうコンでおたがいにじこしょうかいをした。",
    exampleMeaning: "At the group date, we introduced ourselves to each other.",
    type: ["noun", "する verb"],
    _JLPT: true, 
    info: "合コン [ごうコン] is a group date or social gathering.\nお互いに [おたがいに] means 'each other'.",
    extra: ["+ 自己流 [じこりゅう] one's own way, own method"],
  },
  {
    word: "おじぎ",
    reading: "おじぎ",
    meaning: "bow, bowing",
    example: "朝、大家さんに会ったので、おじぎした。",
    exampleReading: "あさ、おおやさんにあったので、おじぎした。",
    exampleMeaning: "I greeted the landlord with a bow when I met him in the morning.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "近所付き合い",
    reading: "きんじょづきあい",
    meaning: "neighborhood relations, interaction with neighbors", 
    example: "できるだけ近所付き合いを大切にしている。",
    exampleReading: "できるだけきんじょづきあいをたいせつにしている。",
    exampleMeaning: "I try to value my interactions with neighbors as much as possible.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ 友達付き合い [ともだちづきあい] interaction with friends"],
  },
  {
    word: "大家",
    reading: "おおや",
    meaning: "landlord, landlady",
    example: "私のアパートの大家さんは、とても親切な人だ。",
    exampleReading: "わたしのアパートのおおやさんは、とてもしんせつなひとだ。",
    exampleMeaning: "The landlord of my apartment is a very kind person.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "飼い主",
    reading: "かいぬし",
    meaning: "pet owner, owner of an animal",
    example: "犬の飼い主同士が公園でおしゃべりをしている。",
    exampleReading: "いぬのかいぬしどうしがこうえんでおしゃべりをしている。",
    exampleMeaning: "The dog's owners are chatting in the park.",
    type: ["noun"],
    _JLPT: true, 
    info: "同士 [どうし] means 'fellow' or 'among'.",
  },
  {
    word: "交わす",
    reading: "かわす",
    meaning: "to exchange, to swap, to trade",
    example: "近所の人達に会うと、笑顔であいさつを交わす。",
    exampleReading: "きんじょのひとたちにあうと、えがおであいさつをかわす。",
    exampleMeaning: "When I meet people in the neighborhood, I exchange greetings with a smile.",
    type: ["う verb"],
    _JLPT: true, 
    info: "近所 [きんじょ] means 'neighborhood' or 'local area'.",
  },
  {
    word: "振り返る",
    reading: "ふりかえる",
    meaning: "to look back, to turn around, to reflect",
    example: "後ろから名前を呼ばれて、振り返った。\n学生時代を振り返ると、なつかしい。",
    exampleReading: "うしろからなまえをよばれて、ふりかえった。\nがくせいじだいをふりかえると、なつかしい。",
    exampleMeaning: "I was called by name from behind and turned around.\nLooking back on my student days, I feel nostalgic.",
    type: ["る verb"],
    _JLPT: true,
    info: "振り返る can mean both 'to look back physically' and 'to reflect on past experiences'.\nなつかしい means 'nostalgic' or 'longing for the past'.\n呼ばれる [よばれる] means 'to be called', its transitive is 呼ぶ [よぶ].",
  },
  {
    word: "再会",
    reading: "さいかい",
    meaning: "reunion, meeting again",
    example: "以前お世話になった人に再会した。",
    exampleReading: "いぜんおせわになったひとにさいかいした。",
    exampleMeaning: "I had a reunion with someone who had helped me before.",
    type: ["noun", "する verb"],
    _JLPT: true, 
  },
  {
    word: "覚え",
    reading: "おぼえ",
    meaning: "recollection, memory, remembrance", 
    example: "田中さんとは会った覚えがない。",
    exampleReading: "たなかさんとはあったおぼえがない。",
    exampleMeaning: "I have no recollection of meeting Mr. Tanaka.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ 記憶 [きおく] memory, recollection"],
  },
  {
    word: "心当たり",
    reading: "こころあたり",
    meaning: "idea, clue, knowledge of, something that comes to mind",
    example: "心当たりのない番号から電話が、かかってきた。",
    exampleReading: "こころあたりのないばんごうからでんわが、かかってきた。",
    exampleMeaning: "I received a call from a number I had no idea about.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "結びつく",
    reading: "むすびつく",
    meaning: "to be connected, to be linked, to be tied together",
    example: "人と人は、いろいろなことで結びついている。",
    exampleReading: "ひととひとは、いろいろなことでむすびついている。",
    exampleMeaning: "People are connected in various ways.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+（～を)結びつける [むすびつける] to connect, to link together",], 
  },
  {
    word: "とっさ[に]",
    reading: "とっさ[に]",
    meaning: "at that moment, in an instant, immediately, in a split second",
    example: "隣の人に会ったとき、とっさに名前が出てこなかった。",
    exampleReading: "となりのひとにあったとき、とっさになまえがでてこなかった。",
    exampleMeaning: "When I met the person next to me, their name didn't come to mind immediately.",
    type: ["adverb"],
    _JLPT: true, 
  },
  {
    word: "てっきり",
    reading: "てっきり",
    meaning: "assumed, I thought for sure", 
    example: "てっきり彼らを兄弟だと思っていた。",
    exampleReading: "てっきりかれらをきょうだいだとおもっていた。",
    exampleMeaning: "I thought for sure they were siblings.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "思い込む",
    reading: "おもいこむ",
    meaning: "to be under the impression, to be convinced",
    example: "私は木村さんが独身だと思い込んでいた。",
    exampleReading: "わたしはきむらさんがどくしんだとおもいこんでいた。",
    exampleMeaning: "I was under the impression that Mr. Kimura was single.",
    type: ["う verb"],
    _JLPT: true, 
    info: "独身 [どくしん] means 'single' or 'unmarried'.",
    extra: ["+ 思い込み [おもいこみ] assumption, belief", "+ 思い込ませる [おもいこませる] to convince someone, to make someone believe", ],
  },
  {
    word: "コミュニケーション",
    reading: "コミュニケーション", 
    meaning: "communication, interaction",
    example: "いろいろな国の人とコミュニケーションを持ちたい。",
    exampleReading: "いろいろなくにのひととコミュニケーションをもちたい。",
    exampleMeaning: "I want to have communication with people from various countries.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ネットワーク",
    reading: "ネットワーク",
    meaning: "network, connection",
    example: "将来のために、知り合いのネットワークを広げたい。",
    exampleReading: "しょうらいのために、しりあいのネットワークをひろげたい。",
    exampleMeaning: "I want to expand my network of acquaintances for the future.",
    type: ["noun"],
    _JLPT: true, 
    info: "知り合い [しりあい] means 'acquaintance' or 'someone you know'.\n広げる [ひろげる] means 'to expand' or 'to spread out'. Its intransivite if 広がる [ひろがる].",
  },
  {
    word: "直接",
    reading: "ちょくせつ",
    meaning: "directly, firsthand",
    example: "彼とは真のを達ではない。",
    exampleReading: "かれとはしんのをたちではない。",
    exampleMeaning: "He is not a close (direct) friend of mine.",
    type: ["adverb", "noun"],
    _JLPT: true, 
    extra: ["⇔ 間接 [かんせつ] indirect"],
  },
  {
    word: "接する",
    reading: "せっする",
    meaning: "to come into contact with, to interact with, adjacent to",
    example: "敬語が下手なので、目上の人と接するのが苦手だ。\n私のアパートは、隣のビルと接している。", 
    exampleReading: "けいごがへたなので、めうえのひととせっするのがにがてだ。\nわたしのアパートは、となりのビルとせっしている。",
    exampleMeaning: "I'm not good at interacting with people of higher status because I'm not good at using honorific language.\nMy apartment is adjacent to the building next door.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "招く",
    reading: "まねく",
    meaning: "to invite, to call, to beckon",
    example: "先日、部長のお宅に招かれた。\n彼の言葉が大きな混乱を招いた。", 
    exampleReading: "せんじつ、ぶちょうのおたくにまねかれた。\nかれのことばがおおきなこんらんをまねいた。",
    exampleMeaning: "The other day, I was invited to the manager's house.\nHis words caused a great deal of confusion.",
    type: ["う verb"],
    _JLPT: true,
    info: "混乱 [こんらん] means 'confusion' or 'disorder'.\n招く can also mean 'to cause' or 'to bring about', as in the second example.",
    extra: ["招かれる [まねかれる] is the passive form meaning 'to be invited'."],
  },
  {
    word: "気配り",
    reading: "きくばり",
    meaning: "consideration for other's feeling, thoughtfulness, attentiveness", 
    example: "アルバイト先の先輩の気配りを見習いたい。",
    exampleReading: "アルバイトさきのせんぱいのきくばりをみならいたい。",
    exampleMeaning: "I want to emulate the consideration for others that my senior co-worker at my part-time job shows.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "込める",
    reading: "こめる",
    meaning: "to put into, to include, to load, infuse",
    example: "感謝の気持ちを込めて、先生へのプレゼントを選んだ。", 
    exampleReading: "かんしゃのきもちをこめて、せんせいへのプレゼントをえらんだ。",
    exampleMeaning: "I chose a gift for my teacher with feelings of gratitude.",
    type: ["る verb"],
    _JLPT: true,
    info: "感謝の気持ち [かんしゃのきもち] means 'feelings of gratitude'.\n込める can also mean 'to include' or 'to load', as in putting effort or emotion into something.",
  },
  {
    word: "同期",
    reading: "どうき",
    meaning: "colleague, peer, same period",
    example: "彼は会社の国期と、とても仲がいい。", 
    exampleReading: "かれはかいしゃのどうきと、とてもなかがいい。",
    exampleMeaning: "He is very close with his colleagues from the same period at the company.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ぐち",
    reading: "ぐち", 
    meaning: "complaint, grumble, gripe",
    example: "毎晩居酒屋で同期とぐちをこぼしている。",
    exampleReading: "まいばんいざかやでどうきとぐちをこぼしている。",
    exampleMeaning: "Every night, I complain to my colleagues at the izakaya.",
    type: ["noun"],
    _JLPT: true,
    info: "こぼす means 'to spill' or 'to complain about'.",
  },
  {
    word: "大いに",
    reading: "おおいに",
    meaning: "very, greatly, very much, a lot", 
    example: "今日は大いに飲んで楽しもう。",
    exampleReading: "きょうはおおいにのんでたのしもう。",
    exampleMeaning: "Let's drink a lot and have fun today.",
    type: ["adverb"],
    _JLPT: true,
    info: "大いに is used to emphasize the extent or degree of something, often used to express enthusiasm or encouragement.",
  },
  {
    word: "低予算",
    reading: "ていよさん", 
    meaning: "low budget",
    example: "低予算で旅行を計画するのは難しい。",
    exampleReading: "ていよさんでりょこうをけいかくするのはむずかしい。",
    exampleMeaning: "Planning a trip on a low budget is difficult.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "低学年",
    reading: "ていがくねん",
    meaning: "lower grade",
    example: "低学年の子供たちは、遊びながら学ぶことが大切だ。",
    exampleReading: "ていがくねんのこどもたちは、あそびながらまなぶことがたいせつだ。",
    exampleMeaning: "For lower grade children, learning through play is important.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "低血圧",
    reading: "ていけつあつ", 
    meaning: "low blood pressure",
    example: "低血圧の人は、朝起きるのが大変だ。",
    exampleReading: "ていけつあつのひとは、あさおきるのがたいへんだ。",
    exampleMeaning: "People with low blood pressure find it difficult to get up in the morning.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "低姿勢",
    reading: "ていしせい",
    meaning: "humble attitude, low posture",
    example: "彼はいつも低姿勢で、周りの人に優しく接する。",
    exampleReading: "かれはいつもていしせいで、まわりのひとにやさしくせっする。",
    exampleMeaning: "He always has a humble attitude and treats those around him kindly.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "低次元",
    reading: "ていじげん",
    meaning: "low dimension, low level, trivial matter",
    example: "その議論は低次元で、もっと深い話をしたい。",
    exampleReading: "そのぎろんはていじげんで、もっとふかいはなしをしたい。",
    exampleMeaning: "That discussion is at a low level, and I want to have a deeper conversation.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "低レベル",
    reading: "ていレベル", 
    meaning: "low level, low standard",
    example: "このゲームは低レベルで、子供向けだ。",
    exampleReading: "このゲームはていレベルで、こどもむけだ。",
    exampleMeaning: "This game is at a low level and is intended for children.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "カップル",
    reading: "カップル",
    meaning: "couple, pair",
    example: "彼らは似合いのカップルだ。",
    exampleReading: "かれらはにあいのカップルだ。",
    exampleMeaning: "They are a perfect couple.",
    type: ["noun"],
    _JLPT: true, 
    info: "似合い [にあい] means 'suitable' or 'well-matched'.",
    extra: ["+ ペア pair, couple", "+ カップルズ couples (plural)"],
  },
  {
    word: "愛",
    reading: "あい", 
    meaning: "love, affection",
    example: "愛を込めて、彼女にメッセージを送る。",
    exampleReading: "あいをこめて、かのじょにメッセージをおくる。",
    exampleMeaning: "I send a message to her with love.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "同士",
    reading: "どうし",
    meaning: "each other, fellow, companion, among",
    example: "恋人回上が見つめ合う。", 
    exampleReading: "こいびとかいじょうがみつめあう。",
    exampleMeaning: "Lovers gaze at each other.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ 友達同士 [ともだちどうし] friends", "+ 他人同士 [たにんどうし] strangers"],
  },
  {
    word: "[お］互い［に］",
    reading: "おたがい［に］",
    meaning: "each other, mutually, one another",
    example: "二人はお互いの性格が気に入った。\n私達は会ったときから、お互いに好きだった。", 
    exampleReading: "ふたりはおたがいのせいかくがきにいった。\nわたしたちはあったときから、おたがいにすきだった。",
    exampleMeaning: "The two liked each other's personalities.\nWe liked each other from the moment we met.",
    type: ["adverb"],
    _JLPT: true,
    info: "性格 [せいかく] means 'personality' or 'character'.\n気に入る [きにいる] means 'to like' or 'to be pleased with'.",
  },
  {
    word: "つり合う",
    reading: "つりあう",
    meaning: "to balance, to be well-matched, to suit each other",
    example: "僕が彼女とつり合っているかどうか心配だ。",
    exampleReading: "ぼくがかのじょとつりあっているかどうかしんぱいだ。",
    exampleMeaning: "I'm worried about whether I match her well or not.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "むしろ",
    reading: "むしろ", 
    meaning: "rather, instead, on the contrary",
    example: "完ぺきな人より、むしろ欠点のある人の方が好きだ。",
    exampleReading: "かんぺきなひとより、むしろけってんのあるひとのほうがすきだ。",
    exampleMeaning: "I prefer people with flaws rather than perfect ones.",
    type: ["adverb"],
    _JLPT: true,
    info: "完ぺきな [かんぺきな] means 'perfect'.\n欠点 [けってん] means 'flaw' or 'weakness'.",
  },
  {
    word: "言わば",
    reading: "いわば",
    meaning: "so to speak, in a way, as it were",
    example: "彼女は僕にとって、言わば太陽のような人だ。", 
    exampleReading: "かのじょはぼくにとって、いわばたいようのようなひとだ。",
    exampleMeaning: "She is, so to speak, like the sun to me.",
    type: ["adverb"],
    _JLPT: true,
    info: "言わば is used to introduce a metaphor or analogy, often to clarify a point or to express something in a different way.\n太陽 [たいよう] means 'sun'.",
  },
  {
    word: "視線",
    reading: "しせん",
    meaning: "line of sight, gaze, glance",
    example: "二人は、しばらく視線を合わせなかった。", 
    exampleReading: "ふたりは、しばらくしせんをあわせなかった。",
    exampleMeaning: "The two refused to look at each other for a while.",
    type: ["noun"],
    _JLPT: true,
    info: "しばらく means 'for a while' or 'for some time'.\n合わせる [あわせる] means 'to match' or 'to combine', in this context it means 'to look at each other'.",
  },
  {
    word: "見つめる",
    reading: "みつめる",
    meaning: "to stare at, to gaze at, to look intently", 
    example: "彼は彼女をじっと見つめていた。",
    exampleReading: "かれはかのじょをじっとみつめていた。",
    exampleMeaning: "He was staring intently at her.",
    type: ["る verb"],
    _JLPT: true,
    info: "じっと means 'steadily' or 'intently'.",
    extra: ["+ 見つめ合う [みつめあう] to stare at each other, to look into each other's eyes"],
  },
  {
    word: "そらす",
    reading: "そらす", 
    meaning: "to look away",
    example: "彼女に気づかれて、目をそらした。",
    exampleReading: "かのじょにきづかれて、めをそらした。",
    exampleMeaning: "I looked away when she noticed me.",
    type: ["う verb"],
    _JLPT: true,
    info: "気づく [きづく] means 'to notice' or 'to become aware of'.",
  },
  {
    word: "ちらっと",
    reading: "ちらっと",
    meaning: "peek, glance, glimpse", 
    example: "彼女はちらっと僕を見たが、すぐに目をそらした。",
    exampleReading: "かのじょはちらっとぼくをみたが、すぐにめをそらした。",
    exampleMeaning: "She glanced at me briefly but quickly looked away.",
    type: ["adverb"],
    _JLPT: true,
    extra: ["= ちらりと"],
  },
  {
    word: "もしかすると",
    reading: "もしかすると",
    meaning: "perhaps, maybe, possibly",
    example: "もしかすると、彼は僕のことが好きなのかもしれない。",
    exampleReading: "もしかすると、かれはぼくのことがすきなのかもしれない。",
    exampleMeaning: "Perhaps he might like me.",
    type: ["adverb"],
    _JLPT: true, 
    extra: ["= もしかしたら", "= もしかして", "= ひょっとすると"],
  },
  {
    word: "探る",
    reading: "さぐる", 
    meaning: "to search, to probe, to investigate",
    example: "友達に頼んで、彼女の気持ちを探ってもらった。\nポケットを探ったら、500円玉が出てきた。",
    exampleReading: "ともだちにたのんで、かのじょのきもちをさぐってもらった。\nポケットをさぐったら、500えんだまがでてきた。",
    exampleMeaning: "I asked my friend to ask whether she liked me or not.\nWhen I searched my pocket, I found a 500 yen coin.",
    type: ["う verb"],
    _JLPT: true,
    info: "Check out without having others notice / Search for something one cannot see",
  },
  {
    word: "示す",
    reading: "しめす", 
    meaning: "to show, to indicate, to point out",
    example: "彼は彼女に自分の気持ちを示せない。\n例を示して、文法を説明する。",
    exampleReading: "かれはかのじょにじぶんのきもちをしめせない。\nれいをしめして、ぶんぽうをせつめいする。",
    exampleMeaning: "He can't show his feelings to her.\nI explain the grammar by showing an example.",
    type: ["う verb"],
    _JLPT: true,
    info: "示す can mean 'to express' or 'to show' in a more abstract sense, such as feelings or intentions."
  },
  {
    word: "口実",
    reading: "こうじつ",
    meaning: "excuse, pretext, justification",
    example: "試験勉強を口実にして、彼女と図書館で会った。", 
    exampleReading: "しけんべんきょうをこうじつにして、かのじょととしょかんであった。",
    exampleMeaning: "I used studying for an exam as an excuse to meet her at the library.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "うつむく",
    reading: "うつむく", 
    meaning: "to look down, to lower one's head",
    example: "彼女は恥ずかしそうにうつむいた。",
    exampleReading: "かのじょははずかしそうにうつむいた。",
    exampleMeaning: "She looked down shyly.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "こそこそ",
    reading: "こそこそ", 
    meaning: "sneakily, secretly, stealthily",
    example: "親に内緒にして、こそこそ付き合うのは嫌だ。",
    exampleReading: "おやにないしょにして、こそこそつきあうのはいやだ。",
    exampleMeaning: "I don't want to keep our relationship a secret from our parents.",
    type: ["adverb"],
    _JLPT: true,
    info: "内緒 [ないしょ] Secret",
    extra: ["+ こっそり [と] Secretly"],
  },
  {
    word: "ささやく",
    reading: "ささやく", 
    meaning: "to whisper, to murmur, to speak softly",
    example: "彼は、やさしい声で「愛してる」とささやいた。",
    exampleReading: "かれは、やさしいこえで「あいしてる」とささやいた。",
    exampleMeaning: "He whispered 'I love you' in a gentle voice.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ つぶやく [つぶやく] to mutter, to murmur",],
  },
  {
    word: "禁物",
    reading: "きんもつ", 
    meaning: "taboo, something to avoid, something forbidden",
    example: "私達の間で、うそは禁物だ。",
    exampleReading: "わたしたちのあいだで、うそはきんもつだ。",
    exampleMeaning: "There should be no lies between us.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ 禁句 [きんく] taboo word, forbidden phrase"],
  },
  {
    word: "許す",
    reading: "ゆるす",
    meaning: "to forgive, to allow, to permit",
    example: "彼にうそをついたことを謝って、許してもらった。",
    exampleReading: "かれにうそをついたことをあやまって、ゆるしてもらった。",
    exampleMeaning: "I apologized for lying to him and he forgave me.",
    type: ["う verb"],
    _JLPT: true, 
  },
  {
    word: "合コン",
    reading: "ごうコン",
    meaning: "group date, social gathering for singles",
    example: "二人は合コンで知り合ったそうだ。",
    exampleReading: "ふたりはごうコンでしりあったそうだ。",
    exampleMeaning: "I heard that they met at a group date.",
    type: ["noun"],
    _JLPT: true, 
    extra: ["+ コンパ Party"],
  },
  {
    word: "アプローチ",
    reading: "アプローチ", 
    meaning: "approach",
    example: "先にアプローチしたのは彼だった。",
    exampleReading: "さきにアプローチしたのはかれだった。",
    exampleMeaning: "He was the one who approached first.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "運命",
    reading: "うんめい",
    meaning: "fate, destiny",
    example: "彼女こそ、僕の運金の人だ。", 
    exampleReading: "かのじょこそ、ぼくのうんめいのひとだ。",
    exampleMeaning: "She is the one destined for me (My soulmate).",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "決意",
    reading: "けつい",
    meaning: "determination, resolution, decision",
    example: "ついに彼女との結婚を決意した。", 
    exampleReading: "ついにかのじょとのけっこんをけついした。",
    exampleMeaning: "I finally made the decision to marry her.",
    type: ["noun", "する verb"],
    _JLPT: true,
    info: "ついに means 'finally' or 'at last'.",
  },
  {
    word: "プロポーズ",
    reading: "プロポーズ",
    meaning: "proposal, to propose marriage",
    example: "指輪を贈って、彼女にプロポーズした。", 
    exampleReading: "ゆびわをおくって、かのじょにプロポーズした。",
    exampleMeaning: "I proposed to her with a ring.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "誓う",
    reading: "ちかう",
    meaning: "to swear, to vow, to promise", 
    example: "二人は永遠の愛を誓った。",
    exampleReading: "ふたりはえいえんのあいをちかった。",
    exampleMeaning: "The two vowed eternal love.",
    type: ["う verb"],
    _JLPT: true,
    info: "永遠 [えいえん] means 'eternal' or 'forever'.\n永遠の愛 [えいえんのあい] means 'eternal love'.",
  },
  {
    word: "花嫁",
    reading: "はなよめ",
    meaning: "bride",
    example: "彼女の花嫁姿は、きっと美しいだろう。", 
    exampleReading: "かのじょのはなよめすがたは、きっとうつくしいだろう。",
    exampleMeaning: "Her bride appearance will surely be beautiful.",
    type: ["noun"],
    _JLPT: true,
    info: "花嫁姿 [はなよめすがた] means 'bride appearance'.\n美しい [うつくしい] means 'beautiful'.",
    extra: ["+ 花婿 [はなむこ] groom"],
  },
  {
    word: "好印象",
    reading: "こういんしょう",
    meaning: "good impression, favorable impression",
    example: "初対面で好印象を与えることが大切だ。",
    exampleReading: "しょたいめんでこういんしょうをあたえることがたいせつだ。",
    exampleMeaning: "It's important to make a good impression on first meeting.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "好条件",
    reading: "こうじょうけん",
    meaning: "favorable conditions, good terms",
    example: "この仕事は好条件で、応募者が多い。",
    exampleReading: "このしごとはこうじょうけんで、おうぼしゃがおおい。",
    exampleMeaning: "This job has favorable conditions, and there are many applicants.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "好成績",
    reading: "こうせいせき",
    meaning: "good results, good performance",
    example: "彼は試験で好成績を収めた。",
    exampleReading: "かれはしけんでこうせいせきをおさめた。",
    exampleMeaning: "He achieved good results in the exam.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "好景気",
    reading: "こうけいき",
    meaning: "economic boom, good economic conditions",
    example: "好景気の影響で、企業の業績が上がった。",
    exampleReading: "こうけいきのえいきょうで、きぎょうのぎょうせきがあがった。",
    exampleMeaning: "Due to the economic boom, the company's performance improved.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "好人物",
    reading: "こうじんぶつ",
    meaning: "good person, nice person",
    example: "彼は本当に好人物で、誰からも信頼されている。",
    exampleReading: "かれはほんとうにこうじんぶつで、だれからもしんらいされている。",
    exampleMeaning: "He is truly a good person and is trusted by everyone.",
    type: ["noun"], 
    _JLPT: true, 
  },
  {
    word: "好都合",
    reading: "こうつごう",
    meaning: "convenient, favorable, suitable",
    example: "この時間は、私にとって好都合だ。",
    exampleReading: "このじかんは、わたしにとってこうつごうだ。",
    exampleMeaning: "This time is convenient for me.",
    type: ["noun", "な adjective"],
    _JLPT: true, 
  },
  {
    word: "悪条件",
    reading: "あくじょうけん",
    meaning: "unfavorable conditions, bad terms",
    example: "この契約は悪条件で、再検討が必要だ。",
    exampleReading: "このけいやくはあくじょうけんで、さいけんとうがひつようだ。",
    exampleMeaning: "This contract has unfavorable conditions and needs to be reconsidered.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "悪趣味",
    reading: "あくしゅみ",
    meaning: "bad taste, poor taste",
    example: "彼の服装は悪趣味で、あまり好きではない。",
    exampleReading: "かれのふくそうはあくしゅみで、あまりすきではない。",
    exampleMeaning: "I don't like his fashion sense; it has bad taste.",
    type: ["noun", "な adjective"],
    _JLPT: true, 
  },
  {
    word: "悪影響",
    reading: "あくえいきょう",
    meaning: "bad influence, negative impact",
    example: "この薬は体に悪影響を与える可能性がある。",
    exampleReading: "このくすりはからだにあくえいきょうをあたえるかのうせいがある。",
    exampleMeaning: "This medicine may have a bad influence on the body.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "悪天候",
    reading: "あくてんこう",
    meaning: "bad weather, inclement weather",
    example: "悪天候のため、試合は中止になった。",
    exampleReading: "あくてんこうのため、しあいはちゅうしになった。",
    exampleMeaning: "The match was canceled due to bad weather.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "悪習慣",
    reading: "あくしゅうかん",
    meaning: "bad habit, unhealthy habit",
    example: "悪習慣を改善するために、毎日運動を始めた。",
    exampleReading: "あくしゅうかんをかいぜんするために、まいにちうんどうをはじめた。",
    exampleMeaning: "I started exercising every day to improve my bad habits.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "悪循環",
    reading: "あくじゅんかん",
    meaning: "vicious cycle, negative cycle",
    example: "ストレスが悪循環を引き起こすことがある。",
    exampleReading: "ストレスがあくじゅんかんをひきおこすことがある。",
    exampleMeaning: "Stress can sometimes trigger a vicious cycle.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "悪知恵",
    reading: "わるぢえ",
    meaning: "crafty idea, cunning, bad wisdom",
    example: "彼は悪知恵を使って、問題を解決した。",
    exampleReading: "かれはわるぢえをつかって、もんだいをかいけつした。",
    exampleMeaning: "He used his cunning to solve the problem.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "悪酔い",
    reading: "わるよい",
    meaning: "hangover, feeling sick from drinking",
    example: "昨日の飲みすぎで、悪酔いしてしまった。",
    exampleReading: "きのうのみすぎで、わるよいしてしまった。",
    exampleMeaning: "I got a hangover from drinking too much yesterday.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "悪ふざけ",
    reading: "わるふざけ",
    meaning: "prank, bad joke, mischief",
    example: "彼の悪ふざけが、みんなを困らせた。",
    exampleReading: "かれのわるふざけが、みんなをこまらせた。",
    exampleMeaning: "His bad joke caused trouble for everyone.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "些細な",
    reading: "ささいな",
    meaning: "petty, insignificant, trivial, minor",
    example: "些細なことで喧嘩をしてしまった。",
    exampleReading: "ささいなことでけんかをしてしまった。",
    exampleMeaning: "We ended up fighting over a trivial matter.",
    type: ["な adjective"],
    _JLPT: true, 
  },
  {
    word: "避ける",
    reading: "さける",
    meaning: "to avoid, to evade, to escape",
    example: "私は彼のようなタイプが苦手で、つい避けてしまう。",
    exampleReading: "わたしはかれのようなタイプがにがてで、ついさけてしまう。",
    exampleMeaning: "I'm not good with people like him, so I tend to avoid them.",
    type: ["る verb"],
    _JLPT: true, 
    info: "つい means 'unintentionally', 'without meaning to' or 'just naturally'.",
  },
  {
    word: "誤解",
    reading: "ごかい",
    meaning: "miscommunication, misunderstanding, misconception",
    example: "小さなことが彼女の誤解を招いてしまった。",
    exampleReading: "ちいさなことがかのじょのごかいをまねいてしまった。",
    exampleMeaning: "A small thing led to her misunderstanding.",
    type: ["noun", "する verb"],
    _JLPT: true,
    info: "招く [まねく] means 'to cause' or 'to bring about'.",
  },
  {
    word: "勘違い",
    reading: "かんちがい", 
    meaning: "misunderstanding, misconception, misinterpretation",
    example: "私の勘違いで、親友と喧嘩になった。",
    exampleReading: "わたしのかんちがいで、しんゆうとけんかになった。",
    exampleMeaning: "I had a misunderstanding and ended up fighting with my best friend.",
    type: ["noun", "する verb"],
    _JLPT: true,
    info: "喧嘩 [けんか] means 'fight' or 'quarrel'.",
  },
  {
    word: "言い訳",
    reading: "いいわけ",
    meaning: "excuse, justification, pretext",
    example: "彼はいつも言い訳ばかりして、責任を取らない。",
    exampleReading: "かれはいつもいいわけばかりして、せきにんをとらない。",
    exampleMeaning: "He always makes excuses and doesn't take responsibility.",
    type: ["noun", "する verb"],
    _JLPT: true, 
    info: "責任 [せきにん] means 'responsibility'.\n言い訳ばかりする means 'to make excuses all the time'.",
  },
  {
    word: "きっぱり[と]",
    reading: "きっぱり[と]",
    meaning: "firmly, decisively, clearly",
    example: "彼に食事に誘われたが、きっぱり断った。",
    exampleReading: "かれにしょくじにさそわれたが、きっぱりことわった。",
    exampleMeaning: "I was invited to dinner by him, but I firmly declined.",
    type: ["adverb"],
    _JLPT: true, 
    info: "きっぱり is used to emphasize the firmness or decisiveness of the action.\n断る [ことわる] means 'to decline' or 'to refuse'.",
  },
  {
    word: "ばかにする",
    reading: "ばかにする", 
    meaning: "to make fun of, to mock, to belittle",
    example: "彼は私の意見をばかにして、全く聞いてくれなかった。",
    exampleReading: "かれはわたしのいけんをばかにして、まったくきいてくれなかった。",
    exampleMeaning: "He made fun of my opinion and didn't listen to me at all.",
    type: ["る verb"],
    _JLPT: true,
    info: "全く [まったく] means 'not at all' or 'completely'.",
  },
  {
    word: "嫌味",
    reading: "いやみ",
    meaning: "sarcastic, snide, unpleasant",
    example: "彼の言い方は嫌味に聞こえる。",
    exampleReading: "かれのいいかたはいやみにきこえる。",
    exampleMeaning: "The way he speaks sounds sarcastic.",
    type: ["noun", "な adjective"],
    _JLPT: true, 
  },
  {
    word: "責める",
    reading: "せめる",
    meaning: "to accuse, to blame, to criticize",
    example: "一方的に人を責めるのはよくない",
    exampleReading: "いっぽうてきにひとをせめるのはよくない。",
    exampleMeaning: "It's not good to blame someone unilaterally.",
    type: ["る verb"],
    _JLPT: true,
    info: "一方的に [いっぽうてきに] means 'unilaterally' or 'one-sidedly'.",
  },
  {
    word: "貶す",
    reading: "けなす",
    meaning: "to belittle, to disparage, to criticize",
    example: "彼はいつも人を貶して、自分を大きく見せようとする。",
    exampleReading: "かれはいつもひとをけなして、じぶんをおおきくみせようとする。",
    exampleMeaning: "He always disparages others to make himself look better.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "黙る",
    reading: "だまる",
    meaning: "to be silent, to shut up, to stop talking",
    example: "彼女が怒っているときは、黙るしかない。",
    exampleReading: "かのじょがおこっているときは、だまるしかない。",
    exampleMeaning: "When she is angry, all you can do is stay quiet.",
    type: ["う verb"],
    _JLPT: true,
    info: "怒る [おこる] means 'to get angry'.",
  },
  {
    word: "睨む",
    reading: "にらむ",
    meaning: "to glare, to scowl, to glare at",
    example: "彼女は怖い顔で、じっと彼をにらんだ。",
    exampleReading: "かのじょはこわいかおで、じっとかれをにらんだ。",
    exampleMeaning: "She glared at him with a scary face.",
    type: ["う verb"],
    _JLPT: true,
    info: "じっと means 'steadily' or 'intently'.",
  },
  {
    word: "裏切る",
    reading: "うらぎる",
    meaning: "to betray, to double-cross, to be disloyal",
    example: "信じていた人に裏切られてしまった。",
    exampleReading: "しんじていたひとにうらぎられてしまった。",
    exampleMeaning: "I was betrayed by someone I trusted.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "騙す",
    reading: "だます",
    meaning: "to trick, to deceive, to cheat",
    example: "知り合いに騙されて、お金を貸してしまった。",
    exampleReading: "しりあいにだまされて、おかねをかしてしまった。",
    exampleMeaning: "I was tricked by an acquaintance and ended up lending money.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "せい",
    reading: "せい",
    meaning: "blame, fault, responsibility",
    example: "うそをついたせいで、彼とけんかになった。",
    exampleReading: "うそをついたせいで、かれとけんかになった。",
    exampleMeaning: "Because I lied, I ended up fighting with him.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ お陰 [おかげ] thanks to, due to"],
  },
  {
    word: "行為",
    reading: "こうい",
    meaning: "act, action, behavior",
    example: "彼女の行為が、どうしても許せない。",
    exampleReading: "かのじょのこういが、どうしてもゆるせない。",
    exampleMeaning: "I just can't forgive her actions.",
    type: ["noun"],
    _JLPT: true,
    info: "許せない [ゆるせない] means 'cannot forgive'. It's the potential form of the verb 許す [ゆるす] 'to forgive'.",
    extra: ["+ 迷惑行為 [めいわくこうい] nuisance behavior, disruptive behavior"],
  },
  {
    word: "口論",
    reading: "こうろん",
    meaning: "argument, quarrel, dispute",
    example: "こんなことで友達と口論したくない。",
    exampleReading: "こんなことでともだちとこうろんしたくない。",
    exampleMeaning: "I don't want to argue with my friend over something like this.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["= 口げんか [くちげんか] verbal fight, argument"],
  },
  {
    word: "怒鳴る",
    reading: "どなる",
    meaning: "to yell, to shout, to scream",
    example: "父が大声で怒鳴るのを初めて聞いた。",
    exampleReading: "ちちがおおごえでどなるのをはじめてきいた。",
    exampleMeaning: "I heard my father yell for the first time.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "殴る",
    reading: "なぐる",
    meaning: "to hit, to punch, to strike",
    example: "友達に殴られて、大けがをした",
    exampleReading: "ともだちになぐられて、おおけがをした。",
    exampleMeaning: "I was punched by a friend and got seriously injured.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "貸し借り",
    reading: "かしかり",
    meaning: "borrowing and lending, debts",
    example: "友達との貸し借りは、できるだけ避けたい。",
    exampleReading: "ともだちとのかしかりは、できるだけさけたい。",
    exampleMeaning: "I want to avoid borrowing and lending with friends as much as possible.",
    type: ["noun", "する verb"],
    _JLPT: true,
    info: "避ける [さける] means 'to avoid'.",
  },
  {
    word: "ばらす",
    reading: "ばらす",
    meaning: "to reveal (the truth), to disclose, to disassemble",
    example: "人の秘密をばらすなんて、彼は最低だ。\n引っ越しで、ベッドをばらして運んだ。",
    exampleReading: "ひとのひみつをばらすなんて、かれはさいていだ。\nひっこしで、ベッドをばらしてはこんだ。",
    exampleMeaning: "He's horrible. He revealed people's secrets.\nI disassembled the bed for the move.",
    type: ["う verb"],
    _JLPT: true,
    info: "最低 [さいてい] means 'the worst' or 'the lowest'.\nなんて is used to express disdain or contempt, similar to 'how dare' or 'how could'.",
  },
  {
    word: "気まずい",
    reading: "きまずい",
    meaning: "awkward, uncomfortable, strained",
    example: "彼と気まずい関係になってしまった。",
    exampleReading: "かれときまずいかんけいになってしまった。",
    exampleMeaning: "I ended up in an awkward relationship with him.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "今さら",
    reading: "いまさら",
    meaning: "now that, at this late hour, now that it's too late",
    example: "今さら彼に謝られても、すぐには許せない。",
    exampleReading: "いまさらかれにあやまられても、すぐにはゆるせない。",
    exampleMeaning: "Even if he apologizes now, I can't forgive him right away.",
    type: ["adverb"],
    _JLPT: true,
    info: "今さら is used to express that something is too late to change or that an action is pointless at this stage.\n謝る [あやまる] means 'to apologize'.",
  },
  {
    word: "台無し",
    reading: "だいなし",
    meaning: "totally ruined, spoiled, wasted",
    example: "けんかをして、親友との友情を白無しにしてしまった。",
    exampleReading: "けんかをして、しんゆうとのゆうじょうをだいなしにしてしまった。",
    exampleMeaning: "I ruined my friendship with my best friend over a fight.",
    type: ["noun", "な adjective"],
    _JLPT: true,
  },
  {
    word: "うらむ",
    reading: "うらむ",
    meaning: "to blame, to resent",
    example: "彼女に裏切られたが、うらむ気にはなれない。",
    exampleReading: "かのじょにうらぎられたが、うらむきにはなれない。",
    exampleMeaning: "I was betrayed by her, but I don't feel like blaming her.",
    type: ["う verb"],
    _JLPT: true,
    info: "裏切る [うらぎる] means 'to betray'.",
    extra: ["+ 恨み [うらみ] blame"],
  },
  {
    word: "追い出す",
    reading: "おいだす",
    meaning: "to drive someone out, to expel, to kick out",
    example: "釜とけんかして、家を追い出された。",
    exampleReading: "かまとけんかして、いえをおいだされた。",
    exampleMeaning: "I had a fight with my parents and was kicked out of the house.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "仲間外れ",
    reading: "なかまはずれ",
    meaning: "leaving someone out, being excluded from a group",
    example: "彼はいつも仲間外れにされて、寂しそうだった。",
    exampleReading: "かれはいつもなかまはずれにされて、さびしそうだった。",
    exampleMeaning: "He always looked lonely because he was excluded from the group.",
    type: ["noun"],
    _JLPT: true,
    info: "仲間 [なかま] means 'companion' or 'group'.\n外れ [はずれ] means 'to be left out' or 'excluded'.",
  },
  {
    word: "あいつ",
    reading: "あいつ",
    meaning: "him/her, that guy (that I don't like), that person (informal, can be derogatory)",
    example: "あいつとは、もう二度と会いたくない。",
    exampleReading: "あいつとは、もうにどとあいたくない。",
    exampleMeaning: "I never want to see him again.",
    type: ["noun"],
    _JLPT: true,
    info: "あいつ is a casual and sometimes derogatory way to refer to someone, often used when the speaker has negative feelings towards that person.",
    extra: ["+ やつ person (informal, can be derogatory)"],
  },
  {
    word: "他人",
    reading: "たにん",
    meaning: "stranger, other people, outsiders",
    example: "兄はけんかすると、他人のような態度になる。",
    exampleReading: "あにはけんかすると、たにんのようなたいどになる。",
    exampleMeaning: "My brother acts like a stranger when we fight.",
    type: ["noun"],
    _JLPT: true,
    info: "態度 [たいど] means 'attitude'.",
  },
  {
    word: "名案",
    reading: "めいあん",
    meaning: "good idea, brilliant plan",
    example: "彼の名案で、問題が解決した。",
    exampleReading: "かれのめいあんで、もんだいがかいけつした。",
    exampleMeaning: "The problem was solved thanks to his brilliant idea.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名作",
    reading: "めいさく",
    meaning: "masterpiece, great work",
    example: "この映画は名作として、長い間愛されている。",
    exampleReading: "このえいがはめいさくとして、ながいあいあいされている。",
    exampleMeaning: "This movie is loved for a long time as a masterpiece.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名画",
    reading: "めいが",
    meaning: "famous painting, masterpiece painting",
    example: "この美術館には、数多くの名画が展示されている。",
    exampleReading: "このびじゅつかんには、かずおおくのめいががてんじされている。",
    exampleMeaning: "This art museum displays many famous paintings.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名曲",
    reading: "めいきょく",
    meaning: "famous song, masterpiece music",
    example: "この曲は名曲として、世代を超えて愛されている。",
    exampleReading: "このきょくはめいきょくとして、せだいをこえてあいされている。",
    exampleMeaning: "This song is loved across generations as a masterpiece.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名所",
    reading: "めいしょ",
    meaning: "famous place, tourist attraction, place of interest",
    example: "この町には多くの名所があり、観光客に人気だ。",
    exampleReading: "このまちにはおおくのめいしょがあり、かんこうきゃくににんきだ。",
    exampleMeaning: "This town has many famous places and is popular with tourists.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名人",
    reading: "めいじん",
    meaning: "master, expert, virtuoso",
    example: "彼は将棋の名人で、数々の大会で優勝している。",
    exampleReading: "かれはしょうぎのめいじんで、かずかずのたいかいでゆうしょうしている。",
    exampleMeaning: "He is a master of shogi and has won many tournaments.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名産",
    reading: "めいさん",
    meaning: "local specialty, famous product",
    example: "この地域の名産は、新鮮な魚と野菜だ。",
    exampleReading: "このちいきのめいさんは、しんせんなさかなとやさいだ。",
    exampleMeaning: "The local specialties of this area are fresh fish and vegetables.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名医",
    reading: "めいい",
    meaning: "famous doctor, renowned physician",
    example: "この病院には名医が多く、患者から信頼されている。",
    exampleReading: "このびょういんにはめいいがおおく、かんじゃからしんらいされている。",
    exampleMeaning: "This hospital has many renowned doctors and is trusted by patients.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名文",
    reading: "めいぶん",
    meaning: "famous writing, masterpiece of literature",
    example: "この小説は名文として、文学界で高く評価されている。",
    exampleReading: "このしょうせつはめいぶんとして、ぶんがくかいでたかくひょうかされている。",
    exampleMeaning: "This novel is highly regarded in the literary world as a masterpiece of writing.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名著",
    reading: "めいちょ",
    meaning: "famous book, classic work",
    example: "この本は名著として、長い間読み継がれている。",
    exampleReading: "このほんはめいちょとして、ながいあいだれよみつがれている。",
    exampleMeaning: "This book has been read for a long time as a classic work.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名声",
    reading: "めいせい",
    meaning: "fame, reputation, renown",
    example: "彼は名声を得るために、努力を惜しまない。",
    exampleReading: "かれはめいせいをえるために、どりょりをおしまない。",
    exampleMeaning: "He spares no effort to gain fame.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名場面",
    reading: "めいばめん",
    meaning: "famous scene, memorable moment",
    example: "この映画の名場面は、何度見ても感動する。",
    exampleReading: "このえいがのめいばめんは、なんどみてもかんどうする。",
    exampleMeaning: "The famous scenes in this movie are moving no matter how many times I watch them.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "名女優",
    reading: "めいじょゆう",
    meaning: "famous actress, renowned actress",
    example: "彼女は名女優として、数々の映画で活躍している。",
    exampleReading: "かのじょはめいじょゆうとして、かずかずのえいがでかつやくしている。",
    exampleMeaning: "She is active in many movies as a renowned actress.",
    type: ["noun"],
    _JLPT: true,
  },
  
];