export const VOCABS_N2: TVocabJLPT[] = [
  {
    word: "一家",
    reading: "いっか", 
    meaning: "a family, a household",
    example: "一家の大黒柱",
    exampleReading: "いっかのだいこくばしら",
    exampleMeaning: "the head of a family",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ ファミリー  ", "= 一家団欒 [いっかだんらん] family gathering"],
  },
  {
    word: "存在",
    reading: "そんざい",
    meaning: "existence, being",
    example: "家族は本当にありがたい存在だ。",
    exampleReading: "かぞくはほんとうにありがたいそんざいだ。",
    exampleMeaning: "Family is truly a precious existence.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "向き合う",
    reading: "むきあう",
    meaning: "to face each other, to confront",
    example: "家族みんなで問題に向き合っている。", 
    exampleReading: "かぞくみんなでもんだいにむきあっている。",
    exampleMeaning: "The whole family is facing the problem together.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "つくづく",
    reading: "つくづく",
    meaning: "deeply, greatly, thoroughly",
    example: "最近、家族のありがたさをつくづくと感じる。", 
    exampleReading: "さいきん、かぞくのありがたさをつくづくとかんじる。",
    exampleMeaning: "Recently, I feel deeply grateful for my family.",
    type: ["adverb"],
    _JLPT: true,
    info: "Used to express a deep or thorough feeling about something. Particle と is often used with it.",
    extra: ["+ しみじみ deeply", ""],
  },
  {
    word: "養う",
    reading: "やしなう",
    meaning: "To rpovide for, to support", 
    example: "父は一生懸命に働いて、家族を養っている。",
    exampleReading: "ちちはいっしょうけんめいにはたらいて、かぞくをやしなっている。",
    exampleMeaning: "My father works hard to support(provide for) the family.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "役目",
    reading: "やくめ",
    meaning: "role, duty, responsibility",
    example: "子どもを育てることが親の役目だ。",
    exampleReading: "こどもをそだてることがおやのやくめだ。",
    exampleMeaning: "Raising children is the parent's responsibility.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "甘える",
    reading: "あまえる",
    meaning: "to behave like a spoiled child, to depend on",
    example: "妹は子どもの頃から、母に甘えている。",
    exampleReading: "いもうとはこどものころから、ははにあまえている。",
    exampleMeaning: "My younger sister has been depending on our mother since childhood.",
    type: ["る verb"],
    _JLPT: true,
    extra: ["+ 甘え Lack of self-reliance", "+ 甘やかす To spoil"],
  },
  {
    word: "世間知らず",
    reading: "せけんしらず",
    meaning: "naive, inexperienced, ignorant of the world",
    example: "父に「おまえは世間知らずだ」と言われた。",
    exampleReading: "ちちに「おまえはせけんしらずだ」といわれた。",
    exampleMeaning: "My father told me, 'You are naive.'",
    type: ["noun", "な adjective"],
    _JLPT: true,
    info: "ず patters works like ないで pattern, indicating a lack of something. Often used with particle に.",
  },
  {
    word: "躾",
    reading: "しつけ",
    meaning: "discipline, training, upbringing",
    example: "子どもの躾は、親の義務だ。",
    exampleReading: "こどものしつけは、おやのぎむだ。",
    exampleMeaning: "Disciplining children is the parent's duty.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ しつける To discipline, to train"],
  },
  {
    word: "義務",
    reading: "ぎむ",
    meaning: "duty, obligation",
    example: "親には子どもを育てる義務がある。",
    exampleReading: "おやにはこどもをそだてるぎむがある。",
    exampleMeaning: "Parents have the duty to raise their children.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "言いつける",
    reading: "いいつける",
    meaning: "to tell, to order, to instruct",
    example: "兄は妹のいたずらを母に言いつけた。",
    exampleReading: "あにはいもうとのいたずらをははにいいつけた。",
    exampleMeaning: "My older brother told our mother about my younger sister's mischief.",
    type: ["る verb"],
    _JLPT: true, 
  },
  {
    word: "自立",
    reading: "じりつ",
    meaning: "independence, self-reliance",
    example: "兄は自立して、一人暮らしをしている。",
    exampleReading: "あにはじりつして、ひとりぐらしをしている。",
    exampleMeaning: "My older brother is independent and living alone.",
    type: ["noun", "する verb"],
    _JLPT: true, 
  },
  {
    word: "言います",
    reading: "いいます",
    meaning: "to start saying",
    example: "妹はアメリカに語学留学したいと言い出した。",
    exampleReading: "いもうとはアメリカにごがくりゅうがくしたいといいだした。",
    exampleMeaning: "My younger sister started saying she wants to study language in America.",
    type: ["う verb"],
    _JLPT: true, 
  },
  {
    word: "意思",
    reading: "いし",
    meaning: "intention, will, purpose",
    example: "親に自分の意思を伝えるのは難しい。", 
    exampleReading: "おやにじぶんのいしをつたえるのはむずかしい。",
    exampleMeaning: "It's difficult to tell my own intentions to my parents.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "尊重",
    reading: "そんちょう",
    meaning: "respect, esteem",
    example: "両親はいつも、私の意見を尊重してくれる。",
    exampleReading: "りょうしんはいつも、わたしのいけんをそんちょうしてくれる。",
    exampleMeaning: "My parents always respect my opinions.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "説得",
    reading: "せっとく",
    meaning: "convincing, persuasion", 
    example: "父は私の留学に反対だったが、母が説得してくれた。",
    exampleReading: "ちちはわたしのりゅうがくにはんたいだったが、ははがせっとくしてくれた。",
    exampleMeaning: "My father was against my studying abroad, but my mother persuaded him.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "納得",
    reading: "なっとく",
    meaning: "acknowledgement, understanding, agreement",
    example: "父は私の留学を、やっと納得してくれた。",
    exampleReading: "ちちはわたしのりゅうがくを、やっとなっとくしてくれた。",
    exampleMeaning: "My father finally agreed to my studying abroad.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "逆らう",
    reading: "さからう",
    meaning: "to go against, to oppose",
    example: "惹いときは、よく親に塗らった。\n強い風に逆らって歩く。", 
    exampleReading: "ときは、よくおやにさからった。\nつよいかぜにさからってあるく。",
    exampleMeaning: "In my youth, I often went against my parents.\nI walk against the strong wind.",
    type: ["う verb"],
    _JLPT: true,
    info: "Used to indicate going against someone or opposing something.",
    extra: ["+ 抵抗 [ていこう] resistance"],
  },
  {
    word: "反省",
    reading: "はんせい",
    meaning: "reflection, reconsideration",
    example: "昔親に逆らったことを、今は反省している。",
    exampleReading: "むかしおやにさからったことを、いまははんせいしている。",
    exampleMeaning: "I now reflect on the times I went against my parents in the past.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 反省会 [はんせいかい] reflection meeting"],
  },
  {
    word: "放っておく",
    reading: "ほうっておく",
    meaning: "to leave alone", 
    example: "父はいちいちうるさい。放っておいてほしい。",
    exampleReading: "ちちはいちいちうるさい。ほうっておいてほしい。",
    exampleMeaning: "My father is so annoying. I wish he would leave me alone.",
    type: ["う verb"],
    _JLPT: true,
    info: "いちいち - 'One by one', 'each and every (little) thing, いちいち文句を言う - 'to complain about every little thing'.\nうるさい can figuratively mean 'annoying' or 'bothersome'.",
  },
  {
    word: "介護",
    reading: "かいご",
    meaning: "nursing care, caregiving",
    example: "家族みんなで祖母を護している。",
    exampleReading: "かぞくみんなでそぼをかいごしている。",
    exampleMeaning: "The whole family is taking care of our grandmother.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 介護士 [かいごし] caregiver / nurse"], 
  },
  {
    word: "世代",
    reading: "せだい",
    meaning: "generation, era",
    example: "世代が違うと、話が合わないこともある。",
    exampleReading: "せだいがちがうと、はなしがあわないこともある。",
    exampleMeaning: "It's difficult to communicate among different generations.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "継ぐ",
    reading: "つぐ",
    meaning: "to inherit, to succeed",
    example: "来年、父の会社を継ぐことになった。",
    exampleReading: "らいねん、ちちのかいしゃをつぐことになった。",
    exampleMeaning: "Next year, I will inherit my father's company.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 受け継ぐ [うけつぐ] to inherit",],
  },
  {
    word: "妊娠",
    reading: "にんしん",
    meaning: "pregnancy",
    example: "姉は妊娠して、来月出産する。", 
    exampleReading: "あねはにんしんして、らいげつしゅっさんする。",
    exampleMeaning: "My older sister is pregnant and will give birth next month.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 産婦人科 [さんふじんか]", "+ 妊婦 [にんぷ] pregnant woman"],
  },
  {
    word: "出産",
    reading: "しゅっさん",
    meaning: "childbirth",
    example: "実家の近くの病院で出産することにした。", 
    exampleReading: "じっかのちかくのびょういんでしゅっさんすることにした。",
    exampleMeaning: "I decided to give birth at a hospital near my parents' home.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 出産祝い [しゅっさんいわい] baby gift"],
  },
  {
    word: "産む",
    reading: "うむ",
    meaning: "to give birth",
    example: "姉は二十歳のときに長男を産んだ。", 
    exampleReading: "あねははたちのときにながしょをうんだ。",
    exampleMeaning: "My older sister gave birth to her first son when she was twenty.",
    type: ["う verb"],
    _JLPT: true,
    info: "長男 [ちょうなん] means 'first son'",
    extra: ["+ 産まれる [うまれる] to be born"],
  },
  {
    word: "高学歷",
    reading: "こうがくれき",
    meaning: "high academic background, well-educated",
    example: "彼は高学歴で、いい会社に就職した。",
    exampleReading: "かれはこうがくれきで、いいかいしゃにしゅうしょくした。",
    exampleMeaning: "He has a high academic background and got a good job.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高学年",
    reading: "こうがくねん",
    meaning: "upper grades (in school), higher grade",
    example: "高学年になると、勉強が難しくなる。",
    exampleReading: "こうがくねんになると、べんきょうがむずかしくなる。",
    exampleMeaning: "When you reach the upper grades, studying becomes more difficult.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高収入",
    reading: "こうしゅうにゅう", 
    meaning: "high income, high salary",
    example: "彼は高収入の仕事に就いている。",
    exampleReading: "かれはこうしゅうにゅうのしごとについている。",
    exampleMeaning: "He has a job with a high income.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "高性能",
    reading: "こうせいのう",
    meaning: "high performance, high efficiency",
    example: "このパソコンは高性能で、仕事がはかどる。",
    exampleReading: "このパソコンはこうせいのうで、しごとがはかどる。",
    exampleMeaning: "This computer has high performance, making work more efficient.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高気压",
    reading: "こうきあつ",
    meaning: "high pressure (weather)",
    example: "今日は高気圧で、天気がいい。",
    exampleReading: "きょうはこうきあつで、てんきがいい。",
    exampleMeaning: "Today, the weather is good due to high pressure.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高血圧",
    reading: "こうけつあつ",
    meaning: "high blood pressure",
    example: "高血圧は健康に悪い影響を与える。",
    exampleReading: "こうけつあつはけんこうにわるいえいきょうをあたえる。",
    exampleMeaning: "High blood pressure has a negative impact on health.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "仲良し",
    reading: "なかよし", 
    meaning: "close friend, good relationship",
    example: "彼とは小学校からの仲良しだ。",
    exampleReading: "かれとはしょうがっこうからのなかよしだ。",
    exampleMeaning: "He has been my close friend since elementary school.",
    type: ["noun", "な adjective"],
    _JLPT: true,
  },
  {
    word: "縁",
    reading: "えん", 
    meaning: "fate, destiny, connection",
    example: "縁があって、彼女と親友になれた。",
    exampleReading: "えんがあって、かのじょとしんゆうになれた。",
    exampleMeaning: "By fate, I became close friends with her.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ニックネーム",
    reading: "ニックネーム",
    meaning: "nickname",
    example: "彼と私はニックネームで呼び合っている。", 
    exampleReading: "かれとわたしはニックネームでよびあっている。",
    exampleMeaning: "He and I call each other by our nicknames.",
    type: ["noun"],
    _JLPT: true,
    info: "呼び合う [よびあう] to call each other.",
    extra: ["= 愛称 [あいしょう] nickname", "= あだ名 [あだな] nickname"],
  },
  {
    word: "大半",
    reading: "たいはん", 
    meaning: "most of, majority",
    example: "一日の大半の時間を友達と過ごしている。",
    exampleReading: "いちにちのたいはんのじかんをともだちとすごしている。",
    exampleMeaning: "I spend most of my day with my friends.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "恵まれる",
    reading: "めぐまれる",
    meaning: "to be blessed with, to be endowed with",
    example: "私は、いつも友人に恵まれている。", 
    exampleReading: "わたしは、いつもゆうじんにめぐまれている。",
    exampleMeaning: "I am always blessed with friends.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "頼る",
    reading: "たよる",
    meaning: "to depend on, to rely on", 
    example: "私達は親友なのだから、困ったときは頼ってほしい。",
    exampleReading: "わたしたちはしんゆうなのだから、こまったときはたよってほしい。",
    exampleMeaning: "Since we are close friends, I want you to rely on me when you're in trouble.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 頼りにする [たよりにする] to rely on","+ 頼りになる [たよりになる] to be reliable, dependable"],
  },
  {
    word: "頼もしい",
    reading: "たのもしい",
    meaning: "dependable, reliable, trustworthy",
    example: "彼女は何でも相談できる頼もしい存在だ。", 
    exampleReading: "かのじょはなんでもそうだんできるたのもしいそんざいだ。",
    exampleMeaning: "She is a reliable person I can talk to about anything.",
    type: ["い adjective"],
    _JLPT: true,
    info: "相談 [そうだん] means 'consultation' or 'discussion'.\n存在 [そんざい] means 'existence' or 'being'.",
  },
  {
    word: "見習う",
    reading: "みならう",
    meaning: "to follow the example of, to learn from, to emulate",
    example: "私には見習うべき友人が何人かいる。", 
    exampleReading: "わたしにはみならうべきゆうじんがなんにんかいる。",
    exampleMeaning: "I have several friends whom I should emulate.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 見習い [みならい] apprentice, trainee"]
  },
  {
    word: "打ち問ける",
    reading: "うちとける",
    meaning: "to confess, to become friendly, to open one's heart",
    example: "親友だけに秘密を打ち明けた。", 
    exampleReading: "しんゆうだけにひみつをうちあけた。",
    exampleMeaning: "I confided my secret only to my close friend.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "励ます",
    reading: "はげます",
    meaning: "to encourage, to cheer up",
    example: "私が試験に落ちたとき、友達が励ましてくれた。",
    exampleReading: "わたしがしけんにおちたとき、ともだちがはげましてくれた。",
    exampleMeaning: "When I failed the exam, my friend encouraged me.",
    type: ["う verb"],
    _JLPT: true,
    info: "落ちる [おちる] means 'to fail' or 'to fall'.",
  },
  {
    word: "あえて",
    reading: "あえて",
    meaning: "daringly, boldly, intentionally",
    example: "大切な友達だから、あえて厳しい忠告もする。",
    exampleReading: "たいせつなともだちだから、あえてきびしいちゅうこくもする。",
    exampleMeaning: "Because they are a precious friend, I intentionally give them strict advice.",
    type: ["adverb"],
    _JLPT: true, 
    info: "あえて is used to indicate doing something intentionally or boldly, often against the norm or expectations.\n忠告 [ちゅうこく] means 'advice' or 'counsel'.",
  },
  {
    word: "慰める",
    reading: "なぐさめる", 
    meaning: "to comfort, to console",
    example: "友達が悲しんでいるとき、私は慰めるために側にいる。",
    exampleReading: "ともだちがかなしんでいるとき、わたしはなぐさめるためにそばにいる。",
    exampleMeaning: "When my friend is sad, I stay by their side to comfort them.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "察する",
    reading: "さっする", 
    meaning: "to infer, to sense, to guess",
    example: "友達の気持ちを察して、何も言わないことにした。",
    exampleReading: "ともだちのきもちをさっして、なにもいわないことにした。",
    exampleMeaning: "I sensed my friend's feelings and decided not to say anything.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "思いやり",
    reading: "おもいやり",
    meaning: "thoughtfulness, consideration, compassion",
    example: "周りの人への思いやりを大切にしたい。",
    exampleReading: "まわりのひとへのおもいやりをたいせつにしたい。",
    exampleMeaning: "I want to cherish thoughtfulness towards those around me.",
    type: ["noun"],
    _JLPT: true, 
    extra: ["+ 思いやる [おもいやる] to be considerate, to care for"],
  },
  {
    word: "何気ない",
    reading: "なにげない", 
    meaning: "casual",
    example: "友達との何気ない会話が楽しい。",
    exampleReading: "ともだちとのなにげないかいわがたのしい。",
    exampleMeaning: "Casual conversations with friends are enjoyable.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "からかう",
    reading: "からかう",
    meaning: "to tease, to make fun of",
    example: "彼女ができて、友達にからかわれた。",
    exampleReading: "かのじょができて、ともだちにからかわれた。",
    exampleMeaning: "I got a girlfriend and was teased by my friends.",
    type: ["う verb"],
    _JLPT: true,
    info: "からかう can also mean 'to joke around' or 'to playfully tease'.", 
  },
  {
    word: "幹事",
    reading: "かんじ",
    meaning: "organizer, person in charge",
    example: "仲間の飲み会では、いつも私が幹事だ。",
    exampleReading: "なかまののみかいでは、いつもわたしがかんじだ。",
    exampleMeaning: "I am always the organizer for our group drining gatherings.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "呼び出す",
    reading: "よびだす",
    meaning: "to send for, to summon, to call out", 
    example: "夜遅く、親友に「飲みに行こう」と呼びされた。",
    exampleReading: "よるおそく、しんゆうによみにいこうとよびだされた。",
    exampleMeaning: "Late at night, my close friend called me out to go drinking.",
    type: ["う verb"],
    _JLPT: true,
    info: "夜遅く [よるおそく] means 'late at night'.",
  },
  {
    word: "呼び止める",
    reading: "よびとめる",
    meaning: "to call out to stop someone, to stop someone by calling them",
    example: "アパートの前で管理人さんに呼び止められた。",
    exampleReading: "アパートのまえでかんりにんさんによびとめられた。",
    exampleMeaning: "I was stopped by the building manager in front of the apartment.",
    type: ["る verb"],
    _JLPT: true, 
    info: "管理人 [かんりにん] means 'building manager' or 'superintendent', especially of an apartment building, dormitory, or office.",
  },
  {
    word: "盛り上がる",
    reading: "もりあがる",
    meaning: "to get excited, to liven up, to surge", 
    example: "パーティーは盛り上がって、夜中まで続いた。\n地震で道が盛り上がった。",
    exampleReading: "パーティーはもりあがって、よなかまでつづいた。\nじしんでみちがもりあがった。",
    exampleMeaning: "The party got lively and continued until midnight.\nThe road rose up due to the earthquake.",
    type: ["う verb"],
    _JLPT: true,
    info: "1 - become excited 2 - expand and rise (surge)"
  },
  {
    word: "あきれる",
    reading: "あきれる",
    meaning: "to be shocked, to be astounded, to be amazed",
    example: "友達の行動にあきれて、何も言えなかった。",
    exampleReading: "ともだちのこうどうにあきれて、なにもいえなかった。",
    exampleMeaning: "I was so shocked by my friend's behavior that I couldn't say anything.",
    type: ["る verb"],
    _JLPT: true, 
    info: "行動 [こうどう] means 'behavior' or 'action'.",
  },
  {
    word: "ふざける",
    reading: "ふざける",
    meaning: "to joke, to fool around, to mess around",
    example: "友達とふざけていたら、転んで足の骨を折った。",
    exampleReading: "ともだちとふざけていたら、ころんであしのほねをおった。",
    exampleMeaning: "While fooling around with my friends, I fell and broke my leg.",
    type: ["る verb"],
    _JLPT: true,
    info: "転ぶ [ころぶ] means 'to fall down' or 'to tumble'.\n足の骨を折る [あしのほねをおる] means 'to break a leg'.",
  },
  {
    word: "久しい",
    reading: "ひさしい",
    meaning: "long time, long-awaited",
    example: "高校時代のクラスメートと久しく会っていない。",
    exampleReading: "こうこうじだいのクラスメートとひさしくあっていない。",
    exampleMeaning: "I haven't seen my high school classmates in a long time.",
    type: ["い adjective"],
    _JLPT: true,
    extra: ["+ 久しぶり [ひさしぶり] long time no see", "+ 久々 [ひさびさ] long time"], 
  },
  {
    word: "初対面",
    reading: "しょたいめん",
    meaning: "first meeting, first encounter",
    example: "初対面の人と話すのは緊張する。",
    exampleReading: "しょたいめんのひととはなすのはきんちょうする。",
    exampleMeaning: "I get nervous when talking to someone for the first time.",
    type: ["noun"], 
    _JLPT: true,
    info: "緊張 [きんちょう] means 'nervousness' or 'tension'.",
  },
  {
    word: "自己紹介",
    reading: "じこしょうかい",
    meaning: "self-introduction",
    example: "合コンでお互いに自己介をした。",
    exampleReading: "ごうコンでおたがいにじこしょうかいをした。",
    exampleMeaning: "At the group date, we introduced ourselves to each other.",
    type: ["noun", "する verb"],
    _JLPT: true, 
    info: "合コン [ごうコン] is a group date or social gathering.\nお互いに [おたがいに] means 'each other'.",
    extra: ["+ 自己流 [じこりゅう] one's own way, own method"],
  },
  {
    word: "おじぎ",
    reading: "おじぎ",
    meaning: "bow, bowing",
    example: "朝、大家さんに会ったので、おじぎした。",
    exampleReading: "あさ、おおやさんにあったので、おじぎした。",
    exampleMeaning: "I greeted the landlord with a bow when I met him in the morning.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "近所付き合い",
    reading: "きんじょづきあい",
    meaning: "neighborhood relations, interaction with neighbors", 
    example: "できるだけ近所付き合いを大切にしている。",
    exampleReading: "できるだけきんじょづきあいをたいせつにしている。",
    exampleMeaning: "I try to value my interactions with neighbors as much as possible.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ 友達付き合い [ともだちづきあい] interaction with friends"],
  },
  {
    word: "大家",
    reading: "おおや",
    meaning: "landlord, landlady",
    example: "私のアパートの大家さんは、とても親切な人だ。",
    exampleReading: "わたしのアパートのおおやさんは、とてもしんせつなひとだ。",
    exampleMeaning: "The landlord of my apartment is a very kind person.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "飼い主",
    reading: "かいぬし",
    meaning: "pet owner, owner of an animal",
    example: "犬の飼い主同士が公園でおしゃべりをしている。",
    exampleReading: "いぬのかいぬしどうしがこうえんでおしゃべりをしている。",
    exampleMeaning: "The dog's owners are chatting in the park.",
    type: ["noun"],
    _JLPT: true, 
    info: "同士 [どうし] means 'fellow' or 'among'.",
  },
  {
    word: "交わす",
    reading: "かわす",
    meaning: "to exchange, to swap, to trade",
    example: "近所の人達に会うと、笑顔であいさつを交わす。",
    exampleReading: "きんじょのひとたちにあうと、えがおであいさつをかわす。",
    exampleMeaning: "When I meet people in the neighborhood, I exchange greetings with a smile.",
    type: ["う verb"],
    _JLPT: true, 
    info: "近所 [きんじょ] means 'neighborhood' or 'local area'.",
  },
  {
    word: "振り返る",
    reading: "ふりかえる",
    meaning: "to look back, to turn around, to reflect",
    example: "後ろから名前を呼ばれて、振り返った。\n学生時代を振り返ると、なつかしい。",
    exampleReading: "うしろからなまえをよばれて、ふりかえった。\nがくせいじだいをふりかえると、なつかしい。",
    exampleMeaning: "I was called by name from behind and turned around.\nLooking back on my student days, I feel nostalgic.",
    type: ["る verb"],
    _JLPT: true,
    info: "振り返る can mean both 'to look back physically' and 'to reflect on past experiences'.\nなつかしい means 'nostalgic' or 'longing for the past'.\n呼ばれる [よばれる] means 'to be called', its transitive is 呼ぶ [よぶ].",
  },
  {
    word: "再会",
    reading: "さいかい",
    meaning: "reunion, meeting again",
    example: "以前お世話になった人に再会した。",
    exampleReading: "いぜんおせわになったひとにさいかいした。",
    exampleMeaning: "I had a reunion with someone who had helped me before.",
    type: ["noun", "する verb"],
    _JLPT: true, 
  },
  {
    word: "覚え",
    reading: "おぼえ",
    meaning: "recollection, memory, remembrance", 
    example: "田中さんとは会った覚えがない。",
    exampleReading: "たなかさんとはあったおぼえがない。",
    exampleMeaning: "I have no recollection of meeting Mr. Tanaka.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ 記憶 [きおく] memory, recollection"],
  },
  {
    word: "心当たり",
    reading: "こころあたり",
    meaning: "idea, clue, knowledge of, something that comes to mind",
    example: "心当たりのない番号から電話が、かかってきた。",
    exampleReading: "こころあたりのないばんごうからでんわが、かかってきた。",
    exampleMeaning: "I received a call from a number I had no idea about.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "結びつく",
    reading: "むすびつく",
    meaning: "to be connected, to be linked, to be tied together",
    example: "人と人は、いろいろなことで結びついている。",
    exampleReading: "ひととひとは、いろいろなことでむすびついている。",
    exampleMeaning: "People are connected in various ways.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+（～を)結びつける [むすびつける] to connect, to link together",], 
  },
  {
    word: "とっさ[に]",
    reading: "とっさ[に]",
    meaning: "at that moment, in an instant, immediately, in a split second",
    example: "隣の人に会ったとき、とっさに名前が出てこなかった。",
    exampleReading: "となりのひとにあったとき、とっさになまえがでてこなかった。",
    exampleMeaning: "When I met the person next to me, their name didn't come to mind immediately.",
    type: ["adverb"],
    _JLPT: true, 
  },
  {
    word: "てっきり",
    reading: "てっきり",
    meaning: "assumed, I thought for sure", 
    example: "てっきり彼らを兄弟だと思っていた。",
    exampleReading: "てっきりかれらをきょうだいだとおもっていた。",
    exampleMeaning: "I thought for sure they were siblings.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "思い込む",
    reading: "おもいこむ",
    meaning: "to be under the impression, to be convinced",
    example: "私は木村さんが独身だと思い込んでいた。",
    exampleReading: "わたしはきむらさんがどくしんだとおもいこんでいた。",
    exampleMeaning: "I was under the impression that Mr. Kimura was single.",
    type: ["う verb"],
    _JLPT: true, 
    info: "独身 [どくしん] means 'single' or 'unmarried'.",
    extra: ["+ 思い込み [おもいこみ] assumption, belief", "+ 思い込ませる [おもいこませる] to convince someone, to make someone believe", ],
  },
  {
    word: "コミュニケーション",
    reading: "コミュニケーション", 
    meaning: "communication, interaction",
    example: "いろいろな国の人とコミュニケーションを持ちたい。",
    exampleReading: "いろいろなくにのひととコミュニケーションをもちたい。",
    exampleMeaning: "I want to have communication with people from various countries.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ネットワーク",
    reading: "ネットワーク",
    meaning: "network, connection",
    example: "将来のために、知り合いのネットワークを広げたい。",
    exampleReading: "しょうらいのために、しりあいのネットワークをひろげたい。",
    exampleMeaning: "I want to expand my network of acquaintances for the future.",
    type: ["noun"],
    _JLPT: true, 
    info: "知り合い [しりあい] means 'acquaintance' or 'someone you know'.\n広げる [ひろげる] means 'to expand' or 'to spread out'. Its intransivite if 広がる [ひろがる].",
  },
  {
    word: "直接",
    reading: "ちょくせつ",
    meaning: "directly, firsthand",
    example: "彼とは真のを達ではない。",
    exampleReading: "かれとはしんのをたちではない。",
    exampleMeaning: "He is not a close (direct) friend of mine.",
    type: ["adverb", "noun"],
    _JLPT: true, 
    extra: ["⇔ 間接 [かんせつ] indirect"],
  },
  {
    word: "接する",
    reading: "せっする",
    meaning: "to come into contact with, to interact with, adjacent to",
    example: "敬語が下手なので、目上の人と接するのが苦手だ。\n私のアパートは、隣のビルと接している。", 
    exampleReading: "けいごがへたなので、めうえのひととせっするのがにがてだ。\nわたしのアパートは、となりのビルとせっしている。",
    exampleMeaning: "I'm not good at interacting with people of higher status because I'm not good at using honorific language.\nMy apartment is adjacent to the building next door.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "招く",
    reading: "まねく",
    meaning: "to invite, to call, to beckon",
    example: "先日、部長のお宅に招かれた。\n彼の言葉が大きな混乱を招いた。", 
    exampleReading: "せんじつ、ぶちょうのおたくにまねかれた。\nかれのことばがおおきなこんらんをまねいた。",
    exampleMeaning: "The other day, I was invited to the manager's house.\nHis words caused a great deal of confusion.",
    type: ["う verb"],
    _JLPT: true,
    info: "混乱 [こんらん] means 'confusion' or 'disorder'.\n招く can also mean 'to cause' or 'to bring about', as in the second example.",
    extra: ["招かれる [まねかれる] is the passive form meaning 'to be invited'."],
  },
  {
    word: "気配り",
    reading: "きくばり",
    meaning: "consideration for other's feeling, thoughtfulness, attentiveness", 
    example: "アルバイト先の先輩の気配りを見習いたい。",
    exampleReading: "アルバイトさきのせんぱいのきくばりをみならいたい。",
    exampleMeaning: "I want to emulate the consideration for others that my senior co-worker at my part-time job shows.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "込める",
    reading: "こめる",
    meaning: "to put into, to include, to load, infuse",
    example: "感謝の気持ちを込めて、先生へのプレゼントを選んだ。", 
    exampleReading: "かんしゃのきもちをこめて、せんせいへのプレゼントをえらんだ。",
    exampleMeaning: "I chose a gift for my teacher with feelings of gratitude.",
    type: ["る verb"],
    _JLPT: true,
    info: "感謝の気持ち [かんしゃのきもち] means 'feelings of gratitude'.\n込める can also mean 'to include' or 'to load', as in putting effort or emotion into something.",
  },
  {
    word: "同期",
    reading: "どうき",
    meaning: "colleague, peer, same period",
    example: "彼は会社の国期と、とても仲がいい。", 
    exampleReading: "かれはかいしゃのどうきと、とてもなかがいい。",
    exampleMeaning: "He is very close with his colleagues from the same period at the company.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ぐち",
    reading: "ぐち", 
    meaning: "complaint, grumble, gripe",
    example: "毎晩居酒屋で同期とぐちをこぼしている。",
    exampleReading: "まいばんいざかやでどうきとぐちをこぼしている。",
    exampleMeaning: "Every night, I complain to my colleagues at the izakaya.",
    type: ["noun"],
    _JLPT: true,
    info: "こぼす means 'to spill' or 'to complain about'.",
  },
  {
    word: "大いに",
    reading: "おおいに",
    meaning: "very, greatly, very much, a lot", 
    example: "今日は大いに飲んで楽しもう。",
    exampleReading: "きょうはおおいにのんでたのしもう。",
    exampleMeaning: "Let's drink a lot and have fun today.",
    type: ["adverb"],
    _JLPT: true,
    info: "大いに is used to emphasize the extent or degree of something, often used to express enthusiasm or encouragement.",
  },
  {
    word: "低予算",
    reading: "ていよさん", 
    meaning: "low budget",
    example: "低予算で旅行を計画するのは難しい。",
    exampleReading: "ていよさんでりょこうをけいかくするのはむずかしい。",
    exampleMeaning: "Planning a trip on a low budget is difficult.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "低学年",
    reading: "ていがくねん",
    meaning: "lower grade",
    example: "低学年の子供たちは、遊びながら学ぶことが大切だ。",
    exampleReading: "ていがくねんのこどもたちは、あそびながらまなぶことがたいせつだ。",
    exampleMeaning: "For lower grade children, learning through play is important.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "低血圧",
    reading: "ていけつあつ", 
    meaning: "low blood pressure",
    example: "低血圧の人は、朝起きるのが大変だ。",
    exampleReading: "ていけつあつのひとは、あさおきるのがたいへんだ。",
    exampleMeaning: "People with low blood pressure find it difficult to get up in the morning.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "低姿勢",
    reading: "ていしせい",
    meaning: "humble attitude, low posture",
    example: "彼はいつも低姿勢で、周りの人に優しく接する。",
    exampleReading: "かれはいつもていしせいで、まわりのひとにやさしくせっする。",
    exampleMeaning: "He always has a humble attitude and treats those around him kindly.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "低次元",
    reading: "ていじげん",
    meaning: "low dimension, low level, trivial matter",
    example: "その議論は低次元で、もっと深い話をしたい。",
    exampleReading: "そのぎろんはていじげんで、もっとふかいはなしをしたい。",
    exampleMeaning: "That discussion is at a low level, and I want to have a deeper conversation.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "低レベル",
    reading: "ていレベル", 
    meaning: "low level, low standard",
    example: "このゲームは低レベルで、子供向けだ。",
    exampleReading: "このゲームはていレベルで、こどもむけだ。",
    exampleMeaning: "This game is at a low level and is intended for children.",
    type: ["noun"],
    _JLPT: true,
  },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  
];