export const VOCABS_N2: TVocabJLPT[] = [
  {
    word: "一家",
    reading: "いっか", 
    meaning: "a family, a household",
    example: "一家の大黒柱",
    exampleReading: "いっかのだいこくばしら",
    exampleMeaning: "the head of a family",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ ファミリー  ", "= 一家団欒 [いっかだんらん] family gathering"],
  },
  {
    word: "存在",
    reading: "そんざい",
    meaning: "existence, being",
    example: "家族は本当にありがたい存在だ。",
    exampleReading: "かぞくはほんとうにありがたいそんざいだ。",
    exampleMeaning: "Family is truly a precious existence.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "向き合う",
    reading: "むきあう",
    meaning: "to face each other, to confront",
    example: "家族みんなで問題に向き合っている。", 
    exampleReading: "かぞくみんなでもんだいにむきあっている。",
    exampleMeaning: "The whole family is facing the problem together.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "つくづく",
    reading: "つくづく",
    meaning: "deeply, greatly, thoroughly",
    example: "最近、家族のありがたさをつくづくと感じる。", 
    exampleReading: "さいきん、かぞくのありがたさをつくづくとかんじる。",
    exampleMeaning: "Recently, I feel deeply grateful for my family.",
    type: ["adverb"],
    _JLPT: true,
    info: "Used to express a deep or thorough feeling about something. Particle と is often used with it.",
    extra: ["+ しみじみ deeply", ""],
  },
  {
    word: "養う",
    reading: "やしなう",
    meaning: "To rpovide for, to support", 
    example: "父は一生懸命に働いて、家族を養っている。",
    exampleReading: "ちちはいっしょうけんめいにはたらいて、かぞくをやしなっている。",
    exampleMeaning: "My father works hard to support(provide for) the family.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "役目",
    reading: "やくめ",
    meaning: "role, duty, responsibility",
    example: "子どもを育てることが親の役目だ。",
    exampleReading: "こどもをそだてることがおやのやくめだ。",
    exampleMeaning: "Raising children is the parent's responsibility.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "甘える",
    reading: "あまえる",
    meaning: "to behave like a spoiled child, to depend on",
    example: "妹は子どもの頃から、母に甘えている。",
    exampleReading: "いもうとはこどものころから、ははにあまえている。",
    exampleMeaning: "My younger sister has been depending on our mother since childhood.",
    type: ["る verb"],
    _JLPT: true,
    extra: ["+ 甘え Lack of self-reliance", "+ 甘やかす To spoil"],
  },
  {
    word: "世間知らず",
    reading: "せけんしらず",
    meaning: "naive, inexperienced, ignorant of the world",
    example: "父に「おまえは世間知らずだ」と言われた。",
    exampleReading: "ちちに「おまえはせけんしらずだ」といわれた。",
    exampleMeaning: "My father told me, 'You are naive.'",
    type: ["noun", "な adjective"],
    _JLPT: true,
    info: "ず patters works like ないで pattern, indicating a lack of something. Often used with particle に.",
  },
  {
    word: "躾",
    reading: "しつけ",
    meaning: "discipline, training, upbringing",
    example: "子どもの躾は、親の義務だ。",
    exampleReading: "こどものしつけは、おやのぎむだ。",
    exampleMeaning: "Disciplining children is the parent's duty.",
    type: ["noun"],
    _JLPT: true,
    extra: ["+ しつける To discipline, to train"],
  },
  {
    word: "義務",
    reading: "ぎむ",
    meaning: "duty, obligation",
    example: "親には子どもを育てる義務がある。",
    exampleReading: "おやにはこどもをそだてるぎむがある。",
    exampleMeaning: "Parents have the duty to raise their children.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "言いつける",
    reading: "いいつける",
    meaning: "to tell, to order, to instruct",
    example: "兄は妹のいたずらを母に言いつけた。",
    exampleReading: "あにはいもうとのいたずらをははにいいつけた。",
    exampleMeaning: "My older brother told our mother about my younger sister's mischief.",
    type: ["る verb"],
    _JLPT: true, 
  },
  {
    word: "自立",
    reading: "じりつ",
    meaning: "independence, self-reliance",
    example: "兄は自立して、一人暮らしをしている。",
    exampleReading: "あにはじりつして、ひとりぐらしをしている。",
    exampleMeaning: "My older brother is independent and living alone.",
    type: ["noun", "する verb"],
    _JLPT: true, 
  },
  {
    word: "言います",
    reading: "いいます",
    meaning: "to start saying",
    example: "妹はアメリカに語学留学したいと言い出した。",
    exampleReading: "いもうとはアメリカにごがくりゅうがくしたいといいだした。",
    exampleMeaning: "My younger sister started saying she wants to study language in America.",
    type: ["う verb"],
    _JLPT: true, 
  },
  {
    word: "意思",
    reading: "いし",
    meaning: "intention, will, purpose",
    example: "親に自分の意思を伝えるのは難しい。", 
    exampleReading: "おやにじぶんのいしをつたえるのはむずかしい。",
    exampleMeaning: "It's difficult to tell my own intentions to my parents.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "尊重",
    reading: "そんちょう",
    meaning: "respect, esteem",
    example: "両親はいつも、私の意見を尊重してくれる。",
    exampleReading: "りょうしんはいつも、わたしのいけんをそんちょうしてくれる。",
    exampleMeaning: "My parents always respect my opinions.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "説得",
    reading: "せっとく",
    meaning: "convincing, persuasion", 
    example: "父は私の留学に反対だったが、母が説得してくれた。",
    exampleReading: "ちちはわたしのりゅうがくにはんたいだったが、ははがせっとくしてくれた。",
    exampleMeaning: "My father was against my studying abroad, but my mother persuaded him.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "納得",
    reading: "なっとく",
    meaning: "acknowledgement, understanding, agreement",
    example: "父は私の留学を、やっと納得してくれた。",
    exampleReading: "ちちはわたしのりゅうがくを、やっとなっとくしてくれた。",
    exampleMeaning: "My father finally agreed to my studying abroad.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "逆らう",
    reading: "さからう",
    meaning: "to go against, to oppose",
    example: "惹いときは、よく親に塗らった。\n強い風に逆らって歩く。", 
    exampleReading: "ときは、よくおやにさからった。\nつよいかぜにさからってあるく。",
    exampleMeaning: "In my youth, I often went against my parents.\nI walk against the strong wind.",
    type: ["う verb"],
    _JLPT: true,
    info: "Used to indicate going against someone or opposing something.",
    extra: ["+ 抵抗 [ていこう] resistance"],
  },
  {
    word: "反省",
    reading: "はんせい",
    meaning: "reflection, reconsideration",
    example: "昔親に逆らったことを、今は反省している。",
    exampleReading: "むかしおやにさからったことを、いまははんせいしている。",
    exampleMeaning: "I now reflect on the times I went against my parents in the past.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 反省会 [はんせいかい] reflection meeting"],
  },
  {
    word: "放っておく",
    reading: "ほうっておく",
    meaning: "to leave alone", 
    example: "父はいちいちうるさい。放っておいてほしい。",
    exampleReading: "ちちはいちいちうるさい。ほうっておいてほしい。",
    exampleMeaning: "My father is so annoying. I wish he would leave me alone.",
    type: ["う verb"],
    _JLPT: true,
    info: "いちいち - 'One by one', 'each and every (little) thing, いちいち文句を言う - 'to complain about every little thing'.\nうるさい can figuratively mean 'annoying' or 'bothersome'.",
  },
  {
    word: "介護",
    reading: "かいご",
    meaning: "nursing care, caregiving",
    example: "家族みんなで祖母を護している。",
    exampleReading: "かぞくみんなでそぼをかいごしている。",
    exampleMeaning: "The whole family is taking care of our grandmother.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 介護士 [かいごし] caregiver / nurse"], 
  },
  {
    word: "世代",
    reading: "せだい",
    meaning: "generation, era",
    example: "世代が違うと、話が合わないこともある。",
    exampleReading: "せだいがちがうと、はなしがあわないこともある。",
    exampleMeaning: "It's difficult to communicate among different generations.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "継ぐ",
    reading: "つぐ",
    meaning: "to inherit, to succeed",
    example: "来年、父の会社を継ぐことになった。",
    exampleReading: "らいねん、ちちのかいしゃをつぐことになった。",
    exampleMeaning: "Next year, I will inherit my father's company.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 受け継ぐ [うけつぐ] to inherit",],
  },
  {
    word: "妊娠",
    reading: "にんしん",
    meaning: "pregnancy",
    example: "姉は妊娠して、来月出産する。", 
    exampleReading: "あねはにんしんして、らいげつしゅっさんする。",
    exampleMeaning: "My older sister is pregnant and will give birth next month.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 産婦人科 [さんふじんか]", "+ 妊婦 [にんぷ] pregnant woman"],
  },
  {
    word: "出産",
    reading: "しゅっさん",
    meaning: "childbirth",
    example: "実家の近くの病院で出産することにした。", 
    exampleReading: "じっかのちかくのびょういんでしゅっさんすることにした。",
    exampleMeaning: "I decided to give birth at a hospital near my parents' home.",
    type: ["noun", "する verb"],
    _JLPT: true,
    extra: ["+ 出産祝い [しゅっさんいわい] baby gift"],
  },
  {
    word: "産む",
    reading: "うむ",
    meaning: "to give birth",
    example: "姉は二十歳のときに長男を産んだ。", 
    exampleReading: "あねははたちのときにながしょをうんだ。",
    exampleMeaning: "My older sister gave birth to her first son when she was twenty.",
    type: ["う verb"],
    _JLPT: true,
    info: "長男 [ちょうなん] means 'first son'",
    extra: ["+ 産まれる [うまれる] to be born"],
  },
  {
    word: "高学歷",
    reading: "こうがくれき",
    meaning: "high academic background, well-educated",
    example: "彼は高学歴で、いい会社に就職した。",
    exampleReading: "かれはこうがくれきで、いいかいしゃにしゅうしょくした。",
    exampleMeaning: "He has a high academic background and got a good job.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高学年",
    reading: "こうがくねん",
    meaning: "upper grades (in school), higher grade",
    example: "高学年になると、勉強が難しくなる。",
    exampleReading: "こうがくねんになると、べんきょうがむずかしくなる。",
    exampleMeaning: "When you reach the upper grades, studying becomes more difficult.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高収入",
    reading: "こうしゅうにゅう", 
    meaning: "high income, high salary",
    example: "彼は高収入の仕事に就いている。",
    exampleReading: "かれはこうしゅうにゅうのしごとについている。",
    exampleMeaning: "He has a job with a high income.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "高性能",
    reading: "こうせいのう",
    meaning: "high performance, high efficiency",
    example: "このパソコンは高性能で、仕事がはかどる。",
    exampleReading: "このパソコンはこうせいのうで、しごとがはかどる。",
    exampleMeaning: "This computer has high performance, making work more efficient.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高気压",
    reading: "こうきあつ",
    meaning: "high pressure (weather)",
    example: "今日は高気圧で、天気がいい。",
    exampleReading: "きょうはこうきあつで、てんきがいい。",
    exampleMeaning: "Today, the weather is good due to high pressure.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "高血圧",
    reading: "こうけつあつ",
    meaning: "high blood pressure",
    example: "高血圧は健康に悪い影響を与える。",
    exampleReading: "こうけつあつはけんこうにわるいえいきょうをあたえる。",
    exampleMeaning: "High blood pressure has a negative impact on health.",
    type: ["noun"],
    _JLPT: true, 
  },
  {
    word: "仲良し",
    reading: "なかよし", 
    meaning: "close friend, good relationship",
    example: "彼とは小学校からの仲良しだ。",
    exampleReading: "かれとはしょうがっこうからのなかよしだ。",
    exampleMeaning: "He has been my close friend since elementary school.",
    type: ["noun", "な adjective"],
    _JLPT: true,
  },
  {
    word: "縁",
    reading: "えん", 
    meaning: "fate, destiny, connection",
    example: "縁があって、彼女と親友になれた。",
    exampleReading: "えんがあって、かのじょとしんゆうになれた。",
    exampleMeaning: "By fate, I became close friends with her.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ニックネーム",
    reading: "ニックネーム",
    meaning: "nickname",
    example: "彼と私はニックネームで呼び合っている。", 
    exampleReading: "かれとわたしはニックネームでよびあっている。",
    exampleMeaning: "He and I call each other by our nicknames.",
    type: ["noun"],
    _JLPT: true,
    info: "呼び合う [よびあう] to call each other.",
    extra: ["= 愛称 [あいしょう] nickname", "= あだ名 [あだな] nickname"],
  },
  {
    word: "大半",
    reading: "たいはん", 
    meaning: "most of, majority",
    example: "一日の大半の時間を友達と過ごしている。",
    exampleReading: "いちにちのたいはんのじかんをともだちとすごしている。",
    exampleMeaning: "I spend most of my day with my friends.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "恵まれる",
    reading: "めぐまれる",
    meaning: "to be blessed with, to be endowed with",
    example: "私は、いつも友人に恵まれている。", 
    exampleReading: "わたしは、いつもゆうじんにめぐまれている。",
    exampleMeaning: "I am always blessed with friends.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "頼る",
    reading: "たよる",
    meaning: "to depend on, to rely on", 
    example: "私達は親友なのだから、困ったときは頼ってほしい。",
    exampleReading: "わたしたちはしんゆうなのだから、こまったときはたよってほしい。",
    exampleMeaning: "Since we are close friends, I want you to rely on me when you're in trouble.",
    type: ["う verb"],
    _JLPT: true,
    extra: ["+ 頼りにする [たよりにする] to rely on","+ 頼りになる [たよりになる] to be reliable, dependable"],
  },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  // {
  //   word: "aaaa",
  //   reading: "aaaa", 
  // },
  
];