export const interviewWords = [
  { kanji: '要件定義', kana: 'ようけんていぎ', english: 'requirement definition' },
  { kanji: '実装', kana: 'じっそう', english: 'implementation' },
  { kanji: '一連', kana: 'いちれん', english: 'series' },
  { kanji: '流れに', kana: 'ながれに', english: 'in the flow' },
  { kanji: '関わる', kana: 'かかわる', english: 'to be involved in' },
  { kanji: '業界', kana: 'ぎょうかい', english: 'industry' },
  { kanji: '携わる', kana: 'たずさわる', english: 'to be involved in' },
  { kanji: '従事する', kana: 'じゅうじする', english: 'to engage in' },
  { kanji: '複数', kana: 'ふくすう', english: 'multiple' },
  { kanji: '多国籍', kana: 'たこくせき', english: 'multinational' },
  { kanji: '多文化', kana: 'たぶんか', english: 'multicultural' },
  { kanji: '環境', kana: 'かんきょう', english: 'environment' },
  { kanji: '管理', kana: 'かんり', english: 'management' },
  { kanji: '意識', kana: 'いしき', english: 'consciousness' },
  { kanji: '成果', kana: 'せいか', english: 'results' },
  { kanji: '目指す', kana: 'めざす', english: 'to aim for' },
  { kanji: '転職', kana: 'てんしょく', english: 'job change' },
  { kanji: '前職', kana: 'ぜんしょく', english: 'previous job' },
  { kanji: '退職', kana: 'たいしょく', english: 'resignation' },
  { kanji: '新機能', kana: 'しんきのう', english: 'new feature' },
  { kanji: '体験', kana: 'たいけん', english: 'experience' },
  { kanji: '改善', kana: 'かいぜん', english: 'improvement' },
  { kanji: '修正', kana: 'しゅうせい', english: 'correction' },
  { kanji: '作成', kana: 'さくせい', english: 'creation' },
  { kanji: '設計', kana: 'せっけい', english: 'design' },
  { kanji: '保守', kana: 'ほしゅ', english: 'maintenance' },
  { kanji: '承知しました', kana: 'しょうちしました', english: 'I understand' },
  { kanji: '了解', kana: 'りょうかい', english: 'understood' },
  { kanji: '理解です', kana: 'りかいです', english: 'I understand' },
  { kanji: '課題', kana: 'かだい', english: 'issue・assignment' },
  { kanji: '解決', kana: 'かいけつ', english: 'solution' },
  { kanji: '真面目に', kana: 'まじめに', english: 'seriously' },
  { kanji: '対応', kana: 'たいおう', english: 'response・correspondence' },
  { kanji: '短期間', kana: 'たんきかん', english: 'short period of time' },
  { kanji: '当時', kana: 'とうじ', english: 'at that time' },
  { kanji: '状況', kana: 'じょうきょう', english: 'situation' },
  { kanji: '連携部分', kana: 'れんけいぶぶん', english: 'integration part・connected section' },
  { kanji: '公式', kana: 'こうしき', english: 'official' },
  { kanji: '仕組み', kana: 'しきみ', english: 'mechanism・how something works' },
  { kanji: '検証', kana: 'けんしょう', english: 'verification・validation・testing' },
  { kanji: '参考', kana: 'さんこう', english: 'reference・example' },
];