export const interviewWords = [
  { kanji: '要件定義', kana: 'ようけんていぎ', english: 'requirement definition' },
  { kanji: '実装', kana: 'じっそう', english: 'implementation' },
  { kanji: '一連', kana: 'いちれん', english: 'series' },
  { kanji: '流れに', kana: 'ながれに', english: 'in the flow' },
  { kanji: '関わる', kana: 'かかわる', english: 'to be involved in' },
  { kanji: '業界', kana: 'ぎょうかい', english: 'industry' },
  { kanji: '携わる', kana: 'たずさわる', english: 'to be involved in' },
  { kanji: '従事する', kana: 'じゅうじする', english: 'to engage in' },
  { kanji: '複数', kana: 'ふくすう', english: 'multiple' },
  { kanji: '多国籍', kana: 'たこくせき', english: 'multinational' },
  { kanji: '多文化', kana: 'たぶんか', english: 'multicultural' },
  { kanji: '環境', kana: 'かんきょう', english: 'environment' },
  { kanji: '管理', kana: 'かんり', english: 'management' },
  { kanji: '意識', kana: 'いしき', english: 'consciousness' },
  { kanji: '成長', kana: 'せいちょう', english: 'growth' },
  { kanji: '成果', kana: 'せいか', english: 'results' },
  { kanji: '作成', kana: 'さくせい', english: 'creation' },
  { kanji: '目指す', kana: 'めざす', english: 'to aim for' },
  { kanji: '転職', kana: 'てんしょく', english: 'job change' },
  { kanji: '前職', kana: 'ぜんしょく', english: 'previous job' },
  { kanji: '退職', kana: 'たいしょく', english: 'resignation' },
  { kanji: '就職', kana: 'しゅうしょく', english: 'job hunting' },
  { kanji: '新機能', kana: 'しんきのう', english: 'new feature' },
  { kanji: '体験', kana: 'たいけん', english: 'experience' },
  { kanji: '改善', kana: 'かいぜん', english: 'improvement' },
  { kanji: '修正', kana: 'しゅうせい', english: 'correction' },
  { kanji: '設計', kana: 'せっけい', english: 'design' },
  { kanji: '設定', kana: 'せってい', english: 'setting' },
  { kanji: '保守', kana: 'ほしゅ', english: 'maintenance' },
  { kanji: '承知しました', kana: 'しょうちしました', english: 'I understand' },
  { kanji: '了解', kana: 'りょうかい', english: 'understood' },
  { kanji: '理解です', kana: 'りかいです', english: 'I understand' },
  { kanji: '課題', kana: 'かだい', english: 'issue・assignment' },
  { kanji: '解決', kana: 'かいけつ', english: 'solution' },
  { kanji: '真面目に', kana: 'まじめに', english: 'seriously' },
  { kanji: '対応', kana: 'たいおう', english: 'response・correspondence' },
  { kanji: '短期間', kana: 'たんきかん', english: 'short period of time' },
  { kanji: '当時', kana: 'とうじ', english: 'at that time' },
  { kanji: '状況', kana: 'じょうきょう', english: 'situation' },
  { kanji: '連携部分', kana: 'れんけいぶぶん', english: 'integration part・connected section' },
  { kanji: '公式', kana: 'こうしき', english: 'official' },
  { kanji: '仕組み', kana: 'しきみ', english: 'mechanism・how something works' },
  { kanji: '検証', kana: 'けんしょう', english: 'verification・validation・testing' },
  { kanji: '参考', kana: 'さんこう', english: 'reference・example' },
  { kanji: '担当', kana: 'たんとう', english: 'responsibility・taking charge' },
  { kanji: '言語', kana: 'げんご', english: 'language' },
  { kanji: '築きたい', kana: 'きずきたい', english: 'to build up' },
  { kanji: '熱い思い', kana: 'あついおもい', english: 'passion・enthusiasm' },
  { kanji: '上達', kana: 'じょうたつ', english: 'improvement・getting better' },
  { kanji: '物事', kana: 'ものごと', english: 'things・matters' },
  { kanji: '仕組み', kana: 'しきみ', english: 'mechanism・how something works' },
  { kanji: '論理', kana: 'ろんり', english: 'logic' },
  { kanji: '実際', kana: 'じっさい', english: 'actual situation' },
  { kanji: '生み出す', kana: 'うみだす', english: 'to create・to bring forth' },
  { kanji: 'やりがい', kana: 'やりがい', english: 'sense of fulfillment' },
  { kanji: '関係者', kana: 'かんけいしゃ', english: 'stakeholder' },
  { kanji: '仕様', kana: 'しよう', english: 'specification' },
  { kanji: '一部', kana: 'いちぶ', english: 'part' },
  { kanji: '認識', kana: 'にんしき', english: 'recognition・understanding' },
  { kanji: '認識合わせ', kana: 'にんしきあわせ', english: 'alignment of understanding' },
  { kanji: 'ずれ', kana: 'ずれ', english: 'gap・discrepancy' },
  { kanji: "直前", kana: "ちょくぜん", english: "just before" },
  { kanji: "段階", kana: "だんかい", english: "stage・phase" },
  { kanji: "以降", kana: "いこう", english: "from that point onward" },
  { kanji: "要件確認", kana: "ようけんかくにん", english: "requirement confirmation" },
  { kanji: "積極的に", kana: "せっきょくてきに", english: "proactively" },
  { kanji: "設ける", kana: "もうける", english: "to set up・to establish" },
  { kanji: "合意", kana: "ごうい", english: "agreement" },
  { kanji: "明確", kana: "めいかく", english: "clear・definite" },
  { kanji: "明確にする", kana: "めいかくにする", english: "to clarify" },
  { kanji: "技術面", kana: "ぎじゅつめん", english: "technical aspect" },
  { kanji: "全体", kana: "ぜんたい", english: "overall・whole" },
  { kanji: "取り組む", kana: "とりくむ", english: "to work on・to engage in" },
  { kanji: "短期間", kana: "たんきかん", english: "short period of time" },
  { kanji: "案件", kana: "あんけん", english: "project・case" },
  { kanji: "試行", kana: "しこう", english: "trial・experiment" },
  { kanji: "錯誤", kana: "さくご", english: "error・mistake" },
  { kanji: "試行錯誤", kana: "しこうさくご", english: "trial and error" },
  { kanji: "適応", kana: "てきおう", english: "adaptation" },
  { kanji: "柔軟", kana: "じゅうなん", english: "flexible" },
  { kanji: "柔軟性", kana: "じゅうなんせい", english: "flexibility" },
  { kanji: "抱え込む", kana: "かかえこむ", english: "to take on・to shoulder" },
  { kanji: "傾向", kana: "けいこう", english: "trend・inclination" },
  { kanji: "上司", kana: "じょうし", english: "supervisor・boss" },
  { kanji: "共有", kana: "きょうゆう", english: "sharing" },
  { kanji: "指摘", kana: "してき", english: "pointing out・criticism" },
  { kanji: "一定", kana: "いってい", english: "certain amount・fixed amount" },
  { kanji: "時間調査", kana: "じかんちょうさ", english: "time check" },
  { kanji: "相談", kana: "そうだん", english: "consultation" },
  { kanji: "徹底", kana: "てってい", english: "thoroughness" },
  { kanji: "影響", kana: "えいきょう", english: "influence" },
  { kanji: "与えられる", kana: "あたえられる", english: "to be given" },
  { kanji: "存在", kana: "そんざい", english: "existence" },
  { kanji: "向上", kana: "こうじょう", english: "improvement" },
  { kanji: "価値向上", kana: "かちこうじょう", english: "value improvement" },
  { kanji: "貢献", kana: "こうけん", english: "contribution" },
  { kanji: "業務", kana: "ぎょうむ", english: "business" },
  { kanji: "業務内容", kana: "ぎょうむないよう", english: "business content" },
  { kanji: "年収", kana: "ねんしゅう", english: "annual income" },
  { kanji: "条件", kana: "じょうけん", english: "conditions" },
  { kanji: "計算", kana: "けいさん", english: "calculation" },
  { kanji: '最大値', kana: 'さいだいち', english: 'maximum value' },
  { kanji: '時間効率', kana: 'じかんこうりつ', english: 'time efficiency' },

  // About the projects I worked on
  { kanji: '周辺機器', kana: 'しゅうへんきき', english: 'peripheral device' },
  { kanji: '印刷', kana: 'いんさつ', english: 'printing' },
  { kanji: '大規模', kana: 'だいきぼ', english: 'large-scale' },
  { kanji: '組み込む', kana: 'くみこむ', english: 'to integrate' },
  { kanji: '構築', kana: 'こうちく', english: 'construction・building' },
  { kanji: '役割', kana: 'やくわり', english: 'role' },
  { kanji: '連携', kana: 'れんけい', english: 'coordination' },
  { kanji: '工程', kana: 'こうてい', english: 'process' },
  { kanji: '詳細', kana: 'しょうさい', english: 'details' },
  { kanji: '単体', kana: 'たんたい', english: 'individual' },
  { kanji: '結合', kana: 'けつごう', english: 'integration' },
  { kanji: '割合', kana: 'わりあい', english: 'proportion・ratio' },
  { kanji: '公共', kana: 'こうきょう', english: 'public' },
  { kanji: '交通', kana: 'こうつう', english: 'traffic・transportation' },
  { kanji: '機関', kana: 'きかん', english: 'agency' },
  { kanji: '購入', kana: 'こうにゅう', english: 'purchase' },
  { kanji: '残高', kana: 'ざんだか', english: 'account balance' },
  { kanji: '乗車', kana: 'じょうしゃ', english: 'boarding' },
  { kanji: '降車', kana: 'こうしゃ', english: 'getting off' },
  // { kanji: '運賃', kana: 'うんちん', english: 'fare' },
  { kanji: '医療', kana: 'いりょう', english: 'medical care' },
  { kanji: '保険', kana: 'ほけん', english: 'insurance' },
  { kanji: '個人', kana: 'こじん', english: 'individual' },
  { kanji: '健康保険', kana: 'けんこうほけん', english: 'health insurance' },
  { kanji: '提供', kana: 'ていきょう', english: 'supply・offering' },
  { kanji: '受診', kana: 'じゅしん', english: 'medical examination' },
  { kanji: '検査', kana: 'けんさ', english: 'examination' },
  { kanji: '保険手続き', kana: 'ほけんてつづき', english: 'insurance procedures' },
  { kanji: '契約', kana: 'けいやく', english: 'contract' },
  { kanji: '診療', kana: 'しんりょう', english: 'medical treatment' },
  { kanji: '点検', kana: 'てんけん', english: 'inspection' },
  { kanji: '保守点検', kana: 'ほしゅうてんけん', english: 'preventive maintenance' },
  { kanji: '設備', kana: 'せつび', english: 'equipment・facilities' },
  { kanji: '作業員', kana: 'さぎょういん', english: 'operator' },
  { kanji: '対象', kana: 'たいしょう', english: 'target' },
  { kanji: '点検対象', kana: 'てんけんたいしょう', english: 'inspection target' },
  { kanji: '形式', kana: 'けいしき', english: 'form・format' },
  { kanji: '回答', kana: 'かいとう', english: 'answer' },
  { kanji: '位置', kana: 'いち', english: 'position' },
  { kanji: '接続', kana: 'せつぞく', english: 'connection' },
  { kanji: '保持', kana: 'ほじ', english: 'to maintain' },
  { kanji: '分析', kana: 'ぶんせき', english: 'analysis' },
  { kanji: '選定', kana: 'せんてい', english: 'selection' },
  { kanji: '技術選定', kana: 'ぎじゅつせんてい', english: 'technical selection' },
  { kanji: '一貫', kana: 'いっかん', english: 'consistency' },
  { kanji: '一貫する', kana: 'いっかんする', english: 'to be consistent' },
];