export const NEMOPHILA_MONSTERS: string[] = [
  `爆{ばく}音{おん}の世界火{ひ}花{ばな}散{ち}らして`,
  `夢よりハイな`,
  `突{つ}き刺{さ}すシャウトボイス`,
  `今から始まる`,
  `Rock'n Party Night`,
  `Boost カマし今{こ}宵{よい} KnockOut！！`,
  ``,
  `C'mon set the fire`,
  `Yeah! Love me do baby`,
  `C'mon let them burn out`,
  `to be shining like the stars!!`,
  ``,
  ``,
  `溢{あふ}れ出す光{こう}源{げん}イカす光{こう}景{けい}`,
  `巻{ま}き込む I'ma "LIVE MONSTER"`,
  `腰{こし}揺{ゆ}らして 髪{かみ}かきあげ踊{おど}り狂{くる}え`,
  `ただ見てるなら服を脱{ぬ}いで`,
  `MUSICでバカになれば`,
  `バイブスをアゲろ`,
  `Your new World Yeah!!`,
  `Keep it up!`,
  `Look up in the sky.`,
  ``,
  `ブレイクでキメよ理{り}論{ろん}はいらねぇ`,
  `まだまだ足りない最&高なTime`,
  `容{よう}赦{しゃ}ない熱{ねつ}量{りょう}`,
  `Fuck'n Hot Tonight.`,
  `朝までこのまま`,
  `Let's dance and party!!`,
  ``,
  ``,
  `はじけだす衝{しょう}動{どう}越{こ}える創{そう}造{ぞう}`,
  `シェイクして`,
  `You're "FLOOR MONSTER"`,
  `腕{うで}上{あ}げて 汗{あせ}で濡{ぬ}らして 遊{あそ}び狂{くる}え`,
  `Heavy級{きゅう}なヘドバン`,
  `目{め}立{だ}ってなんぼ`,
  `COOLにイイ波{なみ}乗{の}っていこ`,
  `欲{よく}望{ぼう}に舵{かじ}切{き}れ`,
  `Let's go wild Yeah!!`,
  `Feel so good!`,
  `You will be alright.`,
  ``,
  ``,
  `照らし出すSUNRISE`,
  `浴{あ}びてONE TIME`,
  `掲{かか}げる`,
  `We are "ROCK'N MONSTERS"`,
  `声{こえ}枯{か}らす笑い飛{と}ばして歌{うた}い狂{くる}え`,
  `ただ見てるなら 服を脱{ぬ}いで`,
  `MUSICでバカになれば`,
  `バイブスをアゲる`,
  `Your new World Yeah!!`,
  `Keep it up!`,
  `Look up in the sky`,
]