/**
 * Words that I did not know while watching 日本語の森 interview videos. 
 */
export const NOTE_WORDS: JLPTReview[] = [
  {
    kanji: "特定",
    kana: "とくてい",
    english: "specific・particular・designated",
    explanation: "Used to refer to something that is specifically identified or designated.",
    example: "{特定}の条件を満たす必要があります。\nYou need to meet specific conditions.",
  },
  {
    kanji: "技能",
    kana: "ぎのう",
    english: "skill・ability・technical skill",
    explanation: "Refers to the ability or skill to perform a task, often related to technical or specialized fields.",
    example: "特定{技能}を持つ労働者が求められています。\nWorkers with specific skills are in demand.",
  },
  {
    kanji: "すらすら",
    kana: "すらすら",
    english: "smoothly・fluently・easily",
    explanation: "Describes the ability to do something smoothly or without difficulty, often used in the context of speaking or writing.",
    example: "彼は日本語を{すらすら}話せます。\nHe can speak Japanese fluently.",
  },
  {
    kanji: "真似をする",
    kana: "まねをする",
    english: "to imitate・to mimic・to copy",
    explanation: "Refers to the act of copying or imitating someone's actions, behavior, or style.",
    example: "子供は親の{真似}をすることが多いです。\nChildren often imitate their parents.",
  },
  {
    kanji: "とにかく",
    kana: "とにかく",
    english: "anyway・in any case・at any rate",
    explanation: "Used to emphasize that something is true regardless of other factors or considerations.",
    example: "{とにかく}頑張ってください。\nAnyway, please do your best.",
  },
  {
    kanji: "模擬",
    kana: "もぎ",
    english: "mock・simulated・practice",
    explanation: "Refers to something that is a simulation or imitation of the real thing, often used in the context of exams or training.",
    example: "{模擬}試験を受けて、準備をしましょう。\nLet's take a mock exam to prepare.",
  },
  {
    kanji: "面接",
    kana: "めんせつ",
    english: "interview・meeting・face-to-face",
    explanation: "Refers to a formal meeting or interview, often for job applications or evaluations.",
    example: "模擬{面接}を行います。\nWe will conduct a mock interview.",
  },
  {
    kanji: "背景",
    kana: "はいけい",
    english: "background・setting・context",
    explanation: "Refers to the background or context of a situation, event, or story.",
    example: "この物語の{背景}を理解することが重要です。\nIt is important to understand the background of this story.",
  },
  {
    kanji: "服装",
    kana: "ふくそう",
    english: "clothing・attire・dress",
    explanation: "Refers to the way someone is dressed or their clothing style.",
    example: "面接には適切な{服装}で行くことが重要です。\nIt is important to go to the interview in appropriate attire.",
  },
  {
    kanji: "普段",
    kana: "ふだん",
    english: "usually・normally・ordinarily・habitually",
    explanation: "Refers to something that is done regularly or habitually in everyday life.",
    example: "{普段}の生活習慣を見直しましょう。\nLet's review our usual lifestyle habits.",
  },
  {
    kanji: "可能",
    kana: "かのう",
    english: "possible・feasible・capable",
    explanation: "Refers to something that can be done or achieved.",
    example: "この計画は実行{可能}です。\nThis plan is feasible.",
  },
  {
    kanji: "相談",
    kana: "そうだん",
    english: "consultation・discussion・advice",
    explanation: "Refers to the act of seeking advice or discussing something with someone.",
    example: "問題があれば、先生に{相談}してください。\nIf you have any problems, please consult your teacher.",
  },
  {
    kanji: "情報",
    kana: "じょうほう",
    english: "information・data・news",
    explanation: "Refers to knowledge or data about a particular subject or situation.",
    example: "最新の{情報}を入手しました。\nI have obtained the latest information.",
  },
  {
    kanji: "検索",
    kana: "けんさく",
    english: "search・lookup・query",
    explanation: "Refers to the act of searching for information, often using a computer or database.",
    example: "インターネットで{検索}してみてください。\nPlease try searching on the internet.",
  },
  {
    kanji: "求人",
    kana: "きゅうじん",
    english: "job offer・recruitment・job vacancy",
    explanation: "Refers to the act of seeking employees or job openings.",
    example: "{求人}情報をチェックしましょう。\nLet's check the job vacancy information.",
  },
  {
    kanji: "響く",
    kana: "ひびく",
    english: "to echo・to resound・to have an impact",
    explanation: "Refers to a sound that reverberates or an action that has a significant effect.",
    example: "彼の言葉は心に{響}きました。\nHis words resonated in my heart.",
  },
  {
    kanji: "喜ぶ",
    kana: "よろこぶ",
    english: "to be delighted・to rejoice・to be glad",
    explanation: "Refers to the feeling of happiness or pleasure in response to something positive.",
    example: "彼女はプレゼントをもらって{喜}びました。\nShe was delighted to receive the present.",
  }
];