const M2_KANJI: Record<number, TKanjiM2> = {
  421: {
    id: 421,
    kanji: "存",
    kun: [],
    on: ["ソン", "ゾン"],
    meanings: ["exist", "be aware of", "believe"],
    words: [
      { 
        word: "保存（する）",
        reading: "ほぞん（する）",
        meaning: "Preservation・to preserve",
        exampleSentenceRuby: "念{ねん}のためデータは必{かなら}ず複{ふく}数{すう}、保{ほ}存{ぞん}してください。",
      },
      { 
        word: "生存（する）",
        reading: "せいぞん（する）",
        meaning: "Existence・survival",
        exampleSentenceRuby: "寂{さび}しい生{せい}存{ぞん}競{きょう}争{そう}、食{く}うか食{く}われるかの弱{じゃく}肉{にく}強{きょう}食{しょく}の世{せ}界{かい}です。",
      },
      { 
        word: "温存（する）",
        reading: "おんぞん（する）",
        meaning: "Preserve・retain・Conservation",
        exampleSentenceRuby: "現{げん}在{ざい}の景{けい}気{き}対{たい}策{さく}では、既{き}得{とく}権{けん}益{えき}を温{おん}存{ぞん}されることになる。",
      },
    ],
    otherWords: [
      { word: "存分(に)", reading: "ぞんぶん(に)", meaning: "to one's heart's content" },
      { word: "存じます", reading: "ぞんじます", meaning: "to know (humble)" },
      { word: "存亡", reading: "そんぼう", meaning: "existence and non-existence" },
      { word: "所存", reading: "しょぞん", meaning: "one's intention" },
      { word: "一存", reading: "いちぞん", meaning: "one's decision" },
    ],
  },
  422: {
    id: 422,
    kanji: "去",
    kun: ["さ"],
    on: ["キョ", "コ"],
    meanings: ["leave", "past", "eliminate"],
    words: [
      { 
        word: "過去",
        reading: "かこ",
        meaning: "past",
        exampleSentenceRuby: "",
      },
      { 
        word: "去る",
        reading: "さる",
        meaning: "to leave・last",
        exampleSentenceRuby: "",
      },
      { 
        word: "撤去（する）",
        reading: "てっきょ（する）",
        meaning: "Withdrawal・to remove",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "立ち去る", reading: "たちさる", meaning: "to leave" },
      { word: "除去（する）", reading: "じょきょ（する）", meaning: "removal・to remove" },
      { word: "退去（する）", reading: "たいきょ（する）", meaning: "withdrawal・to leave" },
      { word: "置き去り（にする）", reading: "おきざり（にする）", meaning: "to leave behind" },
      { word: "消去（する）", reading: "しょうきょ（する）", meaning: "deletion・to delete" },
    ],
  },
  423: {
    id: 423,
    kanji: "庁",
    kun: [],
    on: ["チョウ"],
    meanings: ["government office", "agency"],
    words: [
      { 
        word: "〜庁",
        reading: "〜ちょう",
        meaning: "~agency/office",
        exampleSentenceRuby: "",
      },
      { 
        word: "気象庁",
        reading: "きしょうちょう",
        meaning: "Meteorological Agency",
        exampleSentenceRuby: "",
      },
      { 
        word: "警視庁",
        reading: "けいしちょう",
        meaning: "Metropolitan Police Department",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "警察庁", reading: "けいさつちょう", meaning: "National Police Agency" },
      { word: "海上保安庁", reading: "かいじょうほあんちょう", meaning: "Japan Coast Guard" },
      { word: "検察庁", reading: "けんさつちょう", meaning: "Public Prosecutor's Office" },
      { word: "特許庁", reading: "とっきょちょう", meaning: "Japan Patent Office" },
      { word: "官公庁", reading: "かんこうちょう", meaning: "government office" },
    ],
  },
  424: {
    id: 424,
    kanji: "幸",
    kun: ["しあわ","さいわ", "さち"],
    on: ["コウ"],
    meanings: ["happiness", "blessing", "fortune"],
    words: [
      { 
        word: "幸い",
        reading: "さいわい",
        meaning: "happiness・fortunately",
        exampleSentenceRuby: "",
      },
      { 
        word: "幸運(な）",
        reading: "こううん(な）",
        meaning: "Lucky・Good fortunate",
        exampleSentenceRuby: "",
      },
      { 
        word: "幸いする",
        reading: "さいわいする",
        meaning: "to be favored by",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "幸せ", reading: "しあわせ", meaning: "happiness" },
      { word: "不幸（な）", reading: "ふこう（な）", meaning: "unfortunate" },
      { word: "幸福（な）", reading: "こうふく（な）", meaning: "happy" },
      { word: "幸", reading: "さち", meaning: "happiness" },
      { word: "海の幸", reading: "うみのさち", meaning: "seafood" },
      { word: "山の幸", reading: "やまのさち", meaning: "mountain delicacies" },
    ],
  },
  425: {
    id: 425,
    kanji: "昭",
    kun: [],
    on: ["ショウ"],
    meanings: ["bright", "clear"],
    words: [
      { 
        word: "昭和",
        reading: "しょうわ",
        meaning: "Shōwa era",
        exampleSentenceRuby: "1989年{年}に、64年{年}で昭{しょう}和{わ}が終{お}わった。",
      },
    ],
    otherWords: [
      { word: "昭くさん", reading: "あきらさん", meaning: "人の名前" },
      { word: "昭子くさん", reading: "しょうこさん・あきこさん", meaning: "人の名前" },
      { word: "昭夫さん", reading: "あきおさん", meaning: "人の名前" },
    ],
  },
  426: {
    id: 426,
    kanji: "雨",
    kun: ["あめ", "あま"],
    on: ["ウ"],
    meanings: ["rain"],
    words: [
      { 
        word: "大雨",
        reading: "おおあめ",
        meaning: "heavy rain",
        exampleSentenceRuby: "九{きゅう}州{しゅう}地{ち}方{ほう}で大{おお}雨{あめ}が降{ふ}り、総{ぞう}雨{うり}量{よう}は多{おお}い所{ところ}で400ミリを超{こ}えた。",
      },
      { 
        word: "梅雨",
        reading: "つゆ・ばいう",
        meaning: "rainy season",
        exampleSentenceRuby: "太{たい}平{へい}洋{よう}高{こう}気{き}圧{あつ}が梅{ばい}雨{う}前{ぜん}線{せん}を北{きた}へ押{お}し上{あ}げ、梅{つ}雨{ゆ}が明{あ}けた。",
      },
      { 
        word: "雨天",
        reading: "うてん",
        meaning: "rainy day",
        exampleSentenceRuby: "10月に行われる野{や}外{がい}コンサートは雨{う}天{てん}決{けっ}行{こう}です。",
      },
    ],
    otherWords: [
      { word: "梅雨入り", reading: "つゆいり", meaning: "start of the rainy season" },
      { word: "梅雨明け", reading: "つゆあけ", meaning: "end of the rainy season" },
      { word: "雨水", reading: "あまみず", meaning: "rainwater" },
      { word: "長雨", reading: "ながあめ", meaning: "long rain" },
      { word: "小雨", reading: "こさめ", meaning: "light rain" },
      { word: "暴風雨", reading: "ぼうふうう", meaning: "stormy rain" },
    ],
  },
  427: {
    id: 427,
    kanji: "過",
    kun: ["す", "あやま"],
    on: ["カ"],
    meanings: ["exceed", "go beyond", "error", "mistake"],
    words: [
      { 
        word: "過ぎる",
        reading: "すぎる",
        meaning: "to exceed・pass・too much",
        exampleSentenceRuby: "ゲームのし過{す}ぎで脳{のう}が壊{こわ}れる、と心{しん}配{ぱい}し過{す}ぎる人もいる。",
      },
      { 
        word: "過ごす",
        reading: "すごす",
        meaning: "to spend (time)・pass",
        exampleSentenceRuby: "皆{みな}様{さま}、いかがお過{す}ごしでいらっしゃいますか。",
      },
      { 
        word: "見過ごす",
        reading: "みすごす",
        meaning: "to overlook・miss",
        exampleSentenceRuby: "責{せき}任{にん}上{じょう}、部{ぶ}長{ちょう}は部{ぶ}下{か}の過{あやま}ちを見{み}過{す}ごすわけにはいかない。",
      },
    ],
    otherWords: [
      { word: "通過（する）", reading: "つうか（する）", meaning: "to pass (through)" },
      { word: "通り過ぎる", reading: "とおりすぎる", meaning: "to pass by" },
      { word: "行き過ぎる", reading: "いきすぎる", meaning: "to go too far" },
      { word: "過熱（する）", reading: "かねつ（する）", meaning: "to overheat" },
      { word: "超過（する）", reading: "ちょうか（する）", meaning: "to exceed" },
      { word: "過ち", reading: "あやまち", meaning: "mistake" },
    ],
  },
  428: {
    id: 428,
    kanji: "系",
    kun: [],
    on: ["ケイ"],
    meanings: ["lineage", "system", "group"],
    words: [
      { 
        word: "日系",
        reading: "にっけい",
        meaning: "Japanese descent",
        exampleSentenceRuby: "国{くに}で日{にっ}系{けい}の企{き}業{ぎょう}に勤{つと}めていました。",
      },
      { 
        word: "生態系",
        reading: "せいたいけい",
        meaning: "ecological system",
        exampleSentenceRuby: "人{にん}間{げん}の活{かつ}動{どう}が生{せい}態{たい}系{けい}を破{は}壊{かい}し、他{た}の生{せい}物{ぶつ}を絶{ぜつ}滅{めつ}に追{お}いやっている。",
      },
      { 
        word: "体系",
        reading: "たいけい",
        meaning: "system・organization",
        exampleSentenceRuby: " このサービスを利{り}用{よう}する前に、料{りょう}金{きん}体{たい}系{けい}をよく見ておいた。",
      },
    ],
    otherWords: [
      { word: "~系", reading: "~けい", meaning: "related to ~" },
      { word: "系列", reading: "けいれつ", meaning: "series" },
      { word: "直系", reading: "ちょっけい", meaning: "direct lineage" },
      { word: "家系", reading: "かけい", meaning: "family lineage" },
      { word: "理系", reading: "りけい", meaning: "science (related)"},
      { word: "文系", reading: "ぶんけい", meaning: "literature (related)"},
    ],
  },
  429: {
    id: 429,
    kanji: "談",
    kun: [],
    on: ["ダン"],
    meanings: ["discuss", "talk"],
    words: [
      { 
        word: "冗談",
        reading: "じょうだん",
        meaning: "joke",
        exampleSentenceRuby: "真{ま}面{じ}目{め}な話{はなし}をしている時に冗{じょう}談{だん}を言わないでください。",
      },
      { 
        word: "対談",
        reading: "たいだん",
        meaning: "Talk・conversation",
        exampleSentenceRuby: "A党とB党の党{とう}首{しゅ}が対{たい}談{だん}し、両{りょう}党{とう}の統{とう}合{ごう}について語{かた}った。",
      },
      { 
        word: "談合（する）",
        reading: "だんごう（する）",
        meaning: "consultation",
        exampleSentenceRuby: "公{こう}共{きょう}事{じ}業{ぎょう}の入{にゅう}札{さつ}に関{かん}して3{さん}社{しゃ}が談{だん}合{ごう}していた。",
      },
    ],
    otherWords: [
      { word: "会談（する）", reading: "かいだん（する）", meaning: "meeting・talk" },
      { word: "商談（する）", reading: "しょうだん（する）", meaning: "business negotiation" },
      { word: "面談（する）", reading: "めんだん（する）", meaning: "interview" },
      { word: "雑談（する）", reading: "ざつだん（する）", meaning: "casual talk" },
      { word: "示談", reading: "じだん", meaning: "settlement (out of court)" },
    ],
  },
  430: {
    id: 430,
    kanji: "等",
    kun: ["ひと", "など"],
    on: ["トウ"],
    meanings: ["etc.", "class", "equal", "grade"],
    words: [
      { 
        word: "等しい",
        reading: "ひとしい",
        meaning: "equal・equivalent",
        exampleSentenceRuby: "仕{し}事{ごと}は部{ぶ}下{か}に丸{まる}投{な}げし、課{か}長{ちょう}は何{なに}もしていないに等{ひと}しい。",
      },
      { 
        word: "不平等(な）",
        reading: "ふびょうどう（な）",
        meaning: "inequality・unfair",
        exampleSentenceRuby: "グローバリゼーションは自{じ}由{ゆう}化{か}の反{はん}面{めん}で不{ふ}平{びょう}等{どう}と貧{ひん}困{こん}を助{じょ}長{ちょう}している。",
      },
      { 
        word: "対等(な）",
        reading: "たいとう（な）",
        meaning: "on equal terms",
        exampleSentenceRuby: "本{ほん}来{らい}、労{ろう}働{どう}条{じょう}件{けん}は労{ろう}使{し}が対{たい}等{とう}な立{たち}場{ば}で決{き}めるべきものである。",
      },
    ],
    otherWords: [
      { word: "等分（する）", reading: "とうぶん（する）", meaning: "division (to divide equally)" },
      { word: "等・～等", reading: "とう・～とう", meaning: "etc." },
      { word: "高等（な）", reading: "こうとう（な）", meaning: "advanced・high class" },
      { word: "同等（な・の）", reading: "どうとう（な・の）", meaning: "equal (to)" },
      { word: "上等（な）", reading: "じょうとう（な）", meaning: "superior・high quality" },
    ],
  },
  431: {
    id: 431,
    kanji: "防",
    kun: ["ふせ"],
    on: ["ボウ"],
    meanings: ["defend", "protect", "prevent"],
    words: [
      { 
        word: "防ぐ",
        reading: "ふせぐ",
        meaning: "to prevent・guard",
        exampleSentenceRuby: "パソコンのウィルス感{かん}染{せん}を防{ふせ}ぐために、対{たい}策{さく}用{よう}のソフトを買{か}った。",
      },
      { 
        word: "防災",
        reading: "ぼうさい",
        meaning: "disaster prevention",
        exampleSentenceRuby: "毎{まい}年{とし}9月{がつ}1{つい}日{たち}に防{ぼう}災{さい}訓{くん}練{れん}をして、地{じ}震{しん}に備{そな}えている。",
      },
      { 
        word: "予防（する）",
        reading: "よぼう（する）",
        meaning: "Prevent・Guard",
        exampleSentenceRuby: "インフルエンザを予{よ}防{ぼう}するためワクチン注{ちゅう}射{しゃ}をした。",
      },
    ],
    otherWords: [
      { word: "防衛（する）", reading: "ぼうえい（する）", meaning: "defense" },
      { word: "国防", reading: "こくぼう", meaning: "national defense" },
      { word: "防御（する）", reading: "ぼうぎょ（する）", meaning: "defense" },
      { word: "防犯", reading: "ぼうはん", meaning: "crime prevention" },
      { word: "防火", reading: "ぼうか", meaning: "fire prevention" },
    ],
  },
  432: {
    id: 432,
    kanji: "賞",
    kun: [],
    on: ["ショウ"],
    meanings: ["prize", "reward", "praise"],
    words: [
      { 
        word: "~賞",
        reading: "~しょう",
        meaning: "prize・reward",
        exampleSentenceRuby: "田{た}中{なか}氏{し}がノーベル化{か}学{がく}賞{しょう}を受{じゅ}賞{しょう}した。",
      },
      { 
        word: "賞金",
        reading: "しょうきん",
        meaning: "prize money",
        exampleSentenceRuby: "授{じゅ}賞{しょう}式{しき}でメダルと賞{しょう}状{じょう}と賞{しょう}金{きん}の小{こ}切{ぎっ}手{て}を受{う}け取{と}った。",
      },
      { 
        word: "鑑賞（する）",
        reading: "かんしょう（する）",
        meaning: "appreciation・enjoyment",
        exampleSentenceRuby: "趣{しゅ}味{み}は音{おん}楽{がく}鑑{かん}賞{しょう}です。",
      },
    ],
    otherWords: [
      { word: "入賞（する）", reading: "にゅうしょう（する）", meaning: "to win a prize" },
      { word: "大賞", reading: "たいしょう", meaning: "grand prize" },
      { word: "賞品", reading: "しょうひん", meaning: "prize" },
      { word: "観賞（する）", reading: "かんしょう（する）", meaning: "appreciation・enjoyment" },
      { word: "賞味（する）", reading: "しょうみ（する）", meaning: "to savor・to appreciate the flavor" },
    ],
  },
  433: {
    id: 433,
    kanji: "製",
    kun: [],
    on: ["セイ"],
    meanings: ["manufacture", "make"],
    words: [
      { 
        word: "製造（する）",
        reading: "せいぞう（する）",
        meaning: "manufacture・produce",
        exampleSentenceRuby: "当{とう}社{しゃ}は医{いや}薬{く}品{ひん}を製{せい}造{ぞう}する製{せい}薬{やく}会{かい}社{しゃ}です。",
      },
      { 
        word: "製作（する）",
        reading: "せいさく（する）",
        meaning: "make・produce",
        exampleSentenceRuby: "自分でデザインして、椅{い}子{す}を製{せい}作{さく}した。",
      },
      { 
        word: "～製",
        reading: "～せい",
        meaning: "made in～・made of ～",
        exampleSentenceRuby: "このプリンターはフィリピン製{せい}です。コピー用{よう}紙{し}はタイ製{せい}です。",
      },
    ],
    otherWords: [
      { word: "特製", reading: "とくせい", meaning: "special edition" },
      { word: "木製", reading: "もくせい", meaning: "wooden" },
      { word: "精製（する）", reading: "せいせい（する）", meaning: "refinement" },
      { word: "製法", reading: "せいほう", meaning: "manufacturing method" },
      { word: "作製（する）", reading: "さくせい（する）", meaning: "to create・to produce" },
    ],
  },
  434: {
    id: 434,
    kanji: "型",
    kun: ["かた"],
    on: ["ケイ"],
    meanings: ["model", "type", "mold", "pattern"],
    words: [
      { 
        word: "新型",
        reading: "しんがた",
        meaning: "new style・new model",
        exampleSentenceRuby: "（株{かぶしきがいしゃ}）T{ティー}自動車が、新{しん}型{がた}7{しち}人{にん}乗{の}り乗{じょう}用{よう}車{しゃ}を発{はつ}売{ばい}した。",
      },
      { 
        word: "模型",
        reading: "もけい",
        meaning: "model・miniature",
        exampleSentenceRuby: "趣{しゅ}味{み}は列{れっ}車{しゃ}の模{も}型{けい}作{づく}りです。",
      },
      { 
        word: "典型(的な）",
        reading: "てんけい(てきな）",
        meaning: "typical",
        exampleSentenceRuby: "典{てん}型{けい}的{てき}な詐{さ}欺{ぎ}の手{て}口{ぐち}を公{こう}表{ひょう}し、警{けい}察{さつ}が注意を促{うなが}した。",
      },
    ],
    otherWords: [
      { word: "原型", reading: "げんけい", meaning: "prototype" },
      { word: "同型", reading: "どうけい", meaning: "same type" },
      { word: "類型", reading: "るいけい", meaning: "type・category" },
      { word: "定型", reading: "ていけい", meaning: "regular pattern" },
      { word: "小型", reading: "こがた", meaning: "small size" },
      { word: "中型", reading: "ちゅうがた", meaning: "medium size" },
      { word: "大型", reading: "おおがた", meaning: "large size" },
    ],
  },
  435: {
    id: 435,
    kanji: "顔",
    kun: ["かお"],
    on: ["ガン"],
    meanings: ["face", "expression"],
    words: [
      { 
        word: "顔",
        reading: "かお",
        meaning: "face",
        exampleSentenceRuby: "時間があったらぜひ部{ぶ}室{しつ}に顔を出してください。",
      },
      { 
        word: "笑顔",
        reading: "えがお",
        meaning: "smiling face",
        exampleSentenceRuby: "美顔は周{まわ}りの人も幸せにする。",
      },
      { 
        word: "いい顔",
        reading: "いいかお",
        meaning: "friendly attitude",
        exampleSentenceRuby: "あの人は誰{だれ}にでもいい顔をする人だ。内{ない}心{しん}は分からない。",
      },
    ],
    otherWords: [
      { word: "素顔", reading: "すがお", meaning: "bare face" },
      { word: "顔合わせ（する）", reading: "かおあわせ（する）", meaning: "face-to-face meeting" },
      { word: "新顔", reading: "しんがお", meaning: "new face" },
      { word: "横顔", reading: "よこがお", meaning: "profile (face)" },
      { word: "顔面", reading: "がんめん", meaning: "face (surface)" },
    ],
  },
}

export default M2_KANJI;