const M2_KANJI: Record<number, TKanjiM2> = {
  426: {
    id: 426,
    kanji: "雨",
    kun: ["あめ", "あま"],
    on: ["ウ"],
    meanings: ["rain"],
    words: [
      { 
        word: "大雨",
        reading: "おおあめ",
        meaning: "heavy rain",
        exampleSentenceRuby: "九{きゅう}州{しゅう}地{ち}方{ほう}で大{おお}雨{あめ}が降{ふ}り、総{ぞう}雨{うり}量{よう}は多{おお}い所{ところ}で400ミリを超{こ}えた。",
      },
      { 
        word: "梅雨",
        reading: "つゆ・ばいう",
        meaning: "rainy season",
        exampleSentenceRuby: "太{たい}平{へい}洋{よう}高{こう}気{き}圧{あつ}が梅{ばい}雨{う}前{ぜん}線{せん}を北{きた}へ押{お}し上{あ}げ、梅{つ}雨{ゆ}が明{あ}けた。",
      },
      { 
        word: "雨天",
        reading: "うてん",
        meaning: "rainy day",
        exampleSentenceRuby: "10月に行われる野{や}外{がい}コンサートは雨{う}天{てん}決{けっ}行{こう}です。",
      },
    ],
    otherWords: [
      { word: "梅雨入り", reading: "つゆいり", meaning: "start of the rainy season" },
      { word: "梅雨明け", reading: "つゆあけ", meaning: "end of the rainy season" },
      { word: "雨水", reading: "あまみず", meaning: "rainwater" },
      { word: "長雨", reading: "ながあめ", meaning: "long rain" },
      { word: "小雨", reading: "こさめ", meaning: "light rain" },
      { word: "暴風雨", reading: "ぼうふうう", meaning: "stormy rain" },
    ],
  },
  427: {
    id: 427,
    kanji: "過",
    kun: ["す", "あやま"],
    on: ["カ"],
    meanings: ["exceed", "go beyond", "error", "mistake"],
    words: [
      { 
        word: "過ぎる",
        reading: "すぎる",
        meaning: "to exceed・pass・too much",
        exampleSentenceRuby: "ゲームのし過{す}ぎで脳{のう}が壊{こわ}れる、と心{しん}配{ぱい}し過{す}ぎる人もいる。",
      },
      { 
        word: "過ごす",
        reading: "すごす",
        meaning: "to spend (time)・pass",
        exampleSentenceRuby: "皆{みな}様{さま}、いかがお過{す}ごしでいらっしゃいますか。",
      },
      { 
        word: "見過ごす",
        reading: "みすごす",
        meaning: "to overlook・miss",
        exampleSentenceRuby: "責{せき}任{にん}上{じょう}、部{ぶ}長{ちょう}は部{ぶ}下{か}の過{あやま}ちを見{み}過{す}ごすわけにはいかない。",
      },
    ],
    otherWords: [
      { word: "通過（する）", reading: "つうか（する）", meaning: "to pass (through)" },
      { word: "通り過ぎる", reading: "とおりすぎる", meaning: "to pass by" },
      { word: "行き過ぎる", reading: "いきすぎる", meaning: "to go too far" },
      { word: "過熱（する）", reading: "かねつ（する）", meaning: "to overheat" },
      { word: "超過（する）", reading: "ちょうか（する）", meaning: "to exceed" },
      { word: "過ち", reading: "あやまち", meaning: "mistake" },
    ],
  },
  428: {
    id: 428,
    kanji: "系",
    kun: [],
    on: ["ケイ"],
    meanings: ["lineage", "system", "group"],
    words: [
      { 
        word: "日系",
        reading: "にっけい",
        meaning: "Japanese descent",
        exampleSentenceRuby: "国{くに}で日{にっ}系{けい}の企{き}業{ぎょう}に勤{つと}めていました。",
      },
      { 
        word: "生態系",
        reading: "せいたいけい",
        meaning: "ecological system",
        exampleSentenceRuby: "人{にん}間{げん}の活{かつ}動{どう}が生{せい}態{たい}系{けい}を破{は}壊{かい}し、他{た}の生{せい}物{ぶつ}を絶{ぜつ}滅{めつ}に追{お}いやっている。",
      },
      { 
        word: "体系",
        reading: "たいけい",
        meaning: "system・organization",
        exampleSentenceRuby: " このサービスを利{り}用{よう}する前に、料{りょう}金{きん}体{たい}系{けい}をよく見ておいた。",
      },
    ],
    otherWords: [
      { word: "~系", reading: "~けい", meaning: "related to ~" },
      { word: "系列", reading: "けいれつ", meaning: "series" },
      { word: "直系", reading: "ちょっけい", meaning: "direct lineage" },
      { word: "家系", reading: "かけい", meaning: "family lineage" },
      { word: "理系", reading: "りけい", meaning: "science (related)"},
      { word: "文系", reading: "ぶんけい", meaning: "literature (related)"},
    ],
  },
  429: {
    id: 429,
    kanji: "談",
    kun: [],
    on: ["ダン"],
    meanings: ["discuss", "talk"],
    words: [
      { 
        word: "冗談",
        reading: "じょうだん",
        meaning: "joke",
        exampleSentenceRuby: "真{ま}面{じ}目{め}な話{はなし}をしている時に冗{じょう}談{だん}を言わないでください。",
      },
      { 
        word: "対談",
        reading: "たいだん",
        meaning: "Talk・conversation",
        exampleSentenceRuby: "A党とB党の党{とう}首{しゅ}が対{たい}談{だん}し、両{りょう}党{とう}の統{とう}合{ごう}について語{かた}った。",
      },
      { 
        word: "談合（する）",
        reading: "だんごう（する）",
        meaning: "consultation",
        exampleSentenceRuby: "公{こう}共{きょう}事{じ}業{ぎょう}の入{にゅう}札{さつ}に関{かん}して3{さん}社{しゃ}が談{だん}合{ごう}していた。",
      },
    ],
    otherWords: [
      { word: "会談（する）", reading: "かいだん（する）", meaning: "meeting・talk" },
      { word: "商談（する）", reading: "しょうだん（する）", meaning: "business negotiation" },
      { word: "面談（する）", reading: "めんだん（する）", meaning: "interview" },
      { word: "雑談（する）", reading: "ざつだん（する）", meaning: "casual talk" },
      { word: "示談", reading: "じだん", meaning: "settlement (out of court)" },
    ],
  },
  430: {
    id: 430,
    kanji: "等",
    kun: ["ひと", "など"],
    on: ["トウ"],
    meanings: ["etc.", "class", "equal", "grade"],
    words: [
      { 
        word: "等しい",
        reading: "ひとしい",
        meaning: "equal・equivalent",
        exampleSentenceRuby: "仕{し}事{ごと}は部{ぶ}下{か}に丸{まる}投{な}げし、課{か}長{ちょう}は何{なに}もしていないに等{ひと}しい。",
      },
      { 
        word: "不平等(な）",
        reading: "ふびょうどう（な）",
        meaning: "inequality・unfair",
        exampleSentenceRuby: "グローバリゼーションは自{じ}由{ゆう}化{か}の反{はん}面{めん}で不{ふ}平{びょう}等{どう}と貧{ひん}困{こん}を助{じょ}長{ちょう}している。",
      },
      { 
        word: "対等(な）",
        reading: "たいとう（な）",
        meaning: "on equal terms",
        exampleSentenceRuby: "本{ほん}来{らい}、労{ろう}働{どう}条{じょう}件{けん}は労{ろう}使{し}が対{たい}等{とう}な立{たち}場{ば}で決{き}めるべきものである。",
      },
    ],
    otherWords: [
      { word: "等分（する）", reading: "とうぶん（する）", meaning: "division (to divide equally)" },
      { word: "等・～等", reading: "とう・～とう", meaning: "etc." },
      { word: "高等（な）", reading: "こうとう（な）", meaning: "advanced・high class" },
      { word: "同等（な・の）", reading: "どうとう（な・の）", meaning: "equal (to)" },
      { word: "上等（な）", reading: "じょうとう（な）", meaning: "superior・high quality" },
    ],
  },
}

export default M2_KANJI;