const M2_KANJI: Record<number, TKanjiM2> = {
  416: {
    id: 416,
    kanji: "丸",
    kun: ["まる"],
    on: ["ガン"],
    meanings: ["circle", "round", "full"],
    words: [
      { 
        word: "丸",
        reading: "まる",
        meaning: "Circle・round",
        exampleSentenceRuby: "正しいものには丸を、間違っているものにはバツをつけなさい。",
      },
      { 
        word: "丸める",
        reading: "まるめる",
        meaning: "to roll up・to make round",
        exampleSentenceRuby: "大切な書{しょ}類{るい}を誤{あやま}って、くしゃくしゃに丸めてゴミ箱{ばこ}に捨ててしまった。",
      },
      { 
        word: "丸ごと",
        reading: "まるごと",
        meaning: "Whole・entirely",
        exampleSentenceRuby: "ワニが大きい口で魚を丸ごと飲み込んだ。",
      },
    ],
    otherWords: [
      { word: "丸い［円い］", reading: "まるい", meaning: "round" },
      { word: "丸み［円み］", reading: "まるみ", meaning: "roundness" },
      { word: "丸顔", reading: "まるがお", meaning: "round face" },
      { word: "丸々", reading: "まるまる", meaning: "entirely" },
      { word: "真ん丸（いな）", reading: "まんまる", meaning: "perfectly round" },
    ],
  },
  417: {
    id: 417,
    kanji: "失",
    kun: ["うしな"],
    on: ["シツ", "シッ"],
    meanings: ["lose", "mistake", "disappoint"],
    words: [
      { 
        word: "失う",
        reading: "うしなう",
        meaning: "to lose",
        exampleSentenceRuby: "一度失った信{しん}用{よう}を取{とり}り戻{もど}すのは容{よう}易{い}ではない。",
      },
      { 
        word: "失敗（する）",
        reading: "しっぱい（する）",
        meaning: "Failure・to fail",
        exampleSentenceRuby: "失敗は成{せい}功{こう}のもと、どんな実{じっ}験{けん}もデータは残{のこ}しておいた方がいい。",
      },
      { 
        word: "失業（する）",
        reading: "しつぎょう（する）",
        meaning: "Unemployment・to become unemployed",
        exampleSentenceRuby: "企{き}業{ぎょう}の社員が失業した場合、失業保{ほ}険{けん}の給{きゅう}付{ふ}が受けられる。",
      },
    ],
    otherWords: [
      { word: "失礼（な・する）", reading: "しつれい（な・する）", meaning: "rudeness・to be rude" },
      { word: "失点", reading: "しってん", meaning: "to lose points" },
      { word: "過失", reading: "かしつ", meaning: "error・mistake" },
      { word: "見失う", reading: "みうしなう", meaning: "to lose sight of" },
      { word: "失格（する）", reading: "しっかく（する）", meaning: "disqualification・to be disqualified" },
    ],
  },
  418: {
    id: 418,
    kanji: "健",
    kun: ["すこ"],
    on: ["ケン"],
    meanings: ["healthy", "strength"],
    words: [
      { 
        word: "健康（な）",
        reading: "けんこう（な）",
        meaning: "Health・healthy",
        exampleSentenceRuby: "健康な身{しん}体{たい}を維{い}持{じ}するため、毎日の生活習{しゅう}慣{かん}に気をつける。",
      },
      { 
        word: "健全（な）",
        reading: "けんぜん（な）",
        meaning: "Sound・healthy",
        exampleSentenceRuby: "地{ち}域{いき}社会全体で青{せい}少{しょう}年{ねん}の健全な育{いく}成{せい}を支{し}援{えん}する。",
      },
      { 
        word: "健闘（する）",
        reading: "けんとう（する）",
        meaning: "Strenuous efforts・to do one's best",
        exampleSentenceRuby: "期末テスト、頑張ってください。皆さんの健闘を祈{いの}ります。",
      },
    ],
    otherWords: [
      { word: "保健所", reading: "ほけんじょ", meaning: "health center" },
      { word: "健康保険", reading: "けんこうほけん", meaning: "health insurance" },
      { word: "健在（な）", reading: "けんざい（な）", meaning: "in good health" },
      { word: "穏健（な）", reading: "おんけん（な）", meaning: "moderate" },
      { word: "健やか（な）", reading: "すこやか（な）", meaning: "healthy" },
    ],
  },
  419: {
    id: 419,
    kanji: "助",
    kun: ["たす"],
    on: ["ジョ"],
    meanings: ["help", "assist"],
    words: [
      { 
        word: "助ける",
        reading: "たすける",
        meaning: "Help・save・rescue",
        exampleSentenceRuby: "日本語が分からなくて困っている私を見て、友達が助けてくれた。",
      },
      { 
        word: "助かる",
        reading: "たすかる",
        meaning: "to be saved・to be helped・be helpful",
        exampleSentenceRuby: "消{しょう}防{ぼう}隊{たい}員{いん}が燃える家から子供を救{きゅう}助{じょ}し、幼{おさな}い命{いのち}が助かった。",
      },
      { 
        word: "助長（する）",
        reading: "じょちょう（する）",
        meaning: "Promote・foment",
        exampleSentenceRuby: "報{ほう}道{どう}がかえって犯{はん}行{こう}を助{じょ}長{ちょう}するという危{き}険{けん}性{せい}もある。",
      },
    ],
    otherWords: [
      { word: "手助け（する）", reading: "てだすけ（する）", meaning: "to help" },
      { word: "補助（する）", reading: "ほじょ（する）", meaning: "to assist" },
      { word: "救助（する）", reading: "きゅうじょ（する）", meaning: "to rescue" },
      { word: "助手", reading: "じょしゅ", meaning: "assistant" },
      { word: "助言（する）", reading: "じょげん（する）", meaning: "to advise" },
    ],
  },
  420: {
    id: 420,
    kanji: "務",
    kun: ["つと"],
    on: ["ム"],
    meanings: ["duty", "task"],
    words: [
      { 
        word: "務め・務める",
        reading: "つとめ・つとめる",
        meaning: "Duty・to serve",
        exampleSentenceRuby: "司会を務めます、伊{い}藤{とう}です。よろしくお願いします。",
      },
      { 
        word: "勤務（する）",
        reading: "きんむ（する）",
        meaning: "Work・serve",
        exampleSentenceRuby: "自{じ}宅{たく}から勤務先{さき}までの通{つう}勤{きん}時間は約1時間です。",
      },
      { 
        word: "業務",
        reading: "ぎょうむ",
        meaning: "Business・task",
        exampleSentenceRuby: "業務内{ない}容{よう}は一{ひと}言{こと}で言えば医{い}療{りょう}機{き}器{き}の販{はん}売{ばい}です。",
      },
    ],
    otherWords: [
      { word: "義務", reading: "ぎむ", meaning: "duty" },
      { word: "専務", reading: "せんむ", meaning: "executive" },
      { word: "任務", reading: "にんむ", meaning: "mission" },
      { word: "実務", reading: "じつむ", meaning: "practical work" },
      { word: "職務", reading: "しょくむ", meaning: "one's duty" },
    ],
  },
  421: {
    id: 421,
    kanji: "存",
    kun: [],
    on: ["ソン", "ゾン"],
    meanings: ["exist", "be aware of", "believe"],
    words: [
      { 
        word: "保存（する）",
        reading: "ほぞん（する）",
        meaning: "Preservation・to preserve",
        exampleSentenceRuby: "念{ねん}のためデータは必{かなら}ず複{ふく}数{すう}、保{ほ}存{ぞん}してください。",
      },
      { 
        word: "生存（する）",
        reading: "せいぞん（する）",
        meaning: "Existence・survival",
        exampleSentenceRuby: "寂{さび}しい生{せい}存{ぞん}競{きょう}争{そう}、食{く}うか食{く}われるかの弱{じゃく}肉{にく}強{きょう}食{しょく}の世{せ}界{かい}です。",
      },
      { 
        word: "温存（する）",
        reading: "おんぞん（する）",
        meaning: "Preserve・retain・Conservation",
        exampleSentenceRuby: "現{げん}在{ざい}の景{けい}気{き}対{たい}策{さく}では、既{き}得{とく}権{けん}益{えき}を温{おん}存{ぞん}されることになる。",
      },
    ],
    otherWords: [
      { word: "存分(に)", reading: "ぞんぶん(に)", meaning: "to one's heart's content" },
      { word: "存じます", reading: "ぞんじます", meaning: "to know (humble)" },
      { word: "存亡", reading: "そんぼう", meaning: "existence and non-existence" },
      { word: "所存", reading: "しょぞん", meaning: "one's intention" },
      { word: "一存", reading: "いちぞん", meaning: "one's decision" },
    ],
  },
  422: {
    id: 422,
    kanji: "去",
    kun: ["さ"],
    on: ["キョ", "コ"],
    meanings: ["leave", "past", "eliminate"],
    words: [
      { 
        word: "過去",
        reading: "かこ",
        meaning: "past",
        exampleSentenceRuby: "過ぎ去ったよき過去を思い出して感{かん}慨{がい}にふける。",
      },
      { 
        word: "去る",
        reading: "さる",
        meaning: "to leave・last",
        exampleSentenceRuby: "去る者は日{ひ}々{び}いに疎{うと}し。・猿１０{とお}日{か}に来日したA氏{し}は、来る20{はっ}日{か}に帰{き}国{こく}の予定。",
      },
      { 
        word: "撤去（する）",
        reading: "てっきょ（する）",
        meaning: "Withdrawal・to remove",
        exampleSentenceRuby: "駅前の放{ほう}置{ち}自転車が撤{てっ}去{きょ}されました。",
      },
    ],
    otherWords: [
      { word: "立ち去る", reading: "たちさる", meaning: "to leave" },
      { word: "除去（する）", reading: "じょきょ（する）", meaning: "removal・to remove" },
      { word: "退去（する）", reading: "たいきょ（する）", meaning: "withdrawal・to leave" },
      { word: "置き去り（にする）", reading: "おきざり（にする）", meaning: "to leave behind" },
      { word: "消去（する）", reading: "しょうきょ（する）", meaning: "deletion・to delete" },
    ],
  },
  423: {
    id: 423,
    kanji: "庁",
    kun: [],
    on: ["チョウ"],
    meanings: ["government office", "agency"],
    words: [
      { 
        word: "〜庁",
        reading: "〜ちょう",
        meaning: "~agency/office",
        exampleSentenceRuby: "省{しょう}庁{ちょう}再{さい}編{へん}により、環{かん}境{きょう}庁{ちょう}は格{かく}上{あ}げされて環{かん}境{きょう}省{しょう}になった。",
      },
      { 
        word: "気象庁",
        reading: "きしょうちょう",
        meaning: "Meteorological Agency",
        exampleSentenceRuby: "気象庁は天気予報の他{ほか}、異{い}常{じょう}な自{し}然{ぜん}現{げん}象{しょう}の把{は}握{あく}と予{よ}測{そく}もする。",
      },
      { 
        word: "警視庁",
        reading: "けいしちょう",
        meaning: "Metropolitan Police Department",
        exampleSentenceRuby: "警視庁が殺{さつ}人{じん}犯{はん}を指{し}名{めい}手{て}配{はい}している",
      },
    ],
    otherWords: [
      { word: "警察庁", reading: "けいさつちょう", meaning: "National Police Agency" },
      { word: "海上保安庁", reading: "かいじょうほあんちょう", meaning: "Japan Coast Guard" },
      { word: "検察庁", reading: "けんさつちょう", meaning: "Public Prosecutor's Office" },
      { word: "特許庁", reading: "とっきょちょう", meaning: "Japan Patent Office" },
      { word: "官公庁", reading: "かんこうちょう", meaning: "government office" },
    ],
  },
  424: {
    id: 424,
    kanji: "幸",
    kun: ["しあわ","さいわ", "さち"],
    on: ["コウ"],
    meanings: ["happiness", "blessing", "fortune"],
    words: [
      { 
        word: "幸い",
        reading: "さいわい",
        meaning: "happiness・fortunately",
        exampleSentenceRuby: "雪道で滑{すべ}って転{ころ}んだが、幸{さいわ}い怪{け}我{が}はなかった。",
      },
      { 
        word: "幸運(な）",
        reading: "こううん(な）",
        meaning: "Lucky・Good fortunate",
        exampleSentenceRuby: "精{せい}神{しん}的{てき}にも経{けい}済{ざい}的{てき}にもどん底{ぞこ}の時{とき}に、幸{こう}運{うん}にも宝{たから}くじに当{あ}たった。",
      },
      { 
        word: "幸いする",
        reading: "さいわいする",
        meaning: "to be favored by",
        exampleSentenceRuby: "早めに家を出たのが幸{さいわ}いして渋{じゅう}滞{たい}に巻{ま}き込{こ}まれずに済{す}んだ。",
      },
    ],
    otherWords: [
      { word: "幸せ", reading: "しあわせ", meaning: "happiness" },
      { word: "不幸（な）", reading: "ふこう（な）", meaning: "unfortunate" },
      { word: "幸福（な）", reading: "こうふく（な）", meaning: "happy" },
      { word: "幸", reading: "さち", meaning: "happiness" },
      { word: "海の幸", reading: "うみのさち", meaning: "seafood" },
      { word: "山の幸", reading: "やまのさち", meaning: "mountain delicacies" },
    ],
  },
  425: {
    id: 425,
    kanji: "昭",
    kun: [],
    on: ["ショウ"],
    meanings: ["bright", "clear"],
    words: [
      { 
        word: "昭和",
        reading: "しょうわ",
        meaning: "Shōwa era",
        exampleSentenceRuby: "1989年{年}に、64年{年}で昭{しょう}和{わ}が終{お}わった。",
      },
    ],
    otherWords: [
      { word: "昭くさん", reading: "あきらさん", meaning: "人の名前" },
      { word: "昭子くさん", reading: "しょうこさん・あきこさん", meaning: "人の名前" },
      { word: "昭夫さん", reading: "あきおさん", meaning: "人の名前" },
    ],
  },
  426: {
    id: 426,
    kanji: "雨",
    kun: ["あめ", "あま"],
    on: ["ウ"],
    meanings: ["rain"],
    words: [
      { 
        word: "大雨",
        reading: "おおあめ",
        meaning: "heavy rain",
        exampleSentenceRuby: "九{きゅう}州{しゅう}地{ち}方{ほう}で大{おお}雨{あめ}が降{ふ}り、総{ぞう}雨{うり}量{よう}は多{おお}い所{ところ}で400ミリを超{こ}えた。",
      },
      { 
        word: "梅雨",
        reading: "つゆ・ばいう",
        meaning: "rainy season",
        exampleSentenceRuby: "太{たい}平{へい}洋{よう}高{こう}気{き}圧{あつ}が梅{ばい}雨{う}前{ぜん}線{せん}を北{きた}へ押{お}し上{あ}げ、梅{つ}雨{ゆ}が明{あ}けた。",
      },
      { 
        word: "雨天",
        reading: "うてん",
        meaning: "rainy day",
        exampleSentenceRuby: "10月に行われる野{や}外{がい}コンサートは雨{う}天{てん}決{けっ}行{こう}です。",
      },
    ],
    otherWords: [
      { word: "梅雨入り", reading: "つゆいり", meaning: "start of the rainy season" },
      { word: "梅雨明け", reading: "つゆあけ", meaning: "end of the rainy season" },
      { word: "雨水", reading: "あまみず", meaning: "rainwater" },
      { word: "長雨", reading: "ながあめ", meaning: "long rain" },
      { word: "小雨", reading: "こさめ", meaning: "light rain" },
      { word: "暴風雨", reading: "ぼうふうう", meaning: "stormy rain" },
    ],
  },
  427: {
    id: 427,
    kanji: "過",
    kun: ["す", "あやま"],
    on: ["カ"],
    meanings: ["exceed", "go beyond", "error", "mistake"],
    words: [
      { 
        word: "過ぎる",
        reading: "すぎる",
        meaning: "to exceed・pass・too much",
        exampleSentenceRuby: "ゲームのし過{す}ぎで脳{のう}が壊{こわ}れる、と心{しん}配{ぱい}し過{す}ぎる人もいる。",
      },
      { 
        word: "過ごす",
        reading: "すごす",
        meaning: "to spend (time)・pass",
        exampleSentenceRuby: "皆{みな}様{さま}、いかがお過{す}ごしでいらっしゃいますか。",
      },
      { 
        word: "見過ごす",
        reading: "みすごす",
        meaning: "to overlook・miss",
        exampleSentenceRuby: "責{せき}任{にん}上{じょう}、部{ぶ}長{ちょう}は部{ぶ}下{か}の過{あやま}ちを見{み}過{す}ごすわけにはいかない。",
      },
    ],
    otherWords: [
      { word: "通過（する）", reading: "つうか（する）", meaning: "to pass (through)" },
      { word: "通り過ぎる", reading: "とおりすぎる", meaning: "to pass by" },
      { word: "行き過ぎる", reading: "いきすぎる", meaning: "to go too far" },
      { word: "過熱（する）", reading: "かねつ（する）", meaning: "to overheat" },
      { word: "超過（する）", reading: "ちょうか（する）", meaning: "to exceed" },
      { word: "過ち", reading: "あやまち", meaning: "mistake" },
    ],
  },
  428: {
    id: 428,
    kanji: "系",
    kun: [],
    on: ["ケイ"],
    meanings: ["lineage", "system", "group"],
    words: [
      { 
        word: "日系",
        reading: "にっけい",
        meaning: "Japanese descent",
        exampleSentenceRuby: "国{くに}で日{にっ}系{けい}の企{き}業{ぎょう}に勤{つと}めていました。",
      },
      { 
        word: "生態系",
        reading: "せいたいけい",
        meaning: "ecological system",
        exampleSentenceRuby: "人{にん}間{げん}の活{かつ}動{どう}が生{せい}態{たい}系{けい}を破{は}壊{かい}し、他{た}の生{せい}物{ぶつ}を絶{ぜつ}滅{めつ}に追{お}いやっている。",
      },
      { 
        word: "体系",
        reading: "たいけい",
        meaning: "system・organization",
        exampleSentenceRuby: " このサービスを利{り}用{よう}する前に、料{りょう}金{きん}体{たい}系{けい}をよく見ておいた。",
      },
    ],
    otherWords: [
      { word: "~系", reading: "~けい", meaning: "related to ~" },
      { word: "系列", reading: "けいれつ", meaning: "series" },
      { word: "直系", reading: "ちょっけい", meaning: "direct lineage" },
      { word: "家系", reading: "かけい", meaning: "family lineage" },
      { word: "理系", reading: "りけい", meaning: "science (related)"},
      { word: "文系", reading: "ぶんけい", meaning: "literature (related)"},
    ],
  },
  429: {
    id: 429,
    kanji: "談",
    kun: [],
    on: ["ダン"],
    meanings: ["discuss", "talk"],
    words: [
      { 
        word: "冗談",
        reading: "じょうだん",
        meaning: "joke",
        exampleSentenceRuby: "真{ま}面{じ}目{め}な話{はなし}をしている時に冗{じょう}談{だん}を言わないでください。",
      },
      { 
        word: "対談",
        reading: "たいだん",
        meaning: "Talk・conversation",
        exampleSentenceRuby: "A党とB党の党{とう}首{しゅ}が対{たい}談{だん}し、両{りょう}党{とう}の統{とう}合{ごう}について語{かた}った。",
      },
      { 
        word: "談合（する）",
        reading: "だんごう（する）",
        meaning: "consultation",
        exampleSentenceRuby: "公{こう}共{きょう}事{じ}業{ぎょう}の入{にゅう}札{さつ}に関{かん}して3{さん}社{しゃ}が談{だん}合{ごう}していた。",
      },
    ],
    otherWords: [
      { word: "会談（する）", reading: "かいだん（する）", meaning: "meeting・talk" },
      { word: "商談（する）", reading: "しょうだん（する）", meaning: "business negotiation" },
      { word: "面談（する）", reading: "めんだん（する）", meaning: "interview" },
      { word: "雑談（する）", reading: "ざつだん（する）", meaning: "casual talk" },
      { word: "示談", reading: "じだん", meaning: "settlement (out of court)" },
    ],
  },
  430: {
    id: 430,
    kanji: "等",
    kun: ["ひと", "など"],
    on: ["トウ"],
    meanings: ["etc.", "class", "equal", "grade"],
    words: [
      { 
        word: "等しい",
        reading: "ひとしい",
        meaning: "equal・equivalent",
        exampleSentenceRuby: "仕{し}事{ごと}は部{ぶ}下{か}に丸{まる}投{な}げし、課{か}長{ちょう}は何{なに}もしていないに等{ひと}しい。",
      },
      { 
        word: "不平等(な）",
        reading: "ふびょうどう（な）",
        meaning: "inequality・unfair",
        exampleSentenceRuby: "グローバリゼーションは自{じ}由{ゆう}化{か}の反{はん}面{めん}で不{ふ}平{びょう}等{どう}と貧{ひん}困{こん}を助{じょ}長{ちょう}している。",
      },
      { 
        word: "対等(な）",
        reading: "たいとう（な）",
        meaning: "on equal terms",
        exampleSentenceRuby: "本{ほん}来{らい}、労{ろう}働{どう}条{じょう}件{けん}は労{ろう}使{し}が対{たい}等{とう}な立{たち}場{ば}で決{き}めるべきものである。",
      },
    ],
    otherWords: [
      { word: "等分（する）", reading: "とうぶん（する）", meaning: "division (to divide equally)" },
      { word: "等・～等", reading: "とう・～とう", meaning: "etc." },
      { word: "高等（な）", reading: "こうとう（な）", meaning: "advanced・high class" },
      { word: "同等（な・の）", reading: "どうとう（な・の）", meaning: "equal (to)" },
      { word: "上等（な）", reading: "じょうとう（な）", meaning: "superior・high quality" },
    ],
  },
  431: {
    id: 431,
    kanji: "防",
    kun: ["ふせ"],
    on: ["ボウ"],
    meanings: ["defend", "protect", "prevent"],
    words: [
      { 
        word: "防ぐ",
        reading: "ふせぐ",
        meaning: "to prevent・guard",
        exampleSentenceRuby: "パソコンのウィルス感{かん}染{せん}を防{ふせ}ぐために、対{たい}策{さく}用{よう}のソフトを買{か}った。",
      },
      { 
        word: "防災",
        reading: "ぼうさい",
        meaning: "disaster prevention",
        exampleSentenceRuby: "毎{まい}年{とし}9月{がつ}1{つい}日{たち}に防{ぼう}災{さい}訓{くん}練{れん}をして、地{じ}震{しん}に備{そな}えている。",
      },
      { 
        word: "予防（する）",
        reading: "よぼう（する）",
        meaning: "Prevent・Guard",
        exampleSentenceRuby: "インフルエンザを予{よ}防{ぼう}するためワクチン注{ちゅう}射{しゃ}をした。",
      },
    ],
    otherWords: [
      { word: "防衛（する）", reading: "ぼうえい（する）", meaning: "defense" },
      { word: "国防", reading: "こくぼう", meaning: "national defense" },
      { word: "防御（する）", reading: "ぼうぎょ（する）", meaning: "defense" },
      { word: "防犯", reading: "ぼうはん", meaning: "crime prevention" },
      { word: "防火", reading: "ぼうか", meaning: "fire prevention" },
    ],
  },
  432: {
    id: 432,
    kanji: "賞",
    kun: [],
    on: ["ショウ"],
    meanings: ["prize", "reward", "praise"],
    words: [
      { 
        word: "~賞",
        reading: "~しょう",
        meaning: "prize・reward",
        exampleSentenceRuby: "田{た}中{なか}氏{し}がノーベル化{か}学{がく}賞{しょう}を受{じゅ}賞{しょう}した。",
      },
      { 
        word: "賞金",
        reading: "しょうきん",
        meaning: "prize money",
        exampleSentenceRuby: "授{じゅ}賞{しょう}式{しき}でメダルと賞{しょう}状{じょう}と賞{しょう}金{きん}の小{こ}切{ぎっ}手{て}を受{う}け取{と}った。",
      },
      { 
        word: "鑑賞（する）",
        reading: "かんしょう（する）",
        meaning: "appreciation・enjoyment",
        exampleSentenceRuby: "趣{しゅ}味{み}は音{おん}楽{がく}鑑{かん}賞{しょう}です。",
      },
    ],
    otherWords: [
      { word: "入賞（する）", reading: "にゅうしょう（する）", meaning: "to win a prize" },
      { word: "大賞", reading: "たいしょう", meaning: "grand prize" },
      { word: "賞品", reading: "しょうひん", meaning: "prize" },
      { word: "観賞（する）", reading: "かんしょう（する）", meaning: "appreciation・enjoyment" },
      { word: "賞味（する）", reading: "しょうみ（する）", meaning: "to savor・to appreciate the flavor" },
    ],
  },
  433: {
    id: 433,
    kanji: "製",
    kun: [],
    on: ["セイ"],
    meanings: ["manufacture", "make"],
    words: [
      { 
        word: "製造（する）",
        reading: "せいぞう（する）",
        meaning: "manufacture・produce",
        exampleSentenceRuby: "当{とう}社{しゃ}は医{いや}薬{く}品{ひん}を製{せい}造{ぞう}する製{せい}薬{やく}会{かい}社{しゃ}です。",
      },
      { 
        word: "製作（する）",
        reading: "せいさく（する）",
        meaning: "make・produce",
        exampleSentenceRuby: "自分でデザインして、椅{い}子{す}を製{せい}作{さく}した。",
      },
      { 
        word: "～製",
        reading: "～せい",
        meaning: "made in～・made of ～",
        exampleSentenceRuby: "このプリンターはフィリピン製{せい}です。コピー用{よう}紙{し}はタイ製{せい}です。",
      },
    ],
    otherWords: [
      { word: "特製", reading: "とくせい", meaning: "special edition" },
      { word: "木製", reading: "もくせい", meaning: "wooden" },
      { word: "精製（する）", reading: "せいせい（する）", meaning: "refinement" },
      { word: "製法", reading: "せいほう", meaning: "manufacturing method" },
      { word: "作製（する）", reading: "さくせい（する）", meaning: "to create・to produce" },
    ],
  },
  434: {
    id: 434,
    kanji: "型",
    kun: ["かた"],
    on: ["ケイ"],
    meanings: ["model", "type", "mold", "pattern"],
    words: [
      { 
        word: "新型",
        reading: "しんがた",
        meaning: "new style・new model",
        exampleSentenceRuby: "（株{かぶしきがいしゃ}）T{ティー}自動車が、新{しん}型{がた}7{しち}人{にん}乗{の}り乗{じょう}用{よう}車{しゃ}を発{はつ}売{ばい}した。",
      },
      { 
        word: "模型",
        reading: "もけい",
        meaning: "model・miniature",
        exampleSentenceRuby: "趣{しゅ}味{み}は列{れっ}車{しゃ}の模{も}型{けい}作{づく}りです。",
      },
      { 
        word: "典型(的な）",
        reading: "てんけい(てきな）",
        meaning: "typical",
        exampleSentenceRuby: "典{てん}型{けい}的{てき}な詐{さ}欺{ぎ}の手{て}口{ぐち}を公{こう}表{ひょう}し、警{けい}察{さつ}が注意を促{うなが}した。",
      },
    ],
    otherWords: [
      { word: "原型", reading: "げんけい", meaning: "prototype" },
      { word: "同型", reading: "どうけい", meaning: "same type" },
      { word: "類型", reading: "るいけい", meaning: "type・category" },
      { word: "定型", reading: "ていけい", meaning: "regular pattern" },
      { word: "小型", reading: "こがた", meaning: "small size" },
      { word: "中型", reading: "ちゅうがた", meaning: "medium size" },
      { word: "大型", reading: "おおがた", meaning: "large size" },
    ],
  },
  435: {
    id: 435,
    kanji: "顔",
    kun: ["かお"],
    on: ["ガン"],
    meanings: ["face", "expression"],
    words: [
      { 
        word: "顔",
        reading: "かお",
        meaning: "face",
        exampleSentenceRuby: "時間があったらぜひ部{ぶ}室{しつ}に顔を出してください。",
      },
      { 
        word: "笑顔",
        reading: "えがお",
        meaning: "smiling face",
        exampleSentenceRuby: "美顔は周{まわ}りの人も幸せにする。",
      },
      { 
        word: "いい顔",
        reading: "いいかお",
        meaning: "friendly attitude",
        exampleSentenceRuby: "あの人は誰{だれ}にでもいい顔をする人だ。内{ない}心{しん}は分からない。",
      },
    ],
    otherWords: [
      { word: "素顔", reading: "すがお", meaning: "bare face" },
      { word: "顔合わせ（する）", reading: "かおあわせ（する）", meaning: "face-to-face meeting" },
      { word: "新顔", reading: "しんがお", meaning: "new face" },
      { word: "横顔", reading: "よこがお", meaning: "profile (face)" },
      { word: "顔面", reading: "がんめん", meaning: "face (surface)" },
    ],
  },
  436: {
    id: 436,
    kanji: "追",
    kun: ["お"],
    on: ["ツイ"],
    meanings: ["chase", "follow"],
    words: [
      { 
        word: "追い掛ける",
        reading: "おいかける",
        meaning: "to chase・pursue",
        exampleSentenceRuby: "前の人を追{お}い掛{か}けて、その人に追{お}い付{つ}いて、その人を追{お}い越{こ}した。",
      },
      { 
        word: "追及（する）",
        reading: "ついきゅう（する）",
        meaning: "to accuse・press ~ hard",
        exampleSentenceRuby: "株{かぶ}主{ぬし}らが工{こう}場{じょう}の事{じ}故{こ}に関{かん}して会{かい}社{しゃ}経{けい}営{えい}陣{じん}の責{せき}任{にん}を追{つい}及{きゅう}した。",
      },
      { 
        word: "追い込む",
        reading: "おいこむ",
        meaning: "to drive into",
        exampleSentenceRuby: "その寂{さび}しい追{つい}及{きゅう}は社長を退{たい}陣{じん}に追{お}い込{こ}んだ。",
      },
    ],
    otherWords: [
      { word: "追う", reading: "おう", meaning: "to chase" },
      { word: "追い出す", reading: "おいだす", meaning: "to expel" },
      { word: "追突（する）", reading: "ついとつ（する）", meaning: "to collide with" },
      { word: "追い抜く", reading: "おいぬく", meaning: "to overtake" },
      { word: "追試", reading: "ついし", meaning: "re-examination" },
    ],
  },
  437: {
    id: 437,
    kanji: "悪",
    kun: ["わる", "あ"],
    on: ["アク"],
    meanings: ["bad", "evil", "wrong"],
    words: [
      { 
        word: "最悪（な・の）",
        reading: "さいあく（な・の）",
        meaning: "the worst",
        exampleSentenceRuby: "戦{せん}争{そう}という最{さい}悪{あく}の事{じ}態{たい}を回{かい}避{ひ}するため、外{かい}交{こう}努{ど}力{りょく}が続{つづ}けられた。",
      },
      { 
        word: "悪口",
        reading: "わるくち",
        meaning: "bad mouth・speak evil of~",
        exampleSentenceRuby: "悪{わる}口{ぐち}を言うのではなく、建{けん}設{せつ}的{てき}な意{い}見{けん}をお願いします。",
      },
      { 
        word: "悪用（する）",
        reading: "あくよう（する）",
        meaning: "to abuse・misuse・improper use",
        exampleSentenceRuby: "インターネットの匿{とく}名{めい}性{せい}を悪{あく}用{よう}した犯{はん}罪{ざい}が発{はっ}生{せい}している。",
      },
    ],
    otherWords: [
      { word: "悪い", reading: "わるい", meaning: "bad" },
      { word: "悪さ", reading: "わるさ", meaning: "badness・wickedness" },
      { word: "悪", reading: "あく", meaning: "evil・bad" },
      { word: "悪質（な）", reading: "あくしつ（な）", meaning: "malicious・bad quality" },
      { word: "悪意", reading: "あくい", meaning: "ill will・malice" },
      { word: "悪者", reading: "あくもの", meaning: "villain・bad person" },
    ],
  },
  438: {
    id: 438,
    kanji: "久",
    kun: ["ひさ"],
    on: ["キュウ", "ク"],
    meanings: ["long time", "old story"],
    words: [
      { 
        word: "永久（に）",
        reading: "えいきゅう（に）",
        meaning: "eternally・permanence",
        exampleSentenceRuby: "温{おん}暖{だん}化{か}で山{さん}岳{がく}の永{えい}久{きゅう}凍{とう}土{ど}の溶{よう}解{かい}が進{すす}んでいる。",
      },
      { 
        word: "久し振り",
        reading: "ひさしぶり",
        meaning: "after a long time",
        exampleSentenceRuby: "梅{つ}雨{ゆ}時{どき}で雨が多いが、今日は久{ひさ}し振{ぶ}りの晴{せい}天{てん}だ。",
      },
      { 
        word: "久々",
        reading: "ひさびさ",
        meaning: "after a long time",
        exampleSentenceRuby: "忙しく働き詰{づ}めだったが久{ひさ}々{びさ}に休{やす}みが取{と}れた。",
      },
    ],
    otherWords: [
      { word: "久しい", reading: "ひさしい", meaning: "long time" },
      { word: "恒久", reading: "こうきゅう", meaning: "perpetual・permanent" },
      { word: "耐久", reading: "たいきゅう", meaning: "durability" },
      { word: "持久力", reading: "じきゅうりょく", meaning: "stamina" },
      { word: "悠久", reading: "ゆうきゅう", meaning: "eternity" },
    ],
  },
  439: {
    id: 439,
    kanji: "注",
    kun: ["そそ"],
    on: ["チュウ"],
    meanings: ["pour", "concentration"],
    words: [
      { 
        word: "注目（する）",
        reading: "ちゅうもく（する）",
        meaning: "attention・notice",
        exampleSentenceRuby: "環{かん}境{きょう}改{かい}善{ぜん}のための新{しん}技{ぎ}術{じゅつ}として光{ひかり}触{しょく}媒{ばい}が注{ちゅう}目{もく}されている。",
      },
      { 
        word: "注文（する）",
        reading: "ちゅうもん（する）",
        meaning: "order",
        exampleSentenceRuby: "通{つう}信{しん}販{はん}売{ばい}でお米{こめ}を注{ちゅう}文{もん}した。",
      },
      { 
        word: "注ぐ",
        reading: "そそぐ",
        meaning: "to pour",
        exampleSentenceRuby: "グラスにワインを注{そそ}ぐ。・研{けん}究{きゅう}開{かい}発{はつ}に力{ちから}を注{そそ}ぐ。・愛{あい}情{じょう}を注{そそ}ぐ。",
      },
    ],
    otherWords: [
      { word: "発注（する）", reading: "はっちゅう（する）", meaning: "to place an order" },
      { word: "受注（する）", reading: "じゅちゅう（する）", meaning: "to receive an order" },
      { word: "要注意", reading: "ようちゅうい", meaning: "important notice" },
      { word: "注入（する）", reading: "ちゅうにゅう（する）", meaning: "to inject" },
      { word: "注視（する）", reading: "ちゅうし（する）", meaning: "to observe closely" },
      { word: "降り注ぐ", reading: "ふりそそぐ", meaning: "to pour down" },
    ],
  },
  440: {
    id: 440,
    kanji: "洋",
    kun: [],
    on: ["ヨウ"],
    meanings: ["ocean", "Western"],
    words: [
      { 
        word: "海洋",
        reading: "かいよう",
        meaning: "ocean・sea",
        exampleSentenceRuby: "当{とう}海{かい}洋{よう}研{けん}究{きゅう}所{じょ}では、海{かい}洋{よう}深{しん}層{そう}水{すい}の資{し}源{げん}利{り}用{よう}の研{けん}究{きゅう}をしている。",
      },
      { 
        word: "洋服",
        reading: "ようふく",
        meaning: "Western-style clothes",
        exampleSentenceRuby: "日{にち}常{じょう}はほとんど洋{よう}服{ふく}を着{き}て生{せい}活{かつ}している。和{わ}服{ふく}はあったに着{き}ない。",
      },
      { 
        word: "洋風",
        reading: "ようふう",
        meaning: "Western style",
        exampleSentenceRuby: "和{わ}服{ふく}の庭{にわ}を洋{よう}風{ふう}にリフォームして、ガーデニングを楽しみたい。",
      },
    ],
    otherWords: [
      { word: "洋画", reading: "ようが", meaning: "Western-style painting" },
      { word: "洋楽", reading: "ようがく", meaning: "Western music" },
      { word: "洋食", reading: "ようしょく", meaning: "Western food" },
      { word: "洋式", reading: "ようしき", meaning: "Western style" },
      { word: "洋書", reading: "ようしょ", meaning: "Western book" },
    ],
  },
  441: {
    id: 441,
    kanji: "術",
    kun: ["すべ"],
    on: ["ジュツ"],
    meanings: ["art", "technique"],
    words: [
      { 
        word: "芸術（的な）",
        reading: "げいじゅつ（てきな）",
        meaning: "artistic・art",
        exampleSentenceRuby: "秋{あき}です。芸{げい}術{じゅつ}に親{した}しむ季{き}節{せつ}になりました。",
      },
      { 
        word: "技術（的な）",
        reading: "ぎじゅつ（てきな）",
        meaning: "technical・technological",
        exampleSentenceRuby: "この開{かい}発{はつ}は技{ぎ}術{じゅつ}的{てき}にはクリアできるが、経{けい}済{ざい}的{てき}には問{もん}題{だい}がある。",
      },
      { 
        word: "術",
        reading: "すべ",
        meaning: "way・method",
        exampleSentenceRuby: "自{し}然{ぜん}の猛{もう}威{い}の前では人はなす術{すべ}もなく、呆{ぼう}然{ぜん}と立{た}ち尽{つ}くすのみだ。",
      },
    ],
    otherWords: [
      { word: "芸術家", reading: "げいじゅつか", meaning: "artist" },
      { word: "戦術", reading: "せんじゅつ", meaning: "strategy" },
      { word: "学術", reading: "がくじゅつ", meaning: "academic" },
      { word: "技術革新", reading: "ぎじゅつかくしん", meaning: "technological innovation" },
      { word: "話術", reading: "わじゅつ", meaning: "rhetoric" },
    ],
  },
  442: {
    id: 442,
    kanji: "州",
    kun: ["す"],
    on: ["シュウ"],
    meanings: ["state", "province"],
    words: [
      { 
        word: "欧州",
        reading: "おうしゅう",
        meaning: "Europe",
        exampleSentenceRuby: "欧{おう}州{しゅう}連{れん}合{ごう}（EU）の本{ほん}部{ぶ}はベルギーのブリュッセルにある。",
      },
    ],
    otherWords: [
      { word: "州・～州", reading: "しゅう・～しゅう", meaning: "state・province" },
      { word: "九州（地方）", reading: "きゅうしゅう（ちほう）", meaning: "Kyushu (region)" },
      { word: "本州", reading: "ほんしゅう", meaning: "Honshu (region)" },
      { word: "中州［中洲］", reading: "なかす", meaning: "Nakasu (region)" },
    ],
  },
  443: {
    id: 443,
    kanji: "血",
    kun: ["ち"],
    on: ["ケツ"],
    meanings: ["blood"],
    words: [
      { 
        word: "血",
        reading: "ち",
        meaning: "blood",
        exampleSentenceRuby: "小さい傷{きず}口{ぐち}なのに血{ち}が出{で}てなかなか止{と}まらない。",
      },
      { 
        word: "血液",
        reading: "けつえき",
        meaning: "blood",
        exampleSentenceRuby: "A型{がた}の血{けつ}液{えき}が不{ふ}足{そく}しています。献{けん}血{けつ}にご協{きょう}力{りょく}ください。",
      },
      { 
        word: "輸血（する）",
        reading: "ゆけつ（する）",
        meaning: "blood transfusion",
        exampleSentenceRuby: "大{たい}量{りょう}に出{しゅっ}血{けつ}したため輸{ゆ}血{けつ}せざるを得{え}なかった。",
      },
    ],
    otherWords: [
      { word: "血圧", reading: "けつあつ", meaning: "blood pressure" },
      { word: "高血圧", reading: "こうけつあつ", meaning: "high blood pressure" },
      { word: "低血圧", reading: "ていけつあつ", meaning: "low blood pressure" },
      { word: "血管", reading: "けっかん", meaning: "blood vessel" },
      { word: "血液型", reading: "けつえきがた", meaning: "blood type" },
      { word: "流血（の惨事）", reading: "けつのけ (のさんじ)", meaning: "bloodshed (of a disaster)" },
    ],
  },
  444: {
    id: 444,
    kanji: "渡",
    kun: ["わた"],
    on: ["ト"],
    meanings: ["cross", "ferry"],
    words: [
      { 
        word: "渡す",
        reading: "わたす",
        meaning: "hand・pass・ferry",
        exampleSentenceRuby: "政{せい}治{じ}家{か}に金{かね}を渡{わた}す。・川{かわ}に橋{はし}を渡{わた}す。・両{りょう}国{こく}の橋{はし}渡{わた}しになる。",
      },
      { 
        word: "渡る",
        reading: "わたる",
        meaning: "go across・get along",
        exampleSentenceRuby: "道を渡る。・川を渡る。・彼女は世{よ}渡{わた}りがうまい。・渡る世{せ}間{けん}に鬼{おに}はない。",
      },
      { 
        word: "見渡す",
        reading: "みわたす",
        meaning: "look out over",
        exampleSentenceRuby: "３６０度、見{み}渡{わた}す限{かぎ}り地{ち}平{へい}線{せん}まで広{こう}大{だい}な草{そう}原{げん}が続{つづ}いている。",
      },
    ],
    otherWords: [
      { word: "言い渡す", reading: "いいわたす", meaning: "to declare・to announce" },
      { word: "受け渡し", reading: "うけわたし", meaning: "handing over" },
      { word: "引き渡す", reading: "ひきわたす", meaning: "to hand over" },
      { word: "過渡期", reading: "かとき", meaning: "transitional period" },
      { word: "渡航（する）", reading: "とこう（する）", meaning: "to travel by sea" },
    ],
  },
  445: {
    id: 445,
    kanji: "減",
    kun: ["へ"],
    on: ["ゲン"],
    meanings: ["decrease", "reduce"],
    words: [
      { 
        word: "減る",
        reading: "へる",
        meaning: "get fewer・lessen・decrease",
        exampleSentenceRuby: "子供の数{かず}が減{へ}った。・年{ねん}収{しゅう}が減{へ}った。・おなかが減{へ}った。",
      },
      { 
        word: "減らす",
        reading: "へらす",
        meaning: "reduce・cut down",
        exampleSentenceRuby: "お小{こ}遣{づか}いを減{へ}らした。・罰{ばつ}則{そく}強{きょう}化{か}が事{じ}故{こ}を減{へ}らした。",
      },
      { 
        word: "削減（する）",
        reading: "さくげん（する）",
        meaning: "curtail・reduce・reduction",
        exampleSentenceRuby: "無{む}駄{だ}な経{けい}費{ひ}を削{さく}減{げん}し、利{り}益{えき}を捻{ねん}出{しゅつ}する。",
      },
    ],
    otherWords: [
      { word: "加減（する）", reading: "かげん（する）", meaning: "adjustment・moderation" },
      { word: "いい加減（な・に）", reading: "いいかげん（な・に）", meaning: "irresponsible・careless" },
      { word: "減・～減", reading: "げん・～げん", meaning: "decrease・reduction" },
      { word: "軽減（する）", reading: "けいげん（する）", meaning: "curtail・reduce・reduction" },
      { word: "半減（する）", reading: "はんげん（する）", meaning: "halve・reduce by half" },
      { word: "減点（する）", reading: "げんてん（する）", meaning: "to deduct points" },
    ],
  },
  446: {
    id: 446,
    kanji: "吉",
    kun: ["よし"],
    on: ["キチ", "キツ"],
    meanings: ["good luck", "good fortune"],
    words: [
      { 
        word: "大吉",
        reading: "だいきち",
        meaning: "great luck",
        exampleSentenceRuby: "神{じん}社{しゃ}のおみくじで大{だい}吉{きち}が出{で}た。",
      },
      { 
        word: "不吉（な）",
        reading: "ふきつ（な）",
        meaning: "Ominous・inauspicious",
        exampleSentenceRuby: "嵐{あらし}の前{まえ}のように空{そら}が暗{くら}い。何{なん}となく不{ふ}吉{きつ}な予{よ}感{かん}がする。",
      },
      { 
        word: "吉",
        reading: "きち",
        meaning: "good luck",
        exampleSentenceRuby: "今{こん}回{かい}の首{しゅ}相{しょう}の判{はん}断{だん}が吉{きち}と出{で}るか、凶{きょう}と出{で}るか、政{せい}局{きょく}を見{み}守{まも}りたい。",
      },
    ],
    otherWords: [
      { word: "吉報", reading: "きっぽう", meaning: "good news" },
      { word: "中吉", reading: "ちゅうきち", meaning: "middle luck" },
      { word: "小吉", reading: "しょうきち", meaning: "small luck" },
      { word: "末吉", reading: "すえきち", meaning: "last luck" },
      { word: "大安吉日", reading: "だいあんきちじつ", meaning: "lucky day" },
      { word: "吉岡さん", reading: "きちおかさん", meaning: "Yoshioka-san" },
      { word: "吉田さん", reading: "よしださん", meaning: "Yoshida-san" },
    ],
  },
  447: {
    id: 447,
    kanji: "玉",
    kun: ["たま"],
    on: ["ギョク"],
    meanings: ["jewel", "ball"],
    words: [
      { 
        word: "目玉",
        reading: "めだま",
        meaning: "eyeball",
        exampleSentenceRuby: "目{め}玉{だま}が飛{と}び出{で}るほど高{たか}い・目{め}玉{だま}商{しょう}品{ひん}・先生に大{おお}目{め}玉{だま}を食{く}らった。",
      },
      { 
        word: "玉突き",
        reading: "たまつき",
        meaning: "billiards・pile-up (traffic accident)",
        exampleSentenceRuby: "高{こう}速{そく}道{どう}路{ろ}で車{くるま}10台{だい}の玉{たま}突{つ}き事{じ}故{こ}が起{お}こった。",
      },
      { 
        word: "替え玉",
        reading: "かえだま",
        meaning: "substitute (in a game)・Stand-in",
        exampleSentenceRuby: "試験を受けたのは本{ほん}人{にん}ではなく、替{か}え玉{だま}だった。",
      },
    ],
    otherWords: [
      { word: "玉", reading: "たま・ぎょく", meaning: "ball; jewel" },
      { word: "悪玉", reading: "あくだま", meaning: "bad ball; villain" },
      { word: "善玉", reading: "ぜんだま", meaning: "good ball; hero" },
      { word: "お年玉", reading: "おとしだま", meaning: "New Year's gift (money)" },
      { word: "火の玉", reading: "ひのたま", meaning: "fireball" },
      { word: "水玉（模様）", reading: "みずたま（もよう）", meaning: "polka dot" },
    ],
  },
  448: {
    id: 448,
    kanji: "労",
    kun: [],
    on: ["ロウ"],
    meanings: ["labor", "work"],
    words: [
      { 
        word: "労働（する）",
        reading: "ろうどう（する）",
        meaning: "labor・work",
        exampleSentenceRuby: "経{けい}営{えい}者{しゃ}は合{ごう}理{り}化{か}によって労{ろう}働{どう}力{りょく}を削{さく}減{げん}しようと図{はか}っている。",
      },
      { 
        word: "疲労（する）",
        reading: "ひろう（する）",
        meaning: "fatigue・exhaustion",
        exampleSentenceRuby: "働き過ぎて疲{ひ}労{ろう}のためにダウンしてしまった。",
      },
      { 
        word: "苦労（する）",
        reading: "くろう（する）",
        meaning: "trouble・hardship",
        exampleSentenceRuby: "自分勝{かっ}手{て}な行{こう}動{どう}をして親{おや}には随{ずい}分{ぶん}苦{く}労{ろう}をかけた。",
      },
    ],
    otherWords: [
      { word: "過労", reading: "かろう", meaning: "overwork" },
      { word: "勤労（する）", reading: "きんろう（する）", meaning: "labor; work" },
      { word: "就労（する）", reading: "しゅうろう（する）", meaning: "employment; work" },
      { word: "労（する）", reading: "ろう（する）", meaning: "labor; work" },
      { word: "労力", reading: "ろうりょく", meaning: "labor; effort" },
    ],
  },
  449: {
    id: 449,
    kanji: "橋",
    kun: ["はし"],
    on: ["キョウ"],
    meanings: ["bridge"],
    words: [
      { 
        word: "橋",
        reading: "はし",
        meaning: "bridge",
        exampleSentenceRuby: "将来は両{りょう}国{こく}をつなぐかけ橋{はし}となって働きたいと思っています。",
      },
      { 
        word: "歩道橋",
        reading: "ほどうきょう",
        meaning: "pedestrian bridge・Footbridge",
        exampleSentenceRuby: "横{おう}断{だん}歩{ほ}道{どう}がないので通{とお}りの向{む}こうには、歩{ほ}道{どう}橋{きょう}を渡{わた}って行{い}く。",
      },
      { 
        word: "桟橋",
        reading: "さんばし",
        meaning: "pier",
        exampleSentenceRuby: "港{みなと}の桟{さん}橋{ばし}に国{こく}際{さい}航{こう}路{ろ}の大{おお}型{がた}旅{りょ}客{かく}船{せん}が着{つ}いた。",
      },
    ],
    otherWords: [
      { word: "鉄橋", reading: "てっきょう", meaning: "iron bridge" },
      { word: "石橋", reading: "いしばし", meaning: "stone bridge" },
      { word: "陸橋", reading: "りっきょう", meaning: "land bridge" },
      { word: "日本橋", reading: "にほんばし", meaning: "Nihonbashi" },
      { word: "高橋さん", reading: "たかはしさん", meaning: "Takahashi-san" },
    ],
  },
  450: {
    id: 450,
    kanji: "病",
    kun: ["やまい"],
    on: ["ビョウ", "ヘイ"],
    meanings: ["illness", "disease"],
    words: [
      { 
        word: "病",
        reading: "やまい",
        meaning: "illness・disease",
        exampleSentenceRuby: "癌{がん}は不{ふ}治{じ}の病{やまい}ではなくなってきている。",
      },
      { 
        word: "病人",
        reading: "びょうにん",
        meaning: "Sick person・Patient",
        exampleSentenceRuby: "家{か}族{ぞく}は病{びょう}人{にん}のそばにいて付{つ}ききりで看{かん}病{びょう}している。",
      },
      { 
        word: "病む",
        reading: "やむ",
        meaning: "to fall ill・Suffer from",
        exampleSentenceRuby: "地{ち}球{きゅう}は今、間{ま}違{ちが}いなく病{や}んでいる。",
      },
    ],
    otherWords: [
      { word: "発病（する）", reading: "はつびょう（する）", meaning: "to develop a disease" },
      { word: "病死（する）", reading: "びょうし（する）", meaning: "to die of illness" },
      { word: "病名", reading: "びょうめい", meaning: "disease name" },
      { word: "重病", reading: "じゅうびょう", meaning: "serious illness" },
      { word: "難病", reading: "なんびょう", meaning: "intractable disease" },
      { word: "急病", reading: "きゅうびょう", meaning: "sudden illness" },
    ],
  },
  451: {
    id: 451,
    kanji: "配",
    kun: ["くば"],
    on: ["ハイ"],
    meanings: ["distribution", "to distribute"],
    words: [
      { 
        word: "配る",
        reading: "くばる",
        meaning: "to distribute・to hand out",
        exampleSentenceRuby: "テスト用{よう}紙{し}が配{くば}られた。・あの人は周{まわ}りによく気{き}を配{くば}る人だ。",
      },
      { 
        word: "配慮（する）",
        reading: "はいりょ（する）",
        meaning: "consideration・concern・care",
        exampleSentenceRuby: "わが社{しゃ}では環{かん}境{きょう}に配{はい}慮{りょ}した商{しょう}品{ひん}づくりに取{と}り組{く}んでいます。",
      },
      { 
        word: "気配",
        reading: "けはい",
        meaning: "sign・indication",
        exampleSentenceRuby: "まだ暑{あつ}いが風{かぜ}に秋{あき}の気{け}配{はい}が感{かん}じられる。・人の気{け}配{はい}がある。",
      },
    ],
    otherWords: [
      { word: "配分（する）", reading: "はいぶん（する）", meaning: "distribution・allotment" },
      { word: "配当（する）", reading: "はいとう（する）", meaning: "dividend・distribution of profits" },
      { word: "配布（する）", reading: "はいふ（する）", meaning: "distribution・dissemination" },
      { word: "分配（する）", reading: "ぶんぱい（する）", meaning: "distribution・allotment" },
      { word: "手配（する）", reading: "てはい（する）", meaning: "arrangement・preparation" },
    ],
  },
  452: {
    id: 452,
    kanji: "沢",
    kun: ["さわ"],
    on: ["タク"],
    meanings: ["swamp", "marsh"],
    words: [
      { 
        word: "沢山",
        reading: "たくさん",
        meaning: "a lot・much・many",
        exampleSentenceRuby: "言いたい事が沢{たく}山{さん}ある。・お説{せっ}教{きょう}はもう沢{たく}山{さん}だ。もう嫌{いや}だ。",
      },
      { 
        word: "沢",
        reading: "さわ",
        meaning: "swamp・stream・mountain stream",
        exampleSentenceRuby: "山を降{お}りて沢{さわ}に沿{そ}って歩{ある}いた。",
      },
      { 
        word: "贅沢（な）",
        reading: "ぜいたく（な）",
        meaning: "luxurious・extravagant",
        exampleSentenceRuby: "贅{ぜい}沢{たく}な暮{く}らしが彼{かれ}を病{びょう}気{き}にした。",
      },
    ],
    otherWords: [
      { word: "光沢", reading: "こうたく", meaning: "luster・gloss" },
      { word: "盛（り）沢山（な・の）", reading: "もりだくさん（な・の）", meaning: "a lot・much・many" },
      { word: "石川県金沢市", reading: "いしかわけんかなざわし", meaning: "Kanazawa City, Ishikawa Prefecture" },
      { word: "宮沢さん", reading: "みやざわさん", meaning: "Miyazawa-san" },
      { word: "小沢さん", reading: "おざわさん", meaning: "Ozawa-san" },
    ],
  },
  453: {
    id: 453,
    kanji: "育",
    kun: ["そだ"],
    on: ["イク"],
    meanings: ["to raise", "to bring up", "to rear"],
    words: [
      { 
        word: "育てる",
        reading: "そだてる",
        meaning: "to raise・to bring up",
        exampleSentenceRuby: "",
      },
      { 
        word: "育つ",
        reading: "そだつ",
        meaning: "to grow・to be brought up",
        exampleSentenceRuby: "",
      },
      { 
        word: "体育",
        reading: "たいいく",
        meaning: "physical education",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "保育（する）", reading: "ほいく（する）", meaning: "childcare・nurturing" },
      { word: "育児", reading: "いくじ", meaning: "child-rearing" },
      { word: "義務教育", reading: "ぎむきょういく", meaning: "compulsory education" },
      { word: "育成（する）", reading: "いくせい（する）", meaning: "nurturing・fostering" },
      { word: "発育（する）", reading: "はついく（する）", meaning: "growth・development" },
    ],
  },
  454: {
    id: 454,
    kanji: "検",
    kun: [],
    on: ["ケン"],
    meanings: ["to examine", "to inspect"],
    words: [
      { 
        word: "検討（する）",
        reading: "けんとう（する）",
        meaning: "examination・consideration",
        exampleSentenceRuby: "",
      },
      { 
        word: "検定（する）",
        reading: "けんてい（する）",
        meaning: "Official approval・certification",
        exampleSentenceRuby: "",
      },
      { 
        word: "検証（する）",
        reading: "けんしょう（する）",
        meaning: "verification・verify・inspect",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "検出（する）", reading: "けんしゅつ（する）", meaning: "detection・detect" },
      { word: "検問（する）", reading: "けんもん（する）", meaning: "inspection・interrogation" },
      { word: "車検", reading: "しゃけん", meaning: "vehicle inspection" },
      { word: "検察", reading: "けんさつ", meaning: "prosecution・public prosecutor's office" },
      { word: "検事", reading: "けんじ", meaning: "public prosecutor" },
    ],
  },
  455: {
    id: 455,
    kanji: "負",
    kun: ["ま"],
    on: ["フ"],
    meanings: ["to lose", "to bear", "to owe"],
    words: [
      { 
        word: "負担（する）",
        reading: "ふたん（する）",
        meaning: "burden・responsibility",
        exampleSentenceRuby: "",
      },
      { 
        word: "負う",
        reading: "おう",
        meaning: "shoulder・to bear",
        exampleSentenceRuby: "",
      },
      { 
        word: "抱負",
        reading: "ほうふ",
        meaning: "ambition・aspiration",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "負傷（する）", reading: "ふしょう（する）", meaning: "injury・to be injured" },
      { word: "負け", reading: "まけ", meaning: "defeat・to lose" },
      { word: "負け戦", reading: "まけいくさ", meaning: "losing battle" },
      { word: "自負（する）", reading: "じふ（する）", meaning: "pride・to take pride in" },
      { word: "勝ち負け", reading: "かちまけ", meaning: "victory or defeat" },
    ],
  },
  456: {
    id: 456,
    kanji: "低",
    kun: ["ひく"],
    on: ["テイ"],
    meanings: ["low", "short", "humble"],
    words: [
      { 
        word: "低い",
        reading: "ひくい",
        meaning: "low・short",
        exampleSentenceRuby: "彼は他{た}者{しゃ}の人{じん}権{けん}に対{たい}する意{い}識{しき}が低{ひく}いようだ。",
      },
      { 
        word: "低迷（する）",
        reading: "ていめい（する）",
        meaning: "Hang low・to be sluggish",
        exampleSentenceRuby: "株{かぶ}価{か}が低{てい}迷{めい}している。",
      },
      { 
        word: "最低限",
        reading: "さいていげん",
        meaning: "minimum・the least",
        exampleSentenceRuby: "この部{へ}屋{や}は飲{いん}食{しょく}禁{きん}止{し}です。最{さい}低{てい}限{げん}のルールは守りましょう。",
      },
    ],
    otherWords: [
      { word: "低さ", reading: "ひくさ", meaning: "lowness・shortness" },
      { word: "低温", reading: "ていおん", meaning: "low temperature" },
      { word: "高低", reading: "こうてい", meaning: "high and low" },
      { word: "低調（な）", reading: "ていちょう（な）", meaning: "sluggish・low-key" },
      { word: "低気圧", reading: "ていきあつ", meaning: "low pressure" },
    ],
  },
  457: {
    id: 457,
    kanji: "周",
    kun: ["まわ"],
    on: ["シュウ"],
    meanings: [" circumference", "surround", "ring"],
    words: [
      { 
        word: "周囲",
        reading: "しゅうい",
        meaning: "surroundings・circuit",
        exampleSentenceRuby: "携{けい}帯{たい}電{でん}話{わ}通{つう}話{わ}中{ちゅう}は周{しゅう}囲{い}に対{たい}する気{き}配{くば}りを忘{わす}れないでほしい。",
      },
      { 
        word: "周り",
        reading: "まわり",
        meaning: "surroundings・around",
        exampleSentenceRuby: "部{ぶ}長{ちょう}は人{じん}望{ぼう}が厚{あつ}いので周{まわ}りには優{ゆう}秀{しゅう}な人{じん}材{ざい}が集{あつ}まってくる。",
      },
      { 
        word: "周知（する）",
        reading: "しゅうち（する）",
        meaning: "awareness・to inform・to make ~ known to everyone",
        exampleSentenceRuby: "セクシャルハラスメント防{ぼう}止{し}の基{き}本{ほん}方{ほう}針{しん}を全{ぜん}職{しょく}員{いん}へ周{しゅう}知{ち}徹{てっ}底{てい}する。",
      },
    ],
    otherWords: [
      { word: "周・～周", reading: "しゅう・～しゅう", meaning: "circumference・surrounding" },
      { word: "周波数", reading: "しゅうはすう", meaning: "frequency" },
      { word: "周期", reading: "しゅうき", meaning: "cycle・period" },
      { word: "円周", reading: "えんしゅう", meaning: "circumference" },
      { word: "一周年", reading: "いちしゅうねん", meaning: "first anniversary" },
    ],
  },
  458: {
    id: 458,
    kanji: "課",
    kun: [],
    on: ["カ"],
    meanings: ["section", "lesson", "department"],
    words: [
      { 
        word: "課程",
        reading: "かてい",
        meaning: "course・curriculum",
        exampleSentenceRuby: "大{だい}学{がく}院{いん}には修{しゅう}士{し}課{か}程{てい}と博{はか}士{せ}課{か}程{てい}がある。",
      },
      { 
        word: "日課",
        reading: "にっか",
        meaning: "daily task・daily routine",
        exampleSentenceRuby: "毎日1時間の散{さん}歩{ほ}を日{にっ}課{か}にしている。",
      },
      { 
        word: "課する",
        reading: "かする",
        meaning: "to assign・to allocate・to assess",
        exampleSentenceRuby: "教{きょう}授{じゅ}は学生にレポートを課{か}した。・税{ぜい}金{きん}を課{か}される。",
      },
    ],
    otherWords: [
      { word: "課長", reading: "かちょう", meaning: "section chief・manager" },
      { word: "課・～課", reading: "か・～か", meaning: "section・department" },
      { word: "教育課程", reading: "きょういくかてい", meaning: "educational curriculum" },
      { word: "課外", reading: "かがい", meaning: "extracurricular" },
      { word: "放課後", reading: "ほうかご", meaning: "after school" },
    ],
  },
  459: {
    id: 459,
    kanji: "研",
    kun: ["と"],
    on: ["ケン"],
    meanings: ["to polish", "to study", "to research"],
    words: [
      { 
        word: "研修（する）",
        reading: "けんしゅう（する）",
        meaning: "training・to train",
        exampleSentenceRuby: " 日本の企{き}業{ぎょう}で研{けん}修{しゅう}を受{う}けることになっている。",
      },
      { 
        word: "研ぐ",
        reading: "とぐ",
        meaning: "to polish・to sharpen・Whet",
        exampleSentenceRuby: "砥{と}石{いし}で包{ほう}丁{ちょう}を研{と}ぐ。・お米{こめ}を研{と}ぐ。",
      },
      { 
        word: "研き澄ます",
        reading: "とぎすます",
        meaning: "to refine・to sharpen〜well",
        exampleSentenceRuby: "ピアニストが感{かん}覚{かく}を研{と}ぎ澄{す}ましてピアノに向{む}かう。",
      },
    ],
    otherWords: [
      { word: "研究所", reading: "けんきゅうじょ", meaning: "research institute" },
      { word: "研究者", reading: "けんきゅうしゃ", meaning: "researcher" },
      { word: "研究開発", reading: "けんきゅうかいはつ", meaning: "research and development" },
      { word: "研究会", reading: "けんきゅうかい", meaning: "research group" },
      { word: "研磨（する）", reading: "けんま（する）", meaning: "polishing・to polish" },
    ],
  },
  460: {
    id: 460,
    kanji: "残",
    kun: ["のこ"],
    on: ["ザン"],
    meanings: ["to remain", "to be left", "to stay"],
    words: [
      { 
        word: "残る",
        reading: "のこる",
        meaning: "to remain・to be left",
        exampleSentenceRuby: "映{えい}画{が}の中{なか}で最{さい}後{ご}に主{しゅ}人{じん}公{こう}が言{い}った言{こと}葉{ば}が今{いま}も心{こころ}に残{のこ}っている。",
      },
      { 
        word: "残す",
        reading: "のこす",
        meaning: "to leave (behind)・to save",
        exampleSentenceRuby: "12月です。今年も残{のこ}すところ１{いっ}ヶ{か}月{げつ}となりました。",
      },
      { 
        word: "残り",
        reading: "のこり",
        meaning: "remaining・leftover・rest",
        exampleSentenceRuby: "紙{かみ}を１{いち}枚{まい}ずつ配{くば}ってください。残{のこ}りは前の机{つくえ}に戻{もど}してください。",
      },
    ],
    otherWords: [
      { word: "残高", reading: "ざんだか", meaning: "balance (of an account)" },
      { word: "残念（な）", reading: "ざんねん（な）", meaning: "regrettable・disappointing" },
      { word: "残業（する）", reading: "ざんぎょう（する）", meaning: "overtime・to work overtime" },
      { word: "生き残り・生き残る", reading: "いきのこり・いきのこる", meaning: "survival・to survive" },
      { word: "取り残す", reading: "とりのこす", meaning: "to leave behind" },
    ],
  },
  461: {
    id: 461,
    kanji: "球",
    kun: ["たま"],
    on: ["キュウ"],
    meanings: ["ball", "sphere"],
    words: [
      { 
        word: "地球",
        reading: "ちきゅう",
        meaning: "Earth",
        exampleSentenceRuby: "地{ち}球{きゅう}は自{じ}転{てん}しながら太{たい}陽{よう}の周{まわ}りを公{こう}転{てん}しています。",
      },
      { 
        word: "野球",
        reading: "やきゅう",
        meaning: "baseball",
        exampleSentenceRuby: "日本で野{や}球{きゅう}は人{にん}気{き}のあるスポーツです。",
      },
      { 
        word: "電球",
        reading: "でんきゅう",
        meaning: "light bulb",
        exampleSentenceRuby: "天{てん}井{じょう}の電{でん}球{きゅう}が切{き}れたので新{あたら}しいのに取{と}り替{か}える。",
      },
    ],
    otherWords: [
      { word: "球", reading: "たま・きゅう", meaning: "ball・sphere" },
      { word: "卓球", reading: "たっきゅう", meaning: "table tennis" },
      { word: "球場", reading: "きゅうじょう", meaning: "baseball stadium" },
      { word: "白血球・赤血球", reading: "はっけっきゅう・せっけっきゅう", meaning: "white blood cell・red blood cell" },
      { word: "気球", reading: "ききゅう", meaning: "hot air balloon" },
    ],
  },
  462: {
    id: 462,
    kanji: "浜",
    kun: ["はま"],
    on: ["ヒン"],
    meanings: ["beach", "seashore"],
    words: [
      { 
        word: "砂浜",
        reading: "すなはま",
        meaning: "sandy beach",
        exampleSentenceRuby: "砂{すな}浜{はま}で親{おや}子{こ}連{づ}れが潮{しお}干{ひ}狩{が}りをしている。",
      },
      { 
        word: "浜辺",
        reading: "はまべ",
        meaning: "beach・shore",
        exampleSentenceRuby: "波{なみ}が静{しず}かに打{う}ち寄{よ}せる浜{はま}辺{べ}を歩{ある}いた。",
      },
      { 
        word: "京浜（〈東京、横浜〉の略）",
        reading: "けいひん",
        meaning: "Keihin (abbreviation for Tokyo and Yokohama)",
        exampleSentenceRuby: "京{けい}浜{ひん}工{こう}業{ぎょう}地{ち}帯{たい}は東{とう}京{きょう}・川{かわ}崎{さき}・横{よこ}浜{はま}を結{むす}ぶ巨{きょ}大{だい}な臨{りん}海{かい}工{こう}業{ぎょう}地{ち}帯{たい}だ。",
      },
    ],
    otherWords: [
      { word: "浜", reading: "はま", meaning: "beach・shore" },
      { word: "神奈川県横浜市", reading: "かながわけんよこはまし", meaning: "Yokohama City, Kanagawa Prefecture" },
      { word: "静岡県浜松市", reading: "しずおかけんはままつし", meaning: "Hamamatsu City, Shizuoka Prefecture" },
      { word: "浜田さん", reading: "はまださん", meaning: "Mr./Ms. Hamada" },
    ],
  },
  463: {
    id: 463,
    kanji: "容",
    kun: [],
    on: ["ヨウ"],
    meanings: ["contain", "form", "appearance"],
    words: [
      { 
        word: "容易（な）",
        reading: "ようい（な）",
        meaning: "easy・simple",
        exampleSentenceRuby: "2000の漢{かん}字{じ}を使{つか}いこなすのは容{よう}易{い}ではない。",
      },
      { 
        word: "容認（する）",
        reading: "ようにん（する）",
        meaning: "admission・approval",
        exampleSentenceRuby: "勉強との両{りょう}立{りつ}を条{じょう}件{けん}に親{おや}は子{こ}供{ども}のアルバイトをしぶしぶ容{よう}認{にん}した。",
      },
      { 
        word: "容量",
        reading: "ようりょう",
        meaning: "capacity・volume",
        exampleSentenceRuby: "コンピューターのメモリ容{よう}量{りょう}は飛{ひ}躍{やく}的{てき}に増{ぞう}大{だい}している。",
      },
    ],
    otherWords: [
      { word: "容疑・容疑者", reading: "ようぎ・ようぎしゃ", meaning: "suspicion・suspect" },
      { word: "全容", reading: "ぜんよう", meaning: "full form・whole picture" },
      { word: "形容詞", reading: "けいようし", meaning: "adjective" },
      { word: "受容（する）", reading: "じゅよう（する）", meaning: "acceptance・reception" },
      { word: "許容（する）", reading: "きょよう（する）", meaning: "tolerance・acceptance" },
    ],
  },
  464: {
    id: 464,
    kanji: "非",
    kun: ["あら"],
    on: ["ヒ"],
    meanings: ["non-", "un-", "negative"],
    words: [
      { 
        word: "非難する",
        reading: "ひなんする",
        meaning: "to criticize・to blame",
        exampleSentenceRuby: "経{けい}営{えい}者{しゃ}側{がわ}の怠{たい}慢{まん}は徹{てっ}底{てい}的{てき}に非{ひ}難{なん}されるべきだ。",
      },
      { 
        word: "是非",
        reading: "ぜひ",
        meaning: "by all means・definitely・right and wrong・please",
        exampleSentenceRuby: "ダム建{けん}設{せつ}の是{ぜ}非{ひ}を問{と}う。・近{ちか}くにお出{い}での際{さい}は是{ぜ}非{ひ}お立{たち}寄{よ}り下{くだ}さい。",
      },
      { 
        word: "非・～非",
        reading: "ひ・～ひ",
        meaning: "non-・un-",
        exampleSentenceRuby: "非{ひ}公{こう}式{しき}・非{ひ}公{こう}開{かい}・非{ひ}常{じょう}勤{きん}・非{ひ}常{じょう}識{しき}・非{ひ}常{じょう}口{ぐち}・非{ひ}常{じょう}時{じ}・非{ひ}合{ごう}法{ほう}・非{ひ}売{ばい}品{ひん}・・・。",
      },
    ],
    otherWords: [
      { word: "非行", reading: "ひこう", meaning: "delinquency" },
      { word: "非情（な）", reading: "ひじょう（な）", meaning: "heartless・unfeeling" },
      { word: "非常（な・に）", reading: "ひじょう（な・に）", meaning: "very・extremely" },
      { word: "非力（な）", reading: "ひりき（な）", meaning: "powerless・weak" },
      { word: "非番", reading: "ひばん", meaning: "off-duty" },
    ],
  },
  465: {
    id: 465,
    kanji: "完",
    kun: [],
    on: ["カン"],
    meanings: ["complete", "perfect"],
    words: [
      { 
        word: "完了（する）",
        reading: "かんりょう（する）",
        meaning: "completion・to complete",
        exampleSentenceRuby: "ヒトゲノムの解{かい}読{どく}が遂{つい}に完{かん}了{りょう}した。",
      },
      { 
        word: "未完成（な・の）",
        reading: "みかんせい（な・の）",
        meaning: "incomplete・unfinished",
        exampleSentenceRuby: "この交{こう}響{きょう}曲{きょく}は未{み}完{かん}成{せい}です",
      },
      { 
        word: "完璧（な）",
        reading: "かんぺき（な）",
        meaning: "perfect・flawless",
        exampleSentenceRuby: "100点{てん}満{まん}点{てん}です。よくできました。完{かん}璧{ぺき}です。",
      },
    ],
    otherWords: [
      { word: "完成（する）", reading: "かんせい（する）", meaning: "completion・to complete" },
      { word: "完敗（する）", reading: "かんぱい（する）", meaning: "defeat・to be defeated" },
      { word: "完備（する）", reading: "かんび（する）", meaning: "perfection・to perfect" },
      { word: "不完全（な）", reading: "ふかんぜん（な）", meaning: "incomplete・imperfect" },
      { word: "完封（する）", reading: "かんぷう（する）", meaning: "to shut out" },
    ],
  },
  466: {
    id: 466,
    kanji: "究",
    kun: ["きわ"],
    on: ["キュウ"],
    meanings: ["to research", "to study thoroughly"],
    words: [
      { 
        word: "研究（する）",
        reading: "けんきゅう（する）",
        meaning: "research・to research",
        exampleSentenceRuby: "今{こん}後{ご}研{けん}究{きゅう}する内{ない}容{よう}について、研{けん}究{きゅう}計{けい}画{かく}書{しょ}にまとめた。",
      },
      { 
        word: "究める",
        reading: "きわめる",
        meaning: "to investigate/study thoroughly・to master",
        exampleSentenceRuby: "哲{てつ}学{がく}者{しゃ}は真{しん}理{り}を究{きわ}めようと試{こころ}みる。",
      },
      { 
        word: "究極",
        reading: "きゅうきょく",
        meaning: "ultimate・final・supreme",
        exampleSentenceRuby: "これぞ究{きゅう}極{きょく}の食品！理{り}想{そう}の宇{う}宙{ちゅう}食{しょく}。",
      },
    ],
    otherWords: [
      { word: "探究（する）", reading: "たんきゅう（する）", meaning: "inquiry・to inquire" },
      { word: "究明（する）", reading: "きゅうめい（する）", meaning: "investigation・to investigate" },
      { word: "追究（する）", reading: "ついきゅう（する）", meaning: "inquiry・to inquire" },
    ],
  },
  467: {
    id: 467,
    kanji: "単",
    kun: [],
    on: ["タン"],
    meanings: ["single", "simple", "mere"],
    words: [
      { 
        word: "簡単（な）",
        reading: "かんたん（な）",
        meaning: "Simple・easy",
        exampleSentenceRuby: "この機{き}械{かい}は操{そう}作{さ}が簡{かん}単{たん}で使{つか}いやすい。",
      },
      { 
        word: "単純（な）",
        reading: "たんじゅん（な）",
        meaning: "simple minded・simple",
        exampleSentenceRuby: "善{ぜん}悪{あく}の二{に}完{げん}論{ろん}で説{せつ}明{めい}できるほど国{こく}際{さい}社{しゃ}会{かい}は単{たん}純{じゅん}ではない。",
      },
      { 
        word: "単なる",
        reading: "たんなる",
        meaning: "Mere・simple",
        exampleSentenceRuby: "見ているとロボットの犬が単{たん}なる機{き}械{かい}以{い}上{じょう}のものに思{おも}えてくる。",
      },
    ],
    otherWords: [
      { word: "单独", reading: "たんどく", meaning: "alone・independent" },
      { word: "単に", reading: "たんに", meaning: "merely・simply" },
      { word: "単一（な・の）", reading: "たんいつ（な・の）", meaning: "single・simple" },
      { word: "単身", reading: "たんしん", meaning: "single・alone" },
      { word: "単調（な）", reading: "たんちょう（な）", meaning: "monotonous・tedious" },
    ],
  },
  468: {
    id: 468,
    kanji: "駅",
    kun: [],
    on: ["エキ"],
    meanings: ["station"],
    words: [
      { 
        word: "駅前",
        reading: "えきまえ",
        meaning: "In front of the station",
        exampleSentenceRuby: "駅{えき}前{まえ}は開{かい}発{はつ}されて、ずいぶん様{よう}子{す}が変{かわ}った。",
      },
      { 
        word: "駅員",
        reading: "えきいん",
        meaning: "Station staff",
        exampleSentenceRuby: "電車の中で財{さい}布{ふ}を拾{ひろ}ったので遺{い}失{しつ}物{ぶつ}係{がかり}の駅{えき}員{いん}さんに届{とど}けた。",
      },
      { 
        word: "駅弁",
        reading: "えきべん",
        meaning: "Station bento",
        exampleSentenceRuby: "列{れつ}車{しゃ}で旅{りょ}行{こう}する楽{たの}しみの一{ひと}つは駅{えき}弁{べん}を食{た}べることだ。",
      },
    ],
    otherWords: [
      { word: "駅", reading: "えき", meaning: "station" },
      { word: "駅ビル", reading: "えきビル", meaning: "station building" },
      { word: "駅長", reading: "えきちょう", meaning: "station master" },
      { word: "東京駅", reading: "とうきょうえき", meaning: "Tokyo station" },
      { word: "名古屋駅", reading: "なごやえき", meaning: "Nagoya station" },
    ],
  },
  469: {
    id: 469,
    kanji: "額",
    kun: ["ひたい"],
    on: ["ガク"],
    meanings: ["forehead", "amount", "framed picture"],
    words: [
      { 
        word: "金額",
        reading: "きんがく",
        meaning: "Amount of money",
        exampleSentenceRuby: "金{きん}額{がく}の多{た}寡{か}にかかわらず領{りょう}収{しゅう}書{しょ}をもらってきてください。",
      },
      { 
        word: "額",
        reading: "がく・ひたい",
        meaning: "Amount・Frame・Forehead",
        exampleSentenceRuby: "収{しゅう}入{にゅう}の額{がく}が少{すく}ない。・その額{がく}は絵{え}に合{あ}わない。・額{ひたい}がせまい。",
      },
      { 
        word: "全額",
        reading: "ぜんがく",
        meaning: "Full amount・Total amount",
        exampleSentenceRuby: "留{りゅう}学{がく}生{せい}の入{にゅう}学{がく}金{きん}を全{ぜん}額{がく}免{めん}除{じょ}する大{だい}学{がく}や専{せん}門{もん}学{がっ}校{こう}がある。",
      },
    ],
    otherWords: [
      { word: "高額（な）", reading: "こうがく（な）", meaning: "high amount・expensive" },
      { word: "小額（な）", reading: "しょうがく（な）", meaning: "small amount・cheap" },
      { word: "多額（な）", reading: "たがく（な）", meaning: "large amount・expensive" },
      { word: "定額", reading: "ていがく", meaning: "fixed amount" },
      { word: "減額（する）", reading: "げんがく（する）", meaning: "reduction (to reduce)" },
      { word: "額面", reading: "がくめん", meaning: "face value" },
    ],
  },
  470: {
    id: 470,
    kanji: "史",
    kun: [],
    on: ["シ"],
    meanings: ["history"],
    words: [
      { 
        word: "歴史",
        reading: "れきし",
        meaning: "history",
        exampleSentenceRuby: "日本の歴{れき}史{し}、特{とく}に近{きん}代{だい}史{し}に興{きょう}味{み}がある。",
      },
      { 
        word: "史上",
        reading: "しじょう",
        meaning: "In history",
        exampleSentenceRuby: "今{こ}年{とし}の夏{なつ}、スイスでは41.5度{ど}の史{し}上{じょう}最{さい}高{こう}気{き}温{おん}を記{き}録{ろく}した。",
      },
      { 
        word: "史跡",
        reading: "しせき",
        meaning: "Historic site",
        exampleSentenceRuby: "奈{な}良{ら}・京{きょう}都{と}の史{し}跡{せき}を訪{たず}ねる。",
      },
    ],
    otherWords: [
      { word: "～史", reading: "～し", meaning: "history" },
      { word: "日本史", reading: "にほんし", meaning: "Japanese history" },
      { word: "世界史", reading: "せかいし", meaning: "World history" },
      { word: "史料", reading: "しりょう", meaning: "historical materials" },
      { word: "史学", reading: "しがく", meaning: "historical science" },
      { word: "女史", reading: "じょし", meaning: "Ms." },
    ],
  },
  471: {
    id: 471,
    kanji: "短",
    kun: ["みじか"],
    on: ["タン"],
    meanings: ["short", "brief"],
    words: [
      { 
        word: "短縮（する）",
        reading: "たんしゅく（する）",
        meaning: "Shortening・reduction・to shorten・to reduce",
        exampleSentenceRuby: "急{きゅう}行{こう}に乗{の}ると各{かく}駅{えき}停{てい}車{しゃ}よりも15分{ふん}時{じ}間{かん}を短{たん}縮{しゅく}できる。",
      },
      { 
        word: "短期間",
        reading: "たんきかん",
        meaning: "Short period of time",
        exampleSentenceRuby: "短{たん}期{き}間{かん}の集{しゅう}中{ちゅう}コースでアラビア語{ご}の初{しょ}歩{ほ}を学{まな}んだ。",
      },
      { 
        word: "短気（な）",
        reading: "たんき（な）",
        meaning: "Quick temper・short-tempered",
        exampleSentenceRuby: "私の短{たん}所{しょ}は短{たん}気{き}なところ、長{ちょう}所{しょ}は楽{らっ}観{かん}的{てき}なところです。",
      },
    ],
    otherWords: [
      { word: "短い", reading: "みじかい", meaning: "short" },
      { word: "短期大学", reading: "たんきだいがく", meaning: "junior college" },
      { word: "短大", reading: "たんだい", meaning: "junior college" },
      { word: "短編（小説）", reading: "たんぺん（しょうせつ）", meaning: "short story" },
      { word: "短文", reading: "たんぶん", meaning: "short sentence" },
      { word: "一長一短", reading: "いっちょういったん", meaning: "pros and cons" },
    ],
  },
  472: {
    id: 472,
    kanji: "株",
    kun: ["かぶ"],
    on: [],
    meanings: ["stock", "share", "stump"],
    words: [
      { 
        word: "株主",
        reading: "かぶぬし",
        meaning: "shareholder",
        exampleSentenceRuby: "株{かぶ}主{ぬし}は株{かぶ}価{か}の変{へん}動{どう}に一{いっ}喜{き}一{いち}憂{ゆう}する。",
      },
      { 
        word: "持ち株",
        reading: "もちかぶ",
        meaning: "owned shares",
        exampleSentenceRuby: "持{も}ち株{かぶ}会{がい}社{しゃ}とは、株{かぶ}式{しき}を保{ほ}有{ゆう}して他{た}社{しゃ}を支{し}配{はい}する親{おや}会{かい}社{しゃ}です。",
      },
      { 
        word: "切り株",
        reading: "きりかぶ",
        meaning: "tree stump",
        exampleSentenceRuby: "これでは、ウサギが切{き}り株{かぶ}にぶつかるのを待{ま}つようなものだ。",
      },
    ],
    otherWords: [
      { word: "株券", reading: "かぶけん", meaning: "stock certificate" },
      { word: "お株", reading: "おかぶ", meaning: "your shares" },
      { word: "成長株", reading: "せいちょうかぶ", meaning: "growth stock" },
      { word: "株式会社", reading: "かぶしきがいしゃ", meaning: "joint-stock company" },
      { word: "株", reading: "かぶ", meaning: "stock" },
    ],
  },
  473: {
    id: 473,
    kanji: "帰",
    kun: ["かえ"],
    on: ["キ"],
    meanings: ["to return", "to go back"],
    words: [
      { 
        word: "復帰（する）",
        reading: "ふっき（する）",
        meaning: "Return・Comeback",
        exampleSentenceRuby: "病{びょう}気{き}で1{いち}年{ねん}休{きゅう}職{しょく}していたが、快{かい}復{ふく}し職{しょく}場{ば}に復{ふっ}帰{き}した。",
      },
      { 
        word: "帰り",
        reading: "かえり",
        meaning: "Return・coming home",
        exampleSentenceRuby: "今日は残{ざん}業{ぎょう}があるから、帰{かえ}りが遅{おそ}くなります。",
      },
      { 
        word: "帰化（する）",
        reading: "きか（する）",
        meaning: "Naturalization・to naturalize",
        exampleSentenceRuby: "日本の国{こく}籍{せき}を取{しゅ}得{とく}し、日本に帰{き}化{か}した。",
      },
    ],
    otherWords: [
      { word: "帰る", reading: "かえる", meaning: "to return" },
      { word: "帰宅（する）", reading: "きたく（する）", meaning: "returning home" },
      { word: "日帰り（する）", reading: "ひがえり（する）", meaning: "day trip" },
      { word: "里帰り（する）", reading: "さとがえり（する）", meaning: "returning to one's hometown" },
      { word: "帰途（につく）", reading: "きと（につく）", meaning: "to set out for home" },
    ],
  },
  474: {
    id: 474,
    kanji: "読",
    kun: ["よ"],
    on: ["ドク"],
    meanings: ["to read"],
    words: [
      { 
        word: "読む",
        reading: "よむ",
        meaning: "to read",
        exampleSentenceRuby: "行{ぎょう}間{かん}を読{よ}む。・相{あい}手{て}の心{こころ}を読{よ}む。・先{さき}を読{よ}む。・その場{ば}の空{くう}気{き}を読{よ}む。",
      },
      { 
        word: "読み",
        reading: "よみ",
        meaning: "Reading・Forecasting",
        exampleSentenceRuby: "この漢{かん}字{じ}の読{よ}みが分からない。・読{よ}みが浅{あさ}い。・読{よ}みが外{はず}れた。",
      },
      { 
        word: "読み取る",
        reading: "よみとる",
        meaning: "Read・Understand",
        exampleSentenceRuby: "本{ほん}文{ぶん}の内{ない}容{よう}が読{よ}み取{と}れない。",
      },
    ],
    otherWords: [
      { word: "読者", reading: "どくしゃ", meaning: "reader" },
      { word: "読み書き", reading: "よみかき", meaning: "reading and writing" },
      { word: "読み上げる", reading: "よみあげる", meaning: "to read aloud" },
      { word: "解読（する）", reading: "かいどく（する）", meaning: "decoding・to decode" },
      { word: "読解（する）", reading: "どっかい（する）", meaning: "reading comprehension・to comprehend" },
    ],
  },
  475: {
    id: 475,
    kanji: "義",
    kun: ["よし"],
    on: ["ギ"],
    meanings: ["righteousness", "justice", "meaning"],
    words: [
      { 
        word: "意義",
        reading: "いぎ",
        meaning: "Significance・meaning",
        exampleSentenceRuby: "参{さん}加{か}する事{こと}に意{い}義{ぎ}があるかどうか考{かんが}えてから参{さん}加{か}するべきです。",
      },
      { 
        word: "定義（する）",
        reading: "ていぎ（する）",
        meaning: "Definition・to define",
        exampleSentenceRuby: "「無{む}」とは何{なに}か、定{てい}義{ぎ}を試{こころ}みてください。",
      },
      { 
        word: "義理",
        reading: "ぎり",
        meaning: "Social duty・obligation",
        exampleSentenceRuby: "彼{かれ}には助{たす}けてもらった義{ぎ}理{り}があるから、頼{たの}まれたらやるしかない。",
      },
    ],
    otherWords: [
      { word: "講義（する）", reading: "こうぎ（する）", meaning: "Lecture・to lecture" },
      { word: "名義", reading: "めいぎ", meaning: "Name・title" },
      { word: "有意義（な）", reading: "ゆういぎ（な）", meaning: "Meaningful・significant" },
      { word: "大義名分", reading: "たいぎめいぶん", meaning: "Justification・grounds" },
      { word: "同義語", reading: "どうぎご", meaning: "Synonym" },
      { word: "類義語", reading: "るいぎご", meaning: "Related term・similar word" },
    ],
  },
  //TODO: add 476 - 480
  481: {
    id: 481,
    kanji: "企",
    kun: ["くわだ"],
    on: ["キ"],
    meanings: ["plan", "undertake"],
    words: [
      { 
        word: "企てる",
        reading: "くわだてる",
        meaning: "to plan・try・plot",
        exampleSentenceRuby: "",
      },
      { 
        word: "企業",
        reading: "きぎょう",
        meaning: "enterprise・business・company",
        exampleSentenceRuby: "",
      },
      { 
        word: "企画（する）",
        reading: "きかく（する）",
        meaning: "Planning・to plan",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "中小企業", reading: "ちゅうしょうきぎょう", meaning: "small and medium-sized enterprises" },
      { word: "多国籍企業", reading: "たこくせききぎょう", meaning: "multinational corporation" },
      { word: "大企業", reading: "だいきぎょう", meaning: "large corporation" },
    ],
  },
  482: {
    id: 482,
    kanji: "財",
    kun: [],
    on: ["ザイ"],
    meanings: ["wealth", "property", "assets"],
    words: [
      { 
        word: "財布",
        reading: "さいふ",
        meaning: "wallet",
        exampleSentenceRuby: "",
      },
      { 
        word: "財源",
        reading: "ざいげん",
        meaning: "financial resources・funding source・revenue source",
        exampleSentenceRuby: "",
      },
      { 
        word: "文化財",
        reading: "ぶんかざい",
        meaning: "cultural assets",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "財", reading: "ざい", meaning: "wealth・assets" },
      { word: "財団・財団法人", reading: "ざいだん・ざいだんほうじん", meaning: "foundation・public interest corporation" },
      { word: "財務", reading: "ざいむ", meaning: "financial affairs・accounting" },
      { word: "私財", reading: "しざい", meaning: "private assets" },
      { word: "財力", reading: "ざいりょく", meaning: "financial power・wealth" },
    ],
  },
  483: {
    id: 483,
    kanji: "限",
    kun: ["かぎ"],
    on: ["ゲン"],
    meanings: ["limit", "restrict"],
    words: [
      { 
        word: "限る",
        reading: "かぎる",
        meaning: "set a limit・to restrict",
        exampleSentenceRuby: "",
      },
      { 
        word: "限り・～限り",
        reading: "かぎり・～かぎり",
        meaning: "limit・as far as・as long as",
        exampleSentenceRuby: "",
      },
      { 
        word: "極限",
        reading: "きょくげん",
        meaning: "extreme limit・utmost",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "無期限", reading: "むきげん", meaning: "indefinite・unlimited" },
      { word: "無制限（な）", reading: "むせいげん（な）", meaning: "unlimited・unrestricted" },
      { word: "無限（な・の）", reading: "むげん（な・の）", meaning: "infinite・limitless" },
      { word: "有限（な・の）", reading: "ゆうげん（な・の）", meaning: "limited・finite" },
      { word: "時限", reading: "じげん", meaning: "time limit・deadline" },
      { word: "見限る", reading: "みかぎる", meaning: "to give up on・to abandon" },
    ],
  },
  484: {
    id: 484,
    kanji: "週",
    kun: [],
    on: ["シュウ"],
    meanings: ["week"],
    words: [
      { 
        word: "週明け",
        reading: "しゅうあけ",
        meaning: "beginning of the week・Next monday",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "週休",
        reading: "しゅうきゅう",
        meaning: "weekly day off",
        exampleSentenceRuby: "",
      },
      { 
        word: "隔週",
        reading: "かくしゅう",
        meaning: "biweekly・every other week",
        exampleSentenceRuby: "",
      },
    ],
    otherWords: [
      { word: "先週・今週・来週", reading: "せんしゅう・こんしゅう・らいしゅう", meaning: "last week・this week・next week" },
      { word: "毎週", reading: "まいしゅう", meaning: "every week" },
      { word: "翌週", reading: "よくしゅう", meaning: "the following week" },
      { word: "週刊", reading: "しゅうかん", meaning: "weekly" },
      { word: "週・〜週", reading: "しゅう・〜しゅう", meaning: "week・〜week" },
    ],
  },
  485: {
    id: 485,
    kanji: "造",
    kun: ["つく"],
    on: ["ゾウ"],
    meanings: ["to make", "to create", "to build"],
    words: [
      { 
        word: "造る",
        reading: "つくる",
        meaning: "to make・to build・to create",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "構造",
        reading: "こうぞう",
        meaning: "structure・construction",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "創造（する）",
        reading: "そうぞう（する）",
        meaning: "creation・to create",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "偽造（する）", reading: "ぎぞう（する）", meaning: "forgery・to forge" },
      { word: "建造（する）", reading: "けんぞう（する）", meaning: "construction・to construct" },
      { word: "造成（する）", reading: "ぞうせい（する）", meaning: "development・to develop" },
      { word: "造形", reading: "ぞうけい", meaning: "modeling・sculpture" },
      { word: "造語（する）", reading: "ぞうご（する）", meaning: "neologism・to coin a word" },
    ],
  },
  486: {
    id: 486,
    kanji: "勢",
    kun: ["いきお"],
    on: ["セイ"],
    meanings: ["force", "energy", "vigor"],
    words: [
      { 
        word: "勢い",
        reading: "いきおい",
        meaning: "power・energy・force",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "勢力",
        reading: "せいりょく",
        meaning: "influence・power・strength",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "情勢",
        reading: "じょうせい",
        meaning: "situation・state of affairs",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "大勢", reading: "おおぜい・たいせい", meaning: "great number of people・crowd" },
      { word: "形勢", reading: "けいせい", meaning: "situation・state of affairs" },
      { word: "体勢", reading: "たいせい", meaning: "posture・position" },
      { word: "総勢", reading: "そうぜい", meaning: "total number of people" },
      { word: "優勢（な）", reading: "ゆうせい（な）", meaning: "superior・dominant" },
    ],
  },
  487: {
    id: 487,
    kanji: "券",
    kun: [],
    on: ["ケン"],
    meanings: ["ticket", "certificate"],
    words: [
      { 
        word: "乗車券",
        reading: "じょうしゃけん",
        meaning: "boarding ticket・ride ticket (train, bus, etc)",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "回数券",
        reading: "かいすうけん",
        meaning: "book of tickets・coupon ticket",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "定期券",
        reading: "ていきけん",
        meaning: "commuter pass・season ticket",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "券・～券", reading: "けん・～けん", meaning: "ticket・~ticket" },
      { word: "証券・有価証券", reading: "しょうけん・ゆうかしょうけん", meaning: "security・valuable security" },
      { word: "証券会社", reading: "しょうけんがいしゃ", meaning: "securities company" },
      { word: "債券", reading: "さいけん", meaning: "bond" },
      { word: "商品券", reading: "しょうひんけん", meaning: "merchandise voucher" },
    ],
  },
  488: {
    id: 488,
    kanji: "酒",
    kun: ["さけ・さか"],
    on: ["シュ"],
    meanings: ["alcohol", "sake"],
    words: [
      { 
        word: "酒",
        reading: "さけ",
        meaning: "alcohol・alcoholic drink・sake",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "飲酒",
        reading: "いんしゅ",
        meaning: "drinking alcohol",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "酒屋",
        reading: "さかや",
        meaning: "liquor store・sake shop",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "酒税", reading: "しゅぜい", meaning: "alcohol tax" },
      { word: "洋酒", reading: "ようしゅ", meaning: "Western liquor" },
      { word: "酒造", reading: "しゅぞう", meaning: "sake brewing" },
      { word: "禁酒（する）", reading: "きんしゅ（する）", meaning: "prohibition of alcohol・to prohibit alcohol" },
      { word: "蒸留酒•釀造酒", reading: "じょうりゅうしゅ・にょうぞうしゅ", meaning: "distilled liquor・brewed liquor" },
    ],
  },
  489: {
    id: 489,
    kanji: "江",
    kun: ["え"],
    on: ["コウ"],
    meanings: ["inlet", "bay", "creek"],
    words: [
      { 
        word: "江戸",
        reading: "えど",
        meaning: "Edo (old name of Tokyo)",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "江戸っ子",
        reading: "えどっこ",
        meaning: "person born and raised in Edo (Tokyo)",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "入り江",
        reading: "いりえ",
        meaning: "inlet・bay・cove",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "江ノ島〔神奈川県〕", reading: "えのしま〔かながわけん〕", meaning: "Enoshima (Kanagawa Prefecture)" },
      { word: "東京都江東区", reading: "とうきょうとこうとうく", meaning: "Koto Ward, Tokyo" },
      { word: "大江さん", reading: "おおえさん", meaning: "Mr./Ms. Oe" },
      { word: "江川さん", reading: "えがわさん", meaning: "Mr. Egawa" },
    ],
  },
  490: {
    id: 490,
    kanji: "冷",
    kun: ["つめ・ひ・さ"],
    on: ["レイ"],
    meanings: ["cold", "chill"],
    words: [
      { 
        word: "冷たい",
        reading: "つめたい",
        meaning: "cold (to the touch)・chilly",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "冷める・冷ます",
        reading: "さめる・さます",
        meaning: "to get cold・to cool (something) down",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "冷える・冷やす",
        reading: "ひえる・ひやす",
        meaning: "to become cold・to cool down",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "冷蔵庫・冷凍庫", reading: "れいぞうこ・れいとうこ", meaning: "refrigerator・freezer" },
      { word: "冷暖房・冷房", reading: "れいだんぼう・れいぼう", meaning: "heating and cooling・cooling" },
      { word: "冷水", reading: "れいすい", meaning: "cold water" },
      { word: "冷却（する）", reading: "れいきゃく（する）", meaning: "cooling (to cool down)" },
      { word: "冷え込む", reading: "ひえこむ", meaning: "to get cold" },
    ],
  },
  491: {
    id: 491,
    kanji: "兵",
    kun: ["つわもの"],
    on: ["ヘイ", "ヒョウ"],
    meanings: ["soldier", "warrior"],
    words: [
      { 
        word: "核兵器",
        reading: "かくへいき",
        meaning: "nuclear weapon",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "化学兵器",
        reading: "かがくへいき",
        meaning: "chemical weapon",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "兵士",
        reading: "へいし",
        meaning: "soldier",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "兵", reading: "へい", meaning: "soldier" },
      { word: "兵隊", reading: "へいたい", meaning: "troops" },
      { word: "兵力", reading: "へいりょく", meaning: "military strength" },
      { word: "兵役", reading: "へいえき", meaning: "military service" },
      { word: "徴兵", reading: "ちょうへい", meaning: "conscription" },
    ],
  },
  492: {
    id: 492,
    kanji: "福",
    kun: [],
    on: ["フク"],
    meanings: ["good fortune", "blessing"],
    words: [
      { 
        word: "福祉",
        reading: "ふくし",
        meaning: "welfare・well-being",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "祝福（する）",
        reading: "しゅくふく（する）",
        meaning: "blessing (to bless)",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "福",
        reading: "ふく",
        meaning: "good fortune・blessing・good luck",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "社会福祉", reading: "しゃかいふくし", meaning: "social welfare" },
      { word: "福袋", reading: "ふくぶくろ", meaning: "lucky bag" },
      { word: "大福", reading: "だいふく", meaning: "thick rice cake" },
      { word: "裕福（な）", reading: "ゆうふく（な）", meaning: "wealthy" },
      { word: "冥福（在祈 ）", reading: "めいふく（ざいき）", meaning: "rest in peace" },
    ],
  },
  493: {
    id: 493,
    kanji: "船",
    kun: ["ふね・ふな"],
    on: ["セン"],
    meanings: ["ship", "boat"],
    words: [
      { 
        word: "造船（する）",
        reading: "ぞうせん（する）",
        meaning: "shipbuilding (to build ships)",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "乗船（する）",
        reading: "じょうせん（する）",
        meaning: "boarding (to board a ship)",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "船出（する）",
        reading: "ふなで（する）",
        meaning: "setting sail (to set sail)",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "船", reading: "ふね", meaning: "ship・boat" },
      { word: "船長", reading: "せんちょう", meaning: "captain" },
      { word: "客船", reading: "きゃくせん", meaning: "passenger ship" },
      { word: "船員", reading: "せんいん", meaning: "crew member" },
      { word: "飛行船", reading: "ひこうせん", meaning: "airship" },
    ],
  },
  494: {
    id: 494,
    kanji: "満",
    kun: ["み"],
    on: ["マン"],
    meanings: ["full", "satisfied"],
    words: [
      { 
        word: "未満",
        reading: "みまん",
        meaning: "less than・under・below・insufficient",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "満たない",
        reading: "みたない",
        meaning: "less than・below・not full・insufficient",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "円満（な）",
        reading: "えんまん（な）",
        meaning: "peaceful・harmonious",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "満たす・満ちる", reading: "みたす・みちる", meaning: "to fill・to be full" },
      { word: "満点", reading: "まんてん", meaning: "full marks・perfect score" },
      { word: "満期", reading: "まんき", meaning: "expiration・maturity" },
      { word: "満月", reading: "まんげつ", meaning: "full moon" },
      { word: "満開", reading: "まんかい", meaning: "full bloom" },
    ],
  },
  495: {
    id: 495,
    kanji: "査",
    kun: [],
    on: ["サ"],
    meanings: ["investigate", "examine"],
    words: [
      { 
        word: "検査（する）",
        reading: "けんさ（する）",
        meaning: "inspection (to inspect)・check",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "審査（する）",
        reading: "しんさ（する）",
        meaning: "examination (to examine)・judging",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "査察（する）",
        reading: "ささつ（する）",
        meaning: "inspection (to inspect)・examination",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "国勢調査", reading: "こくせいちょうさ", meaning: "national census" },
      { word: "市場調査", reading: "しじょうちょうさ", meaning: "market research" },
      { word: "監査（する）", reading: "かんさ（する）", meaning: "audit (to audit)" },
      { word: "査定（する）", reading: "さてい（する）", meaning: "assessment (to assess)" },
      { word: "巡査", reading: "じゅんさ", meaning: "patrolman" },
    ],
  },
  496: {
    id: 496,
    kanji: "薬",
    kun: ["くすり"],
    on: ["ヤク"],
    meanings: ["medicine", "drug"],
    words: [
      { 
        word: "薬・～薬",
        reading: "くすり・〜ぐすり・やく",
        meaning: "medicine・drug",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "農薬",
        reading: "のうやく",
        meaning: "agricultural chemicals・pesticides",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "薬品",
        reading: "やくひん",
        meaning: "medicinea・druga",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "薬物", reading: "やくぶつ", meaning: "drugs・medicinal substances" },
      { word: "薬剤師", reading: "やくざいし", meaning: "pharmacist" },
      { word: "火薬", reading: "かやく", meaning: "gunpowder" },
      { word: "目薬", reading: "めぐすり", meaning: "eye drops" },
      { word: "漢方薬", reading: "かんぽうやく", meaning: "Chinese herbal medicine" },
    ],
  },
  497: {
    id: 497,
    kanji: "転",
    kun: ["ころ"],
    on: ["テン"],
    meanings: ["rotate", "turn"],
    words: [
      { 
        word: "逆転（する）",
        reading: "ぎゃくてん（する）",
        meaning: "reversal (to reverse)・turnaround",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "移転（する）",
        reading: "いてん（する）",
        meaning: "relocation (to relocate)・transfer",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "転換（する）",
        reading: "てんかん（する）",
        meaning: "conversion (to convert)・turnaround",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "自転車", reading: "じてんしゃ", meaning: "bicycle" },
      { word: "転じる", reading: "てんじる", meaning: "to change (one's course)" },
      { word: "転勤（する）", reading: "てんきん（する）", meaning: "transfer (to transfer)" },
      { word: "転ぶ・転がる", reading: "ころぶ・ころがる", meaning: "to fall・to roll" },
      { word: "転落（する）", reading: "てんらく（する）", meaning: "falling (to fall)・drop" },
    ],
  },
  498: {
    id: 498,
    kanji: "君",
    kun: ["きみ"],
    on: ["クン"],
    meanings: ["you", "buddy"],
    words: [
      { 
        word: "君",
        reading: "きみ",
        meaning: "you",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "〜君",
        reading: "〜くん",
        meaning: "Mr.・Ms.",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "諸君",
        reading: "しょくん",
        meaning: "you・gentlemen",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "君臨（する）", reading: "くんりん（する）", meaning: "to reign over" },
      { word: "君主", reading: "くんしゅ", meaning: "monarch" },
      { word: "君子", reading: "くんし", meaning: "gentleman" },
      { word: "暴君", reading: "ぼうくん", meaning: "tyrant" },
    ],
  },
  499: {
    id: 499,
    kanji: "量",
    kun: ["はか"],
    on: ["リョウ"],
    meanings: ["quantity", "amount"],
    words: [
      { 
        word: "大量",
        reading: "たいりょう",
        meaning: "large quantity",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "減量（する）",
        reading: "げんりょう（する）",
        meaning: "reduction・to reduce the quantity/amount",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "力量",
        reading: "りきりょう",
        meaning: "power・ability・capability",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "量・〜量", reading: "りょう・〜りょう", meaning: "quantity・amount" },
      { word: "量る", reading: "はかる", meaning: "to measure" },
      { word: "数量", reading: "すうりょう", meaning: "quantity・amount" },
      { word: "重量", reading: "じゅうりょう", meaning: "weight" },
      { word: "測量（する）", reading: "そくりょう（する）", meaning: "surveying (to survey)" },
    ],
  },
  500: {
    id: 500,
    kanji: "武",
    kun: ["たけ"],
    on: ["ブ", "ム"],
    meanings: ["military", "warrior"],
    words: [
      { 
        word: "武力",
        reading: "ぶりょく",
        meaning: "military power",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "武装（する）",
        reading: "ぶそう（する）",
        meaning: "armament・ (to arm)",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "武士",
        reading: "ぶし",
        meaning: "warrior・samurai",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "武道", reading: "ぶどう", meaning: "martial arts" },
      { word: "武術", reading: "ぶじゅつ", meaning: "martial arts" },
      { word: "武家", reading: "ぶけ", meaning: "warrior family" },
      { word: "影武者", reading: "かげむしゃ", meaning: "shadow warrior" },
      { word: "武士道", reading: "ぶしどう", meaning: "the way of the samurai" },
    ],
  },
  501: {
    id: 501,
    kanji: "整",
    kun: ["ととの"],
    on: ["セイ"],
    meanings: ["organize", "arrange"],
    words: [
      { 
        word: "整備（する）",
        reading: "せいび（する）",
        meaning: "maintenance・to maintain",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "整う",
        reading: "ととのう",
        meaning: "to be prepared・to be in order",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "整える",
        reading: "ととのえる",
        meaning: "to arrange・to prepare・to put in order",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "整列（する）", reading: "せいれつ（する）", meaning: "to arrange in order" },
      { word: "整形（する）", reading: "せいけい（する）", meaning: "to shape・to form" },
      { word: "整然（と）", reading: "せいぜん（と）", meaning: "orderly" },
      { word: "整地（する）", reading: "せいち（する）", meaning: "to level・to grade" },
      { word: "整数", reading: "せいすう", meaning: "integer" },
    ],
  },
  502: {
    id: 502,
    kanji: "未",
    kun: ["いま"],
    on: ["ミ"],
    meanings: ["not yet", "un-"],
    words: [
      { 
        word: "未定（な・の）",
        reading: "みてい（な・の）",
        meaning: "undecided・unfixed",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "未知",
        reading: "みち",
        meaning: "unknown・strange",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "未だ（に）",
        reading: "いまだ（に）",
        meaning: "still・not yet",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "未明", reading: "みめい", meaning: "dawn・daybreak" },
      { word: "未払い", reading: "みはらい・みばらい", meaning: "unpaid" },
      { word: "未知数", reading: "みちすう", meaning: "unknown quantity" },
      { word: "未発表", reading: "みはっぴょう", meaning: "unpublished" },
      { word: "未～", reading: "み～", meaning: "un~" },
    ],
  },
  503: {
    id: 503,
    kanji: "観",
    kun: ["みる"],
    on: ["カン"],
    meanings: ["observe", "view"],
    words: [
      { 
        word: "観察（する）",
        reading: "かんさつ（する）",
        meaning: "observation・to observe",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "観点",
        reading: "かんてん",
        meaning: "point of view",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "〜観",
        reading: "〜かん",
        meaning: "view of ~・outlook on ~",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "観測（する）", reading: "かんそく（する）", meaning: "observation・to observe" },
      { word: "観戦（する）", reading: "かんせん（する）", meaning: "viewing (a game)・to watch (a game)" },
      { word: "観念（する）", reading: "かんねん（する）", meaning: "concept・to conceive" },
      { word: "外観", reading: "がいかん", meaning: "external appearance" },
      { word: "参観（する）", reading: "さんかん（する）", meaning: "visiting (a place)・to visit (a place)" },
    ],
  },
  504: {
    id: 504,
    kanji: "営",
    kun: ["いとな"],
    on: ["エイ"],
    meanings: ["perform", "conduct", "manage"],
    words: [
      { 
        word: "営業（する）",
        reading: "えいぎょう（する）",
        meaning: "business・to do business",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "営む",
        reading: "いとなむ",
        meaning: "to conduct・to manage",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "陣営",
        reading: "じんえい",
        meaning: "camp・quarters",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "国営・民営・私営", reading: "こくえい・みんえい・しえい", meaning: "national・private・public" },
      { word: "都営・県営・市営", reading: "とえい・けんえい・しえい", meaning: "metropolitan・prefectural・municipal" },
      { word: "直営（する）", reading: "ちょくえい（する）", meaning: "direct management・to manage directly" },
      { word: "営利", reading: "えいり", meaning: "profit・commercial" },
      { word: "設営（する）", reading: "せつえい（する）", meaning: "to set up・to establish" },
    ],
  },
  505: {
    id: 505,
    kanji: "夢",
    kun: ["ゆめ"],
    on: ["ム"],
    meanings: ["dream"],
    words: [
      { 
        word: "夢",
        reading: "ゆめ",
        meaning: "dream",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "夢中（な）",
        reading: "むちゅう（な）",
        meaning: "absorbed・crazy about・madly",
        exampleSentenceRuby: "xxxxx",
      },
      { 
        word: "夢にも",
        reading: "ゆめにも",
        meaning: "even in dreams・never dream that (used in negative sentences)",
        exampleSentenceRuby: "xxxxx",
      },
    ],
    otherWords: [
      { word: "夢見る", reading: "ゆめみる", meaning: "to dream" },
      { word: "悪夢", reading: "あくむ", meaning: "nightmare" },
      { word: "夢物語", reading: "ゆめものがたり", meaning: "dream story" },
      { word: "無我夢中", reading: "むがむちゅう", meaning: "selfless absorption" },
      { word: "夢想（する）", reading: "むそう（する）", meaning: "to dream" },
    ],
  },
}

export default M2_KANJI;