import { 
  WORDS_GENKI_LESSON_13,
  WORDS_GENKI_LESSON_14,
  WORDS_GENKI_LESSON_15,
  WORDS_GENKI_LESSON_16
} from "./genki";

import { 
  WORD_YDC_LESSON_1,
  WORD_YDC_LESSON_2,
  WORD_YDC_LESSON_3,
  WORD_YDC_LESSON_4,
  WORD_YDC_LESSON_5,
  WORD_YDC_LESSON_6,
  WORD_YDC_LESSON_7,
  WORD_YDC_LESSON_8,
  WORD_YDC_LESSON_9,
  WORD_YDC_LESSON_10,
  WORD_YDC_LESSON_11,
  WORD_YDC_LESSON_12,
  WORD_YDC_LESSON_13,
  WORD_YDC_LESSON_14,
  WORD_YDC_LESSON_15,
  WORD_YDC_LESSON_16,
  WORD_YDC_LESSON_17,
  WORD_YDC_LESSON_18,
  WORD_YDC_LESSON_19,
  WORD_YDC_LESSON_20,
  WORD_YDC_LESSON_21,
  WORD_YDC_LESSON_22,
  WORD_YDC_LESSON_23,
  WORD_YDC_LESSON_24,
  WORD_YDC_LESSON_25
} from "./YDC";


export const WORDS_OBJECT = {
  1: WORD_YDC_LESSON_1,
  2: WORD_YDC_LESSON_2,
  3: WORD_YDC_LESSON_3,
  4: WORD_YDC_LESSON_4,
  5: WORD_YDC_LESSON_5,
  6: WORD_YDC_LESSON_6,
  7: WORD_YDC_LESSON_7,
  8: WORD_YDC_LESSON_8,
  9: WORD_YDC_LESSON_9,
  10: WORD_YDC_LESSON_10,
  11: WORD_YDC_LESSON_11,
  12: WORD_YDC_LESSON_12,
  13: WORD_YDC_LESSON_13,
  14: WORD_YDC_LESSON_14,
  15: WORD_YDC_LESSON_15,
  16: WORD_YDC_LESSON_16,
  17: WORD_YDC_LESSON_17,
  18: WORD_YDC_LESSON_18,
  19: WORD_YDC_LESSON_19,
  20: WORD_YDC_LESSON_20,
  21: WORD_YDC_LESSON_21,
  22: WORD_YDC_LESSON_22,
  23: WORD_YDC_LESSON_23,
  24: WORD_YDC_LESSON_24,
  25: WORD_YDC_LESSON_25,
};

export const GENKI_WORDS_OBJECT = {
  13: WORDS_GENKI_LESSON_13,
  14: WORDS_GENKI_LESSON_14,
  15: WORDS_GENKI_LESSON_15,
  16: WORDS_GENKI_LESSON_16,
};