export const kanji: KanjiWithExample[] = [
  {
    id: 1,
    word: '特に',
    reading: 'とくに',
    meaning: 'specially',
    example: '特に何もない',
    exampleReading: 'とくになにもない',
    exampleMeaning: 'Nothing special',
    radicals: [],
    level: 13
  },
  {
    id: 2,
    word: '昼ご飯',
    reading: 'ひるごはん',
    meaning: 'lunch',
    example: '昼ご飯を食べる',
    exampleReading: 'ひるごはんをたべる',
    exampleMeaning: 'Eat lunch',
    radicals: [],
    level: 13
  },
  {
    id: 3,
    word: '安い',
    reading: 'やすい',
    meaning: 'cheap',
    example: 'その店は安い',
    exampleReading: 'そのみせはやすい',
    exampleMeaning: 'That store is cheap',
    radicals: [],
    level: 13
  },
  {
    id: 4,
    word: '高い',
    reading: 'たかい',
    meaning: 'expensive',
    example: 'その店は高い',
    exampleReading: 'そのみせはたかい',
    exampleMeaning: 'That store is expensive',
    radicals: [],
    level: 13
  },
  {
    id: 5,
    word: '同じ',
    reading: 'おなじ',
    meaning: 'same',
    example: '同じ色',
    exampleReading: 'おなじいろ',
    exampleMeaning: 'Same color',
    radicals: [],
    level: 13
  },
  {
    id: 6,
    word: '体',
    reading: 'からだ',
    meaning: 'body',
    example: '体が痛い',
    exampleReading: 'からだがいたい',
    exampleMeaning: 'Body hurts',
    radicals: [],
    level: 13
  },
  {
    id: 7,
    word: '物',
    reading: 'もの',
    meaning: 'thing',
    example: 'その物は何？',
    exampleReading: 'そのものはなに？',
    exampleMeaning: 'What is that thing?',
    radicals: [],
    level: 13
  },
  {
    id: 8,
    word: '雨',
    reading: 'あめ',
    meaning: 'rain',
    example: '雨が降る',
    exampleReading: 'あめがふる',
    exampleMeaning: 'Rain falls',
    radicals: [],
    level: 13
  }, 
  {
    id: 9,
    word: '肉',
    reading: 'にく',
    meaning: 'meat',
    example: '肉を食べる',
    exampleReading: 'にくをたべる',
    exampleMeaning: 'Eat meat',
    radicals: [],
    level: 13
  },
  {
    id: 10,
    word: '毎日',
    reading: 'まいにち',
    meaning: 'everyday',
    example: '毎日勉強する',
    exampleReading: 'まいにちべんきょうする',
    exampleMeaning: 'Study everyday',
    radicals: [],
    level: 13
  },
  {
    id: 11,
    word: '犬',
    reading: 'いぬ',
    meaning: 'dog',
    example: '犬が好き',
    exampleReading: 'いぬがすき',
    exampleMeaning: 'I like dogs',
    radicals: [],
    level: 13
  },
  {
    id: 12,
    word: '猫',
    reading: 'ねこ',
    meaning: 'cat',
    example: '猫が好き',
    exampleReading: 'ねこがすき',
    exampleMeaning: 'I like cats',
    radicals: [],
    level: 13
  },
  {
    id: 13,
    word: '魚',
    reading: 'さかな',
    meaning: 'fish',
    example: '魚を食べる',
    exampleReading: 'さかなをたべる',
    exampleMeaning: 'Eat fish',
    radicals: [],
    level: 13
  },
  {
    id: 14,
    word: '鳥',
    reading: 'とり',
    meaning: 'bird',
    example: '鳥が飛ぶ',
    exampleReading: 'とりがとぶ',
    exampleMeaning: 'Bird flies',
    radicals: [],
    level: 13
  },
  {
    id: 15,
    word: '海',
    reading: 'うみ',
    meaning: 'sea',
    example: '海に行く',
    exampleReading: 'うみにいく',
    exampleMeaning: 'Go to the sea',
    radicals: [],
    level: 13
  },
  {
    id: 16,
    word: '日本海',
    reading: 'にほんかい',
    meaning: 'Sea of Japan',
    example: '日本海に行く',
    exampleReading: 'にほんかいにいく',
    exampleMeaning: 'Go to the Sea of Japan',
    radicals: [],
    level: 13
  },
  {
    id: 17,
    word: '海外',
    reading: 'かいがい',
    meaning: 'overseas',
    example: '海外に行く',
    exampleReading: 'かいがいにいく',
    exampleMeaning: 'Go overseas',
    radicals: [],
    level: 13
  },
  {
    id: 18,
    word: '山',
    reading: 'やま',
    meaning: 'mountain',
    example: '山に登る',
    exampleReading: 'やまにのぼる',
    exampleMeaning: 'Climb the mountain',
    radicals: [],
    level: 8,
  },
  {
    id: 19,
    word: '川',
    reading: 'かわ',
    meaning: 'river',
    example: '川を泳ぐ',
    exampleReading: 'かわをおよぐ',
    exampleMeaning: 'Swim in the river',
    radicals: [],
    level: 8,
  },
  {
    id: 20,
    word: '町',
    reading: 'まち',
    meaning: 'town',
    example: '町に住む',
    exampleReading: 'まちにすむ',
    exampleMeaning: 'Live in the town',
    radicals: [],
    level: 8,
  },
  {
    id: 21,
    word: '料理',
    reading: 'りょうり',
    meaning: 'cooking',
    example: '料理をする',
    exampleReading: 'りょうりをする',
    exampleMeaning: 'Cook',
    radicals: [],
    level: 13,
  },
  {
    id: 22,
    word: '料',
    reading: 'りょう',
    meaning: 'ingredients, fare',
    example: '料金',
    exampleReading: 'りょうきん',
    exampleMeaning: 'fee',
    radicals: [],
    level: 13,
  },
  {
    id: 23,
    word: '理',
    reading: 'り',
    meaning: 'reason, logic',
    example: '理由',
    exampleReading: 'りゆう',
    exampleMeaning: 'reason',
    radicals: [],
    level: 13,
  },
  {
    id: 24,
    word: '悪い',
    reading: 'わるい',
    meaning: 'bad',
    example: '悪い人',
    exampleReading: 'わるいひと',
    exampleMeaning: 'Bad person',
    radicals: [],
    level: 13,
  },
  {
    id: 25,
    word: '良い',
    reading: 'よい',
    meaning: 'good',
    example: '良い人',
    exampleReading: 'よいひと',
    exampleMeaning: 'Good person',
    radicals: [],
    level: 13,
  },
  {
    id: 26,
    word: '新しい',
    reading: 'あたらしい',
    meaning: 'new',
    example: '新しい車',
    exampleReading: 'あたらしいくるま',
    exampleMeaning: 'New car',
    radicals: [],
    level: 13,
  },
  {
    id: 27,
    word: '古い',
    reading: 'ふるい',
    meaning: 'old',
    example: '古い家',
    exampleReading: 'ふるいいえ',
    exampleMeaning: 'Old house',
    radicals: [],
    level: 13,
  },
  {
    id: 28,
    word: '空',
    reading: 'そら',
    meaning: 'sky',
    example: '空が青い',
    exampleReading: 'そらがあおい',
    exampleMeaning: 'The sky is blue',
    radicals: [],
    level: 13,
  },
  {
    id: 29,
    word: '空港',
    reading: 'くうこう',
    meaning: 'airport',
    example: '空港に行く',
    exampleReading: 'くうこうにいく',
    exampleMeaning: 'Go to the airport',
    radicals: [],
    level: 13,
  }
]