export const VOCABS_N3: TVocabJLPT[] = [
  //
  // From past JLPT exams
  //
  {
    word: "割る",
    reading: "わる",
    meaning: "to break, to divide, to split",
    example: "皿を割る。",
    exampleReading: "さらをわる。",
    exampleMeaning: "to break a plate",
    type: ["う verb"],
    _JLPT: true,   
  },
  {
    word: "基本",
    reading: "きほん",
    meaning: "basis, foundation, principle",
    example: "基本を学ぶことが大切だ。",
    exampleReading: "きほんをまなぶことがたいせつだ。",
    exampleMeaning: "Learning the basics is important.",
    type: ["noun", "な adjective"],
    _JLPT: true,
  },
  {
    word: "基本的",
    reading: "きほんてき",
    meaning: "fundamental, basic, essential",
    example: "基本的な知識を身につける。",
    exampleReading: "きほんてきなちしきをみにつける。",
    exampleMeaning: "to acquire fundamental knowledge",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "基本的に",
    reading: "きほんてきに",
    meaning: "basically, fundamentally",
    example: "基本的に、私は賛成です。",
    exampleReading: "きほんてきに、わたしはさんせいです。",
    exampleMeaning: "Basically, I agree.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "横",
    reading: "よこ",
    meaning: "side, horizontal, sideways, beside, Lateral",
    example: "横に座る。",
    exampleReading: "よこにすわる。",
    exampleMeaning: "to sit beside",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "横断する",
    reading: "おうだんする",
    meaning: "to cross, to traverse",
    example: "道路を横断する。",
    exampleReading: "どうろをおうだんする。",
    exampleMeaning: "to cross the road",
    type: ["する verb"],
    _JLPT: true,
  },
  {
    word: "横断歩道",
    reading: "おうだんほどう",
    meaning: "crosswalk, pedestrian crossing",
    example: "横断歩道を渡る。",
    exampleReading: "おうだんほどうをわたる。",
    exampleMeaning: "to cross the crosswalk",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "横断になる",
    reading: "おうだんになる",
    meaning: "to lie down",
    example: "彼は横断になって休む。",
    exampleReading: "かれはおうだんになってやすむ。",
    exampleMeaning: "He lies down to rest.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "横断を向く",
    reading: "おうだんをむく",
    meaning: "to turn sideways",
    example: "彼は横断を向いて話す。",
    exampleReading: "かれはおうだんをむいてはなす。",
    exampleMeaning: "He turns sideways to talk.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "横並び",
    reading: "よこならび",
    meaning: "side by side, in a row",
    example: "子供たちが横並びに座っている。",
    exampleReading: "こどもたちがよこならびにすわっている。",
    exampleMeaning: "The children are sitting side by side.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "包丁",
    reading: "ほうちょう",
    meaning: "kitchen knife, cooking knife",
    example: "包丁で野菜を切る。",
    exampleReading: "ほうちょうでやさいをきる。",
    exampleMeaning: "to cut vegetables with a kitchen knife",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "適当",
    reading: "てきとう",
    meaning: "suitable, appropriate, proper, reasonable",
    example: "適当な服装で来てください。",
    exampleReading: "てきとうなふくそうできてください。",
    exampleMeaning: "Please come in appropriate attire.",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "適当",
    reading: "てきとう",
    meaning: "sloppy, careless, irresponsible",
    example: "彼は適当に仕事をする。",
    exampleReading: "かれはてきとうにしごとをする。",
    exampleMeaning: "He does his work carelessly.",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "適当に",
    reading: "てきとうに",
    meaning: "suitably, appropriately, reasonably",
    example: "適当に答えてください。",
    exampleReading: "てきとうにこたえてください。",
    exampleMeaning: "Please answer appropriately.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "家具",
    reading: "かぐ",
    meaning: "furniture, furnishings",
    example: "新しい家具を買う。",
    exampleReading: "あたらしいかぐをかう。",
    exampleMeaning: "to buy new furniture",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "具",
    reading: "ぐ",
    meaning: "tool, equipment, utensil, part",
    example: "料理の具を切る。",
    exampleReading: "りょうりのぐをきる。",
    exampleMeaning: "to cut the ingredients for cooking",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "組み立て家具",
    reading: "くみたてかぐ",
    meaning: "flat-pack furniture, ready-to-assemble furniture",
    example: "組み立て家具を買って組み立てる。",
    exampleReading: "くみたてかぐをかってくみたてる。",
    exampleMeaning: "to buy flat-pack furniture and assemble it",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "解く",
    reading: "とく",
    meaning: "to solve, to untie, to unfasten",
    example: "この問題を解いてください。",
    exampleReading: "このもんだいをといてください。",
    exampleMeaning: "Please solve this problem.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "腰",
    reading: "こし",
    meaning: "waist, lower back",
    example: "長時間座っていて腰が痛い。",
    exampleReading: "ちょうじかんすわっていてこしがいたい。",
    exampleMeaning: "My lower back hurts from sitting for a long time.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "腰を上げる",
    reading: "こしをあげる",
    meaning: "to finally take action,to get up, to start moving",
    example: "やっと腰を上げて勉強を始めた。",
    exampleReading: "やっとこしをあげてべんきょうをはじめた。",
    exampleMeaning: "I finally took action and started studying.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "腰が重い",
    reading: "こしがおもい",
    meaning: "to be slow to act, to be reluctant to take action",
    example: "彼は腰が重いので、なかなか仕事を始めない。",
    exampleReading: "かれはこしがおもいので、なかなかしごとをはじめない。",
    exampleMeaning: "He is slow to act, so he doesn't start working easily.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "腰を据える",
    reading: "こしをすえる",
    meaning: "to settle down and focus on something, to commit oneself",
    example: "新しいプロジェクトに腰を据えて取り組む。",
    exampleReading: "あたらしいプロジェクトにこしをすえてとりくむ。",
    exampleMeaning: "To settle down and focus on the new project.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "腰を抜かす",
    reading: "こしをぬかす",
    meaning: "to be shocked, to be surprised, to be taken aback",
    example: "そのニュースを聞いて腰を抜かした。",
    exampleReading: "そのニュースをきいてこしをぬかした。",
    exampleMeaning: "I was shocked when I heard that news.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "翌週",
    reading: "よくしゅう",
    meaning: "next week, following week",
    example: "翌週に会議があります。",
    exampleReading: "よくしゅうにかいぎがあります。",
    exampleMeaning: "There is a meeting next week.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "翌",
    reading: "よく",
    meaning: "next, following (used in formal time-related terms)",
    example: "会議は翌週に延期されました。",
    exampleReading: "かいぎはよくしゅうにえんきされました。",
    exampleMeaning: "The meeting has been postponed to the next week.",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "低い",
    reading: "ひくい",
    meaning: "low, short, humble",
    example: "今朝は気温がひくかったので、水が凍っていた。",
    exampleReading: "けさはきおんがひくかったので、みずがこおっていた。",
    exampleMeaning: "This morning, the temperature was low, so the water was frozen.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "方向",
    reading: "ほうこう",
    meaning: "direction, orientation, way",
    example: "湖はどの方向にありますか。",
    exampleReading: "みずうみはどのほうこうにありますか。",
    exampleMeaning: "In which direction is the lake?",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "向く",
    reading: "むく",
    meaning: "to face, to turn towards, to be suitable for",
    example: "彼は窓のほうを向いて座っている。",
    exampleReading: "かれはまどのほうをむいてすわっている。",
    exampleMeaning: "He is sitting facing the window.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "方向音痴",
    reading: "ほうこうおんち",
    meaning: "bad sense of direction, poor navigation skills",
    example: "私は方向音痴なので、地図が必要です。",
    exampleReading: "わたしはほうこうおんちなので、ちずがひつようです。",
    exampleMeaning: "I have a bad sense of direction, so I need a map.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "規則",
    reading: "きそく",
    meaning: "rule, regulation, code",
    example: "学校の規則が少し変わるそうだ。",
    exampleReading: "がっこうのきそくがすこしかわるそうだ。",
    exampleMeaning: "I heard that the school's rules will change a bit.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "規律",
    reading: "きりつ",
    meaning: "discipline, order, rules",
    example: "規律を守ることが大切だ。",
    exampleReading: "きりつをまもることがたいせつだ。",
    exampleMeaning: "It is important to follow the rules.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "影響",
    reading: "えいきょう",
    meaning: "influence, effect",
    example: "天気の影響で試合が中止になった。",
    exampleReading: "てんきのえいきょうでしあいがちゅうしになった。",
    exampleMeaning: "The match was canceled due to the weather's influence.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
    {
    word: "〜に影響を与える",
    reading: "〜にえいきょうをあたえる",
    meaning: "to influence something, to affect",
    example: "新しい政策が経済に影響を与える。",
    exampleReading: "あたらしいせいさくがけいざいにえいきょうをあたえる。",
    exampleMeaning: "The new policy will influence the economy.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "〜に影響を受ける",
    reading: "〜にえいきょうをうける",
    meaning: "to be influenced by something, to be affected",
    example: "彼は漫画に影響を受けて絵を描き始めた。",
    exampleReading: "かれはまんがにえいきょうをうけてえをかきはじめた。",
    exampleMeaning: "He started drawing influenced by manga.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "友人",
    reading: "ゆうじん",
    meaning: "friend, companion",
    example: "友人と一緒に旅行に行く。",
    exampleReading: "ゆうじんといっしょにりょこうにいく。",
    exampleMeaning: "I will go on a trip with my friend.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "興味",
    reading: "きょうみ",
    meaning: "interest, curiosity",
    example: "野球が好きな友人の影響で、私も野球に興味を持った。",
    exampleReading: "やきゅうがすきなゆうじんのえいきょうで、わたしもやきゅうにきょうみをもった。",
    exampleMeaning: "I became interested in baseball due to the influence of my friend who loves baseball.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "羨ましい",
    reading: "うらやましい",
    meaning: "envious, jealous",
    example: "私は歌が下手なので、歌の上手な人が羨ましいです。",
    exampleReading: "わたしはうたがへたなので、うたのじょうずなひとがうらやましいです。",
    exampleMeaning: "I am envious of people who are good at singing because I am bad at it.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "我慢",
    reading: "がまん",
    meaning: "patience, endurance, self-control, perseverance",
    example: "ゴールまでもう少しだったので、足の痛みを我慢して走ってきた。",
    exampleReading: "ゴールまでもうすこしだったので、あしのいたみをがまんしてはしってきた。",
    exampleMeaning: "I was so close to the finish line that I kept running despite the pain in my legs.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "消極的",
    reading: "しょうきょくてき",
    meaning: "passive, negative, unassertive, unmotivated",
    example: "林さんは会議ではいつも消極的ので、あまり自分の意見をいわない。",
    exampleReading: "はやしさんはかいぎではいつもしょうきょくてきので、あまりじぶんのいけんをいわない。",
    exampleMeaning: "Hayashi is always passive in meetings, so he doesn't often express his own opinions.",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "的",
    reading: "てき",
    meaning: "target, objective, suffix for adjectives",
    example: "基本的な知識を身につけることが大切だ。",
    exampleReading: "きほんてきなちしきをみにつけることがたいせつだ。",
    exampleMeaning: "It is important to acquire basic knowledge.",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "積極的",
    reading: "せっきょくてき",
    meaning: "active, positive, assertive, proactive",
    example: "彼は積極的に意見を述べる。",
    exampleReading: "かれはせっきょくてきにいけんをのべる。",
    exampleMeaning: "He expresses his opinions actively.",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "積極的に参加する",
    reading: "せっきょくてきにさんかする",
    meaning: "to participate actively",
    example: "会議に積極的に参加する。",
    exampleReading: "かいぎにせっきょくてきにさんかする。",
    exampleMeaning: "to participate actively in the meeting",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "積極的な姿勢",
    reading: "せっきょくてきなしせい",
    meaning: "proactive attitude",
    example: "積極的な姿勢で仕事に取り組む。",
    exampleReading: "せっきょくてきなしせいでしごとにとりくむ。",
    exampleMeaning: "to approach work with a proactive attitude",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "経由",
    reading: "けいゆ",
    meaning: "via, through, by way of",
    example: "このバスは駅を出発してから、図書館を経由して美術館へ行きます。",
    exampleReading: "このバスはえきをしゅっぱつしてから、としょかんをけいゆしてびじゅつかんへいきます。",
    exampleMeaning: "This bus departs from the station, and goes to the museum via the library.",
    type: ["noun", "する verb"],
    _JLPT: true,
    info: 
      `Used to indicate a route or path taken to reach a destination. When used as a noun it is followed by particle で (東京経由で大阪に行く - "to go to Osaka via Tokyo").`,
  },
  {
    word: "仲",
    reading: "なか",
    meaning: "relationship, connection, intimacy, get along well",
    example: "あの兄弟はとても仲ので、ほとんどけんかをしないそうです。",
    exampleReading: "あのきょうだいはとてもなかので、ほとんどけんかをしないそうです。",
    exampleMeaning: "Those siblings are very close and hardly ever fight.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "仲がいい",
    reading: "なかがいい",
    meaning: "to have a good relationship, to get along well",
    example: "彼らは仲がいいので、いつも一緒に遊んでいます。",
    exampleReading: "かれらはなかがいいので、いつもいっしょにあそんでいます。",
    exampleMeaning: "They have a good relationship, so they always play together.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "仲直りする",
    reading: "なかなおりする",
    meaning: "to reconcile, to make up",
    example: "けんかした友達と仲直りする。",
    exampleReading: "けんかしたともだちとなかなおりする。",
    exampleMeaning: "to reconcile with a friend after a fight",
    type: ["する verb"],
    _JLPT: true,
  },
  {
    word: "仲間",
    reading: "なかま",
    meaning: "companion, comrade, peer, colleague",
    example: "彼は私の仲間で、いつも助けてくれる。",
    exampleReading: "かれはわたしのなかまで、いつもたすけてくれる。",
    exampleMeaning: "He is my companion and always helps me.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "売り切れる",
    reading: "うりきれる",
    meaning: "to be sold out, to run out of stock",
    example: "その商品はすぐに売り切れた。",
    exampleReading: "そのしょうひんはすぐにうりきれた。",
    exampleMeaning: "That product was sold out quickly.",
    type: ["る verb"],
    _JLPT: true,
    info: `売る (うる) means "to sell", 切れる (きれる) means "to run out" or "to be used up". When combined, 売り切れる (うりきれる) means "to be sold out".`,
  },
  {
    word: "売り場",
    reading: "うりば",
    meaning: "sales floor, sales counter, department",
    example: "デパートの食品売り場に行く。",
    exampleReading: "デパートのしょくひんうりばにいく。",
    exampleMeaning: "to go to the food sales floor of the department store",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "退屈",
    reading: "たいくつ",
    meaning: "boredom, tedium, dullness",
    example: "退屈な授業だった。",
    exampleReading: "たいくつなじゅぎょうだった。",
    exampleMeaning: "It was a boring class.",
    type: ["な adjective", "noun"],
    _JLPT: true,
    info: `つまらない (つまらない) is another common word for "boring".`,
  },
  {
    word: "早速",
    reading: "さっそく",
    meaning: "immediately, at once, without delay",
    example: "早速、メールを送ります。",
    exampleReading: "さっそく、メールをおくります。",
    exampleMeaning: "I will send the email immediately.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "紹介",
    reading: "しょうかい",
    meaning: "introduction, presentation",
    example: "友達を紹介する。",
    exampleReading: "ともだちをしょうかいする。",
    exampleMeaning: "to introduce a friend",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "自己紹介",
    reading: "じこしょうかい",
    meaning: "self-introduction",
    example: "自己紹介をする。",
    exampleReading: "じこしょうかいをする。",
    exampleMeaning: "to do a self-introduction",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "紹介状",
    reading: "しょうかいじょう",
    meaning: "letter of introduction",
    example: "医者に紹介状を書いてもらう。",
    exampleReading: "いしゃにしょうかいじょうをかいてもらう。",
    exampleMeaning: "to get a letter of introduction from the doctor",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ゆるい",
    reading: "ゆるい",
    meaning: "loose, slack, gentle, mild",
    example: "このズボンはゆるいので、ベルトを締める。",
    exampleReading: "このズボンはゆるいので、ベルトをしめる。",
    exampleMeaning: "These pants are loose, so I will tighten the belt.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "きつい",
    reading: "きつい",
    meaning: "tight, strict, harsh, severe",
    example: "この靴はきついので、少し大きいのを買う。",
    exampleReading: "このくつはきついので、すこしおおきいのをかう。",
    exampleMeaning: "These shoes are tight, so I will buy a slightly larger size.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "厳しい",
    reading: "きびしい",
    meaning: "strict, severe, harsh, tough",
    example: "先生はとても厳しいので、宿題を忘れると怒られる。",
    exampleReading: "せんせいはとてもきびしいので、しゅくだいをわすれるとおこられる。",
    exampleMeaning: "The teacher is very strict, so I get scolded if I forget my homework.",
    type: ["い adjective"],
    _JLPT: true,
  },
  {
    word: "知識",
    reading: "ちしき",
    meaning: "knowledge, information, learning",
    example: "歴史の知識を深める。",
    exampleReading: "れきしのちしきをふかめる。",
    exampleMeaning: "to deepen knowledge of history",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "学識",
    reading: "がくしき",
    meaning: "academic knowledge",
    example: "彼は広い学識を持っている。",
    exampleReading: "かれはひろいがくしきをもっている。",
    exampleMeaning: "He has a wide range of academic knowledge.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "響く",
    reading: "ひびく",
    meaning: "to resonate, to sound, to echo, to have an effect, to be heard clearly",
    example: "音楽が遠くまで響く。",
    exampleReading: "おんがくがとおくまでひびく。",
    exampleMeaning: "The music resonates far away.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "完成",
    reading: "かんせい",
    meaning: "completion, accomplishment, finish",
    example: "プロジェクトが完成した。",
    exampleReading: "プロジェクトがかんせいした。",
    exampleMeaning: "The project has been completed.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "完了",
    reading: "かんりょう",
    meaning: "completion (procedural), conclusion, finish",
    example: "仕事が完了した。",
    exampleReading: "しごとがかんりょうした。",
    exampleMeaning: "The work has been completed.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "成功",
    reading: "せいこう",
    meaning: "success, achievement, accomplishment",
    example: "試験に成功した。",
    exampleReading: "しけんにせいこうした。",
    exampleMeaning: "I succeeded in the exam.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "仕上げ",
    reading: "しあげ",
    meaning: "final touch, finishing, completion",
    example: "作品の仕上げをする。",
    exampleReading: "さくひんのしあげをする。",
    exampleMeaning: "to do the finishing touches on the work",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "以前",
    reading: "いぜん",
    meaning: "before, ago, previously, former",
    example: "以前、彼に会ったことがあります。",
    exampleReading: "いぜん、かれにあったことがあります。",
    exampleMeaning: "I have met him before.",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "以後",
    reading: "いご",
    meaning: "after, since, from now on",
    example: "以後、気をつけます。",
    exampleReading: "いご、きをつけます。",
    exampleMeaning: "I will be careful from now on.",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "以外",
    reading: "いがい",
    meaning: "except, other than, besides",
    example: "この問題以外は全部解けました。",
    exampleReading: "このもんだいいがいはぜんぶとけました。",
    exampleMeaning: "I solved all the problems except this one.",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "少なくとも",
    reading: "すくなくとも",
    meaning: "at least, at the very least",
    example: "少なくとも、1時間は待ってください。",
    exampleReading: "すくなくとも、いちじかんはまってください。",
    exampleMeaning: "Please wait at least one hour.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "少しも",
    reading: "すこしも",
    meaning: "not at all, not even a little",
    example: "彼は少しも疲れていないようだ。",
    exampleReading: "かれはすこしもつかれていないようだ。",
    exampleMeaning: "He doesn't seem tired at all.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "気を配る",
    reading: "きをくばる",
    meaning: "to pay attention, to be careful, to be considerate",
    example: "彼は周りに気を配る人だ。",
    exampleReading: "かれはまわりにきをくばるひとだ。",
    exampleMeaning: "He is a person who pays attention to his surroundings.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "配達",
    reading: "はいたつ",
    meaning: "delivery, distribution",
    example: "ピザの配達を頼む。",
    exampleReading: "ピザのはいたつをたのむ。",
    exampleMeaning: "to order pizza delivery",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "配る",
    reading: "くばる",
    meaning: "to distribute, to hand out, to deal (cards)",
    example: "チラシを配る。",
    exampleReading: "チラシをくばる。",
    exampleMeaning: "to distribute flyers",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "実り",
    reading: "みのり",
    meaning: "fruit, result, yield",
    example: "今年の実りは豊作だった。",
    exampleReading: "ことしのみのりはほうさくだった。",
    exampleMeaning: "This year's yield was abundant.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "楽な",
    reading: "らくな",
    meaning: "easy, comfortable, relaxed",
    example: "この仕事は楽なので、すぐ終わる。",
    exampleReading: "このしごとはらくなので、すぐおわる。",
    exampleMeaning: "This job is easy, so it will finish quickly.",
    type: ["な adjective"],
    _JLPT: true,
  },
  {
    word: "公式",
    reading: "こうしき",
    meaning: "official, formal, formula",
    example: "公式な発表があった。",
    exampleReading: "こうしきなはっぴょうがあった。",
    exampleMeaning: "There was an official announcement.",
    type: ["noun", "な adjective"],
    _JLPT: true,
  },
  {
    word: "非公式",
    reading: "ひこうしき",
    meaning: "informal, unofficial",
    example: "非公式な会話を楽しむ。",
    exampleReading: "ひこうしきなかいわをたのしむ。",
    exampleMeaning: "to enjoy informal conversation",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "くせに",
    reading: "くせに",
    meaning: "despite, even though, although (used to express disapproval or criticism)(Same as なのに but more informal)",
    example: "彼は忙しいくせに、遊びに行く。",
    exampleReading: "かれはいそがしいくせに、あそびにいく。",
    exampleMeaning: "Even though he is busy, he goes out to play.",
    type: ["conjunction"],
    _JLPT: true,
  },
  {
    word: "気づかす",
    reading: "きづかす",
    meaning: "to make someone notice, to draw attention to (Withou noticing ???)",
    example: "彼の行動に気づかされた。",
    exampleReading: "かれのこうどうにきづかされた。",
    exampleMeaning: "I was made to notice his behavior.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "細心",
    reading: "さいしん",
    meaning: "attention to detail、utmost care, meticulousness",
    example: "細心の注意を払う。",
    exampleReading: "さいしんのちゅういをはらう。",
    exampleMeaning: "to pay utmost care and attention",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "驚く",
    reading: "おどろく",
    meaning: "to be surprised, to be astonished",
    example: "そのニュースに驚いた。",
    exampleReading: "そのニュースにおどろいた。",
    exampleMeaning: "I was surprised by that news.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "意識",
    reading: "いしき",
    meaning: "consciousness, awareness, consciousness",
    example: "意識を失う。",
    exampleReading: "いしきをうしなう。",
    exampleMeaning: "to lose consciousness",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "石炭",
    reading: "せきたん",
    meaning: "coal",
    example: "石炭は燃料として使われる。",
    exampleReading: "せきたんはねんりょうとしてつかわれる。",
    exampleMeaning: "Coal is used as fuel.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "ますます",
    reading: "ますます",
    meaning: "more and more, increasingly, progressively",
    example: "彼の日本語はますます上手になっている。",
    exampleReading: "かれのにほんごはますますじょうずになっている。",
    exampleMeaning: "His Japanese is getting better and better.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "それぞれ",
    reading: "それぞれ",
    meaning: "each, respectively, individually",
    example: "それぞれの意見を尊重する。",
    exampleReading: "それぞれのいけんをそんちょうする。",
    exampleMeaning: "to respect each person's opinion",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "さまざま",
    reading: "さまざま",
    meaning: "various, diverse, all sorts of",
    example: "さまざまな文化を学ぶ。",
    exampleReading: "さまざまなぶんかをまなぶ。",
    exampleMeaning: "to learn about various cultures",
    type: ["な adjective", "noun"],
    _JLPT: true,
  },
  {
    word: "なかなか",
    reading: "なかなか",
    meaning: "not easily, quite, fairly, pretty",
    example: "なかなか寝付けない。",
    exampleReading: "なかなかねつけない。",
    exampleMeaning: "I can't fall asleep easily.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "だんだん",
    reading: "だんだん",
    meaning: "gradually, little by little, step by step",
    example: "だんだん寒くなってきた。",
    exampleReading: "だんだんさむくなってきた。",
    exampleMeaning: "It is getting colder little by little.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "どんどん",
    reading: "どんどん",
    meaning: "quickly, rapidly, steadily, without hesitation",
    example: "どんどん進むプロジェクト。",
    exampleReading: "どんどんすすむプロジェクト。",
    exampleMeaning: "The project is progressing rapidly.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "どきどき",
    reading: "どきどき",
    meaning: "nervous, heart pounding, excited",
    example: "初めてのデートでどきどきする。",
    exampleReading: "はじめてのデートでどきどきする。",
    exampleMeaning: "I am nervous about my first date.",
    type: ["adverb"],
    _JLPT: true,
  },

  {
    word: "はらはら",
    reading: "はらはら",
    meaning: "anxious, nervous, worried, fluttering",
    example: "試合を見ていてはらはらした。",
    exampleReading: "しあいをみていてはらはらした。",
    exampleMeaning: "I was nervous watching the match.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "きらきら",
    reading: "きらきら",
    meaning: "sparkling, glittering, shining",
    example: "星がきらきら輝いている。",
    exampleReading: "ほしがきらきらかがやいている。",
    exampleMeaning: "The stars are shining brightly.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "ぺらぺら",
    reading: "ぺらぺら",
    meaning: "fluent, fluently, fluency (in speaking a language), thin and flat",
    example: "彼は英語がぺらぺらだ。",
    exampleReading: "かれはえいごがぺらぺらだ。",
    exampleMeaning: "He speaks English fluently.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "のろのろ",
    reading: "のろのろ",
    meaning: "slowly, sluggishly, lazily",
    example: "のろのろ歩く。",
    exampleReading: "のろのろあるく。",
    exampleMeaning: "to walk slowly",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "いらいら",
    reading: "いらいら",
    meaning: "irritated, annoyed, impatient",
    example: "渋滞でいらいらする。",
    exampleReading: "じゅうたいでいらいらする。",
    exampleMeaning: "I get irritated in traffic jams.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "すっかり",
    reading: "すっかり",
    meaning: "completely, entirely, totally",
    example: "すっかり忘れていた。",
    exampleReading: "すっかりわすれていた。",
    exampleMeaning: "I completely forgot.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "増える",
    reading: "ふえる",
    meaning: "to increase, to multiply, to grow",
    example: "人口が増える。",
    exampleReading: "じんこうがふえる。",
    exampleMeaning: "The population is increasing.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "増加",
    reading: "ぞうか",
    meaning: "increase, growth, rise",
    example: "人口の増加が問題になっている。",
    exampleReading: "じんこうのぞうかがもんだいになっている。",
    exampleMeaning: "The increase in population is becoming a problem.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "減少",
    reading: "げんしょう",
    meaning: "decrease, reduction, decline",
    example: "人口の減少が続いている。",
    exampleReading: "じんこうのげんしょうがつづいている。",
    exampleMeaning: "The population decrease continues.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "述べる",
    reading: "のべる",
    meaning: "to state, to mention, to express",
    example: "自分の意見を述べる。",
    exampleReading: "じぶんのいけんをのべる。",
    exampleMeaning: "to express one's own opinion",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "損をする",
    reading: "そんをする",
    meaning: "to incur a loss, to suffer a loss",
    example: "投資で損をした。",
    exampleReading: "とうしでそんをした。",
    exampleMeaning: "I incurred a loss in my investment.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "尊敬",
    reading: "そんけい",
    meaning: "respect, esteem, honor",
    example: "彼は尊敬される人物だ。",
    exampleReading: "かれはそんけいされるじんぶつだ。",
    exampleMeaning: "He is a respected person.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "気になる",
    reading: "きになる",
    meaning: "to be concerned about, to be anxious about, to care about",
    example: "彼のことが気になる。",
    exampleReading: "かれのことがきになる。",
    exampleMeaning: "I am concerned about him.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "結局",
    reading: "けっきょく",
    meaning: "after all, in the end, ultimately",
    example: "結局、彼は来なかった。",
    exampleReading: "けっきょく、かれはこなかった。",
    exampleMeaning: "In the end, he didn't come.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "薬局",
    reading: "やっきょく",
    meaning: "pharmacy, drugstore",
    example: "薬局で薬を買う。",
    exampleReading: "やっきょくでくすりをかう。",
    exampleMeaning: "to buy medicine at the pharmacy",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "慌てる",
    reading: "あわてる",
    meaning: "to panic, to hurry, to be flustered",
    example: "慌てて家を出た。",
    exampleReading: "あわてていえをでた。",
    exampleMeaning: "I hurriedly left the house.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "感心",
    reading: "かんしん",
    meaning: "admiration, being impressed, interest",
    example: "彼の努力に感心した。",
    exampleReading: "かれのどりょくにかんしんした。",
    exampleMeaning: "I was impressed by his effort.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "宣伝",
    reading: "せんでん",
    meaning: "advertisement, publicity, promotion",
    example: "新しい商品を宣伝する。",
    exampleReading: "あたらしいしょうひんをせんでんする。",
    exampleMeaning: "to advertise a new product",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "広告",
    reading: "こうこく",
    meaning: "advertisement, commercial, announcement",
    example: "テレビの広告を見た。",
    exampleReading: "テレビのこうこくをみた。",
    exampleMeaning: "I saw the advertisement on TV.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "苦労",
    reading: "くろう",
    meaning: "hardship, trouble, difficulty",
    example: "彼は苦労して成功した。",
    exampleReading: "かれはくろうしてせいこうした。",
    exampleMeaning: "He succeeded after a lot of hardship.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "時給",
    reading: "じきゅう",
    meaning: "hourly wage, pay per hour",
    example: "このアルバイトの時給は1000円です。",
    exampleReading: "このアルバイトのじきゅうは1000えんです。",
    exampleMeaning: "The hourly wage for this part-time job is 1000 yen.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "発生",
    reading: "はっせい",
    meaning: "occurrence, outbreak, generation",
    example: "新しい問題が発生した。",
    exampleReading: "あたらしいもんだいがはっせいした。",
    exampleMeaning: "A new problem has occurred.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "諦める",
    reading: "あきらめる",
    meaning: "to give up, to abandon, to resign oneself",
    example: "夢を諦めないでください。",
    exampleReading: "ゆめをあきらめないでください。",
    exampleMeaning: "Please don't give up on your dreams.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "努力",
    reading: "どりょく",
    meaning: "effort, endeavor, exertion",
    example: "成功するためには努力が必要だ。",
    exampleReading: "せいこうするためにはどりょくがひつようだ。",
    exampleMeaning: "Effort is necessary to succeed.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "希望",
    reading: "きぼう",
    meaning: "hope, wish, aspiration",
    example: "将来の希望を持つ。",
    exampleReading: "しょうらいのきぼうをもつ。",
    exampleMeaning: "to have hopes for the future",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "せき",
    reading: "せき",
    meaning: "cough, seat (in a theater, etc.)",
    example: "風邪を引いてせきが出る。",
    exampleReading: "かぜをひいてせきがでる。",
    exampleMeaning: "I caught a cold and have a cough.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "くしゃみ",
    reading: "くしゃみ",
    meaning: "sneeze",
    example: "花粉症でくしゃみが出る。",
    exampleReading: "かふんしょうでくしゃみがでる。",
    exampleMeaning: "I sneeze because of hay fever.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "退院",
    reading: "たいいん",
    meaning: "discharge from hospital",
    example: "病気が治って退院した。",
    exampleReading: "びょうきがなおってたいいんした。",
    exampleMeaning: "I was discharged from the hospital after recovering from my illness.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "早退",
    reading: "そうたい",
    meaning: "leaving early, early dismissal",
    example: "今日は早退します。",
    exampleReading: "きょうはそうたいします。",
    exampleMeaning: "I will leave early today.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "に寄る",
    reading: "による",
    meaning: "to stop by",
    example: "友達の家に寄る。",
    exampleReading: "ともだちのいえによる。",
    exampleMeaning: "to stop by a friend's house",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "隠す",
    reading: "かくす",
    meaning: "to hide, to conceal, to cover up",
    example: "秘密を隠す。",
    exampleReading: "ひみつをかくす。",
    exampleMeaning: "to hide a secret",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "満足",
    reading: "まんぞく",
    meaning: "satisfaction, contentment, fulfillment",
    example: "結果に満足する。",
    exampleReading: "けっかにまんぞくする。",
    exampleMeaning: "to be satisfied with the result",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "到着",
    reading: "とうちゃく",
    meaning: "arrival, reaching a destination",
    example: "飛行機が到着した。",
    exampleReading: "ひこうきがとうちゃくした。",
    exampleMeaning: "The airplane has arrived.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "続く",
    reading: "つづく",
    meaning: "to continue, to last, to go on",
    example: "会議が長く続いた。",
    exampleReading: "かいぎがながくつづいた。",
    exampleMeaning: "The meeting continued for a long time.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "豆",
    reading: "まめ",
    meaning: "bean, pea, legume",
    example: "豆を食べるのが好きです。",
    exampleReading: "まめをたべるのがすきです。",
    exampleMeaning: "I like to eat beans.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "増える",
    reading: "ふえる",
    meaning: "to increase, to multiply, to grow",
    example: "人口が増える。",
    exampleReading: "じんこうがふえる。",
    exampleMeaning: "The population is increasing.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "加える",
    reading: "くわえる",
    meaning: "to add, to include, to append",
    example: "砂糖を加える。",
    exampleReading: "さとうをくわえる。",
    exampleMeaning: "to add sugar",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "訓練",
    reading: "くんれん",
    meaning: "training, drill, practice",
    example: "新入社員の訓練を行う。",
    exampleReading: "しんにゅうしゃいんのくんれんをおこなう。",
    exampleMeaning: "to conduct training for new employees",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "波",
    reading: "なみ",
    meaning: "wave, ripple, fluctuation",
    example: "海の波が高い。",
    exampleReading: "うみのなみがたかい。",
    exampleMeaning: "The waves in the sea are high.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "共",
    reading: "とも",
    meaning: "both, together, with",
    example: "彼と共に旅行する。",
    exampleReading: "かれとともにりょこうする。",
    exampleMeaning: "to travel together with him",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "共通",
    reading: "きょうつう",
    meaning: "common, shared, mutual",
    example: "共通の趣味を持つ。",
    exampleReading: "きょうつうのしゅみをもつ。",
    exampleMeaning: "to have a common hobby",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "輸出",
    reading: "ゆしゅつ",
    meaning: "export, shipment abroad",
    example: "日本は多くの製品を輸出している。",
    exampleReading: "にほんはおおくのせいひんをゆしゅつしている。",
    exampleMeaning: "Japan exports many products.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "囲み",
    reading: "かこみ",
    meaning: "enclosure, surround, frame",
    example: "囲み記事が新聞に載っている。",
    exampleReading: "かこみきじがしんぶんにのっている。",
    exampleMeaning: "There is an enclosed article in the newspaper.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "許す",
    reading: "ゆるす",
    meaning: "to forgive, to permit, to allow",
    example: "彼の過ちを許す。",
    exampleReading: "かれのあやまちをゆるす。",
    exampleMeaning: "to forgive his mistake",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "内緒",
    reading: "ないしょ",
    meaning: "secret, confidentiality, privacy",
    example: "このことは内緒にしておいてください。",
    exampleReading: "このことはないしょにしておいてください。",
    exampleMeaning: "Please keep this matter a secret.",
    type: ["noun", "な adjective"],
    _JLPT: true,
  },
  {
    word: "秘密",
    reading: "ひみつ",
    meaning: "secret, confidentiality, mystery",
    example: "彼は私に秘密を打ち明けた。",
    exampleReading: "かれはわたしにひみつをうちあけた。",
    exampleMeaning: "He confided a secret to me.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "冗談",
    reading: "じょうだん",
    meaning: "joke, jest, trick",
    example: "彼は冗談が好きだ。",
    exampleReading: "かれはじょうだんがすきだ。",
    exampleMeaning: "He likes jokes.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "がっかり",
    reading: "がっかり",
    meaning: "disappointed, dejected, disheartened",
    example: "試験に落ちてがっかりした。",
    exampleReading: "しけんにおちてがっかりした。",
    exampleMeaning: "I was disappointed after failing the exam.",
    type: ["adverb", "する verb"],
    _JLPT: true,
  },
  {
    word: "あまりする",
    reading: "あまりする",
    meaning: "to do too much, to overdo",
    example: "勉強をあまりしすぎると疲れる。",
    exampleReading: "べんきょうをあまりしすぎるとつかれる。",
    exampleMeaning: "If you study too much, you will get tired.",
    type: ["expression"],
    _JLPT: true,
  },
  {
    word: "当然",
    reading: "とうぜん",
    meaning: "naturally, of course, as a matter of course, com certeza",
    example: "遅刻したので、当然の罰を受けた。",
    exampleReading: "ちこくしたので、とうぜんのばつをうけた。",
    exampleMeaning: "I received a natural punishment for being late.",
    type: ["noun", "な adjective", "adverb"],
    _JLPT: true,
  },
  {
    word: "訪れた",
    reading: "おとずれた",
    meaning: "to visit, to call on, to come to see",
    example: "友達を訪れた。",
    exampleReading: "ともだちをおとずれた。",
    exampleMeaning: "I visited my friend.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "訪問",
    reading: "ほうもん",
    meaning: "visit, call, calling on",
    example: "先生の家を訪問する。",
    exampleReading: "せんせいのいえをほうもんする。",
    exampleMeaning: "to visit the teacher's house",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "判断",
    reading: "はんだん",
    meaning: "judgment, decision, conclusion",
    example: "正しい判断を下す。",
    exampleReading: "ただしいはんだんをくだす。",
    exampleMeaning: "to make a correct judgment",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "驚く",
    reading: "おどろく",
    meaning: "to be surprised, to be astonished",
    example: "そのニュースに驚いた。",
    exampleReading: "そのニュースにおどろいた。",
    exampleMeaning: "I was surprised by that news.",
    type: ["う verb"],
    _JLPT: true,
  },
  {
    word: "連絡",
    reading: "れんらく",
    meaning: "contact, communication, connection",
    example: "友達と連絡を取る。",
    exampleReading: "ともだちとれんらくをとる。",
    exampleMeaning: "to get in touch with a friend",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  //TODO: AGILDO SENSEI WORDS END HERE
  { 
    word: "実際",
    reading: "じっさい",
    meaning: "actual, reality, practical",
    example: "実際にやってみる。",
    exampleReading: "じっさいにやってみる。",
    exampleMeaning: "to try it in practice",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "ふだん",
    reading: "ふだん",
    meaning: "usually, ordinarily, habitually",
    example: "ふだんは朝早く起きる。",
    exampleReading: "ふだんはあさはやくおきる。",
    exampleMeaning: "I usually wake up early in the morning.",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "寝坊",
    reading: "ねぼう",
    meaning: "oversleeping, sleeping in",
    example: "寝坊して遅刻した。",
    exampleReading: "ねぼうしてちこくした。",
    exampleMeaning: "I overslept and was late.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "遅刻",
    reading: "ちこく",
    meaning: "being late,tardiness",
    example: "学校に遅刻した。",
    exampleReading: "がっこうにちこくした。",
    exampleMeaning: "I was late for school.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "遅れる",
    reading: "おくれる",
    meaning: "to be late, to be delayed",
    example: "電車が遅れる。",
    exampleReading: "でんしゃがおくれる。",
    exampleMeaning: "The train is delayed.",
    type: ["る verb"],
    _JLPT: true,
  },
  {
    word: "欠席",
    reading: "けっせき",
    meaning: "absence, non-attendance",
    example: "授業を欠席する。",
    exampleReading: "じゅぎょうをけっせきする。",
    exampleMeaning: "to be absent from class",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "結局",
    reading: "けっきょく",
    meaning: "after all, in the end, ultimately",
    example: "結局、彼は来なかった。",
    exampleReading: "けっきょく、かれはこなかった。",
    exampleMeaning: "In the end, he didn't come.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "やっぱり",
    reading: "やっぱり",
    meaning: "as expected, after all, just as I thought",
    example: "やっぱり彼は来なかった。",
    exampleReading: "やっぱりかれはこなかった。",
    exampleMeaning: "As expected, he didn't come.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "結末",
    reading: "けつまつ",
    meaning: "conclusion, ending, outcome",
    example: "物語の結末が気になる。",
    exampleReading: "ものがたりのけつまつがきになる。",
    exampleMeaning: "I am curious about the ending of the story.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "実際",
    reading: "じっさい",
    meaning: "actual, reality, practical",
    example: "実際にやってみる。",
    exampleReading: "じっさいにやってみる。",
    exampleMeaning: "to try it in practice",
    type: ["noun", "adverb"],
    _JLPT: true,
  },
  {
    word: "現実",
    reading: "げんじつ",
    meaning: "reality, actual state of affairs",
    example: "現実を直視する。",
    exampleReading: "げんじつをちょくしする。",
    exampleMeaning: "to face reality",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "実物",
    reading: "じつぶつ",
    meaning: "real thing, actual object",
    example: "実物を見てみたい。",
    exampleReading: "じつぶつをみてみたい。",
    exampleMeaning: "I want to see the real thing.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "実験",
    reading: "じっけん",
    meaning: "experiment, test",
    example: "科学の実験を行う。",
    exampleReading: "かがくのじっけんをおこなう。",
    exampleMeaning: "to conduct a science experiment",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "びったり",
    reading: "びったり",
    meaning: "just right, exactly, perfectly",
    example: "この服は私にびったりだ。",
    exampleReading: "このふくはわたしにびったりだ。",
    exampleMeaning: "This clothes fits me perfectly.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "ちょうど",
    reading: "ちょうど",
    meaning: "exactly, Just right, right on time",
    example: "ちょうどいい時間に着いた。",
    exampleReading: "ちょうどいいじかんについた。",
    exampleMeaning: "I arrived at just the right time.",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "夏祭",
    reading: "なつまつり",
    meaning: "summer festival",
    example: "夏祭りで花火を見る。",
    exampleReading: "なつまつりではなびをみる。",
    exampleMeaning: "to see fireworks at the summer festival",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "焼ける",
    reading: "やける",
    meaning: "to burn, to be roasted, to be baked",
    example: "パンが焼ける。",
    exampleReading: "パンがやける。",
    exampleMeaning: "The bread is baking.",
    type: ["る verb"],
    _JLPT: true,
    info: "The transitive form is 焼く (やく).",
  },
  {
    word: "日常生活",
    reading: "にちじょうせいかつ",
    meaning: "daily life, everyday life",
    example: "日常生活を大切にする。",
    exampleReading: "にちじょうせいかつをたいせつにする。",
    exampleMeaning: "to value daily life",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "階段",
    reading: "かいだん",
    meaning: "stairs, staircase",
    example: "階段を上る。",
    exampleReading: "かいだんをのぼる。",
    exampleMeaning: "to go up the stairs",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "速く",
    reading: "はやく",
    meaning: "fast, quickly, early",
    example: "速く走る。",
    exampleReading: "はやくはしる。",
    exampleMeaning: "to run fast",
    type: ["adverb"],
    _JLPT: true,
  },
  {
    word: "大変",
    reading: "たいへん",
    meaning: "difficult",
    example: "大変な仕事だ。",
    exampleReading: "たいへんなしごとだ。",
    exampleMeaning: "It's a very difficult job.",
    type: ["な adjective", "adverb"],
    _JLPT: true,
  },
  {
    word: "困難",
    reading: "こんなん",
    meaning: "difficulty, hardship, adversity",
    example: "困難な状況に直面する。",
    exampleReading: "こんなんなじょうきょうにちょくめんする。",
    exampleMeaning: "to face a difficult situation",
    type: ["noun", "な adjective", "する verb"],
    _JLPT: true,
  },
  {
    word: "眺め",
    reading: "ながめ",
    meaning: "view, scenery, sight",
    example: "山の眺めが美しい。",
    exampleReading: "やまのながめがうつくしい。",
    exampleMeaning: "The view of the mountain is beautiful.",
    type: ["noun"],
    _JLPT: true,
    info: "眺める (ながめる) is the verb form meaning 'to gaze at' or 'to look at'.",

  },
  {
    word: "景色",
    reading: "けしき",
    meaning: "scenery (general), landscape, view",
    example: "海の景色が素晴らしい。",
    exampleReading: "うみのけしきがすばらしい。",
    exampleMeaning: "The view of the sea is wonderful.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "見晴らし",
    reading: "みはらし",
    meaning: "view (from a high place), outlook, prospect",
    example: "山の上からの見晴らしが良い。",
    exampleReading: "やまのうえからのみはらしがよい。",
    exampleMeaning: "The view from the top of the mountain is good.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "感動",
    reading: "かんどう",
    meaning: "Being deeply moved, emotion, impression, excitement",
    example: "映画に感動した。",
    exampleReading: "えいがにかんどうした。",
    exampleMeaning: "I was moved by the movie.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },
  {
    word: "印象",
    reading: "いんしょう",
    meaning: "impression",
    example: "彼の第一印象は良かった。",
    exampleReading: "かれのだいいちいんしょうはよかった。",
    exampleMeaning: "His first impression was good.",
    type: ["noun"],
    _JLPT: true,
  },
  {
    word: "結婚",
    reading: "けっこん",
    meaning: "marriage, wedding",
    example: "結婚式を挙げる。",
    exampleReading: "けっこんしきをあげる。",
    exampleMeaning: "to hold a wedding ceremony",
    type: ["noun", "する verb"],
    _JLPT: true,
  },{
    word: "離婚",
    reading: "りこん",
    meaning: "divorce",
    example: "離婚することに決めた。",
    exampleReading: "りこんすることにきめた。",
    exampleMeaning: "I decided to get a divorce.",
    type: ["noun", "する verb"],
    _JLPT: true,
  },{
    word: "受付",
    reading: "うけつけ",
    meaning: "reception, front desk, information desk",
    example: "ホテルの受付でチェックインする。",
    exampleReading: "ホテルのうけつけでチェックインする。",
    exampleMeaning: "to check in at the hotel reception",
    type: ["noun"],
    _JLPT: true,
  },{
    word: "総合",
    reading: "そうごう",
    meaning: "general, comprehensive, overall",
    example: "総合的な判断が必要だ。",
    exampleReading: "そうごうてきなはんだんがひつようだ。",
    exampleMeaning: "A comprehensive judgment is necessary.",
    type: ["noun", "な adjective", "する verb"],
    _JLPT: true,
  },
  //TODO: continue from 慌てる
  // 
  // ** Vocabulary for JLPT N3 **
  //
  {
    word: "挨拶",
    reading: "あいさつ",
    meaning: "greeting",
    example: "朝の挨拶をする。",
    exampleReading: "あさのあいさつをする。",
    exampleMeaning: "to greet in the morning",
    type: ["noun", "する verb"]
  },
  {
    word: "間",
    reading: "あいだ",
    meaning: "between, interval",
    example: "二つの家の間に公園がある。",
    exampleReading: "ふたつのいえのあいだにこうえんがある。",
    exampleMeaning: "There is a park between the two houses.",
    type: ["noun"]
  },
  {
    word: "相手",
    reading: "あいて",
    meaning: "partner, opponent",
    example: "試合の相手は強い。",
    exampleReading: "しあいのあいてはつよい。",
    exampleMeaning: "The opponent in the match is strong.",
    type: ["noun", "adverb"]
  },
  {
    word: "青",
    reading: "あお",
    meaning: "blue, green",
    example: "空が青い。",
    exampleReading: "そらがあおい。",
    exampleMeaning: "The sky is blue.",
    type: ["noun", "い adjective"]
  },
  {
    word: "赤ちゃん",
    reading: "あかちゃん",
    meaning: "baby",
    example: "赤ちゃんが泣いている。",
    exampleReading: "あかちゃんがないている。",
    exampleMeaning: "The baby is crying.",
    type: ["noun"]
  },
  {
    word: "明るい",
    reading: "あかるい",
    meaning: "bright, cheerful",
    example: "部屋が明るい。",
    exampleReading: "へやがあかるい。",
    exampleMeaning: "The room is bright.",
    type: ["い adjective"]
  },
  {
    word: "回り",
    reading: "まわり",
    meaning: "rotation, surroundings, vicinity",
    example: "家の回りを歩く。",
    exampleReading: "いえのまわりをあるく。",
    exampleMeaning: "to walk around the house",
    type: ["noun"]
  },
  {
    word: "理想",
    reading: "りそう",
    meaning: "ideal",
    example: "理想の生活を送る。",
    exampleReading: "りそうのせいかつをおくる。",
    exampleMeaning: "to lead an ideal life",
    type: ["noun", "な adjective"]
  },
  {
    word: "生",
    reading: "せい・なま",
    meaning: "life, birth (せい), raw, fresh (なま)",
    example: "生まれたばかりの赤ちゃん。",
    exampleReading: "うまれたばかりのあかちゃん。",
    exampleMeaning: "a newborn baby",
    type: ["noun", "な adjective"]
  },
  {
    word: "のんびり",
    reading: "のんびり",
    meaning: "carefree, relaxed",
    example: "のんびりと過ごす。",
    exampleReading: "のんびりとすごす。",
    exampleMeaning: "to spend time in a relaxed manner",
    type: ["adverb"]
  },
  {
    word: "文字",
    reading: "もじ",
    meaning: "character, letter",
    example: "漢字の文字を学ぶ。",
    exampleReading: "かんじのもじをまなぶ。",
    exampleMeaning: "to learn kanji characters",
    type: ["noun"]
  },
  {
    word: "柄",
    reading: "がら",
    meaning: "pattern, design",
    example: "花柄のシャツを着る。",
    exampleReading: "はながらのシャツをきる。",
    exampleMeaning: "to wear a floral patterned shirt",
    type: ["noun"]
  },
  {
    word: "梅雨",
    reading: "つゆ",
    meaning: "rainy season",
    example: "梅雨の時期は湿気が多い。",
    exampleReading: "つゆのじきはしっけがおおい。",
    exampleMeaning: "The rainy season has a lot of humidity.",
    type: ["noun"]
  },
  {
    word: "がっかり",
    reading: "がっかり",
    meaning: "disappointed",
    example: "試験に落ちてがっかりした。",
    exampleReading: "しけんにおちてがっかりした。",
    exampleMeaning: "I was disappointed after failing the exam.",
    type: ["adverb"]
  },
  {
    word: "一言",
    reading: "ひとこと",
    meaning: "a word, a brief comment",
    example: "一言で説明する。",
    exampleReading: "ひとことでせつめいする。",
    exampleMeaning: "to explain in a word",
    type: ["noun", "adverb"]
  },
  {
    word: "不満",
    reading: "ふまん",
    meaning: "dissatisfaction, discontent",
    example: "給料に不満がある。",
    exampleReading: "きゅうりょうにふまんがある。",
    exampleMeaning: "to have dissatisfaction with the salary",
    type: ["な adjective", "noun"]
  },
  {
    word: "不足",
    reading: "ふそく",
    meaning: "insufficiency, shortage",
    example: "時間が不足している。",
    exampleReading: "じかんがふそくしている。",
    exampleMeaning: "There is a shortage of time.",
    type: ["な adjective", "noun"]
  },
  {
    word: "世の中",
    reading: "よのなか",
    meaning: "the world, society",
    example: "世の中は変わっていく。",
    exampleReading: "よのなかはかわっていく。",
    exampleMeaning: "The world is changing.",
    type: ["noun"]
  },
  {
    word: "予算",
    reading: "よさん",
    meaning: "budget, estimate",
    example: "旅行の予算を立てる。",
    exampleReading: "りょこうのよさんをたてる。",
    exampleMeaning: "to set a budget for the trip",
    type: ["noun"]
  },
  {
    word: "事件",
    reading: "じけん",
    meaning: "incident, event",
    example: "大きな事件が起こった。",
    exampleReading: "おおきなじけんがおこった。",
    exampleMeaning: "A big incident occurred.",
    type: ["noun"]
  },
  {
    word: "人間",
    reading: "にんげん",
    meaning: "human, person",
    example: "人間は社会的な動物だ。",
    exampleReading: "にんげんはしゃかいてきなどうぶつだ。",
    exampleMeaning: "Humans are social animals.",
    type: ["noun"]
  },
  {
    word: "人類",
    reading: "じんるい",
    meaning: "humanity, mankind",
    example: "人類は宇宙に進出している。",
    exampleReading: "じんるいはうちゅうにしんしゅつしている。",
    exampleMeaning: "Humanity is advancing into space.",
    type: ["noun"]
  },
  {
    word: "以前",
    reading: "いぜん",
    meaning: "before, previous, since",
    example: "以前の仕事は楽しかった。",
    exampleReading: "いぜんのしごとはたのしかった。",
    exampleMeaning: "The previous job was enjoyable.",
    type: ["noun", "adverb"]
  },
  {
    word: "休憩",
    reading: "きゅうけい",
    meaning: "break, rest",
    example: "仕事の後に休憩を取る。",
    exampleReading: "しごとのあとにきゅうけいをとる。",
    exampleMeaning: "to take a break after work",
    type: ["noun", "する verb"]
  },
  {
    word: "休暇",
    reading: "きゅうか",
    meaning: "vacation, holiday, day off",
    example: "夏休暇を計画する。",
    exampleReading: "なつきゅうかをけいかくする。",
    exampleMeaning: "to plan a summer vacation",
    type: ["noun", "する verb"]
  },
  {
    word: "会員",
    reading: "かいいん",
    meaning: "member, membership",
    example: "クラブの会員になる。",
    exampleReading: "クラブのかいいんになる。",
    exampleMeaning: "to become a member of the club",
    type: ["noun"]
  },
  {
    word: "伝統",
    reading: "でんとう",
    meaning: "tradition, convention",
    example: "日本の伝統を守る。",
    exampleReading: "にほんのでんとうをまもる。",
    exampleMeaning: "to preserve Japanese traditions",
    type: ["noun"]
  },
  {
    word: "伸びる",
    reading: "のびる",
    meaning: "to stretch, to extend",
    example: "髪が伸びる。",
    exampleReading: "かみがのびる。",
    exampleMeaning: "Hair grows longer.",
    type: ["る verb"]
  },
  {
    word: "似合う",
    reading: "にあう",
    meaning: "to suit, to match",
    example: "その服が似合う。",
    exampleReading: "そのふくがにあう。",
    exampleMeaning: "That outfit suits you.",
    type: ["う verb"]
  },
  {
    word: "住民",
    reading: "じゅうみん",
    meaning: "resident, inhabitant",
    example: "この地域の住民は親切だ。",
    exampleReading: "このちいきのじゅうみんはしんせつだ。",
    exampleMeaning: "The residents of this area are kind.",
    type: ["noun"]
  },
  {
    word: "作品",
    reading: "さくひん",
    meaning: "work, production (of art, literature, etc.)",
    example: "彼の最新の作品を読む。",
    exampleReading: "かれのさいしんのさくひんをよむ。",
    exampleMeaning: "to read his latest work",
    type: ["noun"]
  },
  {
    word: "作業",
    reading: "さぎょう",
    meaning: "work, operation, task",
    example: "作業を効率よく進める。",
    exampleReading: "さぎょうをこうりつよくすすめる。",
    exampleMeaning: "to proceed with the work efficiently",
    type: ["noun", "する verb"]
  },
  {
    word: "保存",
    reading: "ほぞん",
    meaning: "maintenance, storage, saving (data)",
    example: "データを保存する。",
    exampleReading: "データをほぞんする。",
    exampleMeaning: "to save data",
    type: ["noun", "する verb"]
  },
  {
    word: "信頼",
    reading: "しんらい",
    meaning: "trust, confidence",
    example: "彼に信頼を置く。",
    exampleReading: "かれにしんらいをおく。",
    exampleMeaning: "to place trust in him",
    type: ["noun", "する verb"]
  },
  {
    word: "俳優",
    reading: "はいゆう",
    meaning: "actor, actress",
    example: "有名な俳優が出演する。",
    exampleReading: "ゆうめいなはいゆうがしゅつえんする。",
    exampleMeaning: "A famous actor will appear.",
    type: ["noun"]
  },
  {
    word: "優勝",
    reading: "ゆうしょう",
    meaning: "championship, victory",
    example: "チームが優勝した。",
    exampleReading: "チームがゆうしょうした。",
    exampleMeaning: "The team won the championship.",
    type: ["noun", "する verb"]
  },
  {
    word: "優秀",
    reading: "ゆうしゅう",
    meaning: "excellent, superior",
    example: "優秀な学生が多い。",
    exampleReading: "ゆうしゅうながくせいがおおい。",
    exampleMeaning: "There are many excellent students.",
    type: ["な adjective", "noun"]
  },
  {
    word: "先日",
    reading: "せんじつ",
    meaning: "the other day, recently",
    example: "先日、友達に会った。",
    exampleReading: "せんじつ、ともだちにあった。",
    exampleMeaning: "I met a friend the other day.",
    type: ["noun", "adverb"]
  },
  {
    word: "全て",
    reading: "すべて",
    meaning: "all, everything",
    example: "全ての人に平等な権利がある。",
    exampleReading: "すべてのひとにびょうどうなけんりがある。",
    exampleMeaning: "Everyone has equal rights.",
    type: ["noun", "adverb"]
  },
  {
    word: "全体",
    reading: "ぜんたい",
    meaning: "whole, entirety",
    example: "プロジェクトの全体を把握する。",
    exampleReading: "プロジェクトのぜんたいをはあくする。",
    exampleMeaning: "to grasp the whole of the project",
    type: ["noun"]
  },
  {
    word: "全員",
    reading: "ぜんいん",
    meaning: "all members, everyone",
    example: "会議には全員が参加した。",
    exampleReading: "かいぎにはぜんいんがさんかした。",
    exampleMeaning: "Everyone participated in the meeting.",
    type: ["noun"]
  },
  {
    word: "共通",
    reading: "きょうつう",
    meaning: "common, mutual",
    example: "共通の趣味を持つ。",
    exampleReading: "きょうつうのしゅみをもつ。",
    exampleMeaning: "to have a common hobby",
    type: ["noun", "な adjective"]
  },
  {
    word: "内容",
    reading: "ないよう",
    meaning: "content, substance",
    example: "この本の内容は面白い。",
    exampleReading: "このほんのないようはおもしろい。",
    exampleMeaning: "The content of this book is interesting.",
    type: ["noun"]
  },
  {
    word: "冗談",
    reading: "じょうだん",
    meaning: "joke, jest",
    example: "冗談を言うのが好きだ。",
    exampleReading: "じょうだんをいうのがすきだ。",
    exampleMeaning: "I like to tell jokes.",
    type: ["noun", "する verb"]
  },
  {
    word: "分",
    reading: "ぶん",
    meaning: "part, portion, minute",
    example: "一人分の料理を作る。",
    exampleReading: "ひとりぶんのりょうりをつくる。",
    exampleMeaning: "to make a dish for one person",
    type: ["noun"]
  },
  {
    word: "～分の～",
    reading: "～ぶんの～",
    meaning: "fraction of, part of",
    example: "三分の一の確率。",
    exampleReading: "さんぶんのいちのかくりつ。",
    exampleMeaning: "a probability of one-third",
    type: ["noun"]
  },
  {
    word: "分野",
    reading: "ぶんや",
    meaning: "field, area, domain",
    example: "科学の分野で研究する。",
    exampleReading: "かがくのぶんやでけんきゅうする。",
    exampleMeaning: "to conduct research in the field of science",
    type: ["noun"]
  },
  {
    word: "刑事",
    reading: "けいじ",
    meaning: "detective, police officer",
    example: "刑事が事件を捜査する。",
    exampleReading: "けいじがじけんをそうさする。",
    exampleMeaning: "The detective investigates the case.",
    type: ["noun"]
  },
  {
    word: "到着",
    reading: "とうちゃく",
    meaning: "arrival",
    example: "飛行機が到着した。",
    exampleReading: "ひこうきがとうちゃくした。",
    exampleMeaning: "The airplane has arrived.",
    type: ["noun", "する verb"]
  },
  {
    word: "努力",
    reading: "どりょく",
    meaning: "effort, endeavor",
    example: "成功のために努力する。",
    exampleReading: "せいこうのためにどりょくする。",
    exampleMeaning: "to make an effort for success",
    type: ["noun", "する verb"]
  },
  {
    word: "効果",
    reading: "こうか",
    meaning: "effect, effectiveness",
    example: "薬の効果を確認する。",
    exampleReading: "くすりのこうかをかくにんする。",
    exampleMeaning: "to confirm the effect of the medicine",
    type: ["noun", "する verb"]
  },
  {
    word: "協力",
    reading: "きょうりょく",
    meaning: "cooperation, collaboration",
    example: "プロジェクトの成功には協力が必要だ。",
    exampleReading: "プロジェクトのせいこうにはきょうりょくがひつようだ。",
    exampleMeaning: "Cooperation is necessary for the success of the project.",
    type: ["noun", "する verb"]
  },
  {
    word: "単語",
    reading: "たんご",
    meaning: "word, vocabulary",
    example: "新しい単語を覚える。",
    exampleReading: "あたらしいたんごをおぼえる。",
    exampleMeaning: "to memorize new vocabulary",
    type: ["noun"]
  },
  {
    word: "占める",
    reading: "しめる",
    meaning: "to occupy, to account for",
    example: "市場の大部分を占める。",
    exampleReading: "しじょうのだいぶぶんをしめる。",
    exampleMeaning: "to occupy a large part of the market",
    type: ["る verb"]
  },
  {
    word: "友人",
    reading: "ゆうじん",
    meaning: "friend",
    example: "友人と旅行に行く。",
    exampleReading: "ゆうじんとりょこうにいく。",
    exampleMeaning: "to go on a trip with a friend",
    type: ["noun"]
  },
  {
    word: "双子",
    reading: "ふたご",
    meaning: "twins",
    example: "双子の兄弟がいる。",
    exampleReading: "ふたごのきょうだいがいる。",
    exampleMeaning: "I have twin siblings.",
    type: ["noun"]
  },
  {
    word: "収穫",
    reading: "しゅうかく",
    meaning: "harvest, crop",
    example: "農家は収穫の時期だ。",
    exampleReading: "のうかはしゅうかくのじきだ。",
    exampleMeaning: "It's harvest time for farmers.",
    type: ["noun", "する verb"]
  },
  {
    word: "叫ぶ",
    reading: "さけぶ",
    meaning: "to shout, to cry out",
    example: "大声で叫ぶ。",
    exampleReading: "おおごえでさけぶ。",
    exampleMeaning: "to shout loudly",
    type: ["う verb"]
  },
  { 
    word: "同僚",
    reading: "どうりょう",
    meaning: "colleague, coworker",
    example: "同僚とランチを食べる。",
    exampleReading: "どうりょうとランチをたべる。",
    exampleMeaning: "to have lunch with a colleague",
    type: ["noun"]
  },
  { 
    word: "味方",
    reading: "みかた",
    meaning: "ally, supporter, friend",
    example: "彼は私の味方だ。",
    exampleReading: "かれはわたしのみかただ。",
    exampleMeaning: "He is my ally.",
    type: ["noun"]
  },
  { 
    word: "品",
    reading: "しな",
    meaning: "goods, item, product",
    example: "店で新しい品を買う。",
    exampleReading: "みせであたらしいしなをかう。",
    exampleMeaning: "to buy new items at the store",
    type: ["noun"]
  },
  { 
    word: "ただ",
    reading: "ただ",
    meaning: "free, only, just",
    example: "このサービスはただだ。",
    exampleReading: "このサービスはただだ。",
    exampleMeaning: "This service is free.",
    type: ["adverb", "noun"]
  },
  { 
    word: "商品",
    reading: "しょうひん",
    meaning: "goods, merchandise, product",
    example: "新しい商品が入荷した。",
    exampleReading: "あたらしいしょうひんがにゅうかした。",
    exampleMeaning: "New products have arrived.",
    type: ["noun"]
  },
  { 
    word: "国民",
    reading: "こくみん",
    meaning: "citizen, people of a country",
    example: "国民の権利を守る。",
    exampleReading: "こくみんのけんりをまもる。",
    exampleMeaning: "to protect the rights of citizens",
    type: ["noun"]
  },
  { 
    word: "地域",
    reading: "ちいき",
    meaning: "area, region",
    example: "この地域は治安が良い。",
    exampleReading: "このちいきはちあんがよい。",
    exampleMeaning: "This area has good security.",
    type: ["noun"]
  },
  { 
    word: "地方",
    reading: "ちほう",
    meaning: "local, region, district",
    example: "地方の特産品を買う。",
    exampleReading: "ちほうのとくさんひんをかう。",
    exampleMeaning: "to buy local specialties",
    type: ["noun"]
  },
  { 
    word: "報告",
    reading: "ほうこく",
    meaning: "report, information",
    example: "会議で報告をする。",
    exampleReading: "かいぎでほうこくをする。",
    exampleMeaning: "to give a report in the meeting",
    type: ["noun", "する verb"]
  },
  { 
    word: "変更",
    reading: "へんこう",
    meaning: "change, modification",
    example: "予定を変更する。",
    exampleReading: "よていをへんこうする。",
    exampleMeaning: "to change the schedule",
    type: ["noun", "する verb"]
  },
  { 
    word: "夜中",
    reading: "よなか",
    meaning: "midnight, middle of the night",
    example: "夜中に目が覚める。",
    exampleReading: "よなかにめがさめる。",
    exampleMeaning: "to wake up in the middle of the night",
    type: ["noun"]
  },
  { 
    word: "夢中",
    reading: "むちゅう",
    meaning: "absorbed, engrossed, obsessed with",
    example: "ゲームに夢中になる。",
    exampleReading: "ゲームにむちゅうになる。",
    exampleMeaning: "to be absorbed in a game",
    type: ["noun", "な adjective"]
  },
  { 
    word: "大統領",
    reading: "だいとうりょう",
    meaning: "president (of a country)",
    example: "アメリカの大統領が訪日した。",
    exampleReading: "アメリカのだいとうりょうがほうにちした。",
    exampleMeaning: "The President of the United States visited Japan.",
    type: ["noun"]
  },
  { 
    word: "太陽",
    reading: "たいよう",
    meaning: "sun",
    example: "太陽が昇る。",
    exampleReading: "たいようがのぼる。",
    exampleMeaning: "The sun rises.",
    type: ["noun"]
  },
  { 
    word: "失う",
    reading: "うしなう",
    meaning: "to lose, to part with",
    example: "大切なものを失う。",
    exampleReading: "たいせつなものをうしなう。",
    exampleMeaning: "to lose something precious",
    type: ["う verb"]
  },
  { 
    word: "契約",
    reading: "けいやく",
    meaning: "contract, agreement",
    example: "新しい契約を結ぶ。",
    exampleReading: "あたらしいけいやくをむすぶ。",
    exampleMeaning: "to conclude a new contract",
    type: ["noun", "する verb"]
  },
  { 
    word: "奥",
    reading: "おく",
    meaning: "interior, depths, inner part",
    example: "部屋の奥に何かある。",
    exampleReading: "へやのおくになにかある。",
    exampleMeaning: "There is something in the depths of the room.",
    type: ["noun"]
  },
  { 
    word: "好み",
    reading: "このみ",
    meaning: "liking, taste, preference",
    example: "自分の好みに合った服を選ぶ。",
    exampleReading: "じぶんのこのみにあったふくをえらぶ。",
    exampleMeaning: "to choose clothes that match one's taste",
    type: ["noun"]
  },
  { 
    word: "委員",
    reading: "いいん",
    meaning: "committee member, commissioner",
    example: "委員会の委員として参加する。",
    exampleReading: "いいんかいのいいんとしてさんかする。",
    exampleMeaning: "to participate as a committee member",
    type: ["noun"]
  },
  { 
    word: "嫌う",
    reading: "きらう",
    meaning: "to dislike, to hate",
    example: "彼は嘘を嫌う。",
    exampleReading: "かれはうそをきらう。",
    exampleMeaning: "He dislikes lies.",
    type: ["う verb"]
  },
  { 
    word: "孫",
    reading: "まご",
    meaning: "grandchild",
    example: "祖父は孫を可愛がる。",
    exampleReading: "そふはまごをかわいがる。",
    exampleMeaning: "The grandfather dotes on his grandchild.",
    type: ["noun"]
  },
  { 
    word: "守る",
    reading: "まもる",
    meaning: "to protect, to guard, to keep",
    example: "法律を守る。",
    exampleReading: "ほうりつをまもる。",
    exampleMeaning: "to obey the law",
    type: ["う verb"]
  },
  { 
    word: "完成",
    reading: "かんせい",
    meaning: "completion, accomplishment",
    example: "プロジェクトが完成した。",
    exampleReading: "プロジェクトがかんせいした。",
    exampleMeaning: "The project has been completed.",
    type: ["noun", "する verb"]
  },
  { 
    word: "家事",
    reading: "かじ",
    meaning: "housework, household chores",
    example: "毎日家事をする。",
    exampleReading: "まいにちかじをする。",
    exampleMeaning: "to do household chores every day",
    type: ["noun", "する verb"]
  },
  { 
    word: "家賃",
    reading: "やちん",
    meaning: "rent (for a house or apartment)",
    example: "家賃を払う。",
    exampleReading: "やちんをはらう。",
    exampleMeaning: "to pay the rent",
    type: ["noun"]
  },
  { 
    word: "宿泊",
    reading: "しゅくはく",
    meaning: "accommodation, lodging",
    example: "ホテルに宿泊する。",
    exampleReading: "ホテルにしゅくはくする。",
    exampleMeaning: "to stay at a hotel",
    type: ["noun", "する verb"]
  },
  { 
    word: "就職",
    reading: "しゅうしょく",
    meaning: "employment, getting a job",
    example: "就職活動を始める。",
    exampleReading: "しゅうしょくかつどうをはじめる。",
    exampleMeaning: "to start job hunting",
    type: ["noun", "する verb"]
  },
  { 
    word: "希望",
    reading: "きぼう",
    meaning: "hope, wish, desire",
    example: "新しい仕事に希望を持つ。",
    exampleReading: "あたらしいしごとにきぼうをもつ。",
    exampleMeaning: "to have hope for a new job",
    type: ["noun", "する verb"]
  },
  { 
    word: "常識",
    reading: "じょうしき",
    meaning: "common sense, general knowledge",
    example: "常識を持って行動する。",
    exampleReading: "じょうしきをもってこうどうする。",
    exampleMeaning: "to act with common sense",
    type: ["noun"]
  },
  { 
    word: "幅",
    reading: "はば",
    meaning: "width, breadth, range",
    example: "道路の幅が広い。",
    exampleReading: "どうろのはばがひろい。",
    exampleMeaning: "The road is wide.",
    type: ["noun"]
  },
  { 
    word: "平和",
    reading: "へいわ",
    meaning: "peace, harmony",
    example: "世界の平和を願う。",
    exampleReading: "せかいのへいわをねがう。",
    exampleMeaning: "to wish for world peace",
    type: ["noun", "な adjective"]
  },
  { 
    word: "平均",
    reading: "へいきん",
    meaning: "average, mean, equilibrium, balance",
    example: "クラスの平均点を計算する。",
    exampleReading: "クラスのへいきんてんをけいさんする。",
    exampleMeaning: "to calculate the average score of the class",
    type: ["noun", "する verb"]
  },
  { 
    word: "年月",
    reading: "ねんげつ・としつき",
    meaning: "years and months, time",
    example: "年月が経つのは早い。",
    exampleReading: "ねんげつがたつのははやい。",
    exampleMeaning: "Time passes quickly.",
    type: ["noun"]
  },
  { 
    word: "年齢",
    reading: "ねんれい",
    meaning: "age, years old",
    example: "年齢を聞かれるのは嫌だ。",
    exampleReading: "ねんれいをきかれるのはいやだ。",
    exampleMeaning: "I dislike being asked my age.",
    type: ["noun"]
  },
  { 
    word: "広がる",
    reading: "ひろがる",
    meaning: "to spread, to expand",
    example: "花が広がる。",
    exampleReading: "はながひろがる。",
    exampleMeaning: "The flowers spread out.",
    type: ["う verb"]
  },
  { 
    word: "建設",
    reading: "けんせつ",
    meaning: "construction, building",
    example: "新しいビルの建設が始まる。",
    exampleReading: "あたらしいビルのけんせつがはじまる。",
    exampleMeaning: "The construction of the new building begins.",
    type: ["noun", "する verb"]
  },
  { 
    word: "影響",
    reading: "えいきょう",
    meaning: "influence, effect",
    example: "環境問題が経済に影響を与える。",
    exampleReading: "かんきょうもんだいがけいざいにえいきょうをあたえる。",
    exampleMeaning: "Environmental issues influence the economy.",
    type: ["noun", "する verb"]
  },
  { 
    word: "役",
    reading: "やく",
    meaning: "role, part, duty, service",
    example: "映画で重要な役を演じる。",
    exampleReading: "えいがでじゅうようなやくをえんじる。",
    exampleMeaning: "to play an important role in a movie",
    type: ["noun", "する verb"]
  },
  { 
    word: "得る",
    reading: "える",
    meaning: "to obtain, to get, to acquire",
    example: "知識を得るために勉強する。",
    exampleReading: "ちしきをえるためにべんきょうする。",
    exampleMeaning: "to study to acquire knowledge",
    type: ["る verb"]
  },
  { 
    word: "得意",
    reading: "とくい",
    meaning: "one's strong point, pride, skill",
    example: "数学が得意だ。",
    exampleReading: "すうがくがとくいだ。",
    exampleMeaning: "I am good at mathematics.",
    type: ["な adjective", "noun"]
  },
  { 
    word: "徹夜",
    reading: "てつや",
    meaning: "all night, staying up all night",
    example: "徹夜で勉強する。",
    exampleReading: "てつやでべんきょうする。",
    exampleMeaning: "to study all night",
    type: ["noun", "する verb"]
  },
  { 
    word: "快適",
    reading: "かいてき",
    meaning: "comfortable, pleasant",
    example: "このソファは快適だ。",
    exampleReading: "このソファはかいてきだ。",
    exampleMeaning: "This sofa is comfortable.",
    type: ["な adjective", "noun"]
  },
  { 
    word: "急に",
    reading: "きゅうに",
    meaning: "suddenly, abruptly",
    example: "急に雨が降り出した。",
    exampleReading: "きゅうにあめがふりだした。",
    exampleMeaning: "It suddenly started to rain.",
    type: ["adverb"]
  },
  { 
    word: "性格",
    reading: "せいかく",
    meaning: "character, personality",
    example: "彼の性格は明るい。",
    exampleReading: "かれのせいかくはあかるい。",
    exampleMeaning: "His personality is cheerful.",
    type: ["noun"]
  },
  { 
    word: "悩む",
    reading: "なやむ",
    meaning: "to be troubled, to worry, to be uncertain",
    example: "将来のことで悩む。",
    exampleReading: "しょうらいのことでなやむ。",
    exampleMeaning: "to worry about the future",
    type: ["う verb"]
  },
  { 
    word: "悪口",
    reading: "わるぐち・あっこう",
    meaning: "badmouthing, slander, insult、badmouthing",
    example: "人の悪口を言わない。",
    exampleReading: "ひとのわるぐちをいわない。",
    exampleMeaning: "I don't speak ill of others.",
    type: ["noun"]
  },
  { 
    word: "情報",
    reading: "じょうほう",
    meaning: "information, news",
    example: "最新の情報を得る。",
    exampleReading: "さいしんのじょうほうをえる。",
    exampleMeaning: "to obtain the latest information",
    type: ["noun"]
  },
  { 
    word: "想像",
    reading: "そうぞう",
    meaning: "imagination, guess, conception",
    example: "未来のことを想像する。",
    exampleReading: "みらいのことをそうぞうする。",
    exampleMeaning: "to imagine the future",
    type: ["noun", "する verb"]
  },
  { 
    word: "愛情",
    reading: "あいじょう",
    meaning: "affection, love, emotion",
    example: "親の愛情を感じる。",
    exampleReading: "おやのあいじょうをかんじる。",
    exampleMeaning: "to feel a parent's love",
    type: ["noun"]
  },
  { 
    word: "感謝",
    reading: "かんしゃ",
    meaning: "gratitude, appreciation",
    example: "助けてくれた人に感謝する。",
    exampleReading: "たすけてくれたひとにかんしゃする。",
    exampleMeaning: "to express gratitude to the person who helped",
    type: ["noun", "する verb"]
  },
  { 
    word: "態度",
    reading: "たいど",
    meaning: "attitude, manner, behavior",
    example: "彼の態度が気に入らない。",
    exampleReading: "かれのたいどがきにいらない。",
    exampleMeaning: "I don't like his attitude.",
    type: ["noun"]
  },
  { 
    word: "成功",
    reading: "せいこう",
    meaning: "success, achievement",
    example: "プロジェクトが成功した。",
    exampleReading: "プロジェクトがせいこうした。",
    exampleMeaning: "The project was successful.",
    type: ["noun", "する verb"]
  },
  { 
    word: "成績",
    reading: "せいせき",
    meaning: "grades, results, performance",
    example: "試験の成績が良かった。",
    exampleReading: "しけんのせいせきがよかった。",
    exampleMeaning: "I got good results on the exam.",
    type: ["noun"]
  },
  { 
    word: "戻す",
    reading: "もどす",
    meaning: "to return, to put back, to restore",
    example: "本を元の場所に戻す。",
    exampleReading: "ほんをもとのばしょにもどす。",
    exampleMeaning: "to return the book to its original place",
    type: ["う verb"]
  },
  { 
    word: "手伝い",
    reading: "てつだい",
    meaning: "help, assistance",
    example: "友達の手伝いをする。",
    exampleReading: "ともだちのてつだいをする。",
    exampleMeaning: "to help a friend",
    type: ["noun", "する verb"]
  },
  { 
    word: "手術",
    reading: "しゅじゅつ",
    meaning: "surgery, operation",
    example: "手術を受ける。",
    exampleReading: "しゅじゅつをうける。",
    exampleMeaning: "to undergo surgery",
    type: ["noun", "する verb"]
  },
  { 
    word: "投票",
    reading: "とうひょう",
    meaning: "vote, voting",
    example: "選挙で投票する。",
    exampleReading: "せんきょでとうひょうする。",
    exampleMeaning: "to vote in an election",
    type: ["noun", "する verb"]
  },
  { 
    word: "抜ける",
    reading: "ぬける",
    meaning: "to come out, to fall out, to be omitted",
    example: "髪の毛が抜ける。",
    exampleReading: "かみのけがぬける。",
    exampleMeaning: "Hair falls out.",
    type: ["る verb"]
  },
  { 
    word: "抱く",
    reading: "だく・いだく",
    meaning: "to hold, to embrace, to harbor (feelings), to hug",
    example: "赤ちゃんを抱く。",
    exampleReading: "あかちゃんをだく。",
    exampleMeaning: "to hold a baby",
    type: ["う verb"]
  },
  { 
    word: "指導",
    reading: "しどう",
    meaning: "guidance, leadership, coaching",
    example: "先生が学生を指導する。",
    exampleReading: "せんせいががくせいをしどうする。",
    exampleMeaning: "The teacher guides the students.",
    type: ["noun", "する verb"]
  },
  { 
    word: "描く",
    reading: "えがく・かく",
    meaning: "to draw, to paint, to depict",
    example: "風景を描く。",
    exampleReading: "ふうけいをえがく。",
    exampleMeaning: "to draw a landscape",
    type: ["う verb"]
  },
  { 
    word: "援助",
    reading: "えんじょ",
    meaning: "assistance, support, aid",
    example: "被災地に援助を送る。",
    exampleReading: "ひさいちにえんじょをおくる。",
    exampleMeaning: "to send aid to the disaster area",
    type: ["noun", "する verb"]
  },
  { 
    word: "操作",
    reading: "そうさ",
    meaning: "operation, manipulation, control, management",
    example: "コンピューターを操作する。",
    exampleReading: "コンピューターをそうさする。",
    exampleMeaning: "to operate a computer",
    type: ["noun", "する verb"]
  },
  { 
    word: "支払う",
    reading: "しはらう",
    meaning: "to pay, to settle (a bill)",
    example: "代金を支払う。",
    exampleReading: "だいきんをしはらう。",
    exampleMeaning: "to pay the bill",
    type: ["う verb"]
  },
  { 
    word: "攻撃",
    reading: "こうげき",
    meaning: "attack, assault, offense",
    example: "敵を攻撃する。",
    exampleReading: "てきをこうげきする。",
    exampleMeaning: "to attack the enemy",
    type: ["noun", "する verb"]
  },
  { 
    word: "故郷",
    reading: "ふるさと・こきょう",
    meaning: "hometown, birthplace",
    example: "故郷に帰る。",
    exampleReading: "ふるさとにかえる。",
    exampleMeaning: "to return to my hometown",
    type: ["noun"]
  },
  { 
    word: "教師",
    reading: "きょうし",
    meaning: "teacher, instructor",
    example: "彼は優秀な教師だ。",
    exampleReading: "かれはゆうしゅうなきょうしだ。",
    exampleMeaning: "He is an excellent teacher.",
    type: ["noun"]
  },
  { 
    word: "数",
    reading: "かず",
    meaning: "number, amount, count",
    example: "数を数える。",
    exampleReading: "かずをかぞえる。",
    exampleMeaning: "to count numbers",
    type: ["noun", "する verb"]
  },
  { 
    word: "数",
    reading: "すう",
    meaning: "number, numeral, figure, several; a few",
    example: "数を計算する。",
    exampleReading: "すうをけいさんする。",
    exampleMeaning: "to calculate numbers",
    type: ["noun"]
  },
  { 
    word: "数える",
    reading: "かぞえる",
    meaning: "to count, to enumerate",
    example: "指で数える。",
    exampleReading: "ゆびでかぞえる。",
    exampleMeaning: "to count on fingers",
    type: ["る verb"]
  },
  { 
    word: "文句",
    reading: "もんく",
    meaning: "complaint, objection, phrase",
    example: "文句を言うのはやめてください。",
    exampleReading: "もんくをいうのはやめてください。",
    exampleMeaning: "Please stop complaining.",
    type: ["noun"]
  },
  { 
    word: "断る",
    reading: "ことわる",
    meaning: "to refuse, to decline, to reject",
    example: "誘いを断る。",
    exampleReading: "さそいをことわる。",
    exampleMeaning: "to decline an invitation",
    type: ["う verb"]
  },
  { 
    word: "新鮮",
    reading: "しんせん",
    meaning: "fresh, new, original",
    example: "新鮮な野菜を食べる。",
    exampleReading: "しんせんなやさいをたべる。",
    exampleMeaning: "to eat fresh vegetables",
    type: ["な adjective", "noun"]
  },
  { 
    word: "方々",
    reading: "かたがた",
    meaning: "people, persons, gentlemen, ladies",
    example: "方々にご迷惑をおかけしました。",
    exampleReading: "かたがたにごめいわくをおかけしました。",
    exampleMeaning: "I apologize for the inconvenience caused to everyone.",
    type: ["noun"]
  },
  { 
    word: "方法",
    reading: "ほうほう",
    meaning: "method, way, means",
    example: "問題を解決する方法を考える。",
    exampleReading: "もんだいをかいけつするほうほうをかんがえる。",
    exampleMeaning: "to think of a way to solve the problem",
    type: ["noun"]
  },
  { 
    word: "時期",
    reading: "じき",
    meaning: "time, period, season",
    example: "旅行の時期を決める。",
    exampleReading: "りょこうのじきをきめる。",
    exampleMeaning: "to decide the time for the trip",
    type: ["noun"]
  },
  { 
    word: "最高",
    reading: "さいこう",
    meaning: "highest, supreme, best",
    example: "彼は最高のパフォーマンスを見せた。",
    exampleReading: "かれはさいこうのパフォーマンスをみせた。",
    exampleMeaning: "He gave the best performance.",
    type: ["な adjective", "noun"]
  },
  { 
    word: "期待",
    reading: "きたい",
    meaning: "expectation, anticipation, hope",
    example: "新しいプロジェクトに期待する。",
    exampleReading: "あたらしいプロジェクトにきたいする。",
    exampleMeaning: "to have high expectations for the new project",
    type: ["noun", "する verb"]
  },
  { 
    word: "条件",
    reading: "じょうけん",
    meaning: "condition, requirement, term",
    example: "契約の条件を確認する。",
    exampleReading: "けいやくのじょうけんをかくにんする。",
    exampleMeaning: "to confirm the terms of the contract",
    type: ["noun"]
  },
  { 
    word: "栄養",
    reading: "えいよう",
    meaning: "nutrition, nourishment",
    example: "バランスの取れた栄養を摂る。",
    exampleReading: "バランスのとれたえいようをとる。",
    exampleMeaning: "to take a balanced diet",
    type: ["noun"]
  },
  { 
    word: "根",
    reading: "ね",
    meaning: "root (of a plant, toothm hair), origin, basis",
    example: "木の根が地面に広がる。",
    exampleReading: "きのねがじめんにひろがる。",
    exampleMeaning: "The roots of the tree spread in the ground.",
    type: ["noun"]
  },
  { 
    word: "検査",
    reading: "けんさ",
    meaning: "inspection, examination, test",
    example: "健康診断で検査を受ける。",
    exampleReading: "けんこうしんだんでけんさをうける。",
    exampleMeaning: "to undergo an examination in a health check-up",
    type: ["noun", "する verb"]
  },
  { 
    word: "極",
    reading: "きょく",
    meaning: "pole, extreme, utmost",
    example: "極寒の地に住む。",
    exampleReading: "きょっかんのちにすむ。",
    exampleMeaning: "to live in a place of extreme cold",
    type: ["noun"]
  },
  { 
    word: "様子",
    reading: "ようす",
    meaning: "state, appearance, condition",
    example: "彼の様子がおかしい。",
    exampleReading: "かれのようすがおかしい。",
    exampleMeaning: "He seems to be in a strange condition.",
    type: ["noun"]
  },
  { 
    word: "機嫌",
    reading: "きげん",
    meaning: "mood, temper, spirits",
    example: "彼女の機嫌が良い。",
    exampleReading: "かのじょのきげんがよい。",
    exampleMeaning: "She is in a good mood.",
    type: ["noun", "な adjective"]
  },
  { 
    word: "機能",
    reading: "きのう",
    meaning: "function, feature, capability",
    example: "このアプリの機能は便利だ。",
    exampleReading: "このアプリのきのうはべんりだ。",
    exampleMeaning: "The features of this app are convenient.",
    type: ["noun", "する verb"]
  },
  { 
    word: "欠席",
    reading: "けっせき",
    meaning: "absence, non-attendance",
    example: "会議を欠席する。",
    exampleReading: "かいぎをけっせきする。",
    exampleMeaning: "to be absent from the meeting",
    type: ["noun", "する verb"]
  },
  { 
    word: "歌手",
    reading: "かしゅ",
    meaning: "singer, vocalist",
    example: "彼は有名な歌手だ。",
    exampleReading: "かれはゆうめいなかしゅだ。",
    exampleMeaning: "He is a famous singer.",
    type: ["noun"]
  },
  { 
    word: "正直",
    reading: "しょうじき",
    meaning: "honesty, integrity, truthfulness",
    example: "正直に答える。",
    exampleReading: "しょうじきにこたえる。",
    exampleMeaning: "to answer honestly",
    type: ["な adjective", "noun"]
  },
  { 
    word: "正確",
    reading: "せいかく",
    meaning: "accuracy, precision, correctness",
    example: "正確な情報を提供する。",
    exampleReading: "せいかくなじょうほうをていきょうする。",
    exampleMeaning: "to provide accurate information",
    type: ["な adjective", "noun"]
  },
  { 
    word: "残り",
    reading: "のこり",
    meaning: "remainder, leftover, balance",
    example: "食べ物の残りを冷蔵庫に入れる。",
    exampleReading: "たべものののこりをれいぞうこにいれる。",
    exampleMeaning: "to put the leftover food in the refrigerator",
    type: ["noun",]
  },
  { 
    word: "気に入る",
    reading: "きにいる",
    meaning: "to like, to be pleased with",
    example: "この服が気に入った。",
    exampleReading: "このふくがきにいった。",
    exampleMeaning: "I liked this clothes.",
    type: ["expression"]
  },
  { 
    word: "気候",
    reading: "きこう",
    meaning: "climate, weather",
    example: "この地域の気候は温暖だ。",
    exampleReading: "このちいきのきこうはおんだんだ。",
    exampleMeaning: "The climate of this area is mild.",
    type: ["noun"]
  },
  { 
    word: "決心",
    reading: "けっしん",
    meaning: "determination, resolution, decision",
    example: "新しい目標を決心する。",
    exampleReading: "あたらしいもくひょうをけっしんする。",
    exampleMeaning: "to make a new goal",
    type: ["noun", "する verb"]
  },
  { 
    word: "泥",
    reading: "どろ",
    meaning: "mud, dirt, soil",
    example: "泥で靴が汚れる。",
    exampleReading: "どろでくつがよごれる。",
    exampleMeaning: "The shoes get dirty with mud.",
    type: ["noun"]
  },
  { 
    word: "注ぐ",
    reading: "そそぐ",
    meaning: "to pour (in a container), to water (plants), to flow into (a river)",
    example: "お茶を注ぐ。",
    exampleReading: "おちゃをそそぐ。",
    exampleMeaning: "to pour tea",
    type: ["う verb"]
  },
  { 
    word: "注文",
    reading: "ちゅうもん",
    meaning: "order, request, subscription",
    example: "レストランで注文する。",
    exampleReading: "レストランでちゅうもんする。",
    exampleMeaning: "to place an order at the restaurant",
    type: ["noun", "する verb"]
  },
  { 
    word: "流行",
    reading: "りゅうこう",
    meaning: "fashion, trend, vogue",
    example: "この服は流行している。",
    exampleReading: "このふくはりゅうこうしている。",
    exampleMeaning: "This clothing is in fashion.",
    type: ["noun", "する verb"]
  },
  { 
    word: "涙",
    reading: "なみだ",
    meaning: "tears, weeping",
    example: "感動して涙が出た。",
    exampleReading: "かんどうしてなみだがでた。",
    exampleMeaning: "I was moved to tears.",
    type: ["noun"]
  },
];