export const KANJI_GENKI_LESSON_14: Array<KanjiYDC> = [
  {
    kanji: '彼',
    onyomi: [],
    kunyomi: ['かれ', 'かの'],
    meaning: ['He'],
    examples: [
      {
        reading: '彼氏',
        kana: 'かれし',
        meaning: ['Boyfriend'],
        sentence: '彼氏が欲しい。',
        type: 'main',
      },
      {
        reading: '彼女',
        kana: 'かのじょ',
        meaning: ['Girlfriend'],
        sentence: '彼女が欲しい。',
        type: 'main',
      },
      {
        reading: '彼ら',
        kana: 'かれら',
        meaning: ['They'],
        sentence: '彼らは学生です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '代',
    onyomi: ['だい'],
    kunyomi: ['か'],
    meaning: ['Age', 'Era', 'Replace'],
    examples: [
      {
        reading: '時代',
        kana: 'じだい',
        meaning: ['Age', 'Era', 'Period'],
        sentence: '時代が変わりました。',
        type: 'main',
      },
      {
        reading: '電気代',
        kana: 'でんきだい',
        meaning: ['Electricity bill'],
        sentence: '電気代が高いです。',
        type: 'main',
      },
      {
        reading: '九十年代',
        kana: 'きゅうじゅうねんだい',
        meaning: ['The 90s'],
        sentence: '九十年代の音楽が好きです。',
        type: 'secondary',
      },
      {
        reading: '十代',
        kana: 'じゅうだい',
        meaning: ['Teenager', 'At one\'s teens'],
        sentence: '十代の頃は楽しかった。',
        type: 'secondary',
      },
      {
        reading: '代わりに',
        kana: 'かわりに',
        meaning: ['Instead', 'Instead of', 'In exchange for'],
        sentence: '代わりに何か飲みますか。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '留',
    onyomi: ['りゅう', 'る'],
    kunyomi: [],
    meaning: ['To Stay', 'To Keep'],
    examples: [
      {
        reading: '留学生',
        kana: 'りゅうがくせい',
        meaning: ['International student'],
        sentence: '留学生と話します。',
        type: 'main',
      },
      {
        reading: '留学する',
        kana: 'りゅうがくする',
        meaning: ['To study abroad'],
        sentence: '留学することになりました。',
        type: 'main',
      },
      {
        reading: '留守',
        kana: 'るす',
        meaning: ['Absence', 'Not at home'],
        sentence: '留守の間に荷物が届きました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '族',
    onyomi: ['ぞく'],
    kunyomi: [],
    meaning: ['Family', 'Tribe'],
    examples: [
      {
        reading: '家族',
        kana: 'かぞく',
        meaning: ['Family'],
        sentence: '家族で旅行します。',
        type: 'main',
      },
      {
        reading: '民族',
        kana: 'みんぞく',
        meaning: ['Ethnic group'],
        sentence: '民族が多い国です。',
        type: 'secondary',
      },
      {
        reading: '王族',
        kana: 'おうぞく',
        meaning: ['Royal family', 'Members of the royalty'],
        sentence: '王族が住んでいます。',
        type: 'secondary',
      },
      {
        reading: '水族館',
        kana: 'すいぞくかん',
        meaning: ['Aquarium'],
        sentence: '水族館に行きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '親',
    onyomi: ['しん'],
    kunyomi: ['おや', 'した'],
    meaning: ['Parent', 'Intimacy'],
    examples: [
      {
        reading: '父親',
        kana: 'ちちおや',
        meaning: ['Father'],
        sentence: '父親が帰りました。',
        type: 'main',
      },
      {
        reading: '母親',
        kana: 'ははおや',
        meaning: ['Mother'],
        sentence: '母親が忙しいです。',
        type: 'main',
      },
      {
        reading: '親切な',
        kana: 'しんせつな',
        meaning: ['Kind'],
        sentence: '親切な人です。',
        type: 'main',
      },
      {
        reading: '親友',
        kana: 'しんゆう',
        meaning: ['Close friend', 'Best friend'],
        sentence: '親友と遊びます。',
        type: 'main',
      },
      {
        reading: '両親',
        kana: 'りょうしん',
        meaning: ['Parents'],
        sentence: '両親と話します。',
        type: 'main',
      },
      {
        reading: '親しい',
        kana: 'したしい',
        meaning: ['Close', 'Intimate'],
        sentence: '親しい友達です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '切',
    onyomi: ['せつ'],
    kunyomi: ['き', 'きっ'],
    meaning: ['To Cut'],
    examples: [
      {
        reading: '親切な',
        kana: 'しんせつな',
        meaning: ['Kind'],
        sentence: '親切な人です。',
        type: 'main',
      },
      {
        reading: '切る',
        kana: 'きる',
        meaning: ['To cut'],
        sentence: '野菜を切ります。',
        type: 'main',
      },
      {
        reading: '切符',
        kana: 'きっぷ',
        meaning: ['Ticket'],
        sentence: '切符を買います。',
        type: 'main',
      },
      {
        reading: '切手',
        kana: 'きって',
        meaning: ['Postage Stamp'],
        sentence: '切手を貼ります。',
        type: 'main',
      },
      {
        reading: '大切な',
        kana: 'たいせつな',
        meaning: ['Precious', 'Important'],
        sentence: '大切な友達です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '英',
    onyomi: ['えい'],
    kunyomi: [],
    meaning: ['English', 'Excellent'],
    examples: [
      {
        reading: '英語',
        kana: 'えいご',
        meaning: ['English language'],
        sentence: '英語を話せる。',
        type: 'main',
      },
      {
        reading: '英会話',
        kana: 'えいかいわ',
        meaning: ['English conversation'],
        sentence: '英会話を習います。',
        type: 'main',
      },
      {
        reading: '英雄',
        kana: 'えいゆう',
        meaning: ['Hero'],
        sentence: '英雄が現れました。',
        type: 'main',
      },
      {
        reading: '英国',
        kana: 'えいこく',
        meaning: ['England'],
        sentence: '英国に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '店',
    onyomi: ['てん'],
    kunyomi: ['みせ'],
    meaning: ['Store', 'Shop'],
    examples: [
      {
        reading: '店',
        kana: 'みせ',
        meaning: ['Store', 'Shop'],
        sentence: '店に行きます。',
        type: 'main',
      },
      {
        reading: '店員',
        kana: 'てんいん',
        meaning: ['Shop assistant', 'Salesclerk'],
        sentence: '店員に聞きます。',
        type: 'main',
      },
      {
        reading: '店長',
        kana: 'てんちょう',
        meaning: ['Store manager'],
        sentence: '店長に話します。',
        type: 'main',
      },
      {
        reading: '書店',
        kana: 'しょてん',
        meaning: ['Bookstore'],
        sentence: '書店に行きます。',
        type: 'main',
      },
      {
        reading: '売店',
        kana: 'ばいてん',
        meaning: ['Shop', 'Kiosk'],
        sentence: '売店で飲み物を買います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '去',
    onyomi: ['きょ', 'こ'],
    kunyomi: ['さ'],
    meaning: ['To Leave', 'Past'],
    examples: [
      {
        reading: '去年',
        kana: 'きょねん',
        meaning: ['Last year'],
        sentence: '去年の夏は暑かった。',
        type: 'main',
      },
      {
        reading: '去る',
        kana: 'さる',
        meaning: ['To leave', 'To go away'],
        sentence: '去る日本に行きます。',
        type: 'main',
      },
      {
        reading: '消去する',
        kana: 'しょうきょする',
        meaning: ['To erase', 'To delete'],
        sentence: '消去することになりました。',
        type: 'secondary',
      },
      {
        reading: '過去',
        kana: 'かこ',
        meaning: ['Past'],
        sentence: '過去のことを思い出します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '急',
    onyomi: ['きゅう'],
    kunyomi: ['いそ'],
    meaning: ['Urgent', 'Hurry'],
    examples: [
      {
        reading: '急に',
        kana: 'きゅうに',
        meaning: ['Suddenly', 'Abruptly'],
        sentence: '急に雨が降りました。',
        type: 'main',
      },
      {
        reading: '急ぐ',
        kana: 'いそぐ',
        meaning: ['To hurry', 'To rush'],
        sentence: '急いで学校に行きます。',
        type: 'main',
      },
      {
        reading: '急行',
        kana: 'きゅうこう',
        meaning: ['Express train'],
        sentence: '急行で行きます。',
        type: 'main',
      },
      {
        reading: '特急',
        kana: 'とっきゅう',
        meaning: ['Limited express train', 'Super express train'],
        sentence: '特急で行きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '乗',
    onyomi: ['じょう'],
    kunyomi: ['の'],
    meaning: ['To Ride', 'To Board'],
    examples: [
      {
        reading: '乗る',
        kana: 'のる',
        meaning: ['To ride', 'To board'],
        sentence: '電車に乗ります。',
        type: 'main',
      },
      {
        reading: '乗り物',
        kana: 'のりもの',
        meaning: ['Vehicle'],
        sentence: '乗り物が好きです。',
        type: 'main',
      },
      {
        reading: '乗車',
        kana: 'じょうしゃ',
        meaning: ['Riding a car'],
        sentence: '乗車券を買います。',
        type: 'main',
      },
      {
        reading: '乗馬',
        kana: 'じょうば',
        meaning: ['Horseback riding'],
        sentence: '乗馬をします。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '当',
    onyomi: ['とう'],
    kunyomi: ['あ'],
    meaning: ['To Hit'],
    examples: [
      {
        reading: '本当に',
        kana: 'ほんとうに',
        meaning: ['Really', 'Truly'],
        sentence: '本当に行きます。',
        type: 'main',
      },
      {
        reading: 'お弁当',
        kana: 'おべんとう',
        meaning: ['Boxed lunch'],
        sentence: 'お弁当を食べます。',
        type: 'main',
      },
      {
        reading: '当時',
        kana: 'とうじ',
        meaning: ['At that time', 'In those days'],
        sentence: '当時は楽しかった。',
        type: 'main',
      },
      {
        reading: '当たる',
        kana: 'あたる',
        meaning: ['To hit', 'To be correct'],
        sentence: '当たるといいです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '音',
    onyomi: ['おん'],
    kunyomi: ['おと', 'ね'],
    meaning: ['Sound'],
    examples: [
      {
        reading: '音楽',
        kana: 'おんがく',
        meaning: ['Music'],
        sentence: '音楽が好きです。',
        type: 'main',
      },
      {
        reading: '音',
        kana: 'おと',
        meaning: ['Sound'],
        sentence: '音が大きいです。',
        type: 'main',
      },
      {
        reading: '本音',
        kana: 'ほんね',
        meaning: ['True feelings', 'One\'s real intention'],
        sentence: '本音を言います。',
        type: 'main',
      },
      {
        reading: '発音',
        kana: 'はつおん',
        meaning: ['Pronunciation'],
        sentence: '発音が難しいです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '楽',
    onyomi: ['がく', 'がっ', 'らく'],
    kunyomi: ['たの'],
    meaning: ['pleasure'],
    examples: [
      {
        reading: '音楽',
        kana: 'おんがく',
        meaning: ['Music'],
        sentence: '音楽が好きです。',
        type: 'main',
      },
      {
        reading: '楽しい',
        kana: 'たのしい',
        meaning: ['Fun', 'Enjoyable'],
        sentence: '楽しい時間です。',
        type: 'main',
      },
      {
        reading: '楽器',
        kana: 'がっき',
        meaning: ['Musical instrument'],
        sentence: '楽器を弾きます。',
        type: 'secondary',
      },
      {
        reading: '楽な',
        kana: 'らくな',
        meaning: ['Easy', 'Comfortable'],
        sentence: '楽な仕事です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '医',
    onyomi: ['い'],
    kunyomi: [],
    meaning: ['Medicine', 'Doctor'],
    examples: [
      {
        reading: '医者',
        kana: 'いしゃ',
        meaning: ['Doctor'],
        sentence: '母は医者です。',
        type: 'main',
      },
      {
        reading: '医院',
        kana: 'いいん',
        meaning: ['Doctor\'s office', 'Clinic'],
        sentence: '医院に行きます。',
        type: 'main',
      },
      {
        reading: '歯医者',
        kana: 'はいしゃ',
        meaning: ['Dentist'],
        sentence: '歯医者に行きます。',
        type: 'main',
      },
      {
        reading: '医学',
        kana: 'いがく',
        meaning: ['Medical science'],
        sentence: '医学を勉強します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '者',
    onyomi: ['しゃ', 'じゃ'],
    kunyomi: ['もの'],
    meaning: ['Person'],
    examples: [
      {
        reading: '医者',
        kana: 'いしゃ',
        meaning: ['Doctor'],
        sentence: '母は医者です。',
        type: 'main',
      },
      {
        reading: '読者',
        kana: 'どくしゃ',
        meaning: ['Reader'],
        sentence: '読者が多いです。',
        type: 'main',
      },
      {
        reading: '若者',
        kana: 'わかもの',
        meaning: ['Young person'],
        sentence: '若者が多いです。',
        type: 'main',
      },
      {
        reading: '学者',
        kana: 'がくしゃ',
        meaning: ['Scholar'],
        sentence: '学者がいます。',
        type: 'main',
      },
      {
        reading: '忍者',
        kana: 'にんじゃ',
        meaning: ['Ninja'],
        sentence: '忍者がいます。',
        type: 'secondary',
      },
    ],
  },
]