export const KANJI_GENKI_LESSON_16: Array<KanjiYDC> = [
  {
    kanji: '供',
    onyomi: ['きょう'],
    kunyomi: ['ども', 'そな'],
    meaning: ['Companion', 'Offer'],
    examples: [
      {
        reading: '子供',
        kana: 'こども',
        meaning: ['Child'],
        sentence: '子供が遊びます。',
        type: 'main',
      },
      {
        reading: '供える',
        kana: 'そなえる',
        meaning: ['To offer something to the gods'],
        sentence: '供えることが大切です。',
        type: 'secondary',
      },
      {
        reading: '提供',
        kana: 'ていきょう',
        meaning: ['Offer'],
        sentence: '提供されたものです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '世',
    onyomi: ['せい', 'せ'],
    kunyomi: ['よ'],
    meaning: ['World', 'Generation'],
    examples: [
      {
        reading: '世界',
        kana: 'せかい',
        meaning: ['World'],
        sentence: '世界中に行きます。',
        type: 'main',
      },
      {
        reading: '世代',
        kana: 'せだい',
        meaning: ['Generation'],
        sentence: '世代が違います。',
        type: 'main',
      },
      {
        reading: '三世',
        kana: 'さんせい',
        meaning: ['Third generation'],
        sentence: '三世の人です。',
        type: 'main',
      },
      {
        reading: '世話',
        kana: 'せわ',
        meaning: ['Care', 'Help'],
        sentence: '世話をします。',
        type: 'main',
      },
      {
        reading: '世の中',
        kana: 'よのなか',
        meaning: ['Society', 'The world'],
        sentence: '世の中が変わりました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '界',
    onyomi: ['かい'],
    kunyomi: [],
    meaning: ['World'],
    examples: [
      {
        reading: '世界',
        kana: 'せかい',
        meaning: ['World'],
        sentence: '世界中に行きます。',
        type: 'main',
      },
      {
        reading: '視界',
        kana: 'しかい',
        meaning: ['Visibility', 'Field of vision'],
        sentence: '視界が悪いです。',
        type: 'main',
      },
      {
        reading: '政界',
        kana: 'せいかい',
        meaning: ['Political world'],
        sentence: '政界に興味があります。',
        type: 'secondary',
      },
      {
        reading: '限界',
        kana: 'げんかい',
        meaning: ['Limit', 'Boundary'],
        sentence: '限界があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '全',
    onyomi: ['ぜん'],
    kunyomi: ['まった', 'すべ'],
    meaning: ['All', 'Whole'],
    examples: [
      {
        reading: '全部',
        kana: 'ぜんぶ',
        meaning: ['All', 'Whole'],
        sentence: '全部食べます。',
        type: 'main',
      },
      {
        reading: '全て',
        kana: 'すべて',
        meaning: ['All', 'Everything'],
        sentence: '全てが好きです。',
        type: 'main',
      },
      {
        reading: '全く',
        kana: 'まったく',
        meaning: ['Completely', 'Entirely'],
        sentence: '全く違います。',
        type: 'main',
      },
      {
        reading: '安全',
        kana: 'あんぜん',
        meaning: ['Safety', 'Security'],
        sentence: '安全な場所です。',
        type: 'main',
      },
      {
        reading: '全国',
        kana: 'ぜんこく',
        meaning: ['Nationwide', 'Whole country'],
        sentence: '全国に行きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '部',
    onyomi: ['ぶ', 'へ'],
    kunyomi: [],
    meaning: ['Part', 'Section'],
    examples: [
      {
        reading: '全部',
        kana: 'ぜんぶ',
        meaning: ['All', 'Whole'],
        sentence: '全部食べます。',
        type: 'main',
      },
      {
        reading: '部屋',
        kana: 'へや',
        meaning: ['Room'],
        sentence: '部屋に行きます。',
        type: 'main',
      },
      {
        reading: 'テニス部',
        kana: 'テニスぶ',
        meaning: ['Tennis club'],
        sentence: 'テニス部に入ります。',
        type: 'main',
      },
      {
        reading: '部長',
        kana: 'ぶちょう',
        meaning: ['Section manager', 'Department manager'],
        sentence: '部長に話します。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '始',
    onyomi: ['し'],
    kunyomi: ['はじ'],
    meaning: ['To Begin'],
    examples: [
      {
        reading: '始まる',
        kana: 'はじまる',
        meaning: ['(Something) begins'],
        sentence: '始まる時間です。',
        type: 'main',
      },
      {
        reading: '始める',
        kana: 'はじめる',
        meaning: ['To begin (Something)', 'To start (Something)'],
        sentence: '始めることが大切です。',
        type: 'main',
      },
      {
        reading: '始発',
        kana: 'しはつ',
        meaning: ['First train (of the day)'],
        sentence: '始発で行きます。',
        type: 'main',
      },
      {
        reading: '開始',
        kana: 'かいし',
        meaning: ['Start', 'Beginning'],
        sentence: '開始時間です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '週',
    onyomi: ['しゅう'],
    kunyomi: [],
    meaning: ['Week'],
    examples: [
      {
        reading: '毎週',
        kana: 'まいしゅう',
        meaning: ['Every week'],
        sentence: '毎週行きます。',
        type: 'main',
      },
      {
        reading: '先週',
        kana: 'せんしゅう',
        meaning: ['Last week'],
        sentence: '先週の天気は良かった。',
        type: 'main',
      },
      {
        reading: '一週間',
        kana: 'いっしゅうかん',
        meaning: ['One week'],
        sentence: '一週間の予定です。',
        type: 'main',
      },
      {
        reading: '二週目',
        kana: 'にしゅうめ',
        meaning: ['Second week'],
        sentence: '二週目の授業です。',
        type: 'main',
      },
      {
        reading: '週末',
        kana: 'しゅうまつ',
        meaning: ['Weekend'],
        sentence: '週末に行きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '考',
    onyomi: ['こう'],
    kunyomi: ['かんが'],
    meaning: ['To Think', 'Idea'],
    examples: [
      {
        reading: '考える',
        kana: 'かんがえる',
        meaning: ['To think', 'To consider'],
        sentence: '考える時間です。',
        type: 'main',
      },
      {
        reading: '考え',
        kana: 'かんがえ',
        meaning: ['Idea', 'Thought'],
        sentence: '考えがあります。',
        type: 'main',
      },
      {
        reading: '参考',
        kana: 'さんこう',
        meaning: ['Reference'],
        sentence: '参考にします。',
        type: 'main',
      },
      {
        reading: '考古学',
        kana: 'こうこがく',
        meaning: ['Archaeology'],
        sentence: '考古学を勉強します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '開',
    onyomi: ['かい'],
    kunyomi: ['あ', 'ひら'],
    meaning: ['To Open'],
    examples: [
      {
        reading: '開ける',
        kana: 'あける',
        meaning: ['To open(Something)'],
        sentence: 'ドアを開けます。',
        type: 'main',
      },
      {
        reading: '開く',
        kana: 'あく',
        meaning: ['(Something) Opens'],
        sentence: '花が開きます。',
        type: 'main',
      },
      {
        reading: '開く',
        kana: 'ひらく',
        meaning: ['To open'],
        sentence: '本を開きます。',
        type: 'main',
      },
      {
        reading: '開店',
        kana: 'かいてん',
        meaning: ['Opening a store'],
        sentence: '開店時間です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '屋',
    onyomi: ['おく'],
    kunyomi: ['や'],
    meaning: ['Shop', 'House'],
    examples: [
      {
        reading: '部屋',
        kana: 'へや',
        meaning: ['Room'],
        sentence: '部屋に行きます。',
        type: 'main',
      },
      {
        reading: '本屋',
        kana: 'ほんや',
        meaning: ['Bookstore'],
        sentence: '本屋に行きます。',
        type: 'main',
      },
      {
        reading: '魚屋',
        kana: 'さかなや',
        meaning: ['Fish store'],
        sentence: '魚屋に行きます。',
        type: 'main',
      },
      {
        reading: '屋上',
        kana: 'おくじょう',
        meaning: ['Rooftop'],
        sentence: '屋上に行きます。',
        type: 'main',
      },
      {
        reading: '屋内',
        kana: 'おくない',
        meaning: ['Indoor'],
        sentence: '屋内で遊びます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '方',
    onyomi: ['ほう'],
    kunyomi: ['かた', 'がた'],
    meaning: ['Direction', 'Person'],
    examples: [
      {
        reading: '味方',
        kana: 'みかた',
        meaning: ['Ally', 'Person on one\'s side'],
        sentence: '味方がいます。',
        type: 'main',
      },
      {
        reading: '読み方',
        kana: 'よみかた',
        meaning: ['How to read'],
        sentence: '読み方が分かります。',
        type: 'main',
      },
      {
        reading: '夕方',
        kana: 'ゆうがた',
        meaning: ['Evening'],
        sentence: '夕方に行きます。',
        type: 'main',
      },
      {
        reading: '両方',
        kana: 'りょうほう',
        meaning: ['Both'],
        sentence: '両方が好きです。',
        type: 'main',
      },
      {
        reading: '方法',
        kana: 'ほうほう',
        meaning: ['Method', 'Way'],
        sentence: '方法があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '運',
    onyomi: ['うん'],
    kunyomi: ['はこ'],
    meaning: ['Transport', 'Luck'],
    examples: [
      {
        reading: '運動',
        kana: 'うんどう',
        meaning: ['Exercise', 'Physical training'],
        sentence: '運動をします。',
        type: 'main',
      },
      {
        reading: '運転',
        kana: 'うんてん',
        meaning: ['Driving'],
        sentence: '運転が上手です。',
        type: 'main',
      },
      {
        reading: '運がいい',
        kana: 'うんがいい',
        meaning: ['To be lucky'],
        sentence: '運がいいです。',
        type: 'main',
      },
      {
        reading: '運命',
        kana: 'うんめい',
        meaning: ['Fate', 'Destiny'],
        sentence: '運命があります。',
        type: 'main',
      },
      {
        reading: '運ぶ',
        kana: 'はこぶ',
        meaning: ['To carry', 'To transport'],
        sentence: '荷物を運びます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '動',
    onyomi: ['どう'],
    kunyomi: ['うご'],
    meaning: ['Movement', 'To Move'],
    examples: [
      {
        reading: '運動',
        kana: 'うんどう',
        meaning: ['Exercise', 'Physical training'],
        sentence: '運動をします。',
        type: 'main',
      },
      {
        reading: '動く',
        kana: 'うごく',
        meaning: ['To move'],
        sentence: '動く時間です。',
        type: 'main',
      },
      {
        reading: '自動車',
        kana: 'じどうしゃ',
        meaning: ['Automobile'],
        sentence: '自動車に乗ります。',
        type: 'main',
      },
      {
        reading: '動物',
        kana: 'どうぶつ',
        meaning: ['Animal'],
        sentence: '動物がいます。',
        type: 'main',
      },
      {
        reading: '動詞',
        kana: 'どうし',
        meaning: ['Verb'],
        sentence: '動詞を勉強します。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '教',
    onyomi: ['きょう'],
    kunyomi: ['おし'],
    meaning: ['Teach'],
    examples: [
      {
        reading: '教える',
        kana: 'おしえる',
        meaning: ['To teach', 'To instruct'],
        sentence: '教える時間です。',
        type: 'main',
      },
      {
        reading: '教室',
        kana: 'きょうしつ',
        meaning: ['Classroom'],
        sentence: '教室に行きます。',
        type: 'main',
      },
      {
        reading: '教会',
        kana: 'きょうかい',
        meaning: ['Church'],
        sentence: '教会に行きます。',
        type: 'secondary',
      },
      {
        reading: '教科書',
        kana: 'きょうかしょ',
        meaning: ['Textbook'],
        sentence: '教科書を読みます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '室',
    onyomi: ['しつ'],
    kunyomi: [],
    meaning: ['Room'],
    examples: [
      {
        reading: '教室',
        kana: 'きょうしつ',
        meaning: ['Classroom'],
        sentence: '教室に行きます。',
        type: 'main',
      },
      {
        reading: '研究室',
        kana: 'けんきゅうしつ',
        meaning: ['Professor\'s office'],
        sentence: '研究室に行きます。',
        type: 'main',
      },
      {
        reading: '地下室',
        kana: 'ちかしつ',
        meaning: ['Basement'],
        sentence: '地下室に行きます。',
        type: 'main',
      },
      {
        reading: '待合室',
        kana: 'まちあいしつ',
        meaning: ['Waiting room'],
        sentence: '待合室に行きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '以',
    onyomi: ['い'],
    kunyomi: [],
    meaning: ['By means of', 'Because of', 'Compared with'],
    examples: [
      {
        reading: '〜以外',
        kana: '〜いがい',
        meaning: ['Except for', 'Other than'],
        sentence: '〜以外の人です。',
        type: 'main',
      },
      {
        reading: '〜以上',
        kana: '〜いじょう',
        meaning: ['More than', 'Over', '...or more'],
        sentence: '〜以上の人です。',
        type: 'main',
      },
      {
        reading: '〜以下',
        kana: '〜いか',
        meaning: ['Less than', 'Under', '...or less'],
        sentence: '〜以下の人です。',
        type: 'main',
      },
      {
        reading: '〜以内',
        kana: '〜いない',
        meaning: ['Within'],
        sentence: '〜以内に行きます。',
        type: 'main',
      },
      {
        reading: '以前',
        kana: 'いぜん',
        meaning: ['Before', 'Previously', 'Formerly'],
        sentence: '以前の話です。',
        type: 'main',
      },
    ],
  },
]