export const KANJI_GENKI_LESSON_13: Array<KanjiYDC> = [
  {
    kanji: '物',
    onyomi: ['ぶつ'],
    kunyomi: ['もの'],
    meaning: ['Thing'],
    examples: [
      {
        reading: '食べ物',
        kana: 'たべもの',
        meaning: ['Food'],
        sentence: '食べ物を食べるのが好きです。',
        type: 'main',
      },
      {
        reading: '飲み物',
        kana: 'のみもの',
        meaning: ['Drink'],
        sentence: '飲み物を買いに行きます。',
        type: 'main',
      },
      {
        reading: '物',
        kana: 'もの',
        meaning: ['Thing'],
        sentence: '物を買いに行きます。',
        type: 'main',
      },
      {
        reading: '買い物',
        kana: 'かいもの',
        meaning: ['Shopping'],
        sentence: '買い物に行きます。',
        type: 'main',
      },
      {
        reading: '動物',
        kana: 'どうぶつ',
        meaning: ['Animal'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '物価',
        kana: 'ぶっか',
        meaning: ['Commodity prices'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '鳥',
    onyomi: ['ちょう'],
    kunyomi: ['とり'],
    meaning: ['Bird'],
    examples: [
      {
        reading: '鳥',
        kana: 'とり',
        meaning: ['Bird'],
        sentence: '鳥が飛んでいます。',
        type: 'main',
      },
      {
        reading: '焼き鳥',
        kana: 'やきとり',
        meaning: ['Grilled chicken'],
        sentence: '焼き鳥を食べたことがありますか。',
        type: 'secondary',
      },
      {
        reading: '白鳥',
        kana: 'はくちょう',
        meaning: ['Swan', 'White bird'],
        sentence: '白鳥が池にいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '料',
    onyomi: ['りょう'],
    kunyomi: [],
    meaning: ['Ingredients'],
    examples: [
      {
        reading: '料理',
        kana: 'りょうり',
        meaning: ['Cooking'],
        sentence: '料理を作るのが好きです。',
        type: 'main',
      },
      {
        reading: '料金',
        kana: 'りょうきん',
        meaning: ['Charge'],
        sentence: '料金を払ってください。',
        type: 'secondary',
      },
      {
        reading: '給料',
        kana: 'きゅうりょう',
        meaning: ['Salary'],
        sentence: '給料が上がりました。',
        type: 'secondary',
      },
      {
        reading: '授業料',
        kana: 'じゅぎょうりょう',
        meaning: ['Tuition fee'],
        sentence: '授業料を払ってください。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '理',
    onyomi: ['り'],
    kunyomi: [],
    meaning: ['Reason'],
    examples: [
      {
        reading: '料理',
        kana: 'りょうり',
        meaning: ['Cooking'],
        sentence: '料理を作るのが好きです。',
        type: 'main',
      },
      {
        reading: '理由',
        kana: 'りゆう',
        meaning: ['Reason'],
        sentence: '理由を教えてください。',
        type: 'secondary',
      },
      {
        reading: '無理な',
        kana: 'むりな',
        meaning: ['Unreasonable', 'Impossible'],
        sentence: '無理なことを言わないでください。',
        type: 'main',
      },
      {
        reading: '地理',
        kana: 'ちり',
        meaning: ['Geography'],
        sentence: '地理が好きです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '特',
    onyomi: ['とく', 'とっ'],
    kunyomi: [],
    meaning: ['Special'],
    examples: [
      {
        reading: '特に',
        kana: 'とくに',
        meaning: ['Especially'],
        sentence: '特に何もありません。',
        type: 'main',
      },
      {
        reading: '特別な',
        kana: 'とくべつな',
        meaning: ['Special'],
        sentence: '特別な日です。',
        type: 'main',
      },
      {
        reading: '特急',
        kana: 'とっきゅう',
        meaning: ['Limited express', 'Super express'],
        sentence: '特急で行きます。',
        type: 'main',
      },
      {
        reading: '特徴',
        kana: 'とくちょう',
        meaning: ['Characteristic', 'Feature'],
        sentence: '特徴があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '安',
    onyomi: ['あん'],
    kunyomi: ['やす'],
    meaning: ['Cheap'],
    examples: [
      {
        reading: '安い',
        kana: 'やすい',
        meaning: ['Cheap'],
        sentence: '安いものを買いたいです。',
        type: 'main',
      },
      {
        reading: '安心',
        kana: 'あんしん',
        meaning: ['Relief'],
        sentence: '安心してください。',
        type: 'main',
      },
      {
        reading: '安全な',
        kana: 'あんぜんな',
        meaning: ['Safe'],
        sentence: '安全な場所です。',
        type: 'main',
      },
      {
        reading: '不安な',
        kana: 'ふあんな',
        meaning: ['Anxious', 'Uneasy'],
        sentence: '不安な気持ちです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '飯',
    onyomi: ['はん'],
    kunyomi: [],
    meaning: ['Food', 'Cooked rice'],
    examples: [
      {
        reading: 'ご飯',
        kana: 'ごはん',
        meaning: ['Rice', 'Meal'],
        sentence: 'ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '朝ご飯',
        kana: 'あさごはん',
        meaning: ['Breakfast'],
        sentence: '朝ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '昼ご飯',
        kana: 'ひるごはん',
        meaning: ['Lunch'],
        sentence: '昼ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '晩ご飯',
        kana: 'ばんごはん',
        meaning: ['Dinner'],
        sentence: '晩ご飯を食べます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '肉',
    onyomi: ['にく'],
    kunyomi: [],
    meaning: ['Meat'],
    examples: [
      {
        reading: '肉',
        kana: 'にく',
        meaning: ['Meat'],
        sentence: '肉を食べます。',
        type: 'main',
      },
      {
        reading: '牛肉',
        kana: 'ぎゅうにく',
        meaning: ['Beef'],
        sentence: '牛肉を食べます。',
        type: 'main',
      },
      {
        reading: '豚肉',
        kana: 'ぶたにく',
        meaning: ['Pork'],
        sentence: '豚肉を食べます。',
        type: 'main',
      },
      {
        reading: '肉屋',
        kana: 'にくや',
        meaning: ['Butcher', 'Meat shop'],
        sentence: '肉屋に行きます。',
        type: 'main',
      },
      {
        reading: '筋肉',
        kana: 'きんにく',
        meaning: ['Muscle'],
        sentence: '筋肉を鍛えます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '悪',
    onyomi: ['あく'],
    kunyomi: ['わる'],
    meaning: ['Bad', 'Wrong'],
    examples: [
      {
        reading: '悪い',
        kana: 'わるい',
        meaning: ['Bad', 'Wrong'],
        sentence: '悪いことをしました。',
        type: 'main',
      },
      {
        reading: '気分が悪い',
        kana: 'きぶんがわるい',
        meaning: ['Feel sick'],
        sentence: '気分が悪いので、明日は学校に行けない。',
        type: 'main',
      },
      {
        reading: '最悪',
        kana: 'さいあく',
        meaning: ['The worst'],
        sentence: '最悪の状況です。',
        type: 'secondary',
      },
      {
        reading: '悪魔',
        kana: 'あくま',
        meaning: ['Devil'],
        sentence: '悪魔が出てきました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '体',
    onyomi: ['たい'],
    kunyomi: ['からだ'],
    meaning: ['Body'],
    examples: [
      {
        reading: '体',
        kana: 'からだ',
        meaning: ['Body'],
        sentence: '体が痛いです。',
        type: 'main',
      },
      {
        reading: '体重',
        kana: 'たいじゅう',
        meaning: ['Body weight'],
        sentence: '体重が増えました。',
        type: 'main',
      },
      {
        reading: '体操',
        kana: 'たいそう',
        meaning: ['Gymnastics', 'Physical exercise'],
        sentence: '体操をします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '同',
    onyomi: ['どう'],
    kunyomi: ['おな'],
    meaning: ['Same'],
    examples: [
      {
        reading: '同じ',
        kana: 'おなじ',
        meaning: ['Same'],
        sentence: '同じことを繰り返しています。',
        type: 'main',
      },
      {
        reading: '同僚',
        kana: 'どうりょう',
        meaning: ['Colleague', 'Co-worker'],
        sentence: '同僚と仕事をします。',
        type: 'main',
      },
      {
        reading: '同級生',
        kana: 'どうきゅうせい',
        meaning: ['Classmate'],
        sentence: '同級生と遊びます。',
        type: 'main',
      },
      {
        reading: '同時',
        kana: 'どうじ',
        meaning: ['At the same time'],
        sentence: '同時に出発します。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '着',
    onyomi: ['ちゃく'],
    kunyomi: ['き', 'ぎ', 'つ'],
    meaning: ['To Wear', 'To reach'],
    examples: [
      {
        reading: '着く',
        kana: 'つく',
        meaning: ['To arrive'],
        sentence: '何時に着きますか。',
        type: 'main',
      },
      {
        reading: '着る',
        kana: 'きる',
        meaning: ['To wear'],
        sentence: '何を着て行きますか。',
        type: 'main',
      },
      {
        reading: '水着',
        kana: 'みずぎ',
        meaning: ['Swimsuit'],
        sentence: '水着を買いました。',
        type: 'main',
      },
      {
        reading: '着物',
        kana: 'きもの',
        meaning: ['Kimono'],
        sentence: '着物を着ます。',
        type: 'main',
      },
      {
        reading: '大阪着',
        kana: 'おおさかちゃく',
        meaning: ['Arrival in Osaka'],
        sentence: '大阪着の飛行機に乗ります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '空',
    onyomi: ['くう'],
    kunyomi: ['そら', 'あ', 'から'],
    meaning: ['Sky', 'Empty'],
    examples: [
      {
        reading: '空港',
        kana: 'くうこう',
        meaning: ['Airport'],
        sentence: '空港に行きます。',
        type: 'main',
      },
      {
        reading: '空気',
        kana: 'くうき',
        meaning: ['Air'],
        sentence: '空気が悪いです。',
        type: 'main',
      },
      {
        reading: '空手',
        kana: 'からて',
        meaning: ['Karate'],
        sentence: '空手を習います。',
        type: 'main',
      },
      {
        reading: '空',
        kana: 'そら',
        meaning: ['Sky'],
        sentence: '空が青いです。',
        type: 'secondary',
      },
      {
        reading: '空く',
        kana: 'あく',
        meaning: ['To become empty', 'To be vacant'],
        sentence: '空いている席があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '港',
    onyomi: ['こう'],
    kunyomi: ['みなと'],
    meaning: ['Port'],
    examples: [
      {
        reading: '空港',
        kana: 'くうこう',
        meaning: ['Airport'],
        sentence: '空港に行きます。',
        type: 'main',
      },
      {
        reading: '神戸港',
        kana: 'こうべこう',
        meaning: ['Kobe Port'],
        sentence: '神戸港に行きます。',
        type: 'secondary',
      },
      {
        reading: '港',
        kana: 'みなと',
        meaning: ['Port'],
        sentence: '港に船が着きます。',
        type: 'secondary',
      },
      {
        reading: '香港',
        kana: 'ホンコン',
        meaning: ['Hong Kong'],
        sentence: '香港に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '昼',
    onyomi: ['ちゅう'],
    kunyomi: ['ひる'],
    meaning: ['Daytime', 'Noon'],
    examples: [
      {
        reading: '昼',
        kana: 'ひる',
        meaning: ['Daytime', 'Noon'],
        sentence: '昼ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '昼ご飯',
        kana: 'ひるごはん',
        meaning: ['Lunch'],
        sentence: '昼ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '昼寝',
        kana: 'ひるね',
        meaning: ['Nap'],
        sentence: '昼寝をします。',
        type: 'main',
      },
      {
        reading: '昼休み',
        kana: 'ひるやすみ',
        meaning: ['Lunch break'],
        sentence: '昼休みに散歩します。',
        type: 'secondary',
      },
      {
        reading: '昼食',
        kana: 'ちゅうしょく',
        meaning: ['Lunch'],
        sentence: '昼食を食べます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '海',
    onyomi: ['かい'],
    kunyomi: ['うみ'],
    meaning: ['Sea', 'Ocean'],
    examples: [
      {
        reading: '海',
        kana: 'うみ',
        meaning: ['Sea', 'Ocean'],
        sentence: '海に行きます。',
        type: 'main',
      },
      {
        reading: '海外',
        kana: 'かいがい',
        meaning: ['Overseas'],
        sentence: '海外に行きます。',
        type: 'main',
      },
      {
        reading: '日本海',
        kana: 'にほんかい',
        meaning: ['Sea of Japan'],
        sentence: '日本海に行きます。',
        type: 'main',
      },
      {
        reading: '北海道',
        kana: 'ほっかいどう',
        meaning: ['Hokkaido'],
        sentence: '北海道に行きます。',
        type: 'main',
      },
      {
        reading: '海岸',
        kana: 'かいがん',
        meaning: ['Coast', 'Beach'],
        sentence: '海岸に行きます。',
        type: 'secondary',
      },
    ],
  },
]