export const KANJI_GENKI_LESSON_15: Array<KanjiYDC> = [
  {
    kanji: '死',
    onyomi: ['し'],
    kunyomi: ['し'],
    meaning: ['Death', 'To Die'],
    examples: [
      {
        reading: '死ね',
        kana: 'しね',
        meaning: ['To die'],
        sentence: 'お前はもう死んでいる。',
        type: 'main',
      },
      {
        reading: '死',
        kana: 'し',
        meaning: ['Death'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '必死',
        kana: 'ひっし',
        meaning: ['Desperate'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '死者',
        kana: 'ししゃ',
        meaning: ['The dead'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '意',
    onyomi: ['い'],
    kunyomi: [],
    meaning: ['Mind', 'Meaning'],
    examples: [
      {
        reading: '意味',
        kana: 'いみ',
        meaning: ['Meaning'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '注意する',
        kana: 'ちゅういする',
        meaning: ['To watch out'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '意見',
        kana: 'いけん',
        meaning: ['Opinion'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '用意する',
        kana: 'よういする',
        meaning: ['To prepare'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '味',
    onyomi: ['み'],
    kunyomi: ['あじ'],
    meaning: ['Taste', 'Flavor'],
    examples: [
      {
        reading: '意味',
        kana: 'いみ',
        meaning: ['Meaning'],
        sentence: '意味が分かりません。',
        type: 'main',
      },
      {
        reading: '趣味',
        kana: 'しゅみ',
        meaning: ['Hobby'],
        sentence: '趣味は何ですか。',
        type: 'main',
      },
      {
        reading: '興味',
        kana: 'きょうみ',
        meaning: ['Interest'],
        sentence: '興味があります。',
        type: 'main',
      },
      {
        reading: '味',
        kana: 'あじ',
        meaning: ['Taste', 'Flavor'],
        sentence: '味がいいです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '注',
    onyomi: ['ちゅう'],
    kunyomi: ['そそ'],
    meaning: ['To Pour', 'To Fill', 'To shed'],
    examples: [
      {
        reading: '注意する',
        kana: 'ちゅういする',
        meaning: ['To watch out'],
        sentence: '注意してください。',
        type: 'main',
      },
      {
        reading: '注文する',
        kana: 'ちゅうもんする',
        meaning: ['To order'],
        sentence: '注文をします。',
        type: 'main',
      },
      {
        reading: '注ぐ',
        kana: 'そそぐ',
        meaning: ['To pour', 'To fill'],
        sentence: 'お茶を注ぎます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '夏',
    onyomi: ['か'],
    kunyomi: ['なつ'],
    meaning: ['Summer'],
    examples: [
      {
        reading: '夏',
        kana: 'なつ',
        meaning: ['Summer'],
        sentence: '夏が好きです。',
        type: 'main',
      },
      {
        reading: '夏休み',
        kana: 'なつやすみ',
        meaning: ['Summer vacation'],
        sentence: '夏休みが楽しいです。',
        type: 'main',
      },
      {
        reading: '初夏',
        kana: 'しょか',
        meaning: ['Early summer'],
        sentence: '初夏です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '魚',
    onyomi: ['ぎょ'],
    kunyomi: ['さかな', 'うお'],
    meaning: ['Fish'],
    examples: [
      {
        reading: '魚',
        kana: 'さかな',
        meaning: ['Fish'],
        sentence: '魚が好きです。',
        type: 'main',
      },
      {
        reading: '魚屋',
        kana: 'さかなや',
        meaning: ['Fish store'],
        sentence: '魚屋に行きます。',
        type: 'main',
      },
      {
        reading: '魚市場',
        kana: 'うおいちば',
        meaning: ['Fish market'],
        sentence: '魚市場に行きます。',
        type: 'main',
      },
      {
        reading: '人魚',
        kana: 'にんぎょ',
        meaning: ['Mermaid'],
        sentence: '人魚がいます。',
        type: 'main',
      },
      {
        reading: '金魚',
        kana: 'きんぎょ',
        meaning: ['Goldfish'],
        sentence: '金魚を飼います。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '寺',
    onyomi: ['じ'],
    kunyomi: ['てら', 'でら'],
    meaning: ['Temple'],
    examples: [
      {
        reading: 'お寺',
        kana: 'おてら',
        meaning: ['Temple'],
        sentence: 'お寺に行きます。',
        type: 'main',
      },
      {
        reading: '東寺',
        kana: 'とうじ',
        meaning: ['Toji Temple'],
        sentence: '東寺に行きます。',
        type: 'secondary',
      },
      {
        reading: '禅寺',
        kana: 'ぜんじ',
        meaning: ['Zen temple'],
        sentence: '禅寺に行きます。',
        type: 'secondary',
      },
      {
        reading: '寺院',
        kana: 'じいん',
        meaning: ['Sacred building'],
        sentence: '寺院に行きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '広',
    onyomi: ['こう'],
    kunyomi: ['ひろ'],
    meaning: ['Wide', 'Spacious'],
    examples: [
      {
        reading: '広い',
        kana: 'ひろい',
        meaning: ['Wide', 'Spacious'],
        sentence: '部屋が広いです。',
        type: 'main',
      },
      {
        reading: '広場',
        kana: 'ひろば',
        meaning: ['Square', 'Plaza', 'Open space'],
        sentence: '広場に行きます。',
        type: 'main',
      },
      {
        reading: '広島',
        kana: 'ひろしま',
        meaning: ['Hiroshima'],
        sentence: '広島に行きます。',
        type: 'main',
      },
      {
        reading: '広告',
        kana: 'こうこく',
        meaning: ['Advertisement'],
        sentence: '広告を見ます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '足',
    onyomi: ['そく'],
    kunyomi: ['あし', 'た'],
    meaning: ['Foot', 'Leg'],
    examples: [
      {
        reading: '足',
        kana: 'あし',
        meaning: ['Foot', 'Leg'],
        sentence: '足が痛いです。',
        type: 'main',
      },
      {
        reading: '足りる',
        kana: 'たりる',
        meaning: ['To be sufficient'],
        sentence: 'お金が足りません。',
        type: 'main',
      },
      {
        reading: '一足',
        kana: 'いっそく',
        meaning: ['One pair of shoes'],
        sentence: '一足買います。',
        type: 'secondary',
      },
      {
        reading: '水不足',
        kana: 'みずぶそく',
        meaning: ['Water shortage'],
        sentence: '水不足です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '転',
    onyomi: ['てん'],
    kunyomi: ['ころ'],
    meaning: ['To roll over'],
    examples: [
      {
        reading: '自転車',
        kana: 'じてんしゃ',
        meaning: ['Bicycle'],
        sentence: '自転車に乗ります。',
        type: 'main',
      },
      {
        reading: '運転する',
        kana: 'うんてんする',
        meaning: ['To drive'],
        sentence: '車を運転します。',
        type: 'main',
      },
      {
        reading: '転ぶ',
        kana: 'ころぶ',
        meaning: ['To fall down'],
        sentence: '転んで怪我をしました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '借',
    onyomi: ['しゃく', 'しゃっ'],
    kunyomi: ['か'],
    meaning: ['To Borrow'],
    examples: [
      {
        reading: '借りる',
        kana: 'かりる',
        meaning: ['To borrow'],
        sentence: '本を借ります。',
        type: 'main',
      },
      {
        reading: '借家',
        kana: 'しゃくや',
        meaning: ['Rented house'],
        sentence: '借家に住みます。',
        type: 'main',
      },
      {
        reading: '借地',
        kana: 'しゃくち',
        meaning: ['Leased land'],
        sentence: '借地に住みます。',
        type: 'main',
      },
      {
        reading: '借金',
        kana: 'しゃっきん',
        meaning: ['Debt'],
        sentence: '借金があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '走',
    onyomi: ['そう'],
    kunyomi: ['はし'],
    meaning: ['To run'],
    examples: [
      {
        reading: '走る',
        kana: 'はしる',
        meaning: ['To run'],
        sentence: '走って学校に行きます。',
        type: 'main',
      },
      {
        reading: '走り書き',
        kana: 'はしりがき',
        meaning: ['Running handwriting'],
        sentence: '走り書きで書きます。',
        type: 'secondary',
      },
      {
        reading: '脱走',
        kana: 'だっそう',
        meaning: ['Escape (from a prison)'],
        sentence: '脱走しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '場',
    onyomi: ['じょう'],
    kunyomi: ['ば'],
    meaning: ['Place'],
    examples: [
      {
        reading: '場所',
        kana: 'ばしょ',
        meaning: ['Place'],
        sentence: '場所を教えてください。',
        type: 'main',
      },
      {
        reading: '工場',
        kana: 'こうじょう',
        meaning: ['Factory'],
        sentence: '工場に行きます。',
        type: 'main',
      },
      {
        reading: '市場',
        kana: 'いちば',
        meaning: ['Market'],
        sentence: '市場に行きます。',
        type: 'main',
      },
      {
        reading: '駐車場',
        kana: 'ちゅうしゃじょう',
        meaning: ['Parking lot'],
        sentence: '駐車場に車を止めます。',
        type: 'main',
      },
      {
        reading: '場合',
        kana: 'ばあい',
        meaning: ['Case'],
        sentence: '場合によって違います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '建',
    onyomi: ['けん'],
    kunyomi: ['た', 'たて'],
    meaning: ['To build'],
    examples: [
      {
        reading: '建物',
        kana: 'たてもの',
        meaning: ['Building'],
        sentence: '建物が高いです。',
        type: 'main',
      },
      {
        reading: '建てる',
        kana: 'たてる',
        meaning: ['To build'],
        sentence: '家を建てます。',
        type: 'main',
      },
      {
        reading: '建つ',
        kana: 'たつ',
        meaning: ['To be built'],
        sentence: '新しいビルが建ちます。',
        type: 'secondary',
      },
      {
        reading: '建国',
        kana: 'けんこく',
        meaning: ['Founding a nation'],
        sentence: '建国します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '地',
    onyomi: ['ち', 'じ'],
    kunyomi: [],
    meaning: ['Ground'],
    examples: [
      {
        reading: '地下',
        kana: 'ちか',
        meaning: ['Underground'],
        sentence: '地下鉄に乗ります。',
        type: 'main',
      },
      {
        reading: '地下鉄',
        kana: 'ちかてつ',
        meaning: ['Subway'],
        sentence: '地下鉄に乗ります。',
        type: 'main',
      },
      {
        reading: '地図',
        kana: 'ちず',
        meaning: ['Map'],
        sentence: '地図を見ます。',
        type: 'main',
      },
      {
        reading: '地震',
        kana: 'じしん',
        meaning: ['Earthquake'],
        sentence: '地震がありました。',
        type: 'main',
      },
      {
        reading: '地球',
        kana: 'ちきゅう',
        meaning: ['The Earth'],
        sentence: '地球は丸いです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '通',
    onyomi: ['つう'],
    kunyomi: ['とお', 'かよ'],
    meaning: ['To pass through', 'To commute'],
    examples: [
      {
        reading: '通る',
        kana: 'とおる',
        meaning: ['To go through', 'To pass'],
        sentence: '通りを通ります。',
        type: 'main',
      },
      {
        reading: '通う',
        kana: 'かよう',
        meaning: ['To commute'],
        sentence: '学校に通います。',
        type: 'main',
      },
      {
        reading: '通学',
        kana: 'つうがく',
        meaning: ['Commuting to school', 'To go to school'],
        sentence: '通学します。',
        type: 'main',
      },
      {
        reading: '通勤',
        kana: 'つうきん',
        meaning: ['Commuting to work', 'To go to work'],
        sentence: '通勤します。',
        type: 'main',
      },
    ],
  },
]