import { GrammarEntryCategory } from "../../../enums";

export const NIHONGO_NO_MORI_GRAMMAR_MONDAI_N2: any[] = [
  // SECTION 4: 順接・逆接 - GRAMMAR 29 - 40
  {
    id: 1,
    content: [
      '背が高い',
      '、ゴールキーパーに選ばれた。',
    ],
    moji: '',
    options: ['といえば', 'というより', 'というだけで', 'としたら'],
    answer: 'というだけで',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 2,
    content: [
      '今日は雨の日',
      '、たくさんお客さんが来ている。',
    ],
    moji: '',
    options: ['にあたって', 'とすると', 'のはずで', 'のわりに'],
    answer: 'のわりに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 3,
    content: [
      '雨',
      '、野球の試合は中止にならなかった。',
    ],
    moji: '',
    options: ['をとわず', 'というより', 'にもかかわらず', 'ということに'],
    answer: 'にもかかわらず',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 4,
    content: [
      'さすが元ダンス部',
      '、山田さんはダンスを覚えるのが早いね。',
    ],
    moji: '',
    options: ['だけあって', 'のみならず', 'というより', 'といえども'],
    answer: 'だけあって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 5,
    content: [
      '芸能人と同じ髪型にした',
      'その人みたいな顔になれるわけではない。',
    ],
    moji: '',
    options: ['にしては', 'のだったら', 'にもかかわらず', 'からといって'],
    answer: 'からといって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 6,
    content: [
      '彼は一年生',
      '落ち着いていて、しっかりしている。',
    ],
    moji: '',
    options: ['とするなら', 'からしか', 'どころか', 'にしては'],
    answer: 'にしては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 7,
    content: [
      '今日は暑い中仕事を頑張った',
      '家で飲むビールは特別においしかった。',
    ],
    moji: '',
    options: ['だけに', 'からって', 'のだったら', 'ものの'],
    answer: 'だけに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 8,
    content: [
      '彼は日本に行ったこと',
      'アニメを観て日本語がうまくなったそうだ。',
    ],
    moji: '',
    options: ['にしては', 'こそないが', 'からには', 'のみにして'],
    answer: 'こそないが',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 9,
    content: [
      'ジムに入会した',
      '、毎日通ってトレーニングをすると決めた。',
    ],
    moji: '',
    options: ['までは', 'からには', 'としては', 'といえば'],
    answer: 'からには',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 10,
    content: [
      '料理をした',
      '、卵を焼いただけの簡単な料理ですよ。',
    ],
    moji: '',
    options: ['だけあって', 'というだけで', 'といっても', 'のみならず'],
    answer: 'といっても',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 11,
    content: [
      '連休',
      '遠くに出かけることはできない。',
    ],
    moji: '',
    options: ['3日間', 'あまり', 'だけなので', 'といっても'],
    answer: '3日間',
    order: [4, 1, 3, 2],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 12,
    content: [
      '日本人だ',
      '実はそんなことはない。',
    ],
    moji: '',
    options: ['漢字を全部', 'からといって', '書ける', 'かというと'],
    answer: 'かというと',
    order: [2, 1, 3, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 13,
    content: [
      'やっぱり',
      '、ゆか先生は言葉の使い方がとてもきれいだ。',
    ],
    moji: '',
    options: ['あって', 'だけ', 'の先生', '日本語'],
    answer: 'だけ',
    order: [4, 3, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 14,
    content: [
      '好きな仕事を見つけて毎日',
      '自分に合う仕事が見つからず転職ばかりする人もいる。',
    ],
    moji: '',
    options: ['人がいる', '過ごす', '一方で', '楽しく'],
    answer: '過ごす',
    order: [4, 2, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 15,
    content: [
      '他の店に',
      '味はあまり良くない。',
    ],
    moji: '',
    options: ['わりに', '高い', 'かなり値段が', '比べて'],
    answer: '比べて',
    order: [4, 3, 2, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  // SECTION 5: 悪い意味 - GRAMMAR 41 - 48
  {
    id: 1,
    content: [
      '今日は忙しすぎて、昼ごはんを食べるために10分休むことすら',
      '。',
    ],
    moji: '',
    options: ['できるそうだ', 'できつつある', 'できそうもない', 'できるまでもない'],
    answer: 'できそうもない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 2,
    content: [
      '彼は',
      '、休日遊びに行っても声をかけられたり写真を撮られたりして大変だ。',
    ],
    moji: '',
    options: ['有名であるとともに', '有名であるようでは', '有名であるどころか', '有名であるばかりに'],
    answer: '有名であるばかりに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 3,
    content: [
      'お金がなくて貧乏だった私は、困った',
      'あやしい人からお金を借りてしまった。',
    ],
    moji: '',
    options: ['あげく', 'ようで', '一方', 'とおり'],
    answer: 'あげく',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 4,
    content: [
      '健康になりたいと思っていても、体に悪いものばかり',
      '病気になってしまう。',
    ],
    moji: '',
    options: ['食べたくせに', '食べていては', '食べたとして', '食べたことから'],
    answer: '食べていては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 5,
    content: [
      'アルファベットを覚えただけでは、英語の試験に',
      'よ。',
    ],
    moji: '',
    options: ['合格するっこない', '合格してっこない', '合格したっこない', 'xxx合格できっこないxx'],
    answer: '合格できっこない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 6,
    content: [
      '一度負けただけで泣いている',
      '、強い選手になることはできない。',
    ],
    moji: '',
    options: ['ようでは', 'ようには', 'ようものなら', 'ようで'],
    answer: 'ようでは',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 7,
    content: [
      'スーパーでさんざんチーズの味見を',
      '、結局何も買わなかった。',
    ],
    moji: '',
    options: ['するあげく', 'したあげく', 'しないあげく', 'すればあげく'],
    answer: 'したあげく',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 8,
    content: [
      'そんなに一生懸命練習したって、プロの野球選手に',
      '。',
    ],
    moji: '',
    options: ['なれるようではないよ', 'なれっこないよ', 'なれなくちゃいけないよ', 'なれたところではないよ'],
    answer: 'なれっこないよ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 9,
    content: [
      '彼はいつも遅刻する',
      '、友達が待ち合わせの時間に遅れたときはすごく怒る。',
    ],
    moji: '',
    options: ['まま', 'ばかりに', 'くせに', '以上'],
    answer: 'くせに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 10,
    content: [
      '恋人と別れて悲しそうな彼女を元気づけたら、',
      '落ち込んでしまった。',
    ],
    moji: '',
    options: ['一方で', '先立って', '比べて', 'かえって'],
    answer: 'かえって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 11,
    content: [
      '今朝、うっかり',
      'に怒られてしまった。',
    ],
    moji: '',
    options: ['遅刻して', '寝坊した', '先生', 'ばかりに'],
    answer: 'ばかりに',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 12,
    content: [
      'なんだか疲れていたの',
      '体調が悪化した。',
    ],
    moji: '',
    options: ['夜まで', '寝たら', '朝から', 'かえって'],
    answer: '朝から',
    order: [3, 1, 2, 4],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 13,
    content: [
      '一度試験に',
      'いつまでたっても合格できないよ。',
    ],
    moji: '',
    options: ['いては', 'あきらめて', 'といって', '落ちたから'],
    answer: 'いては',
    order: [4, 3, 2, 1],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 14,
    content: [
      'こんな',
      'にバカにされるのも当然だ。',
    ],
    moji: '',
    options: ['簡単な', 'ようじゃ', 'こともわからない', '子どもたち'],
    answer: '簡単な',
    order: [1, 3, 2, 4],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 15,
    content: [
      '彼は私が今まで',
      'ひどいことばかり言ってくる。',
    ],
    moji: '',
    options: ['くせに', '努力してきたか', 'どれだけ', '知らない'],
    answer: '努力してきたか',
    order: [3, 2, 4, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 16,
    content: [
      '文字コミュニケーションに、革命を起こした絵文字。文字のように文中に絵を',
      '「絵文字」という名前が付いた。メールを送る際に絵文字を使用することで、相手に自分の気持ちを正確に伝え、誤解を生みにくくするというメリットがある。あたりまえのように使われているこの絵文字が生まれたのが、日本だということをご存知だろうか。',
    ],
    moji: '',
    options: ['入れられることなく', '入れられることから', '入れられるものの', '入れられることなら'],
    answer: '入れられることから',
    type: '文法の文章',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 17,
    content: [
      '現在は無料で何文字でもメールを送信することができるが、昔はメールを一通送るたびに料金が発生し、送できる文字数も限られていた。このような制限はあったが、時間や場所を選ばずコミュニケーシンが取れる点が便利だと、多くの日本人が電話よりメールを好むようになった。',
      '、対面せずにコミュニケーションが取れるという点も、恥ずかしがり屋の日本人に好まれた理由の一つだろう。しかし、文字でのコミュニケーションはしばしば送り手と受け手の間に誤解を生じさせた。',
    ],
    moji: '',
    options: ['しかし', 'したがって', 'つまり', 'また'],
    answer: 'また',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 18,
    content: [
      '',
      'ために開発されたのが、絵文字であった。',
    ],
    moji: '',
    options: ['このような問題を解決する', '文字数を増やす', '料金を抑える', 'あんな人の'],
    answer: 'このような問題を解決する',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 19,
    content: [
      'その後インターネット技術が進化し、世界中の誰とでも簡単にメールを交換できるようになった。また、スマートフォンが普及したことにより、絵文字は日本だけでなく、全世界で',
      '。',
    ],
    moji: '',
    options: ['注目するためにある', '注目させられるそうだ', '注目させてくれた', '注目されるようになった'],
    answer: '注目されるようになった',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 20,
    content: [
      '言葉が通じない外国人とのコミュニケーションでも、正確に内容や気持ちが伝えられると、海外でも絵文字の効果が認められている。絵文字がなかったら、これほどまでインターネット上のコミュニケーションは',
      '。 日本人の思いやりが形になった一つの例である。',
    ],
    moji: '',
    options: ['発展したようだ', '発展していたのでしょう', '発展していなかっただろう', '発展さしているようだ'],
    answer: '発展していなかっただろう',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
];
