import { GrammarEntryCategory } from "../../../enums";

export const NIHONGO_NO_MORI_GRAMMAR_MONDAI_N2: any[] = [
  // SECTION 1: 「もの」シリーズ - GRAMMAR 1 - 10
  {
    id: 1,
    content: [
      '世間の目は厳しい。ただひたすら頑張れば、評価されるという',
      '。',
    ],
    options: ['ものと思われる', 'ものと思われない', 'ものではない', 'ものだ'],
    answer: 'ものではない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 2,
    content: [
      'どんなに親しくなったとしても、上司には常に敬語で',
      'ものだ。',
    ],
    options: ['話す', '話した', '話さない', '話そう'],
    answer: '話す',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 3,
    content: [
      '何事も最初は失敗する',
      'だから、うまくいかなくても諦めずに続けることが大切だ。',
    ],
    options: ['うえ', 'もの', 'あげく', 'ため'],
    answer: 'もの',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 4,
    content: [
      '事件現場の近くで、犯人が使用した',
      '自転車が発見された。',
    ],
    options: ['ものと思うと', 'ものと思いつつ', 'ものと思ったつもりの', 'ものと思われる'],
    answer: 'ものと思われる',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 5,
    content: [
      '誕生日パーティーを開いてもらうなんて少し恥ずかしいけど、みんなにお祝いしてもらうのは',
      '。',
    ],
    options: ['うれしいもんか', 'うれしいもんだ', 'うれしいものの', 'うれしいもんでもない'],
    answer: 'うれしいもんだ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 6,
    content: [
      '休める',
      '休みたいけど、今日は大事なテストがあるから絶対に学校へ行かなければならない。',
    ],
    options: ['ものの', 'ものか', 'ものでも', 'ものなら'],
    answer: 'ものなら',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 7,
    content: [
      '思い切って赤色のワンピースを買った',
      '、恥ずかしくて結局まだ一度も着ていない。',
    ],
    options: ['ものの', 'ものに', 'ものか', 'ものが'],
    answer: 'ものの',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 8,
    content: [
      'いくつになっても子どものことを一番に思う、それが親',
      '。',
    ],
    options: ['というものだ', 'ということだ', 'というものならだ', 'ということならだ'],
    answer: 'というものだ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 9,
    content: [
      '桜の花びらが散っている様子はとてもきれいだけど、どこか',
      'がありますね。',
    ],
    options: ['さびしいというもの', 'さびしいものとか', 'さびしいものの', 'さびしいもの'],
    answer: 'さびしいもの',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 10,
    content: [
      '一度不合格だったくらいで、合格を',
      '。',
    ],
    options: ['あきらめることにする', 'あきらめることか', 'あきらめるものか', 'あきらめるもの'],
    answer: 'あきらめるものか',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 11,
    content: [
      'こんな大きい家に',
      '。',
    ],
    options: ['みたい', '住んで', '住める', 'ものなら'],
    answer: 'ものなら',
    order: [3, 4, 2, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 12,
    content: [
      '揺れる車内で6時間も座りっぱなしで、全然眠れなかった。夜行バス',
      '。',
    ],
    options: ['なんて', '乗る', 'もんか', '二度と'],
    answer: 'なんて',
    order: [1, 4, 2, 3],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 13,
    content: [
      'できなくても落ち込まないでください。誰でもはじめた',
      '。',
    ],
    options: ['ものです', 'うまくいかない', 'ばかりの', 'ころは'],
    answer: 'うまくいかない',
    order: [3, 4, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 14,
    content: [
      '遊んでもいいが、ちゃんと勉強も',
      '。',
    ],
    options: ['大学生', 'するのが', 'という', 'ものだ'],
    answer: 'という',
    order: [2, 1, 3, 4],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.MONO,
  },
  {
    id: 15,
    content: [
      'ドーナツは油が多いと',
      '食べるのをやめられない。',
    ],
    options: ['大好き', 'わかっている', 'だから', 'ものの'],
    answer: 'ものの',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.MONO,
  },
  // SECTION 4: 順接・逆接 - GRAMMAR 29 - 40
  {
    id: 1,
    content: [
      '背が高い',
      '、ゴールキーパーに選ばれた。',
    ],
    moji: '',
    options: ['といえば', 'というより', 'というだけで', 'としたら'],
    answer: 'というだけで',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 2,
    content: [
      '今日は雨の日',
      '、たくさんお客さんが来ている。',
    ],
    moji: '',
    options: ['にあたって', 'とすると', 'のはずで', 'のわりに'],
    answer: 'のわりに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 3,
    content: [
      '雨',
      '、野球の試合は中止にならなかった。',
    ],
    moji: '',
    options: ['をとわず', 'というより', 'にもかかわらず', 'ということに'],
    answer: 'にもかかわらず',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 4,
    content: [
      'さすが元ダンス部',
      '、山田さんはダンスを覚えるのが早いね。',
    ],
    moji: '',
    options: ['だけあって', 'のみならず', 'というより', 'といえども'],
    answer: 'だけあって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 5,
    content: [
      '芸能人と同じ髪型にした',
      'その人みたいな顔になれるわけではない。',
    ],
    moji: '',
    options: ['にしては', 'のだったら', 'にもかかわらず', 'からといって'],
    answer: 'からといって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 6,
    content: [
      '彼は一年生',
      '落ち着いていて、しっかりしている。',
    ],
    moji: '',
    options: ['とするなら', 'からしか', 'どころか', 'にしては'],
    answer: 'にしては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 7,
    content: [
      '今日は暑い中仕事を頑張った',
      '家で飲むビールは特別においしかった。',
    ],
    moji: '',
    options: ['だけに', 'からって', 'のだったら', 'ものの'],
    answer: 'だけに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 8,
    content: [
      '彼は日本に行ったこと',
      'アニメを観て日本語がうまくなったそうだ。',
    ],
    moji: '',
    options: ['にしては', 'こそないが', 'からには', 'のみにして'],
    answer: 'こそないが',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 9,
    content: [
      'ジムに入会した',
      '、毎日通ってトレーニングをすると決めた。',
    ],
    moji: '',
    options: ['までは', 'からには', 'としては', 'といえば'],
    answer: 'からには',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 10,
    content: [
      '料理をした',
      '、卵を焼いただけの簡単な料理ですよ。',
    ],
    moji: '',
    options: ['だけあって', 'というだけで', 'といっても', 'のみならず'],
    answer: 'といっても',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 11,
    content: [
      '連休',
      '遠くに出かけることはできない。',
    ],
    moji: '',
    options: ['3日間', 'あまり', 'だけなので', 'といっても'],
    answer: '3日間',
    order: [4, 1, 3, 2],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 12,
    content: [
      '日本人だ',
      '実はそんなことはない。',
    ],
    moji: '',
    options: ['漢字を全部', 'からといって', '書ける', 'かというと'],
    answer: 'かというと',
    order: [2, 1, 3, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 13,
    content: [
      'やっぱり',
      '、ゆか先生は言葉の使い方がとてもきれいだ。',
    ],
    moji: '',
    options: ['あって', 'だけ', 'の先生', '日本語'],
    answer: 'だけ',
    order: [4, 3, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 14,
    content: [
      '好きな仕事を見つけて毎日',
      '自分に合う仕事が見つからず転職ばかりする人もいる。',
    ],
    moji: '',
    options: ['人がいる', '過ごす', '一方で', '楽しく'],
    answer: '過ごす',
    order: [4, 2, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 15,
    content: [
      '他の店に',
      '味はあまり良くない。',
    ],
    moji: '',
    options: ['わりに', '高い', 'かなり値段が', '比べて'],
    answer: '比べて',
    order: [4, 3, 2, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  // SECTION 5: 悪い意味 - GRAMMAR 41 - 48
  {
    id: 1,
    content: [
      '今日は忙しすぎて、昼ごはんを食べるために10分休むことすら',
      '。',
    ],
    moji: '',
    options: ['できるそうだ', 'できつつある', 'できそうもない', 'できるまでもない'],
    answer: 'できそうもない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 2,
    content: [
      '彼は',
      '、休日遊びに行っても声をかけられたり写真を撮られたりして大変だ。',
    ],
    moji: '',
    options: ['有名であるとともに', '有名であるようでは', '有名であるどころか', '有名であるばかりに'],
    answer: '有名であるばかりに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 3,
    content: [
      'お金がなくて貧乏だった私は、困った',
      'あやしい人からお金を借りてしまった。',
    ],
    moji: '',
    options: ['あげく', 'ようで', '一方', 'とおり'],
    answer: 'あげく',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 4,
    content: [
      '健康になりたいと思っていても、体に悪いものばかり',
      '病気になってしまう。',
    ],
    moji: '',
    options: ['食べたくせに', '食べていては', '食べたとして', '食べたことから'],
    answer: '食べていては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 5,
    content: [
      'アルファベットを覚えただけでは、英語の試験に',
      'よ。',
    ],
    moji: '',
    options: ['合格するっこない', '合格してっこない', '合格したっこない', 'xxx合格できっこないxx'],
    answer: '合格できっこない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 6,
    content: [
      '一度負けただけで泣いている',
      '、強い選手になることはできない。',
    ],
    moji: '',
    options: ['ようでは', 'ようには', 'ようものなら', 'ようで'],
    answer: 'ようでは',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 7,
    content: [
      'スーパーでさんざんチーズの味見を',
      '、結局何も買わなかった。',
    ],
    moji: '',
    options: ['するあげく', 'したあげく', 'しないあげく', 'すればあげく'],
    answer: 'したあげく',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 8,
    content: [
      'そんなに一生懸命練習したって、プロの野球選手に',
      '。',
    ],
    moji: '',
    options: ['なれるようではないよ', 'なれっこないよ', 'なれなくちゃいけないよ', 'なれたところではないよ'],
    answer: 'なれっこないよ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 9,
    content: [
      '彼はいつも遅刻する',
      '、友達が待ち合わせの時間に遅れたときはすごく怒る。',
    ],
    moji: '',
    options: ['まま', 'ばかりに', 'くせに', '以上'],
    answer: 'くせに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 10,
    content: [
      '恋人と別れて悲しそうな彼女を元気づけたら、',
      '落ち込んでしまった。',
    ],
    moji: '',
    options: ['一方で', '先立って', '比べて', 'かえって'],
    answer: 'かえって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 11,
    content: [
      '今朝、うっかり',
      'に怒られてしまった。',
    ],
    moji: '',
    options: ['遅刻して', '寝坊した', '先生', 'ばかりに'],
    answer: 'ばかりに',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 12,
    content: [
      'なんだか疲れていたの',
      '体調が悪化した。',
    ],
    moji: '',
    options: ['夜まで', '寝たら', '朝から', 'かえって'],
    answer: '朝から',
    order: [3, 1, 2, 4],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 13,
    content: [
      '一度試験に',
      'いつまでたっても合格できないよ。',
    ],
    moji: '',
    options: ['いては', 'あきらめて', 'といって', '落ちたから'],
    answer: 'いては',
    order: [4, 3, 2, 1],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 14,
    content: [
      'こんな',
      'にバカにされるのも当然だ。',
    ],
    moji: '',
    options: ['簡単な', 'ようじゃ', 'こともわからない', '子どもたち'],
    answer: '簡単な',
    order: [1, 3, 2, 4],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 15,
    content: [
      '彼は私が今まで',
      'ひどいことばかり言ってくる。',
    ],
    moji: '',
    options: ['くせに', '努力してきたか', 'どれだけ', '知らない'],
    answer: '努力してきたか',
    order: [3, 2, 4, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 16,
    content: [
      '文字コミュニケーションに、革命を起こした絵文字。文字のように文中に絵を',
      '「絵文字」という名前が付いた。メールを送る際に絵文字を使用することで、相手に自分の気持ちを正確に伝え、誤解を生みにくくするというメリットがある。あたりまえのように使われているこの絵文字が生まれたのが、日本だということをご存知だろうか。',
    ],
    moji: '',
    options: ['入れられることなく', '入れられることから', '入れられるものの', '入れられることなら'],
    answer: '入れられることから',
    type: '文法の文章',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 17,
    content: [
      '現在は無料で何文字でもメールを送信することができるが、昔はメールを一通送るたびに料金が発生し、送できる文字数も限られていた。このような制限はあったが、時間や場所を選ばずコミュニケーシンが取れる点が便利だと、多くの日本人が電話よりメールを好むようになった。',
      '、対面せずにコミュニケーションが取れるという点も、恥ずかしがり屋の日本人に好まれた理由の一つだろう。しかし、文字でのコミュニケーションはしばしば送り手と受け手の間に誤解を生じさせた。',
    ],
    moji: '',
    options: ['しかし', 'したがって', 'つまり', 'また'],
    answer: 'また',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 18,
    content: [
      '',
      'ために開発されたのが、絵文字であった。',
    ],
    moji: '',
    options: ['このような問題を解決する', '文字数を増やす', '料金を抑える', 'あんな人の'],
    answer: 'このような問題を解決する',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 19,
    content: [
      'その後インターネット技術が進化し、世界中の誰とでも簡単にメールを交換できるようになった。また、スマートフォンが普及したことにより、絵文字は日本だけでなく、全世界で',
      '。',
    ],
    moji: '',
    options: ['注目するためにある', '注目させられるそうだ', '注目させてくれた', '注目されるようになった'],
    answer: '注目されるようになった',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 20,
    content: [
      '言葉が通じない外国人とのコミュニケーションでも、正確に内容や気持ちが伝えられると、海外でも絵文字の効果が認められている。絵文字がなかったら、これほどまでインターネット上のコミュニケーションは',
      '。 日本人の思いやりが形になった一つの例である。',
    ],
    moji: '',
    options: ['発展したようだ', '発展していたのでしょう', '発展していなかっただろう', '発展さしているようだ'],
    answer: '発展していなかっただろう',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  // SECTION 6: 強調 - GRAMMAR 49 - 58
  {
    id: 1,
    content: [
      '遊園地のような人の多いところへは',
      'と思っていたが、彼女ができてからよく行くようになった。',
    ],
    moji: '',
    options: ['行かまい', '行きまい', '行くまい', '行こまい'],
    answer: '行くまい',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 2,
    content: [
      '集中して勉強したいのに、隣でずっと話をされて',
      '。',
    ],
    moji: '',
    options: ['迷惑なわけがない', '迷惑のなんのない', '迷惑しようがない', '迷惑でならない'],
    answer: '迷惑でならない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 3,
    content: [
      '最近ようやく言葉を話すようになった息子が、',
      '。',
    ],
    moji: '',
    options: ['かわいいたまらない', 'かわいくてたまらない', 'かわいくたまらない', 'かわいいでたまらない'],
    answer: 'かわいくてたまらない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 4,
    content: [
      '私と兄は一歳しか年齢が離れていないので、兄弟',
      '親友のような関係だ。',
    ],
    moji: '',
    options: ['というより', 'にほかならず', 'にとって', 'によって'],
    answer: 'というより',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 5,
    content: [
      'ここのラーメンは他の店にはない特別なおいしさがあるので、二時間',
      '食べる価値がある。',
    ],
    moji: '',
    options: ['待ってから', '待ってでも', '待っていて', '待って以来'],
    answer: '待ってでも',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 6,
    content: [
      '息子が試験に合格したと聞いて、うれしさの',
      '大声でさけんでしまった。',
    ],
    moji: '',
    options: ['くせに', 'つもりで', 'なんのって', 'あまり'],
    answer: 'あまり',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 7,
    content: [
      '一人暮らしを始めてさびしい',
      '、毎日一人で泣いてばかりいる。',
    ],
    moji: '',
    options: ['ものの', 'というより', 'のなんのって', 'によって'],
    answer: 'のなんのって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 8,
    content: [
      '父は「今度',
      '当てる！」と言いながら、走って宝くじを買いに行った。',
    ],
    moji: '',
    options: ['ほど', 'には', 'おきに', 'こそ'],
    answer: 'こそ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 9,
    content: [
      '作品が認められて金賞をとることができたのは、彼自身の努力の結果',
      '。',
    ],
    moji: '',
    options: ['でならない', 'というものがある', 'にほかならない', 'にかかわらずだ'],
    answer: 'にほかならない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 10,
    content: [
      'あんなに一生懸命勉強しているんだから、彼は合格する',
      '。',
    ],
    moji: '',
    options: ['に決まっている', 'にほかならない', 'に先立っている', 'に対している'],
    answer: 'に決まっている',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 11,
    content: [
      '毎週月曜日に放送されるドラマの',
      '。',
    ],
    moji: '',
    options: ['観たくて', '早く', 'たまらない', '続きを'],
    answer: '早く',
    order: [4, 2, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 12,
    content: [
      '途中まで勝っていたのに、最後に逆転されて負けて',
      '。',
    ],
    moji: '',
    options: ['悔しくて', 'しまった', 'ならない', 'ことが'],
    answer: 'ことが',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 13,
    content: [
      '今年は準優勝だったが、',
      '心に決めた。',
    ],
    moji: '',
    options: ['と', 'こそ', '優勝するぞ', '来年'],
    answer: '優勝するぞ',
    order: [4, 2, 3, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 14,
    content: [
      '突然',
      '持っていたアイスクリームを床に落としてしまった。',
    ],
    moji: '',
    options: ['驚きの', '雷が', 'あまり', '鳴って'],
    answer: '鳴って',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 15,
    content: [
      'こんなに短期間で、完ぺきに歌と踊りを覚えられるのは',
      '。',
    ],
    moji: '',
    options: ['ほか', '才能に', 'ならない', '彼女たちの'],
    answer: 'ほか',
    order: [4, 2, 1, 3],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  // SECTION 7: 時間 - GRAMMAR 59 - 67
  {
    id: 1,
    content: [
      '彼女は',
      '私のまねばかりしてくるので、嫌な気分になる。',
    ],
    moji: '',
    options: ['何の通りに', '何に対して', '何かにつけて', '何はともあれ'],
    answer: '何かにつけて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 2,
    content: [
      '勉強している',
      '、妹が私の部屋に何度も来るので集中できない。',
    ],
    moji: '',
    options: ['上で', '次第', '一方', '最中'],
    answer: '最中',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 3,
    content: [
      '外で大きな音',
      '、「助けて」という子どもの声が聞こえた。',
    ],
    moji: '',
    options: ['したかと思うと', 'したと思って', 'したと思わず', 'したかと思うに'],
    answer: 'したかと思うと',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 4,
    content: [
      '勉強する',
      '最も大切なことは、目標を立てて毎日少しずつ取り組むことだ。',
    ],
    moji: '',
    options: ['上が', '上に', '上で', '上は'],
    answer: '上で',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 5,
    content: [
      '賞味期限が切れているおにぎり',
      '、お腹が痛くなり始めた。',
    ],
    moji: '',
    options: ['食べたはずで', '食べたついでに', '食べたとたん', '食べた次第に'],
    answer: '食べたとたん',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 6,
    content: [
      'インフルエンザでしばらく学校を休んでいたので、一週間',
      'に友達に会えた。',
    ],
    moji: '',
    options: ['たち', 'きり', 'うえ', 'ぶり'],
    answer: 'ぶり',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 7,
    content: [
      '日曜日は美容院へ行く',
      '、マッサージを受けてエステにも行く予定だ。',
    ],
    moji: '',
    options: ['とたんに', 'ついでに', '最中に', '以上に'],
    answer: 'ついでに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 8,
    content: [
      '映画が終わる',
      '終わらない',
      'のうちに、お客さんはみんな立ち上がって帰り始めた。',
    ],
    moji: '',
    options: ['の/の', 'に/に', 'と/と', 'か/か'],
    answer: 'か/か',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 9,
    content: [
      '大学合格の知らせを',
      '、母は大喜びして泣き始めた。',
    ],
    moji: '',
    options: ['聞きとたん', '聞くとたん', '聞いてとたん', '聞いたとたん'],
    answer: '聞いたとたん',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 10,
    content: [
      '勉強',
      '、英語の曲をたくさん聞くようにしている。',
    ],
    moji: '',
    options: ['にとって', 'をかねて', 'のあまり', 'にしても'],
    answer: 'をかねて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 11,
    content: [
      '桜は',
      'かと考えているうちに桜の季節が終わってしまった。',
    ],
    moji: '',
    options: ['散ってしまうので', 'かと思うと', '咲いた', 'いつ見に行こう'],
    answer: 'いつ見に行こう',
    order: [3, 2, 1, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 12,
    content: [
      '',
      'ので、今朝は早起きしないですんだ。',
    ],
    moji: '',
    options: ['ついでに', '作っておいた', 'お弁当のおかずも', '夕食を作る'],
    answer: '夕食を作る',
    order: [4, 1, 3, 2],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 13,
    content: [
      '日本に留学して3年経つが、国にいる家族のことを',
      'と思う。',
    ],
    moji: '',
    options: ['つらいことがあっても', '考える', 'につけ', '頑張ろう'],
    answer: 'につけ',
    order: [2, 3, 1, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 14,
    content: [
      '彼と',
      '誰かすぐには思い出せなかった。',
    ],
    moji: '',
    options: ['見た目が', '会うのは', '変わっていて', '10年ぶりなので'],
    answer: '見た目が',
    order: [2, 4, 1, 3],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 15,
    content: [
      'シャワーを浴びている',
      'あわてて出た。',
    ],
    moji: '',
    options: ['体もふかずに', '最中に', '上司から', '電話がかかってきて'],
    answer: '最中に',
    order: [2, 3, 4, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  // SECTION 8: 基準・関連 - GRAMMAR 68 - 77
  {
    id: 1,
    content: [
      'グローバル化する現代',
      '最も必要とされる能力は、コミュニケーション能力である。',
    ],
    moji: '',
    options: ['にはって', 'によって', 'にのって', 'において'],
    answer: 'において',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 2,
    content: [
      '',
      '、すしや天ぷらを思い出す人が多いと思います。',
    ],
    moji: '',
    options: ['日本食というと', '日本食をめぐって', '日本食にかけては', '日本食とは'],
    answer: '日本食というと',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 3,
    content: [
      '夏になると、気温の上昇',
      '熱中症になる人の数が増加する。',
    ],
    moji: '',
    options: ['に備えて', 'に基づいて', 'に伴って', ' に沿って'],
    answer: 'に伴って',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 4,
    content: [
      '健康のために毎朝のウォーキング',
      '、仕事終わりにジムへ通って筋トレをしている。',
    ],
    moji: '',
    options: ['に沿って', 'に加えて', 'において', 'にかけて'],
    answer: 'に加えて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 5,
    content: [
      '大通り',
      '、同じ色の家がたくさん並んでいる。',
    ],
    moji: '',
    options: ['において', 'によって', 'に反して', 'に沿って'],
    answer: 'に沿って',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 6,
    content: [
      '優勝候補のチームが次々と負け、大会は予想',
      '結果となった。',
    ],
    moji: '',
    options: ['に対した', 'に応じる', 'に基づく', 'に反する'],
    answer: 'に反する',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 7,
    content: [
      'この会社では、能力と仕事の結果',
      '社員の給料を決定しています。',
    ],
    moji: '',
    options: ['に加えて', 'に反して', 'に応じて', 'に比べて'],
    answer: 'に応じて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 8,
    content: [
      'ナポリタン',
      '、ケチャップを使った日本風のスパゲティのことである。',
    ],
    moji: '',
    options: ['とは', 'では', 'さえ', 'ただ'],
    answer: 'とは',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 9,
    content: [
      '一人の',
      '、二人の男性が激しく言い争いをしている。',
    ],
    moji: '',
    options: ['女性にあたって', '女性に基づいて', '女性に沿って', '女性をめぐって'],
    answer: '女性をめぐって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 10,
    content: [
      '料理の味とお客様へのサービス',
      '、この店が日本で一番だ。',
    ],
    moji: '',
    options: ['にとっては', 'にかけては', 'をめぐっては', 'をかねては'],
    answer: 'にかけては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 11,
    content: [
      'うちの本屋は古い本から新しい本まで取りそろえているので、',
      'に負けることはないだろう。',
    ],
    moji: '',
    options: ['他の店', '豊富さ', '本の種類の', 'にかけては'],
    answer: 'にかけては',
    order: [3, 2, 4, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 12,
    content: [
      '',
      '、そこには食品や日用品がたくさん売っている。',
    ],
    moji: '',
    options: ['言葉で', '短くした', 'スーパーとは', 'スーパーマーケットを'],
    answer: 'スーパーとは',
    order: [3, 4, 2, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 13,
    content: [
      '現在の日本社会では、高齢化',
      'が問題になっている。',
    ],
    moji: '',
    options: ['若くて力のある', 'に伴う', '働き手', 'の不足'],
    answer: 'の不足',
    order: [2, 1, 3, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 14,
    content: [
      '今年こそは',
      'は初戦で負けてしまった。',
    ],
    moji: '',
    options: ['国民の期待', '優勝するだろうという', '日本チーム', 'に反して'],
    answer: '国民の期待',
    order: [2, 1, 4, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 15,
    content: [
      '先日、祖父が急に亡くなった。明日、祖父の遺産の相続',
      '話し合うことになっている。',
    ],
    moji: '',
    options: ['皆で集まって', 'をめぐる', 'について', '問題'],
    answer: 'をめぐる',
    order: [2, 4, 3, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  // SECTION 9: 仮定・条件 - GRAMMAR 78 - 86
  {
    id: 1,
    content: [
      'この店のおすすめは、店長の気分',
      '変わる。',
    ],
    options: ['次第に', '次第で', '次第', '次第と'],
    answer: '次第で',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 2,
    content: [
      'いくら周りの人が不可能だと',
      '、僕はこの実験を成功させる。',
    ],
    options: ['言うから', '言ってまで', '言おうとも', '言うにしては'],
    answer: '言おうとも',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 3,
    content: [
      'A: 「日曜日みんなで山に登るんだけど、山田さんも行く？」\nB:「行きたいんだけど、日曜日は大事な試験があるんだ。私',
      '行ってきて。」',
    ],
    options: ['抜きで', 'よそに', 'ことなしに', '加えて'],
    answer: '抜きで',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 4,
    content: [
      'うちの親は厳しくて、友達と遊びに行く',
      '親の許可が必要だった。',
    ],
    options: ['にとっても', 'にしても', 'にしては', 'としては'],
    answer: 'にしても',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 5,
    content: [
      '本人の家族',
      '、代わりに手続きをすることはできません。',
    ],
    options: ['にしては', 'であるとき', 'にとっても', 'でなければ'],
    answer: 'でなければ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 6,
    content: [
      'クラスの中で同じ大学に進学したのは、私',
      '二人いた。',
    ],
    options: ['に備えて', 'を通して', 'を除いて', 'に応じて'],
    answer: 'を除いて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 7,
    content: [
      '場所',
      '良ければ、この家に引っ越そうと思っていました。',
    ],
    options: ['しか', 'さえ', 'ほど', 'まで'],
    answer: 'さえ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 8,
    content: [
      'マスクをした',
      '、手洗いうがいをしないとインフルエンザの予防にはならない。',
    ],
    options: ['からだけ', 'といえば', 'からしか', 'としても'],
    answer: 'としても',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 9,
    content: [
      '今回のテストの点数',
      '、進学できる大学が決まる。',
    ],
    options: ['次第で', '一方で', '以上で', '限りで'],
    answer: '次第で',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 10,
    content: [
      '社会人になってからはなかなか旅行に行けなくなったので、学生のうちにもっと旅行に',
      'よかったと思う。',
    ],
    options: ['行けば', '行くとしたら', '行くだけ', '行くとすると'],
    answer: '行けば',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 11,
    content: [
      'できるだけ早くみなさんと仲良くなりたいので、',
      '自己紹介から始めましょう。',
    ],
    options: ['抜き', '難しい', 'にして', '話は'],
    answer: '難しい',
    order: [2, 4, 1, 3],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 12,
    content: [
      '愛',
      '幸せだと言う人がいるけれど、私はそうは思わない。',
    ],
    options: ['さえ', 'お金が', 'あれば', 'なくても'],
    answer: 'お金が',
    order: [1, 3, 2, 4],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 13,
    content: [
      '',
      '、勉強をしなければ日本語が話せるようにはならない。',
    ],
    options: ['行った', 'たとえ', '日本へ', 'としても'],
    answer: '行った',
    order: [2, 3, 1, 4],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 14,
    content: [
      '',
      'は関係ない。私は必ず夢をかなえて見せる。',
    ],
    options: ['言おうとも', '誰が何と', 'そんなこと', 'たとえ'],
    answer: 'そんなこと',
    order: [4, 2, 1, 3],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  {
    id: 15,
    content: [
      'こんなに大変な作業、',
      'で終わらせることはできなかっただろう。',
    ],
    options: ['なければ', '彼', 'で', '一日'],
    answer: 'で',
    order: [2, 3, 1, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.ASSUMPTIONS_CONDITIONS,
  },
  // SECTION 10: 状況・伝聞 - GRAMMAR 87 - 97
  {
    id: 1,
    content: [
      '熱を出している娘のために、早く元気になりますようにという願い',
      '、おかゆを作った。',
    ],
    options: ['を除いて', 'に応じて', 'を込めて', 'を伴って'],
    answer: 'を込めて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 2,
    content: [
      '駅前の新しいパン屋さん、大人気で午前中には売り切れてしまうんだ',
      '。',
    ],
    options: ['のに', 'など', 'こと', 'とか'],
    answer: 'とか',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 3,
    content: [
      '大雨で家の中まで雨が入ってきて、ゆっくりご飯を食べる',
      'ではない。',
    ],
    options: ['ばかり', 'どころ', 'まで', 'しだい'],
    answer: 'どころ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 4,
    content: [
      '監督の厳しい指導',
      '、見事優勝することができました。',
    ],
    options: ['のところ', 'のつもり', 'のももっとも', 'のもと'],
    answer: 'のもと',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 5,
    content: [
      '何か悩み事でもあるのか、彼は一日中下を',
      '。',
    ],
    options: ['向いてばかりいる', '向いたところだ', '向くどころではない', '向くおそれがある'],
    answer: '向いてばかりいる',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 6,
    content: [
      'ここに、実際の赤ちゃんと同じ重さの人形があります。お母さんになった',
      '、抱っこしてみてください。',
    ],
    options: ['みたいで', 'つもりで', 'ようで', 'しだいで'],
    answer: 'つもりで',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 7,
    content: [
      '大雨により、水が',
      'おそれがありますので、川には近づかないようにしてください。',
    ],
    options: ['あふれて', 'あふれよう', 'あふれる', 'あふれない'],
    answer: 'あふれる',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 8,
    content: [
      '健康診断を受けていたので、がんが早いうちに見つかり、手術',
      '。',
    ],
    options: ['せずにすんだ', 'どころではなかった', 'のつもりだった', 'してばかりいる'],
    answer: 'せずにすんだ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 9,
    content: [
      '山田くんは水泳が得意で、まるで泳いでいる魚',
      '美しく泳ぐ。',
    ],
    options: ['ようになっても', 'かと思うと', 'だからと言って', 'かのように'],
    answer: 'かのように',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 10,
    content: [
      '毎日上司の文句を聞きながら仕事をするなんて、辞めたくなるのも',
      '。',
    ],
    options: ['もっともだ', '一方だ', '次第だ', 'ばかりだ'],
    answer: 'もっともだ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 11,
    content: [
      'お昼ご飯を食べていたら急に大きな',
      'ではなくなってしまった。',
    ],
    options: ['休憩', '地震', 'が起きて', 'どころ'],
    answer: 'が起きて',
    order: [2, 3, 1, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 12,
    content: [
      '母は歳をとってから何度も同じ話をするようになったが、息子はいつも',
      'その話を楽しそうに聞く。',
    ],
    options: ['かの', '初めて', '聞いた', 'ように'],
    answer: 'かの',
    order: [2, 3, 1, 4],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 13,
    content: [
      '会社を立ち上げてしばらくはお金がなかったので、実家の',
      '使っていた。',
    ],
    options: ['事務所', '部屋', 'として', 'を'],
    answer: '部屋',
    order: [2, 4, 1, 3],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 14,
    content: [
      '間違った使い方を',
      'ので、使う前に説明書を読んでください。',
    ],
    options: ['爆発', 'するおそれ', 'すると', 'があります'],
    answer: 'があります',
    order: [3, 1, 2, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 15,
    content: [
      '日本人に',
      'と、いつもより少しうまく話せるような気がする。',
    ],
    options: ['話す', '日本語を', 'つもりで', 'なった'],
    answer: 'つもりで',
    order: [4, 3, 2, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 16,
    content: [
      '道路が凍ってしまう北海道では、安全に暮らす上で様々な工夫がされています。その一つに、「ロードヒーティング」というものがあります。\n北海道より暖かい東北地方では、地下水を路の上に少しだけ流すと雪がとけますが、東北地方より気温が低い北海道では、地下水を',
      '道が凍って危険です。',
    ],
    options: ['流してしまうあげく', '流してしまうばかりに', '流してしまいさえすれば', '流してしまったらかえって'],
    answer: '流してしまったらかえって',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 17,
    content: [
      'そのため北海道では、道路の下に電熱線や温水を循環させるパイプを埋めて、道路を加熱します。これにより、雪が降ってもすぐにとけて雪のない路面状態を保つことができます。かつて冬の間は、「スパイクタイヤ」という、地面に触れる面に小さな金属を打ち込んだタイヤを使用するのが主流でした。',
      'により、雪道や凍ったつるつるの路でも、すべらず安定した走行ができたのです。',
    ],
    options: ['タイヤ', 'このタイヤ', 'どのタイヤ', 'あのタイヤ'],
    answer: 'このタイヤ',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 18,
    content: [
      'しかし、これは雪や氷の上',
      '、暖かくなってくる春先、雪がとけ、アスファルトの道路の上を走ると、付いている金属が路面をけずってしまい、ほこりが舞って環境問題を引き起こすという欠点がありました。そこで「スパイクタイヤ」の使用は規制され、それに代わって金属が付いていないタイヤが使用されるようになりました。ですが、やはりそのタイヤでは十分に安全が確保されなかったため、「ロードヒーティング」が広まったというわけです。',
    ],
    options: ['こそ能力を発揮しますが', 'だと能力が発揮されなく', 'でも能力を発揮するだけに', ' なのに能力が発揮されて'],
    answer: 'こそ能力を発揮しますが',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 19,
    content: [
      '',
      'この設備は、急な坂やカーブなど、車がすべって事故が発生する可能性が高い場所に整備されました。近年では車道だけなく、人がすべって転ばないようにコンビニの前や自宅の玄関先にも整備されるようになってきています。',
    ],
    options: ['けれども', 'こうして', 'さらに', 'そこで'],
    answer: 'こうして',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 20,
    content: [
      'また、高齢の方が暮らしている家では、この設備のおかげで、お年寄りが雪を取り除くという',
      '、負担が軽減されているのです。',
    ],
    options: ['重労働をしてでも', '重労働をかねて', '重労働をせずにすみ', '重労働をするどころではなく'],
    answer: '重労働をせずにすみ',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  // SECTION 11: 変化・結果 - GRAMMAR 98 - 105
  {
    id: 1,
    content: [
      '赤色のワンピースを買うか、青色のシャツを買うか一時間も',
      '、どちらも買わなかった。',
    ],
    options: ['悩んだもと', '悩んだすえ', '悩んだより', '悩んだごと'],
    answer: '悩んだすえ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 2,
    content: [
      '20分待った',
      '、焼きたてのピザと揚げたてのポテトを手に入れることができた。',
    ],
    options: ['ばかりに', 'ところを見ると', 'かいがあって', 'あげくに'],
    answer: 'かいがあって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 3,
    content: [
      'お客様のお支払い状況を',
      '、まだ支払いが完了していないようでした。',
    ],
    options: ['確認しながら', '確認した以上', '確認したとあっては', '確認したところ'],
    answer: '確認したところ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 4,
    content: [
      '初めて訪れた街で道に',
      '、帰れなくなって泣きながら母に電話をした。',
    ],
    options: ['迷う末', '迷った未', '迷って末', '迷い未'],
    answer: '迷った未',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 5,
    content: [
      '本当に大切なものというのは、',
      'わかるものだ。',
    ],
    options: ['失ったどころか', '失ってかいがあって', '失ってばかりに', '失ってはじめて'],
    answer: '失ってはじめて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 6,
    content: [
      'あんなに日本に帰りたいと言っていたけれど、帰国日が近づく',
      'みんなと別れるのが嫌で悲しくなってきた。',
    ],
    options: ['につれて', 'にとって', 'にあって', 'にかけて'],
    answer: 'につれて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 7,
    content: [
      '漢字の書き順が間違っていると言われたので、',
      '私は間違っていなかった。',
    ],
    options: ['調べてところ', '調べるところ', '調べたところ', '調べようところ'],
    answer: '調べたところ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 8,
    content: [
      '転職',
      '、住む場所も関わる人も全部変えることにした。',
    ],
    options: ['を最後に', 'を契機に', 'を次第に', 'を以来に'],
    answer: 'を契機に',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 9,
    content: [
      '息子は恋人ができてから遊んでばかりで、成績が',
      '。',
    ],
    options: ['悪くなる一方だ', '悪くなる最中だ', '悪くなる反面だ', '悪くなる未だ'],
    answer: '悪くなる一方だ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 10,
    content: [
      '日本語教師という仕事',
      '、世界中の日本語学習者とつながることができた。',
    ],
    options: ['を問わず', 'を通して', 'のあげく', 'の限り'],
    answer: 'を通して',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 11,
    content: [
      '生まれたばかりのときは私に似ていると思ったが、息子は',
      '夫に似た顔になってきた。',
    ],
    options: ['はっきりしている', '目や鼻が', '成長する', 'につれて'],
    answer: '目や鼻が',
    order: [3, 4, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 12,
    content: [
      '近くに大きなショッピングモールができて',
      'だ。',
    ],
    options: ['一方', 'から', '店の売上は減る', 'うちのような小さな'],
    answer: 'から',
    order: [2, 4, 3, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 13,
    content: [
      '小学生のころの友達がアナウンサーとして',
      '。',
    ],
    options: ['を通じて', 'ニュース番組', '知った', '活躍していることを'],
    answer: '活躍していることを',
    order: [4, 2, 1, 3],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 14,
    content: [
      '',
      'くれたのかを知った。',
    ],
    options: ['子どもを産んで', '母親がどんな苦労をして', '自分を産んで', 'はじめて'],
    answer: '自分を産んで',
    order: [1, 4, 2, 3],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  {
    id: 15,
    content: [
      '父親が',
      'を改めるようになった。',
    ],
    options: ['だらしない自分の', '病気で倒れたこと', 'を契機に', '生活習慣'],
    answer: 'を契機に',
    order: [2, 3, 1, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.CHANGE_RESULT,
  },
  // SECTION 12: 強制・関係ない・推測 - GRAMMAR 106 - 114
  {
    id: 1,
    content: [
      '台風のため飛行機が欠航になってしまったので、旅行を中止に',
      '。',
    ],
    options: ['せざるを得なかった', 'するわけにはいかない', 'してはいられない', 'するどころではない'],
    answer: 'せざるを得なかった',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 2,
    content: [
      '母が作った料理は、見た目',
      '味はおいしい。',
    ],
    options: ['といえば', 'どころか', 'はともかく', 'もかまわず'],
    answer: 'はともかく',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 3,
    content: [
      '日曜日だけど、こんな時間まで',
      '。起きて勉強しなくちゃ。',
    ],
    options: ['寝るのもかまわない', '寝てはいられない', '寝ざるを得ない', '寝るにほかならない'],
    answer: '寝てはいられない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 4,
    content: [
      '簡単な作業なので、年齢',
      '誰でもこの仕事をすることができます。',
    ],
    options: ['をはじめ', 'もかまわず', 'のみならず', 'を問わず'],
    answer: 'を問わず',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 5,
    content: [
      '大事な会議に遅刻する',
      'ので、タクシーに乗った。',
    ],
    options: ['わけではない', 'わけにはいかない', 'のもかまわない', 'かいがある'],
    answer: 'わけにはいかない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 6,
    content: [
      '今年はすごく暑いとみんなは言っているが、南の島に住んでいた私',
      '、この暑さは涼しいくらいだ。',
    ],
    options: ['からこそ', 'からには', 'からといって', 'からすると'],
    answer: 'からすると',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 7,
    content: [
      '服がぬれる',
      '、男性は川に飛び込み子どもを助けた。',
    ],
    options: ['を問わず', 'のもかまわず', 'はともかく', 'をはじめ'],
    answer: 'のもかまわず',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 8,
    content: [
      '終電を逃してしまったので、歩いて',
      'ざるを得ない。',
    ],
    options: ['帰り', '帰る', '帰ら', '帰れ'],
    answer: '帰ら',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 9,
    content: [
      '道路が濡れている',
      '、さっきまで雨が降っていたのだろう。',
    ],
    options: ['ことなしに', 'のもかまわず', 'かいがあって', 'ところをみると'],
    answer: 'ところをみると',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 10,
    content: [
      '経験の有無',
      '、やる気のある方を募集しています。',
    ],
    options: ['にちがいなく', 'にかかわらず', 'のみならず', 'にほかならなく'],
    answer: 'にかかわらず',
    type: '文法形式の判断',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 11,
    content: [
      '学生:「先生、電車が遅れたせいで遅刻をしました。」\n先生:「',
      'です。次からは気をつけてください。」',
    ],
    options: ['遅刻', '理由', '遅刻は', 'はともかく'],
    answer: 'はともかく',
    order: [2, 4, 3, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 12,
    content: [
      '彼のことはあまり好きではないけど、これだけチームのために努力',
      '。',
    ],
    options: ['を得ない', '感謝せざる', 'んだから', 'してくれた'],
    answer: '感謝せざる',
    order: [4, 3, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 13,
    content: [
      'このアーティストの曲は、',
      'からも好かれるような歌詞とメロディーだ。',
    ],
    options: ['人', 'どんな', 'を問わず', '年齢'],
    answer: 'を問わず',
    order: [4, 3, 2, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 14,
    content: [
      'これだけお金をかけた実験なんだから、何が',
      '。',
    ],
    options: ['失敗する', 'わけ', 'あっても', 'にはいかない'],
    answer: '失敗する',
    order: [3, 1, 2, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  {
    id: 15,
    content: [
      '彼には一時間以上前に連絡をしたが、',
      'のだろう。',
    ],
    options: ['返事しない', 'まだ残業している', 'ところを', 'みると'],
    answer: 'まだ残業している',
    order: [1, 3, 4, 2],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.MANDATORY_IRRELEVANCE_INFERENCE,
  },
  // SECTION 13: 列挙 - GRAMMAR 115 - 121
  {
    id: 1,
    content: [
      '日本の学校では、野球部やサッカー部',
      '、いろんなスポーツのチームがあります。',
    ],
    options: ['とすると', 'といえば', 'といった', 'としても'],
    answer: 'といった',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 2,
    content: [
      '夏は花火大会',
      '、夏祭りやビアガーデンなど、楽しいイベントがたくさんある。',
    ],
    options: ['のはじまり', 'にはじめ', 'をはじまり', 'をはじめ'],
    answer: 'をはじめ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 3,
    content: [
      '抹茶は、日本',
      '、世界でも健康に良い食材として注目されている。',
    ],
    options: ['にしては', 'のみならず', 'を問わず', 'に対して'],
    answer: 'のみならず',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 4,
    content: [
      '旅行のために、服',
      'ぼうし',
      "週末に買いに行こうと思っている。",
    ],
    options: ['やら/やら', 'にしろ/にしろ', 'にせよ/にせよ', 'や/やいなや'],
    answer: 'やら/やら',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 5,
    content: [
      '夕食を食べる',
      '食べない',
      "、何時に帰ってくるか連絡してね。",
    ],
    options: ['し/し', 'にしろ／にしろ', 'なり/なり', 'にすら/にすら'],
    answer: 'にしろ／にしろ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 6,
    content: [
      '寒くなると、鍋やおでん',
      '温かい食べ物が食べたくなる。',
    ],
    options: ['といえば', 'というと', 'としても', 'といった'],
    answer: 'といった',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 7,
    content: [
      '聴解ができる人',
      '、会話がうまい人もいるので、得意なものは人それぞれだ。',
    ],
    options: ['にしろ', 'やら', 'もいれば', 'とすれば'],
    answer: 'もいれば',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 8,
    content: [
      '日本',
      '、アジアの様々な国に豆腐を使った料理があります。',
    ],
    options: ['において', 'をはじめ', 'を通して', 'に応じて'],
    answer: 'をはじめ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 9,
    content: [
      '外出が禁止された',
      '、配達サービスも止まってしまったので、不便でしょうがない。',
    ],
    options: ['上に', 'もとで', 'にしても', 'にしろ'],
    answer: '上に',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 10,
    content: [
      '今年は、結婚',
      '娘も生まれて、幸せな一年だった。',
    ],
    options: ['もすると', 'もしたら', 'もすれば', 'もするなら'],
    answer: 'もすれば',
    type: '文法形式の判断',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 11,
    content: [
      'あやの先生は',
      '上手なので、学校でとても人気がある。',
    ],
    options: ['かわいければ', '教え方', '顔も', 'も'],
    answer: '教え方',
    order: [3, 1, 2, 4],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 12,
    content: [
      'おすしや天ぷら',
      '海外でも人気がある。',
    ],
    options: ['のみならず', '日本', 'といった', '料理は'],
    answer: 'のみならず',
    order: [3, 4, 2, 1],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 13,
    content: [
      'みんながいる前で「好きだ！」と大声で告白されて、',
      'が混乱してしまった。',
    ],
    options: ['頭の中', 'うれしいやら', 'やら', '恥ずかしい'],
    answer: 'やら',
    order: [2, 4, 3, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 14,
    content: [
      '頭が良くて',
      '、クラスのみんなは彼のことが大好きだ。',
    ],
    options: ['ので', 'おもしろい', 'できる上に', 'スポーツが'],
    answer: 'できる上に',
    order: [4, 3, 2, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.ENUMERATION,
  },
  {
    id: 15,
    content: [
      '誕生日パーティー',
      '、返事はできるだけ早い方がいい。',
    ],
    options: ['しない', 'に参加する', 'にしろ参加', 'にしろ'],
    answer: 'に参加する',
    order: [2, 3, 1, 4],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.ENUMERATION,
  },
  // SECTION 14: 語彙のような文法 - GRAMMAR 122 - 129
  {
    id: 1,
    content: [
      '息子は中学生になると学校を休み',
      'になって、家でゲームばかりするようになった。',
    ],
    options: ['かけ', 'そう', 'がち', 'きり'],
    answer: 'がち',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 2,
    content: [
      '放課後は、',
      'を全部終わらせてから遊びに行くつもりだ。',
    ],
    options: ['やったかけの宿題', 'やるかけの宿題', 'やらかけの宿題', 'やりかけの宿題'],
    answer: 'やりかけの宿題',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 3,
    content: [
      '世界を旅して回ると言って家を',
      '、10年間一度も家に戻ってきていない。',
    ],
    options: ['出て行った以上', '出て行ったきり', '出て行ったばかり', '出て行ったおきに'],
    answer: '出て行ったきり',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 4,
    content: [
      '海外に住むことは大変なことだと',
      'だが、最近では外国でも日本製の物を手に入れることができるので生活に困ることはない。',
    ],
    options: ['思われがち', '思わしがち', '思わせがち', '思われるがち'],
    answer: '思われがち',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 5,
    content: [
      '漢字に全てふりがなが付いているので、これは留学生',
      '本だと思う。',
    ],
    options: ['中心の', 'ままの', '向けの', 'ほどの'],
    answer: '向けの',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 6,
    content: [
      '彼は何か',
      'が、彼女が話し始めたのでだまってしまった。',
    ],
    options: ['言いさした', '言いすぎた', '言いのがれた', '言いかけた'],
    answer: '言いかけた',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 7,
    content: [
      '会社に行けないほどでもなかったが、体がだるくてかぜ',
      'だったので休むことにした。',
    ],
    options: ['向き', '気味', 'がち', '風'],
    answer: '気味',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 8,
    content: [
      '彼女はもう大学生だが、話し方や行動がなんとなく',
      'と思う。',
    ],
    options: ['子どもがちだ', '子どもげだ', '子どもっぽい', '子どもっきり'],
    answer: '子どもっぽい',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 9,
    content: [
      '「さようなら」と言った彼女は、どこかさびし',
      'な顔をしていた。',
    ],
    options: ['さ', 'ぎ', 'み', 'げ'],
    answer: 'げ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 10,
    content: [
      '人の物を断りなく勝手に使う人の気持ちは、全く',
      '。',
    ],
    options: ['理解し得ない', '理解しかける', '理解しかない', '理解しなきゃ'],
    answer: '理解し得ない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 11,
    content: [
      'ここ一年くらい',
      'は、引っ越して環境が変わったからだろうか。',
    ],
    options: ['なの', 'がち', 'かぜを', 'ひき'],
    answer: 'がち',
    order: [3, 4, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 12,
    content: [
      '大地震を経験し、自然災害は',
      'と実感した。',
    ],
    options: ['いつでも', 'なんだ', '得ること', '起こり'],
    answer: '起こり',
    order: [1, 4, 3, 2],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 13,
    content: [
      '我が社は、',
      'サービスを提供しています。',
    ],
    options: ['一人で暮らす', 'サポートする', '買い物や掃除などの家事を', '高齢者向けに'],
    answer: '高齢者向けに',
    order: [1, 4, 3, 2],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 14,
    content: [
      'あとで',
      '、「早く捨てなさい」と母に叱られた。',
    ],
    options: ['飲もうと思って', 'ジュースを机の上に', '置いておいたら', '飲みかけの'],
    answer: '飲もうと思って',
    order: [1, 4, 2, 3],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  {
    id: 15,
    content: [
      '3年前に',
      'をしなくなった。',
    ],
    options: ['きり', 'した', 'スキー', 'けがを'],
    answer: 'きり',
    order: [4, 2, 1, 3],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.LEXICAL_GRAMMAR,
  },
  // SECTION 15: 丁寧な表現・その他 - GRAMMAR 130 - 135
  {
    id: 1,
    content: [
      'もし、キムさんの連絡先を',
      'でしたら、教えていただけませんか。',
    ],
    options: ['ご承知', 'ご存じ', 'ご覧', 'お求め'],
    answer: 'ご存じ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 2,
    content: [
      '客：「すみません、この商品はいつ入荷予定ですか。」\n店員：「申し訳ありません。まだ未定ですので',
      'かねます。」',
    ],
    options: ['お答えする', 'お答えになり', 'お答えし', 'お答えされ'],
    answer: 'お答えし',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 3,
    content: [
      '部下；「今週末は、社長は自宅に',
      '。」\n社長；「うん、いるよ。」',
    ],
    options: ['おっしゃいますか', '参りますか', 'おりますか', 'おいでになりますか'],
    answer: 'おいでになりますか',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 4,
    content: [
      '（修理会社の人）\n冷蔵庫から変な音がするとのことですが、ちょっと',
      'いいですか？',
    ],
    options: ['見せられても', '見てもらっても', '見せてもらっても', '見せてくれても'],
    answer: '見せてもらっても',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 5,
    content: [
      '客；「この服、サイズが合わなかったので返品したいのですが。」\n店員；「申し訳ありません。こちらの商品は値下げ品ですので返品の対応は',
      '。」',
    ],
    options: ['いたしかねます', '存じます', 'おいでになります', 'させてもらいます'],
    answer: 'いたしかねます',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 6,
    content: [
      '（講演会で）\n運動をすると、幸福度が増して、ストレス解消になることを',
      '。',
    ],
    options: ['存じていますか', 'ご存知ですか', '承知していますか', 'ご覧になりますか'],
    answer: 'ご存知ですか',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 7,
    content: [
      '初めまして。今日から一緒に',
      '、グエンと申します。よろしくお願いします。',
    ],
    options: ['働かせてもらう', '働いてもらう', '働かせられる', '働かせてくれる'],
    answer: '働かせてもらう',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 8,
    content: [
      '3時間くらい時間が空いていますが、その間社長はホテルに',
      '。',
    ],
    options: ['存じていますか', '存じ上げますか', 'おいでになりますか', '参りますか'],
    answer: 'おいでになりますか',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 9,
    content: [
      '学生：「お忙しいところすみませんが、ちょっと',
      'よろしいでしょうか。」\n教授；「はい、どうぞ。」',
    ],
    options: ['おっしゃっても', 'お聞きになっても', 'お聞きしても', '存じ上げても'],
    answer: 'お聞きしても',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 10,
    content: [
      'このズボン、買ったはいいけど私には似合わない色だから、佐藤さん',
      '？',
    ],
    options: ['くれてもらわない', 'あげてくれない', 'もらってあげない', 'もらってくれない'],
    answer: 'もらってくれない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 11,
    content: [
      'ではまず、弊社を志望した、',
      'でしょうか。',
    ],
    options: ['お聞き', 'よろしい', '理由を', 'しても'],
    answer: 'しても',
    order: [3, 1, 4, 2],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 12,
    content: [
      '山田さん、うちの畑でトマトがたくさん採れた',
      '?',
    ],
    options: ['少し', 'から', 'もらって', 'くれない'],
    answer: '少し',
    order: [2, 1, 3, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 13,
    content: [
      'すみません、この機械の',
      '。まだ慣れていなくて。',
    ],
    options: ['ですか', 'ご存じ', '入れ方を', '電源の'],
    answer: 'ご存じ',
    order: [4, 3, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 14,
    content: [
      '今日はおいしいものを',
      '本当にありがとうございました。',
    ],
    options: ['もらい', 'たくさん', 'させて', '食べ'],
    answer: 'させて',
    order: [2, 4, 3, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 15,
    content: [
      'この旅館は、天皇陛下が',
      'そうです。',
    ],
    options: ['なった', 'ある', 'ことも', 'おいでに'],
    answer: 'おいでに',
    order: [4, 1, 3, 2],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 16,
    content: [
      '日本人にとって、最もなじみのあるお酒といえば「日本酒」ではないだろうか。飲み物として愛されてきた日本酒だが、現代では別の形で使われることも多くなった。その活用方法を一つみなさまに',
      'と思う。「酒かす化粧水」だ。「酒かす」というのは、日本酒を作る際にできる白い固形物である。',
    ],
    options: ['紹介した', '紹介しそう', '紹介しよう', '紹介しただろう'],
    answer: '紹介しよう',
    type: '文法の文章',
    situation: "お酒と美容",
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 17,
    content: [
      'この酒かすを使った化粧水が、肌をきれいにする効果があると言われ始めたのである。酒かすを食材として利用することは昔からよくあったが、酒かすから化粧水を作るというのは、全く新しいアイデアだ。\n',
      '化粧水だけではなく酒かすを使った石けんやクリームなど、美容に関する様々な商品が市場に登場するようになった。',
    ],
    options: ['しかし', 'さらに', 'おそらく', 'ついに'],
    answer: 'さらに',
    type: '文法の文章',
    situation: "お酒と美容",
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 18,
    content: [
      '美容に関心がある世の中の人々も、商品名に「酒かす」という文字があるだけで「肌に良さそう！」というイメージを持つようになった。\nこの',
      '、様々な企業が「酒かす」という名前のついた商品をたくさん販売し始めたことにより、このような商品はあまりめずらしいものではなくなった。しかし、ただのブームに終わらず、今でも人気のある商品となっている。',
    ],
    options: ['流れに乗らず', '流れに乗りかけて', '流れに乗るまで', '流れに乗って'],
    answer: '流れに乗って',
    type: '文法の文章',
    situation: "お酒と美容",
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 19,
    content: [
      'その理由は、本当に肌に良いと言われる成分が酒かすにはたくさん入っているからだ。酒かすに含まれるコウジ酸は、メラニンを作りにくくする働きがある。メラニンは肌にできるシミの原因となるものであるため、酒かすによってシミが減り肌がきれいになる',
      '。',
    ],
    options: ['というものだ', 'という気がする', 'というわけだ', 'というのだろうか'],
    answer: 'というわけだ',
    type: '文法の文章',
    situation: "お酒と美容",
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
  {
    id: 20,
    content: [
      'ここまで聞いて、本当に効果があるのか疑問に感じている方も多いだろう。効果があるのかどうか、',
      '。まずはその手で実際に試してみて欲しい。',
    ],
    options: ['疑っていても始まらない', '疑うと間違いない', '疑おうとよくならない', '疑ってみるとよくない'],
    answer: '疑っていても始まらない',
    type: '文法の文章',
    situation: "お酒と美容",
    category: GrammarEntryCategory.POLITE_EXPRESSIONS_OTHERS,
  },
];
