import { GrammarEntryCategory } from "../../../enums";

export const NIHONGO_NO_MORI_GRAMMAR_MONDAI_N2: any[] = [
  // SECTION 4: 順接・逆接 - GRAMMAR 29 - 40
  {
    id: 1,
    content: [
      '背が高い',
      '、ゴールキーパーに選ばれた。',
    ],
    moji: '',
    options: ['といえば', 'というより', 'というだけで', 'としたら'],
    answer: 'というだけで',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 2,
    content: [
      '今日は雨の日',
      '、たくさんお客さんが来ている。',
    ],
    moji: '',
    options: ['にあたって', 'とすると', 'のはずで', 'のわりに'],
    answer: 'のわりに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 3,
    content: [
      '雨',
      '、野球の試合は中止にならなかった。',
    ],
    moji: '',
    options: ['をとわず', 'というより', 'にもかかわらず', 'ということに'],
    answer: 'にもかかわらず',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 4,
    content: [
      'さすが元ダンス部',
      '、山田さんはダンスを覚えるのが早いね。',
    ],
    moji: '',
    options: ['だけあって', 'のみならず', 'というより', 'といえども'],
    answer: 'だけあって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 5,
    content: [
      '芸能人と同じ髪型にした',
      'その人みたいな顔になれるわけではない。',
    ],
    moji: '',
    options: ['にしては', 'のだったら', 'にもかかわらず', 'からといって'],
    answer: 'からといって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 6,
    content: [
      '彼は一年生',
      '落ち着いていて、しっかりしている。',
    ],
    moji: '',
    options: ['とするなら', 'からしか', 'どころか', 'にしては'],
    answer: 'にしては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 7,
    content: [
      '今日は暑い中仕事を頑張った',
      '家で飲むビールは特別においしかった。',
    ],
    moji: '',
    options: ['だけに', 'からって', 'のだったら', 'ものの'],
    answer: 'だけに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 8,
    content: [
      '彼は日本に行ったこと',
      'アニメを観て日本語がうまくなったそうだ。',
    ],
    moji: '',
    options: ['にしては', 'こそないが', 'からには', 'のみにして'],
    answer: 'こそないが',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 9,
    content: [
      'ジムに入会した',
      '、毎日通ってトレーニングをすると決めた。',
    ],
    moji: '',
    options: ['までは', 'からには', 'としては', 'といえば'],
    answer: 'からには',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 10,
    content: [
      '料理をした',
      '、卵を焼いただけの簡単な料理ですよ。',
    ],
    moji: '',
    options: ['だけあって', 'というだけで', 'といっても', 'のみならず'],
    answer: 'といっても',
    type: '文法形式の判断',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 11,
    content: [
      '連休',
      '遠くに出かけることはできない。',
    ],
    moji: '',
    options: ['3日間', 'あまり', 'だけなので', 'といっても'],
    answer: '3日間',
    order: [4, 1, 3, 2],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 12,
    content: [
      '日本人だ',
      '実はそんなことはない。',
    ],
    moji: '',
    options: ['漢字を全部', 'からといって', '書ける', 'かというと'],
    answer: 'かというと',
    order: [2, 1, 3, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 13,
    content: [
      'やっぱり',
      '、ゆか先生は言葉の使い方がとてもきれいだ。',
    ],
    moji: '',
    options: ['あって', 'だけ', 'の先生', '日本語'],
    answer: 'だけ',
    order: [4, 3, 2, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 14,
    content: [
      '好きな仕事を見つけて毎日',
      '自分に合う仕事が見つからず転職ばかりする人もいる。',
    ],
    moji: '',
    options: ['人がいる', '過ごす', '一方で', '楽しく'],
    answer: '過ごす',
    order: [4, 2, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 15,
    content: [
      '他の店に',
      '味はあまり良くない。',
    ],
    moji: '',
    options: ['わりに', '高い', 'かなり値段が', '比べて'],
    answer: '比べて',
    order: [4, 3, 2, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  // SECTION 5: 悪い意味 - GRAMMAR 41 - 48
  {
    id: 1,
    content: [
      '今日は忙しすぎて、昼ごはんを食べるために10分休むことすら',
      '。',
    ],
    moji: '',
    options: ['できるそうだ', 'できつつある', 'できそうもない', 'できるまでもない'],
    answer: 'できそうもない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 2,
    content: [
      '彼は',
      '、休日遊びに行っても声をかけられたり写真を撮られたりして大変だ。',
    ],
    moji: '',
    options: ['有名であるとともに', '有名であるようでは', '有名であるどころか', '有名であるばかりに'],
    answer: '有名であるばかりに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 3,
    content: [
      'お金がなくて貧乏だった私は、困った',
      'あやしい人からお金を借りてしまった。',
    ],
    moji: '',
    options: ['あげく', 'ようで', '一方', 'とおり'],
    answer: 'あげく',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 4,
    content: [
      '健康になりたいと思っていても、体に悪いものばかり',
      '病気になってしまう。',
    ],
    moji: '',
    options: ['食べたくせに', '食べていては', '食べたとして', '食べたことから'],
    answer: '食べていては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 5,
    content: [
      'アルファベットを覚えただけでは、英語の試験に',
      'よ。',
    ],
    moji: '',
    options: ['合格するっこない', '合格してっこない', '合格したっこない', 'xxx合格できっこないxx'],
    answer: '合格できっこない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 6,
    content: [
      '一度負けただけで泣いている',
      '、強い選手になることはできない。',
    ],
    moji: '',
    options: ['ようでは', 'ようには', 'ようものなら', 'ようで'],
    answer: 'ようでは',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 7,
    content: [
      'スーパーでさんざんチーズの味見を',
      '、結局何も買わなかった。',
    ],
    moji: '',
    options: ['するあげく', 'したあげく', 'しないあげく', 'すればあげく'],
    answer: 'したあげく',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 8,
    content: [
      'そんなに一生懸命練習したって、プロの野球選手に',
      '。',
    ],
    moji: '',
    options: ['なれるようではないよ', 'なれっこないよ', 'なれなくちゃいけないよ', 'なれたところではないよ'],
    answer: 'なれっこないよ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 9,
    content: [
      '彼はいつも遅刻する',
      '、友達が待ち合わせの時間に遅れたときはすごく怒る。',
    ],
    moji: '',
    options: ['まま', 'ばかりに', 'くせに', '以上'],
    answer: 'くせに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 10,
    content: [
      '恋人と別れて悲しそうな彼女を元気づけたら、',
      '落ち込んでしまった。',
    ],
    moji: '',
    options: ['一方で', '先立って', '比べて', 'かえって'],
    answer: 'かえって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 11,
    content: [
      '今朝、うっかり',
      'に怒られてしまった。',
    ],
    moji: '',
    options: ['遅刻して', '寝坊した', '先生', 'ばかりに'],
    answer: 'ばかりに',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 12,
    content: [
      'なんだか疲れていたの',
      '体調が悪化した。',
    ],
    moji: '',
    options: ['夜まで', '寝たら', '朝から', 'かえって'],
    answer: '朝から',
    order: [3, 1, 2, 4],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 13,
    content: [
      '一度試験に',
      'いつまでたっても合格できないよ。',
    ],
    moji: '',
    options: ['いては', 'あきらめて', 'といって', '落ちたから'],
    answer: 'いては',
    order: [4, 3, 2, 1],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 14,
    content: [
      'こんな',
      'にバカにされるのも当然だ。',
    ],
    moji: '',
    options: ['簡単な', 'ようじゃ', 'こともわからない', '子どもたち'],
    answer: '簡単な',
    order: [1, 3, 2, 4],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 15,
    content: [
      '彼は私が今まで',
      'ひどいことばかり言ってくる。',
    ],
    moji: '',
    options: ['くせに', '努力してきたか', 'どれだけ', '知らない'],
    answer: '努力してきたか',
    order: [3, 2, 4, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 16,
    content: [
      '文字コミュニケーションに、革命を起こした絵文字。文字のように文中に絵を',
      '「絵文字」という名前が付いた。メールを送る際に絵文字を使用することで、相手に自分の気持ちを正確に伝え、誤解を生みにくくするというメリットがある。あたりまえのように使われているこの絵文字が生まれたのが、日本だということをご存知だろうか。',
    ],
    moji: '',
    options: ['入れられることなく', '入れられることから', '入れられるものの', '入れられることなら'],
    answer: '入れられることから',
    type: '文法の文章',
    category: GrammarEntryCategory.SETSUZOKU_RELATIONS,
  },
  {
    id: 17,
    content: [
      '現在は無料で何文字でもメールを送信することができるが、昔はメールを一通送るたびに料金が発生し、送できる文字数も限られていた。このような制限はあったが、時間や場所を選ばずコミュニケーシンが取れる点が便利だと、多くの日本人が電話よりメールを好むようになった。',
      '、対面せずにコミュニケーションが取れるという点も、恥ずかしがり屋の日本人に好まれた理由の一つだろう。しかし、文字でのコミュニケーションはしばしば送り手と受け手の間に誤解を生じさせた。',
    ],
    moji: '',
    options: ['しかし', 'したがって', 'つまり', 'また'],
    answer: 'また',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 18,
    content: [
      '',
      'ために開発されたのが、絵文字であった。',
    ],
    moji: '',
    options: ['このような問題を解決する', '文字数を増やす', '料金を抑える', 'あんな人の'],
    answer: 'このような問題を解決する',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 19,
    content: [
      'その後インターネット技術が進化し、世界中の誰とでも簡単にメールを交換できるようになった。また、スマートフォンが普及したことにより、絵文字は日本だけでなく、全世界で',
      '。',
    ],
    moji: '',
    options: ['注目するためにある', '注目させられるそうだ', '注目させてくれた', '注目されるようになった'],
    answer: '注目されるようになった',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 20,
    content: [
      '言葉が通じない外国人とのコミュニケーションでも、正確に内容や気持ちが伝えられると、海外でも絵文字の効果が認められている。絵文字がなかったら、これほどまでインターネット上のコミュニケーションは',
      '。 日本人の思いやりが形になった一つの例である。',
    ],
    moji: '',
    options: ['発展したようだ', '発展していたのでしょう', '発展していなかっただろう', '発展さしているようだ'],
    answer: '発展していなかっただろう',
    type: '文法の文章',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  // SECTION 6: 強調 - GRAMMAR 49 - 58
  {
    id: 1,
    content: [
      '遊園地のような人の多いところへは',
      'と思っていたが、彼女ができてからよく行くようになった。',
    ],
    moji: '',
    options: ['行かまい', '行きまい', '行くまい', '行こまい'],
    answer: '行くまい',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 2,
    content: [
      '集中して勉強したいのに、隣でずっと話をされて',
      '。',
    ],
    moji: '',
    options: ['迷惑なわけがない', '迷惑のなんのない', '迷惑しようがない', '迷惑でならない'],
    answer: '迷惑でならない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 3,
    content: [
      '最近ようやく言葉を話すようになった息子が、',
      '。',
    ],
    moji: '',
    options: ['かわいいたまらない', 'かわいくてたまらない', 'かわいくたまらない', 'かわいいでたまらない'],
    answer: 'かわいくてたまらない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 4,
    content: [
      '私と兄は一歳しか年齢が離れていないので、兄弟',
      '親友のような関係だ。',
    ],
    moji: '',
    options: ['というより', 'にほかならず', 'にとって', 'によって'],
    answer: 'というより',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 5,
    content: [
      'ここのラーメンは他の店にはない特別なおいしさがあるので、二時間',
      '食べる価値がある。',
    ],
    moji: '',
    options: ['待ってから', '待ってでも', '待っていて', '待って以来'],
    answer: '待ってでも',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 6,
    content: [
      '息子が試験に合格したと聞いて、うれしさの',
      '大声でさけんでしまった。',
    ],
    moji: '',
    options: ['くせに', 'つもりで', 'なんのって', 'あまり'],
    answer: 'あまり',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 7,
    content: [
      '一人暮らしを始めてさびしい',
      '、毎日一人で泣いてばかりいる。',
    ],
    moji: '',
    options: ['ものの', 'というより', 'のなんのって', 'によって'],
    answer: 'のなんのって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 8,
    content: [
      '父は「今度',
      '当てる！」と言いながら、走って宝くじを買いに行った。',
    ],
    moji: '',
    options: ['ほど', 'には', 'おきに', 'こそ'],
    answer: 'こそ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 9,
    content: [
      '作品が認められて金賞をとることができたのは、彼自身の努力の結果',
      '。',
    ],
    moji: '',
    options: ['でならない', 'というものがある', 'にほかならない', 'にかかわらずだ'],
    answer: 'にほかならない',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 10,
    content: [
      'あんなに一生懸命勉強しているんだから、彼は合格する',
      '。',
    ],
    moji: '',
    options: ['に決まっている', 'にほかならない', 'に先立っている', 'に対している'],
    answer: 'に決まっている',
    type: '文法形式の判断',
    category: GrammarEntryCategory.EMPHASIS,
  },
  {
    id: 11,
    content: [
      '毎週月曜日に放送されるドラマの',
      '。',
    ],
    moji: '',
    options: ['観たくて', '早く', 'たまらない', '続きを'],
    answer: '早く',
    order: [4, 2, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 12,
    content: [
      '途中まで勝っていたのに、最後に逆転されて負けて',
      '。',
    ],
    moji: '',
    options: ['悔しくて', 'しまった', 'ならない', 'ことが'],
    answer: 'ことが',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 13,
    content: [
      '今年は準優勝だったが、',
      '心に決めた。',
    ],
    moji: '',
    options: ['と', 'こそ', '優勝するぞ', '来年'],
    answer: '優勝するぞ',
    order: [4, 2, 3, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 14,
    content: [
      '突然',
      '持っていたアイスクリームを床に落としてしまった。',
    ],
    moji: '',
    options: ['驚きの', '雷が', 'あまり', '鳴って'],
    answer: '鳴って',
    order: [2, 4, 1, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  {
    id: 15,
    content: [
      'こんなに短期間で、完ぺきに歌と踊りを覚えられるのは',
      '。',
    ],
    moji: '',
    options: ['ほか', '才能に', 'ならない', '彼女たちの'],
    answer: 'ほか',
    order: [4, 2, 1, 3],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.BAD_MEANING,
  },
  // SECTION 7: 時間 - GRAMMAR 59 - 67
  {
    id: 1,
    content: [
      '彼女は',
      '私のまねばかりしてくるので、嫌な気分になる。',
    ],
    moji: '',
    options: ['何の通りに', '何に対して', '何かにつけて', '何はともあれ'],
    answer: '何かにつけて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 2,
    content: [
      '勉強している',
      '、妹が私の部屋に何度も来るので集中できない。',
    ],
    moji: '',
    options: ['上で', '次第', '一方', '最中'],
    answer: '最中',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 3,
    content: [
      '外で大きな音',
      '、「助けて」という子どもの声が聞こえた。',
    ],
    moji: '',
    options: ['したかと思うと', 'したと思って', 'したと思わず', 'したかと思うに'],
    answer: 'したかと思うと',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 4,
    content: [
      '勉強する',
      '最も大切なことは、目標を立てて毎日少しずつ取り組むことだ。',
    ],
    moji: '',
    options: ['上が', '上に', '上で', '上は'],
    answer: '上で',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 5,
    content: [
      '賞味期限が切れているおにぎり',
      '、お腹が痛くなり始めた。',
    ],
    moji: '',
    options: ['食べたはずで', '食べたついでに', '食べたとたん', '食べた次第に'],
    answer: '食べたとたん',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 6,
    content: [
      'インフルエンザでしばらく学校を休んでいたので、一週間',
      'に友達に会えた。',
    ],
    moji: '',
    options: ['たち', 'きり', 'うえ', 'ぶり'],
    answer: 'ぶり',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 7,
    content: [
      '日曜日は美容院へ行く',
      '、マッサージを受けてエステにも行く予定だ。',
    ],
    moji: '',
    options: ['とたんに', 'ついでに', '最中に', '以上に'],
    answer: 'ついでに',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 8,
    content: [
      '映画が終わる',
      '終わらない',
      'のうちに、お客さんはみんな立ち上がって帰り始めた。',
    ],
    moji: '',
    options: ['の/の', 'に/に', 'と/と', 'か/か'],
    answer: 'か/か',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 9,
    content: [
      '大学合格の知らせを',
      '、母は大喜びして泣き始めた。',
    ],
    moji: '',
    options: ['聞きとたん', '聞くとたん', '聞いてとたん', '聞いたとたん'],
    answer: '聞いたとたん',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 10,
    content: [
      '勉強',
      '、英語の曲をたくさん聞くようにしている。',
    ],
    moji: '',
    options: ['にとって', 'をかねて', 'のあまり', 'にしても'],
    answer: 'をかねて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 11,
    content: [
      '桜は',
      'かと考えているうちに桜の季節が終わってしまった。',
    ],
    moji: '',
    options: ['散ってしまうので', 'かと思うと', '咲いた', 'いつ見に行こう'],
    answer: 'いつ見に行こう',
    order: [3, 2, 1, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 12,
    content: [
      '',
      'ので、今朝は早起きしないですんだ。',
    ],
    moji: '',
    options: ['ついでに', '作っておいた', 'お弁当のおかずも', '夕食を作る'],
    answer: '夕食を作る',
    order: [4, 1, 3, 2],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 13,
    content: [
      '日本に留学して3年経つが、国にいる家族のことを',
      'と思う。',
    ],
    moji: '',
    options: ['つらいことがあっても', '考える', 'につけ', '頑張ろう'],
    answer: 'につけ',
    order: [2, 3, 1, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 14,
    content: [
      '彼と',
      '誰かすぐには思い出せなかった。',
    ],
    moji: '',
    options: ['見た目が', '会うのは', '変わっていて', '10年ぶりなので'],
    answer: '見た目が',
    order: [2, 4, 1, 3],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  {
    id: 15,
    content: [
      'シャワーを浴びている',
      'あわてて出た。',
    ],
    moji: '',
    options: ['体もふかずに', '最中に', '上司から', '電話がかかってきて'],
    answer: '最中に',
    order: [2, 3, 4, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.TIME,
  },
  // SECTION 8: 基準・関連 - GRAMMAR 68 - 77
  {
    id: 1,
    content: [
      'グローバル化する現代',
      '最も必要とされる能力は、コミュニケーション能力である。',
    ],
    moji: '',
    options: ['にはって', 'によって', 'にのって', 'において'],
    answer: 'において',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 2,
    content: [
      '',
      '、すしや天ぷらを思い出す人が多いと思います。',
    ],
    moji: '',
    options: ['日本食というと', '日本食をめぐって', '日本食にかけては', '日本食とは'],
    answer: '日本食というと',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 3,
    content: [
      '夏になると、気温の上昇',
      '熱中症になる人の数が増加する。',
    ],
    moji: '',
    options: ['に備えて', 'に基づいて', 'に伴って', ' に沿って'],
    answer: 'に伴って',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 4,
    content: [
      '健康のために毎朝のウォーキング',
      '、仕事終わりにジムへ通って筋トレをしている。',
    ],
    moji: '',
    options: ['に沿って', 'に加えて', 'において', 'にかけて'],
    answer: 'に加えて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 5,
    content: [
      '大通り',
      '、同じ色の家がたくさん並んでいる。',
    ],
    moji: '',
    options: ['において', 'によって', 'に反して', 'に沿って'],
    answer: 'に沿って',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 6,
    content: [
      '優勝候補のチームが次々と負け、大会は予想',
      '結果となった。',
    ],
    moji: '',
    options: ['に対した', 'に応じる', 'に基づく', 'に反する'],
    answer: 'に反する',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 7,
    content: [
      'この会社では、能力と仕事の結果',
      '社員の給料を決定しています。',
    ],
    moji: '',
    options: ['に加えて', 'に反して', 'に応じて', 'に比べて'],
    answer: 'に応じて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 8,
    content: [
      'ナポリタン',
      '、ケチャップを使った日本風のスパゲティのことである。',
    ],
    moji: '',
    options: ['とは', 'では', 'さえ', 'ただ'],
    answer: 'とは',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 9,
    content: [
      '一人の',
      '、二人の男性が激しく言い争いをしている。',
    ],
    moji: '',
    options: ['女性にあたって', '女性に基づいて', '女性に沿って', '女性をめぐって'],
    answer: '女性をめぐって',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 10,
    content: [
      '料理の味とお客様へのサービス',
      '、この店が日本で一番だ。',
    ],
    moji: '',
    options: ['にとっては', 'にかけては', 'をめぐっては', 'をかねては'],
    answer: 'にかけては',
    type: '文法形式の判断',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 11,
    content: [
      'うちの本屋は古い本から新しい本まで取りそろえているので、',
      'に負けることはないだろう。',
    ],
    moji: '',
    options: ['他の店', '豊富さ', '本の種類の', 'にかけては'],
    answer: 'にかけては',
    order: [3, 2, 4, 1],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 12,
    content: [
      '',
      '、そこには食品や日用品がたくさん売っている。',
    ],
    moji: '',
    options: ['言葉で', '短くした', 'スーパーとは', 'スーパーマーケットを'],
    answer: 'スーパーとは',
    order: [3, 4, 2, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 13,
    content: [
      '現在の日本社会では、高齢化',
      'が問題になっている。',
    ],
    moji: '',
    options: ['若くて力のある', 'に伴う', '働き手', 'の不足'],
    answer: 'の不足',
    order: [2, 1, 3, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 14,
    content: [
      '今年こそは',
      'は初戦で負けてしまった。',
    ],
    moji: '',
    options: ['国民の期待', '優勝するだろうという', '日本チーム', 'に反して'],
    answer: '国民の期待',
    order: [2, 1, 4, 3],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  {
    id: 15,
    content: [
      '先日、祖父が急に亡くなった。明日、祖父の遺産の相続',
      '話し合うことになっている。',
    ],
    moji: '',
    options: ['皆で集まって', 'をめぐる', 'について', '問題'],
    answer: 'をめぐる',
    order: [2, 4, 3, 1],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.STANDARDS_AND_RELATIONS,
  },
  // SECTION 10: 状況・伝聞 - GRAMMAR 87 - 97
  {
    id: 1,
    content: [
      '熱を出している娘のために、早く元気になりますようにという願い',
      '、おかゆを作った。',
    ],
    options: ['を除いて', 'に応じて', 'を込めて', 'を伴って'],
    answer: 'を込めて',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 2,
    content: [
      '駅前の新しいパン屋さん、大人気で午前中には売り切れてしまうんだ',
      '。',
    ],
    options: ['のに', 'など', 'こと', 'とか'],
    answer: 'とか',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 3,
    content: [
      '大雨で家の中まで雨が入ってきて、ゆっくりご飯を食べる',
      'ではない。',
    ],
    options: ['ばかり', 'どころ', 'まで', 'しだい'],
    answer: 'どころ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 4,
    content: [
      '監督の厳しい指導',
      '、見事優勝することができました。',
    ],
    options: ['のところ', 'のつもり', 'のももっとも', 'のもと'],
    answer: 'のもと',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 5,
    content: [
      '何か悩み事でもあるのか、彼は一日中下を',
      '。',
    ],
    options: ['向いてばかりいる', '向いたところだ', '向くどころではない', '向くおそれがある'],
    answer: '向いてばかりいる',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 6,
    content: [
      'ここに、実際の赤ちゃんと同じ重さの人形があります。お母さんになった',
      '、抱っこしてみてください。',
    ],
    options: ['みたいで', 'つもりで', 'ようで', 'しだいで'],
    answer: 'つもりで',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 7,
    content: [
      '大雨により、水が',
      'おそれがありますので、川には近づかないようにしてください。',
    ],
    options: ['あふれて', 'あふれよう', 'あふれる', 'あふれない'],
    answer: 'あふれる',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 8,
    content: [
      '健康診断を受けていたので、がんが早いうちに見つかり、手術',
      '。',
    ],
    options: ['せずにすんだ', 'どころではなかった', 'のつもりだった', 'してばかりいる'],
    answer: 'せずにすんだ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 9,
    content: [
      '山田くんは水泳が得意で、まるで泳いでいる魚',
      '美しく泳ぐ。',
    ],
    options: ['ようになっても', 'かと思うと', 'だからと言って', 'かのように'],
    answer: 'かのように',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 10,
    content: [
      '毎日上司の文句を聞きながら仕事をするなんて、辞めたくなるのも',
      '。',
    ],
    options: ['もっともだ', '一方だ', '次第だ', 'ばかりだ'],
    answer: 'もっともだ',
    type: '文法形式の判断',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 11,
    content: [
      'お昼ご飯を食べていたら急に大きな',
      'ではなくなってしまった。',
    ],
    options: ['休憩', '地震', 'が起きて', 'どころ'],
    answer: 'が起きて',
    order: [2, 3, 1, 4],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 12,
    content: [
      '母は歳をとってから何度も同じ話をするようになったが、息子はいつも',
      'その話を楽しそうに聞く。',
    ],
    options: ['かの', '初めて', '聞いた', 'ように'],
    answer: 'かの',
    order: [2, 3, 1, 4],
    starPosition: 3,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 13,
    content: [
      '会社を立ち上げてしばらくはお金がなかったので、実家の',
      '使っていた。',
    ],
    options: ['事務所', '部屋', 'として', 'を'],
    answer: '部屋',
    order: [2, 4, 1, 3],
    starPosition: 1,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 14,
    content: [
      '間違った使い方を',
      'ので、使う前に説明書を読んでください。',
    ],
    options: ['爆発', 'するおそれ', 'すると', 'があります'],
    answer: 'があります',
    order: [3, 1, 2, 4],
    starPosition: 4,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 15,
    content: [
      '日本人に',
      'と、いつもより少しうまく話せるような気がする。',
    ],
    options: ['話す', '日本語を', 'つもりで', 'なった'],
    answer: 'つもりで',
    order: [4, 3, 2, 1],
    starPosition: 2,
    type: '並び替え',
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 16,
    content: [
      '道路が凍ってしまう北海道では、安全に暮らす上で様々な工夫がされています。その一つに、「ロードヒーティング」というものがあります。\n北海道より暖かい東北地方では、地下水を路の上に少しだけ流すと雪がとけますが、東北地方より気温が低い北海道では、地下水を',
      '道が凍って危険です。',
    ],
    options: ['流してしまうあげく', '流してしまうばかりに', '流してしまいさえすれば', '流してしまったらかえって'],
    answer: '流してしまったらかえって',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 17,
    content: [
      'そのため北海道では、道路の下に電熱線や温水を循環させるパイプを埋めて、道路を加熱します。これにより、雪が降ってもすぐにとけて雪のない路面状態を保つことができます。かつて冬の間は、「スパイクタイヤ」という、地面に触れる面に小さな金属を打ち込んだタイヤを使用するのが主流でした。',
      'により、雪道や凍ったつるつるの路でも、すべらず安定した走行ができたのです。',
    ],
    options: ['タイヤ', 'このタイヤ', 'どのタイヤ', 'あのタイヤ'],
    answer: 'このタイヤ',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 18,
    content: [
      'しかし、これは雪や氷の上',
      '、暖かくなってくる春先、雪がとけ、アスファルトの道路の上を走ると、付いている金属が路面をけずってしまい、ほこりが舞って環境問題を引き起こすという欠点がありました。そこで「スパイクタイヤ」の使用は規制され、それに代わって金属が付いていないタイヤが使用されるようになりました。ですが、やはりそのタイヤでは十分に安全が確保されなかったため、「ロードヒーティング」が広まったというわけです。',
    ],
    options: ['こそ能力を発揮しますが', 'だと能力が発揮されなく', 'でも能力を発揮するだけに', ' なのに能力が発揮されて'],
    answer: 'こそ能力を発揮しますが',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 19,
    content: [
      '',
      'この設備は、急な坂やカーブなど、車がすべって事故が発生する可能性が高い場所に整備されました。近年では車道だけなく、人がすべって転ばないようにコンビニの前や自宅の玄関先にも整備されるようになってきています。',
    ],
    options: ['けれども', 'こうして', 'さらに', 'そこで'],
    answer: 'こうして',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
  {
    id: 20,
    content: [
      'また、高齢の方が暮らしている家では、この設備のおかげで、お年寄りが雪を取り除くという',
      '、負担が軽減されているのです。',
    ],
    options: ['重労働をしてでも', '重労働をかねて', '重労働をせずにすみ', '重労働をするどころではなく'],
    answer: '重労働をせずにすみ',
    type: '文法の文章',
    situation: "北海道で暮らす工夫",
    category: GrammarEntryCategory.CIRCUMSTANCES_HEARSAY,
  },
];
