export const KANJI_YDC_LESSON_20: Array<KanjiYDC> = [
  {
    kanji: '場',
    onyomi: ['じょう'],
    kunyomi: ['ば'],
    meaning: ['Place', 'Location'],
    examples: [
      {
        reading: '場所',
        kana: 'ばしょ',
        meaning: ['Place', 'Location'],
        sentence: 'この場所はとても静かです。',
        type: 'YDC_main',
      },
      {
        reading: '場合',
        kana: 'ばあい',
        meaning: ['Case', 'Situation'],
        sentence: '緊急の場合は、すぐに連絡してください。',
        type: 'YDC_main',
      },
      {
        reading: '会場',
        kana: 'かいじょう',
        meaning: ['Venue', 'Meeting place'],
        sentence: 'コンサートの会場はとても広いです。',
        type: 'YDC_main',
      },
      {
        reading: '工場',
        kana: 'こうじょう',
        meaning: ['Factory'],
        sentence: '工場で新しい製品が作られています。',
        type: 'YDC_main',
      },
      {
        reading: '売り場',
        kana: 'うりば',
        meaning: ['Sales floor', 'Counter'],
        sentence: 'デパートの売り場で買い物をしました。',
        type: 'YDC_main',
      },
      {
        reading: '駐車場',
        kana: 'ちゅうしゃじょう',
        meaning: ['Parking lot'],
        sentence: '駐車場は満車でした。',
        type: 'main',
      },
      {
        reading: '広場',
        kana: 'ひろば',
        meaning: ['Square', 'Open space'],
        sentence: '広場で子供たちが遊んでいます。',
        type: 'secondary',
      },
      {
        reading: '市場',
        kana: 'いちば',
        meaning: ['Market'],
        sentence: '市場で新鮮な野菜を買いました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '戸',
    onyomi: ['こ'],
    kunyomi: ['と', 'ど'],
    meaning: ['Door', 'Counter for houses'],
    examples: [
      {
        reading: '戸',
        kana: 'と',
        meaning: ['Door'],
        sentence: '戸を開けて、外に出ました。',
        type: 'YDC_main',
      },
      {
        reading: '戸棚',
        kana: 'とだな',
        meaning: ['Cupboard', 'Shelf'],
        sentence: '戸棚の中に食器をしまいました。',
        type: 'secondary',
      },
      {
        reading: '井戸',
        kana: 'いど',
        meaning: ['Well'],
        sentence: '井戸から水を汲みました。',
        type: 'secondary',
      },
      {
        reading: '戸締り',
        kana: 'とじまり',
        meaning: ['Locking up', 'Securing doors'],
        sentence: '戸締りを忘れずにしてください。',
        type: 'secondary',
      },
      {
        reading: '網戸',
        kana: 'あみど',
        meaning: ['Screen door'],
        sentence: '夏は網戸を使って、虫を防ぎます。',
        type: 'secondary',
      },
      {
        reading: '江戸時代',
        kana: 'えどじだい',
        meaning: ['Edo period'],
        sentence: '江戸時代は日本の歴史の中で重要な時期です。',
        type: 'main',
      },
      {
        reading: '戸籍',
        kana: 'こせき',
        meaning: ['Family register'],
        sentence: '戸籍は個人の身分を証明する重要な書類です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '所',
    onyomi: ['しょ', 'じょ'],
    kunyomi: ['ところ', 'どころ'],
    meaning: ['Place', 'Location'],
    examples: [
      {
        reading: 'どんな所',
        kana: 'どんなところ',
        meaning: ['What kind of place'],
        sentence: 'どんな所に住んでいますか？',
        type: 'YDC_main',
      },
      {
        reading: '台所',
        kana: 'だいどころ',
        meaning: ['Kitchen'],
        sentence: '台所で料理をしています。',
        type: 'YDC_main',
      },
      {
        reading: '住所',
        kana: 'じゅうしょ',
        meaning: ['Address'],
        sentence: '新しい住所を教えてください。',
        type: 'YDC_main',
      },
      {
        reading: '近所',
        kana: 'きんじょ',
        meaning: ['Neighborhood'],
        sentence: '近所の人と仲良くしています。',
        type: 'YDC_main',
      },
      {
        reading: '場所',
        kana: 'ばしょ',
        meaning: ['Place', 'Location'],
        sentence: 'この場所はとても静かです。',
        type: 'YDC_main',
      },
      {
        reading: '事務所',
        kana: 'じむしょ',
        meaning: ['Office'],
        sentence: '事務所で働いています。',
        type: 'main',
      },
      {
        reading: '市役所',
        kana: 'しやくしょ',
        meaning: ['City hall'],
        sentence: '市役所で住民票を取得しました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '屋',
    onyomi: ['おく'],
    kunyomi: ['や'],
    meaning: ['Roof', 'Shop'],
    examples: [
      {
        reading: '本屋',
        kana: 'ほんや',
        meaning: ['Bookstore'],
        sentence: '本屋で新しい本を買いました。',
        type: 'YDC_main',
      },
      {
        reading: '屋上',
        kana: 'おくじょう',
        meaning: ['Rooftop'],
        sentence: '屋上で花火を見るのが好きです。',
        type: 'YDC_main',
      },
      {
        reading: '八百屋',
        kana: 'やおや',
        meaning: ['Greengrocer', 'Vegetable shop'],
        sentence: '八百屋で新鮮な野菜を買いました。',
        type: 'main',
      },
      {
        reading: '部屋',
        kana: 'へや',
        meaning: ['Room'],
        sentence: '私の部屋はとても広いです。',
        type: 'main',
      },
      {
        reading: '床屋',
        kana: 'とこや',
        meaning: ['Barber shop'],
        sentence: '床屋で髪を切ってもらいました。',
        type: 'main',
      },
      {
        reading: '屋根',
        kana: 'やね',
        meaning: ['Roof'],
        sentence: '屋根の上に鳥が止まっています。',
        type: 'secondary',
      },
      {
        reading: '名古屋',
        kana: 'なごや',
        meaning: ['Nagoya (city in Japan)'],
        sentence: '名古屋は日本の大都市の一つです。',
        type: 'main',
      },
      {
        reading: '酒屋',
        kana: 'さかや',
        meaning: ['Liquor store'],
        sentence: '酒屋で日本酒を買いました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '堂',
    onyomi: ['どう'],
    kunyomi: [],
    meaning: ['Hall'],
    examples: [
      {
        reading: '食堂',
        kana: 'しょくどう',
        meaning: ['Dining hall', 'Cafeteria'],
        sentence: '大学の食堂で昼食を食べました。',
        type: 'YDC_main',
      },
      {
        reading: '講堂',
        kana: 'こうどう',
        meaning: ['Auditorium', 'Lecture hall'],
        sentence: '講堂で講演会が開かれました。',
        type: 'secondary',
      },
      {
        reading: '堂々と',
        kana: 'どうどうと',
        meaning: ['Confidently', 'With dignity'],
        sentence: '彼は堂々とスピーチをしました。',
        type: 'secondary',
      },
      {
        reading: '公会堂',
        kana: 'こうかいどう',
        meaning: ['Public hall'],
        sentence: '公会堂で地域のイベントが行われます。',
        type: 'secondary',
      },
      {
        reading: '国会議事堂',
        kana: 'こっかいぎじどう',
        meaning: ['National Diet Building'],
        sentence: '国会議事堂は日本の政治の中心地です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '都',
    onyomi: ['と', 'つ'],
    kunyomi: ['みやこ'],
    meaning: ['Capital', 'Metropolis'],
    examples: [
      {
        reading: '東京都',
        kana: 'とうきょうと',
        meaning: ['Tokyo Metropolis'],
        sentence: '東京都は日本の首都です。',
        type: 'YDC_main',
      },
      {
        reading: '首都',
        kana: 'しゅと',
        meaning: ['Capital city'],
        sentence: '日本の首都は東京です。',
        type: 'YDC_main',
      },
      {
        reading: '都合',
        kana: 'つごう',
        meaning: ['Convenience', 'Circumstances'],
        sentence: '都合が悪いので、今日は行けません。',
        type: 'YDC_main',
      },
      {
        reading: '京都',  
        kana: 'きょうと',
        meaning: ['Kyoto'],
        sentence: '京都は歴史的な街で、観光名所がたくさんあります。',
        type: 'YDC_main',
      },
      {
        reading: '都会',
        kana: 'とかい',
        meaning: ['City', 'Urban area'],
        sentence: '都会の生活は便利ですが、忙しいです。',
        type: 'main',
      },
      {
        reading: '都',
        kana: 'みやこ',
        meaning: ['Capital', 'Metropolis'],
        sentence: '古代の都は今でも観光地として人気があります。',
        type: 'main',
      },
      {
        reading: '都心',
        kana: 'としん',
        meaning: ['City center', 'Downtown'],
        sentence: '都心には高層ビルが立ち並んでいます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '県',
    onyomi: ['けん'],
    kunyomi: [],
    meaning: ['Prefecture'],
    examples: [
      {
        reading: '長野県',  
        kana: 'ながのけん',
        meaning: ['Nagano Prefecture'],
        sentence: '長野県は美しい自然が豊かな場所です。',
        type: 'YDC_main',
      },
      {
        reading: '神奈川県',
        kana: 'かながわけん',
        meaning: ['Kanagawa Prefecture'],
        sentence: '神奈川県には横浜市があります。',
        type: 'main',
      },
      {
        reading: '県庁',
        kana: 'けんちょう',
        meaning: ['Prefectural office'],
        sentence: '県庁で住民票を取得しました。',
        type: 'secondary',
      },
      {
        reading: '県知事',
        kana: 'けんちじ',
        meaning: ['Governor of a prefecture'],
        sentence: '県知事は地域の問題に取り組んでいます。',
        type: 'secondary',
      },
      {
        reading: '県立',  
        kana: 'けんりつ',
        meaning: ['Prefectural'],
        sentence: '県立の図書館は多くの本を所蔵しています。',
        type: 'secondary',
      },
      {
        reading: '都道府県',  
        kana: 'とどうふけん',
        meaning: ['Prefectures and cities'],
        sentence: '日本には47の都道府県があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '区',
    onyomi: ['く'],
    kunyomi: [],
    meaning: ['Ward', 'District'],
    examples: [
      {
        reading: '北区',  
        kana: 'きたく',
        meaning: ['Kita Ward'],
        sentence: '北区には多くの公園があります。',
        type: 'YDC_main',
      },
      {
        reading: '区切る',
        kana: 'くぎる',
        meaning: ['To divide', 'To separate'],
        sentence: '文章を区切って、読みやすくしました。',
        type: 'secondary',
      },
      {
        reading: '区域',
        kana: 'くいき',
        meaning: ['District'],
        sentence: 'この区域は静かな住宅街です。',
        type: 'secondary',
      },
      {
        reading: '地区',
        kana: 'ちく',
        meaning: ['Area'],
        sentence: 'この地区は治安が良いと評判です。',
        type: 'secondary',
      },
      {
        reading: '区役所',
        kana: 'くやくしょ',
        meaning: ['Ward office'],
        sentence: '区役所で住民票を取得しました。',
        type: 'main',
      },
      {
        reading: '区別する',
        kana: 'くべつする',
        meaning: ['To distinguish', 'To differentiate'],
        sentence: '男女を区別せずに平等に扱います。',
        type: 'secondary',
      },
      {
        reading: '区間',
        kana: 'くかん',
        meaning: ['Section', 'Segment'],
        sentence: 'この区間の電車は遅れています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '池',
    onyomi: ['ち'],
    kunyomi: ['いけ'],
    meaning: ['Pond'],
    examples: [
      {
        reading: '池',
        kana: 'いけ',
        meaning: ['Pond'],
        sentence: '池にはたくさんの魚がいます。',
        type: 'YDC_main',
      },
      {
        reading: '電池',
        kana: 'でんち',
        meaning: ['Battery'],
        sentence: '電池が切れたので、新しいものに交換しました。',
        type: 'YDC_main',
      },
      {
        reading: '溜め池',
        kana: 'ためいけ',
        meaning: ['Irrigation pond'],
        sentence: '溜め池は農業用の水源として利用されています。',
        type: 'secondary',
      },
      {
        reading: '貯水池',
        kana: 'ちょすいち',
        meaning: ['Reservoir'],
        sentence: '貯水池は水の供給源として重要です。',
        type: 'secondary',
      },
      {
        reading: '用水池',
        kana: 'ようすいち',
        meaning: ['Water reservoir'],
        sentence: '用水池は農業用の水を蓄えるために作られています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '発',
    onyomi: ['はつ', 'ぱつ', 'ほつ', 'はっ', 'ほっ'],
    kunyomi: [],
    meaning: ['To depart', 'To reveal'],
    examples: [
      {
        reading: '発音',
        kana: 'はつおん',
        meaning: ['Pronunciation'],
        sentence: '日本語の発音は難しいです。',
        type: 'YDC_main',
      },
      {
        reading: '出発',
        kana: 'しゅっぱつ',
        meaning: ['Departure'],
        sentence: '明日の朝、出発します。',
        type: 'YDC_main',
      },
      {
        reading: '発表',
        kana: 'はっぴょう',
        meaning: ['Presentation', 'Announcement'],
        sentence: '会議で新しいプロジェクトを発表しました。',
        type: 'main',
      },
      {
        reading: '発明',
        kana: 'はつめい',
        meaning: ['Invention'],
        sentence: '彼は新しい技術を発明しました。',
        type: 'main',
      },
      {
        reading: '発見',
        kana: 'はっけん',
        meaning: ['Discovery'],
        sentence: '科学者は新しい惑星を発見しました。',
        type: 'main',
      },
      {
        reading: '発売',
        kana: 'はつばい',
        meaning: ['Release', 'Launch'],
        sentence: '新しいスマートフォンが発売されました。',
        type: 'secondary',
      },
      {
        reading: '始発',
        kana: 'しはつ',
        meaning: ['First train of the day', 'First bus'],
        sentence: '始発の電車に乗って、早朝の仕事に向かいます。',
        type: 'main',
      },
      {
        reading: '発足',
        kana: 'ほっそく',
        meaning: ['Inauguration', 'Establishment'],
        sentence: '新しい団体が発足しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '建',
    onyomi: ['けん', 'こん'],
    kunyomi: ['た', 'だ'],
    meaning: ['To build', 'To construct'],
    examples: [
      {
        reading: '建てる',
        kana: 'たてる',
        meaning: ['To build', 'To construct'],
        sentence: '新しい家を建てる予定です。',
        type: 'YDC_main',
      },
      {
        reading: '建物',
        kana: 'たてもの',
        meaning: ['Building'],
        sentence: 'この建物は歴史的な価値があります。',
        type: 'YDC_main',
      },
      {
        reading: '建つ',
        kana: 'たつ',
        meaning: ['To be built', 'To stand'],
        sentence: '新しいビルが建っています。',
        type: 'secondary',
      },
      {
        reading: '建設',
        kana: 'けんせつ',
        meaning: ['Construction'],
        sentence: '新しい道路の建設が始まりました。',
        type: 'secondary',
      },
      {
        reading: '建築',
        kana: 'けんちく',
        meaning: ['Architecture', 'Building construction'],
        sentence: '建築の勉強をしています。',
        type: 'secondary',
      },
      {
        reading: '二階建て',
        kana: 'にかいだて',
        meaning: ['Two-story building'],
        sentence: 'この家は二階建てです。',
        type: 'secondary',
      },
      {
        reading: '建国',
        kana: 'けんこく',
        meaning: ['Nation building', 'Founding a nation'],
        sentence: '建国記念日は国の重要な日です。',
        type: 'secondary',
      },
      {
        reading: '建立',
        kana: 'こんりゅう',
        meaning: ['Construction of a temple or shrine'],
        sentence: 'この寺院は平安時代に建立されました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '物',
    onyomi: ['ぶつ', 'もつ'],
    kunyomi: ['もの'],
    meaning: ['Thing', 'Object'],
    examples: [
      {
        reading: '物',
        kana: 'もの',
        meaning: ['Thing', 'Object'],
        sentence: 'これはとても大切な物です。',
        type: 'YDC_main',
      },
      {
        reading: '食べ物',
        kana: 'たべもの',
        meaning: ['Food'],
        sentence: '新鮮な食べ物を買いました。',
        type: 'YDC_main',
      },
      {
        reading: '飲み物',
        kana: 'のみもの',
        meaning: ['Drink', 'Beverage'],
        sentence: '冷たい飲み物が欲しいです。',
        type: 'YDC_main',
      },
      {
        reading: '買い物',
        kana: 'かいもの',
        meaning: ['Shopping'],
        sentence: '週末に買い物に行きます。',
        type: 'YDC_main',
      },
      {
        reading: '建物',
        kana: 'たてもの',
        meaning: ['Building'],
        sentence: 'この建物はとても古いです。',
        type: 'YDC_main',
      },
      {
        reading: '着物',
        kana: 'きもの',
        meaning: ['Kimono'],
        sentence: '彼女は美しい着物を着ています。',
        type: 'YDC_main',
      },
      {
        reading: '動物',
        kana: 'どうぶつ',
        meaning: ['Animal'],
        sentence: '動物園でいろいろな動物を見ました。',
        type: 'YDC_main',
      },
      {
        reading: '果物',
        kana: 'くだもの',
        meaning: ['Fruit'],
        sentence: '果物は健康に良いです。',
        type: 'main',
      },
      {
        reading: '荷物',
        kana: 'にもつ',
        meaning: ['Luggage', 'Baggage'],
        sentence: '荷物を持って、駅に向かいます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '品',
    onyomi: ['ひん'],
    kunyomi: ['しな'],
    meaning: ['Goods'],
    examples: [
      {
        reading: '品物',
        kana: 'しなもの',
        meaning: ['Goods', 'Items'],
        sentence: 'この店にはいろいろな品物があります。',
        type: 'YDC_main',
      },
      {
        reading: '日用品',
        kana: 'にちようひん',
        meaning: ['Daily necessities'],
        sentence: '日用品を買いにスーパーに行きました。',
        type: 'main',
      },
      {
        reading: '製品',
        kana: 'せいひん',
        meaning: ['Product', 'Manufactured goods'],
        sentence: 'この会社の製品は品質が高いです。',
        type: 'secondary',
      },
      {
        reading: '必需品',
        kana: 'ひつじゅひん',
        meaning: ['Essentials', 'Necessities'],
        sentence: '旅行には必需品を忘れずに持って行きます。',
        type: 'secondary',
      },
      {
        reading: '作品',
        kana: 'さくひん',
        meaning: ['Work of art', 'Artistic piece'],
        sentence: 'この絵は有名な画家の作品です。',
        type: 'secondary',
      },
      {
        reading: '上品な',
        kana: 'じょうひんな',
        meaning: ['Elegant', 'Refined'],
        sentence: '彼女は上品な服装をしています。',
        type: 'secondary',
      },
      {
        reading: '下品な',
        kana: 'げひんな',
        meaning: ['Vulgar', 'Unrefined'],
        sentence: '下品な言葉を使わないでください。',
        type: 'secondary',
      },
      {
        reading: '食料品',
        kana: 'しょくりょうひん',
        meaning: ['Food products', 'Groceries'],
        sentence: '食料品を買いに行きました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '旅',
    onyomi: ['りょ'],
    kunyomi: ['たび'],
    meaning: ['Travel', 'Journey'],
    examples: [
      {
        reading: '旅行',
        kana: 'りょこう',
        meaning: ['Travel', 'Trip'],
        sentence: '来月、旅行に行く予定です。',
        type: 'YDC_main',
      },
      {
        reading: '旅館',
        kana: 'りょかん',
        meaning: ['Japanese inn'],
        sentence: '旅館で温泉に入りました。',
        type: 'YDC_main',
      },
      {
        reading: '旅券',
        kana: 'りょけん',
        meaning: ['Passport'],
        sentence: '海外旅行には旅券が必要です。',
        type: 'main',
      },
      {
        reading: '旅',
        kana: 'たび',
        meaning: ['Journey', 'Trip'],
        sentence: '彼は世界一周の旅をしています。',
        type: 'main',
      },
      {
        reading: '一人旅',
        kana: 'ひとりたび',
        meaning: ['Solo travel'],
        sentence: '一人旅は自由で楽しいです。',
        type: 'main',
      },
      {
        reading: '旅費',
        kana: 'りょひ',
        meaning: ['Travel expenses'],
        sentence: '旅費を節約するために、安い宿を探しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '通',
    onyomi: ['つう', 'つ'],
    kunyomi: ['とお', 'かよ'],
    meaning: ['To pass', 'To commute'],
    examples: [
      {
        reading: '通る',
        kana: 'とおる',
        meaning: ['To pass through', 'To go through'],
        sentence: 'この道を通ると、駅に行けます。',
        type: 'YDC_main',
      },
      {
        reading: '通う',
        kana: 'かよう',
        meaning: ['To commute (Go everyday)'],
        sentence: '毎日、学校に通っています。',
        type: 'YDC_main',
      },
      {
        reading: '通り',
        kana: 'とおり',
        meaning: ['Street', 'Avenue'],
        sentence: 'この通りにはたくさんの店があります。',
        type: 'YDC_main',
      },
      {
        reading: '交通',
        kana: 'こうつう',
        meaning: ['Traffic', 'Transportation'],
        sentence: '交通渋滞がひどいです。',
        type: 'main',
      },
      {
        reading: '通訳',
        kana: 'つうやく',
        meaning: ['Interpretation'],
        sentence: '彼は英語の通訳をしています。',
        type: 'secondary',
      },
      {
        reading: '普通の',
        kana: 'ふつうの',
        meaning: ['Ordinary'],
        sentence: '普通の生活を送っています。',
        type: 'secondary',
      },
      {
        reading: '通学',
        kana: 'つうがく',
        meaning: ['Commuting to school'],
        sentence: '通学時間は約30分です。',
        type: 'secondary',
      },
      {
        reading: '通勤',
        kana: 'つうきん',
        meaning: ['Commuting to work'],
        sentence: '通勤時間は長いですが、電車は快適です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '進',
    onyomi: ['しん'],
    kunyomi: ['すす'],
    meaning: ['To advance', 'To proceed'],
    examples: [
      {
        reading: '進む',
        kana: 'すすむ',
        meaning: ['(Something) advances'],
        sentence: '新しい技術が進んでいます。',
        type: 'YDC_main',
      },
      {
        reading: '進める',
        kana: 'すすめる',
        meaning: ['To advance (something)'],
        sentence: 'プロジェクトを進めるために会議を開きます。',
        type: 'main',
      },
      {
        reading: '進学',
        kana: 'しんがく',
        meaning: ['Advancing to a higher level of education'],
        sentence: '大学に進学することを決めました。',
        type: 'secondary',
      },
      {
        reading: '進歩',
        kana: 'しんぽ',
        meaning: ['Progress', 'Advancement'],
        sentence: '科学技術の進歩は目覚ましいです。',
        type: 'secondary',
      },
      {
        reading: '進化',
        kana: 'しんか',
        meaning: ['Evolution'],
        sentence: '生物の進化は長い時間をかけて起こります。',
        type: 'secondary',
      },
      {
        reading: '昇進',
        kana: 'しょうしん',
        meaning: ['Promotion'],
        sentence: '彼は会社で昇進しました。',
        type: 'secondary',
      },
      {
        reading: '先進国',
        kana: 'せんしんこく',
        meaning: ['Developed country'],
        sentence: '先進国は技術が発展しています。',
        type: 'secondary',
      },
    ],
  },
]