export const KANJI_YDC_LESSON_27: Array<KanjiYDC> = [
  {
    kanji: '吉',
    onyomi: ['きち', 'きつ', 'きっ'],
    kunyomi: [],
    meaning: ['Good luck', 'Good fortune'],
    examples: [
      {
        reading: '吉',
        kana: 'きち',
        meaning: ['Good luck', 'Good fortune'],
        sentence: '吉日を選んで結婚式を挙げました。',
        type: 'secondary',
      },
      {
        reading: '大吉',
        kana: 'だいきち',
        meaning: ['Great luck'],
        sentence: '大吉の結果が出ました。',
        type: 'YDC_main',
      },
      {
        reading: '吉日',
        kana: 'きちにち',
        meaning: ['Lucky day'],
        sentence: '吉日を選んで結婚式を挙げました。',
        type: 'secondary',
      },
      {
        reading: '不吉な',
        kana: 'ふきつな',
        meaning: ['Unlucky'],
        sentence: '不吉な予感がします。',
        type: 'secondary',
      },
      {
        reading: '吉報',
        kana: 'きっぽう',
        meaning: ['Good news', 'Welcome news'],
        sentence: '吉報が届きました。',
        type: 'secondary',
      },
      {
        reading: '吉凶',
        kana: 'きっきょう',
        meaning: ['Good and bad luck'],
        sentence: '吉凶を占う。',
        type: 'secondary',
      },
      {
        reading: '吉田さん',
        kana: 'よしださん',
        meaning: ['Mr./Ms. Yoshida'],
        sentence: '吉田さんは優しい人です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '結',
    onyomi: ['けつ', 'けっ'],
    kunyomi: ['むす', 'ゆ'],
    meaning: ['Tie', 'Bind', 'Join'],
    examples: [
      {
        reading: '結婚する',
        kana: 'けっこんする',
        meaning: ['To get married'],
        sentence: '彼らは来月結婚します。',
        type: 'YDC_main',
      },
      {
        reading: '結ぶ',
        kana: 'むすぶ',
        meaning: ['To tie a knot', 'To bind'],
        sentence: 'リボンを結ぶのが得意です。',
        type: 'YDC_main',
      },
      {
        reading: '結果',
        kana: 'けっか',
        meaning: ['Result'],
        sentence: 'テストの結果が気になります。',
        type: 'YDC_main',
      },
      {
        reading: '結論',
        kana: 'けつろん',
        meaning: ['Conclusion'],
        sentence: '結論を言うと、彼は来ないでしょう。',
        type: 'secondary',
      },
      {
        reading: '結う',
        kana: 'ゆう',
        meaning: ['To tie', 'To bind'],
        sentence: '彼はリボンを結うのが得意です。',
        type: 'secondary',
      },
      {
        reading: '結局',
        kana: 'けっきょく',
        meaning: ['After all', 'In the end'],
        sentence: '結局、彼は来なかった。',
        type: 'main',
      },
      {
        reading: '団結する',
        kana: 'だんけつする',
        meaning: ['To unite', 'To come together'],
        sentence: 'みんなで団結して問題に立ち向かいましょう。',
        type: 'secondary',
      },
      {
        reading: '結構',
        kana: 'けっこう',
        meaning: ['Fairly', 'Quite', 'Well enough', 'No thank you'],
        sentence: 'この問題は結構難しいです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '婚',
    onyomi: ['こん'],
    kunyomi: [],
    meaning: ['Marriage', 'Wedding'],
    examples: [
      {
        reading: '結婚する',
        kana: 'けっこんする',
        meaning: ['To get married'],
        sentence: '彼らは来月結婚します。',
        type: 'YDC_main',
      },
      {
        reading: '離婚',
        kana: 'りこん',
        meaning: ['Divorce'],
        sentence: '彼は離婚して一人暮らしを始めました。',
        type: 'main',
      },
      {
        reading: '婚約',
        kana: 'こんやく',
        meaning: ['Engagement'],
        sentence: '彼らは婚約しました。',
        type: 'secondary',
      },
      {
        reading: '婚約者',
        kana: 'こんやくしゃ',
        meaning: ['Fiancé', 'Fiancée'],
        sentence: '彼らは婚約者です。',
        type: 'secondary',
      },
      {
        reading: '既婚',
        kana: 'きこん',
        meaning: ['Married'],
        sentence: '彼は既婚者です。',
        type: 'secondary',
      },
      {
        reading: '未婚',
        kana: 'みこん',
        meaning: ['Unmarried'],
        sentence: '彼は未婚です。',
        type: 'secondary',
      },
      {
        reading: '新婚',
        kana: 'しんこん',
        meaning: ['Newlywed'],
        sentence: '彼らは新婚です。',
        type: 'secondary',
      },
      {
        reading: '求婚する',
        kana: 'きゅうこんする',
        meaning: ['To propose marriage'],
        sentence: '彼は彼女に求婚しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '共',
    onyomi: ['きょう'],
    kunyomi: ['とも'],
    meaning: ['Together', 'Common'],
    examples: [
      {
        reading: '共に',
        kana: 'ともに',
        meaning: ['Together'],
        sentence: '共に頑張りましょう。',
        type: 'YDC_main',
      },
      {
        reading: '共通',
        kana: 'きょうつう',
        meaning: ['Common', 'Shared'],
        sentence: 'この問題は共通の課題です。',
        type: 'YDC_main',
      },
      {
        reading: '公共',
        kana: 'こうきょう',
        meaning: ['Public', 'Common'],
        sentence: '公共の場ではマナーを守りましょう。',
        type: 'YDC_main',
      },
      {
        reading: '共感する',
        kana: 'きょうかんする',
        meaning: ['To empathize'],
        sentence: '彼女の気持ちに共感します。',
        type: 'secondary',
      },
      {
        reading: '共産主義',
        kana: 'きょうさんしゅぎ',
        meaning: ['Communism'],
        sentence: '共産主義は平等を重視します。',
        type: 'secondary',
      },
      {
        reading: '共学',
        kana: 'きょうがく',
        meaning: ['Co-education'],
        sentence: 'この学校は共学です。',
        type: 'secondary',
      },
      {
        reading: '共同',
        kana: 'きょうどう',
        meaning: ['Partnership', 'Joint'],
        sentence: '共同作業で問題を解決しましょう。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '供',
    onyomi: ['きょう', 'く'],
    kunyomi: ['ども', 'とも', 'そな'],
    meaning: ['Offer', 'Provide'],
    examples: [
      {
        reading: '子供',
        kana: 'こども',
        meaning: ['Child'],
        sentence: '子供たちは公園で遊んでいます。',
        type: 'YDC_main',
      },
      {
        reading: '供える',
        kana: 'そなえる',
        meaning: ['To offer (something to a spirit)'],
        sentence: '神社に花を供えました。',
        type: 'secondary',
      },
      {
        reading: '供給する',
        kana: 'きょうきゅうする',
        meaning: ['To supply', 'To provide'],
        sentence: 'この工場は電力を供給しています。',
        type: 'secondary',
      },
      {
        reading: '提供',
        kana: 'ていきょう',
        meaning: ['Provision', 'Offer'],
        sentence: 'このサービスは多くの人に提供されています。',
        type: 'secondary',
      },
      {
        reading: '試供品',
        kana: 'しきょうひん',
        meaning: ['Sample', 'Trial product'],
        sentence: '試供品をもらいました。',
        type: 'secondary',
      },
      {
        reading: 'お供する',
        kana: 'おともする',
        meaning: ['To accompany', 'To go with'],
        sentence: '彼は私にお供してくれました。',
        type: 'secondary',
      },
      {
        reading: '供養',
        kana: 'くよう',
        meaning: ['Buddhist memorial service'],
        sentence: '供養のためにお花を供えました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '両',
    onyomi: ['りょう'],
    kunyomi: [],
    meaning: ['Both', 'Pair'],
    examples: [
      {
        reading: '両親',
        kana: 'りょうしん',
        meaning: ['Parents'],
        sentence: '両親は私を支えてくれました。',
        type: 'YDC_main',
      },
      {
        reading: '両手',
        kana: 'りょうて',
        meaning: ['Both hands'],
        sentence: '両手で荷物を持ち上げました。',
        type: 'YDC_main',
      },
      {
        reading: '両方',
        kana: 'りょうほう',
        meaning: ['Both sides', 'Either'],
        sentence: '両方の意見を考慮する必要があります。',
        type: 'YDC_main',
      },
      {
        reading: '両側',
        kana: 'りょうがわ',
        meaning: ['Both sides'],
        sentence: '両側からの意見を聞くことが大切です。',
        type: 'YDC_main',
      },
      {
        reading: '両替',
        kana: 'りょうがえ',
        meaning: ['Currency exchange'],
        sentence: '空港で両替をしました。',
        type: 'main',
      },
      {
        reading: '両立する',
        kana: 'りょうりつする',
        meaning: ['To be compatible', 'To coexist'],
        sentence: '仕事と趣味を両立させるのは難しいです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '若',
    onyomi: ['じゃく', 'にゃく'],
    kunyomi: ['わか', 'も'],
    meaning: ['Young', 'Immature'],
    examples: [
      {
        reading: '若い',
        kana: 'わかい',
        meaning: ['Young'],
        sentence: '若い人たちが集まっています。',
        type: 'YDC_main',
      },
      {
        reading: '若者',
        kana: 'わかもの',
        meaning: ['Young person', 'Youth'],
        sentence: '若者の意見を尊重することが大切です。',
        type: 'YDC_main',
      },
      {
        reading: '若々しい',
        kana: 'わかわかしい',
        meaning: ['Youthful', 'Young-looking'],
        sentence: '彼は若々しい外見をしています。',
        type: 'secondary',
      },
      {
        reading: '若しくは',
        kana: 'もしくは',
        meaning: ['Or', 'Either'],
        sentence: 'AもしくはBの選択肢があります。',
        type: 'secondary',
      },
      {
        reading: '若輩',
        kana: 'じゃくはい',
        meaning: ['Young and inexperienced person'],
        sentence: '若輩の意見を尊重することが大切です。',
        type: 'secondary',
      },
      {
        reading: '老若男女',
        kana: 'ろうにゃくなんにょ',
        meaning: ['Old and young, men and women', 'men and women of all ages'],
        sentence: '老若男女を問わず参加できます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '老',
    onyomi: ['ろう'],
    kunyomi: ['お', 'ふ'],
    meaning: ['Old', 'Aged'],
    examples: [
      {
        reading: '老人',
        kana: 'ろうじん',
        meaning: ['Old person', 'Elderly'],
        sentence: '老人ホームでボランティアをしています。',
        type: 'YDC_main',
      },
      {
        reading: '老いる',
        kana: 'おいる',
        meaning: ['To grow old', 'To age'],
        sentence: '人は老いるにつれて経験を積む。',
        type: 'secondary',
      },
      {
        reading: '老ける',
        kana: 'ふける',
        meaning: ['To grow old', 'To age'],
        sentence: '彼は最近老けて見える。',
        type: 'secondary',
      },
      {
        reading: '老化',
        kana: 'ろうか',
        meaning: ['Aging', 'Old age'],
        sentence: '老化は誰にでも訪れる自然な現象です。',
        type: 'secondary',
      },
      {
        reading: '老眼',
        kana: 'ろうがん',
        meaning: ['farsightedness due to old age', 'presbyopia'],
        sentence: '老眼が進んで、細かい字が見えにくくなりました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '息',
    onyomi: ['そく'],
    kunyomi: ['いき'],
    meaning: ['Breath', 'Respiration'],
    examples: [
      {
        reading: '息',
        kana: 'いき',
        meaning: ['Breath', 'Respiration'],
        sentence: '深呼吸をして息を整えました。',
        type: 'YDC_main',
      },
      {
        reading: '息子',
        kana: 'むすこ',
        meaning: ['Son'],
        sentence: '息子は今大学生です。',
        type: 'YDC_main',
      },
      {
        reading: '休息',
        kana: 'きゅうそく',
        meaning: ['Rest', 'Break'],
        sentence: '仕事の合間に休息を取ります。',
        type: 'main',
      },
      {
        reading: '息をする',
        kana: 'いきをする',
        meaning: ['To breathe'],
        sentence: '深呼吸をして息を整えました。',
        type: 'secondary',
      },
      {
        reading: '消息',
        kana: 'しょうそく',
        meaning: ['News', 'Information'],
        sentence: '最新の消息をお伝えします。',
        type: 'secondary',
      },
      {
        reading: 'ため息',
        kana: 'ためいき',
        meaning: ['Sigh'],
        sentence: 'ため息をつくと、少し楽になりました。',
        type: 'secondary',
      },
      {
        reading: '息切れ',
        kana: 'いきぎれ',
        meaning: ['Breathlessness', 'Out of breath'],
        sentence: '運動をしすぎて息切れしてしまいました。',
        type: 'secondary',
      },
      {
        reading: '息抜き',
        kana: 'いきぬき',
        meaning: ['Relaxation', 'Break'],
        sentence: '仕事の合間に息抜きをします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '娘',
    onyomi: [],
    kunyomi: ['むすめ'],
    meaning: ['Daughter'],
    examples: [
      {
        reading: '娘',
        kana: 'むすめ',
        meaning: ['Daughter'],
        sentence: '彼女は私の娘です。',
        type: 'YDC_main',
      },
      {
        reading: '一人娘',
        kana: 'ひとりむすめ',
        meaning: ['Only daughter'],
        sentence: '彼女は一人娘です。',
        type: 'main',
      },
      {
        reading: '娘婿',
        kana: 'むすめむこ',
        meaning: ['Son-in-law'],
        sentence: '彼は私の娘婿です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '奥',
    onyomi: ['おう'],
    kunyomi: ['おく'],
    meaning: ['Back', 'Inner part'],
    examples: [
      {
        reading: '奥',
        kana: 'おく',
        meaning: ['Back', 'Inner part'],
        sentence: '窓を開けて新鮮な空気を入れました。',
        type: 'YDC_main',
      },
      {
        reading: '奥さん',
        kana: 'おくさん',
        meaning: ['Wife', 'Mrs.'],
        sentence: '奥さんはとても優しい人です。',
        type: 'YDC_main',
      },
      {
        reading: '奥歯',
        kana: 'おくば',
        meaning: ['Back tooth', 'Molar'],
        sentence: '奥歯が痛くなってきました。',
        type: 'main',
      },
      {
        reading: '奥ゆかしい',
        kana: 'おくゆかしい',
        meaning: ['Modest', 'Reserved'],
        sentence: '彼女は奥ゆかしい性格です。',
        type: 'secondary',
      },
      {
        reading: '奥行き',
        kana: 'おくゆき',
        meaning: ['Depth of a space'],
        sentence: 'この部屋の奥行きは3メートルです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '将',
    onyomi: ['しょう'],
    kunyomi: [],
    meaning: ['Command'],
    examples: [
      {
        reading: '将来',
        kana: 'しょうらい',
        meaning: ['Future'],
        sentence: '将来の夢は何ですか？',
        type: 'YDC_main',
      },
      {
        reading: '将棋',
        kana: 'しょうぎ',
        meaning: ['Shogi', 'Japanese chess'],
        sentence: '将棋は日本の伝統的なボードゲームです。',
        type: 'secondary',
      },
      {
        reading: '将軍',
        kana: 'しょうぐん',
        meaning: ['Shogun', 'General'],
        sentence: '将軍は戦の指揮を執ります。',
        type: 'secondary',
      },
      {
        reading: '主将',
        kana: 'しゅしょう',
        meaning: ['Commander', 'Captain of a team'],
        sentence: '彼はチームの主将です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '祖',
    onyomi: ['そ', 'ぞ'],
    kunyomi: [],
    meaning: ['Ancestor'],
    examples: [
      {
        reading: '祖父',
        kana: 'そふ',
        meaning: ['Grandfather'],
        sentence: '私の祖父はとても優しい人です。',
        type: 'YDC_main',
      },
      {
        reading: '祖母',
        kana: 'そぼ',
        meaning: ['Grandmother'],
        sentence: '私の祖母はとても優しい人です。',
        type: 'YDC_main',
      },
      {
        reading: '祖先',
        kana: 'そせん',
        meaning: ['Ancestor'],
        sentence: '私の祖先は日本から来ました。',
        type: 'YDC_main',
      },
      {
        reading: '祖国',
        kana: 'そこく',
        meaning: ['Motherland', 'Home country'],
        sentence: '祖国を離れて暮らすのは寂しいです。',
        type: 'YDC_main',
      },
      {
        reading: '先祖',
        kana: 'せんぞ',
        meaning: ['Ancestor'],
        sentence: '私の先祖は日本から来ました。',
        type: 'secondary',
      },
      {
        reading: '祖父母',
        kana: 'そふぼ',
        meaning: ['Grandparents'],
        sentence: '私の祖父母はとても優しい人です。',
        type: 'secondary',
      },
      {
        reading: '元祖',
        kana: 'がんそ',
        meaning: ['Originator', 'Founder'],
        sentence: '彼はこの流派の元祖です。',
        type: 'secondary',
      },
      {
        reading: '教祖',
        kana: 'きょうそ',
        meaning: ['Religious founder'],
        sentence: '教祖の教えを大切にしています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '育',
    onyomi: ['いく'],
    kunyomi: ['そだ', 'はぐく'],
    meaning: ['To grow'],
    examples: [
      {
        reading: '教育',
        kana: 'きょういく',
        meaning: ['Education'],
        sentence: '教育は国の未来を左右します。',
        type: 'YDC_main',
      },
      {
        reading: '育てる',
        kana: 'そだてる',
        meaning: ['To raise'],
        sentence: '子供を育てるのは大変ですが、楽しいです。',
        type: 'YDC_main',
      },
      {
        reading: '育つ',
        kana: 'そだつ',
        meaning: ['To grow'],
        sentence: '子供が育つのを見るのは楽しいです。',
        type: 'YDC_main',
      },
      {
        reading: '体育',
        kana: 'たいいく',
        meaning: ['Physical education'],
        sentence: '体育の授業は楽しいです。',
        type: 'YDC_main',
      },
      {
        reading: '育児',
        kana: 'いくじ',
        meaning: ['Nurturing children'],
        sentence: '育児は大変ですが、やりがいがあります。',
        type: 'secondary',
      },
      {
        reading: '保育',
        kana: 'ほいく',
        meaning: ['Childcare'],
        sentence: '保育園で子供を預けています。',
        type: 'secondary',
      },
      {
        reading: '飼育する',
        kana: 'しいくする',
        meaning: ['To raise animals', 'To breed'],
        sentence: '彼は犬を飼育しています。',
        type: 'secondary',
      },
      {
        reading: '育む',
        kana: 'はぐくむ',
        meaning: ['To cultivate'],
        sentence: '子供の才能を育むことが大切です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '性',
    onyomi: ['せい', 'しょう'],
    kunyomi: [],
    meaning: ['Sex', 'Character'],
    examples: [
      {
        reading: '男性',
        kana: 'だんせい',
        meaning: ['Male', 'Man'],
        sentence: '彼は男性です。',
        type: 'YDC_main',
      },
      {
        reading: '女性',
        kana: 'じょせい',
        meaning: ['Female', 'Woman'],
        sentence: '彼女は女性です。',
        type: 'YDC_main',
      },
      {
        reading: '性別',
        kana: 'せいべつ',
        meaning: ['Gender', 'Sex'],
        sentence: '性別による差別は許されません。',
        type: 'YDC_main',
      },
      {
        reading: '性格',
        kana: 'せいかく',
        meaning: ['Personality', 'Character'],
        sentence: '彼女の性格はとても明るいです。',
        type: 'main',
      },
      {
        reading: '性質',
        kana: 'せいしつ',
        meaning: ['Nature', 'Characteristic'],
        sentence: 'この商品の性質を理解することが重要です。',
        type: 'secondary',
      },
      {
        reading: '理性',
        kana: 'りせい',
        meaning: ['Reason', 'Rationality'],
        sentence: '理性を持って判断することが大切です。',
        type: 'secondary',
      },
      {
        reading: '酸性',
        kana: 'さんせい',
        meaning: ['Acidity'],
        sentence: 'この液体は酸性です。',
        type: 'secondary',
      },
      {
        reading: '相性',
        kana: 'あいしょう',
        meaning: ['Compatibility'],
        sentence: '彼らは相性が良いカップルです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '招',
    onyomi: ['しょう'],
    kunyomi: ['まね'],
    meaning: ['To invite'],
    examples: [
      {
        reading: '招待する',
        kana: 'しょうたいする',
        meaning: ['To invite'],
        sentence: '友達をパーティーに招待しました。',
        type: 'YDC_main',
      },
      {
        reading: '招く',
        kana: 'まねく',
        meaning: ['To invite'],
        sentence: '友達をパーティーに招くつもりです。',
        type: 'YDC_main',
      },
      {
        reading: '招き',
        kana: 'まねき',
        meaning: ['Invitation'],
        sentence: 'パーティーの招きが届きました。',
        type: 'main',
      },
      {
        reading: '招待状',
        kana: 'しょうたいじょう',
        meaning: ['Invitation card'],
        sentence: 'パーティーの招待状が届きました。',
        type: 'secondary',
      },
    ],
  },
]