export const KANJI_YDC_LESSON_13: Array<KanjiYDC> = [
  {
    kanji: '家',
    onyomi: ['か', 'け'],
    kunyomi: ['いえ', 'や'],
    meaning: ['House', 'Family'],
    examples: [
      {
        reading: '家',
        kana: 'いえ',
        meaning: ['House'],
        sentence: '家に帰ります。',
        type: 'main',
      },
      {
        reading: '家族',
        kana: 'かぞく',
        meaning: ['Family'],
        sentence: '家族で食事します。',
        type: 'main',
      },
      {
        reading: '家庭',
        kana: 'かてい',
        meaning: ['Home', 'Household'],
        sentence: '家庭で勉強します。',
        type: 'secondary',
      },
      {
        reading: '家内',
        kana: 'かない',
        meaning: ['Wife'],
        sentence: '家内がいます。',
        type: 'main',
      },
      {
        reading: '家事',
        kana: 'かじ',
        meaning: ['Housework'],
        sentence: '家事をします。',
        type: 'main',
      },
      {
        reading: '大家',
        kana: 'おおや',
        meaning: ['Landlord'],
        sentence: '大家さんに会います。',
        type: 'main',
      },
      {
        reading: '家賃',
        kana: 'やちん',
        meaning: ['Rent'],
        sentence: '家賃を払います。',
        type: 'main',
      },
      {
        reading: '山田家',
        kana: 'やまだけ',
        meaning: ['Yamada family'],
        sentence: '山田家に会いたい。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '矢',
    onyomi: ['し'],
    kunyomi: ['や'],
    meaning: ['Arrow'],
    examples: [
      {
        reading: '矢',
        kana: 'や',
        meaning: ['Arrow'],
        sentence: '矢を射ます。',
        type: 'secondary',
      },
      {
        reading: '矢印',
        kana: 'やじるし',
        meaning: ['Arrow mark'],
        sentence: '矢印を見てください。',
        type: 'secondary',
      },
      {
        reading: '無理矢理',
        kana: 'むりやり',
        meaning: ['By force', 'Against one\'s will'],
        sentence: '無理矢理行かせる。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '族',
    onyomi: ['ぞく'],
    kunyomi: [],
    meaning: ['Tribe', 'Family'],
    examples: [
      {
        reading: '家族',
        kana: 'かぞく',
        meaning: ['Family'],
        sentence: '家族で食事します。',
        type: 'main',
      },
      {
        reading: '親族',
        kana: 'しんぞく',
        meaning: ['Relatives'],
        sentence: '親族に会います。',
        type: 'main',
      },
      {
        reading: '貴族',
        kana: 'きぞく',
        meaning: ['Noble', 'Aristocrat'],
        sentence: '貴族の家。',
        type: 'secondary',
      },
      {
        reading: '民族',
        kana: 'みんぞく',
        meaning: ['Ethnic group'],
        sentence: '民族の文化。',
        type: 'secondary',
      },
      {
        reading: '水族館',
        kana: 'すいぞくかん',
        meaning: ['Aquarium'],
        sentence: '水族館に行きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '親',
    onyomi: ['しん'],
    kunyomi: ['おや', 'した'],
    meaning: ['Parent', 'Intimate'],
    examples: [
      {
        reading: '親',
        kana: 'おや',
        meaning: ['Parent'],
        sentence: '親に会います。',
        type: 'main',
      },
      {
        reading: '親切な',
        kana: 'しんせつな',
        meaning: ['Kind', 'Friendly'],
        sentence: '親切な人。',
        type: 'main',
      },
      {
        reading: '両親',
        kana: 'りょうしん',
        meaning: ['Parents'],
        sentence: '両親に会います。',
        type: 'main',
      },
      {
        reading: '親友',
        kana: 'しんゆう',
        meaning: ['Best friend'],
        sentence: '親友と遊びます。',
        type: 'main',
      },
      {
        reading: '父親',
        kana: 'ちちおや',
        meaning: ['Father'],
        sentence: '父親に会います。',
        type: 'secondary',
      },
      {
        reading: '母親',
        kana: 'ははおや',
        meaning: ['Mother'],
        sentence: '母親に会います。',
        type: 'secondary',
      },
      {
        reading: '親子',
        kana: 'おやこ',
        meaning: ['Parent and child'],
        sentence: '親子で遊びます。',
        type: 'secondary',
      },
      {
        reading: '親しい',
        kana: 'したしい',
        meaning: ['Intimate', 'Close'],
        sentence: '親しい友達。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '兄',
    onyomi: ['きょう', 'けい'],
    kunyomi: ['あに'],
    meaning: ['Older brother'],
    examples: [
      {
        reading: '兄',
        kana: 'あに',
        meaning: ['Older brother'],
        sentence: '兄に会います。',
        type: 'main',
      },
      {
        reading: 'お兄さん',
        kana: 'おにいさん',
        meaning: ['Older brother'],
        sentence: 'お兄さんに会います。',
        type: 'main',
      },
      {
        reading: '兄弟',
        kana: 'きょうだい',
        meaning: ['Siblings'],
        sentence: '兄弟で遊びます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '姉',
    onyomi: ['し'],
    kunyomi: ['あね'],
    meaning: ['Older sister'],
    examples: [
      {
        reading: '姉',
        kana: 'あね',
        meaning: ['Older sister'],
        sentence: '姉に会います。',
        type: 'main',
      },
      {
        reading: 'お姉さん',
        kana: 'おねえさん',
        meaning: ['Older sister'],
        sentence: 'お姉さんに会います。',
        type: 'main',
      },
      {
        reading: '姉妹',
        kana: 'しまい',
        meaning: ['Sisters'],
        sentence: '姉妹で遊びます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '弟',
    onyomi: ['だい', 'てい', 'で'],
    kunyomi: ['おとうと'],
    meaning: ['Younger brother'],
    examples: [
      {
        reading: '弟',  
        kana: 'おとうと',
        meaning: ['Younger brother'],
        sentence: '弟に会います。',
        type: 'main',
      },
      {
        reading: '兄弟',
        kana: 'きょうだい',
        meaning: ['Siblings'],
        sentence: '兄弟で遊びます。',
        type: 'main',
      },
      {
        reading: '弟子',
        kana: 'でし',
        meaning: ['Disciple'],
        sentence: '弟子に教えます。',
        type: 'secondary',
      },
      {
        reading: '義弟',
        kana: 'ぎてい',
        meaning: ['Youger Brother-in-law'],
        sentence: '義弟に会います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '妹',
    onyomi: ['まい'],
    kunyomi: ['いもうと'],
    meaning: ['Younger sister'],
    examples: [
      {
        reading: '妹',  
        kana: 'いもうと',
        meaning: ['Younger sister'],
        sentence: '妹に会います。',
        type: 'main',
      },
      {
        reading: '姉妹',
        kana: 'しまい',
        meaning: ['Sisters'],
        sentence: '姉妹で遊びます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '私',
    onyomi: ['し'],
    kunyomi: ['わたくし', 'わたし'],
    meaning: ['I', 'Me', 'Private'],
    examples: [
      {
        reading: '私',
        kana: 'わたし・わたくし',
        meaning: ['I', 'Me'],
        sentence: '私は学生です。',
        type: 'main',
      },
      {
        reading: '私立大学',
        kana: 'しりつだいがく',
        meaning: ['Private university'],
        sentence: '私立大学に通います。',
        type: 'main',
      },
      {
        reading: '私鉄',
        kana: 'してつ',
        meaning: ['Private railway'],
        sentence: '私鉄に乗ります。',
        type: 'main',
      },
      {
        reading: '私用',
        kana: 'しよう',
        meaning: ['Private use'],
        sentence: '私用の時間。',
        type: 'main',
      },
      {
        reading: '私有',
        kana: 'しゆう',
        meaning: ['Private ownership'],
        sentence: '私有地。',
        type: 'secondary',
      },
      {
        reading: '私生活',
        kana: 'しせいかつ',
        meaning: ['Private life'],
        sentence: '私生活を大切にします。',
        type: 'main',
      },
      {
        reading: '私書箱',
        kana: 'ししょばこ',
        meaning: ['Post office box'],
        sentence: '私書箱を開けます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '夫',
    onyomi: ['ふ', 'ふう', 'ぶ'],
    kunyomi: ['おっと'],
    meaning: ['Husband'],
    examples: [ 
      {
        reading: '夫',
        kana: 'おっと',
        meaning: ['Husband'],
        sentence: '夫に会います。',
        type: 'main',
      },
      {
        reading: '夫妻',
        kana: 'ふさい',
        meaning: ['Husband and wife'],
        sentence: '夫妻で遊びます。',
        type: 'secondary',
      },
      {
        reading: '夫婦',
        kana: 'ふうふ',
        meaning: ['Married couple'],
        sentence: '夫婦で遊びます。',
        type: 'main',
      },
      {
        reading: '大丈夫',
        kana: 'だいじょうぶ',
        meaning: ['All right', 'OK'],
        sentence: '大丈夫です。',
        type: 'secondary',
      },
      {
        reading: '夫人',
        kana: 'ふじん',
        meaning: ['Married lady', 'Wife'],
        sentence: '夫人に会います。',
        type: 'main',
      },
      {
        reading: '工夫',
        kana: 'くふう',
        meaning: ['Device', 'Invension'],
        sentence: '工夫を凝らす。',
        type: 'secondary',
      },
      {
        reading: '丈夫な',
        kana: 'じょうぶな',
        meaning: ['Strong', 'Sturdy'],
        sentence: '丈夫な体。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '妻',
    onyomi: ['さい'],
    kunyomi: ['つま'],
    meaning: ['Wife (My)'],
    examples: [
      {
        reading: '妻',
        kana: 'つま',
        meaning: ['Wife (My)'],
        sentence: '妻に会います。',
        type: 'main',
      },
      {
        reading: '夫妻',
        kana: 'ふさい',
        meaning: ['Husband and wife'],
        sentence: '夫妻で遊びます。',
        type: 'secondary',
      },
      {
        reading: '妻子',
        kana: 'さいし',
        meaning: ['Wife and children'],
        sentence: '妻子で遊びます。',
        type: 'secondary',
      },
      {
        reading: '一夫多妻',
        kana: 'いっぷたさい',
        meaning: ['Polygamy'],
        sentence: '一夫多妻制度。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '主',
    onyomi: ['しゅ', 'す'],
    kunyomi: ['ぬし', 'おも'],
    meaning: ['Main'],
    examples: [
      {
        reading: '主人',
        kana: 'しゅじん',
        meaning: ['Husband (My)'],
        sentence: '主人に会います。',
        type: 'main',
      },
      {
        reading: '主婦',
        kana: 'しゅふ',
        meaning: ['Housewife'],
        sentence: '主婦の仕事。',
        type: 'main',
      },
      {
        reading: '主語',
        kana: 'しゅご',
        meaning: ['Subject (of a sentence)'],
        sentence: '主語を決めます。',
        type: 'main',
      },
      {
        reading: '主義',
        kana: 'しゅぎ',
        meaning: ['Principle'],
        sentence: '主義を守ります。',
        type: 'secondary',
      },
      {
        reading: '主題',
        kana: 'しゅだい',
        meaning: ['Topic', 'Theme'],
        sentence: '主題を決めます。',
        type: 'main',
      },
      {
        reading: '主食',
        kana: 'しゅしょく',
        meaning: ['Main dish', 'Staple food'],
        sentence: '主食を食べます。',
        type: 'main',
      },
      {
        reading: '主に',
        kana: 'おもに',
        meaning: ['Mainly'],
        sentence: '主に使います。',
        type: 'main',
      },
      {
        reading: '持ち主',
        kana: 'もちぬし',
        meaning: ['Owner'],
        sentence: '持ち主に会います。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '住',
    onyomi: ['じゅう'],
    kunyomi: ['す'],
    meaning: ['To live'],
    examples: [
      {
        reading: '住む',
        kana: 'すむ',
        meaning: ['To live'],
        sentence: '東京に住んでいます。',
        type: 'main',
      },
      {
        reading: '住所',
        kana: 'じゅうしょ',
        meaning: ['Address'],
        sentence: '住所を書いてあります。',
        type: 'main',
      },
      {
        reading: '住民',
        kana: 'じゅうみん',
        meaning: ['Resident'],
        sentence: '住民票を取ります。',
        type: 'main',
      },
      {
        reading: '住宅',
        kana: 'じゅうたく',
        meaning: ['House', 'Residence'],
        sentence: '住宅を建てます。',
        type: 'main',
      },
      {
        reading: '衣食住',
        kana: 'いしょくじゅう',
        meaning: ['Clothing, food, and shelter'],
        sentence: '衣食住を大切にします。',
        type: 'secondary',
      },
      {
        reading: '移住する',
        kana: 'いじゅうする',
        meaning: ['To migrate'],
        sentence: '移住する。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '糸',
    onyomi: ['し'],
    kunyomi: ['いと'],
    meaning: ['Thread'],
    examples: [
      {
        reading: '糸',
        kana: 'いと',
        meaning: ['Thread'],
        sentence: '糸を編みます。',
        type: 'main',
      },
      {
        reading: '毛糸',
        kana: 'けいと',
        meaning: ['Wool', 'Woolen Yarn'],
        sentence: '毛糸で編みます。',
        type: 'secondary',
      },
      {
        reading: '釣り糸',
        kana: 'つりいと',
        meaning: ['Fishing line'],
        sentence: '釣り糸を使います。',
        type: 'secondary',
      },
      {
        reading: '抜糸',
        kana: 'ばっし',
        meaning: ['Stitch removal'],
        sentence: '抜糸します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '氏',
    onyomi: ['し'],
    kunyomi: ['うじ'],
    meaning: ['Surname', 'Family name'],
    examples: [
      {
        reading: '氏名',
        kana: 'しめい',
        meaning: ['Full name'],
        sentence: '氏名を書いてある。',
        type: 'main',
      },
      {
        reading: '彼氏',
        kana: 'かれし',
        meaning: ['Boyfriend'],
        sentence: '彼氏に会います。',
        type: 'main',
      },
      {
        reading: '大野氏',
        kana: 'おおのし',
        meaning: ['Mr. Ohno'],
        sentence: '大野氏に会います。',
        type: 'secondary',
      },
      {
        reading: '摂氏',
        kana: 'せっし',
        meaning: ['Celsius'],
        sentence: '摂氏で測ります。',
        type: 'main',
      },
      {
        reading: '華氏',
        kana: 'かし',
        meaning: ['Fahrenheit'],
        sentence: '華氏で測ります。',
        type: 'secondary',
      },
      {
        reading: '氏神',
        kana: 'うじがみ',
        meaning: ['Guardian God'],
        sentence: '氏神にお参りします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '紙',
    onyomi: ['し'],
    kunyomi: ['かみ', 'がみ'],
    meaning: ['Paper'],
    examples: [
      {
        reading: '紙',
        kana: 'かみ',
        meaning: ['Paper'],
        sentence: '紙を使います。',
        type: 'main',
      },
      {
        reading: '手紙',
        kana: 'てがみ',
        meaning: ['Letter'],
        sentence: '手紙を書きます。',
        type: 'main',
      },
      {
        reading: '表紙',
        kana: 'ひょうし',
        meaning: ['Cover page'],
        sentence: '表紙を見ます。',
        type: 'secondary',
      },
      {
        reading: '紙幣',
        kana: 'しへい',
        meaning: ['Bill (Paper money)'],
        sentence: '紙幣を使います。',
        type: 'secondary',
      },
      {
        reading: '和紙',
        kana: 'わし',
        meaning: ['Japanese paper'],
        sentence: '和紙を使います。',
        type: 'secondary',
      },
      {
        reading: '紙くず',
        kana: 'かみくず',
        meaning: ['Waste paper'],
        sentence: '紙くずを捨てます。',
        type: 'main',
      },
      {
        reading: '折り紙',
        kana: 'おりがみ',
        meaning: ['Origami'],
        sentence: '折り紙を折ります。',
        type: 'main',
      },
      {
        reading: '紙コップ',
        kana: 'かみこっぷ',
        meaning: ['Paper cup'],
        sentence: '紙コップを使います。',
        type: 'secondary',
      },
    ],
  },
]