// Copilot, please, on sentences, create long sentences with a lot of context, complex, with N4/N3 grammar
export const KANJI_YDC_LESSON_16: Array<KanjiYDC> = [
  {
    kanji: '運',
    onyomi: ['うん'],
    kunyomi: ['はこ'],
    meaning: ['Carry', 'Transport', 'Luck'],
    examples: [
      {
        reading: '運ぶ',
        kana: 'はこぶ',
        meaning: ['To carry', 'To transport'],
        sentence: '昨日は大雨で電車が止まってしまったので、重たい荷物を駅から家まで自分で運ばなければならず、とても疲れました。',
        type: 'main',
      },
      {
        reading: '運転',
        kana: 'うんてん',
        meaning: ['Driving'],
        sentence: '運転免許を取るために、毎週土曜日に教習所に通っています。',
        type: 'main',
      },
      {
        reading: '運転手',
        kana: 'うんてんしゅ',
        meaning: ['Driver'],
        sentence: '運転手の仕事は、長時間運転することが多くて大変ですが、やりがいがあります。',
        type: 'main',
      },
      {
        reading: '運動',
        kana: 'うんどう',
        meaning: ['Exercise'],
        sentence: '毎朝、ジョギングをして運動不足を解消するように心がけています。',
        type: 'main',
      },
      {
        reading: '運がいい',
        kana: 'うんがいい',
        meaning: ['Lucky'],
        sentence: '今日は運がいい日で、思いがけないプレゼントをもらいました。',
        type: 'secondary',
      },
      {
        reading: '不運',
        kana: 'ふうん',
        meaning: ['Unlucky'],
        sentence: '不運な出来事が続いて、少し落ち込んでいますが、前向きに考えるようにしています。',
        type: 'secondary',
      },
      {
        reading: '運命',
        kana: 'うんめい',
        meaning: ['Fate', 'Destiny'],
        sentence: '運命を信じて、出会った人との縁を大切にしています。',
        type: 'secondary',
      },
      {
        reading: '運賃',
        kana: 'うんちん',
        meaning: ['Fare'],
        sentence: '運賃は現金で支払います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '動',
    onyomi: ['どう'],
    kunyomi: ['うご'],
    meaning: ['Move', 'Motion'],
    examples: [
      {
        reading: '動く',
        kana: 'うごく',
        meaning: ['To move'],
        sentence: 'このパソコンは長い間使っていなかったから、電源を入れてもなかなか動かなくて、修理に出すしかなかった。',
        type: 'main',
      },
      {
        reading: '運動',
        kana: 'うんどう',
        meaning: ['Exercise'],
        sentence: '毎日運動することは健康に良いとされていますが、忙しい日常生活の中で時間を作るのが難しいこともあります。',
        type: 'main',
      },
      {
        reading: '自動車',
        kana: 'じどうしゃ',
        meaning: ['Automobile'],
        sentence: '自動車の運転は、特に初めての人にとっては緊張することが多いですが、慣れれば楽しくなります。',
        type: 'main',
      },
      {
        reading: '動物',
        kana: 'どうぶつ',
        meaning: ['Animal'],
        sentence: '動物園では、さまざまな動物を見ることができて、特に子供たちにとっては楽しい体験になります。',
        type: 'main',
      },
      {
        reading: '活動',
        kana: 'かつどう',
        meaning: ['Activity'],
        sentence: '地域の活動に参加することで、地元の人々とのつながりを深めることができると思います。',
        type: 'secondary',
      },
      {
        reading: '感動する',
        kana: 'かんどうする',
        meaning: ['To be moved', 'To be touched'],
        sentence: '映画を見て感動することは、心に残る素晴らしい体験です。',
        type: 'secondary',
      },
      {
        reading: '動詞',
        kana: 'どうし',
        meaning: ['Verb'],
        sentence: '日本語の文法を学ぶ上で、動詞の使い方は非常に重要です。',
        type: 'main',
      },
      {
        reading: '自動ドア',
        kana: 'じどうドア',
        meaning: ['Automatic door'],
        sentence: '自動ドアは、手を使わずに出入りできる便利な設備です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '止',
    onyomi: ['し'],
    kunyomi: ['と'],
    meaning: ['Stop'],
    examples: [
      {
        reading: '止まる',
        kana: 'とまる',
        meaning: ['To stop'],
        sentence: 'バスが止まると、乗客たちは一斉に降りていきました。',
        type: 'main',
      },
      {
        reading: '止める',
        kana: 'とめる',
        meaning: ['To stop', 'To turn off'],
        sentence: '運転中に電話がかかってきたので、車を止めてから出ることにしました。',
        type: 'main',
      },
      {
        reading: '中止',
        kana: 'ちゅうし',
        meaning: ['Cancellation'],
        sentence: '悪天候のため、イベントは中止になりました。',
        type: 'main',
      },
      {
        reading: '禁止する',
        kana: 'きんしする',
        meaning: ['To prohibit'],
        sentence: '公園内での喫煙は禁止されていますので、注意してください。',
        type: 'main',
      },
      {
        reading: '停止する',
        kana: 'ていしする',
        meaning: ['To come to a stand'],
        sentence: '信号が赤になったので、車は停止しました。',
        type: 'secondary',
      },
      {
        reading: '廃止する',
        kana: 'はいしする',
        meaning: ['To abolish'],
        sentence: 'この法律は、社会の変化に伴い廃止されることになりました。',
        type: 'secondary',
      },
      {
        reading: '防止する',
        kana: 'ぼうしする',
        meaning: ['To prevent'],
        sentence: '感染症の防止には、手洗いやうがいが効果的です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '歩',
    onyomi: ['ほ', 'ぽ','ふ', 'ぶ'],
    kunyomi: ['ある', 'あゆ'],
    meaning: ['Walk', 'Step'],
    examples: [
      {
        reading: '歩く',
        kana: 'あるく',
        meaning: ['To walk'],
        sentence: '地図を見ながら歩いていたけど、道に迷ってしまって、気がついたら全く知らない公園に着いていた。',
        type: 'main',
      },
      {
        reading: '散歩する',
        kana: 'さんぽする',
        meaning: ['To take a walk'],
        sentence: '毎朝、近くの公園を散歩することが日課になっています。',
        type: 'main',
      },
      {
        reading: '一歩',
        kana: 'いっぽ',
        meaning: ['One step'],
        sentence: '一歩ずつ進むことが大切だと思います。',
        type: 'main',
      },
      {
        reading: '進歩',
        kana: 'しんぽ',
        meaning: ['Progress'],
        sentence: '技術の進歩は目覚ましいものがあります。',
        type: 'secondary',
      },
      {
        reading: '歩道',
        kana: 'ほどう',
        meaning: ['Sidewalk'],
        sentence: '歩道を歩くときは、周りに注意を払うことが大切です。',
        type: 'main',
      },
      {
        reading: '歩み',
        kana: 'あゆみ',
        meaning: ['walking'],
        sentence: '彼の歩みは、私たちにとって大きな励みになります。',
        type: 'secondary',
      },
      {
        reading: '歩合',
        kana: 'ぶあい',
        meaning: ['Commission'],
        sentence: '営業の仕事は歩合制なので、頑張った分だけ給料が増えます。',
        type: 'secondary',
      },
      {
        reading: '歩行者',
        kana: 'ほこうしゃ',
        meaning: ['Pedestrian'],
        sentence: '歩行者専用の信号が点滅しているときは、絶対に渡らないでください。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '使',
    onyomi: ['し'],
    kunyomi: ['つか'],
    meaning: ['Use'],
    examples: [
      {
        reading: '使う',
        kana: 'つかう',
        meaning: ['To use'],
        sentence: 'このアプリは便利だけど、使い方を間違えると個人情報が漏れる可能性があるから、十分に注意して使ってください。',
        type: 'main',
      },
      {
        reading: '大使館',
        kana: 'たいしかん',
        meaning: ['Embassy'],
        sentence: '大使館に行くと、外国の文化や習慣について学ぶことができるので、とても興味深いです。',
        type: 'main',
      },
      {
        reading: '大使',
        kana: 'たいし',
        meaning: ['Ambassador'],
        sentence: '大使は国と国との関係を深めるために重要な役割を果たしています。',
        type: 'main',
      },
      {
        reading: '使用中',
        kana: 'しようちゅう',
        meaning: ['In use'],
        sentence: 'このトイレは使用中なので、他のトイレを利用してください。',
        type: 'main',
      },
      {
        reading: '使命',
        kana: 'しめい',
        meaning: ['Mission'],
        sentence: '私たちの使命は、地域社会に貢献することです。',
        type: 'secondary',
      },
      {
        reading: '天使',
        kana: 'てんし',
        meaning: ['Angel'],
        sentence: '天使のような優しい心を持った人になりたいです。',
        type: 'main',
      },
      {
        reading: 'お使い',
        kana: 'おつかい',
        meaning: ['Errand'],
        sentence: 'お使いを頼まれたので、近くのコンビニに行ってきます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '送',
    onyomi: ['そう'],
    kunyomi: ['おく'],
    meaning: ['Send', 'Deliver'],
    examples: [
      {
        reading: '送る',
        kana: 'おくる',
        meaning: ['To send', 'To deliver'],
        sentence: '友達に手紙を送るために、郵便局に行きましたが、長い列ができていて、待つのが大変でした。',
        type: 'main',
      },
      {
        reading: '放送',
        kana: 'ほうそう',
        meaning: ['Broadcast'],
        sentence: 'テレビの放送を見ていたら、特別番組が始まるというアナウンスがありました。',
        type: 'secondary',
      },
      {
        reading: '郵送する',
        kana: 'ゆうそうする',
        meaning: ['To send by mail'],
        sentence: '書類を郵送するために、封筒に入れて切手を貼りました。',
        type: 'main',
      },
      {
        reading: '送料',
        kana: 'そうりょう',
        meaning: ['Shipping fee', 'Postage'],
        sentence: 'ネットショッピングで商品を購入したら、送料が無料だったので、とても得した気分になりました。',
        type: 'main',
      },
      {
        reading: '送別会',
        kana: 'そうべつかい',
        meaning: ['Farewell party'],
        sentence: '友達の送別会を開くことになり、みんなでサプライズパーティーを計画しています。',
        type: 'secondary',
      },
      {
        reading: '送信する',
        kana: 'そうしんする',
        meaning: ['To send (an email) (a message)'],
        sentence: 'メールを送信する前に、内容をもう一度確認することが大切です。',
        type: 'main',
      },
      {
        reading: '見送る',
        kana: 'みおくる',
        meaning: ['To see off'],
        sentence: '友達を空港まで見送りに行きましたが、別れが寂しくて涙が出そうになりました。',
        type: 'main',
      },
      {
        reading: '回送電車',
        kana: 'かいそうでんしゃ',
        meaning: ['Out-of-service train'],
        sentence: '回送電車が通過するので、しばらくお待ちください。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '洗',
    onyomi: ['せん'],
    kunyomi: ['あら'],
    meaning: ['Wash'],
    examples: [
      {
        reading: '洗う',  
        kana: 'あらう',
        meaning: ['To wash'],
        sentence: '手を洗うことは、風邪やインフルエンザの予防にとても効果的です。',
        type: 'main',
      },
      {
        reading: 'お手洗い',
        kana: 'おてあらい',
        meaning: ['Restroom'],
        sentence: 'お手洗いは、廊下の突き当たりにあります。',
        type: 'main',
      },
      {
        reading: '洗濯する',
        kana: 'せんたくする',
        meaning: ['To do laundry'],
        sentence: '今日は天気がいいので、洗濯物を外に干すことにしました。',
        type: 'main',
      },
      {
        reading: '洗剤',
        kana: 'せんざい',
        meaning: ['Detergent'],
        sentence: '洗剤を使って、汚れた服をきれいに洗います。',
        type: 'main',
      },
      {
        reading: '洗顔',  
        kana: 'せんがん',
        meaning: ['Wash one\'s face'],
        sentence: '朝起きたら、まず洗顔をしてから朝食を取ります。',
        type: 'secondary',
      },
      {
        reading: '洗礼',  
        kana: 'せんれい',
        meaning: ['Baptism'],
        sentence: '彼女は洗礼を受けて、キリスト教徒になりました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '急',
    onyomi: ['きゅう'],
    kunyomi: ['いそ'],
    meaning: ['Hurry', 'Emergency'],
    examples: [
      {
        reading: '急に',  
        kana: 'きゅうに',
        meaning: ['Suddenly'],
        sentence: '急に雨が降り出したので、傘を持っていなかった私はびしょ濡れになってしまいました。',
        type: 'main',
      },
      {
        reading: '急ぐ',
        kana: 'いそぐ',
        meaning: ['To hurry'],
        sentence: '急いで駅に向かったけれど、電車が出発してしまったので、次の電車を待つことになりました。',
        type: 'main',
      },
      {
        reading: '急行',
        kana: 'きゅうこう',
        meaning: ['Express train'],
        sentence: '急行電車は、各駅停車よりも早く目的地に着くので、時間を節約できます。',
        type: 'main',
      },
      {
        reading: '特急',
        kana: 'とっきゅう',
        meaning: ['Limited express (Super express train)'],
        sentence: '特急電車は、主要な駅だけに停車するので、旅行の際に便利です。',
        type: 'main',
      },
      {
        reading: '至急',
        kana: 'しきゅう',
        meaning: ['Urgently', 'Without delay'],
        sentence: '至急の用事があるので、少し早めに帰ります。',
        type: 'main',
      },
      {
        reading: '緊急',
        kana: 'きんきゅう',
        meaning: ['Emergency'],
        sentence: '緊急事態が発生した場合は、すぐに避難してください。',
        type: 'main',
      },
      {
        reading: '救急車',
        kana: 'きゅうきゅうしゃ',
        meaning: ['Ambulance'],
        sentence: '救急車が来るまで、応急処置を続けてください。',
        type: 'main',
      },
      {
        reading: '急用',
        kana: 'きゅうよう',
        meaning: ['Urgent matter'],
        sentence: '急用ができたので、予定を変更しなければなりませんでした。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '開',
    onyomi: ['かい'],
    kunyomi: ['あ', 'ひら'],
    meaning: ['Open'],
    examples: [
      {
        reading: '開く',
        kana: 'あく',
        meaning: ['(Something) opens'],
        sentence: 'ドアが開くと、外の景色が見えました。',
        type: 'main',
      },
      {
        reading: '開ける',
        kana: 'あける',
        meaning: ['To open (something)'],
        sentence: '窓を開けると、涼しい風が入ってきました。',
        type: 'main',
      },
      {
        reading: '開く',
        kana: 'ひらく',
        meaning: ['To open (something)'],
        sentence: '本を開くと、面白い物語が始まりました。',
        type: 'main',
      },
      {
        reading: '開始する',
        kana: 'かいしする',
        meaning: ['To start (Something)'],
        sentence: '会議は午後2時に開始される予定です。',
        type: 'main',
      },
      {
        reading: '開店',
        kana: 'かいてん',
        meaning: ['Opening of a store'],
        sentence: '新しいレストランが開店しました。',
        type: 'main',
      },
      {
        reading: '公開',
        kana: 'こうかい',
        meaning: ['Public release', 'Open to the public'],
        sentence: '映画の公開日が決まりました。',
        type: 'main',
      },
      {
        reading: '開会式',
        kana: 'かいかいしき',
        meaning: ['Opening ceremony'],
        sentence: 'オリンピックの開会式は、世界中から注目されています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '閉',
    onyomi: ['へい'],
    kunyomi: ['し', 'と'],
    meaning: ['Close'],
    examples: [ 
      {
        reading: '閉まる',
        kana: 'しまる',
        meaning: ['(Something) closes'],
        sentence: 'ドアが閉まる音が聞こえました。',
        type: 'main',
      },
      {
        reading: '閉める',
        kana: 'しめる',
        meaning: ['To close (something)'],
        sentence: '窓を閉めると、外の音が聞こえなくなりました。',
        type: 'main',
      },
      {
        reading: '閉じる',
        kana: 'とじる',
        meaning: ['To close (something)'],
        sentence: '本を閉じると、物語の余韻に浸ることができました。',
        type: 'main',
      },
      {
        reading: '閉会式',
        kana: 'へいかいしき',
        meaning: ['Closing ceremony'],
        sentence: 'オリンピックの閉会式は、感動的な瞬間がたくさんありました。',
        type: 'main',
      },
      {
        reading: '閉店',
        kana: 'へいてん',
        meaning: ['Closing of a store'],
        sentence: 'お店の閉店時間が近づいてきました。',
        type: 'main',
      },
      {
        reading: '閉鎖',
        kana: 'へいさ',
        meaning: ['Closure'],
        sentence: 'この道は工事のため、閉鎖されています。',
        type: 'secondary',
      },
      {
        reading: '閉口する',
        kana: 'へいこうする',
        meaning: ['To be annoyed'],
        sentence: '彼の話には閉口してしまいました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '押',
    onyomi: ['おう'],
    kunyomi: ['お'],
    meaning: ['Push', 'Press'],
    examples: [
      {
        reading: '押す',
        kana: 'おす',
        meaning: ['To push', 'To press'],
        sentence: 'ボタンを押すと、電源が入ります。',
        type: 'main',
      },
      {
        reading: '押し入れ',
        kana: 'おしいれ',
        meaning: ['Closet'],
        sentence: '押し入れの中には、古い布団がしまってあります。',
        type: 'main',
      },
      {
        reading: '押さえる',
        kana: 'おさえる',
        meaning: ['To hold down', 'To pin down'],
        sentence: '風で飛ばされないように、紙を押さえておきます。',
        type: 'secondary',
      },
      {
        reading: '押し出す',
        kana: 'おしだす',
        meaning: ['To push out'],
        sentence: '人混みの中で、押し出されてしまいました。',
        type: 'main',
      },
      {
        reading: '押収する',
        kana: 'おうしゅうする',
        meaning: ['To confiscate', 'To seize'],
        sentence: '警察は違法な物品を押収しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '引',
    onyomi: ['いん'],
    kunyomi: ['ひ', 'び'],
    meaning: ['Pull'],
    examples: [
      {
        reading: '引く',
        kana: 'ひく',
        meaning: ['To pull'],
        sentence: 'ドアを引くと、部屋の中に入ることができます。',
        type: 'main',
      },
      {
        reading: '引き出し',
        kana: 'ひきだし',
        meaning: ['Drawer'],
        sentence: '引き出しの中には、たくさんの書類が入っています。',
        type: 'main',
      },
      {
        reading: '引き出す',
        kana: 'ひきだす',
        meaning: ['To withdraw'],
        sentence: 'お金を引き出すために、ATMに行きました。',
        type: 'main',
      },
      {
        reading: '引っ越す',
        kana: 'ひっこす',
        meaning: ['To move out (house)'],
        sentence: '新しい家に引っ越す準備をしています。',
        type: 'main',
      },
      {
        reading: '引き分け',
        kana: 'ひきわけ',
        meaning: ['Draw', 'Tie'],
        sentence: '試合は引き分けに終わりました。',
        type: 'secondary',
      },
      {
        reading: '割引 (割り引き)',
        kana: 'わりびき',
        meaning: ['Discount'],
        sentence: 'この商品は割引セール中です。',
        type: 'main',
      },
      {
        reading: '引用',
        kana: 'いんよう',
        meaning: ['Quotation'],
        sentence: '本の中から引用を使うときは、出典を明記することが大切です。',
        type: 'secondary',
      },
      {
        reading: '引力',
        kana: 'いんりょく',
        meaning: ['Gravity'],
        sentence: '地球の引力は、私たちを地面に引き寄せています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '思',
    onyomi: ['し'],
    kunyomi: ['おも'],
    meaning: ['Think', 'Consider'],
    examples: [
      {
        reading: '思う',
        kana: 'おもう',
        meaning: ['To think'],
        sentence: '彼のことを思うと、心が温かくなります。',
        type: 'main',
      },
      {
        reading: '思い出す',
        kana: 'おもいだす',
        meaning: ['To remember'],
        sentence: '昔のことを思い出すと、懐かしい気持ちになります。',
        type: 'main',
      },
      {
        reading: '思い出',
        kana: 'おもいで',
        meaning: ['Memory'],
        sentence: '旅行の思い出をアルバムにまとめました。',
        type: 'main',
      },
      {
        reading: '思いがけない',
        kana: 'おもいがけない',
        meaning: ['Unexpected'],
        sentence: '思いがけないプレゼントをもらって、驚きました。',
        type: 'main',
      },
      {
        reading: '思いきり',
        kana: 'おもいきり',
        meaning: ['To one\'s heart\'s content'],
        sentence: '思いきり遊んで、楽しい時間を過ごしました。',
        type: 'secondary',
      },
      {
        reading: '不思議な',
        kana: 'ふしぎな',
        meaning: ['Mysterious'],
        sentence: '不思議な出来事が起こりました。',
        type: 'secondary',
      },
      {
        reading: '思想',
        kana: 'しそう',
        meaning: ['Thought', 'Idea'],
        sentence: '彼の思想は、私たちに大きな影響を与えました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '知',
    onyomi: ['ち'],
    kunyomi: ['し'],
    meaning: ['Know'],
    examples: [
      {
        reading: '知る',
        kana: 'しる',
        meaning: ['To know'],
        sentence: '彼のことを知っている人は少ないです。',
        type: 'main',
      },
      {
        reading: '知らせる',
        kana: 'しらせる',
        meaning: ['To inform', 'To notify'],
        sentence: '新しい情報を知らせるために、メールを送りました。',
        type: 'main',
      },
      {
        reading: '知り合い',
        kana: 'しりあい',
        meaning: ['Acquaintance'],
        sentence: '彼は私の知り合いです。',
        type: 'secondary',
      },
      {
        reading: '知人',
        kana: 'ちじん',
        meaning: ['Acquaintance'],
        sentence: '知人に会うために、東京に行きました。',
        type: 'secondary',
      },
      {
        reading: '承知する',
        kana: 'しょうちする',
        meaning: ['To consent', 'To agree'],
        sentence: 'その件については、承知しました。',
        type: 'main',
      },
      {
        reading: '知識',
        kana: 'ちしき',
        meaning: ['Knowledge'],
        sentence: '知識を深めるために、本を読むことが大切です。',
        type: 'secondary',
      },
      {
        reading: '知性',
        kana: 'ちせい',
        meaning: ['Intelligence'],
        sentence: '彼女は知性が高く、さまざまな分野に詳しいです。',
        type: 'secondary',
      },
      {
        reading: '知事',
        kana: 'ちじ',
        meaning: ['Governor'],
        sentence: '知事は地域の発展に貢献するために、さまざまな政策を実施しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '考',
    onyomi: ['こう'],
    kunyomi: ['かんが'],
    meaning: ['Think', 'Consider', 'Idea'],
    examples: [
      {
        reading: '考える',
        kana: 'かんがえる',
        meaning: ['To think', 'To consider'],
        sentence: '問題を解決するために、いろいろな方法を考えています。',
        type: 'main',
      },
      {
        reading: '考え',
        kana: 'かんがえ',
        meaning: ['Thought', 'Idea'],
        sentence: '彼の考えはとても興味深いです。',
        type: 'main',
      },
      {
        reading: '考え方',
        kana: 'かんがえかた',
        meaning: ['Way of thinking'],
        sentence: '考え方を変えることで、問題が解決することがあります。',
        type: 'main',
      },
      {
        reading: '参考',
        kana: 'さんこう',
        meaning: ['Reference'],
        sentence: 'この本は、研究の参考になります。',
        type: 'main',
      },
      {
        reading: '考慮する',
        kana: 'こうりょする',
        meaning: ['To consider'],
        sentence: '彼の意見を考慮して、決定を下しました。',
        type: 'secondary',
      },
      {
        reading: '考古学',
        kana: 'こうこがく',
        meaning: ['Archaeology'],
        sentence: '考古学の研究は、古代の文化を理解する手助けになります。',
        type: 'secondary',
      },
      {
        reading: '参考書',
        kana: 'さんこうしょ',
        meaning: ['Reference book'],
        sentence: 'この参考書は、試験勉強に役立ちます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '死',
    onyomi: ['し'],
    kunyomi: ['し'],
    meaning: ['Death'],
    examples: [
      {
        reading: '死ぬ',
        kana: 'しぬ',
        meaning: ['To die'],
        sentence: '死んだらどうするんだ？',
        type: 'main',
      },
      {
        reading: '死',
        kana: 'し',
        meaning: ['Death'],
        sentence: '死は避けられない現実です。',
        type: 'secondary',
      },
      {
        reading: '死体',
        kana: 'したい',
        meaning: ['Corpse', 'Dead body'],
        sentence: '死体が見つかりました。',
        type: 'main',
      },
      {
        reading: '必死',
        kana: 'ひっし',
        meaning: ['Desperate'],
        sentence: '彼は必死に助けを求めていました。',
        type: 'main',
      },
      {
        reading: '死亡',
        kana: 'しぼう',
        meaning: ['Death'],
        sentence: '事故による死亡者が増えています。',
        type: 'main',
      },
      {
        reading: '安楽死',
        kana: 'あんらくし',
        meaning: ['Euthanasia'],
        sentence: '医師として、患者が安楽死を望んでいると聞いたとき、自分の信念と向き合わなければならなかった。',
        type: 'main',
      },
      {
        reading: '死者',
        kana: 'ししゃ',
        meaning: ['Deceased person'],
        sentence: '死者の冥福を祈ります。',
        type: 'secondary',
      },
      {
        reading: '死語',
        kana: 'しご',
        meaning: ['Dead language'],
        sentence: 'この言葉は死語になってしまった。',
        type: 'secondary',
      },
    ],
  },
]