export const KANJI_YDC_LESSON_7: Array<KanjiYDC> = [
  {
    kanji: '入',
    onyomi: ['にゅう'],
    kunyomi: ['はい', 'い'],
    meaning: ['Enter'],
    examples: [
      {
        reading: '入る',
        kana: 'はいる',
        meaning: ['To enter'],
        sentence: '部屋に入ってください。',
        type: 'main',
      },
      {
        reading: '入れる',
        kana: 'いれる',
        meaning: ['To put in'],
        sentence: 'コーヒーを入れます。',
        type: 'main',
      },
      {
        reading: '入り口',
        kana: 'いりぐち',
        meaning: ['Entrance'],
        sentence: '入り口に行きます。',
        type: 'main',
      },
      {
        reading: '入学する',
        kana: 'にゅうがくする',
        meaning: ['To enter a school'],
        sentence: '大学に入学します。',
        type: 'main',
      },
      {
        reading: '入院する',
        kana: 'にゅういんする',
        meaning: ['To be hospitalized'],
        sentence: '入院しています。',
        type: 'main',
      },
      {
        reading: '気に入る',
        kana: 'きにいる',
        meaning: ['To be pleased with', 'To be fond of'],
        sentence: 'この服が気に入りました。',
        type: 'secondary',
      },
      {
        reading: '輸入',
        kana: 'ゆにゅう',
        meaning: ['Import'],
        sentence: '輸入品があります。',
        type: 'secondary',
      },
      {
        reading: '収入',
        kana: 'しゅうにゅう',
        meaning: ['Income'],
        sentence: '収入が増えました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '出',
    onyomi: ['しゅつ', 'しゅっ', 'すい'],
    kunyomi: ['で', 'だ'],
    meaning: ['Exit', 'Leave'],
    examples: [
      {
        reading: '出る',
        kana: 'でる',
        meaning: ['To leave'],
        sentence: '部屋を出てください。',
        type: 'main',
      },
      {
        reading: '出かける',
        kana: 'でかける',
        meaning: ['To go out'],
        sentence: '友達と出かけます。',
        type: 'main',
      },
      {
        reading: '出す',
        kana: 'だす',
        meaning: ['To take out', 'To hand in'],
        sentence: '宿題を出しってください。',
        type: 'main',
      },
      {
        reading: '出口',
        kana: 'でぐち',
        meaning: ['Exit'],
        sentence: '出口に行きます。',
        type: 'main',
      },
      {
        reading: '思い出す',
        kana: 'おもいだす',
        meaning: ['To remember'],
        sentence: '思い出してください。',
        type: 'main',
      },
      {
        reading: '輸出',
        kana: 'ゆしゅつ',
        meaning: ['Export'],
        sentence: '輸出品があります。',
        type: 'secondary',
      },
      {
        reading: '出席',
        kana: 'しゅっせき',
        meaning: ['Attendance'],
        sentence: '出席してください。',
        type: 'secondary',
      },
      {
        reading: '提出する',
        kana: 'ていしゅつする',
        meaning: ['To submit'],
        sentence: '提出してください。',
        type: 'secondary',
      }
    ],
  },
  {
    kanji: '市',
    onyomi: ['し'],
    kunyomi: ['いち'],
    meaning: ['City', 'Market'],
    examples: [
      {
        reading: '市長',
        kana: 'しちょう',
        meaning: ['Mayor'],
        sentence: '市長がいます。',
        type: 'main',
      },
      {
        reading: '横浜市',
        kana: 'よこはまし',
        meaning: ['Yokohama city'],
        sentence: '横浜市に住んでいます。',
        type: 'main',
      },
      {
        reading: '市民',
        kana: 'しみん',
        meaning: ['Citizen'],
        sentence: 'つくば市の市民。',
        type: 'secondary',
      },
      {
        reading: '市役所',
        kana: 'しやくしょ',
        meaning: ['City hall'],
        sentence: '市役所に行きます。',
        type: 'main',
      },
      {
        reading: '都市',
        kana: 'とし',
        meaning: ['Metropolis'],
        sentence: '都市部に住んでいます。',
        type: 'secondary',
      },
      {
        reading: '市場',
        kana: 'いちば',
        meaning: ['Market (Stocks)'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '市場',
        kana: 'いちば',
        meaning: ['Market (Goods)'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '朝市',
        kana: 'あさいち',
        meaning: ['Morning market'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '町',
    onyomi: ['ちょう'],
    kunyomi: ['まち'],
    meaning: ['Town'],
    examples: [
      {
        reading: '町',
        kana: 'まち',
        meaning: ['Town'],
        sentence: '町に住んでいます。',
        type: 'main',
      },
      {
        reading: '北山町',
        kana: 'きたやまちょう',
        meaning: ['Kitayama town'],
        sentence: '北山町に住んでいます。',
        type: 'secondary',
      },
      {
        reading: '町長',
        kana: 'ちょうちょう',
        meaning: ['Town mayor'],
        sentence: '町長です。',
        type: 'secondary',
      },
      {
        reading: '町民',
        kana: 'ちょうみん',
        meaning: ['Town people'],
        sentence: '町民です。',
        type: 'secondary',
      },
      {
        reading: '城下町',
        kana: 'じょうかちょう',
        meaning: ['Castle town'],
        sentence: '城下町に行きます。',
        type: 'secondary',
      },
      {
        reading: '港町',
        kana: 'みなとちょう',
        meaning: ['Port town'],
        sentence: '港町に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '村',
    onyomi: ['そん'],
    kunyomi: ['むら'],
    meaning: ['Village'],
    examples: [
      {
        reading: '村',
        kana: 'むら',
        meaning: ['Village'],
        sentence: '村に住んでいます。',
        type: 'main',
      },
      {
        reading: '田村さん',
        kana: 'たむらさん',
        meaning: ['Mr. Tamura'],
        sentence: '田村さんに会いました。',
        type: 'secondary',
      },
      {
        reading: '村長',
        kana: 'そんちょう',
        meaning: ['Village headman'],
        sentence: '村長です。',
        type: 'secondary',
      },
      {
        reading: '村民',
        kana: 'そんみん',
        meaning: ['Village people'],
        sentence: '村民です。',
        type: 'secondary',
      },
      {
        reading: '農村',
        kana: 'のうそん',
        meaning: ['Farm village'],
        sentence: '農村に行きます。',
        type: 'secondary',
      },
      {
        reading: '市町村',
        kana: 'しちょうそん',
        meaning: ['Municipality', 'City, town, and village'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '漁村',
        kana: 'りょうそん',
        meaning: ['Fishing village'],
        sentence: '漁村に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '雨',
    onyomi: ['う'],
    kunyomi: ['あめ', 'あま'],
    meaning: ['Rain'],
    examples: [
      {
        reading: '雨',
        kana: 'あめ',
        meaning: ['Rain'],
        sentence: '雨が降っています。',
        type: 'main',
      },
      {
        reading: '梅雨',
        kana: 'つゆ・ばいう',
        meaning: ['Rainy season (of early summer)'],
        sentence: '梅雨が明けました。',
        type: 'secondary',
      },
      {
        reading: '雨季',
        kana: 'うき',
        meaning: ['Rainy season'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '大雨',
        kana: 'おおあめ',
        meaning: ['Heavy rain'],
        sentence: '大雨が降っています。',
        type: 'secondary',
      },
      {
        reading: '暴風雨',
        kana: 'ぼうふうう',
        meaning: ['Windy rainstorm', 'Windstorm'],
        sentence: '暴風雨が来ます。',
        type: 'secondary',
      },
      {
        reading: '雨水',
        kana: 'あまみず',
        meaning: ['Rainwater'],
        sentence: '雨水が溜まっています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '電',
    onyomi: ['でん'],
    kunyomi: [],
    meaning: ['Electricity'],
    examples: [
      {
        reading: '電気',
        kana: 'でんき',
        meaning: ['Electricity'],
        sentence: '電気が消えました。',
        type: 'main',
      },
      {
        reading: '電車',
        kana: 'でんしゃ',
        meaning: ['Train'],
        sentence: '電車に乗ります。',
        type: 'main',
      },
      {
        reading: '電話',
        kana: 'でんわ',
        meaning: ['Telephone'],
        sentence: '電話をかけます。',
        type: 'main',
      },
      {
        reading: '電力',
        kana: 'でんりょく',
        meaning: ['Electric power'],
        sentence: '電力があります。',
        type: 'secondary',
      },
      {
        reading: '電子',
        kana: 'でんし',
        meaning: ['Electron'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '電池',
        kana: 'でんち',
        meaning: ['Battery'],
        sentence: '電池が切れました。',
        type: 'secondary',
      },
      {
        reading: '停電',
        kana: 'ていでん',
        meaning: ['Power outage', 'Blackout'],
        sentence: '停電しています。',
        type: 'secondary',
      },
      {
        reading: '電源',
        kana: 'でんげん',
        meaning: ['Power source'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '車',
    onyomi: ['しゃ'],
    kunyomi: ['くるま'],
    meaning: ['Car'],
    examples: [
      {
        reading: '車',
        kana: 'くるま',
        meaning: ['Car'],
        sentence: '車を運転します。',
        type: 'main',
      },
      {
        reading: '電車',
        kana: 'でんしゃ',
        meaning: ['Train'],
        sentence: '電車に乗ります。',
        type: 'main',
      },
      {
        reading: '自動車',
        kana: 'じどうしゃ',
        meaning: ['Automobile'],
        sentence: '自動車を運転します。',
        type: 'secondary',
      },
      {
        reading: '自転車',
        kana: 'じてんしゃ',
        meaning: ['Bicycle'],
        sentence: '自転車に乗ります。',
        type: 'secondary',
      },
      {
        reading: '駐車場',
        kana: 'ちゅうしゃじょう',
        meaning: ['Parking lot'],
        sentence: '駐車場に行きます。',
        type: 'secondary',
      },
      {
        reading: '救急車',
        kana: 'きゅうきゅうしゃ',
        meaning: ['Ambulance'],
        sentence: '救急車が来ました。',
        type: 'secondary',
      },
      {
        reading: '車いす',
        kana: 'くるまいす',
        meaning: ['Wheelchair'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '馬',
    onyomi: ['ば'],
    kunyomi: ['うま', 'ま'],
    meaning: ['Horse'],
    examples: [
      {
        reading: '馬',
        kana: 'うま',
        meaning: ['Horse'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '子馬',
        kana: 'こうま',
        meaning: ['Pony'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '馬小屋',
        kana: 'うまごや',
        meaning: ['Stable'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '馬車',
        kana: 'ばしゃ',
        meaning: ['Horse-drawn carriage'],
        sentence: '馬車に乗ります。',
        type: 'secondary',
      },
      {
        reading: '乗馬',
        kana: 'じょうば',
        meaning: ['Horseback riding'],
        sentence: '乗馬に行きます。',
        type: 'secondary',
      },
      {
        reading: '競馬',
        kana: 'けいば',
        meaning: ['Horse racing'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '馬鹿',
        kana: 'ばか',
        meaning: ['Fool', 'Idiot'],
        sentence: '馬鹿！',
        type: 'main',
      },
    ],
  },
  {
    kanji: '駅',
    onyomi: ['えき'],
    kunyomi: [],
    meaning: ['Station'],
    examples: [ 
      {
        reading: '駅',
        kana: '駅',
        meaning: ['Station'],
        sentence: '戸部駅',
        type: 'main',
      },
      {
        reading: '東京駅',
        kana: 'とうきょうえき',
        meaning: ['Tokyo station'],
        sentence: '東京駅。',
        type: 'main',
      },
      {
        reading: '駅員',
        kana: 'えきいん',
        meaning: ['Station attendant'],
        sentence: '駅員です。',
        type: 'main',
      },
      {
        reading: '駅前',
        kana: 'えきまえ',
        meaning: ['In front of the station'],
        sentence: '駅前に会いましょう。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '社',
    onyomi: ['しゃ', 'じゃ'],
    kunyomi: ['やしろ'],
    meaning: ['Company', 'Shrine'],
    examples: [
      {
        reading: '会社',
        kana: 'かいしゃ',
        meaning: ['Company'],
        sentence: '電車で会社へ来た。',
        type: 'main',
      },
      {
        reading: '社会',
        kana: 'しゃかい',
        meaning: ['Society'],
        sentence: '社会に出る。',
        type: 'main',
      },
      {
        reading: '社長',
        kana: 'しゃちょう',
        meaning: ['Company president'],
        sentence: '社長です。',
        type: 'main',
      },
      {
        reading: '神社',
        kana: 'じんじゃ',
        meaning: ['Shrine'],
        sentence: '神社に行く。',
        type: 'secondary',
      },
      {
        reading: '社会学',
        kana: 'しゃかいがく',
        meaning: ['Sociology'],
        sentence: '社会学を勉強する。',
        type: 'secondary',
      },
      {
        reading: '社会主義',
        kana: 'しゃかいしゅぎ',
        meaning: ['Socialism'],
        sentence: '社会主義を信じる。',
        type: 'secondary',
      },
      {
        reading: '社',
        kana: 'やしろ',
        meaning: ['Shrine'],
        sentence: '社に行く。',
        type: 'secondary',
      },
      {
        reading: '商社',
        kana: 'しょうしゃ',
        meaning: ['Trading company'],
        sentence: '商社に勤める。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '校',
    onyomi: ['こう'],
    kunyomi: [],
    meaning: ['School'],
    examples: [
      {
        reading: '学校',
        kana: 'がっこう',
        meaning: ['School'],
        sentence: '学校に行く。',
        type: 'main',
      },
      {
        reading: '高校',
        kana: 'こうこう',
        meaning: ['High school'],
        sentence: '高校生。',
        type: 'main',
      },
      {
        reading: '中学校',
        kana: 'ちゅうがっこう',
        meaning: ['Middle school', 'Junior high school'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '小学校',
        kana: 'しょうがっこう',
        meaning: ['Elementary school'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '校長',
        kana: 'こうちょう',
        meaning: ['Principal'],
        sentence: '校長です。',
        type: 'main',
      },
      {
        reading: '校舎',
        kana: 'こうしゃ',
        meaning: ['School building'],
        sentence: '校舎に行く。',
        type: 'secondary',
      },
      {
        reading: '校歌',
        kana: 'こうか',
        meaning: ['School song'],
        sentence: '校歌を歌う。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '店',
    onyomi: ['てん'],
    kunyomi: ['みせ'],
    meaning: ['Store', 'Shop'],
    examples: [
      {
        reading: '店',
        kana: 'みせ',
        meaning: ['Store', 'Shop'],
        sentence: '店に行く。',
        type: 'main',
      },
      {
        reading: '喫茶店',
        kana: 'きっさてん',
        meaning: ['Cafe', 'Coffee shop'],
        sentence: '喫茶店に行く。',
        type: 'secondary',
      },
      {
        reading: '店員',
        kana: 'てんいん',
        meaning: ['Store clerk'],
        sentence: '店員です。',
        type: 'main',
      },
      {
        reading: '書店',
        kana: 'しょてん',
        meaning: ['Bookstore'],
        sentence: '書店に行く。',
        type: 'main',
      },
      {
        reading: '売店',
        kana: 'ばいてん',
        meaning: ['Stand', 'Kiosk'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '店長',
        kana: 'てんちょう',
        meaning: ['Store manager'],
        sentence: '店長です。',
        type: 'main',
      },
      {
        reading: '本店',
        kana: 'ほんてん',
        meaning: ['Main store'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '支店',
        kana: 'してん',
        meaning: ['Branch office'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '銀',
    onyomi: ['ぎん'],
    kunyomi: [],
    meaning: ['Silver'],
    examples: [
      {
        reading: '銀行',
        kana: 'ぎんこう',
        meaning: ['Bank'],
        sentence: '銀行にお金を預ける。',
        type: 'main',
      },
      {
        reading: '銀',
        kana: 'ぎん',
        meaning: ['Silver'],
        sentence: '銀の指輪。',
        type: 'secondary',
      },
      {
        reading: '水銀',
        kana: 'すいぎん',
        meaning: ['Mercury'],
        sentence: '水銀の温度計。',
        type: 'secondary',
      },
      {
        reading: '銀色',
        kana: 'ぎんいろ',
        meaning: ['Silver color'],
        sentence: '銀色の車。',
        type: 'secondary',
      },
      {
        reading: '銀河',
        kana: 'ぎんが',
        meaning: ['Galaxy'],
        sentence: '銀河系。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '病',
    onyomi: ['びょう', 'ぺい', 'へい'],
    kunyomi: ['や', 'やまい'],
    meaning: ['Sick', 'Illness'],
    examples: [
      {
        reading: '病気',
        kana: 'びょうき',
        meaning: ['Illness', 'Sickness'],
        sentence: '病気になる。',
        type: 'main',
      },
      {
        reading: '病院',
        kana: 'びょういん',
        meaning: ['Hospital'],
        sentence: '病院に行く。',
        type: 'main',
      },
      {
        reading: '看病する',
        kana: 'かんびょうする',
        meaning: ['To nurse', 'To take care of a sick person'],
        sentence: '母を看病する。',
        type: 'secondary',
      },
      {
        reading: '急病',
        kana: 'きゅうびょう',
        meaning: ['Sudden illness'],
        sentence: '急病になる。',
        type: 'secondary',
      },
      {
        reading: '重病',
        kana: 'じゅうびょう',
        meaning: ['Serious illness'],
        sentence: '重病にかかる。',
        type: 'secondary',
      },
      {
        reading: '病む',
        kana: 'やむ',
        meaning: ['To be ill', 'To get sick'],
        sentence: '心が病んでいる。',
        type: 'secondary',
      },
      {
        reading: '病',
        kana: 'やまい',
        meaning: ['Illness'],
        sentence: '病気になる。',
        type: 'secondary',
      },
      {
        reading: '疾病',
        kana: 'しっぺい',
        meaning: ['Disease'],
        sentence: '疾病にかかる。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '院',
    onyomi: ['いん'],
    kunyomi: [],
    meaning: ['Institution'],
    examples: [
      {
        reading: '病院',
        kana: 'びょういん',
        meaning: ['Hospital'],
        sentence: '病院に行く。',
        type: 'main',
      },
      {
        reading: '入院する',
        kana: 'にゅういんする',
        meaning: ['To be hospitalized'],
        sentence: '入院しています。',
        type: 'main',
      },
      {
        reading: '大学院',
        kana: 'だいがくいん',
        meaning: ['Graduate school'],
        sentence: '大学院に行く。',
        type: 'main',
      },
      {
        reading: '大学院生',
        kana: 'だいがくいんせい',
        meaning: ['Graduate student'],
        sentence: '大学院生です。',
        type: 'main',
      },
      {
        reading: '退院する',
        kana: 'たいいんする',
        meaning: ['To leave the hospital'],
        sentence: '退院します。',
        type: 'secondary',
      },
      {
        reading: '医院',
        kana: 'いいん',
        meaning: ['Clinic'],
        sentence: '医院に行く。',
        type: 'secondary',
      },
      {
        reading: '美容院',
        kana: 'びよういん',
        meaning: ['Beauty salon'],
        sentence: '美容院で髪を切る。',
        type: 'secondary',
      },
    ],
  },
]