export const KANJI_YDC_LESSON_19: Array<KanjiYDC> = [
  {
    kanji: '頭',
    onyomi: ['ず', 'とう', 'と', 'ど'],
    kunyomi: ['あたま', 'かしら'],
    meaning: ['Head'],
    examples: [
      {
        reading: '頭',
        kana: 'あたま',
        meaning: ['Head'],
        sentence: '頭が痛いので、少し休みます。',
        type: 'YDC_main',
      },
      {
        reading: '頭痛',
        kana: 'ずつう',
        meaning: ['Headache'],
        sentence: '頭痛がするので、薬を飲みました。',
        type: 'main',
      },
      {
        reading: '先頭',
        kana: 'せんとう',
        meaning: ['Front', 'Lead'],
        sentence: '先頭に立って、みんなを引っ張ります。',
        type: 'secondary',
      },
      {
        reading: '二頭',
        kana: 'にとう',
        meaning: ['Two (Big animals)'],
        sentence: '二頭の馬がレースをしています。',
        type: 'main',
      },
      {
        reading: '頭脳',
        kana: 'ずのう',
        meaning: ['Brain', 'Intellect'],
        sentence: '頭脳を使って問題を解決します。',
        type: 'secondary',
      },
      {
        reading: '頭文字',
        kana: 'かしらもじ',
        meaning: ['Initials', 'First letter'],
        sentence: '彼の名前の頭文字は「T」です。',
        type: 'main',
      },
      {
        reading: '音頭',
        kana: 'おんど',
        meaning: ['Bond dance song'],
        sentence: '夏祭りで音頭を踊りました。',
        type: 'secondary',
      },
      {
        reading: '店頭',
        kana: 'てんとう',
        meaning: ['Storefront'],
        sentence: '店頭で新商品を見つけました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '顔',
    onyomi: ['がん'],
    kunyomi: ['かお', 'がお'],
    meaning: ['Face'],
    examples: [
      {
        reading: '顔',
        kana: 'かお',
        meaning: ['Face'],
        sentence: '彼女の顔はとても美しいです。',
        type: 'YDC_main',
      },
      {
        reading: '笑顔',
        kana: 'えがお',
        meaning: ['Smile'],
        sentence: '彼はいつも笑顔で接してくれます。',
        type: 'main',
      },
      {
        reading: '洗顔',
        kana: 'せんがん',
        meaning: ['Washing one\'s face'],
        sentence: '朝は洗顔をしてから、顔を整えます。',
        type: 'secondary',
      },
      {
        reading: '顔つき',
        kana: 'かおつき',
        meaning: ['Look on one\'s face'],
        sentence: '彼の顔つきは真剣そのものです。',
        type: 'secondary',
      },
      {
        reading: '似顔絵',
        kana: 'にがおえ',
        meaning: ['Portrait'],
        sentence: '似顔絵を描くのが得意です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '声',
    onyomi: ['せい', 'しょう'],
    kunyomi: ['こえ', 'こわ'],
    meaning: ['Voice'],
    examples: [
      {
        reading: '声',
        kana: 'こえ',
        meaning: ['Voice'],
        sentence: '彼女の声はとても美しいです。',
        type: 'YDC_main',
      },
      {
        reading: '音声学',
        kana: 'おんせいがく',
        meaning: ['Phonetics'],
        sentence: '音声学を学ぶことで、言語の理解が深まります。',
        type: 'secondary',
      },
      {
        reading: '声変わり',
        kana: 'こえがわり',
        meaning: ['The change of one\'s voice'],
        sentence: '思春期に声変わりが起こります。',
        type: 'secondary',
      },
      {
        reading: '擬声語',
        kana: 'ぎせいご',
        meaning: ['Onomatopoeia'],
        sentence: '擬声語は、音を模倣した言葉です。',
        type: 'secondary',
      },
      {
        reading: '声楽',
        kana: 'せいがく',
        meaning: ['Vocal music'],
        sentence: '声楽のレッスンを受けています。',
        type: 'secondary',
      },
      {
        reading: '声優',
        kana: 'せいゆう',
        meaning: ['Voice actor'],
        sentence: '声優の仕事は、アニメやゲームのキャラクターに命を吹き込みます。',
        type: 'secondary',
      },
      {
        reading: '声色',
        kana: 'こわいろ',
        meaning: ['Voice tone'],
        sentence: '彼の声色はとても感情豊かです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '特',
    onyomi: ['とく', 'とっ'],
    kunyomi: [],
    meaning: ['Special'],
    examples: [
      {
        reading: '特別な',
        kana: 'とくべつな',
        meaning: ['Special'],
        sentence: '今日は特別な日なので、パーティーを開きます。',
        type: 'YDC_main',
      },
      {
        reading: '特に',
        kana: 'とくに',
        meaning: ['Especially'],
        sentence: '特に問題はありませんでした。',
        type: 'YDC_main',
      },
      {
        reading: '特急電車',
        kana: 'とっきゅうでんしゃ',
        meaning: ['Limited (Super) express train'],
        sentence: '特急電車は速くて便利です。',
        type: 'main',
      },
      {
        reading: '独特な',
        kana: 'どくとくな',
        meaning: ['Unique'],
        sentence: '彼の独特なスタイルが好きです。',
        type: 'secondary',
      },
      {
        reading: '特色',
        kana: 'とくしょく',
        meaning: ['Characteristic'],
        sentence: 'この地域の特色は、豊かな自然です。',
        type: 'secondary',
      },
      {
        reading: '特徴',
        kana: 'とくちょう',
        meaning: ['Feature', 'Characteristic'],
        sentence: 'この商品の特徴は、使いやすさです。',
        type: 'secondary',
      },
      {
        reading: '特技',
        kana: 'とくぎ',
        meaning: ['Special skill'],
        sentence: '彼の特技はピアノ演奏です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '別',
    onyomi: ['べつ', 'べっ'],
    kunyomi: ['わか'],
    meaning: ['To Separate'],
    examples: [
      {
        reading: '別れる',
        kana: 'わかれる',
        meaning: ['To separate', 'To part'],
        sentence: '友達と別れるのは寂しいです。',
        type: 'YDC_main',
      },
      {
        reading: '特別な',
        kana: 'とくべつな',
        meaning: ['Special'],
        sentence: '今日は特別な日なので、パーティーを開きます。',
        type: 'YDC_main',
      },
      {
        reading: '別に',
        kana: 'べつに',
        meaning: ['Not particularly', 'Not especially'],
        sentence: '別に問題はありません。',
        type: 'YDC_main',
      },
      {
        reading: '別の',
        kana: 'べつの',
        meaning: ['Another', 'Different'],
        sentence: '別の方法を試してみましょう。',
        type: 'YDC_main',
      },
      {
        reading: '別々に',
        kana: 'べつべつに',
        meaning: ['Separately'],
        sentence: '私たちは別々に行動します。',
        type: 'main',
      },
      {
        reading: '性別',
        kana: 'せいべつ',
        meaning: ['Gender', 'Sex'],
        sentence: '性別に関係なく、平等な社会を目指します。',
        type: 'secondary',
      },
      {
        reading: '差別',
        kana: 'さべつ',
        meaning: ['Discrimination'],
        sentence: '差別は許されない行為です。',
        type: 'secondary',
      },
      {
        reading: '別荘',
        kana: 'べっそう',
        meaning: ['Villa', 'Second home'],
        sentence: '夏休みに別荘で過ごす予定です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '竹',
    onyomi: ['ちく'],
    kunyomi: ['たけ'],
    meaning: ['Bamboo'],
    examples: [
      {
        reading: '竹',
        kana: 'たけ',
        meaning: ['Bamboo'],
        sentence: '竹の子は春の味覚です。',
        type: 'YDC_main',
      },
      {
        reading: '竹の子',
        kana: 'たけのこ',
        meaning: ['Bamboo shoot'],
        sentence: '竹の子を使った料理が好きです。',
        type: 'secondary',
      },
      {
        reading: '竹林',
        kana: 'ちくりん',
        meaning: ['Bamboo grove'],
        sentence: '竹林を散歩するのはとてもリラックスできます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '合',
    onyomi: ['ごう', 'がっ', 'かっ'],
    kunyomi: ['あ'],
    meaning: ['To fit', 'To match'],
    examples: [
      {
        reading: '合う',  
        kana: 'あう',
        meaning: ['To fit', 'To match'],
        sentence: 'この服は私に合います。',
        type: 'YDC_main',
      },
      {
        reading: '試合',
        kana: 'しあい',
        meaning: ['Match', 'Game'],
        sentence: 'サッカーの試合を観戦しました。',
        type: 'YDC_main',
      },
      {
        reading: '間に合う',
        kana: 'まにあう',
        meaning: ['To be in time'],
        sentence: '電車に間に合うように急ぎます。',
        type: 'YDC_main',
      },
      {
        reading: '都合',
        kana: 'つごう',
        meaning: ['Convenience', 'Circumstances'],
        sentence: '都合が悪いので、今日は行けません。',
        type: 'main',
      },
      {
        reading: '場合',  
        kana: 'ばあい',
        meaning: ['Case', 'Situation'],
        sentence: '緊急の場合は、すぐに連絡してください。',
        type: 'main',
      },
      {
        reading: '似合う',  
        kana: 'にあう',
        meaning: ['To suit', 'To look good on'],
        sentence: 'その服はあなたに似合います。',
        type: 'main',
      },
      {
        reading: '付き合う',  
        kana: 'つきあう',
        meaning: ['To associate with', 'To date'],
        sentence: '彼と付き合うことになりました。',
        type: 'main',
      },
      {
        reading: '合宿',  
        kana: 'がっしゅく',
        meaning: ['Training camp'],
        sentence: '夏休みに合宿に参加します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '答',
    onyomi: ['とう'],
    kunyomi: ['こた'],
    meaning: ['Answer'],
    examples: [
      {
        reading: '答える',  
        kana: 'こたえる',
        meaning: ['To answer'],
        sentence: '質問に答えるのは大切です。',
        type: 'YDC_main',
      },
      {
        reading: '答え',
        kana: 'こたえ',
        meaning: ['Answer'],
        sentence: 'この問題の答えは簡単です。',
        type: 'YDC_main',
      },
      {
        reading: '答案',
        kana: 'とうあん',
        meaning: ['Answer sheet', 'Exam paper'],
        sentence: '試験の答案を提出しました。',
        type: 'secondary',
      },
      {
        reading: '解答',
        kana: 'かいとう',
        meaning: ['Solution', 'Answer'],
        sentence: '数学の問題の解答を考えています。',
        type: 'secondary',
      },
      {
        reading: '回答',
        kana: 'かいとう',
        meaning: ['Answer', 'Reply (to a question)'],
        sentence: 'アンケートの回答を集めています。',
        type: 'secondary',
      },
      {
        reading: '返答',
        kana: 'へんとう',
        meaning: ['Reply', 'Response'],
        sentence: 'メールの返答を待っています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '正',
    onyomi: ['しょう', 'せい'],
    kunyomi: ['ただ', 'まさ'],
    meaning: ['Correct', 'Right'],
    examples: [
      {
        reading: 'お正月',
        kana: 'おしょうがつ',
        meaning: ['New Year holiday'],
        sentence: 'お正月は家族と過ごす大切な時期です。',
        type: 'YDC_main',
      },
      {
        reading: '正しい',
        kana: 'ただしい',
        meaning: ['Correct', 'Right'],
        sentence: '正しい答えを選んでください。',
        type: 'YDC_main',
      },
      {
        reading: '正式な',
        kana: 'せいしきな',
        meaning: ['Formal', 'Official'],
        sentence: '正式な文書を提出しました。',
        type: 'YDC_main',
      },
      {
        reading: '正午',
        kana: 'しょうご',
        meaning: ['Noon'],
        sentence: '正午に会議が始まります。',
        type: 'main',
      },
      {
        reading: '正直な',
        kana: 'しょうじきな',
        meaning: ['Honest'],
        sentence: '正直な意見を聞かせてください。',
        type: 'secondary',
      },
      {
        reading: '正確な',
        kana: 'せいかくな',
        meaning: ['Accurate', 'Exact'],
        sentence: '正確な情報を提供することが大切です。',
        type: 'secondary',
      },
      {
        reading: '正解',
        kana: 'せいかい',
        meaning: ['Correct answer'],
        sentence: 'クイズの正解は「C」です。',
        type: 'main',
      },
      {
        reading: '正に',
        kana: 'まさに',
        meaning: ['Exactly'],
        sentence: '正にその通りです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '同',
    onyomi: ['どう'],
    kunyomi: ['おな'],
    meaning: ['Same'],
    examples: [
      {
        reading: '同じ',
        kana: 'おなじ',
        meaning: ['Same'],
        sentence: '私たちは同じ学校に通っています。',
        type: 'YDC_main',
      },
      {
        reading: '同時',
        kana: 'どうじ',
        meaning: ['Simultaneous', 'At the same time'],
        sentence: '同時に二つのことをするのは難しいです。',
        type: 'main',
      },
      {
        reading: '同僚',
        kana: 'どうりょう',
        meaning: ['Colleague', 'Coworker'],
        sentence: '同僚と一緒にプロジェクトを進めています。',
        type: 'secondary',
      },
      {
        reading: '共同',
        kana: 'きょうどう',
        meaning: ['Partnership', 'Cooperation'],
        sentence: '共同でプロジェクトを進めることが大切です。',
        type: 'secondary',
      },
      {
        reading: '同級生',
        kana: 'どうきゅうせい',
        meaning: ['Classmate'],
        sentence: '同級生と一緒に勉強しています。',
        type: 'secondary',
      },
      {
        reading: '同情する',
        kana: 'どうじょうする',
        meaning: ['To sympathize'],
        sentence: '彼の苦しみに同情します。',
        type: 'secondary',
      },
      {
        reading: '同封する',
        kana: 'どうふうする',
        meaning: ['To enclose'],
        sentence: '手紙に写真を同封しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '計',
    onyomi: ['けい'],
    kunyomi: ['はか'],
    meaning: ['To measure'],
    examples: [
      {
        reading: '時計',
        kana: 'とけい',
        meaning: ['Clock', 'Watch'],
        sentence: '時計を見て、時間を確認しました。',
        type: 'YDC_main',
      },
      {
        reading: '計画',
        kana: 'けいかく',
        meaning: ['Plan'],
        sentence: '旅行の計画を立てています。',
        type: 'YDC_main',
      },
      {
        reading: '合計',
        kana: 'ごうけい',
        meaning: ['Total'],
        sentence: '買い物の合計金額を計算しました。',
        type: 'main',
      },
      {
        reading: '計る',
        kana: 'はかる',
        meaning: ['To measure', 'To weigh'],
        sentence: '体重を計るために、体重計に乗りました。',
        type: 'main',
      },
      {
        reading: '会計',
        kana: 'かいけい',
        meaning: ['Accounting', 'Bill'],
        sentence: 'レストランで会計を済ませました。',
        type: 'secondary',
      },
      {
        reading: '統計',
        kana: 'とうけい',
        meaning: ['Statistics'],
        sentence: '統計データを分析しています。',
        type: 'secondary',
      },
      {
        reading: '計算する',
        kana: 'けいさんする',
        meaning: ['To calculate'],
        sentence: '計算するのが得意です。',
        type: 'secondary',
      },
      {
        reading: '家計',
        kana: 'かけい',
        meaning: ['Household budget'],
        sentence: '家計を見直して、無駄遣いを減らします。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '京',
    onyomi: ['きょう', 'けい'],
    kunyomi: [],
    meaning: ['Capital'],
    examples: [
      {
        reading: '東京',
        kana: 'とうきょう',
        meaning: ['Tokyo'],
        sentence: '東京は日本の首都です。',
        type: 'YDC_main',
      },
      {
        reading: '京都',
        kana: 'きょうと',
        meaning: ['Kyoto'],
        sentence: '京都は歴史的な街で、観光名所がたくさんあります。',
        type: 'YDC_main',
      },
      {
        reading: '京子',
        kana: 'きょうこ',
        meaning: ['Kyoko (Woman\'s name)'],
        sentence: '京子さんはとても親切な人です。',
        type: 'secondary',
      },
      {
        reading: '京阪神',
        kana: 'けいはんしん',
        meaning: ['Kyoto, Osaka, and Kobe area'],
        sentence: '京阪神地域は文化と経済の中心地です。',
        type: 'secondary',
      },
      {
        reading: '上京する',
        kana: 'じょうきょうする',
        meaning: ['To go to the capital (Tokyo)'],
        sentence: '大学のために上京しました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '集',
    onyomi: ['しゅう'],
    kunyomi: ['あつ', 'つど'],
    meaning: ['To gather'],
    examples: [
      {
        reading: '集める',
        kana: 'あつめる',
        meaning: ['To collect', 'To gather'],
        sentence: '切手を集めるのが趣味です。',
        type: 'YDC_main',
      },
      {
        reading: '集まる',
        kana: 'あつまる',
        meaning: ['To gather', 'To assemble'],
        sentence: '友達が集まって、パーティーを開きました。',
        type: 'YDC_main',
      },
      {
        reading: '募集する',
        kana: 'ぼしゅうする',
        meaning: ['To recruit', 'To solicit'],
        sentence: '新しいメンバーを募集しています。',
        type: 'main',
      },
      {
        reading: '集会',
        kana: 'しゅうかい',
        meaning: ['Meeting', 'Gathering'],
        sentence: '地域の集会に参加しました。',
        type: 'secondary',
      },
      {
        reading: '集中する',
        kana: 'しゅうちゅうする',
        meaning: ['To concentrate'],
        sentence: '勉強に集中するために、静かな場所を選びました。',
        type: 'secondary',
      },
      {
        reading: '集団',
        kana: 'しゅうだん',
        meaning: ['Group', 'Crowd'],
        sentence: '集団で行動することが多いです。',
        type: 'secondary',
      },
      {
        reading: '集う',
        kana: 'つどう',
        meaning: ['To gather', 'To assemble'],
        sentence: '人々が集う場所は、コミュニティの中心です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '不',
    onyomi: ['ふ', 'ぶ'],
    kunyomi: [],
    meaning: ['Not', 'Non-'],
    examples: [
      {
        reading: '不便な',
        kana: 'ふべんな',
        meaning: ['Inconvenient'],
        sentence: 'この場所は不便なので、引っ越すことにしました。',
        type: 'YDC_main',
      },
      {
        reading: '不安な',
        kana: 'ふあんな',
        meaning: ['Anxious', 'Uneasy', 'Worried'],
        sentence: '試験の結果が不安です。',
        type: 'main',
      },
      {
        reading: '不思議な',
        kana: 'ふしぎな',
        meaning: ['Mysterious', 'Strange'],
        sentence: '不思議な出来事が起こりました。',
        type: 'secondary',
      },
      {
        reading: '不幸',
        kana: 'ふこう',
        meaning: ['Unhappiness', 'Misfortune'],
        sentence: '不幸な出来事が続いています。',
        type: 'secondary',
      },
      {
        reading: '水不足',
        kana: 'みずぶそく',
        meaning: ['Water shortage'],
        sentence: '水不足が深刻な問題になっています。',
        type: 'main',
      },
      {
        reading: '不可能な',
        kana: 'ふかのうな',
        meaning: ['Impossible'],
        sentence: '不可能なことはありません。努力すればできます。',
        type: 'secondary',
      },
      {
        reading: '不公平な',
        kana: 'ふこうへいな',
        meaning: ['Unfair'],
        sentence: '不公平な扱いを受けたと感じています。',
        type: 'secondary',
      },
      {
        reading: '不景気',
        kana: 'ふけいき',
        meaning: ['Economic recession'],
        sentence: '不景気の影響で、仕事が減っています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '便',
    onyomi: ['べん', 'びん'],
    kunyomi: ['たよ'],
    meaning: ['Convenience', 'Mail'],
    examples: [
      {
        reading: '不便な',
        kana: 'ふべんな',
        meaning: ['Inconvenient'],
        sentence: 'この場所は不便なので、引っ越すことにしました。',
        type: 'YDC_main',
      },
      {
        reading: '便利な',
        kana: 'べんりな',
        meaning: ['Convenient'],
        sentence: 'このアプリはとても便利です。',
        type: 'main',
      },
      {
        reading: '便',
        kana: 'びん',
        meaning: ['Flight'],
        sentence: '明日の便で東京に行きます。',
        type: 'main',
      },
      {
        reading: '郵便局',
        kana: 'ゆうびんきょく',
        meaning: ['Post office'],
        sentence: '郵便局で手紙を出しました。',
        type: 'main',
      },
      {
        reading: '便り',
        kana: 'たより',
        meaning: ['News', 'Letter'],
        sentence: '久しぶりに友達から便りが届きました。',
        type: 'secondary',
      },
      {
        reading: '便所',
        kana: 'べんじょ',
        meaning: ['Toilet', 'Lavatory'],
        sentence: '便所は清潔に保つことが大切です。',
        type: 'secondary',
      },
      {
        reading: '航空便',
        kana: 'こうくうびん',
        meaning: ['Air mail'],
        sentence: '航空便で荷物を送ることができます。',
        type: 'main',
      },
      {
        reading: '船便',
        kana: 'ふなびん',
        meaning: ['Sea mail', 'Surface mail'],
        sentence: '船便は時間がかかりますが、安いです。',
        type: 'secondary',
      },
      {
        reading: '便せん',
        kana: 'びんせん',
        meaning: ['Letter paper'],
        sentence: '便せんに手紙を書いて、友達に送りました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '以',
    onyomi: ['い'],
    kunyomi: [],
    meaning: ['Starting point'],
    examples: [
      {
        reading: '以上',
        kana: 'いじょう',
        meaning: ['More than', 'Over', '...or more'],
        sentence: 'この商品は1000円以上で購入できます。',
        type: 'YDC_main',
      },
      {
        reading: '以下',
        kana: 'いか',
        meaning: ['Less than', 'Under', '...or less'],
        sentence: 'この商品は500円以下で購入できます。',
        type: 'YDC_main',
      },
      {
        reading: '以外',
        kana: 'いがい',
        meaning: ['Except', 'Other than'],
        sentence: 'この問題以外はすべて解決しました。',
        type: 'YDC_main',
      },
      {
        reading: '以内',
        kana: 'いない',
        meaning: ['Within'],
        sentence: 'このプロジェクトは一ヶ月以内に完成します。',
        type: 'main',
      },
      {
        reading: '以前',
        kana: 'いぜん',
        meaning: ['Before', 'Ago', 'Formerly'],
        sentence: '以前にこの場所に来たことがあります。',
        type: 'main',
      },
      {
        reading: '以後',
        kana: 'いご',
        meaning: ['After', 'From now on'],
        sentence: '以後、このルールを守ってください。',
        type: 'main',
      },
      {
        reading: '以来',
        kana: 'いらい',
        meaning: ['Since...'],
        sentence: '彼と会うのはそれ以来です。',
        type: 'main',
      },
    ],
  },
]