export const KANJI_YDC_LESSON_21: Array<KanjiYDC> = [
  {
    kanji: '丸',
    onyomi: ['がん'],
    kunyomi: ['まる'],
    meaning: ['Circle', 'Round'],
    examples: [
      {
        reading: '丸い',
        kana: 'まるい',
        meaning: ['Round', 'Circular'],
        sentence: 'このテーブルは丸い形をしています。',
        type: 'YDC_main',
      },
      {
        reading: '丸',
        kana: 'まる',
        meaning: ['Circle', 'Round shape'],
        sentence: '丸いボールを投げました。',
        type: 'YDC_main',
      },
      {
        reading: '丸める',
        kana: 'まるめる',
        meaning: ['To roll up', 'To curl'],
        sentence: '紙を丸めてゴミ箱に捨てました。',
        type: 'secondary',
      },
      {
        reading: '弾丸',
        kana: 'だんがん',
        meaning: ['Bullet'],
        sentence: '弾丸は銃から発射されます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '熱',
    onyomi: ['ねつ', 'ねっ'],
    kunyomi: ['あつ'],
    meaning: ['Heat', 'Temperature'],
    examples: [
      {
        reading: '熱',
        kana: 'ねつ',
        meaning: ['Heat', 'Fever'],
        sentence: '今日はとても熱いです。',
        type: 'YDC_main',
      },
      {
        reading: '熱い',
        kana: 'あつい',
        meaning: ['Hot'],
        sentence: 'このお茶は熱いので気をつけてください。',
        type: 'YDC_main',
      },
      {
        reading: '熱心な',
        kana: 'ねっしんな',
        meaning: ['Enthusiastic', 'Eager'],
        sentence: '彼は熱心に勉強しています。',
        type: 'YDC_main',
      },
      {
        reading: '熱中する',
        kana: 'ねっちゅうする',
        meaning: ['To be absorbed in', 'To be enthusiastic about'],
        sentence: '彼はゲームに熱中しています。',
        type: 'YDC_main',
      },
      {
        reading: '熱帯',
        kana: 'ねったい',
        meaning: ['Tropical'],
        sentence: '熱帯地方は一年中暖かいです。',
        type: 'secondary',
      },
      {
        reading: '熱する',
        kana: 'ねっする',
        meaning: ['To heat', 'To warm up'],
        sentence: '鍋を熱して料理を作ります。',
        type: 'secondary',
      },
      {
        reading: '加熱',
        kana: 'かねつ',
        meaning: ['Heating'],
        sentence: '食品を加熱してから食べてください。',
        type: 'secondary',
      },
      {
        reading: '熱湯',
        kana: 'ねっとう',
        meaning: ['Boiling water'],
        sentence: '熱湯を使うときは注意が必要です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '冷',
    onyomi: ['れい'],
    kunyomi: ['つめ', 'ひ', 'さ'],
    meaning: ['To freeze'],
    examples: [
      {
        reading: '冷たい',
        kana: 'つめたい',
        meaning: ['Cold'],
        sentence: '冷たい飲み物が欲しいです。',
        type: 'YDC_main',
      },
      {
        reading: '冷える',
        kana: 'ひえる',
        meaning: ['To get cold', 'To chill'],
        sentence: '夜になると気温が冷えます。',
        type: 'YDC_main',
      },
      {
        reading: '冷やす',
        kana: 'ひやす',
        meaning: ['To cool down', 'To chill'],
        sentence: '飲み物を冷やしておきます。',
        type: 'YDC_main',
      },
      {
        reading: '冷ます',
        kana: 'さます',
        meaning: ['To let cool', 'To cool down'],
        sentence: 'スープを冷ましてから食べます。',
        type: 'YDC_main',
      },
      {
        reading: '冷蔵庫',
        kana: 'れいぞうこ',
        meaning: ['Refrigerator'],
        sentence: '冷蔵庫に食材を保存しています。',
        type: 'main',
      },
      {
        reading: '冷房',
        kana: 'れいぼう',
        meaning: ['Air conditioning'],
        sentence: '夏は冷房が欠かせません。',
        type: 'main',
      },
      {
        reading: '冷凍する',
        kana: 'れいとうする',
        meaning: ['To freeze'],
        sentence: '食材を冷凍して保存します。',
        type: 'secondary',
      },
      {
        reading: '冷静な',
        kana: 'れいせいな',
        meaning: ['Calm', 'Cool-headed'],
        sentence: '冷静な判断が必要です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '甘',
    onyomi: ['かん'],
    kunyomi: ['あま'],
    meaning: ['Sweet'],
    examples: [
      {
        reading: '甘い',
        kana: 'あまい',
        meaning: ['Sweet'],
        sentence: 'このケーキはとても甘いです。',
        type: 'YDC_main',
      },
      {
        reading: '甘やかす',
        kana: 'あまやかす',
        meaning: ['To spoil'],
        sentence: '子供を甘やかすと、わがままになります。',
        type: 'YDC_main',
      },
      {
        reading: '甘える',
        kana: 'あまえる',
        meaning: ['To behave like a spoiled child'],
        sentence: '彼は母親に甘えています。',
        type: 'main',
      },
      {
        reading: '甘味料',
        kana: 'あまみりょう',
        meaning: ['Sweetener'],
        sentence: '甘味料を使って、料理を甘くしました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '汚',
    onyomi: ['お'],
    kunyomi: ['きたな', 'よご', 'けが'],
    meaning: ['Dirty'],
    examples: [
      {
        reading: '汚い',
        kana: 'きたない',
        meaning: ['Dirty', 'Filthy'],
        sentence: 'この部屋は汚いので掃除が必要です。',
        type: 'YDC_main',
      },
      {
        reading: '汚れる',
        kana: 'よごれる',
        meaning: ['To get dirty', 'To become dirty'],
        sentence: '靴が汚れたので、拭きました。',
        type: 'YDC_main',
      },
      {
        reading: '汚す',
        kana: 'よごす',
        meaning: ['To make dirty', 'To soil'],
        sentence: '服を汚してしまいました。',
        type: 'YDC_main',
      },
      {
        reading: '汚染',
        kana: 'おせん',
        meaning: ['Pollution', 'Contamination'],
        sentence: '工場の排水が川を汚染しています。',
        type: 'secondary',
      },
      {
        reading: '汚れ',
        kana: 'よごれ',
        meaning: ['Dirt', 'Stain'],
        sentence: '服の汚れを落とすために洗剤を使います。',
        type: 'secondary',
      },
      {
        reading: '汚職',
        kana: 'おしょく',
        meaning: ['Corruption', 'Bribery'],
        sentence: '汚職事件が発覚しました。',
        type: 'secondary',
      },
      {
        reading: '汚れる',
        kana: 'けがれる',
        meaning: ['To become dirty'],
        sentence: '心が汚れると、幸せになれません。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '果',
    onyomi: ['か'],
    kunyomi: ['は'],
    meaning: ['Fruit', 'Result'],
    examples: [
      {
        reading: '果物',
        kana: 'くだもの',
        meaning: ['Fruit'],
        sentence: '果物は健康に良いです。',
        type: 'YDC_main',
      },
      {
        reading: '結果',
        kana: 'けっか',
        meaning: ['Result', 'Outcome'],
        sentence: '試験の結果が発表されました。',
        type: 'main',
      },
      {
        reading: '効果',
        kana: 'こうか',
        meaning: ['Effect', 'Effectiveness'],
        sentence: 'この薬の効果はすぐに現れます。',
        type: 'secondary',
      },
      {
        reading: '果実',  
        kana: 'かじつ',
        meaning: ['Fruit', 'Produce'],
        sentence: '果実は自然の甘さが楽しめます。',
        type: 'secondary',
      },
      {
        reading: '果たして',
        kana: 'はたして',
        meaning: ['Indeed', 'As expected', 'As it turns out'],
        sentence: '果たして彼は約束を守りました。',
        type: 'main',
      },
      {
        reading: '成果',
        kana: 'せいか',
        meaning: ['Achievement', 'Result'],
        sentence: 'このプロジェクトの成果は素晴らしいです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '卵',
    onyomi: ['らん'],
    kunyomi: ['たまご'],
    meaning: ['Egg'],
    examples: [
      {
        reading: '卵',  
        kana: 'たまご',
        meaning: ['Egg'],
        sentence: '朝ごはんに卵を食べました。',
        type: 'YDC_main',
      },
      {
        reading: '卵黄',
        kana: 'らんおう',
        meaning: ['Egg yolk'],
        sentence: '卵黄は料理にコクを与えます。',
        type: 'secondary',
      },
      {
        reading: '卵白',
        kana: 'らんぱく',
        meaning: ['Egg white'],
        sentence: '卵白は泡立ててメレンゲを作ります。',
        type: 'main',
      },
      {
        reading: '卵焼き',
        kana: 'たまごやき',
        meaning: ['Japanese omelette'],
        sentence: '朝食に卵焼きを作りました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '皿',
    onyomi: ['さら', 'ざら'],
    kunyomi: [],
    meaning: ['Plate', 'Dish'],
    examples: [
      {
        reading: 'お皿',  
        kana: 'おさら',
        meaning: ['Plate', 'Dish'],
        sentence: 'お皿に料理を盛り付けました。',
        type: 'YDC_main',
      },
      {
        reading: '灰皿',
        kana: 'はいざら',
        meaning: ['Ashtray'],
        sentence: '灰皿にタバコの吸い殻を捨てました。',
        type: 'secondary',
      },
      {
        reading: '紙皿',
        kana: 'かみざら',
        meaning: ['Paper plate'],
        sentence: 'ピクニックでは紙皿を使います。',
        type: 'main',
      },
      {
        reading: '大皿',
        kana: 'おおざら',
        meaning: ['Large plate'],
        sentence: '大皿にサラダを盛り付けました。',
        type: 'main',
      },
      {
        reading: '小皿',
        kana: 'こざら',
        meaning: ['Small plate'],
        sentence: '小皿にお漬物を盛り付けました。',
        type: 'main',
      },
      {
        reading: '皿洗い',
        kana: 'さらあらい',
        meaning: ['Dishwashing'],
        sentence: '皿洗いは家事の一つです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '酒',
    onyomi: ['しゅ'],
    kunyomi: ['さけ', 'ざけ', 'さか', 'ざか'],
    meaning: ['Alcohol'],
    examples: [
      {
        reading: 'お酒',
        kana: 'おさけ',
        meaning: ['Alcohol'],
        sentence: 'お酒は控えめに飲みましょう。',
        type: 'YDC_main',
      },
      {
        reading: '酒屋',
        kana: 'さかや',
        meaning: ['Liquor store'],
        sentence: '近くの酒屋でお酒を買いました。',
        type: 'YDC_main',
      },
      {
        reading: '日本酒',
        kana: 'にほんしゅ',
        meaning: ['Japanese sake'],
        sentence: '日本酒は米から作られています。',
        type: 'YDC_main',
      },
      {
        reading: '飲酒運転',
        kana: 'いんしゅうんてん',
        meaning: ['Drunk driving'],
        sentence: '飲酒運転は法律で禁止されています。',
        type: 'YDC_main',
      },
      {
        reading: '洋酒',
        kana: 'ようしゅ',
        meaning: ['Western liquor'],
        sentence: '洋酒はワインやウイスキーなどがあります。',
        type: 'secondary',
      },
      {
        reading: '居酒屋',
        kana: 'いざかや',
        meaning: ['Japanese pub'],
        sentence: '居酒屋で友達と飲みました。',
        type: 'main',
      },
      {
        reading: '地酒',
        kana: 'じざけ',
        meaning: ['Local sake'],
        sentence: '地酒はその地域の特産品です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '塩',
    onyomi: ['えん'],
    kunyomi: ['しお'],
    meaning: ['Salt'],
    examples: [
      {
        reading: '塩',
        kana: 'しお',
        meaning: ['Salt'],
        sentence: '料理には塩を少し加えます。',
        type: 'YDC_main',
      },
      {
        reading: '塩辛い',
        kana: 'しおからい',
        meaning: ['Salty'],
        sentence: 'この料理は塩辛いので、少し薄めます。',
        type: 'main',
      },
      {
        reading: '食塩',
        kana: 'しょくえん',
        meaning: ['Table salt'],
        sentence: '食塩は料理に欠かせない調味料です。',
        type: 'secondary',
      },
      {
        reading: '塩分',
        kana: 'えんぶん',
        meaning: ['Salt content'],
        sentence: '塩分を控えることは健康に良いです。',
        type: 'secondary',
      },
      {
        reading: '塩水',
        kana: 'しおみず',
        meaning: ['Saltwater'],
        sentence: '海は塩水でできています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '付',
    onyomi: ['ふ'],
    kunyomi: ['つ', 'づ'],
    meaning: ['To attach'],
    examples: [
      {
        reading: '付き合う',
        kana: 'つきあう',
        meaning: ['To associate with', 'To date'],
        sentence: '彼と付き合い始めました。',
        type: 'YDC_main',
      },
      {
        reading: '片付ける',
        kana: 'かたづける',
        meaning: ['To tidy up', 'To clean up'],
        sentence: '部屋を片付けるのは大変です。',
        type: 'YDC_main',
      },
      {
        reading: '付ける',
        kana: 'つける',
        meaning: ['To attach', 'To add'],
        sentence: '名札をシャツに付けました。',
        type: 'YDC_main',
      },
      {
        reading: '付く',
        kana: 'つく',
        meaning: ['To stick'],
        sentence: 'シールが紙に付いています。',
        type: 'YDC_main',
      },
      {
        reading: '日付',
        kana: 'ひづけ',
        meaning: ['Date'],
        sentence: '今日の日付は2023年10月1日です。',
        type: 'YDC_main',
      },
      {
        reading: '受付',
        kana: 'うけつけ',
        meaning: ['Reception', 'Front desk'],
        sentence: 'ホテルの受付でチェックインしました。',
        type: 'main',
      },
      {
        reading: '寄付',
        kana: 'きふ',
        meaning: ['Donation'],
        sentence: '学校に寄付をしました。',
        type: 'secondary',
      },
      {
        reading: '付録',
        kana: 'ふろく',
        meaning: ['Supplement', 'Appendix'],
        sentence: 'この雑誌には付録がついています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '片',
    onyomi: ['へん'],
    kunyomi: ['かた'],
    meaning: ['One-sided'],
    examples: [
      {
        reading: '片付ける',
        kana: 'かたづける',
        meaning: ['To tidy up', 'To clean up'],
        sentence: '部屋を片付けるのは大変です。',
        type: 'YDC_main',
      },
      {
        reading: '片道',
        kana: 'かたみち',
        meaning: ['One-way'],
        sentence: '片道切符を買いました。',
        type: 'YDC_main',
      },
      {
        reading: '片方',
        kana: 'かたほう',
        meaning: ['One of a pair'],
        sentence: '靴の片方をなくしてしまいました。',
        type: 'main',
      },
      {
        reading: '片手',
        kana: 'かたて',
        meaning: ['One hand'],
        sentence: '片手で荷物を持つのは大変です。',
        type: 'main',
      },
      {
        reading: '片言',
        kana: 'かたこと',
        meaning: ['Broken language', 'Baby talk'],
        sentence: '彼は片言の日本語を話します。',
        type: 'secondary',
      },
      {
        reading: '片寄る',
        kana: 'かたよる',
        meaning: ['To lean to one side', 'To be biased'],
        sentence: '意見が片寄っていると感じます。',
        type: 'secondary',
      },
      {
        reading: '破片',
        kana: 'はへん',
        meaning: ['Fragment', 'Piece'],
        sentence: 'ガラスの破片が床に散らばっています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '焼',
    onyomi: ['しょう'],
    kunyomi: ['や'],
    meaning: ['To burn', 'To grill'],
    examples: [
      {
        reading: '焼く',
        kana: 'やく',
        meaning: ['To burn', 'To bake'],
        sentence: '魚を焼いて食べました。',
        type: 'YDC_main',
      },
      {
        reading: '焼ける',
        kana: 'やける',
        meaning: ['To be burned', 'To be baked'],
        sentence: 'パンが焼ける匂いがします。',
        type: 'YDC_main',
      },
      {
        reading: '夕焼け',
        kana: 'ゆうやけ',
        meaning: ['Sunset', 'Evening glow'],
        sentence: '夕焼けがとても美しいです。',
        type: 'secondary',
      },
      {
        reading: '日焼け',
        kana: 'ひやけ',
        meaning: ['Sunburn'],
        sentence: '夏に海で日焼けをしました。',
        type: 'secondary',
      },
      {
        reading: '焼き鳥',
        kana: 'やきとり',
        meaning: ['Grilled chicken skewers'],
        sentence: '焼き鳥は居酒屋の人気メニューです。',
        type: 'main',
      },
      {
        reading: '焼き肉',
        kana: 'やきにく',
        meaning: ['Grilled meat'],
        sentence: '焼き肉を食べに行きました。',
        type: 'main',
      },
      {
        reading: '燃焼',
        kana: 'ねんしょう',
        meaning: ['Combustion'],
        sentence: '燃焼効率を上げるために新しい技術が開発されています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '消',
    onyomi: ['しょう'],
    kunyomi: ['け', 'き'],
    meaning: ['To turn off', 'To disappear'],
    examples: [
      {
        reading: '消す',
        kana: 'けす',
        meaning: ['To turn off'],
        sentence: '電気を消してから寝ます。',
        type: 'YDC_main',
      },
      {
        reading: '消える',
        kana: 'きえる',
        meaning: ['To disappear', 'Something turns off'],
        sentence: '明かりが消えました。',
        type: 'YDC_main',
      },
      {
        reading: '消化する',
        kana: 'しょうかする',
        meaning: ['To digest'],
        sentence: '食べ物を消化するのに時間がかかります。',
        type: 'YDC_main',
      },
      {
        reading: '消防署',
        kana: 'しょうぼうしょ',
        meaning: ['Fire station'],
        sentence: '消防署は火事の時に助けてくれます。',
        type: 'secondary',
      },
      {
        reading: '取り消す',
        kana: 'とりけす',
        meaning: ['To cancel', 'To retract'],
        sentence: '予約を取り消しました。',
        type: 'secondary',
      },
      {
        reading: '消去する',
        kana: 'しょうきょする',
        meaning: ['To erase', 'To delete'],
        sentence: 'パソコンのデータを消去しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '固',
    onyomi: ['こ'],
    kunyomi: ['かた'],
    meaning: ['Solid', 'Hard'],
    examples: [
      {
        reading: '固い',
        kana: 'かたい',
        meaning: ['Hard', 'Solid'],
        sentence: 'この石はとても固いです。',
        type: 'YDC_main',
      },
      {
        reading: '固まる',
        kana: 'かたまる',
        meaning: ['To harden', 'To solidify'],
        sentence: 'ゼリーが固まるまで待ちます。',
        type: 'YDC_main',
      },
      {
        reading: '個体',
        kana: 'こたい',
        meaning: ['Solid body'],
        sentence: '水は常温では液体ですが、冷やすと個体になります。',
        type: 'secondary',
      },
      {
        reading: '固定',
        kana: 'こてい',
        meaning: ['Fix'],
        sentence: '家具を壁に固定しました。',
        type: 'secondary',
      },
      {
        reading: '頑固な',
        kana: 'がんこな',
        meaning: ['Stubborn', 'Obstinate'],
        sentence: '彼は頑固な性格で、意見を変えません。',
        type: 'secondary',
      },
      {
        reading: '固有の',
        kana: 'こゆうの',
        meaning: ['Unique', 'Peculiar'],
        sentence: 'この地域には固有の文化があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '個',
    onyomi: ['こ'],
    kunyomi: [],
    meaning: ['Individual', 'Counter for small items'],
    examples: [
      {
        reading: '一個',
        kana: 'いっこ',
        meaning: ['One piece', 'One item'],
        sentence: 'りんごを一個買いました。',
        type: 'YDC_main',
      },
      {
        reading: '個人',
        kana: 'こじん',
        meaning: ['Individual', 'Personal'],
        sentence: '個人情報は大切に扱うべきです。',
        type: 'YDC_main',
      },
      {
        reading: '個人主義',
        kana: 'こじんしゅぎ',
        meaning: ['Individualism'],
        sentence: '個人主義は自由を重んじる考え方です。',
        type: 'secondary',
      },
      {
        reading: '個展',
        kana: 'こてん',
        meaning: ['Solo exhibition'],
        sentence: '彼の個展がギャラリーで開かれます。',
        type: 'secondary',
      },
      {
        reading: '個性',
        kana: 'こせい',
        meaning: ['Personality'],
        sentence: '彼女は個性豊かな人です。',
        type: 'secondary',
      },
      {
        reading: '個数',
        kana: 'こすう',
        meaning: ['Number of items', 'Count'],
        sentence: '注文した商品の個数を確認しました。',
        type: 'secondary',
      },
      {
        reading: '個室',
        kana: 'こしつ',
        meaning: ['Private room'],
        sentence: '病院の個室で静かに休んでいます。',
        type: 'main',
      },
    ],
  },
]