export const KANJI_YDC_LESSON_18: Array<KanjiYDC> = [
  {
    kanji: '図',
    onyomi: ['ず', 'と'],
    kunyomi: ['はか'],
    meaning: ['Drawing'],
    examples: [
      {
        reading: '地図',
        kana: 'ちず',
        meaning: ['Map'],
        sentence: '旅行に行く前に、地図を確認しておきます。',
        type: 'main',
      },
      {
        reading: '図書館',
        kana: 'としょかん',
        meaning: ['Library'],
        sentence: '図書館で本を借りてきました。',
        type: 'main',
      },
      {
        reading: '図',
        kana: 'ず',
        meaning: ['Chart', 'Diagram'],
        sentence: 'この図は、データを視覚的に表現しています。',
        type: 'main',
      },
      {
        reading: '図表',
        kana: 'ずひょう',
        meaning: ['Figures and diagrams'],
        sentence: '図表を使って、データをわかりやすく説明します。',
        type: 'secondary',
      },
      {
        reading: '合図',
        kana: 'あいず',
        meaning: ['Signal', 'Sign'],
        sentence: '合図を送って、みんなに集まるように伝えました。',
        type: 'main',
      },
      {
        reading: '意図',
        kana: 'いと',
        meaning: ['Intention', 'Purpose'],
        sentence: '彼の意図を理解するのは難しいです。',
        type: 'main',
      },
      {
        reading: '図る',
        kana: 'はかる',
        meaning: ['To plot', 'To attempt'],
        sentence: '新しいプロジェクトを図るために、会議を開きました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '官',
    onyomi: ['かん'],
    kunyomi: [],
    meaning: ['Government official'],
    examples: [
      {
        reading: '長官',
        kana: 'ちょうかん',
        meaning: ['Director-general'],
        sentence: '長官は会議で重要な発表をしました。',
        type: 'main',
      },
      {
        reading: '外交官',
        kana: 'がいこうかん',
        meaning: ['Diplomat'],
        sentence: '外交官は国と国との関係を築く役割を担っています。',
        type: 'secondary',
      },
      {
        reading: '警官',
        kana: 'けいかん',
        meaning: ['Police officer'],
        sentence: '警官が交通整理をしていました。',
        type: 'secondary',
      },
      {
        reading: '裁判官',
        kana: 'さいばんかん',
        meaning: ['Judge'],
        sentence: '裁判官は公正な判断を下すことが求められます。',
        type: 'secondary',
      },
      {
        reading: '官庁',
        kana: 'かんちょう',
        meaning: ['Government office'],
        sentence: '官庁は国の政策を実行する機関です。',
        type: 'secondary',
      },
      {
        reading: '官僚',
        kana: 'かんりょう',
        meaning: ['Government official'],
        sentence: '官僚は政策の立案や実行に関与します。',
        type: 'secondary',
      },
      {
        reading: '器官',
        kana: 'きかん',
        meaning: ['Organ'],
        sentence: '人間の体には多くの器官があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '館',
    onyomi: ['かん'],
    kunyomi: ['やかた'],
    meaning: ['Building'],
    examples: [
      {
        reading: '映画館',
        kana: 'えいがかん',
        meaning: ['Movie theater'],
        sentence: '映画館で新作映画を観ました。',
        type: 'main',
      },
      {
        reading: '大使館',
        kana: 'たいしかん',
        meaning: ['Embassy'],
        sentence: '大使館でビザの申請をしました。',
        type: 'main',
      },
      {
        reading: '旅館',
        kana: 'りょかん',
        meaning: ['Japanese inn'],
        sentence: '旅館で温泉に入ってリラックスしました。',
        type: 'secondary',
      },
      {
        reading: '会館',
        kana: 'かいかん',
        meaning: ['Hall'],
        sentence: '会館でコンサートが開かれます。',
        type: 'main',
      },
      {
        reading: '美術館',
        kana: 'びじゅつかん',
        meaning: ['Art museum'],
        sentence: '美術館で絵画を鑑賞しました。',
        type: 'secondary',
      },
      {
        reading: '博物館',
        kana: 'はくぶつかん',
        meaning: ['Museum'],
        sentence: '博物館で歴史的な展示を見学しました。',
        type: 'secondary',
      },
      {
        reading: '水族館',
        kana: 'すいぞくかん',
        meaning: ['Aquarium'],
        sentence: '水族館で色とりどりの魚を見ました。',
        type: 'main',
      },
      {
        reading: '占いの館',
        kana: 'うらないのやかた',
        meaning: ['Fortune-telling house'],
        sentence: '占いの館で未来を占ってもらいました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '昔',
    onyomi: ['せき', 'しゃく', 'じゃく'],
    kunyomi: ['むかし'],
    meaning: ['Long ago'],
    examples: [
      {
        reading: '昔',
        kana: 'むかし',
        meaning: ['Long ago'],
        sentence: '昔、遠い国に美しい姫がいました。',
        type: 'main',
      },
      {
        reading: '昔話',
        kana: 'むかしばなし',
        meaning: ['Old tale'],
        sentence: '昔話を聞くのが好きです。',
        type: 'main',
      },
      {
        reading: '大昔',
        kana: 'おおむかし',
        meaning: ['Long, long ago', 'Ancient times'],
        sentence: '大昔の人々は、どのように生活していたのでしょうか。',
        type: 'secondary',
      },
      {
        reading: '昔日',
        kana: 'せきじつ',
        meaning: ['Old days'],
        sentence: '昔日を懐かしむ人が多いです。',
        type: 'secondary',
      },
      {
        reading: '昔々',
        kana: 'むかしむかし',
        meaning: ['Once upon a time'],
        sentence: '昔々、あるところにおじいさんとおばあさんがいました。',
        type: 'main',
      },
      {
        reading: '今昔',
        kana: 'こんじゃく',
        meaning: ['The changing times'],
        sentence: '今昔物語は、日本の古典文学の一つです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '借',
    onyomi: ['しゃく', 'しゃっ'],
    kunyomi: ['か'],
    meaning: ['Borrow'],
    examples: [
      {
        reading: '借りる',
        kana: 'かりる',
        meaning: ['To borrow'],
        sentence: '友達から本を借りました。',
        type: 'main',
      },
      {
        reading: '借家',
        kana: 'しゃくや',
        meaning: ['Rented house'],
        sentence: '借家に住んでいるので、家賃を払っています。',
        type: 'main',
      },
      {
        reading: '借金',
        kana: 'しゃっきん',
        meaning: ['Debt'],
        sentence: '借金を返すために、働いています。',
        type: 'main',
      },
      {
        reading: '借地',
        kana: 'しゃくち',
        meaning: ['Leased land'],
        sentence: '借地に家を建てることができます。',
        type: 'main',
      },
      {
        reading: '貸し借り',
        kana: 'かしかり',
        meaning: ['Lending and borrowing'],
        sentence: '貸し借りは、信頼関係が大切です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '代',
    onyomi: ['だい', 'たい'],
    kunyomi: ['か', 'しろ', 'よ'],
    meaning: ['Age', 'To replace'],
    examples: [
      {
        reading: '時代',
        kana: 'じだい',
        meaning: ['Era', 'Period'],
        sentence: 'この時代の文化はとても興味深いです。',
        type: 'main',
      },
      {
        reading: '電気代',
        kana: 'でんきだい',
        meaning: ['Electricity bill'],
        sentence: '今月の電気代は高かったです。',
        type: 'main',
      },
      {
        reading: '代わりに',
        kana: 'かわりに',
        meaning: ['Instead of'],
        sentence: '彼は私の代わりに会議に出席しました。',
        type: 'main',
      },
      {
        reading: '六十年代',
        kana: 'ろくじゅうねんだい',
        meaning: ['60s'],
        sentence: '六十年代の音楽は、今でも人気があります。',
        type: 'secondary',
      },
      {
        reading: '十代',
        kana: 'じゅうだい',
        meaning: ['Teenage years'],
        sentence: '十代の頃は、夢を追いかけていました。',
        type: 'secondary',
      },
      {
        reading: '代表',
        kana: 'だいひょう',
        meaning: ['Representative'],
        sentence: '彼は会社の代表として会議に出席しました。',
        type: 'secondary',
      },
      {
        reading: '現代',
        kana: 'げんだい',
        meaning: ['Modern times'],
        sentence: '現代の技術は、私たちの生活を便利にしています。',
        type: 'secondary',
      },
      {
        reading: '代金',
        kana: 'だいきん',
        meaning: ['Price', 'Charge'],
        sentence: '代金は後で支払います。',
        type: 'secondary',
      },
      {
        reading: '身代金',
        kana: 'みのしろきん',
        meaning: ['Ransom'],
        sentence: '誘拐された人質の身代金が要求されました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '貸',
    onyomi: ['たい'],
    kunyomi: ['か'],
    meaning: ['Lend'],
    examples: [
      {
        reading: '貸す',  
        kana: 'かす',
        meaning: ['To lend'],
        sentence: '友達に本を貸しました。',
        type: 'main',
      },
      {
        reading: '貸し出し',
        kana: 'かしだし',
        meaning: ['Lending out'],
        sentence: '図書館で本の貸し出しを行っています。',
        type: 'main',
      },
      {
        reading: '貸切',
        kana: 'かしきり',
        meaning: ['Reserved'],
        sentence: 'この部屋は貸切です。',
        type: 'main',
      },
      {
        reading: '賃貸マンション',
        kana: 'ちんたいマンション',
        meaning: ['Apartment for rent'],
        sentence: '賃貸マンションを探しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '地',
    onyomi: ['ち', 'じ'],
    kunyomi: [],
    meaning: ['Land'],
    examples: [
      {
        reading: '地理',  
        kana: 'ちり',
        meaning: ['Geography'],
        sentence: '地理の授業で世界の国々を学びました。',
        type: 'main',
      },
      {
        reading: '地下',
        kana: 'ちか',
        meaning: ['Underground'],
        sentence: '地下鉄は便利な交通手段です。',
        type: 'main',
      },
      {
        reading: '地下鉄',
        kana: 'ちかてつ',
        meaning: ['Subway'],
        sentence: '地下鉄で駅まで行きます。',
        type: 'main',
      },
      {
        reading: '地震',
        kana: 'じしん',
        meaning: ['Earthquake'],
        sentence: '地震が起きたとき、すぐに避難しました。',
        type: 'main',
      },
      {
        reading: '意地悪な',
        kana: 'いじわるな',
        meaning: ['Mean-spirited'],
        sentence: '彼は意地悪なことを言う人です。',
        type: 'secondary',
      },
      {
        reading: '地方',
        kana: 'ちほう',
        meaning: ['Region', 'Countryside'],
        sentence: '地方の特産品を買いました。',
        type: 'secondary',
      },
      {
        reading: '地球',
        kana: 'ちきゅう',
        meaning: ['Earth'],
        sentence: '地球は太陽系の惑星の一つです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '産',
    onyomi: ['さん'],
    kunyomi: ['う', 'うぶ'],
    meaning: ['Produce', 'Give birth'],
    examples: [
      {
        reading: '産業',
        kana: 'さんぎょう',
        meaning: ['Industry'],
        sentence: 'この地域の主要な産業は農業です。',
        type: 'main',
      },
      {
        reading: '生産',
        kana: 'せいさん',
        meaning: ['Production'],
        sentence: 'この工場では、自動車の生産が行われています。',
        type: 'main',
      },
      {
        reading: 'お土産',
        kana: 'おみやげ',
        meaning: ['Souvenir'],
        sentence: '旅行のお土産に、地元の特産品を買いました。',
        type: 'main',
      },
      {
        reading: '産地',
        kana: 'さんち',
        meaning: ['Source of products'],
        sentence: 'この野菜は新鮮な産地から取り寄せています。',
        type: 'secondary',
      },
      {
        reading: '共産主義',
        kana: 'きょうさんしゅぎ',
        meaning: ['Communism'],
        sentence: '共産主義は、資本主義とは異なる経済体制です。',
        type: 'secondary',
      },
      {
        reading: '財産',
        kana: 'ざいさん',
        meaning: ['Property', 'Assets'],
        sentence: '彼は多くの財産を持っています。',
        type: 'secondary',
      },
      {
        reading: '産む',
        kana: 'うむ',
        meaning: ['To give birth'],
        sentence: '彼女は元気な赤ちゃんを産みました。',
        type: 'main',
      },
      {
        reading: '不動産',
        kana: 'ふどうさん',
        meaning: ['Real estate'],
        sentence: '不動産の購入は、大きな投資です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '業',
    onyomi: ['ぎょう', 'ごう'],
    kunyomi: ['わざ'],
    meaning: ['Business', 'Industry'],
    examples: [ 
      {
        reading: '工業',
        kana: 'こうぎょう',
        meaning: ['Manufacturing industry'],
        sentence: '工業はこの地域の主要な産業です。',
        type: 'main',
      },
      {
        reading: '授業',
        kana: 'じゅぎょう',
        meaning: ['Class'],
        sentence: '授業は午後から始まります。',
        type: 'main',
      },
      {
        reading: '卒業',
        kana: 'そつぎょう',
        meaning: ['Graduation'],
        sentence: '大学を卒業したら、就職活動を始めます。',
        type: 'secondary',
      },
      {
        reading: '職業',
        kana: 'しょくぎょう',
        meaning: ['Occupation', 'Profession'],
        sentence: '彼は医者という職業を選びました。',
        type: 'main',
      },
      {
        reading: '企業',
        kana: 'きぎょう',
        meaning: ['Enterprise'],
        sentence: '企業の成長には、革新が必要です。',
        type: 'secondary',
      },
      {
        reading: '営業中',
        kana: 'えいぎょうちゅう',
        meaning: ['Open for business'],
        sentence: 'この店は営業中です。',
        type: 'secondary',
      },
      {
        reading: '自業自得',
        kana: 'じごうじとく',
        meaning: ['You reap what you sow'],
        sentence: '自業自得という言葉は、自分の行動の結果を受け入れることを意味します。',
        type: 'secondary',
      },
      {
        reading: '農業',
        kana: 'のうぎょう',
        meaning: ['Agriculture'],
        sentence: '農業はこの地域の重要な産業です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '薬',
    onyomi: ['やく', 'やっ'],
    kunyomi: ['くすり', 'ぐすり'],
    meaning: ['Medicine'],
    examples: [
      {
        reading: '薬',
        kana: 'くすり',
        meaning: ['Medicine'],
        sentence: '風邪をひいたので、薬を飲みました。',
        type: 'main',
      },
      {
        reading: '薬屋',
        kana: 'くすりや',
        meaning: ['Pharmacy'],
        sentence: '薬屋で風邪薬を買いました。',
        type: 'main',
      },
      {
        reading: '薬局',
        kana: 'やっきょく',
        meaning: ['Pharmacy'],
        sentence: '薬局で処方箋を持って、薬を受け取りました。',
        type: 'main',
      },
      {
        reading: '農薬',
        kana: 'のうやく',
        meaning: ['Agricultural chemicals'],
        sentence: '農薬を使うことで、作物の病気を防ぎます。',
        type: 'secondary',
      },
      {
        reading: '薬指',
        kana: 'くすりゆび',
        meaning: ['Ring finger'],
        sentence: '薬指に指輪をはめることが多いです。',
        type: 'secondary',
      },
      {
        reading: '風邪薬',
        kana: 'かぜぐすり',
        meaning: ['Cold medicine'],
        sentence: '風邪薬を飲んで、早く治したいです。',
        type: 'main',
      },
      {
        reading: '薬学',
        kana: 'やくがく',
        meaning: ['Pharmaceutical science'],
        sentence: '薬学を学ぶことで、医療に貢献できるようになりたいです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '働',
    onyomi: ['どう'],
    kunyomi: ['はたら', 'ばたら'],
    meaning: ['Work', 'Labor'],
    examples: [
      {
        reading: '働く',
        kana: 'はたらく',
        meaning: ['To work'],
        sentence: '毎日、会社で働いています。',
        type: 'main',
      },
      {
        reading: '共働き',
        kana: 'ともばたらき',
        meaning: ['Dual-income family'],
        sentence: '共働きの家庭が増えています。',
        type: 'main',
      },
      {
        reading: '働き者',
        kana: 'はたらきもの',
        meaning: ['Hard worker'],
        sentence: '彼は働き者で、いつも忙しそうです。',
        type: 'secondary',
      },
      {
        reading: '労働',
        kana: 'ろうどう',
        meaning: ['Labor', 'Work'],
        sentence: '労働条件の改善が求められています。',
        type: 'main',
      },
      {
        reading: '労働者',
        kana: 'ろうどうしゃ',
        meaning: ['Worker'],
        sentence: '労働者の権利を守るために、法律が整備されています。',
        type: 'main',
      },
      {
        reading: '労働組合',
        kana: 'ろうどうくみあい',
        meaning: ['Labor union'],
        sentence: '労働組合は、労働者の権利を守るために活動しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '員',
    onyomi: ['いん'],
    kunyomi: [],
    meaning: ['Member'],
    examples: [
      {
        reading: '会社員',
        kana: 'かいしゃいん',
        meaning: ['Company employee'],
        sentence: '彼は大手企業の会社員です。',
        type: 'main',
      },
      {
        reading: '店員',
        kana: 'てんいん',
        meaning: ['Store clerk'],
        sentence: '店員に商品の場所を聞きました。',
        type: 'main',
      },
      {
        reading: '銀行員',
        kana: 'ぎんこういん',
        meaning: ['Bank employee'],
        sentence: '銀行員として働いています。',
        type: 'main',
      },
      {
        reading: '全員',
        kana: 'ぜんいん',
        meaning: ['All members'],
        sentence: '全員が参加することが求められています。',
        type: 'main',
      },
      {
        reading: '公務員',
        kana: 'こうむいん',
        meaning: ['Public servant'],
        sentence: '公務員は安定した職業とされています。',
        type: 'secondary',
      },
      {
        reading: '会員',
        kana: 'かいいん',
        meaning: ['Member'],
        sentence: 'このクラブの会員になるには、申し込みが必要です。',
        type: 'secondary',
      },
      {
        reading: '満員',
        kana: 'まんいん',
        meaning: ['Full', 'No vacancies'],
        sentence: 'この電車は満員です。',
        type: 'main',
      },
      {
        reading: '教員',
        kana: 'きょういん',
        meaning: ['Teacher'],
        sentence: '教員は学生の学びをサポートする役割があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '士',
    onyomi: ['し'],
    kunyomi: [],
    meaning: ['Warrior', 'Samurai'],
    examples: [
      {
        reading: '武士',
        kana: 'ぶし',
        meaning: ['Samurai'],
        sentence: '武士は日本の歴史において重要な役割を果たしました。',
        type: 'main',
      },
      {
        reading: '博士',
        kana: 'はかせ・はかせ',
        meaning: ['Doctor', 'PhD'],
        sentence: '彼は物理学の博士号を持っています。',
        type: 'secondary',
      },
      {
        reading: '修士',
        kana: 'しゅうし',
        meaning: ['Master\'s degree'],
        sentence: '彼女は修士号を取得しました。',
        type: 'main',
      },
      {
        reading: '弁護士',
        kana: 'べんごし',
        meaning: ['Lawyer'],
        sentence: '弁護士は法律の専門家です。',
        type: 'secondary',
      },
      {
        reading: '紳士',
        kana: 'しんし',
        meaning: ['Gentleman'],
        sentence: '彼はとても紳士的な態度で接してくれました。',
        type: 'main',
      },
      {
        reading: '消防士',
        kana: 'しょうぼうし',
        meaning: ['Firefighter'],
        sentence: '消防士は火災から人々を守るために働いています。',
        type: 'secondary',
      },
      {
        reading: '会計士',
        kana: 'かいけいし',
        meaning: ['Accountant'],
        sentence: '会計士は企業の財務を管理する専門家です。',
        type: 'main',
      },
      {
        reading: '税理士',
        kana: 'ぜいりし',
        meaning: ['Tax accountant'],
        sentence: '税理士は税金に関する専門家です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '仕',
    onyomi: ['し', 'じ'],
    kunyomi: ['つか'],
    meaning: ['To serve'],
    examples: [
      {
        reading: '仕事',
        kana: 'しごと',
        meaning: ['Work', 'Job'],
        sentence: '仕事が終わったら、友達と飲みに行く予定です。',
        type: 'main',
      },
      {
        reading: '仕方',
        kana: 'しかた',
        meaning: ['Method', 'Way'],
        sentence: '仕方がないので、諦めます。',
        type: 'secondary',
      },
      {
        reading: '仕上げる',
        kana: 'しあげる',
        meaning: ['To finish', 'To complete'],
        sentence: '宿題を仕上げるのに時間がかかりました。',
        type: 'main',
      },
      {
        reading: '仕返し',
        kana: 'しかえし',
        meaning: ['Revenge'],
        sentence: '彼は仕返しをするつもりです。',
        type: 'main',
      },
      {
        reading: '奉仕活動',
        kana: 'ほうしかつどう',
        meaning: ['Volunteer work'],
        sentence: '奉仕活動は社会貢献の一環です。',
        type: 'secondary',
      },
      {
        reading: '仕える',
        kana: 'つかえる',
        meaning: ['To serve'],
        sentence: '彼は会社に仕えることを誇りに思っています。',
        type: 'main',
      },
      {
        reading: '給仕',
        kana: 'きゅうじ',
        meaning: ['Waiter', 'Waitress'],
        sentence: '給仕が料理を運んできました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '事',
    onyomi: ['じ', 'ず'],
    kunyomi: ['こと', 'ごと'],
    meaning: ['Thing'],
    examples: [
      {
        reading: '事',
        kana: 'こと',
        meaning: ['Thing', 'Matter'],
        sentence: '大切な事を忘れないでください。',
        type: 'main',
      },
      {
        reading: '火事',
        kana: 'かじ',
        meaning: ['Fire'],
        sentence: '火事が発生したので、避難してください。',
        type: 'main',
      },
      {
        reading: '食事',
        kana: 'しょくじ',
        meaning: ['Meal'],
        sentence: '食事の時間になりました。',
        type: 'main',
      },
      {
        reading: '返事',
        kana: 'へんじ',
        meaning: ['Reply', 'Response'],
        sentence: 'メールの返事を待っています。',
        type: 'main',
      },
      {
        reading: '事故',
        kana: 'じこ',
        meaning: ['Accident'],
        sentence: '事故が起きたので、交通が混雑しています。',
        type: 'main',
      },
      {
        reading: '用事',
        kana: 'ようじ',
        meaning: ['Errand', 'Business'],
        sentence: '今日は用事があるので、早めに帰ります。',
        type: 'secondary',
      },
      {
        reading: '事務所',
        kana: 'じむしょ',
        meaning: ['Office'],
        sentence: '事務所で書類を整理しています。',
        type: 'main',
      },
    ],
  },
]