export const KANJI_YDC_LESSON_24: Array<KanjiYDC> = [
  {
    kanji: '全',
    onyomi: ['ぜん'],
    kunyomi: ['まった', 'すべ'],
    meaning: ['Whole', 'All'],
    examples: [
      {
        reading: '全部',
        kana: 'ぜんぶ',
        meaning: ['All', 'Entirely'],
        sentence: '宿題は全部終わりました。',
        type: 'YDC_main',
      },
      {
        reading: '安全',
        kana: 'あんぜん',
        meaning: ['Safety', 'Secure'],
        sentence: '安全第一で行動しましょう。',
        type: 'YDC_main',
      },
      {
        reading: '全国',
        kana: 'ぜんこく',
        meaning: ['Nationwide', 'All over the country'],
        sentence: '全国の学校で運動会が行われます。',
        type: 'YDC_main',
      },
      {
        reading: '全員',
        kana: 'ぜんいん',
        meaning: ['All members', 'Everyone'],
        sentence: '全員が参加することが求められます。',
        type: 'YDC_main',
      },
      {
        reading: '全く',
        kana: 'まったく',
        meaning: ['Completely', 'Entirely'],
        sentence: '彼の話は全く理解できませんでした。',
        type: 'YDC_main',
      },
      {
        reading: '完全な',
        kana: 'かんぜんな',
        meaning: ['Perfect', 'Complete'],
        sentence: 'この計画は完全なものです。',
        type: 'secondary',
      },
      {
        reading: '全力',
        kana: 'ぜんりょく',
        meaning: ['All one\'s strength', 'Full power'],
        sentence: '全力を尽くして頑張ります。',
        type: 'main',
      },
      {
        reading: '全て',
        kana: 'すべて',
        meaning: ['Everything', 'All'],
        sentence: '全ての人に平等な権利があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '部',
    onyomi: ['ぶ'],
    kunyomi: [],
    meaning: ['Part', 'Section'],
    examples: [
      {
        reading: '全部',
        kana: 'ぜんぶ',
        meaning: ['All', 'Entirely'],
        sentence: '宿題は全部終わりました。',
        type: 'YDC_main',
      },
      {
        reading: '部屋',
        kana: 'へや',
        meaning: ['Room'],
        sentence: '私の部屋はとても広いです。',
        type: 'YDC_main',
      },
      {
        reading: '部長',
        kana: 'ぶちょう',
        meaning: ['Department head', 'Manager'],
        sentence: '彼は営業部の部長です。',
        type: 'YDC_main',
      },
      {
        reading: '一部',
        kana: 'いちぶ',
        meaning: ['One part', 'A section'],
        sentence: 'この本の一部を読みました。',
        type: 'YDC_main',
      },
      {
        reading: 'テニス部',
        kana: 'てにすぶ',
        meaning: ['Tennis team'],
        sentence: '私はテニス部に所属しています。',
        type: 'YDC_main',
      },
      {
        reading: '工学部',
        kana: 'こうがくぶ',
        meaning: ['Engineering department'],
        sentence: '彼は工学部で学んでいます。',
        type: 'YDC_main',
      },
      {
        reading: '大部分',
        kana: 'だいぶぶん',
        meaning: ['Majority', 'Most of...'],
        sentence: '大部分の学生が試験に合格しました。',
        type: 'YDC_main',
      },
    ],
  },
  {
    kanji: '必',
    onyomi: ['ひつ', 'ひっ'],
    kunyomi: ['かなら'],
    meaning: ['Surely'],
    examples: [
      {
        reading: '必要な',
        kana: 'ひつような',
        meaning: ['Necessary', 'Essential'],
        sentence: 'この資料は必要なものです。',
        type: 'YDC_main',
      },
      {
        reading: '必ず',
        kana: 'かならず',
        meaning: ['Surely', 'Without fail'],
        sentence: '明日は必ず来てください。',
        type: 'YDC_main',
      },
      {
        reading: '必ずしも',
        kana: 'かならずしも',
        meaning: ['Not always', 'Not necessarily'],
        sentence: '成功は必ずしも努力の結果ではありません。',
        type: 'main',
      },
      {
        reading: '必死',
        kana: 'ひっし',
        meaning: ['Desperate'],
        sentence: '彼は必死に仕事をしています。',
        type: 'secondary',
      },
      {
        reading: '必修',
        kana: 'ひっしゅう',
        meaning: ['Compulsory', 'Required'],
        sentence: 'この科目は必修です。',
        type: 'main',
      },
      {
        reading: '必需品',
        kana: 'ひつじゅひん',
        meaning: ['Necessities', 'Essential items'],
        sentence: '旅行には必需品を持って行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '要',
    onyomi: ['よう'],
    kunyomi: ['い', 'かなめ'],
    meaning: ['Neecessary'],
    examples: [
      {
        reading: '要る',
        kana: 'いる',
        meaning: ['To be needed', 'To require'],
        sentence: 'お金が要ります。',
        type: 'YDC_main',
      },
      {
        reading: '必要な',
        kana: 'ひつような',
        meaning: ['Necessary', 'Essential'],
        sentence: 'この資料は必要なものです。',
        type: 'YDC_main',
      },
      {
        reading: '重要な',
        kana: 'じゅうような',
        meaning: ['Important', 'Significant'],
        sentence: 'この会議は非常に重要なものです。',
        type: 'YDC_main',
      },
      {
        reading: '不要な',
        kana: 'ふような',
        meaning: ['Unnecessary', 'Not needed'],
        sentence: '不要なものは捨ててください。',
        type: 'main',
      },
      {
        reading: '要求',
        kana: 'ようきゅう',
        meaning: ['Demand', 'Request'],
        sentence: '彼は給料の増額を要求しました。',
        type: 'secondary',
      },
      {
        reading: '要約',
        kana: 'ようやく',
        meaning: ['Summary', 'Abstract'],
        sentence: 'この文章の要約を作成しました。',
        type: 'main',
      },
      {
        reading: '要するに',
        kana: 'ようするに',
        meaning: ['In short', 'To sum up'],
        sentence: '要するに、彼の言いたいことはこれです。',
        type: 'main',
      },
      {
        reading: '主要な',
        kana: 'しゅような',
        meaning: ['Main', 'Major'],
        sentence: 'この地域の主要な産業は農業です。',
        type: 'main',
      },
      {
        reading: 'チームの要',
        kana: 'チームのかなめ',
        meaning: ['The key player of the team'],
        sentence: '彼はチームの要として活躍しています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '荷',
    onyomi: ['か'],
    kunyomi: ['に'],
    meaning: ['Luggage'],
    examples: [
      {
        reading: '荷物',
        kana: 'にもつ',
        meaning: ['Luggage', 'Baggage'],
        sentence: '空港で荷物を受け取りました。',
        type: 'YDC_main',
      },
      {
        reading: '荷造り',
        kana: 'にづくり',
        meaning: ['Packing', 'Wrapping'],
        sentence: '旅行のために荷造りをしました。',
        type: 'main',
      },
      {
        reading: '重荷',
        kana: 'おもに',
        meaning: ['Heavy burden', 'Load'],
        sentence: '彼は家族の重荷を背負っています。',
        type: 'secondary',
      },
      {
        reading: '入荷',
        kana: 'にゅうか',
        meaning: ['Arrival of goods', 'Stock arrival'],
        sentence: '新しい商品が入荷しました。',
        type: 'main',
      },
      {
        reading: '出荷',
        kana: 'しゅっか',
        meaning: ['Shipping', 'Dispatch'],
        sentence: '商品を出荷する準備ができました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '由',
    onyomi: ['ゆ', 'ゆう', 'ゆい'],
    kunyomi: ['よし'],
    meaning: ['Reason', 'Cause'],
    examples: [
      {
        reading: '自由',
        kana: 'じゆう',
        meaning: ['Freedom', 'Liberty'],
        sentence: '私たちは自由に意見を言うことができます。',
        type: 'YDC_main',
      },
      {
        reading: '理由',
        kana: 'りゆう',
        meaning: ['Reason', 'Cause'],
        sentence: '遅れた理由を説明しました。',
        type: 'YDC_main',
      },
      {
        reading: 'パリ経由',
        kana: 'パリけいゆ',
        meaning: ['Via Paris'],
        sentence: 'この飛行機はパリ経由でロンドンに行きます。',
        type: 'secondary',
      },
      {
        reading: '不自由な',  
        kana: 'ふじゆうな',
        meaning: ['Inconvenient', 'Restricted'],
        sentence: 'この車椅子は不自由な動きしかできません。',
        type: 'main',
      },
      {
        reading: '由来',
        kana: 'ゆらい',
        meaning: ['Origin', 'Source'],
        sentence: 'この言葉の由来は古い時代にあります。',
        type: 'main',
      },
      {
        reading: '由緒ある',
        kana: 'ゆいしょある',
        meaning: ['Historic', 'Traditional', 'venerable'],
        sentence: 'この寺は由緒ある場所です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '届',
    onyomi: ['とど'],
    kunyomi: [],
    meaning: ['To Deliver', 'To Reach'],
    examples: [
      {
        reading: '届ける',  
        kana: 'とどける',
        meaning: ['To deliver', 'To send'],
        sentence: '手紙を友達に届けました。',
        type: 'YDC_main',
      },
      {
        reading: '届く',
        kana: 'とどく',
        meaning: ['To reach', 'To arrive', 'To be delivered'],
        sentence: '荷物が無事に届きました。',
        type: 'YDC_main',
      },
      {
        reading: '婚姻届',
        kana: 'こんいんとどけ',
        meaning: ['Marriage registration'],
        sentence: '結婚のために婚姻届を提出しました。',
        type: 'secondary',
      },
      {
        reading: '欠席届',
        kana: 'けっせきとどけ',
        meaning: ['Registration of absence'],
        sentence: '学校に欠席届を出しました。',
        type: 'secondary',
      },
      {
        reading: '届け出る',
        kana: 'とどけでる',
        meaning: ['To report', 'To notify'],
        sentence: '警察に事件を届け出ました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '利',
    onyomi: ['り'],
    kunyomi: ['き'],
    meaning: ['Profit', 'Advantage'],
    examples: [
      {
        reading: '便利な',  
        kana: 'べんりな',
        meaning: ['Convenient', 'Handy'],
        sentence: 'このアプリはとても便利です。',
        type: 'YDC_main',
      },
      {
        reading: '利用する',
        kana: 'りようする',
        meaning: ['To use', 'To utilize'],
        sentence: '図書館を利用して勉強します。',
        type: 'YDC_main',
      },
      {
        reading: '利益',
        kana: 'りえき',
        meaning: ['Profit', 'Gain'],
        sentence: '会社の利益が増加しました。',
        type: 'secondary',
      },
      {
        reading: '利口な',
        kana: 'りこうな',
        meaning: ['Clever', 'Smart'],
        sentence: '彼はとても利口な子供です。',
        type: 'secondary',
      },
      {
        reading: '権利',
        kana: 'けんり',
        meaning: ['Rights'],
        sentence: 'すべての人には平等な権利があります。',
        type: 'secondary',
      },
      {
        reading: '利子',
        kana: 'りし',
        meaning: ['Interest (on money)'],
        sentence: '銀行に預けたお金に利子がつきます。',
        type: 'main',
      },
      {
        reading: '左利き',
        kana: 'ひだりきき',
        meaning: ['Left-handed'],
        sentence: '彼は左利きなので、左手で書きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '払',
    onyomi: ['ふつ', 'ふっ'],
    kunyomi: ['はら'],
    meaning: ['To pay'],
    examples: [
      {
        reading: '払う',
        kana: 'はらう',
        meaning: ['To pay', 'To clear'],
        sentence: '電気代を払いました。',
        type: 'YDC_main',
      },
      {
        reading: '支払い',
        kana: 'しはらい',
        meaning: ['Payment'],
        sentence: '商品の支払いは現金でお願いします。',
        type: 'main',
      },
      {
        reading: '払い戻す',
        kana: 'はらいもどす',
        meaning: ['To refund', 'To return money'],
        sentence: 'チケットの払い戻しを受けました。',
        type: 'main',
      },
      {
        reading: '払い込む',
        kana: 'はらいこむ',
        meaning: ['To pay in', 'To deposit'],
        sentence: '銀行にお金を払い込みました。',
        type: 'main',
      },
      {
        reading: '払拭する',
        kana: 'ふっしょくする',
        meaning: ['To wipe out', 'To dispel'],
        sentence: '不安を払拭するために努力しています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '濯',
    onyomi: ['たく'],
    kunyomi: [],
    meaning: ['Wash'],
    examples: [
      {
        reading: '洗濯する',
        kana: 'せんたくする',
        meaning: ['To wash', 'To do laundry'],
        sentence: '毎週末に洗濯をします。',
        type: 'YDC_main',
      },
      {
        reading: '洗濯物',
        kana: 'せんたくもの',
        meaning: ['Laundry', 'Washing'],
        sentence: '洗濯物を干しました。',
        type: 'YDC_main',
      },
      {
        reading: '洗濯機',
        kana: 'せんたくき',
        meaning: ['Washing machine'],
        sentence: '新しい洗濯機を買いました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '寝',
    onyomi: ['しん'],
    kunyomi: ['ね'],
    meaning: ['To sleep', 'To lie down'],
    examples: [
      {
        reading: '寝る',
        kana: 'ねる',
        meaning: ['To sleep', 'To go to bed'],
        sentence: '毎晩10時に寝ます。',
        type: 'YDC_main',
      },
      {
        reading: '昼寝',
        kana: 'ひるね',
        meaning: ['Nap', 'Siesta'],
        sentence: '昼寝をすると、午後の仕事がはかどります。',
        type: 'YDC_main',
      },
      {
        reading: '寝坊',
        kana: 'ねぼう',
        meaning: ['Oversleeping'],
        sentence: '寝坊して学校に遅刻しました。',
        type: 'secondary',
      },
      {
        reading: '寝室',
        kana: 'しんしつ',
        meaning: ['Bedroom'],
        sentence: '寝室は静かな場所にあります。',
        type: 'main',
      },
      {
        reading: '寝台車',
        kana: 'しんだいしゃ',
        meaning: ['Sleeper car', 'Sleeping car'],
        sentence: '寝台車で長距離旅行をしました。',
        type: 'secondary',
      },
      {
        reading: '寝言',
        kana: 'ねごと',
        meaning: ['Sleep talking'],
        sentence: '彼は寝言を言うことがあります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '踊',
    onyomi: ['よう'],
    kunyomi: ['おど'],
    meaning: ['To dance'],
    examples: [
      {
        reading: '踊る',
        kana: 'おどる',
        meaning: ['To dance'],
        sentence: 'パーティーでみんなで踊りました。',
        type: 'YDC_main',
      },
      {
        reading: '踊り',
        kana: 'おどり',
        meaning: ['Dance'],
        sentence: '日本の伝統的な踊りを学びました。',
        type: 'YDC_main',
      },
      {
        reading: '日本舞踊',
        kana: 'にほんぶよう',
        meaning: ['Japanese traditional dance'],
        sentence: '日本舞踊のクラスに参加しています。',
        type: 'secondary',
      },
      {
        reading: '盆踊り',
        kana: 'ぼんおどり',
        meaning: ['Bon dance'],
        sentence: '夏祭りで盆踊りを楽しみました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '活',
    onyomi: ['かつ', 'かっ'],
    kunyomi: [],
    meaning: ['Active', 'Lively'],
    examples: [
      {
        reading: '生活',
        kana: 'せいかつ',
        meaning: ['Life', 'Living'],
        sentence: '東京での生活は忙しいです。',
        type: 'YDC_main',
      },
      {
        reading: '活動',
        kana: 'かつどう',
        meaning: ['Activity', 'Action'],
        sentence: '地域の清掃活動に参加しました。',
        type: 'YDC_main',
      },
      {
        reading: '活字',
        kana: 'かつじ',
        meaning: ['Printed matter', 'Type'],
        sentence: '活字を読むのが好きです。',
        type: 'secondary',
      },
      {
        reading: '活気',
        kana: 'かっき',
        meaning: ['Vigor', 'Liveliness'],
        sentence: 'この町は活気にあふれています。',
        type: 'secondary',
      },
      {
        reading: '活躍する',
        kana: 'かつやくする',
        meaning: ['To play an active role', 'To be active'],
        sentence: '彼はスポーツで活躍しています。',
        type: 'main',
      },
      {
        reading: '活用',
        kana: 'かつよう',
        meaning: ['Conjugation'],
        sentence: 'この文法を活用して文章を書きます。',
        type: 'secondary',
      },
      {
        reading: '活発な',
        kana: 'かっぱつな',
        meaning: ['Active', 'Energetic', 'Lively'],
        sentence: '彼は活発な性格で、いつも元気です。',
        type: 'main',
      },
      {
        reading: '食生活',
        kana: 'しょくせいかつ',
        meaning: ['Diet', 'Eating habits'],
        sentence: '健康のために食生活を見直しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '末',
    onyomi: ['まつ', 'ばつ'],
    kunyomi: ['すえ'],
    meaning: ['End', 'Tip'],
    examples: [
      {
        reading: '週末',
        kana: 'しゅうまつ',
        meaning: ['Weekend'],
        sentence: '週末は友達と遊びます。',
        type: 'YDC_main',
      },
      {
        reading: '月末',
        kana: 'げつまつ',
        meaning: ['End of the month'],
        sentence: '月末に給料が支給されます。',
        type: 'YDC_main',
      },
      {
        reading: '年末',
        kana: 'ねんまつ',
        meaning: ['End of the year'],
        sentence: '年末には大掃除をします。',
        type: 'YDC_main',
      },
      {
        reading: '末',
        kana: 'すえ',
        meaning: ['End of a period'],
        sentence: 'このペンの末が細くなっています。',
        type: 'YDC_main',
      },
      {
        reading: '末っ子',
        kana: 'すえっこ',
        meaning: ['Youngest child'],
        sentence: '彼は家族の末っ子です。',
        type: 'YDC_main',
      },
      {
        reading: '期末試験',
        kana: 'きまつしけん',
        meaning: ['Final exam'],
        sentence: '期末試験の準備をしています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '宅',
    onyomi: ['たく'],
    kunyomi: [],
    meaning: ['Home', 'House'],
    examples: [
      {
        reading: 'お宅',
        kana: 'おたく',
        meaning: ['Someone\'s house (Polite)'],
        sentence: 'お宅にお邪魔してもいいですか？',
        type: 'YDC_main',
      },
      {
        reading: '帰宅',
        kana: 'きたく',
        meaning: ['Returning home'],
        sentence: '仕事が終わったら帰宅します。',
        type: 'YDC_main',
      },
      {
        reading: '自宅',
        kana: 'じたく',
        meaning: ['One\'s own home'],
        sentence: '自宅でリモートワークをしています。',
        type: 'YDC_main',
      },
      {
        reading: '住宅',
        kana: 'じゅうたく',
        meaning: ['House', 'Residence'],
        sentence: '新しい住宅地が開発されています。',
        type: 'main',
      },
      {
        reading: '宅配便',
        kana: 'たくはいびん',
        meaning: ['Home delivery service'],
        sentence: '宅配便で荷物が届きました。',
        type: 'main',
      },
      {
        reading: '社宅',
        kana: 'しゃたく',
        meaning: ['Company housing'],
        sentence: '彼は会社の社宅に住んでいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '祭',
    onyomi: ['さい'],
    kunyomi: ['まつ'],
    meaning: ['Festival'],
    examples: [
      {
        reading: '祭り・祭',
        kana: 'まつり',
        meaning: ['Festival'],
        sentence: '夏祭りはとても楽しいです。',
        type: 'YDC_main',
      },
      {
        reading: '祭日',
        kana: 'さいじつ',
        meaning: ['Holiday', 'National holiday'],
        sentence: '今日は祭日なので、学校は休みです。',
        type: 'main',
      },
      {
        reading: '学園祭',
        kana: 'がくえんさい',
        meaning: ['School festival'],
        sentence: '学園祭の準備で忙しいです。',
        type: 'main',
      },
      {
        reading: '夏祭り',
        kana: 'なつまつり',
        meaning: ['Summer festival'],
        sentence: '夏祭りでは花火が上がります。',
        type: 'secondary',
      },
      {
        reading: '祭る',
        kana: 'まつる',
        meaning: ['To deify', 'To enshrine'],
        sentence: '神社に神を祭ります。',
        type: 'secondary',
      },
    ],
  },
]