export const KANJI_YDC_LESSON_12: Array<KanjiYDC> = [
  {
    kanji: '音',
    onyomi: ['おん', 'いん'],
    kunyomi: ['おと', 'ね'],
    meaning: ['Sound'],
    examples: [
      {
        reading: '音',
        kana: 'おと',
        meaning: ['Sound'],
        sentence: '音が聞こえる。',
        type: 'main',
      },
      {
        reading: '音楽',
        kana: 'おんがく',
        meaning: ['Music'],
        sentence: '音楽を聞きながら、働きます。',
        type: 'main',
      },
      {
        reading: '発音',
        kana: 'はつおん',
        meaning: ['Pronunciation'],
        sentence: '発音が難しい。',
        type: 'secondary',
      },
      {
        reading: '録音',
        kana: 'ろくおん',
        meaning: ['Recording'],
        sentence: '録音を聞きます。',
        type: 'main',
      },
      {
        reading: '音量',
        kana: 'おんりょう',
        meaning: ['Volume'],
        sentence: '音量を下げてください。',
        type: 'main',
      },
      {
        reading: '母音',
        kana: 'ぼいん',
        meaning: ['Vowel'],
        sentence: '母音を覚えます。',
        type: 'secondary',
      },
      {
        reading: '子音',
        kana: 'しいん',
        meaning: ['Consonant'],
        sentence: '子音を覚えます。',
        type: 'secondary',
      },
      {
        reading: '本音',
        kana: 'ほんね',
        meaning: ['True feelings', 'One’s real intention'],
        sentence: '本音を言ってください。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '楽',
    onyomi: ['がく', 'らく', 'がっ'],
    kunyomi: ['たの'],
    meaning: ['Fun', 'Comfortable'],
    examples: [
      {
        reading: '音楽',
        kana: 'おんがく',
        meaning: ['Music'],
        sentence: '音楽を聞きながら、働きます。',
        type: 'main',
      },
      {
        reading: '楽しい',
        kana: 'たのしい',
        meaning: ['Fun', 'Enjoyable'],
        sentence: '楽しい時間を過ごします。',
        type: 'main',
      },
      {
        reading: '楽しみ',
        kana: 'たのしみ',
        meaning: ['Fun'],
        sentence: '楽しみにしています。',
        type: 'main',
      },
      {
        reading: '楽しむ',
        kana: 'たのしむ',
        meaning: ['To enjoy', 'To have fun'],
        sentence: '楽しんで下さい。',
        type: 'main',
      },
      {
        reading: '楽な',
        kana: 'らくな',
        meaning: ['Easy', 'Comfortable'],
        sentence: '楽な仕事です。',
        type: 'secondary',
      },
      {
        reading: '楽器',
        kana: 'がっき',
        meaning: ['Musical instrument'],
        sentence: '楽器を演奏します。',
        type: 'main',
      },
      {
        reading: '娯楽',
        kana: 'ごらく',
        meaning: ['Entertainment'],
        sentence: '娯楽を楽しむ。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '歌',
    onyomi: ['か'],
    kunyomi: ['うた'],
    meaning: ['Song', 'To sing'],
    examples: [
      {
        reading: '歌',
        kana: 'うた',
        meaning: ['Song'],
        sentence: '歌を歌います。',
        type: 'main',
      },
      {
        reading: '歌う',
        kana: 'うたう',
        meaning: ['To sing'],
        sentence: '歌を歌います。',
        type: 'main',
      },
      {
        reading: '歌手',
        kana: 'かしゅ',
        meaning: ['Singer'],
        sentence: '歌手になりたい。',
        type: 'main',
      },
      {
        reading: '歌詞',
        kana: 'かし',
        meaning: ['Lyrics'],
        sentence: '歌詞を覚えます。',
        type: 'main',
      },
      {
        reading: '短歌',
        kana: 'たんか',
        meaning: ['Tanka', '31-syllable poem'],
        sentence: '短歌を詠む。',
        type: 'secondary',
      },
      {
        reading: '国歌',
        kana: 'こっか',
        meaning: ['National anthem'],
        sentence: '国歌を歌います。',
        type: 'main',
      },
      {
        reading: '校歌',
        kana: 'こうか',
        meaning: ['School song'],
        sentence: '校歌を歌います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '自',
    onyomi: ['じ', 'し'],
    kunyomi: ['みずか'],
    meaning: ['Self'],
    examples: [
      {
        reading: '自分',
        kana: 'じぶん',
        meaning: ['oneself'],
        sentence: '自分でやってみてください。',
        type: 'main',
      },
      {
        reading: '自転車',
        kana: 'じてんしゃ',
        meaning: ['Bicycle'],
        sentence: '自転車で通勤します。',
        type: 'main',
      },
      {
        reading: '自動車',
        kana: 'じどうしゃ',
        meaning: ['Automobile'],
        sentence: '自動車で通勤します。',
        type: 'main',
      },
      {
        reading: '自由',
        kana: 'じゆう',
        meaning: ['Freedom'],
        sentence: '自由にしてください。',
        type: 'main',
      },
      {
        reading: '自ら',
        kana: 'みずから',
        meaning: ['For oneself'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '自然',
        kana: 'しぜん',
        meaning: ['Nature'],
        sentence: '自然を楽しむ。',
        type: 'secondary',
      },
      {
        reading: '自習',
        kana: 'じしゅう',
        meaning: ['Self-study'],
        sentence: '自習をします。',
        type: 'secondary',
      },
      {
        reading: '自信',
        kana: 'じしん',
        meaning: ['Self-confidence'],
        sentence: '自信を持ってください。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '転',
    onyomi: ['てん'],
    kunyomi: ['ころ'],
    meaning: ['To roll over'],
    examples: [
      {
        reading: '自転車',
        kana: 'じてんしゃ',
        meaning: ['Bicycle'],
        sentence: '自転車で通勤します。',
        type: 'main',
      },
      {
        reading: '運転',
        kana: 'うんてん',
        meaning: ['Driving'],
        sentence: '運転が上手です。',
        type: 'main',
      },
      {
        reading: '運転手',
        kana: 'うんてんしゅ',
        meaning: ['Driver'],
        sentence: '運転手がとても上手です。',
        type: 'main',
      },
      {
        reading: '転ぶ',
        kana: 'ころぶ',
        meaning: ['To fall down', 'To tumble'],
        sentence: '転ばないように気をつけてください。',
        type: 'secondary',
      },
      {
        reading: '転がる',
        kana: 'ころがる',
        meaning: ['To roll'],
        sentence: 'ボールが転がります。',
        type: 'secondary',
      },
      {
        reading: '回転ずし',
        kana: 'かいてんずし',
        meaning: ['Conveyor belt sushi'],
        sentence: '回転ずしに行きます。',
        type: 'secondary',
      },
      {
        reading: '転職',
        kana: 'てんしょく',
        meaning: ['Changing jobs'],
        sentence: '転職を考えています。',
        type: 'main',
      },
      {
        reading: '転校',
        kana: 'てんこう',
        meaning: ['Changing schools'],
        sentence: '転校します。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '乗',
    onyomi: ['じょう'],
    kunyomi: ['の'],
    meaning: ['To get on', 'To ride'],
    examples: [
      {
        reading: '乗る',
        kana: 'のる',
        meaning: ['To get on', 'To ride'],
        sentence: '電車に乗ります。',
        type: 'main',
      },
      {
        reading: '乗り物',
        kana: 'のりもの',
        meaning: ['Vehicle'],
        sentence: '乗り物が好きです。',
        type: 'main',
      },
      {
        reading: '乗り換える',
        kana: 'のりかえる',
        meaning: ['To transfer'],
        sentence: '乗り換えてください。',
        type: 'main',
      },
      {
        reading: '乗車',
        kana: 'じょうしゃ',
        meaning: ['Riding a car'],
        sentence: '乗車券を買います。',
        type: 'main',
      },
      {
        reading: '乗客',
        kana: 'じょうきゃく',
        meaning: ['Passenger'],
        sentence: '乗客が多い。',
        type: 'main',
      },
      {
        reading: '乗せる',
        kana: 'のせる',
        meaning: ['To  put on', 'To load'],
        sentence: '荷物を乗せます。',
        type: 'secondary',
      },
      {
        reading: '乗馬',
        kana: 'じょうば',
        meaning: ['Horseback riding'],
        sentence: '乗馬をします。',
        type: 'main',
      },
      {
        reading: '乗車券',
        kana: 'じょうしゃけん',
        meaning: ['Train ticket'],
        sentence: '乗車券を買います。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '写',
    onyomi: ['しゃ'],
    kunyomi: ['うつ'],
    meaning: ['Photograph', 'To copy'],
    examples: [
      {
        reading: '写真',  
        kana: 'しゃしん',
        meaning: ['Photograph'],
        sentence: '写真を撮ります。',
        type: 'main',
      },
      {
        reading: '写す',
        kana: 'うつす',
        meaning: ['To copy', 'To photograph'],
        sentence: '写真を撮ります。',
        type: 'main',
      },
      {
        reading: '写真家',
        kana: 'しゃしんか',
        meaning: ['Photographer'],
        sentence: '写真家になりたい。',
        type: 'main',
      },
      {
        reading: '写生',
        kana: 'しゃせい',
        meaning: ['Sketch'],
        sentence: '写生をします。',
        type: 'main',
      },
      {
        reading: '複写',
        kana: 'ふくしゃ',
        meaning: ['Copy', 'Duplicate'],
        sentence: '複写をします。',
        type: 'main',
      },
      {
        reading: '描写する',
        kana: 'びょうしゃする',
        meaning: ['To describe', 'To depict'],
        sentence: '描写する。',
        type: 'main',
      },
      {
        reading: '写実主義',
        kana: 'しゃじつしゅぎ',
        meaning: ['Realism'],
        sentence: '写実主義の絵画。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '真',
    onyomi: ['しん'],
    kunyomi: ['ま'],
    meaning: ['True', 'Real'],
    examples: [
      {
        reading: '写真',  
        kana: 'しゃしん',
        meaning: ['Photograph'],
        sentence: '写真を撮ります。',
        type: 'main',
      },
      {
        reading: '真ん中',
        kana: 'まんなか',
        meaning: ['Middle', 'Center'],
        sentence: '真ん中に座ってください。',
        type: 'main',
      },
      { 
        reading: '真っ黒',
        kana: 'まっくろ',
        meaning: ['Pitch black'],
        sentence: '真っ黒な空。',
        type: 'main',
      },
      {
        reading: '真っ白',
        kana: 'まっしろ',
        meaning: ['Snow white'],
        sentence: '真っ白な雪。',
        type: 'main',
      },
      {
        reading: '真夜中',
        kana: 'まよなか',
        meaning: ['Midnight'],
        sentence: '真夜中に帰ります。',
        type: 'main',
      },
      {
        reading: '真剣',
        kana: 'しんけん',
        meaning: ['Serious', 'Earnest'],
        sentence: '真剣に取り組む。',
        type: 'secondary',
      },
      {
        reading: '真実',
        kana: 'しんじつ',
        meaning: ['Truth'],
        sentence: '真実を知りたい。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '台',
    onyomi: ['だい', 'たい'],
    kunyomi: [],
    meaning: ['Stand', 'Rack'],
    examples: [
      {
        reading: '台所',
        kana: 'だいどころ',
        meaning: ['Kitchen'],
        sentence: '台所で料理します。',
        type: 'main',
      },
      {
        reading: '二台',
        kana: 'にだい',
        meaning: ['Two (machines)'],
        sentence: '二台のパソコン。',
        type: 'main',
      },
      {
        reading: '台風',
        kana: 'たいふう',
        meaning: ['Typhoon'],
        sentence: '台風が来ます。',
        type: 'main',
      },
      {
        reading: '台',
        kana: 'だい',
        meaning: ['Stand', 'board'],
        sentence: '机の台。',
        type: 'secondary',
      },
      {
        reading: '舞台',
        kana: 'ぶたい',
        meaning: ['Stage'],
        sentence: '舞台に立つ。',
        type: 'main',
      },
      {
        reading: '台湾',
        kana: 'たいわん',
        meaning: ['Taiwan'],
        sentence: '台湾に行きます。',
        type: 'main',
      },
      {
        reading: '台本',
        kana: 'だいほん',
        meaning: ['Script', 'Scenario'],
        sentence: '台本を読みます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '央',
    onyomi: ['おう'],
    kunyomi: [],
    meaning: ['Center'],
    examples: [ 
      {
        reading: '中央',
        kana: 'ちゅうおう',
        meaning: ['Center'],
        sentence: '中央に座ってください。',
        type: 'main',
      },
      {
        reading: '中央線',
        kana: 'ちゅうおうせん',
        meaning: ['Chuo Line'],
        sentence: '中央線に乗ります。',
        type: 'main',
      },
      {
        reading: '中央集権',
        kana: 'ちゅうおうしゅうけん',
        meaning: ['Centralization of government'],
        sentence: '中央集権の政府。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '映',
    onyomi: ['えい'],
    kunyomi: ['うつ', 'は'],
    meaning: ['To project', 'To reflect'],
    examples: [
      {
        reading: '映画',
        kana: 'えいが',
        meaning: ['Movie'],
        sentence: '映画を見ます。',
        type: 'main',
      },
      {
        reading: '映画館',
        kana: 'えいがかん',
        meaning: ['Movie theater'],
        sentence: '映画館に行きます。',
        type: 'main',
      },
      {
        reading: '映る',
        kana: 'うつる',
        meaning: ['To be projected'],
        sentence: '映る映画。',
        type: 'secondary',
      },
      {
        reading: '映す',
        kana: 'うつす',
        meaning: ['To project'],
        sentence: '映す映画。',
        type: 'secondary',
      },
      {
        reading: '反映する',
        kana: 'はんえいする',
        meaning: ['To reflect'],
        sentence: '反映する。',
        type: 'secondary',
      },
      {
        reading: '放映する',
        kana: 'ほうえいする',
        meaning: ['To broadcast', 'To televise'],
        sentence: '放映する。',
        type: 'main',
      },
      {
        reading: '映える',
        kana: 'はえる',
        meaning: ['To shine', 'To stand out'],
        sentence: '映える景色。',
        type: 'secondary',
      },
      {
        reading: '上映する',
        kana: 'じょうえいする',
        meaning: ['To show (Films)', 'To screen'],
        sentence: '明日上映します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '画',
    onyomi: ['が', 'かく'],
    kunyomi: [],
    meaning: ['Drawing', 'Picture'],
    examples: [
      {
        reading: '映画',
        kana: 'えいが',
        meaning: ['Movie'],
        sentence: '映画を見ます。',
        type: 'main',
      },
      {
        reading: '漫画',
        kana: 'まんが',
        meaning: ['Comic'],
        sentence: '漫画を読みます。',
        type: 'main',
      },
      {
        reading: '計画',
        kana: 'けいかく',
        meaning: ['Plan'],
        sentence: '計画を立てます。',
        type: 'main',
      },
      {
        reading: '画家',
        kana: 'がか',
        meaning: ['Painter'],
        sentence: '画家になりたい。',
        type: 'secondary',
      },
      {
        reading: '絵画',
        kana: 'かいが',
        meaning: ['Painting'],
        sentence: '絵画を描きます。',
        type: 'secondary',
      },
      {
        reading: '画数',
        kana: 'かくすう',
        meaning: ['Stroke count (of a kanji)'],
        sentence: '画数を数えます。',
        type: 'secondary',
      },
      {
        reading: '画素',
        kana: 'がそ',
        meaning: ['Pixel'],
        sentence: '画素数。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '羊',
    onyomi: ['よう'],
    kunyomi: ['ひつじ'],
    meaning: ['Sheep'],
    examples: [
      {
        reading: '羊',
        kana: 'ひつじ',
        meaning: ['Sheep'],
        sentence: '羊がいます。',
        type: 'main',
      },
      {
        reading: '小羊',
        kana: 'こひつじ',
        meaning: ['Lamb'],
        sentence: '小羊がいます。',
        type: 'secondary',
      },
      {
        reading: '羊毛',
        kana: 'ようもう',
        meaning: ['Wool'],
        sentence: '羊毛を使います。',
        type: 'secondary',
      },
      {
        reading: '山羊',
        kana: 'やぎ',
        meaning: ['Goat'],
        sentence: '山羊がいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '洋',
    onyomi: ['よう'],
    kunyomi: [],
    meaning: ['Oversea'],
    examples: [
      {
        reading: '洋服',
        kana: 'ようふく',
        meaning: ['Western-style clothes'],
        sentence: '洋服を着ます。',
        type: 'main',
      },
      {
        reading: '西洋',
        kana: 'せいよう',
        meaning: ['Western countries'],
        sentence: '西洋の文化。',
        type: 'secondary',
      },
      {
        reading: '東洋',
        kana: 'とうよう',
        meaning: ['Eastern countries'],
        sentence: '東洋の文化。',
        type: 'secondary',
      },
      {
        reading: '太平洋',
        kana: 'たいへいよう',
        meaning: ['Pacific Ocean'],
        sentence: '太平洋に行きます。',
        type: 'secondary',
      },
      {
        reading: '大西洋',
        kana: 'たいせいよう',
        meaning: ['Atlantic Ocean'],
        sentence: '大西洋に行きます。',
        type: 'secondary',
      },
      {
        reading: '洋式',
        kana: 'ようしき',
        meaning: ['Western style'],
        sentence: '洋式の建物。',
        type: 'secondary',
      },
      {
        reading: '洋食',
        kana: 'ようしょく',
        meaning: ['Western food'],
        sentence: '洋食を食べます。',
        type: 'main',
      },
      {
        reading: '洋書',
        kana: 'ようしょ',
        meaning: ['Western book'],
        sentence: '洋書を読みます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '服',
    onyomi: ['ふく'],
    kunyomi: [],
    meaning: ['Clothes', 'To submit'],
    examples: [
      {
        reading: '服',
        kana: 'ふく',
        meaning: ['Clothes'],
        sentence: '服を着ます。',
        type: 'main',
      },
      {
        reading: '洋服',
        kana: 'ようふく',
        meaning: ['Western-style clothes'],
        sentence: '洋服を着ます。',
        type: 'main',
      },
      {
        reading: '和服',
        kana: 'わふく',
        meaning: ['Japanese-style clothes'],
        sentence: '和服を着ます。',
        type: 'main',
      },
      {
        reading: '服装',
        kana: 'ふくそう',
        meaning: ['Costume'],
        sentence: '服装を決めます。',
        type: 'main',
      },
      {
        reading: '克服する',
        kana: 'こくふくする',
        meaning: ['To overcome'],
        sentence: '克服する。',
        type: 'secondary',
      },
      {
        reading: '制服',
        kana: 'せいふく',
        meaning: ['Uniform'],
        sentence: '制服を着ます。',
        type: 'secondary',
      },
      {
        reading: '喪服',
        kana: 'もふく',
        meaning: ['Mourning clothes'],
        sentence: '喪服を着ます。',
        type: 'secondary',
      },
      {
        reading: '征服',
        kana: 'せいふく',
        meaning: ['Conquest'],
        sentence: '征服する。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '着',
    onyomi: ['ちゃく', 'じゃく'],
    kunyomi: ['き', 'ぎ', 'つ'],
    meaning: ['To wear', 'To arrive', 'To reach'],
    examples: [
      {
        reading: '着る',
        kana: 'きる',
        meaning: ['To wear'],
        sentence: '服を着ます。',
        type: 'main',
      },
      {
        reading: '上着',
        kana: 'うわぎ',
        meaning: ['Jacket'],
        sentence: '上着を着ます。',
        type: 'main',
      },
      {
        reading: '下着',
        kana: 'したぎ',
        meaning: ['Underwear'],
        sentence: '下着を着ます。',
        type: 'main',
      },
      {
        reading: '着く',
        kana: 'つく',
        meaning: ['To arrive', 'To reach'],
        sentence: '着きました。',
        type: 'main',
      },
      {
        reading: '着物',
        kana: 'きもの',
        meaning: ['Kimono'],
        sentence: '着物を着ます。',
        type: 'main',
      },
      {
        reading: '到着',
        kana: 'とうちゃく',
        meaning: ['Arrival'],
        sentence: '到着しました。',
        type: 'main',
      },
      {
        reading: '落ち着く',
        kana: 'おちつく',
        meaning: ['To calm down'],
        sentence: '落ち着いてください。',
        type: 'main',
      },
      {
        reading: '水着',
        kana: 'みずぎ',
        meaning: ['Swimsuit'],
        sentence: '水着を着ます。',
        type: 'main',
      },
    ],
  },
]