export const KANJI_YDC_LESSON_10: Array<KanjiYDC> = [
  {
    kanji: '山',
    onyomi: ['さん', 'ざん'],
    kunyomi: ['やま'],
    meaning: ['Mountain'],
    examples: [
      {
        reading: '山',
        kana: 'やま',
        meaning: ['Mountain'],
        sentence: '山が見えます。',
        type: 'main',
      },
      {
        reading: '山道',
        kana: 'やまみち',
        meaning: ['Mountain path', 'Mountain road'],
        sentence: '山道を歩いています。',
        type: 'main',
      },
      {
        reading: '富士山',
        kana: 'ふじさん',
        meaning: ['Mount Fuji'],
        sentence: '富士山に行きます。',
        type: 'secondary',
      },
      {
        reading: '火山',
        kana: 'かざん',
        meaning: ['Volcano'],
        sentence: '火山が噴火しました。',
        type: 'secondary',
      },
      {
        reading: '山火事',
        kana: 'やまかじ',
        meaning: ['Mountain fire', 'Forest fire'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '登山',
        kana: 'とざん',
        meaning: ['Mountain climbing'],
        sentence: '登山が好きです。',
        type: 'secondary',
      },
      {
        reading: '山林',
        kana: 'さんりん',
        meaning: ['Mountain forest'],
        sentence: '山林が広がっています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '川',
    onyomi: ['せん'],
    kunyomi: ['かわ', 'がわ'],
    meaning: ['River'],
    examples: [
      {
        reading: '川',
        kana: 'かわ',
        meaning: ['River'],
        sentence: '川が流れています。',
        type: 'main',
      },
      {
        reading: '小川さん',
        kana: 'おがわさん',
        meaning: ['Mr. Ogawa'],
        sentence: '小川さんがいます。',
        type: 'main',
      },
      {
        reading: 'ナイル川',
        kana: 'ナイルがわ',
        meaning: ['Nile River'],
        sentence: 'ナイル川に行きます。',
        type: 'secondary',
      },
      {
        reading: '天の川',
        kana: 'あまのがわ',
        meaning: ['Milky Way'],
        sentence: '天の川が綺麗です。',
        type: 'secondary',
      },
      {
        reading: '河岸',
        kana: 'かがん',
        meaning: ['Riverbank', 'Riverside'],
        sentence: '河岸で散歩します。',
        type: 'secondary',
      },
      {
        reading: '川遊び',
        kana: 'かわあそび',
        meaning: ['River play', 'Outing to the riverside'],
        sentence: '川遊びに行きます。',
        type: 'secondary',
      },
      {
        reading: '河川',
        kana: 'かせん',
        meaning: ['Rivers'],
        sentence: '河川が増水しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '林',
    onyomi: ['りん'],
    kunyomi: ['はやし', 'ばやし'],
    meaning: ['Woods', 'Small forest', 'Grove'],
    examples: [
      {
        reading: '林',
        kana: 'はやし',
        meaning: ['Small forest', 'Woods'],
        sentence: '林が広がっています。',
        type: 'main',
      },
      {
        reading: '小林さん',
        kana: 'こばやしさん',
        meaning: ['Mr. Kobayashi'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '森林',
        kana: 'しんりん',
        meaning: ['Forest'],
        sentence: '森林が広がっています。',
        type: 'secondary',
      },
      {
        reading: '山林',
        kana: 'さんりん',
        meaning: ['Mountain forest'],
        sentence: '山林が広がっています。',
        type: 'secondary',
      },
      {
        reading: '林業',
        kana: 'りんぎょう',
        meaning: ['Forestry'],
        sentence: '林業が盛んです。',
        type: 'secondary',
      },
      {
        reading: '松林',
        kana: 'まつばやし',
        meaning: ['Pine forest'],
        sentence: '松林が広がっています。',
        type: 'secondary',
      },
      {
        reading: '林道',
        kana: 'りんどう',
        meaning: ['Forest road', 'Path through the woods'],
        sentence: '林道を歩いています。',
        type: 'secondary',
      },
      {
        reading: '密林',
        kana: 'みつりん',
        meaning: ['Thick forest', 'Jungle'],
        sentence: '密林が広がっています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '森',
    onyomi: ['しん'],
    kunyomi: ['もり'],
    meaning: ['Forest'],
    examples: [
      {
        reading: '森',
        kana: 'もり',
        meaning: ['Forest'],
        sentence: '森が広がっています。',
        type: 'main',
      },
      {
        reading: '森田さん',
        kana: 'もりたさん',
        meaning: ['Mr. Morita'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '森林',
        kana: 'しんりん',
        meaning: ['Forest'],
        sentence: '森林が広がっています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '空',
    onyomi: ['くう'],
    kunyomi: ['そら', 'ぞら', 'から', 'あ'],
    meaning: ['Sky', 'Empty'],
    examples: [
      {
        reading: '空',
        kana: 'そら',
        meaning: ['Sky'],
        sentence: '空が青いです。',
        type: 'main',
      },
      {
        reading: '空気',
        kana: 'くうき',
        meaning: ['Air'],
        sentence: '空気が澄んでいます。',
        type: 'main',
      },
      {
        reading: '空港',
        kana: 'くうこう',
        meaning: ['Airport'],
        sentence: '空港に行きます。',
        type: 'secondary',
      },
      {
        reading: '航空便',
        kana: 'こうくうびん',
        meaning: ['Airmail'],
        sentence: '航空便で送ります。',
        type: 'secondary',
      },
      {
        reading: '空手',
        kana: 'からて',
        meaning: ['Karate'],
        sentence: '空手を習います。',
        type: 'secondary',
      },
      {
        reading: '空く',
        kana: 'あく',
        meaning: ['To become empty', 'To become vacant'],
        sentence: '空いていますか。',
        type: 'secondary',
      },
      {
        reading: '空っぽ',
        kana: 'からっぽ',
        meaning: ['Empty'],
        sentence: '空っぽです。',
        type: 'secondary',
      },
      {
        reading: '大空',
        kana: 'おおぞら',
        meaning: ['Big Sky'],
        sentence: '大空が広がっています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '海',
    onyomi: ['かい'],
    kunyomi: ['うみ'],
    meaning: ['Sea', 'Ocean'],
    examples: [
      {
        reading: '海',
        kana: 'うみ',
        meaning: ['Sea', 'Ocean'],
        sentence: '海が広がっています。',
        type: 'main',
      },
      {
        reading: '北海道',
        kana: 'ほっかいどう',
        meaning: ['Hokkaido'],
        sentence: '北海道に行きます。',
        type: 'main',
      },
      {
        reading: '海外',
        kana: 'かいがい',
        meaning: ['Overseas'],
        sentence: '海外に行きます。',
        type: 'secondary',
      },
      {
        reading: 'エーゲ海',
        kana: 'エーゲかい',
        meaning: ['Aegean Sea'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '海岸',
        kana: 'かいがん',
        meaning: ['Coast', 'Seashore'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '海賊',
        kana: 'かいぞく',
        meaning: ['Pirate'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '海藻',
        kana: 'かいそう',
        meaning: ['Seaweed'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '海水',
        kana: 'かいすい',
        meaning: ['Sea water'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '化  ',
    onyomi: ['か', 'け'],
    kunyomi: ['ば'],
    meaning: ['Change', 'Transform'],
    examples: [
      {
        reading: '化学',  
        kana: 'かがく',
        meaning: ['Chemistry'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '文化',
        kana: 'ぶんか',
        meaning: ['Culture'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: 'お化け',
        kana: 'おばけ',
        meaning: ['Ghost'],
        sentence: 'お化けを見たことがある？',
        type: 'secondary',
      },
      {
        reading: '化粧',
        kana: 'けしょう',
        meaning: ['Makeup'],
        sentence: '化粧をします。',
        type: 'secondary',
      },
      {
        reading: '民主化',
        kana: 'みんしゅか',
        meaning: ['Democratization'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '変化',
        kana: 'へんか',
        meaning: ['Change'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '進化',
        kana: 'しんか',
        meaning: ['Evolution'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '花',
    onyomi: ['か'],
    kunyomi: ['はな', 'ばな'],
    meaning: ['Flower'],
    examples: [
      {
        reading: '花',
        kana: 'はな',
        meaning: ['Flower'],
        sentence: '花が咲いています。',
        type: 'main',
      },
      { 
        reading: '花見',
        kana: 'はなみ',
        meaning: ['Cherry blossom viewing'],
        sentence: '花見に行きます。',
        type: 'main',
      },
      {
        reading: '花火',
        kana: 'はなび',
        meaning: ['Fireworks'],
        sentence: '花火大会に行きます。',
        type: 'secondary',
      },
      {
        reading: '花屋',
        kana: 'はなや',
        meaning: ['Florist', 'Flower shop'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '花嫁',
        kana: 'はなよめ',
        meaning: ['Bride'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '生花',
        kana: 'いけばな',
        meaning: ['Flower arrangement'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '花瓶',
        kana: 'かびん',
        meaning: ['Flower Vase'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '花粉症',
        kana: 'かふんしょう',
        meaning: ['Hay fever'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '天',
    onyomi: ['てん'],
    kunyomi: ['あま', 'あめ'],
    meaning: ['Heaven'],
    examples: [
      {
        reading: '天気',
        kana: 'てんき',
        meaning: ['Weather'],
        sentence: 'いい天気ね？',
        type: 'main',
      },
      {
        reading: '天気予報',
        kana: 'てんきよほう',
        meaning: ['Weather forecast'],
        sentence: '天気予報を見ます。',
        type: 'main',
      },
      {
        reading: '天国',
        kana: 'てんごく',
        meaning: ['Heaven'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '天皇',
        kana: 'てんのう',
        meaning: ['Emperor'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '天使',
        kana: 'てんし',
        meaning: ['Angel'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '天才',
        kana: 'てんさい',
        meaning: ['Genius'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '天の川',
        kana: 'あまのがわ',
        meaning: ['Milky Way'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '天文学',
        kana: 'てんもんがく',
        meaning: ['Astronomy'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '赤',
    onyomi: ['せき', 'しゃく'],
    kunyomi: ['あか'],
    meaning: ['Red'],
    examples: [ 
      {
        reading: '赤い',
        kana: 'あかい',
        meaning: ['Red'],
        sentence: '赤い車が好きです。',
        type: 'main',
      },
      {
        reading: '赤ちゃん',
        kana: 'あかちゃん',
        meaning: ['Baby'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '赤字',
        kana: 'あかじ',
        meaning: ['Deficit'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '真っ赤',
        kana: 'まっか',
        meaning: ['Bright red', 'Deep red'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '赤十字',
        kana: 'せきじゅうじ',
        meaning: ['Red Cross'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '赤道',
        kana: 'せきどう',
        meaning: ['Equator'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '赤飯',
        kana: 'せきはん',
        meaning: ['Red rice'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '赤外線',
        kana: 'せきがいせん',
        meaning: ['Infrared rays'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '青',
    onyomi: ['せい', 'しょう'],
    kunyomi: ['あお'],
    meaning: ['Blue'],
    examples: [
      {
        reading: '青い',
        kana: 'あおい',
        meaning: ['Blue'],
        sentence: '青い空が好きです。',
        type: 'main',
      },
      {
        reading: '青空',
        kana: 'あおぞら',
        meaning: ['Blue sky'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '青信号',
        kana: 'あおしんごう',
        meaning: ['Green light'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '青森',
        kana: 'あおもり',
        meaning: ['Aomori'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '青年',
        kana: 'せいねん',
        meaning: ['Youth'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '真っ青',
        kana: 'まっさお',
        meaning: ['Deep blue'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '青春',
        kana: 'せいしゅん',
        meaning: ['Youth', 'Springtime of life'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '白',
    onyomi: ['はく', 'びゃく'],
    kunyomi: ['しろ', 'しら'],
    meaning: ['White'],
    examples: [
      {
        reading: '白い',
        kana: 'しろい',
        meaning: ['White'],
        sentence: '白い雲が好きです。',
        type: 'main',
      },
      {
        reading: '白黒',
        kana: 'しろくろ',
        meaning: ['Black and white'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '面白い',
        kana: 'おもしろい',
        meaning: ['Interesting', 'Funny'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '白髪',
        kana: 'しらが・はくはつ',
        meaning: ['White/gray hair'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '真っ白',
        kana: 'まっしろ',
        meaning: ['Pure white', 'Snow white'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '白紙',
        kana: 'はくし',
        meaning: ['Blank paper', 'Blank sheet'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '白鳥',
        kana: 'はくちょう',
        meaning: ['Swan'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '白夜',
        kana: 'びゃくや',
        meaning: ['White night'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '黒',
    onyomi: ['こく'],
    kunyomi: ['くろ'],
    meaning: ['Black'],
    examples: [
      {
        reading: '黒い',
        kana: 'くろい',
        meaning: ['Black'],
        sentence: '黒い猫がいます。',
        type: 'main',
      },
      {
        reading: '白黒',
        kana: 'しろくろ',
        meaning: ['Black and white'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '黒猫',
        kana: 'くろねこ',
        meaning: ['Black cat'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '黒板',
        kana: 'こくばん',
        meaning: ['Blackboard'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '真っ黒',
        kana: 'まっくろ',
        meaning: ['Pitch black'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '黒字',
        kana: 'くろじ',
        meaning: ['Surplus'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '色',
    onyomi: ['しょく', 'しき'],
    kunyomi: ['いろ'],
    meaning: ['Color'],
    examples: [
      {
        reading: '色',
        kana: 'いろ',
        meaning: ['Color'],
        sentence: 'この色は日本語で何ですか。',
        type: 'main',
      },
      {
        reading: '色々な',
        kana: 'いろいろな',
        meaning: ['Various'],
        sentence: '色々な色があります。',
        type: 'secondary',
      },
      {
        reading: '水色',
        kana: 'みずいろ',
        meaning: ['Light blue'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '灰色',
        kana: 'はいいろ',
        meaning: ['Gray'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '色鉛筆',
        kana: 'いろえんぴつ',
        meaning: ['Colored pencil'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '景色',
        kana: 'けしき',
        meaning: ['Scenery'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '特色',
        kana: 'とくしょく',
        meaning: ['Characteristic', 'Feature'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '脱色',
        kana: 'だっしょく',
        meaning: ['Decolorization', 'Bleaching'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '魚',
    onyomi: ['ぎょ'],
    kunyomi: ['さかな', 'ざかな', 'うお'],
    meaning: ['Fish'],
    examples: [
      {
        reading: '魚',
        kana: 'さかな',
        meaning: ['Fish'],
        sentence: '魚が泳いでいます。',
        type: 'main',
      },
      {
        reading: '魚屋',
        kana: 'さかなや',
        meaning: ['Fish store'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '小魚',
        kana: 'こざかな',
        meaning: ['Small fish'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '魚市場',
        kana: 'うおいちば',
        meaning: ['Fish market'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '金魚',
        kana: 'きんぎょ',
        meaning: ['Goldfish'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '人魚',
        kana: 'にんぎょ',
        meaning: ['Mermaid'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '熱帯魚',
        kana: 'ねったいぎょ',
        meaning: ['Tropical fish'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '魚介類',
        kana: 'ぎょかいるい',
        meaning: ['Seafood'],
        sentence: '',
        type: 'main',
      },
    ],
  },
  {
    kanji: '犬',
    onyomi: ['けん'],
    kunyomi: ['いぬ'],
    meaning: ['Dog'],
    examples: [
      {
        reading: '犬',
        kana: 'いぬ',
        meaning: ['Dog'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '子犬',
        kana: 'こいぬ',
        meaning: ['Puppy'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '番犬',
        kana: 'ばんけん',
        meaning: ['Watchdog'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '盲導犬',
        kana: 'もうどうけん',
        meaning: ['Guide dog'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '犬猿の仲',
        kana: 'けんえんのなか',
        meaning: ['To dislike each other'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '猟犬',
        kana: 'りょうけん',
        meaning: ['Hunting dog'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '狂犬病',
        kana: 'きょうけんびょう',
        meaning: ['Rabies'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
]