export const KANJI_YDC_LESSON_14: Array<KanjiYDC> = [
  {
    kanji: '教',
    onyomi: ['きょう'],
    kunyomi: ['おし', 'おそ'],
    meaning: ['Teach', 'Religion'],
    examples: [
      {
        reading: '教える',
        kana: 'おしえる',
        meaning: ['To teach'],
        sentence: '教えてください。',
        type: 'main',
      },
      {
        reading: '教室',
        kana: 'きょうしつ',
        meaning: ['Classroom'],
        sentence: '教室に行きます。',
        type: 'main',
      },
      {
        reading: '教会',
        kana: 'きょうかい',
        meaning: ['Church'],
        sentence: '教会に行きます。',
        type: 'main',
      },
      {
        reading: '教育',
        kana: 'きょういく',
        meaning: ['Education'],
        sentence: '教育を受けます。',
        type: 'secondary',
      },
      {
        reading: '教授',
        kana: 'きょうじゅ',
        meaning: ['Professor'],
        sentence: '教授に会います。',
        type: 'main',
      },
      {
        reading: '教師',
        kana: 'きょうし',
        meaning: ['Teacher'],
        sentence: '教師に会います。',
        type: 'main',
      },
      {
        reading: '教科書',
        kana: 'きょうかしょ',
        meaning: ['Textbook'],
        sentence: '教科書を読みます。',
        type: 'main',
      },
      {
        reading: '宗教',
        kana: 'しゅうきょう',
        meaning: ['Religion'],
        sentence: '宗教を信じます。',
        type: 'secondary',
      },
      {
        reading: '教わる',
        kana: 'おそわる',
        meaning: ['To be taught'],
        sentence: '教わります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '室',
    onyomi: ['しつ'],
    kunyomi: ['むろ'],
    meaning: ['Room'],
    examples: [
      {
        reading: '教室',
        kana: 'きょうしつ',
        meaning: ['Classroom'],
        sentence: '教室に行きます。',
        type: 'main',
      },
      {
        reading: '研究室',
        kana: 'けんきゅうしつ',
        meaning: ['Laboratory'],
        sentence: '研究室に行きます。',
        type: 'secondary',
      },
      {
        reading: '会議室',
        kana: 'かいぎしつ',
        meaning: ['Meeting room'],
        sentence: '会議室に行きます。',
        type: 'main',
      },
      {
        reading: '待合室',
        kana: 'まちあいしつ',
        meaning: ['Waiting room'],
        sentence: '待合室に座ります。',
        type: 'main',
      },
      {
        reading: '温室',
        kana: 'おんしつ',
        meaning: ['Greenhouse'],
        sentence: '温室に入ります。',
        type: 'secondary',
      },
      {
        reading: '地下室',
        kana: 'ちかしつ',
        meaning: ['Basement'],
        sentence: '地下室に行きます。',
        type: 'main',
      },
      {
        reading: '和室',
        kana: 'わしつ',
        meaning: ['Japanese-style room'],
        sentence: '和室に泊まります。',
        type: 'main',
      },
      {
        reading: '浴室',
        kana: 'よくしつ',
        meaning: ['Bathroom'],
        sentence: '浴室に入ります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '羽',
    onyomi: ['う'],
    kunyomi: ['はね', 'は', 'ば'],
    meaning: ['Feather', 'Wing'],
    examples: [
      {
        reading: '羽',
        kana: 'はね',
        meaning: ['Feather'],
        sentence: '羽を見ます。',
        type: 'main',
      },
      {
        reading: '羽根',
        kana: 'はね',
        meaning: ['Feather'],
        sentence: '羽根を見ます。',
        type: 'secondary',
      },
      {
        reading: '一羽',
        kana: 'いちわ',
        meaning: ['One bird'],
        sentence: '一羽の鳥。',
        type: 'secondary',
      },
      {
        reading: '千羽',
        kana: 'せんば',
        meaning: ['One thousand birds'],
        sentence: '千羽の鳥。',
        type: 'secondary',
      },
      {
        reading: '羽毛',
        kana: 'うもう',
        meaning: ['Feather'],
        sentence: '羽毛を見ます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '習',
    onyomi: ['しゅう'],
    kunyomi: ['なら'],
    meaning: ['Learn'],
    examples: [
      {
        reading: '習う',
        kana: 'ならう',
        meaning: ['To learn'],
        sentence: '習い事をします。',
        type: 'main',
      },
      {
        reading: '練習',
        kana: 'れんしゅう',
        meaning: ['Practice'],
        sentence: '練習をします。',
        type: 'main',
      },
      {
        reading: '習慣',
        kana: 'しゅうかん',
        meaning: ['Custom', 'Habit'],
        sentence: '習慣を変えます。',
        type: 'secondary',
      },
      {
        reading: '復習',
        kana: 'ふくしゅう',
        meaning: ['Review'],
        sentence: '復習をします。',
        type: 'secondary',
      },
      {
        reading: '予習',
        kana: 'よしゅう',
        meaning: ['Preparation for a lesson'],
        sentence: '予習をします。',
        type: 'secondary',
      },
      {
        reading: '学習',
        kana: 'がくしゅう',
        meaning: ['Study'],
        sentence: '学習をします。',
        type: 'secondary',
      },
      {
        reading: '自習',
        kana: 'じしゅう',
        meaning: ['Self-study'],
        sentence: '自習をします。',
        type: 'secondary',
      },
      {
        reading: '習字',
        kana: 'しゅうじ',
        meaning: ['Calligraphy'],
        sentence: '習字をします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '漢',
    onyomi: ['かん'],
    kunyomi: [],
    meaning: ['China'],
    examples: [
      {
        reading: '漢字',
        kana: 'かんじ',
        meaning: ['Kanji'],
        sentence: '漢字を勉強します。',
        type: 'main',
      },
      {
        reading: '漢和辞典',
        kana: 'かんわじてん',
        meaning: ['Kanji-Japanese dictionary'],
        sentence: '漢和辞典を使います。',
        type: 'secondary',
      },
      {
        reading: '漢方薬',
        kana: 'かんぽうやく',
        meaning: ['Chinese herbal medicine'],
        sentence: '漢方薬を飲みます。',
        type: 'secondary',
      },
      {
        reading: '漢文',
        kana: 'かんぶん',
        meaning: ['Chinese classics'],
        sentence: '漢文を勉強します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '字',
    onyomi: ['じ'],
    kunyomi: ['あざ'],
    meaning: ['Character'],
    examples: [
      {
        reading: '字',
        kana: 'じ',
        meaning: ['Character'],
        sentence: '字を書きます。',
        type: 'main',
      },
      {
        reading: '漢字',
        kana: 'かんじ',
        meaning: ['Kanji'],
        sentence: '漢字を勉強します。',
        type: 'main',
      },
      {
        reading: '文字',
        kana: 'もじ',
        meaning: ['Letter', 'Character'],
        sentence: '文字を書きます。',
        type: 'secondary',
      },
      {
        reading: '名字',
        kana: 'みょうじ',
        meaning: ['Family name'],
        sentence: '名字を書きます。',
        type: 'main',
      },
      {
        reading: '数字',
        kana: 'すうじ',
        meaning: ['Number'],
        sentence: '数字を書きます。',
        type: 'secondary',
      },
      {
        reading: '習字',
        kana: 'しゅうじ',
        meaning: ['Calligraphy'],
        sentence: '習字をします。',
        type: 'secondary',
      },
      {
        reading: '活字',
        kana: 'かつじ',
        meaning: ['Printed type'],
        sentence: '活字を読みます。',
        type: 'secondary',
      },
      {
        reading: 'ローマ字',
        kana: 'ローマじ',
        meaning: ['Roman alphabet'],
        sentence: 'ローマ字を読みます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '式',
    onyomi: ['しき'],
    kunyomi: [],
    meaning: ['Style', 'Ceremony'],
    examples: [
      {
        reading: '入学式',  
        kana: 'にゅうがくしき',
        meaning: ['Entrance ceremony'],
        sentence: '入学式に出席します。',
        type: 'main',
      },
      {
        reading: '結婚式',
        kana: 'けっこんしき',
        meaning: ['Wedding ceremony'],
        sentence: '結婚式に出席します。',
        type: 'secondary',
      },
      {
        reading: '式',
        kana: 'しき',
        meaning: ['Style', 'Ceremony'],
        sentence: '式を行います。',
        type: 'secondary',
      },
      {
        reading: '正式な',
        kana: 'せいしきな',
        meaning: ['Formal'],
        sentence: '正式な場所。',
        type: 'secondary',
      },
      {
        reading: '洋式',
        kana: 'ようしき',
        meaning: ['Western style'],
        sentence: '洋式の服。',
        type: 'main',
      },
      {
        reading: '和式',
        kana: 'わしき',
        meaning: ['Japanese style'],
        sentence: '和式の部屋。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '試',
    onyomi: ['し'],
    kunyomi: ['ため', 'こころ'],
    meaning: ['Test', 'Try'],
    examples: [
      {
        reading: '試験',  
        kana: 'しけん',
        meaning: ['Test', 'Examination'],
        sentence: '試験を受けます。',
        type: 'main',
      },
      {
        reading: '試合',
        kana: 'しあい',
        meaning: ['Game', 'Match'],
        sentence: '試合に出ます。',
        type: 'main',
      },
      {
        reading: '試す',
        kana: 'ためす',
        meaning: ['To try'],
        sentence: '試してみます。',
        type: 'secondary',
      },
      {
        reading: '試みる',
        kana: 'こころみる',
        meaning: ['To try'],
        sentence: '試みます。',
        type: 'secondary',
      },
      {
        reading: '入学試験',
        kana: 'にゅうがくしけん',
        meaning: ['Entrance examination'],
        sentence: '入学試験を受けます。',
        type: 'main',
      },
      {
        reading: '試食',
        kana: 'ししょく',
        meaning: ['Sample food'],
        sentence: '試食をします。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '験',
    onyomi: ['けん', 'げん'], 
    kunyomi: [],
    meaning: ['Test', 'Experience'],
    examples: [
      {
        reading: '試験',
        kana: 'しけん',
        meaning: ['Test', 'Examination'],
        sentence: '試験を受けます。',
        type: 'main',
      },
      {
        reading: '経験',
        kana: 'けいけん',
        meaning: ['Experience'],
        sentence: '経験を積みます。',
        type: 'secondary',
      },
      {
        reading: '実験',
        kana: 'じっけん',
        meaning: ['Experiment'],
        sentence: '実験をします。',
        type: 'secondary',
      },
      {
        reading: '受験',
        kana: 'じゅけん',
        meaning: ['Taking an examination'],
        sentence: '受験をします。',
        type: 'secondary',
      },
      {
        reading: '体験',
        kana: 'たいけん',
        meaning: ['Experience'],
        sentence: '体験をします。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '宿',
    onyomi: ['しゅく'],
    kunyomi: ['やど'],
    meaning: ['Inn', 'Lodge'],
    examples: [ 
      {
        reading: '宿題',
        kana: 'しゅくだい',
        meaning: ['Homework'],
        sentence: '宿題をします。',
        type: 'main',
      },
      {
        reading: '宿',
        kana: 'やど',
        meaning: ['Inn', 'Lodge'],
        sentence: '宿に泊まります。',
        type: 'main',
      },
      {
        reading: '下宿',
        kana: 'げしゅく',
        meaning: ['Boarding house'],
        sentence: '下宿に住みます。',
        type: 'secondary',
      },
      {
        reading: '宿泊',
        kana: 'しゅくはく',
        meaning: ['Lodging'],
        sentence: '宿泊を予約します。',
        type: 'secondary',
      },
      {
        reading: '民宿',
        kana: 'みんしゅく',
        meaning: ['Guest house', 'Tourist home'],
        sentence: '民宿に泊まります。',
        type: 'secondary',
      },
      {
        reading: '雨宿り',
        kana: 'あまやどり',
        meaning: ['Taking shelter from the rain'],
        sentence: '雨宿りをします。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '題',
    onyomi: ['だい'],
    kunyomi: [],
    meaning: ['Topic', 'Title', 'Subject'],
    examples: [
      {
        reading: '宿題',
        kana: 'しゅくだい',
        meaning: ['Homework'],
        sentence: '宿題をします。',
        type: 'main',
      },
      {
        reading: '問題',
        kana: 'もんだい',
        meaning: ['Problem', 'Question'],
        sentence: '問題を解きます。',
        type: 'main',
      },
      {
        reading: '題',
        kana: 'だい',
        meaning: ['Title'],
        sentence: '題を決めます。',
        type: 'secondary',
      },
      {
        reading: '題名',
        kana: 'だいめい',
        meaning: ['Title'],
        sentence: '題名を書きます。',
        type: 'secondary',
      },
      {
        reading: '話題',
        kana: 'わだい',
        meaning: ['Topic of conversation'],
        sentence: '話題を変えます。',
        type: 'main',
      },
      {
        reading: '議題',
        kana: 'ぎだい',
        meaning: ['Agenda', 'Topic for discussion'],
        sentence: '議題を決めます。',
        type: 'secondary',
      },
      {
        reading: '課題',
        kana: 'かだい',
        meaning: ['Task', 'Assignment'],
        sentence: '課題を出します。',
        type: 'main',
      },
      {
        reading: '主題',
        kana: 'しゅだい',
        meaning: ['Main theme', 'Topic'],
        sentence: '主題を決めます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '文',
    onyomi: ['ぶん', 'もん'],
    kunyomi: ['ふみ'],
    meaning: ['Sentence', 'Character'],
    examples: [
      {
        reading: '文学',
        kana: 'ぶんがく',
        meaning: ['Literature'],
        sentence: '文学を勉強します。',
        type: 'main',
      },
      {
        reading: '作文',
        kana: 'さくぶん',
        meaning: ['Composition'],
        sentence: '作文を書きます。',
        type: 'main',
      },
      {
        reading: '文化',
        kana: 'ぶんか',
        meaning: ['Culture'],
        sentence: '文化を学びます。',
        type: 'main',
      },
      {
        reading: '文字',
        kana: 'もじ',
        meaning: ['Letter', 'Character'],
        sentence: '文字を書きます。',
        type: 'main',
      },
      {
        reading: '文法',
        kana: 'ぶんぽう',
        meaning: ['Grammar'],
        sentence: '文法を勉強します。',
        type: 'main',
      },
      {
        reading: '英文',
        kana: 'えいぶん',
        meaning: ['English sentence'],
        sentence: '英文を読みます。',
        type: 'secondary',
      },
      {
        reading: '文句',
        kana: 'もんく',
        meaning: ['Complaint'],
        sentence: '文句を言います。',
        type: 'secondary',
      },
      {
        reading: '文',
        kana: 'ふみ',
        meaning: ['Letter', 'Character'],
        sentence: '文を書きます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '英',
    onyomi: ['えい'],
    kunyomi: [],
    meaning: ['English', 'Excellent'],
    examples: [
      {
        reading: '英語',
        kana: 'えいご',
        meaning: ['English language'],
        sentence: '英語を勉強します。',
        type: 'main',
      },
      {
        reading: '英雄',
        kana: 'えいゆう',
        meaning: ['Hero'],
        sentence: '英雄に憧れます。',
        type: 'secondary',
      },
      {
        reading: '英国',
        kana: 'えいこく',
        meaning: ['England'],
        sentence: '英国に行きます。',
        type: 'secondary',
      },
      {
        reading: '英会話',
        kana: 'えいかいわ',
        meaning: ['English conversation'],
        sentence: '英会話を練習します。',
        type: 'main',
      },
      {
        reading: '英和辞典',
        kana: 'えいわじてん',
        meaning: ['English-Japanese dictionary'],
        sentence: '英和辞典を使います。',
        type: 'secondary',
      },
      {
        reading: '和英辞典',
        kana: 'わえいじてん',
        meaning: ['Japanese-English dictionary'],
        sentence: '和英辞典を使います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '質',
    onyomi: ['しつ', 'しち', 'ち'],
    kunyomi: [],
    meaning: ['Quality', 'Substance'],
    examples: [
      {
        reading: '質問',
        kana: 'しつもん',
        meaning: ['Question'],
        sentence: '質問をします。',
        type: 'main',
      },
      {
        reading: '質',
        kana: 'しつ',
        meaning: ['Quality', 'Substance'],
        sentence: '質を確認します。',
        type: 'main',
      },
      {
        reading: '性質',
        kana: 'せいしつ',
        meaning: ['Nature', 'Quality', 'Characteristic'],
        sentence: '性質を調べます。',
        type: 'secondary',
      },
      {
        reading: '物質',
        kana: 'ぶっしつ',
        meaning: ['Substance', 'Material'],
        sentence: '物質を調べます。',
        type: 'secondary',
      },
      {
        reading: '素質',
        kana: 'そしつ',
        meaning: ['Aptitude'],
        sentence: '素質を見ます。',
        type: 'secondary',
      },
      {
        reading: '神経質',
        kana: 'しんけいしつ',
        meaning: ['Nervous temperament'],
        sentence: '神経質な人。',
        type: 'secondary',
      },
      {
        reading: '質屋',
        kana: 'しちや',
        meaning: ['Pawnshop'],
        sentence: '質屋に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '問',
    onyomi: ['もん'],
    kunyomi: ['と', 'とん'],
    meaning: ['Question', 'Problem'],
    examples: [
      {
        reading: '問題',
        kana: 'もんだい',
        meaning: ['Problem', 'Question'],
        sentence: '問題を解きます。',
        type: 'main',
      },
      {
        reading: '質問',
        kana: 'しつもん',
        meaning: ['Question'],
        sentence: '質問をします。',
        type: 'main',
      },
      {
        reading: '問い',
        kana: 'とい',
        meaning: ['Question'],
        sentence: '問いをします。',
        type: 'main',
      },
      {
        reading: '問い合わせ',
        kana: 'といあわせ',
        meaning: ['Inquiry'],
        sentence: '問い合わせをします。',
        type: 'secondary',
      },
      {
        reading: '訪問',
        kana: 'ほうもん',
        meaning: ['Visit'],
        sentence: '訪問をします。',
        type: 'secondary',
      },
      {
        reading: '疑問',
        kana: 'ぎもん',
        meaning: ['Doubt', 'Question'],
        sentence: '疑問を持ちます。',
        type: 'secondary',
      },
      {
        reading: '学問',
        kana: 'がくもん',
        meaning: ['Learning', 'Study'],
        sentence: '学問をします。',
        type: 'main',
      },
      {
        reading: '問屋',
        kana: 'とんや',
        meaning: ['Wholesale store'],
        sentence: '問屋に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '説',
    onyomi: ['せつ', 'せっ', 'ぜい'],
    kunyomi: ['と'],
    meaning: ['Theory', 'Explain'],
    examples: [
      {
        reading: '説明',
        kana: 'せつめい',
        meaning: ['Explanation'],
        sentence: '説明をします。',
        type: 'main',
      },
      {
        reading: '小説',
        kana: 'しょうせつ',
        meaning: ['Novel'],
        sentence: '小説を読みます。',
        type: 'main',
      },
      {
        reading: '解説',
        kana: 'かいせつ',
        meaning: ['Commentary'],
        sentence: '解説を読みます。',
        type: 'secondary',
      },
      {
        reading: '説得する',
        kana: 'せっとくする',
        meaning: ['To persuade'],
        sentence: '説得します。',
        type: 'secondary',
      },
      {
        reading: '説教する',
        kana: 'せっきょうする',
        meaning: ['To preach'],
        sentence: '説教します。',
        type: 'secondary',
      },
      {
        reading: '仮説',
        kana: 'かせつ',
        meaning: ['Hypothesis'],
        sentence: '仮説を立てます。',
        type: 'secondary',
      },
      {
        reading: '説く',
        kana: 'とく',
        meaning: ['To expound'],
        sentence: '説きます。',
        type: 'secondary',
      },
      {
        reading: '遊説',
        kana: 'ゆうぜい',
        meaning: ['Political campaign tour'],
        sentence: '遊説をします。',
        type: 'secondary',
      },
    ],
  },
]