export const KANJI_YDC_LESSON_15: Array<KanjiYDC> = [
  {
    kanji: '遠',
    onyomi: ['えん', 'おん'],
    kunyomi: ['とお'],
    meaning: ['Distant', 'Far'],
    examples: [
      {
        reading: '遠い',
        kana: 'とおい',
        meaning: ['Distant', 'Far'],
        sentence: '遠い国。',
        type: 'main',
      },
      {
        reading: '遠く',
        kana: 'とおく',
        meaning: ['Far away', 'Far place'],
        sentence: '遠くに行きます。',
        type: 'main',
      },
      {
        reading: '遠方',
        kana: 'えんぽう',
        meaning: ['Distant place'],
        sentence: '遠方に行きます。',
        type: 'main',
      },
      {
        reading: '遠慮する',
        kana: 'えんりょする',
        meaning: ['To hesitate', 'To hold back'],
        sentence: '遠慮します。',
        type: 'secondary',
      },
      {
        reading: '遠足',
        kana: 'えんそく',
        meaning: ['One-day Excursion', 'Field trip'],
        sentence: '遠足に行きます。',
        type: 'secondary',
      },
      {
        reading: '望遠鏡',
        kana: 'ぼうえんきょう',
        meaning: ['Telescope'],
        sentence: '望遠鏡を覗きます。',
        type: 'secondary',
      },
      {
        reading: '永遠の',
        kana: 'えいえんの',
        meaning: ['Eternal'],
        sentence: '永遠の愛。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '近',
    onyomi: ['きん'],
    kunyomi: ['ちか'],
    meaning: ['Near', 'Close'],
    examples: [
      {
        reading: '近い',
        kana: 'ちかい',
        meaning: ['Near', 'Close'],
        sentence: '近い国。',
        type: 'main',
      },
      {
        reading: '近く',
        kana: 'ちかく',
        meaning: ['Nearby', 'Close'],
        sentence: '近くに行きます。',
        type: 'main',
      },
      {
        reading: '近所',
        kana: 'きんじょ',
        meaning: ['Neighborhood'],
        sentence: '近所の人。',
        type: 'main',
      },
      {
        reading: '最近',
        kana: 'さいきん',
        meaning: ['Recently'],
        sentence: '最近の出来事。',
        type: 'main',
      },
      {
        reading: '近ごろ',
        kana: 'ちかごろ',
        meaning: ['Lately', 'Recently'],
        sentence: '近ごろの出来事。',
        type: 'main',
      },
      {
        reading: '近代的な',
        kana: 'きんだいてきな',
        meaning: ['Modern'],
        sentence: '近代的な建物。',
        type: 'secondary',
      },
      {
        reading: '近視',
        kana: 'きんし',
        meaning: ['Short-sightedness'],
        sentence: '近視の人。',
        type: 'secondary',
      },
      {
        reading: '中近東',
        kana: 'ちゅうきんとう',
        meaning: ['Middle East'],
        sentence: '中近東の国。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '者',
    onyomi: ['しゃ'],
    kunyomi: ['もの'],
    meaning: ['Person', 'Someone'],
    examples: [
      {
        reading: '学者',
        kana: 'がくしゃ',
        meaning: ['Scholar'],
        sentence: '学者に会います。',
        type: 'main',
      },
      {
        reading: '作者',
        kana: 'さくしゃ',
        meaning: ['Author'],
        sentence: '作者に会います。',
        type: 'main',
      },
      {
        reading: '医者',
        kana: 'いしゃ',
        meaning: ['Doctor'],
        sentence: '医者に会います。',
        type: 'main',
      },
      {
        reading: '歯医者',
        kana: 'はいしゃ',
        meaning: ['Dentist'],
        sentence: '歯医者に行きます。',
        type: 'main',
      },
      {
        reading: '研究者',
        kana: 'けんきゅうしゃ',
        meaning: ['Researcher'],
        sentence: '研究者に会います。',
        type: 'secondary',
      },
      {
        reading: '記者',
        kana: 'きしゃ',
        meaning: ['Reporter'],
        sentence: '記者に会います。',
        type: 'main',
      },
      {
        reading: '読者',
        kana: 'どくしゃ',
        meaning: ['Reader'],
        sentence: '読者に会います。',
        type: 'main',
      },
      {
        reading: '若者',
        kana: 'わかもの',
        meaning: ['Young person'],
        sentence: '若者に会います。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '暑',
    onyomi: ['しょ'],
    kunyomi: ['あつ'],
    meaning: ['Hot', 'Warm'],
    examples: [
      {
        reading: '暑い',
        kana: 'あつい',
        meaning: ['Hot', 'Warm'],
        sentence: '暑い日。',
        type: 'main',
      },
      {
        reading: '蒸し暑い',
        kana: 'むしあつい',
        meaning: ['Humid', 'Sultry'],
        sentence: '蒸し暑い日。',
        type: 'secondary',
      },
      {
        reading: '暑中見舞い',
        kana: 'しょちゅうみまい',
        meaning: ['Summer greeting card'],
        sentence: '暑中見舞いを送ります。',
        type: 'secondary',
      },
      {
        reading: '残暑',
        kana: 'ざんしょ',
        meaning: ['Late summer heat'],
        sentence: '残暑が厳しい。',
        type: 'secondary',
      },
      {
        reading: '避暑地',
        kana: 'ひしょち',
        meaning: ['Summer resort'],
        sentence: '避暑地に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '寒',
    onyomi: ['かん'],
    kunyomi: ['さむ'],
    meaning: ['Cold'],
    examples: [
      {
        reading: '寒い',
        kana: 'さむい',
        meaning: ['Cold'],
        sentence: '寒い日。',
        type: 'main',
      },
      {
        reading: '寒気',
        kana: 'さむけ',
        meaning: ['Chill'],
        sentence: '寒気がする。',
        type: 'main',
      },
      {
        reading: '寒気',
        kana: 'かんき',
        meaning: ['Cold air', 'The cold'],
        sentence: '寒気がする。',
        type: 'main',
      },
      {
        reading: '寒帯',
        kana: 'かんたい',
        meaning: ['Frigid zone'],
        sentence: '寒帯に行きます。',
        type: 'secondary',
      },
      {
        reading: '寒風',
        kana: 'かんぷう',
        meaning: ['Cold wind'],
        sentence: '寒風が吹く。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '重',
    onyomi: ['じゅう', 'ちょう'],
    kunyomi: ['おも', 'え', 'かさ'],
    meaning: ['Heavy', 'Important'],
    examples: [
      {
        reading: '重い',
        kana: 'おもい',
        meaning: ['Heavy'],
        sentence: '重い荷物。',
        type: 'main',
      },
      {
        reading: '重ねる',
        kana: 'かさねる',
        meaning: ['To pile up', 'To stack'],
        sentence: '重ねて置きます。',
        type: 'secondary',
      },
      {
        reading: '体重',
        kana: 'たいじゅう',
        meaning: ['Body weight'],
        sentence: '体重を量ります。',
        type: 'main',
      },
      {
        reading: '重役',
        kana: 'じゅうやく',
        meaning: ['Executive'],
        sentence: '重役に会います。',
        type: 'secondary',
      },
      {
        reading: '重要な',
        kana: 'じゅうような',
        meaning: ['Important'],
        sentence: '重要な仕事。',
        type: 'main',
      },
      {
        reading: '貴重品',
        kana: 'きちょうひん',
        meaning: ['Valuables'],
        sentence: '貴重品を持ちます。',
        type: 'secondary',
      },
      {
        reading: '二重まぶた',
        kana: 'ふたえまぶた',
        meaning: ['Double eyelid'],
        sentence: '二重まぶた。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '軽',
    onyomi: ['けい'],
    kunyomi: ['かる', 'がる', 'かろ'],
    meaning: ['Light', 'Easy'],
    examples: [
      {
        reading: '軽い',  
        kana: 'かるい',
        meaning: ['Light', 'Easy'],
        sentence: '軽い荷物。',
        type: 'main',
      },
      {
        reading: '手軽な',
        kana: 'てがるな',
        meaning: ['Easy', 'Simple'],
        sentence: '手軽な料理。',
        type: 'secondary',
      },
      {
        reading: '気軽に',
        kana: 'きがるに',
        meaning: ['light-heartly', 'casually'],
        sentence: '気軽に話しかけます。',
        type: 'secondary',
      },
      {
        reading: '軽自動車',
        kana: 'けいじどうしゃ',
        meaning: ['Compact car'],
        sentence: '軽自動車に乗ります。',
        type: 'secondary',
      },
      {
        reading: '軽やかに',  
        kana: 'かろやかに',
        meaning: ['Airy'],
        sentence: '軽やかに歩きます。',
        type: 'secondary',
      },
      {
        reading: '軽率な',  
        kana: 'けいそつな',
        meaning: ['careless', 'Hasty'],
        sentence: '軽率な行動。',
        type: 'secondary',
      },
      {
        reading: '軽蔑',  
        kana: 'けいべつ',
        meaning: ['Contempt'],
        sentence: '軽蔑の目で見ます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '低',
    onyomi: ['てい'],
    kunyomi: ['ひく'],
    meaning: ['Low', 'Short'],
    examples: [
      {
        reading: '低い',  
        kana: 'ひくい',
        meaning: ['Low', 'Short'],
        sentence: 'この人は背が低い。',
        type: 'main',
      },
      {
        reading: '最低',
        kana: 'さいてい',
        meaning: ['The lowest', 'The worst'],
        sentence: '最低の評価。',
        type: 'main',
      },
      {
        reading: '低下',
        kana: 'ていか',
        meaning: ['Decline', 'Fall'],
        sentence: '低下する。',
        type: 'secondary',
      },
      {
        reading: '低温',
        kana: 'ていおん',
        meaning: ['Low temperature'],
        sentence: '低温の部屋。',
        type: 'main',
      },
      {
        reading: '低気圧',
        kana: 'ていきあつ',
        meaning: ['Low pressure'],
        sentence: '低気圧の影響。',
        type: 'secondary',
      },
      {
        reading: '高低',
        kana: 'こうてい',
        meaning: ['High and low'],
        sentence: '高低差。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '弱',
    onyomi: ['じゃく'],
    kunyomi: ['よわ'],
    meaning: ['Weak'],
    examples: [
      {
        reading: '弱い',
        kana: 'よわい',
        meaning: ['Weak'],
        sentence: '弱い人。',
        type: 'main',
      },
      {
        reading: '弱点',
        kana: 'じゃくてん',
        meaning: ['Weak point', 'Weakness'],
        sentence: '弱点を克服する。',
        type: 'main',
      },
      {
        reading: '弱る',
        kana: 'よわる',
        meaning: ['To weaken', 'To grow weak'],
        sentence: '体が弱る。',
        type: 'main',
      },
      {
        reading: '病弱',
        kana: 'びょうじゃく',
        meaning: ['Physically weak'],
        sentence: '病弱な体質。',
        type: 'secondary',
      },
      {
        reading: '弱肉強食',
        kana: 'じゃくにくきょうしょく',
        meaning: ['The law of the jungle'],
        sentence: '弱肉強食の世の中。',
        type: 'secondary',
      },
      {
        reading: '弱気',
        kana: 'よわき',
        meaning: ['Weakness'],
        sentence: '弱気な態度。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '悪',
    onyomi: ['あく', 'お'],
    kunyomi: ['わる'],
    meaning: ['Bad', 'Evil'],
    examples: [ 
      {
        reading: '悪い',
        kana: 'わるい',
        meaning: ['Bad', 'Evil'],
        sentence: '悪い人。',
        type: 'main',
      },
      {
        reading: '悪口',
        kana: 'わるくち・わるぐち',
        meaning: ['Slender', 'Abuse'],
        sentence: '悪口を言う。',
        type: 'secondary',
      },
      {
        reading: '意地悪な',
        kana: 'いじわるな',
        meaning: ['Malicious', 'Mean'],
        sentence: '意地悪な人。',
        type: 'secondary',
      },
      {
        reading: '最悪',
        kana: 'さいあく',
        meaning: ['The worst'],
        sentence: '最悪の状況。',
        type: 'main',
      },
      {
        reading: '悪者',
        kana: 'わるもの',
        meaning: ['Villain'],
        sentence: '悪者を捕まえる。',
        type: 'main',
      },
      {
        reading: '悪魔',
        kana: 'あくま',
        meaning: ['Devil'],
        sentence: '悪魔のような人。',
        type: 'secondary',
      },
      {
        reading: '悪',
        kana: 'あく',
        meaning: ['Evil'],
        sentence: '悪の根源。',
        type: 'main',
      },
      {
        reading: '悪寒',
        kana: 'おかん',
        meaning: ['Chill'],
        sentence: '悪寒がする。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '暗',
    onyomi: ['あん'],
    kunyomi: ['くら'],
    meaning: ['Dark', 'Gloomy'],
    examples: [
      {
        reading: '暗い',
        kana: 'くらい',
        meaning: ['Dark', 'Gloomy'],
        sentence: '暗い部屋。',
        type: 'main',
      },
      {
        reading: '真っ暗',
        kana: 'まっくら',
        meaning: ['Pitch dark', 'Completely dark'],
        sentence: '真っ暗な夜。',
        type: 'main',
      },
      {
        reading: '暗記する',
        kana: 'あんきする',
        meaning: ['To memorize', 'To learn by heart'],
        sentence: '暗記します。',
        type: 'main',
      },
      {
        reading: '暗殺',
        kana: 'あんさつ',
        meaning: ['Assassination'],
        sentence: '暗殺される。',
        type: 'secondary',
      },
      {
        reading: '暗証番号',
        kana: 'あんしょうばんごう',
        meaning: ['PIN number'],
        sentence: '暗証番号を入力します。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '太',
    onyomi: ['たい', 'た'],
    kunyomi: ['ふと'],
    meaning: ['Fat', 'Thick'],
    examples: [
      {
        reading: '太い',
        kana: 'ふとい',
        meaning: ['Fat', 'Thick'],
        sentence: '太い人。',
        type: 'main',
      },
      {
        reading: '太る',
        kana: 'ふとる',
        meaning: ['To gain weight'],
        sentence: 'あの人は太りやすい。',
        type: 'main',
      },
      {
        reading: '太陽',
        kana: 'たいよう',
        meaning: ['Sun'],
        sentence: '太陽が昇る。',
        type: 'secondary',
      },
      {
        reading: '太鼓',
        kana: 'たいこ',
        meaning: ['Japanese Drum'],
        sentence: '太鼓を叩く。',
        type: 'secondary',
      },
      {
        reading: '皇太子',
        kana: 'こうたいし',
        meaning: ['Crown Prince'],
        sentence: '皇太子が即位する。',
        type: 'secondary',
      },
      {
        reading: '太平洋',
        kana: 'たいへいよう',
        meaning: ['Pacific Ocean'],
        sentence: '太平洋に行きます。',
        type: 'secondary',
      },
      {
        reading: '丸太',
        kana: 'まるた',
        meaning: ['Log'],
        sentence: '丸太を運びます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '豆',
    onyomi: ['とう', 'ず'],
    kunyomi: ['まめ'],
    meaning: ['Bean', 'Pea'],
    examples: [
      {
        reading: '豆',
        kana: 'まめ',
        meaning: ['Bean', 'Pea'],
        sentence: '豆を食べます。',
        type: 'main',
      },
      {
        reading: '豆腐',
        kana: 'とうふ',
        meaning: ['Tofu'],
        sentence: '豆腐を食べます。',
        type: 'main',
      },
      {
        reading: 'コーヒー豆',
        kana: 'コーヒーまめ',
        meaning: ['Coffee beans'],
        sentence: 'コーヒー豆を挽きます。',
        type: 'secondary',
      },
      {
        reading: '枝豆',
        kana: 'えだまめ',
        meaning: ['Green soybeans'],
        sentence: '枝豆を食べます。',
        type: 'secondary',
      },
      {
        reading: '大豆',
        kana: 'だいず',
        meaning: ['Soybeans'],
        sentence: '大豆を食べます。',
        type: 'main',
      },
      {
        reading: '豆乳',
        kana: 'とうにゅう',
        meaning: ['Soy milk'],
        sentence: '豆乳を飲みます。',
        type: 'main',
      },
      {
        reading: '納豆',
        kana: 'なっとう',
        meaning: ['Fermented soybeans'],
        sentence: '納豆を食べます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '短',
    onyomi: ['たん'],
    kunyomi: ['みじか'],
    meaning: ['Short'],
    examples: [
      {
        reading: '短い',
        kana: 'みじかい',
        meaning: ['Short'],
        sentence: '短い人。',
        type: 'main',
      },
      {
        reading: '短所',
        kana: 'たんしょ',
        meaning: ['Weak point', 'weakness'],
        sentence: '短所を克服する。',
        type: 'main',
      },
      {
        reading: '短期',
        kana: 'たんき',
        meaning: ['Short term'],
        sentence: '短期間。',
        type: 'main',
      },
      {
        reading: '短期大学',
        kana: 'たんきだいがく',
        meaning: ['Junior college'],
        sentence: '短期大学に通います。',
        type: 'main',
      },
      {
        reading: '短編',
        kana: 'たんぺん',
        meaning: ['Short story'],
        sentence: '短編小説。',
        type: 'secondary',
      },
      {
        reading: '短気な',
        kana: 'たんきな',
        meaning: ['Short-tempered', 'Impatient'],
        sentence: '短気な人。',
        type: 'main',
      },
      {
        reading: '短歌',
        kana: 'たんか',
        meaning: ['Tanka', '31-syllable poem'],
        sentence: '短歌を詠む。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '光',
    onyomi: ['こう'],
    kunyomi: ['ひかり', 'ひか'],
    meaning: ['Light', 'Ray'],
    examples: [
      {
        reading: '光',
        kana: 'ひかり',
        meaning: ['Light', 'Ray'],
        sentence: '光が差す。',
        type: 'main',
      },
      {
        reading: '光る',
        kana: 'ひかる',
        meaning: ['To shine'],
        sentence: '星が光る。',
        type: 'main',
      },
      {
        reading: '観光',
        kana: 'かんこう',
        meaning: ['Sightseeing'],
        sentence: '観光地に行きます。',
        type: 'main',
      },
      {
        reading: '日光',
        kana: 'にっこう',
        meaning: ['Sunlight', 'Sunshine'],
        sentence: '日光浴。',
        type: 'main',
      },
      {
        reading: '光線',
        kana: 'こうせん',
        meaning: ['Ray'],
        sentence: '光線を浴びる。',
        type: 'secondary',
      },
      {
        reading: '光景',
        kana: 'こうけい',
        meaning: ['Spectacle', 'Scene', 'View', 'Sight'],
        sentence: '美しい光景。',
        type: 'main',
      },
      {
        reading: '光熱費',
        kana: 'こうねつひ',
        meaning: ['Utility bill', 'Light and heat expenses'],
        sentence: '光熱費を払います。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '風',
    onyomi: ['ふう', 'ふ'],
    kunyomi: ['かぜ', 'かざ'],
    meaning: ['Wind', 'Style'],
    examples: [
      {
        reading: '風',
        kana: 'かぜ',
        meaning: ['Wind'],
        sentence: '風が吹く。',
        type: 'main',
      },
      {
        reading: '台風',
        kana: 'たいふう',
        meaning: ['Typhoon'],
        sentence: '台風が来る。',
        type: 'main',
      },
      {
        reading: '風邪',
        kana: 'かぜ',
        meaning: ['Cold', 'Flu'],
        sentence: '風邪を引く。',
        type: 'main',
      },
      {
        reading: 'お風呂',
        kana: 'おふろ',
        meaning: ['Bath'],
        sentence: 'お風呂に入ります。',
        type: 'main',
      },
      {
        reading: '風船',
        kana: 'ふうせん',
        meaning: ['Balloon'],
        sentence: '風船を飛ばす。',
        type: 'secondary',
      },
      {
        reading: '風景',
        kana: 'ふうけい',
        meaning: ['Scenery'],
        sentence: '美しい風景。',
        type: 'main',
      },
      {
        reading: '洋風',
        kana: 'ようふう',
        meaning: ['Western style'],
        sentence: '洋風の建物。',
        type: 'main',
      },
      {
        reading: '和風',
        kana: 'わふう',
        meaning: ['Japanese style'],
        sentence: '和風の建物。',
        type: 'main',
      },
    ],
  },
]