export const KANJI_YDC_LESSON_22: Array<KanjiYDC> = [
  {
    kanji: '笑',
    onyomi: ['しょう'],
    kunyomi: ['わら', 'え'],
    meaning: ['Laugh', 'Smile'],
    examples: [
      {
        reading: '笑う',
        kana: 'わらう',
        meaning: ['To laugh', 'To smile'],
        sentence: '彼のジョークでみんなが笑いました。',
        type: 'YDC_main',
      },
      {
        reading: '笑顔',
        kana: 'えがお',
        meaning: ['Smile', 'Smiling face'],
        sentence: '彼女はいつも笑顔で接してくれます。',
        type: 'YDC_main',
      },
      {
        reading: 'ほほ笑む',
        kana: 'ほほえむ',
        meaning: ['To smile gently', 'To beam'],
        sentence: '赤ちゃんがほほ笑んでいます。',
        type: 'secondary',
      },
      {
        reading: '微笑',
        kana: 'びしょう',
        meaning: ['Slight Smile'],
        sentence: '彼女は微笑を浮かべて話しました。',
        type: 'secondary',
      },
      {
        reading: '爆笑する',
        kana: 'ばくしょうする',
        meaning: ['To burst into laughter'],
        sentence: 'そのコメディ映画を見て爆笑しました。',
        type: 'secondary',
      },
      {
        reading: '苦笑い',
        kana: 'にがわらい',
        meaning: ['Bitter smile', 'Forced smile'],
        sentence: '彼の苦笑いが印象的でした。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '泣',
    onyomi: ['きゅう'],
    kunyomi: ['な'],
    meaning: ['Cry'],
    examples: [
      {
        reading: '泣く',
        kana: 'なく',
        meaning: ['To cry'],
        sentence: '赤ちゃんが泣いています。',
        type: 'YDC_main',
      },
      {
        reading: '鳴き声',
        kana: 'なきごえ',
        meaning: ['Cry'],
        sentence: '鳥の鳴き声が聞こえます。',
        type: 'secondary',
      },
      {
        reading: '泣き虫',
        kana: 'なきむし',
        meaning: ['Crybaby'],
        sentence: '彼はちょっとしたことで泣き虫になります。',
        type: 'secondary',
      },
      {
        reading: '嬉し泣き',
        kana: 'うれしなき',
        meaning: ['Tears of joy'],
        sentence: '感動して嬉し泣きをしました。',
        type: 'secondary',
      },
      {
        reading: '号泣する',
        kana: 'ごうきゅうする',
        meaning: ['To wail', 'To weep loudly'],
        sentence: '映画を見て号泣しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '怒',
    onyomi: ['ど'],
    kunyomi: ['おこ', 'いか'],
    meaning: ['Angry'],
    examples: [
      {
        reading: '怒る',
        kana: 'おこる',
        meaning: ['To get angry', 'To be angry'],
        sentence: '彼は遅刻して怒っています。',
        type: 'YDC_main',
      },
      {
        reading: '怒り',
        kana: 'いかり',
        meaning: ['Anger', 'Fury'],
        sentence: '彼の怒りは理解できます。',
        type: 'secondary',
      },
      {
        reading: '怒鳴る',
        kana: 'どなる',
        meaning: ['To shout', 'To yell'],
        sentence: '彼は大声で怒鳴りました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '幸',
    onyomi: ['こう'],
    kunyomi: ['しあわ', 'さいわ', 'さち'],
    meaning: ['Happiness'],
    examples: [
      {
        reading: '幸せな',
        kana: 'しあわせな',
        meaning: ['Happy', 'Fortunate'],
        sentence: '彼女は幸せな結婚生活を送っています。',
        type: 'YDC_main',
      },
      {
        reading: '不幸',
        kana: 'ふこう',
        meaning: ['Unhappiness', 'Misfortune'],
        sentence: '不幸な出来事が続きました。',
        type: 'YDC_main',
      },
      {
        reading: '幸運',
        kana: 'こううん',
        meaning: ['Good luck', 'Fortune'],
        sentence: '幸運を祈っています。',
        type: 'secondary',
      },
      {
        reading: '幸い',
        kana: 'さいわい',
        meaning: ['Fortunately', 'Happily'],
        sentence: '幸いにも、事故は軽傷で済みました。',
        type: 'secondary',
      },
      {
        reading: '幸福な',
        kana: 'こうふくな',
        meaning: ['Happy', 'Fortunate'],
        sentence: '彼は幸福な家庭を築いています。',
        type: 'secondary',
      },
      {
        reading: '幸',
        kana: 'さち',
        meaning: ['Happiness', 'Good fortune'],
        sentence: '幸は自分の手で作るものです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '悲',
    onyomi: ['ひ'],
    kunyomi: ['かな'],
    meaning: ['Sad'],
    examples: [
      {
        reading: '悲しい',
        kana: 'かなしい',
        meaning: ['Sad', 'Sorrowful'],
        sentence: '彼の話を聞いて悲しくなりました。',
        type: 'YDC_main',
      },
      {
        reading: '悲しむ',
        kana: 'かなしむ',
        meaning: ['To grieve', 'To mourn'],
        sentence: '彼女は友人の死を悲しんでいます。',
        type: 'YDC_main',
      },
      {
        reading: '悲劇',
        kana: 'ひげき',
        meaning: ['Tragedy'],
        sentence: 'その映画は悲劇的な結末を迎えました。',
        type: 'secondary',
      },
      {
        reading: '悲惨な',
        kana: 'ひさんな',
        meaning: ['Miserable'],
        sentence: '悲惨な事故が起きました。',
        type: 'secondary',
      },
      {
        reading: '悲観する',
        kana: 'ひかんする',
        meaning: ['To be pessimistic'],
        sentence: '未来に対して悲観的な見方をしています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '苦',
    onyomi: ['く'],
    kunyomi: ['にが', 'くる'],
    meaning: ['To suffer', 'Bitter'],
    examples: [
      {
        reading: '苦い',
        kana: 'にがい',
        meaning: ['Bitter'],
        sentence: 'この薬は苦い味がします。',
        type: 'YDC_main',
      },
      {
        reading: '苦手',
        kana: 'にがて',
        meaning: ['Weak at', 'Not good at'],
        sentence: '私は数学が苦手です。',
        type: 'YDC_main',
      },
      {
        reading: '苦しい',
        kana: 'くるしい',
        meaning: ['Painful', 'Difficult'],
        sentence: '彼は苦しい状況に置かれています。',
        type: 'YDC_main',
      },
      {
        reading: '苦しむ',  
        kana: 'くるしむ',
        meaning: ['To suffer', 'To be in pain'],
        sentence: '病気で苦しんでいる人が多いです。',
        type: 'YDC_main',
      },
      {
        reading: '苦痛',
        kana: 'くつう',
        meaning: ['Pain', 'Suffering'],
        sentence: '手術後の苦痛が続きました。',
        type: 'YDC_main',
      },
      {
        reading: '苦労',
        kana: 'くろう',
        meaning: ['Hardship', 'Difficulty'],
        sentence: '彼は苦労して成功を収めました。',
        type: 'secondary',
      },
      {
        reading: '苦情',
        kana: 'くじょう',
        meaning: ['Complaint', 'Objection'],
        sentence: 'お客様から苦情が寄せられました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '痛',
    onyomi: ['つう'],
    kunyomi: ['いた'],
    meaning: ['Pain', 'Hurt'],
    examples: [
      {
        reading: '痛い',  
        kana: 'いたい',
        meaning: ['Painful', 'Hurt'],
        sentence: '足が痛いので、しばらく休みます。',
        type: 'YDC_main',
      },
      {
        reading: '痛み',
        kana: 'いたみ',
        meaning: ['Pain', 'Ache'],
        sentence: '頭の痛みが続いています。',
        type: 'YDC_main',
      },
      {
        reading: '頭痛',
        kana: 'ずつう',
        meaning: ['Headache'],
        sentence: '頭痛がひどいので、薬を飲みました。',
        type: 'YDC_main',
      },
      {
        reading: '苦痛',
        kana: 'くつう',
        meaning: ['Pain', 'Suffering'],
        sentence: '手術後の苦痛が続きました。',
        type: 'YDC_main',
      },
      {
        reading: '痛み止め',
        kana: 'いたみどめ',
        meaning: ['Painkiller'],
        sentence: '痛み止めの薬を飲みました。',
        type: 'secondary',
      },
      {
        reading: '腹痛',
        kana: 'ふくつう',
        meaning: ['Stomachache'],
        sentence: '腹痛で学校を休みました。',
        type: 'secondary',
      },
      {
        reading: '腰痛',
        kana: 'ようつう',
        meaning: ['Lower Back pain'],
        sentence: '腰痛がひどくて動けません。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '恥',
    onyomi: ['ち'],
    kunyomi: ['は', 'はじ'],
    meaning: ['Shame'],
    examples: [
      {
        reading: '恥ずかしい',  
        kana: 'はずかしい',
        meaning: ['To be embarrassed', 'Ashamed'],
        sentence: '彼の前で恥ずかしいことを言ってしまいました。',
        type: 'YDC_main',
      },
      {
        reading: '恥',
        kana: 'はじ',
        meaning: ['Shame', 'Embarrassment'],
        sentence: '失敗して恥をかきました。',
        type: 'main',
      },
      {
        reading: '恥ずかしがる',
        kana: 'はずかしがる',
        meaning: ['To be shy'],
        sentence: '彼女は人前で恥ずかしがります。',
        type: 'secondary',
      },
      {
        reading: '恥じる',
        kana: 'はじる',
        meaning: ['To be ashamed', 'To feel ashamed'],
        sentence: '自分の行動を恥じています。',
        type: 'secondary',
      },
      {
        reading: '恥知らず',
        kana: 'はじしらず',
        meaning: ['Shameless person'],
        sentence: '彼は恥知らずな行動をしました。',
        type: 'secondary',
      },
      {
        reading: '羞恥心',
        kana: 'しゅうちしん',
        meaning: ['Sense of shame'],
        sentence: '羞恥心を持つことは大切です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '配',
    onyomi: ['ぱい', 'はい'],
    kunyomi: ['くば'],
    meaning: ['To Deliver'],
    examples: [
      {
        reading: '心配する',
        kana: 'しんぱいする',
        meaning: ['To worry', 'To be anxious'],
        sentence: '彼の健康を心配しています。',
        type: 'YDC_main',
      },
      {
        reading: '配る',
        kana: 'くばる',
        meaning: ['To distribute', 'To hand out'],
        sentence: 'チラシを配る仕事をしています。',
        type: 'YDC_main',
      },
      {
        reading: '配達',
        kana: 'はいたつ',
        meaning: ['Delivery'],
        sentence: 'ピザの配達を頼みました。',
        type: 'secondary',
      },
      {
        reading: '支配',
        kana: 'しはい',
        meaning: ['Control', ' Rule'],
        sentence: 'その国は長い間、外国の支配下にありました。',
        type: 'secondary',
      },
      {
        reading: '配偶者',
        kana: 'はいぐうしゃ',
        meaning: ['Spouse'],
        sentence: '配偶者と一緒に旅行に行きました。',
        type: 'secondary',
      },
      {
        reading: '支配人',
        kana: 'しはいにん',
        meaning: ['Manager', 'Director'],
        sentence: 'ホテルの支配人と話しました。',
        type: 'secondary',
      },
      {
        reading: '宅配便',
        kana: 'たくはいびん',
        meaning: ['Home delivery service'],
        sentence: '宅配便で荷物が届きました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '困',
    onyomi: ['こん'],
    kunyomi: ['こま'],
    meaning: ['Trouble'],
    examples: [
      {
        reading: '困る',
        kana: 'こまる',
        meaning: ['To be in trouble'],
        sentence: 'お金がなくて困っています。',
        type: 'YDC_main',
      },
      {
        reading: '困難な',
        kana: 'こんなんな',
        meaning: ['Difficult', 'Challenging'],
        sentence: '困難な状況に直面しています。',
        type: 'secondary',
      },
      {
        reading: '貧困',
        kana: 'ひんこん',
        meaning: ['Poverty'],
        sentence: '貧困問題は世界的な課題です。',
        type: 'secondary',
      },
      {
        reading: '困惑',
        kana: 'こんわく',
        meaning: ['Confusion'],
        sentence: '彼の突然の質問に困惑しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '辛',
    onyomi: ['しん'],
    kunyomi: ['から'],
    meaning: ['Spicy'],
    examples: [
      {
        reading: '辛い',
        kana: 'からい',
        meaning: ['Spicy', 'Hot'],
        sentence: 'このカレーはとても辛いです。',
        type: 'YDC_main',
      },
      {
        reading: '塩辛い',
        kana: 'しおからい',
        meaning: ['Salty'],
        sentence: 'この魚は塩辛い味がします。',
        type: 'secondary',
      },
      {
        reading: '香辛料',
        kana: 'こうしんりょう',
        meaning: ['Spices'],
        sentence: 'カレーには多くの香辛料が使われています。',
        type: 'secondary',
      },
      {
        reading: '辛抱',
        kana: 'しんぼう',
        meaning: ['Patience', 'Endurance'],
        sentence: '辛抱強く待つことが大切です。',
        type: 'secondary',
      },
      {
        reading: '辛子',
        kana: 'からし',
        meaning: ['Mustard'],
        sentence: 'おでんに辛子をつけて食べます。',
        type: 'secondary',
      },
      {
        reading: '辛い',
        kana: 'つらい',
        meaning: ['Painful', 'Arduous'],
        sentence: '別れはいつも辛いものです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '眠',
    onyomi: ['みん'],
    kunyomi: ['ねむ'],
    meaning: ['To Sleep'],
    examples: [
      {
        reading: '眠い・眠たい',
        kana: 'ねむい・ねむたい',
        meaning: ['Sleepy'],
        sentence: '昨夜はあまり寝られなかったので、眠いです。',
        type: 'YDC_main',
      },
      {
        reading: '眠る',
        kana: 'ねむる',
        meaning: ['To sleep'],
        sentence: '赤ちゃんが眠っています。',
        type: 'YDC_main',
      },
      {
        reading: '睡眠',
        kana: 'すいみん',
        meaning: ['Sleeping'],
        sentence: '十分な睡眠は健康に大切です。',
        type: 'secondary',
      },
      {
        reading: '居眠り',
        kana: 'いねむり',
        meaning: ['Dozing'],
        sentence: '授業中に居眠りしてしまいました。',
        type: 'secondary',
      },
      {
        reading: '冬眠',
        kana: 'とうみん',
        meaning: ['Hibernation'],
        sentence: 'クマは冬眠します。',
        type: 'secondary',
      },
      {
        reading: '催眠術',
        kana: 'さいみんじゅつ',
        meaning: ['Hypnosis'],
        sentence: '催眠術は人の意識を変える技術です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '残',
    onyomi: ['ざん'],
    kunyomi: ['のこ'],
    meaning: ['To remain'],
    examples: [
      {
        reading: '残念な',
        kana: 'ざんねんな',
        meaning: ['Regrettable', 'Disappointing'],
        sentence: '試験に落ちて残念でした。',
        type: 'YDC_main',
      },
      {
        reading: '残る',
        kana: 'のこる',
        meaning: ['To remain', 'To be left'],
        sentence: '食べ物が残っています。',
        type: 'YDC_main',
      },
      {
        reading: '残す',
        kana: 'のこす',
        meaning: ['To leave something behind'],
        sentence: '宿題を残してしまいました。',
        type: 'YDC_main',
      },
      {
        reading: '残り',
        kana: 'のこり',
        meaning: ['Remainder', 'Leftover'],
        sentence: '残り物を食べました。',
        type: 'YDC_main',
      },
      {
        reading: '残業',
        kana: 'ざんぎょう',
        meaning: ['Overtime work'],
        sentence: '今日は残業が多かったです。',
        type: 'main',
      },
      {
        reading: '残高',
        kana: 'ざんだか',
        meaning: ['Balance (of an account)'],
        sentence: '銀行の残高を確認しました。',
        type: 'main',
      },
      {
        reading: '残らず',
        kana: 'のこらず',
        meaning: ['All', 'Without exception'],
        sentence: '彼は残らず全ての資料を提出しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '念',
    onyomi: ['ねん'],
    kunyomi: [],
    meaning: ['Thought'],
    examples: [
      {
        reading: '残念な',
        kana: 'ざんねんな',
        meaning: ['Regrettable', 'Disappointing'],
        sentence: '試験に落ちて残念でした。',
        type: 'YDC_main',
      },
      {
        reading: '記念',
        kana: 'きねん',
        meaning: ['Remembrance'],
        sentence: '結婚記念日に特別なディナーを用意しました。',
        type: 'secondary',
      },
      {
        reading: '記念日',
        kana: 'きねんび',
        meaning: ['Memorial day'],
        sentence: '今日は私たちの結婚記念日です。',
        type: 'secondary',
      },
      {
        reading: '信念',
        kana: 'しんねん',
        meaning: ['Belief', 'Conviction'],
        sentence: '彼は自分の信念を貫いています。',
        type: 'secondary',
      },
      {
        reading: '念願',
        kana: 'ねんがん',
        meaning: ['Long-cherished desire'],
        sentence: '念願の夢が叶いました。',
        type: 'secondary',
      },
      {
        reading: '無念',
        kana: 'むねん',
        meaning: ['Regret', 'Mortification'],
        sentence: '試合に負けて無念の思いです。',
        type: 'secondary',
      },
      {
        reading: '概念',
        kana: 'がいねん',
        meaning: ['Concept'],
        sentence: 'この概念は非常に重要です。',
        type: 'secondary',
      },
      {
        reading: '断念する',
        kana: 'だんねんする',
        meaning: ['To give up', 'To abandon a plan'],
        sentence: '計画を断念することにしました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '感',
    onyomi: ['かん'],
    kunyomi: [],
    meaning: ['To feel'],
    examples: [
      {
        reading: '感じる',
        kana: 'かんじる',
        meaning: ['To feel', 'To sense'],
        sentence: '彼の言葉に深い感動を感じました。',
        type: 'YDC_main',
      },
      {
        reading: '感じ',
        kana: 'かんじ',
        meaning: ['Feeling', 'Impression'],
        sentence: 'この映画はとても感動的な感じがしました。',
        type: 'YDC_main',
      },
      {
        reading: '感動する',
        kana: 'かんどうする',
        meaning: ['To be moved', 'To be touched'],
        sentence: 'その話を聞いて感動しました。',
        type: 'YDC_main',
      },
      {
        reading: '感謝',
        kana: 'かんしゃ',
        meaning: ['Gratitude', 'Thankfulness'],
        sentence: '彼の助けに感謝しています。',
        type: 'secondary',
      },
      {
        reading: '感想',
        kana: 'かんそう',
        meaning: ['Impression', 'Thoughts'],
        sentence: '映画の感想を友達に話しました。',
        type: 'secondary',
      },
      {
        reading: '感激する',
        kana: 'かんげきする',
        meaning: ['To be deeply moved'],
        sentence: '彼の演説に感激しました。',
        type: 'secondary',
      },
      {
        reading: '感心する',
        kana: 'かんしんする',
        meaning: ['To be impressed'],
        sentence: '彼の努力に感心しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '情',
    onyomi: ['じょう', 'せい', 'ぜい'],
    kunyomi: ['なさ'],
    meaning: ['Feeling'],
    examples: [
      {
        reading: '感情',
        kana: 'かんじょう',
        meaning: ['Emotion', 'Feeling'],
        sentence: '彼の感情を理解するのは難しいです。',
        type: 'YDC_main',
      },
      {
        reading: '苦情',
        kana: 'くじょう',
        meaning: ['Complaint', 'Objection'],
        sentence: 'お客様から苦情が寄せられました。',
        type: 'YDC_main',
      },
      {
        reading: '事情',
        kana: 'じじょう',
        meaning: ['Circumstances', 'Situation'],
        sentence: '事情があって、参加できませんでした。',
        type: 'YDC_main',
      },
      {
        reading: '友情',
        kana: 'ゆうじょう',
        meaning: ['Friendship'],
        sentence: '友情は大切なものです。',
        type: 'YDC_main',
      },
      {
        reading: '表情',
        kana: 'ひょうじょう',
        meaning: ['Facial expression'],
        sentence: '彼女の表情から、彼女の気持ちがわかりました。',
        type: 'secondary',
      },
      {
        reading: '情報',
        kana: 'じょうほう',
        meaning: ['Information'],
        sentence: '最新の情報を提供します。',
        type: 'secondary',
      },
      {
        reading: '情け',
        kana: 'なさけ',
        meaning: ['Mercy', 'Compassion'],
        sentence: '情けは人のためならずと言います。',
        type: 'secondary',
      },
      {
        reading: '風情',
        kana: 'ふぜい',
        meaning: ['Elegance', 'Taste'],
        sentence: 'この町には古い風情があります。',
        type: 'secondary',
      },
    ],
  },
]