export const KANJI_YDC_LESSON_17: Array<KanjiYDC> = [
  {
    kanji: '医',
    onyomi: ['い'],
    kunyomi: [],
    meaning: ['Medicine', 'Doctor'],
    examples: [
      {
        reading: '医者',
        kana: 'いしゃ',
        meaning: ['Doctor'],
        sentence: '医者に行くときは、予約をしてから行くことが多いです。',
        type: 'main',
      },
      {
        reading: '医師',
        kana: 'いし',
        meaning: ['Physician', 'Doctor'],
        sentence: '医師は患者の健康を守るために、日々努力しています。',
        type: 'main',
      },
      {
        reading: '医学',
        kana: 'いがく',
        meaning: ['Medical science'],
        sentence: '医学の勉強をするために、大学に進学しました。',
        type: 'main',
      },
      {
        reading: '歯医者',
        kana: 'はいしゃ',
        meaning: ['Dentist'],
        sentence: '歯医者に行くのは少し緊張しますが、定期的に検診を受けることが大切です。',
        type: 'main',
      },
      {
        reading: '医院',
        kana: 'いいん',
        meaning: ['Clinic'],
        sentence: '近くに新しい医院がオープンしました。',
        type: 'main',
      },
      {
        reading: '医療',
        kana: 'いりょう',
        meaning: ['Medical care', 'Medical treatment'],
        sentence: '医療制度の改善が求められています。',
        type: 'main',
      },
      {
        reading: '医薬品',
        kana: 'いりゃくひん',
        meaning: ['Medicinal products', 'Medicinal supplies'],
        sentence: '医薬品の購入には、処方箋が必要な場合があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '始',
    onyomi: ['し'],
    kunyomi: ['はじ'],
    meaning: ['Begin', 'Start'],
    examples: [
      {
        reading: '始まる',
        kana: 'はじまる',
        meaning: ['To begin (Something begins)'],
        sentence: '授業が始まる前に、教室に入って準備をします。',
        type: 'main',
      },
      {
        reading: '始める',
        kana: 'はじめる',
        meaning: ['To start (something)'],
        sentence: '新しいプロジェクトを始めるために、チームを結成しました。',
        type: 'main',
      },
      {
        reading: '開始する',
        kana: 'かいしする',
        meaning: ['To start (Something)'],
        sentence: '会議は午後2時に開始される予定です。',
        type: 'main',
      },
      {
        reading: '始終',
        kana: 'しじゅう',
        meaning: ['Always', 'From beginning to end', 'All the time'],
        sentence: '彼は始終忙しそうにしているので、あまり話す機会がありません。',
        type: 'main',
      },
      {
        reading: '書き始める',
        kana: 'かきはじめる',
        meaning: ['To start writing'],
        sentence: '新しい小説を書き始めることにしました。',
        type: 'main',
      },
      {
        reading: '始発',
        kana: 'しはつ',
        meaning: ['First train of the day'],
        sentence: '始発の電車に乗るために、早起きしました。',
        type: 'main',
      },
      {
        reading: '原始的な',
        kana: 'げんしてきな',
        meaning: ['Primitive'],
        sentence: '原始的な生活様式は、現代社会とは大きく異なります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '終',
    onyomi: ['しゅう', 'じゅう'],
    kunyomi: ['お'],
    meaning: ['End', 'Finish'],
    examples: [
      {
        reading: '終わる',
        kana: 'おわる',
        meaning: ['To end (Something ends)', 'To come to an end'],
        sentence: '授業が終わったら、友達と一緒にランチを食べに行きました。',
        type: 'main',
      },
      {
        reading: '終わり',
        kana: 'おわり',
        meaning: ['End'],
        sentence: '映画の終わりがとても感動的でした。',
        type: 'main',
      },
      {
        reading: '終える',
        kana: 'おえる',
        meaning: ['To finish (Something)'],
        sentence: '宿題を終えたら、友達と遊びに行く予定です。',
        type: 'main',
      },
      {
        reading: '最終',
        kana: 'さいしゅう',
        meaning: ['Final', 'Last'],
        sentence: '最終回の放送が楽しみです。',
        type: 'main',
      },
      {
        reading: '終了',
        kana: 'しゅうりょう',
        meaning: ['End', 'Completion'],
        sentence: '試験の終了時間が近づいてきました。',
        type: 'main',
      },
      {
        reading: '終電',
        kana: 'しゅうでん',
        meaning: ['Last train of the day'],
        sentence: '終電を逃さないように、急いで駅に向かいました。',
        type: 'main',
      },
      {
        reading: '終点',
        kana: 'しゅうてん',
        meaning: ['Last stop', 'Final destination'],
        sentence: 'この電車の終点は、東京駅です。',
        type: 'main',
      },
      {
        reading: '始終',
        kana: 'しじゅう',
        meaning: ['Always', 'From beginning to end', 'All the time'],
        sentence: '彼は始終忙しそうにしているので、あまり話す機会がありません。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '石',
    onyomi: ['せき', 'せっ', 'しゃく', 'こく'],
    kunyomi: ['いし'],
    meaning: ['Stone'],
    examples: [
      {
        reading: '宝石',
        kana: 'ほうせき',
        meaning: ['Gem', 'Jewel'],
        sentence: '宝石店で美しい宝石を見つけました。',
        type: 'secondary',
      },
      {
        reading: '石鹸',
        kana: 'せっけん',
        meaning: ['Soap'],
        sentence: '石鹸で手を洗うことは、衛生的です。',
        type: 'main',
      },
      {
        reading: '石油',
        kana: 'せきゆ',
        meaning: ['Petroleum', 'Oil'],
        sentence: '石油はエネルギー源として重要な資源です。',
        type: 'secondary',
      },
      {
        reading: '石炭',
        kana: 'せきたん',
        meaning: ['Coal'],
        sentence: '石炭は、昔からエネルギー源として利用されてきました。',
        type: 'secondary',
      },
      {
        reading: '磁石',
        kana: 'じしゃく',
        meaning: ['Magnet'],
        sentence: '磁石を使って、鉄のものを引き寄せることができます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '研',
    onyomi: ['けん'],
    kunyomi: ['と'],
    meaning: ['Polish', 'Study'],
    examples: [
      {
        reading: '研究',
        kana: 'けんきゅう',
        meaning: ['Research'],
        sentence: '大学での研究は、専門知識を深めるために重要です。',
        type: 'main',
      },
      {
        reading: '研究者',
        kana: 'けんきゅうしゃ',
        meaning: ['Researcher'],
        sentence: '研究者は新しい発見をするために、日々努力しています。',
        type: 'main',
      },
      {
        reading: '研究室',
        kana: 'けんきゅうしつ',
        meaning: ['Laboratory', 'Research room'],
        sentence: '研究室では、さまざまな実験が行われています。',
        type: 'main',
      },
      {
        reading: '研究所',
        kana: 'けんきゅうじょ・けんきゅうしょ',
        meaning: ['Research institute'],
        sentence: '新しい技術の開発を行う研究所が設立されました。',
        type: 'secondary',
      },
      {
        reading: '研修',
        kana: 'けんしゅう',
        meaning: ['Training'],
        sentence: '新入社員は研修を受けて、会社のルールを学びます。',
        type: 'secondary',
      },
      {
        reading: '研ぐ',
        kana: 'とぐ',
        meaning: ['To sharpen', 'To polish'],
        sentence: '包丁を研ぐことで、切れ味が良くなります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '究',
    onyomi: ['きゅう'],
    kunyomi: ['きわ'],
    meaning: ['Research', 'Study'],
    examples: [
      {
        reading: '研究',
        kana: 'けんきゅう',
        meaning: ['Research'],
        sentence: '大学での研究は、専門知識を深めるために重要です。',
        type: 'main',
      },
      {
        reading: '研究者',
        kana: 'けんきゅうしゃ',
        meaning: ['Researcher'],
        sentence: '研究者は新しい発見をするために、日々努力しています。',
        type: 'main',
      },
      {
        reading: '研究室',
        kana: 'けんきゅうしつ',
        meaning: ['Laboratory', 'Research room'],
        sentence: '研究室では、さまざまな実験が行われています。',
        type: 'main',
      },
      {
        reading: '究明',
        kana: 'きゅうめい',
        meaning: ['Investigation', 'Clarification'],
        sentence: '事件の真相を究明するために、捜査が行われています。',
        type: 'secondary',
      },
      {
        reading: '究極の',
        kana: 'きゅうきょくの',
        meaning: ['Ultimate'],
        sentence: '究極の選択を迫られる場面が多いです。',
        type: 'secondary',
      },
      {
        reading: '究める',
        kana: 'きわめる',
        meaning: ['To investigate thoroughly', 'To master'],
        sentence: 'この分野を究めるために、長い時間をかけて勉強しています。',
        type: 'secondary',
      },
      {
        reading: '探究',
        kana: 'たんきゅう',
        meaning: ['Inquiry'],
        sentence: '探究心を持って、さまざまなことに挑戦しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '留',
    onyomi: ['りゅう', 'る'],
    kunyomi: ['と'],
    meaning: ['To Stay'],
    examples: [
      {
        reading: '留学する',  
        kana: 'りゅうがくする',
        meaning: ['To study abroad'],
        sentence: '彼はアメリカに留学することを決めました。',
        type: 'main',
      },
      {
        reading: '留学生',
        kana: 'りゅうがくせい',
        meaning: ['International student'],
        sentence: '留学生として、日本の文化を学ぶことができて嬉しいです。',
        type: 'main',
      },
      {
        reading: '留守',
        kana: 'るす',
        meaning: ['Absence', 'Not at home'],
        sentence: '留守の間に、宅配便が届きました。',
        type: 'main',
      },
      {
        reading: '留守番電話',
        kana: 'るすばんでんわ',
        meaning: ['Answering machine'],
        sentence: '留守番電話にメッセージが残っていました。',
        type: 'main',
      },
      {
        reading: '留める',  
        kana: 'とめる',
        meaning: ['To fasten'],
        sentence: '書類をクリップで留めておきました。',
        type: 'secondary',
      },
      {
        reading: '書留(書き留め)',
        kana: 'かきとめ',
        meaning: ['Registered mail'],
        sentence: '重要な書類は、書留で送ることにしました。',
        type: 'main',  
      },
    ],
  },
  {
    kanji: '有',
    onyomi: ['ゆう', 'う'],
    kunyomi: ['あ'],
    meaning: ['Exist', 'Have'],
    examples: [
      {
        reading: '有名な',  
        kana: 'ゆうめいな',
        meaning: ['Famous'],
        sentence: '彼は有名な作家です。',
        type: 'main',
      },
      {
        reading: '有る',
        kana: 'ある',
        meaning: ['To exist', 'To have'],
        sentence: 'この町には美しい公園が有ります。',
        type: 'main',
      },
      {
        reading: '有料',
        kana: 'ゆうりょう',
        meaning: ['Toll', 'Fee'],
        sentence: 'この駐車場は有料です。',
        type: 'main',
      },
      {
        reading: '有利な',
        kana: 'ゆうりな',
        meaning: ['Advantageous'],
        sentence: 'この条件は有利なものです。',
        type: 'secondary',
      },
      {
        reading: '有効な',
        kana: 'ゆうこうな',
        meaning: ['Valid', 'Effective'],
        sentence: 'このクーポンは有効期限が切れています。',
        type: 'secondary',
      },
      {
        reading: '有能な',
        kana: 'ゆうのうな',
        meaning: ['Talented', 'Competent'],
        sentence: '彼は有能なエンジニアです。',
        type: 'secondary',
      },
      {
        reading: '有難い（有り難い）',
        kana: 'ありがたい',
        meaning: ['Grateful', 'Thankful'],
        sentence: '忙しい中、わざわざ時間を作って手伝ってくれて、本当に有り難かったです。',
        type: 'main',
      },
      {
        reading: '有無',
        kana: 'うむ',
        meaning: ['To have or not have', 'Existence or non-existence', 'Whether or not'],
        sentence: '応募の際は、日本での就労資格の有無を明記してください。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '産',
    onyomi: ['さん'],
    kunyomi: ['う', 'うぶ'],
    meaning: ['Produce', 'Give birth'],
    examples: [
      {
        reading: '産業',
        kana: 'さんぎょう',
        meaning: ['Industry'],
        sentence: 'この地域の主要な産業は農業です。',
        type: 'main',
      },
      {
        reading: '生産',
        kana: 'せいさん',
        meaning: ['Production'],
        sentence: 'この工場では、自動車の生産が行われています。',
        type: 'main',
      },
      {
        reading: 'お土産',
        kana: 'おみやげ',
        meaning: ['Souvenir'],
        sentence: '旅行のお土産に、地元の特産品を買いました。',
        type: 'main',
      },
      {
        reading: '産地',
        kana: 'さんち',
        meaning: ['Source of products'],
        sentence: 'この野菜は新鮮な産地から取り寄せています。',
        type: 'secondary',
      },
      {
        reading: '共産主義',
        kana: 'きょうさんしゅぎ',
        meaning: ['Communism'],
        sentence: '共産主義は、資本主義とは異なる経済体制です。',
        type: 'secondary',
      },
      {
        reading: '財産',
        kana: 'ざいさん',
        meaning: ['Property', 'Assets'],
        sentence: '彼は多くの財産を持っています。',
        type: 'secondary',
      },
      {
        reading: '産む',
        kana: 'うむ',
        meaning: ['To give birth'],
        sentence: '彼女は元気な赤ちゃんを産みました。',
        type: 'main',
      },
      {
        reading: '不動産',
        kana: 'ふどうさん',
        meaning: ['Real estate'],
        sentence: '不動産の購入は、大きな投資です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '業',
    onyomi: ['ぎょう', 'ごう'],
    kunyomi: ['わざ'],
    meaning: ['Business', 'Industry'],
    examples: [ 
      {
        reading: '工業',
        kana: 'こうぎょう',
        meaning: ['Manufacturing industry'],
        sentence: '工業はこの地域の主要な産業です。',
        type: 'main',
      },
      {
        reading: '授業',
        kana: 'じゅぎょう',
        meaning: ['Class'],
        sentence: '授業は午後から始まります。',
        type: 'main',
      },
      {
        reading: '卒業',
        kana: 'そつぎょう',
        meaning: ['Graduation'],
        sentence: '大学を卒業したら、就職活動を始めます。',
        type: 'secondary',
      },
      {
        reading: '職業',
        kana: 'しょくぎょう',
        meaning: ['Occupation', 'Profession'],
        sentence: '彼は医者という職業を選びました。',
        type: 'main',
      },
      {
        reading: '企業',
        kana: 'きぎょう',
        meaning: ['Enterprise'],
        sentence: '企業の成長には、革新が必要です。',
        type: 'secondary',
      },
      {
        reading: '営業中',
        kana: 'えいぎょうちゅう',
        meaning: ['Open for business'],
        sentence: 'この店は営業中です。',
        type: 'secondary',
      },
      {
        reading: '自業自得',
        kana: 'じごうじとく',
        meaning: ['You reap what you sow'],
        sentence: '自業自得という言葉は、自分の行動の結果を受け入れることを意味します。',
        type: 'secondary',
      },
      {
        reading: '農業',
        kana: 'のうぎょう',
        meaning: ['Agriculture'],
        sentence: '農業はこの地域の重要な産業です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '薬',
    onyomi: ['やく', 'やっ'],
    kunyomi: ['くすり', 'ぐすり'],
    meaning: ['Medicine'],
    examples: [
      {
        reading: '薬',
        kana: 'くすり',
        meaning: ['Medicine'],
        sentence: '風邪をひいたので、薬を飲みました。',
        type: 'main',
      },
      {
        reading: '薬屋',
        kana: 'くすりや',
        meaning: ['Pharmacy'],
        sentence: '薬屋で風邪薬を買いました。',
        type: 'main',
      },
      {
        reading: '薬局',
        kana: 'やっきょく',
        meaning: ['Pharmacy'],
        sentence: '薬局で処方箋を持って、薬を受け取りました。',
        type: 'main',
      },
      {
        reading: '農薬',
        kana: 'のうやく',
        meaning: ['Agricultural chemicals'],
        sentence: '農薬を使うことで、作物の病気を防ぎます。',
        type: 'secondary',
      },
      {
        reading: '薬指',
        kana: 'くすりゆび',
        meaning: ['Ring finger'],
        sentence: '薬指に指輪をはめることが多いです。',
        type: 'secondary',
      },
      {
        reading: '風邪薬',
        kana: 'かぜぐすり',
        meaning: ['Cold medicine'],
        sentence: '風邪薬を飲んで、早く治したいです。',
        type: 'main',
      },
      {
        reading: '薬学',
        kana: 'やくがく',
        meaning: ['Pharmaceutical science'],
        sentence: '薬学を学ぶことで、医療に貢献できるようになりたいです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '働',
    onyomi: ['どう'],
    kunyomi: ['はたら', 'ばたら'],
    meaning: ['Work', 'Labor'],
    examples: [
      {
        reading: '働く',
        kana: 'はたらく',
        meaning: ['To work'],
        sentence: '毎日、会社で働いています。',
        type: 'main',
      },
      {
        reading: '共働き',
        kana: 'ともばたらき',
        meaning: ['Dual-income family'],
        sentence: '共働きの家庭が増えています。',
        type: 'main',
      },
      {
        reading: '働き者',
        kana: 'はたらきもの',
        meaning: ['Hard worker'],
        sentence: '彼は働き者で、いつも忙しそうです。',
        type: 'secondary',
      },
      {
        reading: '労働',
        kana: 'ろうどう',
        meaning: ['Labor', 'Work'],
        sentence: '労働条件の改善が求められています。',
        type: 'main',
      },
      {
        reading: '労働者',
        kana: 'ろうどうしゃ',
        meaning: ['Worker'],
        sentence: '労働者の権利を守るために、法律が整備されています。',
        type: 'main',
      },
      {
        reading: '労働組合',
        kana: 'ろうどうくみあい',
        meaning: ['Labor union'],
        sentence: '労働組合は、労働者の権利を守るために活動しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '員',
    onyomi: ['いん'],
    kunyomi: [],
    meaning: ['Member'],
    examples: [
      {
        reading: '会社員',
        kana: 'かいしゃいん',
        meaning: ['Company employee'],
        sentence: '彼は大手企業の会社員です。',
        type: 'main',
      },
      {
        reading: '店員',
        kana: 'てんいん',
        meaning: ['Store clerk'],
        sentence: '店員に商品の場所を聞きました。',
        type: 'main',
      },
      {
        reading: '銀行員',
        kana: 'ぎんこういん',
        meaning: ['Bank employee'],
        sentence: '銀行員として働いています。',
        type: 'main',
      },
      {
        reading: '全員',
        kana: 'ぜんいん',
        meaning: ['All members'],
        sentence: '全員が参加することが求められています。',
        type: 'main',
      },
      {
        reading: '公務員',
        kana: 'こうむいん',
        meaning: ['Public servant'],
        sentence: '公務員は安定した職業とされています。',
        type: 'secondary',
      },
      {
        reading: '会員',
        kana: 'かいいん',
        meaning: ['Member'],
        sentence: 'このクラブの会員になるには、申し込みが必要です。',
        type: 'secondary',
      },
      {
        reading: '満員',
        kana: 'まんいん',
        meaning: ['Full', 'No vacancies'],
        sentence: 'この電車は満員です。',
        type: 'main',
      },
      {
        reading: '教員',
        kana: 'きょういん',
        meaning: ['Teacher'],
        sentence: '教員は学生の学びをサポートする役割があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '士',
    onyomi: ['し'],
    kunyomi: [],
    meaning: ['Warrior', 'Samurai'],
    examples: [
      {
        reading: '武士',
        kana: 'ぶし',
        meaning: ['Samurai'],
        sentence: '武士は日本の歴史において重要な役割を果たしました。',
        type: 'main',
      },
      {
        reading: '博士',
        kana: 'はかせ・はかせ',
        meaning: ['Doctor', 'PhD'],
        sentence: '彼は物理学の博士号を持っています。',
        type: 'secondary',
      },
      {
        reading: '修士',
        kana: 'しゅうし',
        meaning: ['Master\'s degree'],
        sentence: '彼女は修士号を取得しました。',
        type: 'main',
      },
      {
        reading: '弁護士',
        kana: 'べんごし',
        meaning: ['Lawyer'],
        sentence: '弁護士は法律の専門家です。',
        type: 'secondary',
      },
      {
        reading: '紳士',
        kana: 'しんし',
        meaning: ['Gentleman'],
        sentence: '彼はとても紳士的な態度で接してくれました。',
        type: 'main',
      },
      {
        reading: '消防士',
        kana: 'しょうぼうし',
        meaning: ['Firefighter'],
        sentence: '消防士は火災から人々を守るために働いています。',
        type: 'secondary',
      },
      {
        reading: '会計士',
        kana: 'かいけいし',
        meaning: ['Accountant'],
        sentence: '会計士は企業の財務を管理する専門家です。',
        type: 'main',
      },
      {
        reading: '税理士',
        kana: 'ぜいりし',
        meaning: ['Tax accountant'],
        sentence: '税理士は税金に関する専門家です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '仕',
    onyomi: ['し', 'じ'],
    kunyomi: ['つか'],
    meaning: ['To serve'],
    examples: [
      {
        reading: '仕事',
        kana: 'しごと',
        meaning: ['Work', 'Job'],
        sentence: '仕事が終わったら、友達と飲みに行く予定です。',
        type: 'main',
      },
      {
        reading: '仕方',
        kana: 'しかた',
        meaning: ['Method', 'Way'],
        sentence: '仕方がないので、諦めます。',
        type: 'secondary',
      },
      {
        reading: '仕上げる',
        kana: 'しあげる',
        meaning: ['To finish', 'To complete'],
        sentence: '宿題を仕上げるのに時間がかかりました。',
        type: 'main',
      },
      {
        reading: '仕返し',
        kana: 'しかえし',
        meaning: ['Revenge'],
        sentence: '彼は仕返しをするつもりです。',
        type: 'main',
      },
      {
        reading: '奉仕活動',
        kana: 'ほうしかつどう',
        meaning: ['Volunteer work'],
        sentence: '奉仕活動は社会貢献の一環です。',
        type: 'secondary',
      },
      {
        reading: '仕える',
        kana: 'つかえる',
        meaning: ['To serve'],
        sentence: '彼は会社に仕えることを誇りに思っています。',
        type: 'main',
      },
      {
        reading: '給仕',
        kana: 'きゅうじ',
        meaning: ['Waiter', 'Waitress'],
        sentence: '給仕が料理を運んできました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '事',
    onyomi: ['じ', 'ず'],
    kunyomi: ['こと', 'ごと'],
    meaning: ['Thing'],
    examples: [
      {
        reading: '事',
        kana: 'こと',
        meaning: ['Thing', 'Matter'],
        sentence: '大切な事を忘れないでください。',
        type: 'main',
      },
      {
        reading: '火事',
        kana: 'かじ',
        meaning: ['Fire'],
        sentence: '火事が発生したので、避難してください。',
        type: 'main',
      },
      {
        reading: '食事',
        kana: 'しょくじ',
        meaning: ['Meal'],
        sentence: '食事の時間になりました。',
        type: 'main',
      },
      {
        reading: '返事',
        kana: 'へんじ',
        meaning: ['Reply', 'Response'],
        sentence: 'メールの返事を待っています。',
        type: 'main',
      },
      {
        reading: '事故',
        kana: 'じこ',
        meaning: ['Accident'],
        sentence: '事故が起きたので、交通が混雑しています。',
        type: 'main',
      },
      {
        reading: '用事',
        kana: 'ようじ',
        meaning: ['Errand', 'Business'],
        sentence: '今日は用事があるので、早めに帰ります。',
        type: 'secondary',
      },
      {
        reading: '事務所',
        kana: 'じむしょ',
        meaning: ['Office'],
        sentence: '事務所で書類を整理しています。',
        type: 'main',
      },
    ],
  },
]