export const KANJI_YDC_LESSON_26: Array<KanjiYDC> = [
  {
    kanji: '遊',
    onyomi: ['ゆう', 'ゆ'],
    kunyomi: ['あそ'],
    meaning: ['Play', 'Amusement'],
    examples: [
      {
        reading: '遊ぶ',
        kana: 'あそぶ',
        meaning: ['To play', 'To have fun'],
        sentence: '子供たちは公園で遊んでいます。',
        type: 'YDC_main',
      },
      {
        reading: '遊び',
        kana: 'あそび',
        meaning: ['Play', 'Game'],
        sentence: '遊びの時間はとても楽しいです。',
        type: 'YDC_main',
      },
      {
        reading: '遊園地',
        kana: 'ゆうえんち',
        meaning: ['Amusement park'],
        sentence: '家族で遊園地に行きました。',
        type: 'YDC_main',
      },
      {
        reading: '周遊',
        kana: 'しゅうゆう',
        meaning: ['Tour', 'Round trip', 'excursion'],
        sentence: 'このバスは市内を周遊します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '泳',
    onyomi: ['えい'],
    kunyomi: ['およ'],
    meaning: ['Swim'],
    examples: [
      {
        reading: '泳ぐ',
        kana: 'およぐ',
        meaning: ['To swim'],
        sentence: '夏は海で泳ぐのが好きです。',
        type: 'YDC_main',
      },
      {
        reading: '水泳',
        kana: 'すいえい',
        meaning: ['Swimming'],
        sentence: '水泳の授業は楽しいです。',
        type: 'YDC_main',
      },
      {
        reading: '平泳ぎ',
        kana: 'ひらおよぎ',
        meaning: ['Breaststroke'],
        sentence: '平泳ぎは初心者におすすめの泳ぎ方です。',
        type: 'secondary',
      },
      {
        reading: '背泳ぎ',
        kana: 'せおよぎ',
        meaning: ['Backstroke'],
        sentence: '背泳ぎは背中を上にして泳ぎます。',
        type: 'secondary',
      },
      {
        reading: '競泳',
        kana: 'きょうえい',
        meaning: ['Competitive swimming'],
        sentence: '彼は競泳の選手として活躍しています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '疲',
    onyomi: ['ひ'],
    kunyomi: ['つか'],
    meaning: ['Tired', 'Exhausted'],
    examples: [
      {
        reading: '疲れる',
        kana: 'つかれる',
        meaning: ['To get tired', 'To be exhausted'],
        sentence: '長い仕事の後で疲れました。',
        type: 'YDC_main',
      },
      {
        reading: '疲れ',
        kana: 'つかれ',
        meaning: ['Fatigue', 'Tiredness'],
        sentence: '疲れが取れないので、早く寝ます。',
        type: 'YDC_main',
      },
      {
        reading: '疲労',
        kana: 'ひろう',
        meaning: ['Fatigue', 'Exhaustion'],
        sentence: '長時間の運転で疲労がたまりました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '暖',
    onyomi: ['だん'],
    kunyomi: ['あたた'],
    meaning: ['Warm'],
    examples: [
      {
        reading: '暖かい',
        kana: 'あたたかい',
        meaning: ['Warm', 'Mild'],
        sentence: '今日は暖かい日ですね。',
        type: 'YDC_main',
      },
      {
        reading: '温める',
        kana: 'あたためる',
        meaning: ['To warm up', 'To heat'],
        sentence: 'スープを温めてください。',
        type: 'YDC_main',
      },
      {
        reading: '温まる',
        kana: 'あたたまる',
        meaning: ['To get warm', 'To be heated'],
        sentence: '部屋が温まるまで待ちましょう。',
        type: 'secondary',
      },
      {
        reading: '暖房',
        kana: 'だんぼう',
        meaning: ['Heating', 'Heater'],
        sentence: '冬は暖房が必要です。',
        type: 'main',
      },
      {
        reading: '温暖な',
        kana: 'おんだんな',
        meaning: ['Warm'],
        sentence: 'この地域は温暖な気候です。',
        type: 'secondary',
      },
      {
        reading: '暖冬',
        kana: 'だんとう',
        meaning: ['Mild winter'],
        sentence: '今年の冬は暖冬でした。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '涼',
    onyomi: ['りょう'],
    kunyomi: ['すず'],
    meaning: ['Cool', 'Refreshing'],
    examples: [
      {
        reading: '涼しい',
        kana: 'すずしい',
        meaning: ['Cool', 'Refreshing'],
        sentence: '秋の風は涼しいです。',
        type: 'YDC_main',
      },
      {
        reading: '涼む',
        kana: 'すずむ',
        meaning: ['To cool off', 'To refresh oneself'],
        sentence: '川辺で涼んでいます。',
        type: 'secondary',
      },
      {
        reading: '清涼飲料水',
        kana: 'せいりょういんりょうすい',
        meaning: ['Soft drink', 'Refreshing beverage'],
        sentence: '夏は清涼飲料水がよく売れます。',
        type: 'main',
      },
      {
        reading: '夕涼み',
        kana: 'ゆうすずみ',
        meaning: ['Cooling oneself in the evening'],
        sentence: '夕涼みをしながら、星を見上げました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '静',
    onyomi: ['せい', 'じょう'],
    kunyomi: ['しず'],
    meaning: ['Quiet', 'Calm'],
    examples: [
      {
        reading: '静か',
        kana: 'しずか',
        meaning: ['Quiet', 'Calm'],
        sentence: 'この場所はとても静かです。',
        type: 'YDC_main',
      },
      {
        reading: '静まる',
        kana: 'しずまる',
        meaning: ['To calm down', 'To settle', 'To become quiet'],
        sentence: '嵐が静まるまで待ちましょう。',
        type: 'YDC_main',
      },
      {
        reading: '冷静な',
        kana: 'れいせいな',
        meaning: ['Calm', 'Cool-headed'],
        sentence: '冷静な判断が必要です。',
        type: 'YDC_main',
      },
      {
        reading: '安静',
        kana: 'あんせい',
        meaning: ['To lie wuietly in the bed', 'Rest'],
        sentence: '病気の時は安静にしていることが大切です。',
        type: 'secondary',
      },
      {
        reading: '静養する',
        kana: 'せいようする',
        meaning: ['To rest'],
        sentence: '病気の後は静養が必要です。',
        type: 'secondary',
      },
      {
        reading: '静脈',
        kana: 'じょうみゃく',
        meaning: ['Vein'],
        sentence: '静脈から血液を採取しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '公',
    onyomi: ['こう'],
    kunyomi: ['おおやけ'],
    meaning: ['Public', 'Official'],
    examples: [
      {
        reading: '公園',
        kana: 'こうえん',
        meaning: ['Park'],
        sentence: '公園でピクニックをしました。',
        type: 'YDC_main',
      },
      {
        reading: '公平',
        kana: 'こうへい',
        meaning: ['Fair', 'Impartial'],
        sentence: '公平な判断が求められます。',
        type: 'YDC_main',
      },
      {
        reading: '公務員',
        kana: 'こうむいん',
        meaning: ['Public servant', 'Civil servant'],
        sentence: '彼は公務員として働いています。',
        type: 'secondary',
      },
      {
        reading: '公衆',
        kana: 'こうしゅう',
        meaning: ['Public', 'General public'],
        sentence: '公衆の場ではマナーを守りましょう。',
        type: 'secondary',
      },
      {
        reading: '公立',
        kana: 'こうりつ',
        meaning: ['Public (institution)'],
        sentence: '公立学校に通っています。',
        type: 'secondary',
      },
      {
        reading: '公の',
        kana: 'おおやけの',
        meaning: ['Public', 'Official'],
        sentence: '公の場では礼儀正しく振る舞います。',
        type: 'secondary',
      },
      {
        reading: '公開',
        kana: 'こうかい',
        meaning: ['Public release', 'Open to the public'],
        sentence: '映画の公開日が決まりました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '園',
    onyomi: ['えん'],
    kunyomi: ['その'],
    meaning: ['Garden', 'Park'],
    examples: [
      {
        reading: '公園',
        kana: 'こうえん',
        meaning: ['Park'],
        sentence: '公園で子供たちが遊んでいます。',
        type: 'YDC_main',
      },
      {
        reading: '動物園',
        kana: 'どうぶつえん',
        meaning: ['Zoo'],
        sentence: '動物園でいろいろな動物を見ました。',
        type: 'YDC_main',
      },
      {
        reading: '遊園地',
        kana: 'ゆうえんち',
        meaning: ['Amusement park'],
        sentence: '遊園地でジェットコースターに乗りました。',
        type: 'YDC_main',
      },
      {
        reading: '幼稚園',
        kana: 'ようちえん',
        meaning: ['Kindergarten'],
        sentence: '子供は幼稚園に通っています。',
        type: 'main',
      },
      {
        reading: '園芸',
        kana: 'えんげい',
        meaning: ['Gardening'],
        sentence: '園芸が趣味で、花を育てています。',
        type: 'secondary',
      },
      {
        reading: '庭園',
        kana: 'ていえん',
        meaning: ['Garden'],
        sentence: '庭園で静かな時間を過ごしました。',
        type: 'secondary',
      },
      {
        reading: 'エデンの園',
        kana: 'エデンのその',
        meaning: ['Garden of Eden'],
        sentence: 'エデンの園は聖書に登場する楽園です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '込',
    onyomi: ['こ', 'ご'],
    kunyomi: [],
    meaning: ['Crowded', 'To include'],
    examples: [
      {
        reading: '込む',
        kana: 'こむ',
        meaning: ['To be crowded', 'To include'],
        sentence: '電車が朝はとても込んでいます。',
        type: 'YDC_main',
      },
      {
        reading: '人込み',
        kana: 'ひとごみ',
        meaning: ['Crowd', 'Throng'],
        sentence: '人込みの中で迷子になりました。',
        type: 'YDC_main',
      },
      {
        reading: '申し込む',
        kana: 'もうしこむ',
        meaning: ['To apply', 'To subscribe'],
        sentence: 'イベントに参加を申し込みました。',
        type: 'main',
      },
      {
        reading: '飛び込む',
        kana: 'とびこむ',
        meaning: ['To jump in', 'To dive'],
        sentence: 'プールに飛び込みました。',
        type: 'secondary',
      },
      {
        reading: '税込み',
        kana: 'ぜいこみ',
        meaning: ['Including tax'],
        sentence: 'この価格は税込みです。',
        type: 'secondary',
      },
      {
        reading: '割り込む',
        kana: 'わりこむ',
        meaning: ['To cut in line', 'To interrupt'],
        sentence: '列に割り込むのはマナー違反です。',
        type: 'main',
      },
      {
        reading: '思い込む',
        kana: 'おもいこむ',
        meaning: ['To be under the impression', 'To assume'],
        sentence: '彼は自分が正しいと思い込んでいます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '連',
    onyomi: ['れん'],
    kunyomi: ['つら', 'つ'],
    meaning: ['To link', 'To connect'],
    examples: [
      {
        reading: '連れて行く',
        kana: 'つれていく',
        meaning: ['To take someone along'],
        sentence: '友達を映画に連れて行きました。',
        type: 'YDC_main',
      },
      {
        reading: '連続',
        kana: 'れんぞく',
        meaning: ['Consecutive', 'In a row', 'continuity'],
        sentence: '連続ドラマを毎週見ています。',
        type: 'secondary',
      },
      {
        reading: '連絡',
        kana: 'れんらく',
        meaning: ['Contact', 'Communication'],
        sentence: '友達と連絡を取り合っています。',
        type: 'main',
      },
      {
        reading: '関連',
        kana: 'かんれん',
        meaning: ['Relation', 'Connection'],
        sentence: 'この問題は他の事柄と関連しています。',
        type: 'secondary',
      },
      {
        reading: '連休',
        kana: 'れんきゅう',
        meaning: ['Consecutive holidays'],
        sentence: '連休に旅行に行く予定です。',
        type: 'main',
      },
      {
        reading: '連なる',
        kana: 'つらなる',
        meaning: ['To extend', 'To be lined up'],
        sentence: '山々が連なっています。',
        type: 'secondary',
      },
      {
        reading: '国際連合',
        kana: 'こくさいれんごう',
        meaning: ['United Nations'],
        sentence: '国際連合は世界平和を目指しています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '窓',
    onyomi: ['そう'],
    kunyomi: ['まど'],
    meaning: ['Window'],
    examples: [
      {
        reading: '窓',
        kana: 'まど',
        meaning: ['Window'],
        sentence: '窓を開けて新鮮な空気を入れました。',
        type: 'YDC_main',
      },
      {
        reading: '窓口',
        kana: 'まどぐち',
        meaning: ['Window (service counter)'],
        sentence: 'チケットの購入は窓口で行います。',
        type: 'YDC_main',
      },
      {
        reading: '同窓会',
        kana: 'どうそうかい',
        meaning: ['Class reunion'],
        sentence: '高校の同窓会に参加しました。',
        type: 'YDC_main',
      },
      {
        reading: '窓側の席',
        kana: 'まどがわのせき',
        meaning: ['Window seat'],
        sentence: '飛行機の窓側の席を予約しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '側',
    onyomi: ['そく'],
    kunyomi: ['がわ'],
    meaning: ['Side'],
    examples: [
      {
        reading: '右側',
        kana: 'みぎがわ',
        meaning: ['Right side'],
        sentence: '右側の席に座りました。',
        type: 'YDC_main',
      },
      {
        reading: '両側',
        kana: 'りょうがわ',
        meaning: ['Both sides'],
        sentence: '道の両側に花が咲いています。',
        type: 'main',
      },
      {
        reading: '向こう側',
        kana: 'むこうがわ',
        meaning: ['Opposite side'],
        sentence: '向こう側に公園があります。',
        type: 'main',
      },
      {
        reading: '側面',
        kana: 'そくめん',
        meaning: ['Side', 'Profile'],
        sentence: 'この建物の側面はとても美しいです。',
        type: 'secondary',
      },
      {
        reading: '反対側',
        kana: 'はんたいがわ',
        meaning: ['Opposite side'],
        sentence: '反対側の道を渡りました。',
        type: 'main',
      },
      {
        reading: '外側',
        kana: 'そとがわ',
        meaning: ['Outside', 'Outer side'],
        sentence: '外側の壁を塗り替えました。',
        type: 'main',
      },
      {
        reading: '内側',
        kana: 'うちがわ',
        meaning: ['Inside', 'Inner side'],
        sentence: '内側のドアを開けてください。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '葉',
    onyomi: ['よう'],
    kunyomi: ['は', 'ば'],
    meaning: ['Leaf'],
    examples: [
      {
        reading: '葉',
        kana: 'は',
        meaning: ['Leaf'],
        sentence: '木の葉が秋に色づきます。',
        type: 'YDC_main',
      },
      {
        reading: '言葉',
        kana: 'ことば',
        meaning: ['Word', 'Language'],
        sentence: '新しい言葉を覚えるのは楽しいです。',
        type: 'YDC_main',
      },
      {
        reading: '葉書',
        kana: 'はがき',
        meaning: ['Postcard'],
        sentence: '友達に葉書を送りました。',
        type: 'YDC_main',
      },
      {
        reading: '紅葉',
        kana: 'こうよう・*もみじ',
        meaning: ['Autumn leaves', 'Fall foliage', '*Maple leaves'],
        sentence: '紅葉を見に山に行きました。',
        type: 'main',
      },
      {
        reading: '落ち葉',
        kana: 'おちば',
        meaning: ['Fallen leaves'],
        sentence: '公園の落ち葉を掃除しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '景',
    onyomi: ['けい'],
    kunyomi: [],
    meaning: ['Scenery', 'View'],
    examples: [
      {
        reading: '景色',
        kana: 'けしき',
        meaning: ['Scenery', 'Landscape'],
        sentence: '山の景色はとても美しいです。',
        type: 'YDC_main',
      },
      {
        reading: '景気',
        kana: 'けいき',
        meaning: ['Business conditions', 'Economic conditions'],
        sentence: '景気が回復してきました。',
        type: 'YDC_main',
      },
      {
        reading: '不景気',
        kana: 'ふけいき',
        meaning: ['Recession', 'Economic downturn'],
        sentence: '不景気の影響で失業者が増えています。',
        type: 'YDC_main',
      },
      {
        reading: '風景',
        kana: 'ふうけい',
        meaning: ['Scenery', 'Landscape'],
        sentence: 'この風景は絵画のようです。',
        type: 'secondary',
      },
      {
        reading: '夜景',
        kana: 'やけい',
        meaning: ['Night view'],
        sentence: '夜景を見ながらディナーを楽しみました。',
        type: 'main',
      },
      {
        reading: '背景',
        kana: 'はいけい',
        meaning: ['Background'],
        sentence: '写真の背景がとても美しいです。',
        type: 'secondary',
      },
      {
        reading: '光景',
        kana: 'こうけい',
        meaning: ['Scene', 'Sight'],
        sentence: 'その光景は忘れられない思い出です。',
        type: 'secondary',
      },
      {
        reading: '景品',
        kana: 'けいひん',
        meaning: ['Prize', 'Gift'],
        sentence: 'ゲームの景品としてお菓子をもらいました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '記',
    onyomi: ['き'],
    kunyomi: ['しる'],
    meaning: ['Record', 'Write down'],
    examples: [
      {
        reading: '日記',
        kana: 'にっき',
        meaning: ['Diary'],
        sentence: '毎晩、日記を書いています。',
        type: 'YDC_main',
      },
      {
        reading: '暗記する',
        kana: 'あんきする',
        meaning: ['To learn by heart'],
        sentence: '漢字を暗記するのは大変です。',
        type: 'YDC_main',
      },
      {
        reading: '記事',
        kana: 'きじ',
        meaning: ['Newspaper article', 'News'],
        sentence: '新聞の記事を読みました。',
        type: 'YDC_main',
      },
      {
        reading: '記者',
        kana: 'きしゃ',
        meaning: ['Reporter', 'Journalist'],
        sentence: '記者として働いています。',
        type: 'YDC_main',
      },
      {
        reading: '記入する',
        kana: 'きにゅうする',
        meaning: ['To fill in', 'To write down'],
        sentence: 'フォームに必要事項を記入してください。',
        type: 'YDC_main',
      },
      {
        reading: '記念',
        kana: 'きねん',
        meaning: ['Remembrance', 'Memory'],
        sentence: '結婚記念日に特別なディナーをしました。',
        type: 'secondary',
      },
      {
        reading: '記録',
        kana: 'きろく',
        meaning: ['Record', 'Documentation'],
        sentence: '新しい記録を更新しました。',
        type: 'secondary',
      },
      {
        reading: '記す',
        kana: 'しるす',
        meaning: ['To write down', 'To take note'],
        sentence: '重要なことをメモに記しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '形',
    onyomi: ['ぎょう', 'けい'],
    kunyomi: ['かたち', 'かた'],
    meaning: ['Shape', 'Form'],
    examples: [
      {
        reading: '形',
        kana: 'かたち',
        meaning: ['Shape', 'Form'],
        sentence: 'この花の形はとてもユニークです。',
        type: 'YDC_main',
      },
      {
        reading: '人形',
        kana: 'にんぎょう',
        meaning: ['Doll', 'Figure'],
        sentence: '子供は人形で遊ぶのが好きです。',
        type: 'YDC_main',
      },
      {
        reading: '形容詞',
        kana: 'けいようし',
        meaning: ['Adjective'],
        sentence: '形容詞は名詞を修飾します。',
        type: 'main',
      },
      {
        reading: '過去形',
        kana: 'かこけい',
        meaning: ['Past tense'],
        sentence: '英語の過去形を勉強しています。',
        type: 'main',
      },
      {
        reading: '現在形',
        kana: 'げんざいけい',
        meaning: ['Present tense'],
        sentence: '日本語の現在形は動詞の基本形です。',
        type: 'main',
      },
      {
        reading: '図形',
        kana: 'ずけい',
        meaning: ['Geometric figure', 'Shape'],
        sentence: '数学の授業で図形を学びました。',
        type: 'secondary',
      },
      {
        reading: '正方形',
        kana: 'せいほうけい',
        meaning: ['Square'],
        sentence: '正方形の面積を計算しました。',
        type: 'secondary',
      },
      {
        reading: '形見',
        kana: 'かたみ',
        meaning: ['Memento', 'Keepsake'],
        sentence: '祖母の形見として大切にしています。',
        type: 'secondary',
      },
    ],
  },
]