export const KANJI_YDC_LESSON_9: Array<KanjiYDC> = [
  {
    kanji: '春',
    onyomi: ['しゅん'],
    kunyomi: ['はる'],
    meaning: ['Spring'],
    examples: [
      {
        reading: '春',
        kana: 'はる',
        meaning: ['Spring'],
        sentence: '春が好きです。',
        type: 'main',
      },
      {
        reading: '春休み',
        kana: 'はるやすみ',
        meaning: ['Spring break'],
        sentence: '春休みに旅行に行きます。',
        type: 'main',
      },
      {
        reading: '春学期',
        kana: 'しゅんがっき',
        meaning: ['Spring semester'],
        sentence: '春学期に入学します。',
        type: 'secondary',
      },
      {
        reading: '春巻',
        kana: 'はるまき',
        meaning: ['Spring roll'],
        sentence: '春巻が好きです。',
        type: 'secondary',
      },
      {
        reading: '春分',
        kana: 'しゅんぶん',
        meaning: ['Vernal equinox'],
        sentence: '春分の日にお花見に行きます。',
        type: 'secondary',
      },
      {
        reading: '青春',
        kana: 'せいしゅん',
        meaning: ['Youth'],
        sentence: '青春時代を楽しみます。',
        type: 'secondary',
      },
      {
        reading: '春夏秋冬',
        kana: 'しゅんかしゅうとう',
        meaning: ['The four seasons'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '夏',
    onyomi: ['か'],
    kunyomi: ['なつ'],
    meaning: ['Summer'],
    examples: [
      {
        reading: '夏',
        kana: 'なつ',
        meaning: ['Summer'],
        sentence: '夏が好きです。',
        type: 'main',
      },
      {
        reading: '夏休み',
        kana: 'なつやすみ',
        meaning: ['Summer vacation'],
        sentence: '夏休みに旅行に行きます。',
        type: 'main',
      },
      {
        reading: '夏服',
        kana: 'なつふく',
        meaning: ['Summer clothes'],
        sentence: '夏服を買いに行きます。',
        type: 'secondary',
      },
      {
        reading: '真夏',
        kana: 'まなつ',
        meaning: ['Midsummer'],
        sentence: '真夏に海に行きます。',
        type: 'secondary',
      },
      {
        reading: '初夏',
        kana: 'しょか',
        meaning: ['Early summer'],
        sentence: '初夏に花火大会に行きます。',
        type: 'secondary',
      },
      {
        reading: '夏至',
        kana: 'げし',
        meaning: ['Summer solstice'],
        sentence: '夏至の日にお祭りに行きます。',
        type: 'secondary',
      },
      {
        reading: '春夏秋冬',
        kana: 'しゅんかしゅうとう',
        meaning: ['The four seasons'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '秋',
    onyomi: ['しゅう'],
    kunyomi: ['あき'],
    meaning: ['Autumn'],
    examples: [
      {
        reading: '秋',
        kana: 'あき',
        meaning: ['Autumn'],
        sentence: '秋が好きです。',
        type: 'main',
      },
      {
        reading: '秋学期',
        kana: 'あきがっき',
        meaning: ['Autumn semester'],
        sentence: '秋学期に入学します。',
        type: 'secondary',
      },
      {
        reading: '秋風',
        kana: 'あきかぜ',
        meaning: ['Autumn breeze'],
        sentence: '秋風が気持ちいいです。',
        type: 'secondary',
      },
      {
        reading: '秋分',
        kana: 'しゅうぶん',
        meaning: ['Autumnal equinox'],
        sentence: '秋分の日にお花見に行きます。',
        type: 'secondary',
      },
      {
        reading: '晩秋',
        kana: 'ばんしゅう',
        meaning: ['Late autumn'],
        sentence: '晩秋に紅葉を見に行きます。',
        type: 'secondary',
      },
      {
        reading: '春夏秋冬',
        kana: 'しゅんかしゅうとう',
        meaning: ['The four seasons'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '冬',
    onyomi: ['とう'],
    kunyomi: ['ふゆ'],
    meaning: ['Winter'],
    examples: [
      {
        reading: '冬',
        kana: 'ふゆ',
        meaning: ['Winter'],
        sentence: '冬が好きです。',
        type: 'main',
      },
      {
        reading: '冬休み',
        kana: 'ふゆやすみ',
        meaning: ['Winter vacation'],
        sentence: '冬休みに旅行に行きます。',
        type: 'main',
      },
      {
        reading: '冬至',
        kana: 'とうじ',
        meaning: ['Winter solstice'],
        sentence: '冬至の日にお祭りに行きます。',
        type: 'secondary',
      },
      {
        reading: '冬眠',
        kana: 'とうみん',
        meaning: ['Hibernation'],
        sentence: '冬眠する動物がいます。',
        type: 'secondary',
      },
      {
        reading: '暖冬',
        kana: 'だんとう',
        meaning: ['Mild winter'],
        sentence: '暖冬です。',
        type: 'secondary',
      },
      {
        reading: '春夏秋冬',
        kana: 'しゅんかしゅうとう',
        meaning: ['The four seasons'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '朝',
    onyomi: ['ちょう'],
    kunyomi: ['あさ'],
    meaning: ['Morning'],
    examples: [
      {
        reading: '朝',
        kana: 'あさ',
        meaning: ['Morning'],
        sentence: '朝が好きです。',
        type: 'main',
      },
      {
        reading: '毎朝',
        kana: 'まいあさ',
        meaning: ['Every morning'],
        sentence: '毎朝日本語を勉強します。',
        type: 'main',
      },
      {
        reading: '今朝',
        kana: 'けさ',
        meaning: ['This morning'],
        sentence: '今朝は早く起きました。',
        type: 'main',
      },
      {
        reading: '朝ご飯',
        kana: 'あさごはん',
        meaning: ['Breakfast'],
        sentence: '今朝朝ご飯を食べた。',
        type: 'secondary',
      },
      {
        reading: '朝食',
        kana: 'ちょうしょく',
        meaning: ['Breakfast'],
        sentence: '朝食を食べます。',
        type: 'secondary',
      },
      {
        reading: '朝寝坊する',
        kana: 'あさねぼうする',
        meaning: ['To sleep in'],
        sentence: '朝寝坊して遅刻しました。',
        type: 'secondary',
      },
      {
        reading: '朝刊',
        kana: 'ちょうかん',
        meaning: ['Morning paper', 'Morning edition'],
        sentence: '朝刊を読みます。',
        type: 'secondary',
      },
      {
        reading: '北朝鮮',
        kana: 'きたちょうせん',
        meaning: ['North Korea'],
        sentence: '北朝鮮に行きたくない。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '昼',
    onyomi: ['ちゅう'],
    kunyomi: ['ひる'],
    meaning: ['Daytime', 'Noon'],
    examples: [
      {
        reading: '昼',
        kana: 'ひる',
        meaning: ['Daytime', 'Noon'],
        sentence: '昼が好きです。',
        type: 'main',
      },
      {
        reading: '昼間',
        kana: 'ひるま',
        meaning: ['Daytime'],
        sentence: '昼間に日本語を勉強します。',
        type: 'main',
      },
      {
        reading: '昼休み',
        kana: 'ひるやすみ',
        meaning: ['Lunch break'],
        sentence: '昼休みに日本語を勉強します。',
        type: 'main',
      },
      {
        reading: '昼ご飯',
        kana: 'ひるごはん',
        meaning: ['Lunch'],
        sentence: '昼ご飯を食べます。',
        type: 'secondary',
      },
      {
        reading: '昼食',
        kana: 'ちゅうしょく',
        meaning: ['Lunch'],
        sentence: '昼食を食べます。',
        type: 'secondary',
      },
      {
        reading: '昼寝',
        kana: 'ひるね',
        meaning: ['Nap'],
        sentence: '昼寝をします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '夕',
    onyomi: ['せき'],
    kunyomi: ['ゆう'],
    meaning: ['Evening'],
    examples: [
      {
        reading: '夕方',
        kana: 'ゆうがた',
        meaning: ['Evening'],
        sentence: '夕方に日本語を勉強します。',
        type: 'main',
      },
      {
        reading: '夕日',
        kana: 'ゆうひ',
        meaning: ['Sunset'],
        sentence: '夕日が綺麗です。',
        type: 'secondary',
      },
      {
        reading: '夕食',
        kana: 'ゆうしょく',
        meaning: ['Dinner', 'Evening meal'],
        sentence: '夕食を食べます。',
        type: 'secondary',
      },
      {
        reading: '七夕',
        kana: 'たなばた',
        meaning: ['The Star Festival'],
        sentence: '七夕に願い事をします。',
        type: 'secondary',
      },
      {
        reading: '夕刊',
        kana: 'ゆうかん',
        meaning: ['Evening paper', 'Evening edition'],
        sentence: '夕刊を読みます。',
        type: 'secondary',
      },
      {
        reading: '夕立',
        kana: 'ゆうだち',
        meaning: ['Evening shower'],
        sentence: '夕立が降りました。',
        type: 'secondary',
      },
      {
        reading: '一朝一夕',
        kana: 'いっちょういっせき',
        meaning: ['In a very short time'],
        sentence: '一朝一夕で覚えられません。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '方',
    onyomi: ['ほう'],
    kunyomi: ['かた', 'がた'],
    meaning: ['Direction', 'Way', 'Person'],
    examples: [
      {
        reading: '読み方',
        kana: 'よみかた',
        meaning: ['How to read', 'Way of reading'],
        sentence: '読み方を教えてください。',
        type: 'main',
      },
      {
        reading: '夕方',
        kana: 'ゆうがた',
        meaning: ['Early evening'],
        sentence: '夕方に日本語を勉強します。',
        type: 'main',
      },
      {
        reading: 'あの方',
        kana: 'あのかた',
        meaning: ['That person'],
        sentence: 'あの方は誰ですか。',
        type: 'secondary',
      },
      {
        reading: '両方',
        kana: 'りょうほう',
        meaning: ['Both (sides)'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '方法',
        kana: 'ほうほう',
        meaning: ['Method', 'Way'],
        sentence: '方法を教えてください。',
        type: 'secondary',
      },
      {
        reading: '方向',
        kana: 'ほうこう',
        meaning: ['Direction'],
        sentence: '200メートルに左方向',
        type: 'secondary',
      },
      {
        reading: '方言',
        kana: 'ほうげん',
        meaning: ['Dialect'],
        sentence: '方言が分かりません。',
        type: 'secondary',
      },
      {
        reading: '長方形',
        kana: 'ちょうほうけい',
        meaning: ['Rectangle'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '晩',
    onyomi: ['ばん'],
    kunyomi: [],
    meaning: ['Night', 'Evening'],
    examples: [
      {
        reading: '晩',
        kana: 'ばん',
        meaning: ['Night', 'Evening'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '今晩',
        kana: 'こんばん',
        meaning: ['Tonight'],
        sentence: '今晩は何をしますか。',
        type: 'main',
      },
      {
        reading: '毎晩',
        kana: 'まいばん',
        meaning: ['Every night'],
        sentence: '毎晩日本語を勉強します。',
        type: 'main',
      },
      {
        reading: '晩ご飯',
        kana: 'ばんごはん',
        meaning: ['Dinner'],
        sentence: '晩ご飯を食べます。',
        type: 'secondary',
      },
      {
        reading: '晩婚',
        kana: 'ばんこん',
        meaning: ['Late marriage'],
        sentence: '晩婚です。',
        type: 'secondary',
      },
      {
        reading: '晩年',
        kana: 'ばんねん',
        meaning: ['Late years', 'Last years', 'One\'s later years'],
        sentence: '',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '夜',
    onyomi: ['や'],
    kunyomi: ['よる', 'よ'],
    meaning: ['Night'],
    examples: [ 
      {
        reading: '夜',
        kana: 'よる',
        meaning: ['Night'],
        sentence: '',
        type: 'main',
      },
      {
        reading: '今夜',
        kana: 'こんや',
        meaning: ['Tonight'],
        sentence: '今夜は何をしますか。',
        type: 'main',
      },
      {
        reading: '夜中',
        kana: 'よなか',
        meaning: ['Midnight', 'Middle of the night'],
        sentence: '夜中に何をしていますか。',
        type: 'secondary',
      },
      {
        reading: '夜明け',
        kana: 'よあけ',
        meaning: ['Dawn', 'Daybreak'],
        sentence: '夜明けに起きます。',
        type: 'secondary',
      },
      {
        reading: '深夜',
        kana: 'しんや',
        meaning: ['Late at night'],
        sentence: '深夜に何をしてるの？',
        type: 'secondary',
      },
      {
        reading: '夜食',
        kana: 'やしょく',
        meaning: ['Night snack'],
        sentence: '夜食を食べます。',
        type: 'secondary',
      },
      {
        reading: '徹夜する',
        kana: 'てつやする',
        meaning: ['To stay up all night'],
        sentence: '徹夜して勉強しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '心',
    onyomi: ['しん'],
    kunyomi: ['こころ'],
    meaning: ['Heart', 'Mind'],
    examples: [
      {
        reading: '心',
        kana: 'こころ',
        meaning: ['Heart', 'Mind'],
        sentence: '心が痛いです。',
        type: 'main',
      },
      {
        reading: '安心する',
        kana: 'あんしんする',
        meaning: ['To feel relieved'],
        sentence: '安心しました。',
        type: 'main',
      },
      {
        reading: '心配する',
        kana: 'しんぱいする',
        meaning: ['To worry'],
        sentence: '心配しないといけないよ。',
        type: 'main',
      },
      {
        reading: '中心',
        kana: 'ちゅうしん',
        meaning: ['Center'],
        sentence: '中心に立ってください。',
        type: 'main',
      },
      {
        reading: '熱心な',
        kana: 'ねっしんな',
        meaning: ['Enthusiastic'],
        sentence: '熱心な学生がいます。',
        type: 'secondary',
      },
      {
        reading: '感心する',
        kana: 'かんしんする',
        meaning: ['To be impressed'],
        sentence: '感心しました。',
        type: 'secondary',
      },
      {
        reading: '心理学',
        kana: 'しんりがく',
        meaning: ['Psychology'],
        sentence: '心理学を勉強します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '手',
    onyomi: ['しゅ'],
    kunyomi: ['て', 'た'],
    meaning: ['Hand'],
    examples: [
      {
        reading: '手',
        kana: 'て',
        meaning: ['Hand'],
        sentence: '手を洗ってください。',
        type: 'main',
      },
      {
        reading: '下手な',
        kana: 'へたな',
        meaning: ['Poor at', 'Bad at'],
        sentence: '下手な絵を描きます。',
        type: 'main',
      },
      {
        reading: '上手な',
        kana: 'じょうずな',
        meaning: ['Good at'],
        sentence: '上手な絵を描きます。',
        type: 'main',
      },
      {
        reading: '手紙',
        kana: 'てがみ',
        meaning: ['Letter'],
        sentence: '手紙を書きます。',
        type: 'secondary',
      },
      {
        reading: 'お手洗い',
        kana: 'おてあらい',
        meaning: ['Restroom'],
        sentence: 'お手洗いに行きます。',
        type: 'secondary',
      },
      {
        reading: '切手',
        kana: 'きって',
        meaning: ['Postage Stamp'],
        sentence: '切手を貼ります。',
        type: 'secondary',
      },
      {
        reading: '手伝う',
        kana: 'てつだう',
        meaning: ['To help'],
        sentence: '手伝ってください。',
        type: 'secondary',
      },
      {
        reading: '歌手',
        kana: 'かしゅ',
        meaning: ['Singer'],
        sentence: '好きな歌手は何ですか。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '足',
    onyomi: ['そく', 'ぞく'],
    kunyomi: ['あし', 'た'],
    meaning: ['Foot', 'Leg'],
    examples: [
      {
        reading: '足',
        kana: 'あし',
        meaning: ['Foot', 'Leg'],
        sentence: '足が痛いです。',
        type: 'main',
      },
      {
        reading: '足りる',
        kana: 'たりる',
        meaning: ['To be enough', 'To be sufficient'],
        sentence: 'お金が足りません。',
        type: 'main',
      },
      {
        reading: '足す',
        kana: 'たす',
        meaning: ['To add'],
        sentence: '足してください。',
        type: 'main',
      },
      {
        reading: '一足',
        kana: 'いっそく',
        meaning: ['One pair of shoes'],
        sentence: '一足買いました。',
        type: 'secondary',
      },
      {
        reading: '水不足',
        kana: 'みずぶそく',
        meaning: ['Water shortage'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '遠足',
        kana: 'えんそく',
        meaning: ['One-day trip', 'Excursion'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '満足',
        kana: 'まんぞく',
        meaning: ['Satisfaction'],
        sentence: '満足しています。',
        type: 'secondary',
      },
      {
        reading: '足音',
        kana: 'あしおと',
        meaning: ['Footsteps'],
        sentence: '足音が聞こえるの？',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '体',
    onyomi: ['たい', 'てい'],
    kunyomi: ['からだ'],
    meaning: ['Body'],
    examples: [
      {
        reading: '体',
        kana: 'からだ',
        meaning: ['Body'],
        sentence: '体が痛いです。',
        type: 'main',
      },
      {
        reading: '体重',
        kana: 'たいじゅう',
        meaning: ['Body Weight'],
        sentence: '体重が増えました。',
        type: 'secondary',
      },
      {
        reading: '体操',
        kana: 'たいそう',
        meaning: ['Gymnastics'],
        sentence: '体操をします。',
        type: 'secondary',
      },
      {
        reading: '体温',
        kana: 'たいおん',
        meaning: ['Body temperature'],
        sentence: '体温が高いです。',
        type: 'secondary',
      },
      {
        reading: '全体',
        kana: 'ぜんたい',
        meaning: ['Whole', 'Entirety'],
        sentence: '全体を見てください。',
        type: 'main',
      },
      {
        reading: '団体',
        kana: 'だんたい',
        meaning: ['Group'],
        sentence: '団体で行動します。',
        type: 'secondary',
      },
      {
        reading: '世間体',
        kana: 'せけんてい',
        meaning: ['Reputation' ,'Appearance', 'Public image'],
        sentence: '世間体を気にします。',
        type: 'secondary',
      },
      {
        reading: '体調',
        kana: 'たいちょう',
        meaning: ['Physical condition'],
        sentence: '体調が悪いです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '首',
    onyomi: ['しゅ'],
    kunyomi: ['くび'],
    meaning: ['Neck', 'Head'],
    examples: [
      {
        reading: '首',
        kana: 'くび',
        meaning: ['Neck'],
        sentence: '首が痛いです。',
        type: 'main',
      },
      {
        reading: '首になる',
        kana: 'くびになる',
        meaning: ['To be fired'],
        sentence: '首になりました。',
        type: 'secondary',
      },
      {
        reading: '手首',
        kana: 'てくび',
        meaning: ['Wrist'],
        sentence: '手首が痛いです。',
        type: 'secondary',
      },
      {
        reading: '首相',
        kana: 'しゅしょう',
        meaning: ['Prime Minister'],
        sentence: '首相が変わりました。',
        type: 'secondary',
      },
      {
        reading: '首都',
        kana: 'しゅと',
        meaning: ['Capital city'],
        sentence: '首都に行きます。',
        type: 'secondary',
      },
      {
        reading: '首位',
        kana: 'しゅい',
        meaning: ['First place', 'Top position'],
        sentence: '首位になりました。',
        type: 'secondary',
      },
      {
        reading: '部首',
        kana: 'ぶしゅ',
        meaning: ['Radical (of a kanji character)'],
        sentence: '部首を覚えます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '道',
    onyomi: ['どう', 'とう'],
    kunyomi: ['みち'],
    meaning: ['Road', 'Way'],
    examples: [
      {
        reading: '道',
        kana: 'みち',
        meaning: ['Road', 'Way'],
        sentence: '道を渡ってください。',
        type: 'main',
      },
      {
        reading: '片道',
        kana: 'かたみち',
        meaning: ['One-way'],
        sentence: '片道切符を買いました。',
        type: 'secondary',
      },
      {
        reading: '書道',
        kana: 'しょどう',
        meaning: ['Calligraphy'],
        sentence: '書道を習います。',
        type: 'secondary',
      },
      {
        reading: '柔道',
        kana: 'じゅうどう',
        meaning: ['Judo'],
        sentence: '柔道を習います。',
        type: 'secondary',
      },
      {
        reading: '北海道',
        kana: 'ほっかいどう',
        meaning: ['Hokkaido'],
        sentence: '北海道に行きたい。',
        type: 'secondary',
      },
      { 
        reading: '道具',
        kana: 'どうぐ',
        meaning: ['Tool'],
        sentence: '道具を使います。',
        type: 'secondary',
      },
      {
        reading: '歩道',
        kana: 'ほどう',
        meaning: ['Sidewalk'],
        sentence: '歩道を歩きます。',
        type: 'secondary',
      },
      {
        reading: '近道',
        kana: 'ちかみち',
        meaning: ['Shortcut'],
        sentence: '近道を教えてください。',
        type: 'secondary',
      },
    ],
  },
]