export const KANJI_YDC_LESSON_25: Array<KanjiYDC> = [
  {
    kanji: '平',
    onyomi: ['へい', 'びょう'],
    kunyomi: ['たい', 'ひら'],
    meaning: ['Flat', 'Calm', 'Peace'],
    examples: [
      {
        reading: '平日',
        kana: 'へいじつ',
        meaning: ['Weekday'],
        sentence: '平日は仕事があります。',
        type: 'YDC_main',
      },
      {
        reading: '平らな',
        kana: 'たいらな',
        meaning: ['Flat', 'Level'],
        sentence: 'このテーブルは平らです。',
        type: 'YDC_main',
      },
      {
        reading: '平和',
        kana: 'へいわ',
        meaning: ['Peace', 'Harmony'],
        sentence: '世界の平和を願っています。',
        type: 'YDC_main',
      },
      {
        reading: '平成',
        kana: 'へいせい',
        meaning: ['Heisei era'],
        sentence: '平成は1989年から2019年までの期間です。',
        type: 'secondary',
      },
      {
        reading: '平均',
        kana: 'へいきん',
        meaning: ['Average'],
        sentence: 'クラスの平均点は80点でした。',
        type: 'secondary',
      },
      {
        reading: '公平',
        kana: 'こうへい',
        meaning: ['Impartiality'],
        sentence: '公平な判断が求められます。',
        type: 'main',
      },
      {
        reading: '平等',
        kana: 'びょうどう',
        meaning: ['Equality'],
        sentence: 'すべての人は平等な権利を持っています。',
        type: 'secondary',
      },
      {
        reading: '平たい',
        kana: 'ひらたい',
        meaning: ['Flat', 'Level'],
        sentence: 'この石は平たい形をしています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '和',
    onyomi: ['わ', 'お'],
    kunyomi: ['やわ', 'なご'],
    meaning: ['Harmony', 'Japanese'],
    examples: [
      {
        reading: '平和',
        kana: 'へいわ',
        meaning: ['Peace'],
        sentence: '世界の平和を願っています。',
        type: 'YDC_main',
      },
      {
        reading: '和食',
        kana: 'わしょく',
        meaning: ['Japanese food'],
        sentence: '和食は健康に良いとされています。',
        type: 'YDC_main',
      },
      {
        reading: '和',
        kana: 'わ',
        meaning: ['Harmony'],
        sentence: '和を大切にする文化があります。',
        type: 'secondary',
      },
      {
        reading: '英和辞典',
        kana: 'えいわじてん',
        meaning: ['English-Japanese dictionary'],
        sentence: '英和辞典を使って単語を調べます。',
        type: 'secondary',
      },
      {
        reading: '和やか',
        kana: 'なごやか',
        meaning: ['Gentle', 'Friendly'],
        sentence: '和やかな雰囲気の中で会話を楽しみました。',
        type: 'secondary',
      },
      {
        reading: '昭和',
        kana: 'しょうわ',
        meaning: ['Showa era'],
        sentence: '昭和は1926年から1989年までの期間です。',
        type: 'secondary',
      },
      {
        reading: '和らぐ',
        kana: 'やわらぐ',
        meaning: ['To soften', 'To calm down'],
        sentence: '緊張が和らいで、リラックスできました。',
        type: 'secondary',
      },
      {
        reading: '共和国',
        kana: 'きょうわこく',
        meaning: ['Republic'],
        sentence: '日本は立憲君主制の国ですが、共和国ではありません。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '戦',
    onyomi: ['せん'],
    kunyomi: ['たたか', 'いくさ'],
    meaning: ['War', 'Battle'],
    examples: [
      {
        reading: '戦う',
        kana: 'たたかう',
        meaning: ['To fight', 'To battle'],
        sentence: '彼は正義のために戦います。',
        type: 'YDC_main',
      },
      {
        reading: '戦争',
        kana: 'せんそう',
        meaning: ['War'],
        sentence: '戦争は多くの人々に悲しみをもたらします。',
        type: 'YDC_main',
      },
      {
        reading: '戦い',
        kana: 'たたかい',
        meaning: ['Battle', 'Fight'],
        sentence: '歴史上の有名な戦いについて学びました。',
        type: 'main',
      },
      {
        reading: '作戦',
        kana: 'さくせん',
        meaning: ['Strategy', 'Operation'],
        sentence: '軍の作戦が成功しました。',
        type: 'secondary',
      },
      {
        reading: '冷戦',
        kana: 'れいせん',
        meaning: ['Cold War'],
        sentence: '冷戦は20世紀の重要な歴史的事件です。',
        type: 'secondary',
      },
      {
        reading: '反戦',
        kana: 'はんせん',
        meaning: ['Anti-war'],
        sentence: '反戦運動が世界中で広がっています。',
        type: 'main',
      },
      {
        reading: '挑戦',
        kana: 'ちょうせん',
        meaning: ['Challenge'],
        sentence: '新しいことに挑戦するのが好きです。',
        type: 'secondary',
      },
      {
        reading: '戦',
        kana: 'いくさ',
        meaning: ['War', 'Battle (archaic)'],
        sentence: '古代の戦は多くの人々の命を奪いました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '争',
    onyomi: ['そう'],
    kunyomi: ['あらそ'],
    meaning: ['Conflict'],
    examples: [
      {
        reading: '戦争',
        kana: 'せんそう',
        meaning: ['War'],
        sentence: '戦争は多くの人々に悲しみをもたらします。',
        type: 'YDC_main',
      },
      {
        reading: '争う',
        kana: 'あらそう',
        meaning: ['To fight', 'To quarrel'],
        sentence: '彼らは小さなことで争っています。',
        type: 'YDC_main',
      },
      {
        reading: '競争する',
        kana: 'きょうそうする',
        meaning: ['To compete'],
        sentence: 'スポーツ大会で競争しました。',
        type: 'secondary',
      },
      {
        reading: '争い',
        kana: 'あらそい',
        meaning: ['Conflict', 'Dispute'],
        sentence: '争いごとは避けたいです。',
        type: 'secondary',
      },
      {
        reading: '論争',
        kana: 'ろんそう',
        meaning: ['Argument', 'Debate'],
        sentence: 'その問題について論争が起きました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '政',
    onyomi: ['せい', 'しょう'],
    kunyomi: ['まつりごと'],
    meaning: ['Government'],
    examples: [
      {
        reading: '政治',
        kana: 'せいじ',
        meaning: ['Politics'],
        sentence: '政治に関心があります。',
        type: 'YDC_main',
      },
      {
        reading: '政治家',
        kana: 'せいじか',
        meaning: ['Politician'],
        sentence: '彼は有名な政治家です。',
        type: 'YDC_main',
      },
      {
        reading: '政党',
        kana: 'せいとう',
        meaning: ['Political party'],
        sentence: '政党の政策について話し合いました。',
        type: 'YDC_main',
      },
      {
        reading: '政府',
        kana: 'せいふ',
        meaning: ['Government'],
        sentence: '政府は新しい法律を制定しました。',
        type: 'secondary',
      },
      {
        reading: '行政',
        kana: 'ぎょうせい',
        meaning: ['Administration'],
        sentence: '行政の手続きが複雑です。',
        type: 'secondary',
      },
      {
        reading: '財政',
        kana: 'ざいせい',
        meaning: ['Finance', 'Financial affairs'],
        sentence: '国の財政が厳しい状況です。',
        type: 'secondary',
      },
      {
        reading: '政権',
        kana: 'せいけん',
        meaning: ['Political power'],
        sentence: '新しい政権が誕生しました。',
        type: 'secondary',
      },
      {
        reading: '政策',
        kana: 'せいさく',
        meaning: ['Policy'],
        sentence: '政府の政策が国民に影響を与えます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '治',
    onyomi: ['ち', 'じ'],
    kunyomi: ['おさ', 'なお'],
    meaning: ['To govern', 'To heal'],
    examples: [
      {
        reading: '治る',
        kana: 'なおる',
        meaning: ['To heal', 'To recover'],
        sentence: '風邪が治りました。',
        type: 'YDC_main',
      },
      {
        reading: '治す',
        kana: 'なおす',
        meaning: ['To cure', 'To heal'],
        sentence: '医者が病気を治してくれました。',
        type: 'YDC_main',
      },
      {
        reading: '政治',
        kana: 'せいじ',
        meaning: ['Politics'],
        sentence: '政治に関心があります。',
        type: 'YDC_main',
      },
      {
        reading: '政治家',  
        kana: 'せいじか',
        meaning: ['Politician'],
        sentence: '彼は有名な政治家です。',
        type: 'YDC_main',
      },
      {
        reading: '治める',
        kana: 'おさめる',
        meaning: ['To govern', 'To rule'],
        sentence: '彼は国を治めるために努力しています。',
        type: 'secondary',
      },
      {
        reading: '治療',
        kana: 'ちりょう',
        meaning: ['Medical treatment'],
        sentence: '病院で治療を受けました。',
        type: 'secondary',
      },
      {
        reading: '治安',
        kana: 'ちあん',
        meaning: ['Public order', 'Law and order'],
        sentence: '治安が良い地域に住んでいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '経',
    onyomi: ['けい', 'きょう'],
    kunyomi: ['へ'],
    meaning: ['To pass through'],
    examples: [
      {
        reading: '経験',  
        kana: 'けいけん',
        meaning: ['Experience'],
        sentence: '多くの経験を積むことが大切です。',
        type: 'YDC_main',
      },
      {
        reading: '経済',
        kana: 'けいざい',
        meaning: ['Economy'],
        sentence: '経済の勉強をしています。',
        type: 'YDC_main',
      },
      {
        reading: '経由',
        kana: 'けいゆ',
        meaning: ['Via', 'By way of'],
        sentence: '東京経由で大阪に行きます。',
        type: 'YDC_main',
      },
      {
        reading: '経営',
        kana: 'けいえい',
        meaning: ['Management', 'Administration'],
        sentence: '会社の経営に携わっています。',
        type: 'secondary',
      },
      {
        reading: '神経',
        kana: 'しんけい',
        meaning: ['Nerve', 'Nervous system'],
        sentence: '神経が高ぶると、体に影響があります。',
        type: 'secondary',
      },
      {
        reading: '経歴',
        kana: 'けいれき',
        meaning: ['Background', 'Personal history'],
        sentence: '彼の経歴は素晴らしいです。',
        type: 'secondary',
      },
      {
        reading: 'お経',
        kana: 'おきょう',
        meaning: ['Buddhist sutra'],
        sentence: 'お経を唱えることは心を落ち着けます。',
        type: 'secondary',
      },
      {
        reading: '経る',
        kana: 'へる',
        meaning: ['To pass through', 'To go through', 'To undergo'],
        sentence: '多くの困難を経て、成功しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '済',
    onyomi: ['さい', 'ざい'],
    kunyomi: ['す', 'ず'],
    meaning: ['To finish', 'To complete'],
    examples: [
      {
        reading: '経済',  
        kana: 'けいざい',
        meaning: ['Economy'],
        sentence: '経済の勉強をしています。',
        type: 'YDC_main',
      },
      {
        reading: '経済学',
        kana: 'けいざいがく',
        meaning: ['Economics'],
        sentence: '経済学の授業を受けています。',
        type: 'YDC_main',
      },
      {
        reading: '済む',
        kana: 'すむ',
        meaning: ['(Something) finishes', 'To be over'],
        sentence: '宿題がやっと済みました。',
        type: 'YDC_main',
      },
      {
        reading: '済ませる',
        kana: 'すませる',
        meaning: ['To finish (something)', 'To complete'],
        sentence: '仕事を早く済ませて帰ります。',
        type: 'YDC_main',
      },
      {
        reading: '使用済み',
        kana: 'しようずみ',
        meaning: ['Used', 'Consumed'],
        sentence: '使用済みの電池は正しく捨ててください。',
        type: 'secondary',
      },
      {
        reading: '返済する',
        kana: 'へんさいする',
        meaning: ['To repay', 'To reimburse'],
        sentence: '借りたお金を返済しました。',
        type: 'secondary',
      },
      {
        reading: '救済',
        kana: 'きゅうさい',
        meaning: ['Relief', 'Aid', 'salvation'],
        sentence: '災害時の救済活動に参加しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '法',
    onyomi: ['ほう', 'ぽう'],
    kunyomi: ['はっ', 'ほっ'],
    meaning: ['Law', 'Method'],
    examples: [
      {
        reading: '法律',
        kana: 'ほうりつ',
        meaning: ['Law'],
        sentence: '法律を守ることは大切です。',
        type: 'YDC_main',
      },
      {
        reading: '文法',
        kana: 'ぶんぽう',
        meaning: ['Grammar'],
        sentence: '日本語の文法を勉強しています。',
        type: 'YDC_main',
      },
      {
        reading: '方法',
        kana: 'ほうほう',
        meaning: ['Method', 'Way'],
        sentence: '新しい方法で問題を解決しました。',
        type: 'YDC_main',
      },
      {
        reading: '憲法',
        kana: 'けんぽう',
        meaning: ['Constitution'],
        sentence: '日本の憲法は1947年に施行されました。',
        type: 'secondary',
      },
      {
        reading: '違法',
        kana: 'いほう',
        meaning: ['Illegal'],
        sentence: '違法行為は厳しく罰せられます。',
        type: 'secondary',
      },
      {
        reading: '用法',
        kana: 'ようほう',
        meaning: ['Usage', 'Instructions for use'],
        sentence: '薬の用法をよく読んでください。',
        type: 'main',
      }, 
      {
        reading: '法案',
        kana: 'ほうあん',
        meaning: ['Bill', 'Draft law'],
        sentence: '新しい法案が国会で審議されています。',
        type: 'secondary',
      }, 
      {
        reading: '法則',
        kana: 'ほうそく',
        meaning: ['Law', 'Rule'],
        sentence: '自然の法則に従って物事は進みます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '律',
    onyomi: ['りつ', 'りち'],
    kunyomi: [],
    meaning: ['Regulation'],
    examples: [
      {
        reading: '法律',
        kana: 'ほうりつ',
        meaning: ['Law'],
        sentence: '法律を守ることは大切です。',
        type: 'YDC_main',
      },
      {
        reading: '規律',
        kana: 'きりつ',
        meaning: ['Discipline', 'Regulation'],
        sentence: '学校では規律を守ることが求められます。',
        type: 'main',
      },
      {
        reading: '戒律',
        kana: 'かいりつ',
        meaning: ['Commandment'],
        sentence: '仏教の戒律を守ることは重要です。',
        type: 'secondary',
      },
      {
        reading: '一律に',
        kana: 'いちりつに',
        meaning: ['Uniformly', 'Equally'],
        sentence: '一律に料金が設定されています。',
        type: 'secondary',
      },
      {
        reading: '自律神経',
        kana: 'じりつしんけい',
        meaning: ['Autonomic nervous system'],
        sentence: '自律神経は体の自動的な機能を調節します。',
        type: 'secondary',
      },
      {
        reading: '律儀な',
        kana: 'りちぎな',
        meaning: ['Conscientious'],
        sentence: '彼は律儀な性格で、約束を守ります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '際',
    onyomi: ['さい'],
    kunyomi: ['きわ', 'ぎわ'],
    meaning: ['Occasion'],
    examples: [
      {
        reading: '国際',
        kana: 'こくさい',
        meaning: ['International'],
        sentence: '国際問題について学んでいます。',
        type: 'YDC_main',
      },
      {
        reading: '国際化',
        kana: 'こくさいか',
        meaning: ['Internationalization'],
        sentence: '国際化が進む現代社会では、異文化理解が重要です。',
        type: 'YDC_main',
      },
      {
        reading: '〜際',
        kana: '〜さい',
        meaning: ['When', 'On the occasion of'],
        sentence: '旅行の際はパスポートを忘れないでください。',
        type: 'YDC_main',
      },
      {
        reading: '交際',
        kana: 'こうさい',
        meaning: ['Companionship', 'Relationship'],
        sentence: '彼女と交際を始めました。',
        type: 'secondary',
      },
      {
        reading: '実際',
        kana: 'じっさい',
        meaning: ['Actually', 'Reality'],
        sentence: '実際の状況は予想以上に厳しいです。',
        type: 'secondary',
      },
      {
        reading: '際立つ',
        kana: 'きわだつ',
        meaning: ['To stand out', 'To be prominent'],
        sentence: '彼の才能は際立っています。',
        type: 'secondary',
      },
      {
        reading: '間際',
        kana: 'まぎわ',
        meaning: ['Just before', 'On the verge of'],
        sentence: '試験の間際に勉強を始めました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '関',
    onyomi: ['かん'],
    kunyomi: ['せき', 'かか'],
    meaning: ['Connection', 'Relation'],
    examples: [
      {
        reading: '関係',
        kana: 'かんけい',
        meaning: ['Relation', 'Connection'],
        sentence: '彼との関係はとても大切です。',
        type: 'YDC_main',
      },
      {
        reading: '国際関係',
        kana: 'こくさいかんけい',
        meaning: ['International relations'],
        sentence: '国際関係の専門家として働いています。',
        type: 'YDC_main',
      },
      {
        reading: '関心',
        kana: 'かんしん',
        meaning: ['Interest', 'Concern'],
        sentence: '環境問題に関心があります。',
        type: 'YDC_main',
      },
      {
        reading: '関東',
        kana: 'かんとう',
        meaning: ['Kanto region'],
        sentence: '関東地方は東京を含む地域です。',
        type: 'YDC_main',
      },
      {
        reading: '関西',
        kana: 'かんさい',
        meaning: ['Kansai region'],
        sentence: '関西地方は大阪や京都が含まれます。',
        type: 'YDC_main',
      },
      {
        reading: '関取',
        kana: 'せきとり',
        meaning: ['Sumo wrestler'],
        sentence: '彼は有名な関取です。',
        type: 'secondary',
      },
      {
        reading: '玄関',
        kana: 'げんかん',
        meaning: ['Entrance', 'Front door'],
        sentence: '玄関で靴を脱いでください。',
        type: 'main',
      },
      {
        reading: '税関',
        kana: 'ぜいかん',
        meaning: ['Customs', 'Customs office'],
        sentence: '空港の税関で荷物をチェックされました。',
        type: 'secondary',
      },
      {
        reading: '関わる',
        kana: 'かかわる',
        meaning: ['To be involved', 'To relate to'],
        sentence: 'このプロジェクトに関わることになりました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '係',
    onyomi: ['けい'],
    kunyomi: ['かかり', 'かか'],
    meaning: ['Person in charge', 'Connection'],
    examples: [
      {
        reading: '関係',
        kana: 'かんけい',
        meaning: ['Relation', 'Connection'],
        sentence: '彼との関係はとても大切です。',
        type: 'YDC_main',
      },
      {
        reading: '国際関係',
        kana: 'こくさいかんけい',
        meaning: ['International relations'],
        sentence: '国際関係の専門家として働いています。',
        type: 'YDC_main',
      },
      {
        reading: '係',
        kana: 'かかり',
        meaning: ['Person in charge'],
        sentence: 'このイベントの係は私です。',
        type: 'YDC_main',
      },
      {
        reading: '係員',
        kana: 'かかりいん',
        meaning: ['Staff member', 'Someone in charge'],
        sentence: '係員に質問してみてください。',
        type: 'secondary',
      },
      {
        reading: '人間関係',
        kana: 'にんげんかんけい',
        meaning: ['Human relationships'],
        sentence: '人間関係は複雑です。',
        type: 'secondary',
      },
      {
        reading: '無関係',
        kana: 'むかんけい',
        meaning: ['Unrelated', 'Irrelevant'],
        sentence: 'その話は私には無関係です。',
        type: 'secondary',
      },
      {
        reading: '係る',
        kana: 'かかる',
        meaning: ['To be related to', 'To concern'],
        sentence: 'この問題は私に係ることではありません。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '義',
    onyomi: ['ぎ'],
    kunyomi: [],
    meaning: ['Justice', 'Righteousness'],
    examples: [
      {
        reading: '主義',
        kana: 'しゅぎ',
        meaning: ['Principle', 'Doctrine'],
        sentence: '彼は自由主義の信奉者です。',
        type: 'YDC_main',
      },
      {
        reading: '民主主義',
        kana: 'みんしゅしゅぎ',
        meaning: ['Democracy'],
        sentence: '民主主義は国民の意志を尊重します。',
        type: 'YDC_main',
      },
      {
        reading: '社会主義',
        kana: 'しゃかいしゅぎ',
        meaning: ['Socialism'],
        sentence: '社会主義は平等を重視する政治体制です。',
        type: 'YDC_main',
      },
      {
        reading: '講義',
        kana: 'こうぎ',
        meaning: ['Lecture', 'Class'],
        sentence: '大学の講義を受けています。',
        type: 'secondary',
      },
      {
        reading: '義務',
        kana: 'ぎむ',
        meaning: ['Duty', 'Obligation'],
        sentence: '義務教育は9年間です。',
        type: 'secondary',
      },
      {
        reading: '義理',
        kana: 'ぎり',
        meaning: ['Obligation', 'Sense of duty'],
        sentence: '義理を重んじる文化があります。',
        type: 'secondary',
      },
      {
        reading: '正義',
        kana: 'せいぎ',
        meaning: ['Justice', 'Righteousness'],
        sentence: '正義を貫くことが大切です。',
        type: 'secondary',
      },
      {
        reading: '定義',
        kana: 'ていぎ',
        meaning: ['Definition'],
        sentence: '言葉の定義を確認しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '議',
    onyomi: ['ぎ'],
    kunyomi: [],
    meaning: ['Discussion', 'Deliberation'],
    examples: [
      {
        reading: '会議',
        kana: 'かいぎ',
        meaning: ['Meeting', 'Conference'],
        sentence: '明日の会議は午後3時からです。',
        type: 'YDC_main',
      },
      {
        reading: '国会議員',
        kana: 'こっかいぎいん',
        meaning: ['Member of congress'],
        sentence: '国会議員は法律を制定します。',
        type: 'YDC_main',
      },
      {
        reading: '不思議な',
        kana: 'ふしぎな',
        meaning: ['Mysterious', 'Strange'],
        sentence: '不思議な出来事が起こりました。',
        type: 'YDC_main',
      },
      {
        reading: '議会',
        kana: 'ぎかい',
        meaning: ['Parliament', 'Legislature', 'the Diet'],
        sentence: '議会で新しい法律が審議されています。',
        type: 'secondary',
      },
      {
        reading: '議論する',
        kana: 'ぎろんする',
        meaning: ['To discuss', 'To debate'],
        sentence: 'その問題について議論しました。',
        type: 'main',
      },
      {
        reading: '議題',
        kana: 'ぎだい',
        meaning: ['Agenda', 'Topic of discussion'],
        sentence: '次の会議の議題を決めました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '党',
    onyomi: ['とう'],
    kunyomi: [],
    meaning: ['Political Party'],
    examples: [
      {
        reading: '政党',
        kana: 'せいとう',
        meaning: ['Political party'],
        sentence: '政党の政策について話し合いました。',
        type: 'YDC_main',
      },
      {
        reading: '与党',
        kana: 'よとう',
        meaning: ['Ruling party'],
        sentence: '与党は新しい法律を提案しました。',
        type: 'secondary',
      },
      {
        reading: '野党',
        kana: 'やとう',
        meaning: ['Opposition party'],
        sentence: '野党は政府の政策に反対しています。',
        type: 'secondary',
      },
      {
        reading: '党首',
        kana: 'とうしゅ',
        meaning: ['Party leader'],
        sentence: '党首が記者会見を開きました。',
        type: 'secondary',
      },
    ],
  },
]