export const KANJI_YDC_LESSON_11: Array<KanjiYDC> = [
  {
    kanji: '料',
    onyomi: ['りょう'],
    kunyomi: [],
    meaning: ['Ingredient', 'fare'],
    examples: [
      {
        reading: '料理',
        kana: 'りょうり',
        meaning: ['Cooking', 'Dish'],
        sentence: '料理をします。',
        type: 'main',
      },
      {
        reading: '食料品',
        kana: 'しょくりょうひん',
        meaning: ['Groceries'],
        sentence: '食料品を買います。',
        type: 'main',
      },
      {
        reading: '無料',
        kana: 'むりょう',
        meaning: ['Free', 'No charge'],
        sentence: '無料です。',
        type: 'main',
      },
      {
        reading: '料金',
        kana: 'りょうきん',
        meaning: ['Fee', 'Charge'],
        sentence: '料金を払います。',
        type: 'main',
      },
      {
        reading: '給料',
        kana: 'きゅうりょう',
        meaning: ['Salary', 'Wage'],
        sentence: '給料が上がります。',
        type: 'main',
      },
      {
        reading: '授業料',
        kana: 'じゅぎょうりょう',
        meaning: ['Tuition fee'],
        sentence: '授業料を払います。',
        type: 'secondary',
      },
      {
        reading: '材料',
        kana: 'ざいりょう',
        meaning: ['Materials'],
        sentence: '材料を買います。',
        type: 'secondary',
      },
      {
        reading: '資料',
        kana: 'しりょう',
        meaning: ['Documents', 'Data'],
        sentence: '資料を見ます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '理',
    onyomi: ['り'],
    kunyomi: [],
    meaning: ['Reason', 'Logic'],
    examples: [
      {
        reading: '料理',
        kana: 'りょうり',
        meaning: ['Cooking', 'Dish'],
        sentence: '料理をします。',
        type: 'main',
      },
      {
        reading: '無理な',
        kana: 'むりな',
        meaning: ['Unreasonable', 'Impossible'],
        sentence: '無理な要求です。',
        type: 'main',
      },
      {
        reading: '理由',
        kana: 'りゆう',
        meaning: ['Reason', 'Excuse'],
        sentence: '理由を聞きます。',
        type: 'main',
      },
      {
        reading: '地理',
        kana: 'ちり',
        meaning: ['Geography'],
        sentence: '地理が好きです。',
        type: 'secondary',
      },
      {
        reading: '修理',
        kana: 'しゅうり',
        meaning: ['Repair'],
        sentence: '修理に出します。',
        type: 'secondary',
      },
      {
        reading: '理想',
        kana: 'りそう',
        meaning: ['Ideal'],
        sentence: '理想を持ちます。',
        type: 'secondary',
      },
      {
        reading: '理解',
        kana: 'りかい',
        meaning: ['Understanding'],
        sentence: '理解します。',
        type: 'secondary',
      },
      {
        reading: '心理学',
        kana: 'しんりがく',
        meaning: ['Psychology'],
        sentence: '心理学が好きです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '反',
    onyomi: ['はん', 'ほん', 'たん'],
    kunyomi: ['そ'],
    meaning: ['To Oppose'],
    examples: [
      {
        reading: '反対する',
        kana: 'はんたいする',
        meaning: ['To oppose', 'To object'],
        sentence: '反対します。',
        type: 'main',
      },
      {
        reading: '違反',
        kana: 'いはん',
        meaning: ['Violation'],
        sentence: '違反します。',
        type: 'secondary',
      },
      {
        reading: '反省',
        kana: 'はんせい',
        meaning: ['Reflection', 'Self-examination'],
        sentence: '反省します。',
        type: 'secondary',
      },
      {
        reading: '反抗',
        kana: 'はんこう',
        meaning: ['Resistance', 'Rebellion'],
        sentence: '反抗します。',
        type: 'secondary',
      },
      {
        reading: '反る',
        kana: 'そる',
        meaning: ['To bend', 'To warp'],
        sentence: '反ります。',
        type: 'secondary',
      },
      {
        reading: '反応',
        kana: 'はんのう',
        meaning: ['Reaction', 'Response'],
        sentence: '反応します。',
        type: 'secondary',
      },
      {
        reading: '反物',
        kana: 'たんもの',
        meaning: ['Kimono fabric', 'Cloth'],
        sentence: '',
        type: 'secondary',
      },
      {
        reading: '謀反',
        kana: 'ぼうはん',
        meaning: ['Rebellion', 'Revolt'],
        sentence: '謀反を起こします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: 'ご飯',
    onyomi: ['はん'],
    kunyomi: ['めし'],
    meaning: ['Rice', 'Meal'],
    examples: [
      {
        reading: 'ご飯',
        kana: 'ごはん',
        meaning: ['Rice', 'Meal'],
        sentence: 'ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '朝ご飯',
        kana: 'あさごはん',
        meaning: ['Breakfast'],
        sentence: '朝ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '昼ご飯',
        kana: 'ひるごはん',
        meaning: ['Lunch'],
        sentence: '昼ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '晩ご飯',
        kana: 'ばんごはん',
        meaning: ['Dinner'],
        sentence: '晩ご飯を食べます。',
        type: 'main',
      },
      {
        reading: '飯',
        kana: 'めし',
        meaning: ['Meal (Vulgar expression)'],
        sentence: '飯を食べます。',
        type: 'secondary',
      },
      {
        reading: '炊飯器',
        kana: 'すいはんき',
        meaning: ['Rice cooker'],
        sentence: '炊飯器を使います。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '牛',
    onyomi: ['ぎゅう'],
    kunyomi: ['うし'],
    meaning: ['Cow'],
    examples: [
      {
        reading: '牛',
        kana: 'うし',
        meaning: ['Cow', 'Bull'],
        sentence: '牛がいます。',
        type: 'main',
      },
      {
        reading: '牛肉',
        kana: 'ぎゅうにく',
        meaning: ['Beef'],
        sentence: '牛肉を食べます。',
        type: 'main',
      },
      {
        reading: '牛乳',
        kana: 'ぎゅうにゅう',
        meaning: ['Milk'],
        sentence: '牛乳を飲みます。',
        type: 'main',
      },
      {
        reading: '牛丼',
        kana: 'ぎゅうどん',
        meaning: ['Beef bowl'],
        sentence: '牛丼を食べます。',
        type: 'main',
      },
      {
        reading: '子牛',
        kana: 'こうし',
        meaning: ['Calf', 'Veal'],
        sentence: '子牛がいます。',
        type: 'secondary',
      },
      {
        reading: '牡牛座',
        kana: 'おうしざ',
        meaning: ['Taurus'],
        sentence: '牡牛座が好きです。',
        type: 'secondary',
      },
      {
        reading: '水牛',
        kana: 'すいぎゅう',
        meaning: ['Buffalo'],
        sentence: '水牛がいます。',
        type: 'secondary',
      },
      {
        reading: '闘牛',
        kana: 'とうぎゅう',
        meaning: ['Bullfight'],
        sentence: '闘牛を見ます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '豚',
    onyomi: ['とん'],
    kunyomi: ['ぶた'],
    meaning: ['Pig'],
    examples: [
      {
        reading: '豚',
        kana: 'ぶた',
        meaning: ['Pig'],
        sentence: '豚がいます。',
        type: 'main',
      },
      {
        reading: '豚肉',
        kana: 'ぶたにく',
        meaning: ['Pork'],
        sentence: '豚肉を食べます。',
        type: 'main',
      },
      {
        reading: '子豚',
        kana: 'こぶた',
        meaning: ['Piglet'],
        sentence: '子豚がいます。',
        type: 'secondary',
      },
      {
        reading: '豚カツ',
        kana: 'とんかつ',
        meaning: ['Pork cutlet'],
        sentence: '豚カツを食べます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '鳥',
    onyomi: ['ちょう'],
    kunyomi: ['とり'],
    meaning: ['Bird'],
    examples: [
      {
        reading: '鳥',  
        kana: 'とり',
        meaning: ['Bird'],
        sentence: '鳥が飛んでいます。',
        type: 'main',
      },
      {
        reading: '小鳥',
        kana: 'ことり',
        meaning: ['Small bird'],
        sentence: '小鳥がいます。',
        type: 'main',
      },
      {
        reading: '鳥肉',
        kana: 'とりにく',
        meaning: ['Chicken'],
        sentence: '鳥肉を食べます。',
        type: 'main',
      },
      {
        reading: '焼き鳥',
        kana: 'やきとり',
        meaning: ['Grilled chicken'],
        sentence: '焼き鳥を食べます。',
        type: 'main',
      },
      {
        reading: '鳥居',
        kana: 'とりい',
        meaning: ['Shrine gate'],
        sentence: '鳥居があります。',
        type: 'main',
      },
      {
        reading: '一石二鳥',
        kana: 'いっせきにちょう',
        meaning: ['Kill two birds with one stone'],
        sentence: '一石二鳥です。',
        type: 'main',
      },
      {
        reading: '白鳥',
        kana: 'はくちょう',
        meaning: ['Swan', 'White bird'],
        sentence: '白鳥がいます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '肉',
    onyomi: ['にく'],
    kunyomi: [],
    meaning: ['Meat'],
    examples: [
      {
        reading: '肉',
        kana: 'にく',
        meaning: ['Meat'],
        sentence: '肉を食べます。',
        type: 'main',
      },
      { 
        reading: '牛肉',
        kana: 'ぎゅうにく',
        meaning: ['Beef'],
        sentence: '牛肉を食べます。',
        type: 'main',
      },
      {
        reading: '豚肉',
        kana: 'ぶたにく',
        meaning: ['Pork'],
        sentence: '豚肉を食べます。',
        type: 'main',
      },
      {
        reading: '鳥肉',
        kana: 'とりにく',
        meaning: ['Chicken'],
        sentence: '鳥肉を食べます。',
        type: 'main',
      },
      {
        reading: '肉屋',
        kana: 'にくや',
        meaning: ['Butcher', 'Meat shop'],
        sentence: '肉屋に行きます。',
        type: 'main',
      },
      {
        reading: '筋肉',
        kana: 'きんにく',
        meaning: ['Muscle'],
        sentence: '筋肉がつきます。',
        type: 'main',
      },
      {
        reading: '皮肉',
        kana: 'ひにく',
        meaning: ['Irony', 'Sarcasm'],
        sentence: '皮肉です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '茶',
    onyomi: ['ちゃ', 'さ'],
    kunyomi: [],
    meaning: ['Tea'],
    examples: [
      {
        reading: 'お茶',
        kana: 'おちゃ',
        meaning: ['Tea'],
        sentence: 'お茶を飲みます。',
        type: 'main',
      },
      {
        reading: '茶色',
        kana: 'ちゃいろ',
        meaning: ['Brown'],
        sentence: '茶色が好きです。',
        type: 'main',
      },
      {
        reading: '紅茶',
        kana: 'こうちゃ',
        meaning: ['Black tea'],
        sentence: '紅茶を飲みます。',
        type: 'main',
      },
      {
        reading: '緑茶',
        kana: 'りょくちゃ',
        meaning: ['Green tea'],
        sentence: '緑茶を飲みます。',
        type: 'main',
      },
      {
        reading: '喫茶店',
        kana: 'きっさてん',
        meaning: ['Cafe'],
        sentence: '喫茶店に行きます。',
        type: 'secondary',
      },
      {
        reading: '茶碗',
        kana: 'ちゃわん',
        meaning: ['Tea cup', 'Rice bowl'],
        sentence: '茶碗を使います。',
        type: 'secondary',
      },
      {
        reading: '茶道',
        kana: 'さどう・ちゃどう',
        meaning: ['Tea ceremony'],
        sentence: '茶道を習います。',
        type: 'secondary',
      },
      {
        reading: '無茶苦茶',
        kana: 'むちゃくちゃ',
        meaning: ['Mess'],
        sentence: '無茶苦茶です。',
        type: 'secondary',
      },
      {
        reading: '茶店',
        kana: 'さてん',
        meaning: ['Tea shop', 'Tea house'],
        sentence: '茶店に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '予',
    onyomi: ['よ'],
    kunyomi: [],
    meaning: ['In advance', 'Beforehand'],
    examples: [ 
      {
        reading: '予定',
        kana: 'よてい',
        meaning: ['Plan', 'Schedule'],
        sentence: '予定を立てます。',
        type: 'main',
      },
      {
        reading: '予約',
        kana: 'よやく',
        meaning: ['Reservation'],
        sentence: '予約をします。',
        type: 'main',
      },
      {
        reading: '天気予報',
        kana: 'てんきよほう',
        meaning: ['Weather forecast'],
        sentence: '天気予報を見ます。',
        type: 'main',
      },
      {
        reading: '予算',
        kana: 'よさん',
        meaning: ['Budget'],
        sentence: '予算を立てます。',
        type: 'main',
      },
      {
        reading: '予習',
        kana: 'よしゅう',
        meaning: ['Preparation for a lesson'],
        sentence: '予習します。',
        type: 'secondary',
      },
      {
        reading: '予測',
        kana: 'よそく',
        meaning: ['Prediction', 'Forecast'],
        sentence: '予測します。',
        type: 'secondary',
      },
      {
        reading: '予防',
        kana: 'よぼう',
        meaning: ['Prevention'],
        sentence: '予防します。',
        type: 'secondary',
      },
      {
        reading: '予言',
        kana: 'よげん',
        meaning: ['Prophecy', 'Prediction'],
        sentence: '予言します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '野',
    onyomi: ['や'],
    kunyomi: ['の'],
    meaning: ['Field'],
    examples: [
      {
        reading: '野菜',
        kana: 'やさい',
        meaning: ['Vegetable'],
        sentence: '野菜を食べます。',
        type: 'main',
      },
      {
        reading: '長野',
        kana: 'ながの',
        meaning: ['Nagano (prefecture)'],
        sentence: '長野に行きます。',
        type: 'main',
      },
      {
        reading: '小野さん',
        kana: 'おのさん',
        meaning: ['Mr. Ono'],
        sentence: '小野さんがいます。',
        type: 'secondary',
      },
      {
        reading: '野球',
        kana: 'やきゅう',
        meaning: ['Baseball'],
        sentence: '野球をします。',
        type: 'main',
      },
      {
        reading: '分野',
        kana: 'ぶんや',
        meaning: ['Field', 'Area', 'Realm'],
        sentence: '分野が広いです。',
        type: 'secondary',
      },
      {
        reading: '野党',
        kana: 'やとう',
        meaning: ['Opposition party'],
        sentence: '野党がいます。',
        type: 'secondary',
      },
      {
        reading: '野原',
        kana: 'のはら',
        meaning: ['Field', 'Plains'],
        sentence: '野原が広いです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '菜',
    onyomi: ['さい'],
    kunyomi: ['な'],
    meaning: ['Vegetable'],
    examples: [
      {
        reading: '野菜',
        kana: 'やさい',
        meaning: ['Vegetable'],
        sentence: '野菜を食べます。',
        type: 'main',
      },
      {
        reading: '白菜',
        kana: 'はくさい',
        meaning: ['Chinese cabbage'],
        sentence: '白菜を食べます。',
        type: 'main',
      },
      {
        reading: '山菜',
        kana: 'さんさい',
        meaning: ['Mountain vegetables', 'Edible Wild plants'],
        sentence: '山菜を食べます。',
        type: 'main',
      },
      {
        reading: '菜園',
        kana: 'さいえん',
        meaning: ['Vegetable garden'],
        sentence: '菜園をします。',
        type: 'secondary',
      },
      {
        reading: '菜の花',
        kana: 'なのはな',
        meaning: ['Rape blossoms'],
        sentence: '菜の花が咲きます。',
        type: 'secondary',
      },
      {
        reading: '菜食主義',
        kana: 'さいしょくしゅぎ',
        meaning: ['Vegetarianism'],
        sentence: '菜食主義です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '切',
    onyomi: ['せつ', 'さい'],
    kunyomi: ['き', 'きっ'],
    meaning: ['To Cut'],
    examples: [
      {
        reading: '切る',
        kana: 'きる',
        meaning: ['To cut'],
        sentence: '切ります。',
        type: 'main',
      },
      {
        reading: '切手',
        kana: 'きって',
        meaning: ['Postage Stamp'],
        sentence: '切手を貼ります。',
        type: 'main',
      },
      {
        reading: '大切な',
        kana: 'たいせつな',
        meaning: ['Important', 'Precious'],
        sentence: '大切な人です。',
        type: 'main',
      },
      {
        reading: '親切な',
        kana: 'しんせつな',
        meaning: ['Kind', 'Friendly'],
        sentence: '親切な人です。',
        type: 'main',
      },
      {
        reading: '切符',
        kana: 'きっぷ',
        meaning: ['Ticket'],
        sentence: '切符を買います。',
        type: 'main',
      },
      {
        reading: '締め切り',
        kana: 'しめきり',
        meaning: ['Deadline'],
        sentence: '締め切りです。',
        type: 'main',
      },
      {
        reading: '一切れ',
        kana: 'ひときれ',
        meaning: ['One slice'],
        sentence: '一切れです。',
        type: 'main',
      },
      {
        reading: '一切',
        kana: 'いっさい',
        meaning: ['All', 'Everything'],
        sentence: '一切です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '作',
    onyomi: ['さく', 'さっ', 'さ'],
    kunyomi: ['つく', 'づく'],
    meaning: ['To Make'],
    examples: [
      {
        reading: '作る',
        kana: 'つくる',
        meaning: ['To make'],
        sentence: '作ります。',
        type: 'main',
      },
      {
        reading: '手作り',
        kana: 'てづくり',
        meaning: ['Handmade'],
        sentence: '手作りです。',
        type: 'main',
      },
      {
        reading: '作文',
        kana: 'さくぶん',
        meaning: ['Composition', 'Essay'],
        sentence: '作文を書きます。',
        type: 'secondary',
      },
      {
        reading: '作品',
        kana: 'さくひん',
        meaning: ['Artistic Piece'],
        sentence: '作品があります。',
        type: 'secondary',
      },
      {
        reading: '作家',
        kana: 'さっか',
        meaning: ['Author', 'Writer', 'Novelist'],
        sentence: '作家です。',
        type: 'secondary',
      },
      {
        reading: '操作',
        kana: 'そうさ',
        meaning: ['Operation', 'Management'],
        sentence: '操作します。',
        type: 'secondary',
      },
      {
        reading: '名作',
        kana: 'めいさく',
        meaning: ['Masterpiece'],
        sentence: '名作です。',
        type: 'secondary',
      },
      {
        reading: '動作',
        kana: 'どうさ',
        meaning: ['Movement', 'Action'],
        sentence: '動作します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '未',
    onyomi: ['み'],
    kunyomi: [],
    meaning: ['Not Yet'],
    examples: [
      {
        reading: '未来',
        kana: 'みらい',
        meaning: ['Future'],
        sentence: '未来が楽しみです。',
        type: 'main',
      },
      {
        reading: '未成年',
        kana: 'みせいねん',
        meaning: ['Minor', 'Underage'],
        sentence: '未成年です。',
        type: 'main',
      },
      {
        reading: '未満',
        kana: 'みまん',
        meaning: ['Less than', 'Under', 'Below'],
        sentence: '未満です。',
        type: 'secondary',
      },
      {
        reading: '未婚',
        kana: 'みこん',
        meaning: ['Unmarried', 'Single'],
        sentence: '未婚です。',
        type: 'secondary',
      },
      {
        reading: '未定',
        kana: 'みてい',
        meaning: ['Not yet determined', 'Pending'],
        sentence: '未定です。',
        type: 'secondary',
      },
      {
        reading: '未熟',
        kana: 'みじゅく',
        meaning: ['Immature', 'Inexperienced'],
        sentence: '未熟です。',
        type: 'secondary',
      },
      {
        reading: '未明',
        kana: 'みめい',
        meaning: ['Before dawn', 'Daybreak'],
        sentence: '未明です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '味',
    onyomi: ['み'],
    kunyomi: ['あじ'],
    meaning: ['Taste'],
    examples: [
      {
        reading: '味',
        kana: 'あじ',
        meaning: ['Taste', 'Flavor'],
        sentence: '味がいいです。',
        type: 'main',
      },
      {
        reading: '意味',
        kana: 'いみ',
        meaning: ['Meaning'],
        sentence: '意味がわかります。',
        type: 'main',
      },
      {
        reading: '趣味',
        kana: 'しゅみ',
        meaning: ['Hobby'],
        sentence: '趣味は何？',
        type: 'main',
      },
      {
        reading: '興味',
        kana: 'きょうみ',
        meaning: ['Interest'],
        sentence: '興味があります。',
        type: 'secondary',
      },
      {
        reading: '味噌',
        kana: 'みそ',
        meaning: ['Miso (Soybean paste)'],
        sentence: '味噌を使います。',
        type: 'main',
      },
      {
        reading: '調味料',
        kana: 'ちょうみりょう',
        meaning: ['Seasoning'],
        sentence: '調味料を使います。',
        type: 'main',
      },
      {
        reading: '味わう',
        kana: 'あじわう',
        meaning: ['To taste', 'To savor'],
        sentence: '味わいます。',
        type: 'main',
      },
      {
        reading: '地味',
        kana: 'じみ',
        meaning: ['Plain', 'Simple', 'Somber'],
        sentence: '地味です。',
        type: 'secondary',
      },
    ],
  },
]