export const KANJI_YDC_LESSON_17: Array<KanjiYDC> = [
  {
    kanji: '医',
    onyomi: ['い'],
    kunyomi: [],
    meaning: ['Medicine', 'Doctor'],
    examples: [
      {
        reading: '医者',
        kana: 'いしゃ',
        meaning: ['Doctor'],
        sentence: '医者に行くときは、予約をしてから行くことが多いです。',
        type: 'main',
      },
      {
        reading: '医師',
        kana: 'いし',
        meaning: ['Physician', 'Doctor'],
        sentence: '医師は患者の健康を守るために、日々努力しています。',
        type: 'main',
      },
      {
        reading: '医学',
        kana: 'いがく',
        meaning: ['Medical science'],
        sentence: '医学の勉強をするために、大学に進学しました。',
        type: 'main',
      },
      {
        reading: '歯医者',
        kana: 'はいしゃ',
        meaning: ['Dentist'],
        sentence: '歯医者に行くのは少し緊張しますが、定期的に検診を受けることが大切です。',
        type: 'main',
      },
      {
        reading: '医院',
        kana: 'いいん',
        meaning: ['Clinic'],
        sentence: '近くに新しい医院がオープンしました。',
        type: 'main',
      },
      {
        reading: '医療',
        kana: 'いりょう',
        meaning: ['Medical care', 'Medical treatment'],
        sentence: '医療制度の改善が求められています。',
        type: 'main',
      },
      {
        reading: '医薬品',
        kana: 'いりゃくひん',
        meaning: ['Medicinal products', 'Medicinal supplies'],
        sentence: '医薬品の購入には、処方箋が必要な場合があります。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '始',
    onyomi: ['し'],
    kunyomi: ['はじ'],
    meaning: ['Begin', 'Start'],
    examples: [
      {
        reading: '始まる',
        kana: 'はじまる',
        meaning: ['To begin (Something begins)'],
        sentence: '授業が始まる前に、教室に入って準備をします。',
        type: 'main',
      },
      {
        reading: '始める',
        kana: 'はじめる',
        meaning: ['To start (something)'],
        sentence: '新しいプロジェクトを始めるために、チームを結成しました。',
        type: 'main',
      },
      {
        reading: '開始する',
        kana: 'かいしする',
        meaning: ['To start (Something)'],
        sentence: '会議は午後2時に開始される予定です。',
        type: 'main',
      },
      {
        reading: '始終',
        kana: 'しじゅう',
        meaning: ['Always', 'From beginning to end', 'All the time'],
        sentence: '彼は始終忙しそうにしているので、あまり話す機会がありません。',
        type: 'main',
      },
      {
        reading: '書き始める',
        kana: 'かきはじめる',
        meaning: ['To start writing'],
        sentence: '新しい小説を書き始めることにしました。',
        type: 'main',
      },
      {
        reading: '始発',
        kana: 'しはつ',
        meaning: ['First train of the day'],
        sentence: '始発の電車に乗るために、早起きしました。',
        type: 'main',
      },
      {
        reading: '原始的な',
        kana: 'げんしてきな',
        meaning: ['Primitive'],
        sentence: '原始的な生活様式は、現代社会とは大きく異なります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '終',
    onyomi: ['しゅう', 'じゅう'],
    kunyomi: ['お'],
    meaning: ['End', 'Finish'],
    examples: [
      {
        reading: '終わる',
        kana: 'おわる',
        meaning: ['To end (Something ends)', 'To come to an end'],
        sentence: '授業が終わったら、友達と一緒にランチを食べに行きました。',
        type: 'main',
      },
      {
        reading: '終わり',
        kana: 'おわり',
        meaning: ['End'],
        sentence: '映画の終わりがとても感動的でした。',
        type: 'main',
      },
      {
        reading: '終える',
        kana: 'おえる',
        meaning: ['To finish (Something)'],
        sentence: '宿題を終えたら、友達と遊びに行く予定です。',
        type: 'main',
      },
      {
        reading: '最終',
        kana: 'さいしゅう',
        meaning: ['Final', 'Last'],
        sentence: '最終回の放送が楽しみです。',
        type: 'main',
      },
      {
        reading: '終了',
        kana: 'しゅうりょう',
        meaning: ['End', 'Completion'],
        sentence: '試験の終了時間が近づいてきました。',
        type: 'main',
      },
      {
        reading: '終電',
        kana: 'しゅうでん',
        meaning: ['Last train of the day'],
        sentence: '終電を逃さないように、急いで駅に向かいました。',
        type: 'main',
      },
      {
        reading: '終点',
        kana: 'しゅうてん',
        meaning: ['Last stop', 'Final destination'],
        sentence: 'この電車の終点は、東京駅です。',
        type: 'main',
      },
      {
        reading: '始終',
        kana: 'しじゅう',
        meaning: ['Always', 'From beginning to end', 'All the time'],
        sentence: '彼は始終忙しそうにしているので、あまり話す機会がありません。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '石',
    onyomi: ['せき', 'せっ', 'しゃく', 'こく'],
    kunyomi: ['いし'],
    meaning: ['Stone'],
    examples: [
      {
        reading: '宝石',
        kana: 'ほうせき',
        meaning: ['Gem', 'Jewel'],
        sentence: '宝石店で美しい宝石を見つけました。',
        type: 'secondary',
      },
      {
        reading: '石鹸',
        kana: 'せっけん',
        meaning: ['Soap'],
        sentence: '石鹸で手を洗うことは、衛生的です。',
        type: 'main',
      },
      {
        reading: '石油',
        kana: 'せきゆ',
        meaning: ['Petroleum', 'Oil'],
        sentence: '石油はエネルギー源として重要な資源です。',
        type: 'secondary',
      },
      {
        reading: '石炭',
        kana: 'せきたん',
        meaning: ['Coal'],
        sentence: '石炭は、昔からエネルギー源として利用されてきました。',
        type: 'secondary',
      },
      {
        reading: '磁石',
        kana: 'じしゃく',
        meaning: ['Magnet'],
        sentence: '磁石を使って、鉄のものを引き寄せることができます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '研',
    onyomi: ['けん'],
    kunyomi: ['と'],
    meaning: ['Polish', 'Study'],
    examples: [
      {
        reading: '研究',
        kana: 'けんきゅう',
        meaning: ['Research'],
        sentence: '大学での研究は、専門知識を深めるために重要です。',
        type: 'main',
      },
      {
        reading: '研究者',
        kana: 'けんきゅうしゃ',
        meaning: ['Researcher'],
        sentence: '研究者は新しい発見をするために、日々努力しています。',
        type: 'main',
      },
      {
        reading: '研究室',
        kana: 'けんきゅうしつ',
        meaning: ['Laboratory', 'Research room'],
        sentence: '研究室では、さまざまな実験が行われています。',
        type: 'main',
      },
      {
        reading: '研究所',
        kana: 'けんきゅうじょ・けんきゅうしょ',
        meaning: ['Research institute'],
        sentence: '新しい技術の開発を行う研究所が設立されました。',
        type: 'secondary',
      },
      {
        reading: '研修',
        kana: 'けんしゅう',
        meaning: ['Training'],
        sentence: '新入社員は研修を受けて、会社のルールを学びます。',
        type: 'secondary',
      },
      {
        reading: '研ぐ',
        kana: 'とぐ',
        meaning: ['To sharpen', 'To polish'],
        sentence: '包丁を研ぐことで、切れ味が良くなります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '究',
    onyomi: ['きゅう'],
    kunyomi: ['きわ'],
    meaning: ['Research', 'Study'],
    examples: [
      {
        reading: '研究',
        kana: 'けんきゅう',
        meaning: ['Research'],
        sentence: '大学での研究は、専門知識を深めるために重要です。',
        type: 'main',
      },
      {
        reading: '研究者',
        kana: 'けんきゅうしゃ',
        meaning: ['Researcher'],
        sentence: '研究者は新しい発見をするために、日々努力しています。',
        type: 'main',
      },
      {
        reading: '研究室',
        kana: 'けんきゅうしつ',
        meaning: ['Laboratory', 'Research room'],
        sentence: '研究室では、さまざまな実験が行われています。',
        type: 'main',
      },
      {
        reading: '究明',
        kana: 'きゅうめい',
        meaning: ['Investigation', 'Clarification'],
        sentence: '事件の真相を究明するために、捜査が行われています。',
        type: 'secondary',
      },
      {
        reading: '究極の',
        kana: 'きゅうきょくの',
        meaning: ['Ultimate'],
        sentence: '究極の選択を迫られる場面が多いです。',
        type: 'secondary',
      },
      {
        reading: '究める',
        kana: 'きわめる',
        meaning: ['To investigate thoroughly', 'To master'],
        sentence: 'この分野を究めるために、長い時間をかけて勉強しています。',
        type: 'secondary',
      },
      {
        reading: '探究',
        kana: 'たんきゅう',
        meaning: ['Inquiry'],
        sentence: '探究心を持って、さまざまなことに挑戦しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '留',
    onyomi: ['りゅう', 'る'],
    kunyomi: ['と'],
    meaning: ['To Stay'],
    examples: [
      {
        reading: '留学する',  
        kana: 'りゅうがくする',
        meaning: ['To study abroad'],
        sentence: '彼はアメリカに留学することを決めました。',
        type: 'main',
      },
      {
        reading: '留学生',
        kana: 'りゅうがくせい',
        meaning: ['International student'],
        sentence: '留学生として、日本の文化を学ぶことができて嬉しいです。',
        type: 'main',
      },
      {
        reading: '留守',
        kana: 'るす',
        meaning: ['Absence', 'Not at home'],
        sentence: '留守の間に、宅配便が届きました。',
        type: 'main',
      },
      {
        reading: '留守番電話',
        kana: 'るすばんでんわ',
        meaning: ['Answering machine'],
        sentence: '留守番電話にメッセージが残っていました。',
        type: 'main',
      },
      {
        reading: '留める',  
        kana: 'とめる',
        meaning: ['To fasten'],
        sentence: '書類をクリップで留めておきました。',
        type: 'secondary',
      },
      {
        reading: '書留(書き留め)',
        kana: 'かきとめ',
        meaning: ['Registered mail'],
        sentence: '重要な書類は、書留で送ることにしました。',
        type: 'main',  
      },
    ],
  },
  {
    kanji: '有',
    onyomi: ['ゆう', 'う'],
    kunyomi: ['あ'],
    meaning: ['Exist', 'Have'],
    examples: [
      {
        reading: '有名な',  
        kana: 'ゆうめいな',
        meaning: ['Famous'],
        sentence: '彼は有名な作家です。',
        type: 'main',
      },
      {
        reading: '有る',
        kana: 'ある',
        meaning: ['To exist', 'To have'],
        sentence: 'この町には美しい公園が有ります。',
        type: 'main',
      },
      {
        reading: '有料',
        kana: 'ゆうりょう',
        meaning: ['Toll', 'Fee'],
        sentence: 'この駐車場は有料です。',
        type: 'main',
      },
      {
        reading: '有利な',
        kana: 'ゆうりな',
        meaning: ['Advantageous'],
        sentence: 'この条件は有利なものです。',
        type: 'secondary',
      },
      {
        reading: '有効な',
        kana: 'ゆうこうな',
        meaning: ['Valid', 'Effective'],
        sentence: 'このクーポンは有効期限が切れています。',
        type: 'secondary',
      },
      {
        reading: '有能な',
        kana: 'ゆうのうな',
        meaning: ['Talented', 'Competent'],
        sentence: '彼は有能なエンジニアです。',
        type: 'secondary',
      },
      {
        reading: '有難い（有り難い）',
        kana: 'ありがたい',
        meaning: ['Grateful', 'Thankful'],
        sentence: '忙しい中、わざわざ時間を作って手伝ってくれて、本当に有り難かったです。',
        type: 'main',
      },
      {
        reading: '有無',
        kana: 'うむ',
        meaning: ['To have or not have', 'Existence or non-existence', 'Whether or not'],
        sentence: '応募の際は、日本での就労資格の有無を明記してください。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '開',
    onyomi: ['かい'],
    kunyomi: ['あ', 'ひら'],
    meaning: ['Open'],
    examples: [
      {
        reading: '開く',
        kana: 'あく',
        meaning: ['(Something) opens'],
        sentence: 'ドアが開くと、外の景色が見えました。',
        type: 'main',
      },
      {
        reading: '開ける',
        kana: 'あける',
        meaning: ['To open (something)'],
        sentence: '窓を開けると、涼しい風が入ってきました。',
        type: 'main',
      },
      {
        reading: '開く',
        kana: 'ひらく',
        meaning: ['To open (something)'],
        sentence: '本を開くと、面白い物語が始まりました。',
        type: 'main',
      },
      {
        reading: '開始する',
        kana: 'かいしする',
        meaning: ['To start (Something)'],
        sentence: '会議は午後2時に開始される予定です。',
        type: 'main',
      },
      {
        reading: '開店',
        kana: 'かいてん',
        meaning: ['Opening of a store'],
        sentence: '新しいレストランが開店しました。',
        type: 'main',
      },
      {
        reading: '公開',
        kana: 'こうかい',
        meaning: ['Public release', 'Open to the public'],
        sentence: '映画の公開日が決まりました。',
        type: 'main',
      },
      {
        reading: '開会式',
        kana: 'かいかいしき',
        meaning: ['Opening ceremony'],
        sentence: 'オリンピックの開会式は、世界中から注目されています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '閉',
    onyomi: ['へい'],
    kunyomi: ['し', 'と'],
    meaning: ['Close'],
    examples: [ 
      {
        reading: '閉まる',
        kana: 'しまる',
        meaning: ['(Something) closes'],
        sentence: 'ドアが閉まる音が聞こえました。',
        type: 'main',
      },
      {
        reading: '閉める',
        kana: 'しめる',
        meaning: ['To close (something)'],
        sentence: '窓を閉めると、外の音が聞こえなくなりました。',
        type: 'main',
      },
      {
        reading: '閉じる',
        kana: 'とじる',
        meaning: ['To close (something)'],
        sentence: '本を閉じると、物語の余韻に浸ることができました。',
        type: 'main',
      },
      {
        reading: '閉会式',
        kana: 'へいかいしき',
        meaning: ['Closing ceremony'],
        sentence: 'オリンピックの閉会式は、感動的な瞬間がたくさんありました。',
        type: 'main',
      },
      {
        reading: '閉店',
        kana: 'へいてん',
        meaning: ['Closing of a store'],
        sentence: 'お店の閉店時間が近づいてきました。',
        type: 'main',
      },
      {
        reading: '閉鎖',
        kana: 'へいさ',
        meaning: ['Closure'],
        sentence: 'この道は工事のため、閉鎖されています。',
        type: 'secondary',
      },
      {
        reading: '閉口する',
        kana: 'へいこうする',
        meaning: ['To be annoyed'],
        sentence: '彼の話には閉口してしまいました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '押',
    onyomi: ['おう'],
    kunyomi: ['お'],
    meaning: ['Push', 'Press'],
    examples: [
      {
        reading: '押す',
        kana: 'おす',
        meaning: ['To push', 'To press'],
        sentence: 'ボタンを押すと、電源が入ります。',
        type: 'main',
      },
      {
        reading: '押し入れ',
        kana: 'おしいれ',
        meaning: ['Closet'],
        sentence: '押し入れの中には、古い布団がしまってあります。',
        type: 'main',
      },
      {
        reading: '押さえる',
        kana: 'おさえる',
        meaning: ['To hold down', 'To pin down'],
        sentence: '風で飛ばされないように、紙を押さえておきます。',
        type: 'secondary',
      },
      {
        reading: '押し出す',
        kana: 'おしだす',
        meaning: ['To push out'],
        sentence: '人混みの中で、押し出されてしまいました。',
        type: 'main',
      },
      {
        reading: '押収する',
        kana: 'おうしゅうする',
        meaning: ['To confiscate', 'To seize'],
        sentence: '警察は違法な物品を押収しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '引',
    onyomi: ['いん'],
    kunyomi: ['ひ', 'び'],
    meaning: ['Pull'],
    examples: [
      {
        reading: '引く',
        kana: 'ひく',
        meaning: ['To pull'],
        sentence: 'ドアを引くと、部屋の中に入ることができます。',
        type: 'main',
      },
      {
        reading: '引き出し',
        kana: 'ひきだし',
        meaning: ['Drawer'],
        sentence: '引き出しの中には、たくさんの書類が入っています。',
        type: 'main',
      },
      {
        reading: '引き出す',
        kana: 'ひきだす',
        meaning: ['To withdraw'],
        sentence: 'お金を引き出すために、ATMに行きました。',
        type: 'main',
      },
      {
        reading: '引っ越す',
        kana: 'ひっこす',
        meaning: ['To move out (house)'],
        sentence: '新しい家に引っ越す準備をしています。',
        type: 'main',
      },
      {
        reading: '引き分け',
        kana: 'ひきわけ',
        meaning: ['Draw', 'Tie'],
        sentence: '試合は引き分けに終わりました。',
        type: 'secondary',
      },
      {
        reading: '割引 (割り引き)',
        kana: 'わりびき',
        meaning: ['Discount'],
        sentence: 'この商品は割引セール中です。',
        type: 'main',
      },
      {
        reading: '引用',
        kana: 'いんよう',
        meaning: ['Quotation'],
        sentence: '本の中から引用を使うときは、出典を明記することが大切です。',
        type: 'secondary',
      },
      {
        reading: '引力',
        kana: 'いんりょく',
        meaning: ['Gravity'],
        sentence: '地球の引力は、私たちを地面に引き寄せています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '思',
    onyomi: ['し'],
    kunyomi: ['おも'],
    meaning: ['Think', 'Consider'],
    examples: [
      {
        reading: '思う',
        kana: 'おもう',
        meaning: ['To think'],
        sentence: '彼のことを思うと、心が温かくなります。',
        type: 'main',
      },
      {
        reading: '思い出す',
        kana: 'おもいだす',
        meaning: ['To remember'],
        sentence: '昔のことを思い出すと、懐かしい気持ちになります。',
        type: 'main',
      },
      {
        reading: '思い出',
        kana: 'おもいで',
        meaning: ['Memory'],
        sentence: '旅行の思い出をアルバムにまとめました。',
        type: 'main',
      },
      {
        reading: '思いがけない',
        kana: 'おもいがけない',
        meaning: ['Unexpected'],
        sentence: '思いがけないプレゼントをもらって、驚きました。',
        type: 'main',
      },
      {
        reading: '思いきり',
        kana: 'おもいきり',
        meaning: ['To one\'s heart\'s content'],
        sentence: '思いきり遊んで、楽しい時間を過ごしました。',
        type: 'secondary',
      },
      {
        reading: '不思議な',
        kana: 'ふしぎな',
        meaning: ['Mysterious'],
        sentence: '不思議な出来事が起こりました。',
        type: 'secondary',
      },
      {
        reading: '思想',
        kana: 'しそう',
        meaning: ['Thought', 'Idea'],
        sentence: '彼の思想は、私たちに大きな影響を与えました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '知',
    onyomi: ['ち'],
    kunyomi: ['し'],
    meaning: ['Know'],
    examples: [
      {
        reading: '知る',
        kana: 'しる',
        meaning: ['To know'],
        sentence: '彼のことを知っている人は少ないです。',
        type: 'main',
      },
      {
        reading: '知らせる',
        kana: 'しらせる',
        meaning: ['To inform', 'To notify'],
        sentence: '新しい情報を知らせるために、メールを送りました。',
        type: 'main',
      },
      {
        reading: '知り合い',
        kana: 'しりあい',
        meaning: ['Acquaintance'],
        sentence: '彼は私の知り合いです。',
        type: 'secondary',
      },
      {
        reading: '知人',
        kana: 'ちじん',
        meaning: ['Acquaintance'],
        sentence: '知人に会うために、東京に行きました。',
        type: 'secondary',
      },
      {
        reading: '承知する',
        kana: 'しょうちする',
        meaning: ['To consent', 'To agree'],
        sentence: 'その件については、承知しました。',
        type: 'main',
      },
      {
        reading: '知識',
        kana: 'ちしき',
        meaning: ['Knowledge'],
        sentence: '知識を深めるために、本を読むことが大切です。',
        type: 'secondary',
      },
      {
        reading: '知性',
        kana: 'ちせい',
        meaning: ['Intelligence'],
        sentence: '彼女は知性が高く、さまざまな分野に詳しいです。',
        type: 'secondary',
      },
      {
        reading: '知事',
        kana: 'ちじ',
        meaning: ['Governor'],
        sentence: '知事は地域の発展に貢献するために、さまざまな政策を実施しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '考',
    onyomi: ['こう'],
    kunyomi: ['かんが'],
    meaning: ['Think', 'Consider', 'Idea'],
    examples: [
      {
        reading: '考える',
        kana: 'かんがえる',
        meaning: ['To think', 'To consider'],
        sentence: '問題を解決するために、いろいろな方法を考えています。',
        type: 'main',
      },
      {
        reading: '考え',
        kana: 'かんがえ',
        meaning: ['Thought', 'Idea'],
        sentence: '彼の考えはとても興味深いです。',
        type: 'main',
      },
      {
        reading: '考え方',
        kana: 'かんがえかた',
        meaning: ['Way of thinking'],
        sentence: '考え方を変えることで、問題が解決することがあります。',
        type: 'main',
      },
      {
        reading: '参考',
        kana: 'さんこう',
        meaning: ['Reference'],
        sentence: 'この本は、研究の参考になります。',
        type: 'main',
      },
      {
        reading: '考慮する',
        kana: 'こうりょする',
        meaning: ['To consider'],
        sentence: '彼の意見を考慮して、決定を下しました。',
        type: 'secondary',
      },
      {
        reading: '考古学',
        kana: 'こうこがく',
        meaning: ['Archaeology'],
        sentence: '考古学の研究は、古代の文化を理解する手助けになります。',
        type: 'secondary',
      },
      {
        reading: '参考書',
        kana: 'さんこうしょ',
        meaning: ['Reference book'],
        sentence: 'この参考書は、試験勉強に役立ちます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '死',
    onyomi: ['し'],
    kunyomi: ['し'],
    meaning: ['Death'],
    examples: [
      {
        reading: '死ぬ',
        kana: 'しぬ',
        meaning: ['To die'],
        sentence: '死んだらどうするんだ？',
        type: 'main',
      },
      {
        reading: '死',
        kana: 'し',
        meaning: ['Death'],
        sentence: '死は避けられない現実です。',
        type: 'secondary',
      },
      {
        reading: '死体',
        kana: 'したい',
        meaning: ['Corpse', 'Dead body'],
        sentence: '死体が見つかりました。',
        type: 'main',
      },
      {
        reading: '必死',
        kana: 'ひっし',
        meaning: ['Desperate'],
        sentence: '彼は必死に助けを求めていました。',
        type: 'main',
      },
      {
        reading: '死亡',
        kana: 'しぼう',
        meaning: ['Death'],
        sentence: '事故による死亡者が増えています。',
        type: 'main',
      },
      {
        reading: '安楽死',
        kana: 'あんらくし',
        meaning: ['Euthanasia'],
        sentence: '医師として、患者が安楽死を望んでいると聞いたとき、自分の信念と向き合わなければならなかった。',
        type: 'main',
      },
      {
        reading: '死者',
        kana: 'ししゃ',
        meaning: ['Deceased person'],
        sentence: '死者の冥福を祈ります。',
        type: 'secondary',
      },
      {
        reading: '死語',
        kana: 'しご',
        meaning: ['Dead language'],
        sentence: 'この言葉は死語になってしまった。',
        type: 'secondary',
      },
    ],
  },
]