export const KANJI_YDC_LESSON_5: Array<KanjiYDC> = [
  {
    kanji: '見',
    onyomi: ['けん'],
    kunyomi: ['み'],
    meaning: ['See', 'Look'],
    examples: [
      {
        reading: '見る',
        kana: 'みる',
        meaning: ['To see', 'To look'],
        sentence: '見てください。',
        type: 'main',
      },
      {
        reading: '見せる',
        kana: 'みせる',
        meaning: ['To show'],
        sentence: '見せてください。',
        type: 'main',
      },
      {
        reading: '見える',
        kana: 'みえる',
        meaning: ['Can be seen'],
        sentence: '見えますか。',
        type: 'main',
      },
      {
        reading: '花見',
        kana: 'はなみ',
        meaning: ['Cherry blossom viewing'],
        sentence: '花見に行きます。',
        type: 'secondary',
      },
      {
        reading: '意見',
        kana: 'いけん',
        meaning: ['Opinion'],
        sentence: '意見を聞いてください。',
        type: 'secondary',
      },
      {
        reading: '見物',
        kana: 'けんぶつ',
        meaning: ['Sightseeing'],
        sentence: '見物に行きます。',
        type: 'secondary',
      },
      {
        reading: '見本',
        kana: 'みほん',
        meaning: ['Sample'],
        sentence: '見本を見てください。',
        type: 'secondary',
      },
      {
        reading: '見学',
        kana: 'けんがく',
        meaning: ['Tour (to learn)'],
        sentence: '見学に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '行',
    onyomi: ['こう', 'ぎょう', 'あん'],
    kunyomi: ['い', 'ゆ', 'おこな'],
    meaning: ['To Go'],
    examples: [
      {
        reading: '行く',
        kana: 'いく・ゆく',
        meaning: ['Power', 'Strength'],
        sentence: '力を使ってください。',
        type: 'main',
      },
      {
        reading: '行う',
        kana: 'おこなう',
        meaning: ['To do'],
        sentence: '行うことが大切です。',
        type: 'secondary',
      },
      {
        reading: '銀行',
        kana: 'ぎんこう',
        meaning: ['Bank'],
        sentence: '銀行に行きます。',
        type: 'secondary',
      },
      {
        reading: '旅行',
        kana: 'りょこう',
        meaning: ['Travel'],
        sentence: '旅行に行きます。',
        type: 'secondary',
      },
      {
        reading: '行動',
        kana: 'こうどう',
        meaning: ['Behavior'],
        sentence: '行動を見てください。',
        type: 'secondary',
      },
      {
        reading: '行事',
        kana: 'ぎょうじ',
        meaning: ['Event'],
        sentence: '行事があります。',
        type: 'secondary',
      },
      {
        reading: '一行目',
        kana: 'いちぎょうめ',
        meaning: ['First line'],
        sentence: '一行目を読んでください。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '米',
    onyomi: ['べい', 'まい'],
    kunyomi: ['こめ'],
    meaning: ['Rice'],
    examples: [
      {
        reading: 'お米',
        kana: 'おこめ',
        meaning: ['Rice'],
        sentence: 'お米を食べます。',
        type: 'main',
      },
      {
        reading: '米屋',
        kana: 'こめや',
        meaning: ['Rice shop'],
        sentence: '米屋に行きます。',
        type: 'secondary',
      },
      {
        reading: '米国',
        kana: 'べいこく',
        meaning: ['U.S.A.'],
        sentence: '米国に行きます。',
        type: 'secondary',
      },
      {
        reading: '欧米',
        kana: 'おうべい',
        meaning: ['Europe and America'],
        sentence: '欧米に行きます。',
        type: 'secondary',
      },
      {
        reading: '南米',
        kana: 'なんべい',
        meaning: ['South America'],
        sentence: '南米に行きます。',
        type: 'secondary',
      },
      {
        reading: '北米',
        kana: 'ほくべい',
        meaning: ['North America'],
        sentence: '北米に行きます。',
        type: 'secondary',
      },
      {
        reading: '新米',
        kana: 'しんまい',
        meaning: ['New rice'],
        sentence: '新米を食べます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '来',
    onyomi: ['らい'],
    kunyomi: ['く', 'き', 'こ', 'きた',],
    meaning: ['To Come'],
    examples: [
      {
        reading: '来る',
        kana: 'くる',
        meaning: ['To come'],
        sentence: '来てください。',
        type: 'main',
      },
      {
        reading: '来ない',
        kana: 'こない',
        meaning: ['Not come'],
        sentence: '来ないでください。',
        type: 'main',
      },
      {
        reading: '来年',
        kana: 'らいねん',
        meaning: ['Next year'],
        sentence: '来年はどこに行きますか。',
        type: 'main',
      },
      {
        reading: '来週',
        kana: 'らいしゅう',
        meaning: ['Next week'],
        sentence: '来週の予定はありますか。',
        type: 'main',
      },
      {
        reading: '将来',
        kana: 'しょうらい',
        meaning: ['Future'],
        sentence: '将来の夢は何ですか。',
        type: 'secondary',
      },
      {
        reading: '来学期',
        kana: 'らいがっき',
        meaning: ['Next semester'],
        sentence: '来学期はどのクラスに行きますか。',
        type: 'secondary',
      },
      {
        reading: '来る',
        kana: 'きたる',
        meaning: ['This coming...'],
        sentence: '来る日本に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '良',
    onyomi: ['りょう'],
    kunyomi: ['よ'],
    meaning: ['Good', 'Well'],
    examples: [
      {
        reading: '良い',
        kana: 'いい',
        meaning: ['Good'],
        sentence: '良いですね。',
        type: 'secondary',
      },
      {
        reading: '良心',
        kana: 'りょうしん',
        meaning: ['Conscience'],
        sentence: '良心があります。',
        type: 'secondary',
      },
      {
        reading: '不良',
        kana: 'ふりょう',
        meaning: ['Delinquent'],
        sentence: '不良がいます。',
        type: 'secondary',
      },
      {
        reading: '奈良県',
        kana: 'ならけん',
        meaning: ['Nara Prefecture'],
        sentence: '奈良県に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '食',
    onyomi: ['しょく', 'じき'],
    kunyomi: ['た', 'く'],
    meaning: ['To eat'],
    examples: [
      {
        reading: '食べる',
        kana: 'たべる',
        meaning: ['To eat'],
        sentence: '食べてください。',
        type: 'main',
      },
      {
        reading: '食べ物',
        kana: 'たべもの',
        meaning: ['Food'],
        sentence: '食べ物が好きです。',
        type: 'secondary',
      },
      {
        reading: '食堂',
        kana: 'しょくどう',
        meaning: ['Caferia'],
        sentence: '食堂に行きます。',
        type: 'secondary',
      },
      {
        reading: '食事',
        kana: 'しょくじ',
        meaning: ['Meal'],
        sentence: '食事を食べます。',
        type: 'secondary',
      },
      {
        reading: '昼食',
        kana: 'ちゅうしょく',
        meaning: ['Lunch'],
        sentence: '昼食を食べます。',
        type: 'secondary',
      },
      {
        reading: '朝食',
        kana: 'ちょうしょく',
        meaning: ['Breakfast'],
        sentence: '朝食を食べます。',
        type: 'secondary',
      },
      {
        reading: '食う',
        kana: 'くう',
        meaning: ['To eat'],
        sentence: '食うことが大切です。',
        type: 'secondary',
      },
      {
        reading: '断食',
        kana: 'だんじき',
        meaning: ['Fasting'],
        sentence: '断食をします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '飲',
    onyomi: ['いん'],
    kunyomi: ['の'],
    meaning: ['To drink'],
    examples: [
      {
        reading: '飲む',
        kana: 'のむ',
        meaning: ['To drink'],
        sentence: '飲んでください。',
        type: 'main',
      },
      {
        reading: '飲み物',
        kana: 'のみもの',
        meaning: ['Drink'],
        sentence: '飲み物が好きです。',
        type: 'secondary',
      },
      {
        reading: '飲み屋',
        kana: 'のみや',
        meaning: ['Bar'],
        sentence: '飲み屋に行きます。',
        type: 'secondary',
      },
      {
        reading: '飲み薬',
        kana: 'のみぐすり',
        meaning: ['Oral Medicine'],
        sentence: '飲み薬を飲みます。',
        type: 'secondary',
      },
      {
        reading: '飲食店',
        kana: 'いんしょくてん',
        meaning: ['Restaurant'],
        sentence: '飲食店に行きます。',
        type: 'secondary',
      },
      {
        reading: '飲酒運転',
        kana: 'いんしゅうんてん',
        meaning: ['Drunk driving'],
        sentence: '飲酒運転は危険です。',
        type: 'secondary',
      },
      {
        reading: '飲料水',
        kana: 'いんりょうすい',
        meaning: ['Drinking water'],
        sentence: '飲料水を飲みます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '会',
    onyomi: ['かい', 'え'],
    kunyomi: ['あ'],
    meaning: ['To meet'],
    examples: [
      {
        reading: '会う',
        kana: 'あう',
        meaning: ['To meet'],
        sentence: '会ってください。',
        type: 'main',
      },
      {
        reading: '会話',
        kana: 'かいわ',
        meaning: ['Conversation'],
        sentence: '会話をします。',
        type: 'main',
      },
      {
        reading: '会社',
        kana: 'かいしゃ',
        meaning: ['Company'],
        sentence: '会社に行きます。',
        type: 'secondary',
      },
      {
        reading: '会社員',
        kana: 'かいしゃいん',
        meaning: ['Company employee'],
        sentence: '会社員がいます。',
        type: 'secondary',
      },
      {
        reading: '会議',
        kana: 'かいぎ',
        meaning: ['Meeting'],
        sentence: '会議があります。',
        type: 'secondary',
      },
      {
        reading: '会場',
        kana: 'かいじょう',
        meaning: ['Meeting place'],
        sentence: '会場に行きます。',
        type: 'secondary',
      },
      {
        reading: '国会',
        kana: 'こっかい',
        meaning: ['The Diet'],
        sentence: '国会議員がいます。',
        type: 'secondary',
      },
      {
        reading: '会釈',
        kana: 'えしゃく',
        meaning: ['Bow'],
        sentence: '会釈をします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '耳',
    onyomi: ['じ'],
    kunyomi: ['みみ'],
    meaning: ['Ear'],
    examples: [
      {
        reading: '耳',
        kana: 'みみ',
        meaning: ['Ear'],
        sentence: '耳が痛いです。',
        type: 'main',
      },
      {
        reading: '耳かき',
        kana: 'みみかき',
        meaning: ['Earpick'],
        sentence: '耳かきをします。',
        type: 'secondary',
      },
      {
        reading: '耳鳴り',
        kana: 'みみなり',
        meaning: ['Ringing in the ears'],
        sentence: '耳鳴りがします。',
        type: 'secondary',
      },
      {
        reading: '耳鼻科',
        kana: 'じびか',
        meaning: ['Otolaryngology'],
        sentence: '耳鼻科に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '聞',
    onyomi: ['ぶん', 'もん'],
    kunyomi: ['き'],
    meaning: ['To hear', 'To listen'],
    examples: [ 
      {
        reading: '聞く',
        kana: 'きく',
        meaning: ['To hear', 'To listen'],
        sentence: '聞いてください。',
        type: 'main',
      },
      {
        reading: '聞こえる',
        kana: 'きこえる',
        meaning: ['Can be heard'],
        sentence: '聞こえますか。',
        type: 'main',
      },
      {
        reading: '新聞',
        kana: 'しんぶん',
        meaning: ['Newspaper'],
        sentence: '新聞を読みます。',
        type: 'secondary',
      },
      {
        reading: '聞き取る',
        kana: 'ききとる',
        meaning: ['To catch', 'To understand'],
        sentence: '聞き取ってください。',
        type: 'secondary',
      },
      {
        reading: '前代未聞',
        kana: 'ぜんだいみもん',
        meaning: ['The unheard-of'],
        sentence: '前代未聞のことです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '言',
    onyomi: ['げん', 'ごん'],
    kunyomi: ['い', 'こと'],
    meaning: ['To say'],
    examples: [
      {
        reading: '言う',
        kana: 'いう',
        meaning: ['To say'],
        sentence: '言ってください。',
        type: 'main',
      },
      {
        reading: '言葉',
        kana: 'ことば',
        meaning: ['Word'],
        sentence: '言葉を覚えます。',
        type: 'secondary',
      },
      {
        reading: '一言',
        kana: 'ひとこと',
        meaning: ['Single word'],
        sentence: '一言お願いします。',
        type: 'secondary',
      },
      {
        reading: '伝言',
        kana: 'でんごん',
        meaning: ['Message'],
        sentence: '伝言をください。',
        type: 'secondary',
      },
      {
        reading: '方言',
        kana: 'ほうげん',
        meaning: ['Dialect'],
        sentence: '方言があります。',
        type: 'secondary',
      },
      {
        reading: '予言',
        kana: 'よげん',
        meaning: ['Profecy'],
        sentence: '予言が当たりました。',
        type: 'secondary',
      },
      {
        reading: '言語学',
        kana: 'げんごがく',
        meaning: ['Linguistics'],
        sentence: '言語学を勉強します。',
        type: 'secondary',
      },
      {
        reading: '言い訳',
        kana: 'いいわけ',
        meaning: ['Excuse'],
        sentence: '言い訳をします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '話',
    onyomi: ['わ'],
    kunyomi: ['はな', 'はなし'],
    meaning: ['To speak', 'To talk'],
    examples: [
      {
        reading: '話す',
        kana: 'はなす',
        meaning: ['To speak', 'To talk'],
        sentence: '話してください。',
        type: 'main',
      },
      {
        reading: '話',
        kana: 'はなし',
        meaning: ['Story'],
        sentence: '話を聞きます。',
        type: 'main',
      },
      {
        reading: '会話',
        kana: 'かいわ',
        meaning: ['Conversation'],
        sentence: '会話をします。',
        type: 'main',
      },
      {
        reading: '電話',
        kana: 'でんわ',
        meaning: ['Telephone'],
        sentence: '電話をします。',
        type: 'secondary',
      },
      {
        reading: '世話',
        kana: 'せわ',
        meaning: ['Care'],
        sentence: '世話をします。',
        type: 'secondary',
      },
      {
        reading: '話題',
        kana: 'わだい',
        meaning: ['Topic of conversation'],
        sentence: '話題があります。',
        type: 'secondary',
      },
      {
        reading: '話し合う',
        kana: 'はなしあう',
        meaning: ['To discuss'],
        sentence: '話し合ってください。',
        type: 'secondary',
      },
      {
        reading: '手話',
        kana: 'しゅわ',
        meaning: ['Sign language'],
        sentence: '手話をします。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '立',
    onyomi: ['りつ', 'りっ', 'りゅう'],
    kunyomi: ['た', 'だ'],
    meaning: ['To stand'],
    examples: [
      {
        reading: '立つ',
        kana: 'たつ',
        meaning: ['To stand'],
        sentence: '立ってください。',
        type: 'main',
      },
      {
        reading: '役に立つ',
        kana: 'やくにたつ',
        meaning: ['To be useful'],
        sentence: '役に立ちます。',
        type: 'secondary',
      },
      {
        reading: '目立つ',
        kana: 'めだつ',
        meaning: ['To stand out'],
        sentence: '目立ちます。',
        type: 'secondary',
      },
      {
        reading: '国立大学',
        kana: 'こくりつだいがく',
        meaning: ['National university'],
        sentence: '国立大学に行きます。',
        type: 'secondary',
      },
      {
        reading: '立派',
        kana: 'りっぱ',
        meaning: ['Splendid'],
        sentence: '立派ですね。',
        type: 'secondary',
      },
      {
        reading: '建立',
        kana: 'こんりつ',
        meaning: ['Building (temples, etc)'],
        sentence: '立派ですね。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '待',
    onyomi: ['たい'],
    kunyomi: ['ま'],
    meaning: ['To wait'],
    examples: [
      {
        reading: '待つ',
        kana: 'まつ',
        meaning: ['To wait'],
        sentence: '待ってください。',
        type: 'main',
      },
      {
        reading: '招待する',
        kana: 'しょうたいする',
        meaning: ['To invite'],
        sentence: '招待してください。',
        type: 'secondary',
      },
      {
        reading: '待合室',
        kana: 'まちあいしつ',
        meaning: ['Waiting room'],
        sentence: '待合室に行きます。',
        type: 'secondary',
      },
      {
        reading: '待ち合わせる',
        kana: 'まちあわせる',
        meaning: ['To arrange to meet'],
        sentence: '待ち合わせてください。',
        type: 'secondary',
      },
      {
        reading: '期待する',
        kana: 'きたいする',
        meaning: ['To expect', 'To hope for'],
        sentence: '期待しています。',
        type: 'secondary',
      },
      {
        reading: '待望',
        kana: 'たいぼう',
        meaning: ['Long-awaited'],
        sentence: '待望の商品です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '周',
    onyomi: ['しゅう'],
    kunyomi: ['まわ'],
    meaning: ['To go Around'],
    examples: [
      {
        reading: '周り',
        kana: 'まわり',
        meaning: ['Surrounding'],
        sentence: '周りを見てください。',
        type: 'secondary',
      },
      {
        reading: '周辺',
        kana: 'しゅうへん',
        meaning: ['Surrounding'],
        sentence: '周辺を見てください。',
        type: 'secondary',
      },
      {
        reading: '周期',
        kana: 'しゅうき',
        meaning: ['Cycle'],
        sentence: '周期があります。',
        type: 'secondary',
      },
      {
        reading: '世界一周',
        kana: 'せかいいっしゅう',
        meaning: ['Around the world'],
        sentence: '世界一周に行きます。',
        type: 'secondary',
      },
      {
        reading: '一周年',
        kana: 'いっしゅうねん',
        meaning: ['One-year anniversary'],
        sentence: '一周年です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '週',
    onyomi: ['しゅう'],
    kunyomi: [],
    meaning: ['Week'],
    examples: [
      {
        reading: '今週',
        kana: 'こんしゅう',
        meaning: ['This week'],
        sentence: '今週は何をしますか。',
        type: 'main',
      },
      {
        reading: '来週',
        kana: 'らいしゅう',
        meaning: ['Next week'],
        sentence: '来週の予定はありますか。',
        type: 'main',
      },
      {
        reading: '先週',
        kana: 'せんしゅう',
        meaning: ['Last week'],
        sentence: '先週は何をしましたか。',
        type: 'main',
      },
      {
        reading: '毎週',
        kana: 'まいしゅう',
        meaning: ['Every week'],
        sentence: '毎週何をしますか。',
        type: 'main',
      },
      {
        reading: '一週間',
        kana: 'いっしゅうかん',
        meaning: ['One week'],
        sentence: '一週間です。',
        type: 'main',
      },
      {
        reading: '週末',
        kana: 'しゅうまつ',
        meaning: ['Weekend'],
        sentence: '週末は何をしますか。',
        type: 'secondary',
      },
      {
        reading: '週刊',
        kana: 'しゅうかん',
        meaning: ['Weekly　publication'],
        sentence: '週刊誌を読みます。',
        type: 'secondary',
      },
    ],
  },
]