export const KANJI_YDC_LESSON_23: Array<KanjiYDC> = [
  {
    kanji: '覚',
    onyomi: ['かく'],
    kunyomi: ['おぼ', 'さ', 'ざ'],
    meaning: ['To remember', 'To realize'],
    examples: [
      {
        reading: '覚える',
        kana: 'おぼえる',
        meaning: ['To remember', 'To learn'],
        sentence: '新しい単語を覚えるのは大変です。',
        type: 'YDC_main',
      },
      {
        reading: '感覚',
        kana: 'かんかく',
        meaning: ['Sense', 'Feeling'],
        sentence: '彼は感覚が鋭いです。',
        type: 'main',
      },
      {
        reading: '目が覚める',
        kana: 'めがさめる',
        meaning: ['To wake up'],
        sentence: '朝、目が覚めるとすでに日が昇っていました。',
        type: 'main',
      },
      {
        reading: '自覚する',
        kana: 'じかくする',
        meaning: ['To be aware of', 'To realize'],
        sentence: '自分の問題を自覚することが大切です。',
        type: 'main',
      },
      {
        reading: '味覚',
        kana: 'みかく',
        meaning: ['Taste', 'Sense of taste'],
        sentence: '味覚が敏感な人もいれば、鈍感な人もいます。',
        type: 'main',
      },
      {
        reading: '視覚',
        kana: 'しかく',
        meaning: ['Sight', 'Sense of sight'],
        sentence: '視覚障害を持つ人のための支援が必要です。',
        type: 'main',
      },
      {
        reading: '目覚まし時計',
        kana: 'めざましどけい',
        meaning: ['Alarm clock'],
        sentence: '目覚まし時計が鳴って、起きました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '忘',
    onyomi: ['ぼう'],
    kunyomi: ['わす'],
    meaning: ['To forget'],
    examples: [
      {
        reading: '忘れる',
        kana: 'わすれる',
        meaning: ['To forget'],
        sentence: '大事なことを忘れてしまいました。',
        type: 'YDC_main',
      },
      {
        reading: '忘れ物',
        kana: 'わすれもの',
        meaning: ['Forgotten item', 'Lost item'],
        sentence: '学校に忘れ物をしてしまいました。',
        type: 'YDC_main',
      },
      {
        reading: '忘れっぽい',
        kana: 'わすれっぽい',
        meaning: ['Forgetful'],
        sentence: '私は忘れっぽい性格です。',
        type: 'secondary',
      },
      {
        reading: '忘年会',
        kana: 'ぼうねんかい',
        meaning: ['Year-end party'],
        sentence: '会社の忘年会に参加しました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '決',
    onyomi: ['けつ', 'けっ'],
    kunyomi: ['き'],
    meaning: ['To decide', 'To determine'],
    examples: [
      {
        reading: '決める',
        kana: 'きめる',
        meaning: ['To decide', 'To choose'],
        sentence: '旅行の行き先を決めました。',
        type: 'YDC_main',
      },
      {
        reading: '決まる',
        kana: 'きまる',
        meaning: ['To be decided', 'To be settled'],
        sentence: '試合の結果が決まりました。',
        type: 'YDC_main',
      },
      {
        reading: '決して',
        kana: 'けっして',
        meaning: ['Never', 'By no means'],
        sentence: '彼は決して諦めない人です。',
        type: 'YDC_main',
      },
      {
        reading: '決定',
        kana: 'けってい',
        meaning: ['Decision', 'Determination'],
        sentence: '会議で重要な決定が下されました。',
        type: 'YDC_main',
      },
      {
        reading: '決心',
        kana: 'けっしん',
        meaning: ['Determination', 'Resolution'],
        sentence: '新しい目標を決心しました。',
        type: 'secondary',
      },
      {
        reading: '解決',
        kana: 'かいけつ',
        meaning: ['Solution', 'Resolution'],
        sentence: '問題を解決するために努力しています。',
        type: 'secondary',
      },
      {
        reading: '決勝',
        kana: 'けっしょう',
        meaning: ['Finals', 'Final match'],
        sentence: 'サッカーの決勝戦を観戦しました。',
        type: 'secondary',
      },
      {
        reading: '判決',
        kana: 'はんけつ',
        meaning: ['Judgment', 'Verdict'],
        sentence: '裁判所の判決が下されました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '定',
    onyomi: ['てい', 'じょう'],
    kunyomi: ['さだ'],
    meaning: ['To fix', 'To determine'],
    examples: [
      {
        reading: '予定',
        kana: 'よてい',
        meaning: ['Schedule', 'Plan'],
        sentence: '明日の予定を教えてください。',
        type: 'YDC_main',
      },
      {
        reading: '定休日',
        kana: 'ていきゅうび',
        meaning: ['Holiday (of a store)'],
        sentence: 'この店は毎週水曜日が定休日です。',
        type: 'YDC_main',
      },
      {
        reading: '決定',
        kana: 'けってい',
        meaning: ['Decision', 'Determination'],
        sentence: '会議で重要な決定が下されました。',
        type: 'YDC_main',
      },
      {
        reading: '肯定する',
        kana: 'こうていする',
        meaning: ['To approve', 'To agree'],
        sentence: '彼の意見に肯定的な返事をしました。',
        type: 'main',
      },
      {
        reading: '否定する',
        kana: 'ひていする',
        meaning: ['To deny', 'To negate'],
        sentence: '彼はその事実を否定しました。',
        type: 'main',
      },
      {
        reading: '勘定',
        kana: 'かんじょう',
        meaning: ['Calculation', 'Bill'],
        sentence: 'レストランで勘定を済ませました。',
        type: 'secondary',
      },
      {
        reading: '定期券',
        kana: 'ていきけん',
        meaning: ['Commuter pass'],
        sentence: '定期券を買いました。',
        type: 'main',
      },
      {
        reading: '定める',
        kana: 'さだめる',
        meaning: ['To set', 'To fix'],
        sentence: 'ルールを定めることが大切です。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '比',
    onyomi: ['ひ'],
    kunyomi: ['くら'],
    meaning: ['To compare'],
    examples: [
      {
        reading: '比べる',
        kana: 'くらべる',
        meaning: ['To compare'],
        sentence: '二つの製品を比べてみました。',
        type: 'YDC_main',
      },
      {
        reading: '比較',
        kana: 'ひかく',
        meaning: ['Comparison'],
        sentence: 'このデータを他の研究と比較しました。',
        type: 'secondary',
      },
      {
        reading: '比較的',
        kana: 'ひかくてき',
        meaning: ['Comparatively'],
        sentence: 'この問題は比較的簡単です。',
        type: 'secondary',
      },
      {
        reading: '対比',
        kana: 'たいひ',
        meaning: ['Contrast', 'Comparison'],
        sentence: '二つの文化を対比して考えました。',
        type: 'secondary',
      },
      {
        reading: '比例',
        kana: 'ひれい',
        meaning: ['Proportion', 'Ratio'],
        sentence: '収入は支出に比例して増えます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '受',
    onyomi: ['じゅ'],
    kunyomi: ['う'],
    meaning: ['To receive'],
    examples: [
      {
        reading: '受ける',
        kana: 'うける',
        meaning: ['To receive', 'To take (a test)'],
        sentence: '試験を受けるために勉強しています。',
        type: 'YDC_main',
      },
      {
        reading: '受付',
        kana: 'うけつけ',
        meaning: ['Reception', 'Front desk'],
        sentence: 'ホテルの受付でチェックインしました。',
        type: 'YDC_main',
      },
      {
        reading: '受験',
        kana: 'じゅけん',
        meaning: ['Taking an exam'],
        sentence: '大学の受験を控えています。',
        type: 'YDC_main',
      },
      {
        reading: '受け取る',  
        kana: 'うけとる',
        meaning: ['To receive', 'To accept'],
        sentence: '荷物を受け取るために郵便局に行きました。',
        type: 'main',
      },
      {
        reading: '受かる',
        kana: 'うかる',
        meaning: ['To pass (an exam)'],
        sentence: '試験に受かるために一生懸命勉強しました。',
        type: 'main',
      },
      {
        reading: '受け身',
        kana: 'うけみ',
        meaning: ['Passive voice', 'Receptive'],
        sentence: '受け身の態度では成功しません。',
        type: 'secondary',
      },
      {
        reading: '受信',
        kana: 'じゅしん',
        meaning: ['Receiving (a message)'],
        sentence: 'メールの受信を確認しました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '授',
    onyomi: ['じゅ'],
    kunyomi: ['さず'],
    meaning: ['To instruct'],
    examples: [
      {
        reading: '授業',  
        kana: 'じゅぎょう',
        meaning: ['Class', 'Lesson'],
        sentence: '今日の授業はとても面白かったです。',
        type: 'YDC_main',
      },
      {
        reading: '教授',
        kana: 'きょうじゅ',
        meaning: ['Professor', 'Instructor'],
        sentence: '大学の教授に質問しました。',
        type: 'YDC_main',
      },
      {
        reading: '授業料',
        kana: 'じゅぎょうりょう',
        meaning: ['Tuition fee'],
        sentence: '授業料を支払うのを忘れないでください。',
        type: 'YDC_main',
      },
      {
        reading: '授ける',
        kana: 'さずける',
        meaning: ['To give', 'To grant'],
        sentence: '先生は知識を授けてくれました。',
        type: 'main',
      },
      {
        reading: '授かる',
        kana: 'さずかる',
        meaning: ['To be given', 'To receive'],
        sentence: '子供を授かることはとても幸せなことです。',
        type: 'main',
      },
      {
        reading: '授受',
        kana: 'じゅじゅ',
        meaning: ['Giving and receiving'],
        sentence: '授受の関係は大切にしなければなりません。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '徒',
    onyomi: ['と'],
    kunyomi: [],
    meaning: ['Fellower'],
    examples: [
      {
        reading: '生徒',  
        kana: 'せいと',
        meaning: ['Student', 'Pupil'],
        sentence: '彼は優秀な生徒です。',
        type: 'YDC_main',
      },
      {
        reading: '徒歩で',
        kana: 'とほで',
        meaning: ['On foot'],
        sentence: '駅まで徒歩で行きました。',
        type: 'main',
      },
      {
        reading: 'イスラム教徒',
        kana: 'イスラムきょうと',
        meaning: ['Muslim'],
        sentence: '彼はイスラム教徒です。',
        type: 'secondary',
      },
      {
        reading: 'クリスト教徒',
        kana: 'クリストきょうと',
        meaning: ['Christian'],
        sentence: '彼女はクリスト教徒で、毎週日曜日に教会に行きます。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '練',
    onyomi: ['れん'],
    kunyomi: ['ね'],
    meaning: ['To elaborate'],
    examples: [
      {
        reading: '練習',
        kana: 'れんしゅう',
        meaning: ['Practice', 'Training'],
        sentence: '毎日ピアノの練習をしています。',
        type: 'YDC_main',
      },
      {
        reading: '訓練',
        kana: 'くんれん',
        meaning: ['Training (for skills) (e.g. army, sports)'],
        sentence: '消防士は定期的に訓練を受けます。',
        type: 'main',
      },
      {
        reading: '練る',
        kana: 'ねる',
        meaning: ['To knead', 'To elaborate'],
        sentence: '生地をよく練ってから焼きます。',
        type: 'main',
      },
      {
        reading: '試練',
        kana: 'しれん',
        meaning: ['Trial', 'Test'],
        sentence: '人生には多くの試練があります。',
        type: 'secondary',
      },
      {
        reading: '洗練',
        kana: 'せんれん',
        meaning: ['Refinement', 'Polish'],
        sentence: '彼女のファッションセンスは洗練されています。',
        type: 'secondary',
      },
      {
        reading: '未練',
        kana: 'みれん',
        meaning: ['Lingering ttachment', 'Regret'],
        sentence: '彼との未練を断ち切るのは難しいです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '復',
    onyomi: ['ふく', 'ふっ'],
    kunyomi: ['ぷく'],
    meaning: ['To return'],
    examples: [
      {
        reading: '復習',
        kana: 'ふくしゅう',
        meaning: ['Review', 'Revision'],
        sentence: '授業の内容を復習しました。',
        type: 'YDC_main',
      },
      {
        reading: '回復',
        kana: 'かいふく',
        meaning: ['Recovery', 'Restoration'],
        sentence: '病気からの回復には時間がかかります。',
        type: 'YDC_main',
      },
      {
        reading: '往復',
        kana: 'おうふく',
        meaning: ['Round trip'],
        sentence: '東京と大阪の往復切符を買いました。',
        type: 'main',
      },
      {
        reading: '復旧',
        kana: 'ふっきゅう',
        meaning: ['Restoration', 'Retrieval'],
        sentence: '地震の後、インフラの復旧が急がれています。',
        type: 'secondary',
      },
      {
        reading: '復興',
        kana: 'ふっこう',
        meaning: ['Reconstruction'],
        sentence: '被災地の復興が進んでいます。',
        type: 'secondary',
      },
      {
        reading: '復活',
        kana: 'ふっかつ',
        meaning: ['Resurrection', 'Revival'],
        sentence: 'この祭りは毎年復活します。',
        type: 'secondary',
      },
      {
        reading: '反復',
        kana: 'はんぷく',
        meaning: ['Repetition'],
        sentence: '反復練習が上達の鍵です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '表',
    onyomi: ['ひょう', 'ぴょう'],
    kunyomi: ['あらわ', 'おもて'],
    meaning: ['To express', 'Surface'],
    examples: [
      {
        reading: '表',
        kana: 'ひょう',
        meaning: ['Table', 'Chart'],
        sentence: 'データを表にまとめました。',
        type: 'YDC_main',
      },
      {
        reading: '表',
        kana: 'おもて',
        meaning: ['Surface', 'Front'],
        sentence: 'この箱の表に名前を書いてください。',
        type: 'YDC_main',
      },
      {
        reading: '発表',
        kana: 'はっぴょう',
        meaning: ['Presentation', 'Announcement'],
        sentence: '明日の会議で新しいプロジェクトを発表します。',
        type: 'YDC_main',
      },
      {
        reading: '表す',
        kana: 'あらわす',
        meaning: ['To express', 'To represent'],
        sentence: '彼の笑顔は喜びを表しています。',
        type: 'YDC_main',
      },
      {
        reading: '表紙',
        kana: 'ひょうし',
        meaning: ['Cover page (of a book)'],
        sentence: 'この本の表紙はとても美しいです。',
        type: 'main',
      },
      {
        reading: '代表',
        kana: 'だいひょう',
        meaning: ['Representative'],
        sentence: '彼は会社の代表として会議に出席しました。',
        type: 'secondary',
      },
      {
        reading: '表情',
        kana: 'ひょうじょう',
        meaning: ['Facial expression'],
        sentence: '彼女の表情から、彼女の気持ちがわかりました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '卒',
    onyomi: ['そつ'],
    kunyomi: [],
    meaning: ['To graduate'],
    examples: [
      {
        reading: '卒業',
        kana: 'そつぎょう',
        meaning: ['Graduation'],
        sentence: '大学を卒業しました。',
        type: 'YDC_main',
      },
      {
        reading: '卒業式',
        kana: 'そつぎょうしき',
        meaning: ['Graduation ceremony'],
        sentence: '卒業式は来週の土曜日です。',
        type: 'YDC_main',
      },
      {
        reading: '卒業生',
        kana: 'そつぎょうせい',
        meaning: ['Graduate'],
        sentence: '彼は昨年の卒業生です。',
        type: 'YDC_main',
      },
      {
        reading: '大卒',
        kana: 'だいそつ',
        meaning: ['University graduate'],
        sentence: '彼は大卒で、今は会社員です。',
        type: 'main',
      },
      {
        reading: '卒論',
        kana: 'そつろん',
        meaning: ['Graduation thesis'],
        sentence: '卒論のテーマを決めるのに苦労しました。',
        type: 'secondary',
      },
      {
        reading: '新卒',
        kana: 'しんそつ',
        meaning: ['New graduate'],
        sentence: '新卒の社員が入社しました。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '違',
    onyomi: ['い'],
    kunyomi: ['ちが'],
    meaning: ['To differ'],
    examples: [
      {
        reading: '違う',
        kana: 'ちがう',
        meaning: ['To differ', 'To be wrong'],
        sentence: 'あなたの意見は私と違います。',
        type: 'YDC_main',
      },
      {
        reading: '間違える',
        kana: 'まちがえる',
        meaning: ['To make a mistake'],
        sentence: '計算を間違えてしまいました。',
        type: 'YDC_main',
      },
      {
        reading: '違い',
        kana: 'ちがい',
        meaning: ['Difference'],
        sentence: 'この二つの製品の違いは何ですか？',
        type: 'YDC_main',
      },
      {
        reading: '間違い',
        kana: 'まちがい',
        meaning: ['Mistake', 'Error'],
        sentence: '間違いを見つけて、訂正しました。',
        type: 'YDC_main',
      },
      {
        reading: '違反',
        kana: 'いはん',
        meaning: ['Violation', 'Breach'],
        sentence: '交通違反で警察に捕まりました。',
        type: 'secondary',
      },
      {
        reading: '勘違い',
        kana: 'かんちがい',
        meaning: ['Misunderstanding', 'Mistake'],
        sentence: '彼の言葉を勘違いしてしまいました。',
        type: 'secondary',
      },
      {
        reading: '相違',
        kana: 'そうい',
        meaning: ['Difference', 'Discrepancy'],
        sentence: '二つの報告書には相違があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '役',
    onyomi: ['やく', 'えき'],
    kunyomi: [],
    meaning: ['Duty'],
    examples: [
      {
        reading: '役に立つ',
        kana: 'やくにたつ',
        meaning: ['To be useful', 'To be helpful'],
        sentence: 'この情報は役に立ちます。',
        type: 'YDC_main',
      },
      {
        reading: '市役所',
        kana: 'しやくしょ',
        meaning: ['City hall'],
        sentence: '市役所で住民票を取得しました。',
        type: 'YDC_main',
      },
      {
        reading: '役目',
        kana: 'やくめ',
        meaning: ['Role', 'Duty'],
        sentence: '彼の役目はチームをまとめることです。',
        type: 'main',
      },
      {
        reading: '役者',
        kana: 'やくしゃ',
        meaning: ['Actor', 'Actress'],
        sentence: '彼は有名な役者です。',
        type: 'main',
      },
      {
        reading: '役',
        kana: 'やく',
        meaning: ['Role', 'Part (in a play)'],
        sentence: 'この映画で彼は重要な役を演じています。',
        type: 'main',
      },
      {
        reading: '主役',
        kana: 'しゅやく',
        meaning: ['Leading role', 'Main character'],
        sentence: '彼女はこのドラマの主役です。',
        type: 'main',
      },
      {
        reading: '兵役',
        kana: 'へいえき',
        meaning: ['Military service'],
        sentence: '彼は兵役に就いています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '皆',
    onyomi: ['かい'],
    kunyomi: ['みな'],
    meaning: ['Everyone', 'All'],
    examples: [
      {
        reading: '皆さん',
        kana: 'みなさん',
        meaning: ['Everbody'],
        sentence: '皆さん、こんにちは！',
        type: 'YDC_main',
      },
      {
        reading: '皆',
        kana: 'みな',
        meaning: ['All'],
        sentence: '皆でパーティーを楽しみました。',
        type: 'YDC_main',
      },
      {
        reading: '皆勤',
        kana: 'かいきん',
        meaning: ['Full attendance'],
        sentence: '彼は学校を皆勤賞で卒業しました。',
        type: 'main',
      },
      {
        reading: '皆目',
        kana: 'かいもく',
        meaning: ['Not at all', 'Not in the least'],
        sentence: '皆目わからないことばかりです。',
        type: 'main',
      },
      {
        reading: '皆無',
        kana: 'かいむ',
        meaning: ['None', 'Nothing at all'],
        sentence: '彼の助けは皆無でした。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '彼',
    onyomi: ['ひ'],
    kunyomi: ['かれ', 'かの'],
    meaning: ['He', 'Boyfriend'],
    examples: [
      {
        reading: '彼',
        kana: 'かれ',
        meaning: ['He', 'Boyfriend'],
        sentence: '彼は私の親友です。',
        type: 'YDC_main',
      },
      {
        reading: '彼ら',
        kana: 'かれら',
        meaning: ['They', 'Them'],
        sentence: '彼らは一緒に旅行に行きました。',
        type: 'YDC_main',
      },
      {
        reading: '彼女',
        kana: 'かのじょ',
        meaning: ['She', 'Girlfriend'],
        sentence: '彼女はとても優しい人です。',
        type: 'YDC_main',
      },
      {
        reading: '彼氏',
        kana: 'かれし',
        meaning: ['Boyfriend'],
        sentence: '彼氏とデートに行きました。',
        type: 'main',
      },
      {
        reading: '彼岸',
        kana: 'ひがん',
        meaning: ['Equinoctial day', 'The other side (of life)'],
        sentence: '彼岸の時期にはお墓参りをします。',
        type: 'secondary',
      },
    ],
  },
]