export const KANJI_YDC_LESSON_18: Array<KanjiYDC> = [
  {
    kanji: '図',
    onyomi: ['ず', 'と'],
    kunyomi: ['はか'],
    meaning: ['Drawing'],
    examples: [
      {
        reading: '地図',
        kana: 'ちず',
        meaning: ['Map'],
        sentence: '旅行に行く前に、地図を確認しておきます。',
        type: 'main',
      },
      {
        reading: '図書館',
        kana: 'としょかん',
        meaning: ['Library'],
        sentence: '図書館で本を借りてきました。',
        type: 'main',
      },
      {
        reading: '図',
        kana: 'ず',
        meaning: ['Chart', 'Diagram'],
        sentence: 'この図は、データを視覚的に表現しています。',
        type: 'main',
      },
      {
        reading: '図表',
        kana: 'ずひょう',
        meaning: ['Figures and diagrams'],
        sentence: '図表を使って、データをわかりやすく説明します。',
        type: 'secondary',
      },
      {
        reading: '合図',
        kana: 'あいず',
        meaning: ['Signal', 'Sign'],
        sentence: '合図を送って、みんなに集まるように伝えました。',
        type: 'main',
      },
      {
        reading: '意図',
        kana: 'いと',
        meaning: ['Intention', 'Purpose'],
        sentence: '彼の意図を理解するのは難しいです。',
        type: 'main',
      },
      {
        reading: '図る',
        kana: 'はかる',
        meaning: ['To plot', 'To attempt'],
        sentence: '新しいプロジェクトを図るために、会議を開きました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '官',
    onyomi: ['かん'],
    kunyomi: [],
    meaning: ['Government official'],
    examples: [
      {
        reading: '長官',
        kana: 'ちょうかん',
        meaning: ['Director-general'],
        sentence: '長官は会議で重要な発表をしました。',
        type: 'main',
      },
      {
        reading: '外交官',
        kana: 'がいこうかん',
        meaning: ['Diplomat'],
        sentence: '外交官は国と国との関係を築く役割を担っています。',
        type: 'secondary',
      },
      {
        reading: '警官',
        kana: 'けいかん',
        meaning: ['Police officer'],
        sentence: '警官が交通整理をしていました。',
        type: 'secondary',
      },
      {
        reading: '裁判官',
        kana: 'さいばんかん',
        meaning: ['Judge'],
        sentence: '裁判官は公正な判断を下すことが求められます。',
        type: 'secondary',
      },
      {
        reading: '官庁',
        kana: 'かんちょう',
        meaning: ['Government office'],
        sentence: '官庁は国の政策を実行する機関です。',
        type: 'secondary',
      },
      {
        reading: '官僚',
        kana: 'かんりょう',
        meaning: ['Government official'],
        sentence: '官僚は政策の立案や実行に関与します。',
        type: 'secondary',
      },
      {
        reading: '器官',
        kana: 'きかん',
        meaning: ['Organ'],
        sentence: '人間の体には多くの器官があります。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '館',
    onyomi: ['かん'],
    kunyomi: ['やかた'],
    meaning: ['Building'],
    examples: [
      {
        reading: '映画館',
        kana: 'えいがかん',
        meaning: ['Movie theater'],
        sentence: '映画館で新作映画を観ました。',
        type: 'main',
      },
      {
        reading: '大使館',
        kana: 'たいしかん',
        meaning: ['Embassy'],
        sentence: '大使館でビザの申請をしました。',
        type: 'main',
      },
      {
        reading: '旅館',
        kana: 'りょかん',
        meaning: ['Japanese inn'],
        sentence: '旅館で温泉に入ってリラックスしました。',
        type: 'secondary',
      },
      {
        reading: '会館',
        kana: 'かいかん',
        meaning: ['Hall'],
        sentence: '会館でコンサートが開かれます。',
        type: 'main',
      },
      {
        reading: '美術館',
        kana: 'びじゅつかん',
        meaning: ['Art museum'],
        sentence: '美術館で絵画を鑑賞しました。',
        type: 'secondary',
      },
      {
        reading: '博物館',
        kana: 'はくぶつかん',
        meaning: ['Museum'],
        sentence: '博物館で歴史的な展示を見学しました。',
        type: 'secondary',
      },
      {
        reading: '水族館',
        kana: 'すいぞくかん',
        meaning: ['Aquarium'],
        sentence: '水族館で色とりどりの魚を見ました。',
        type: 'main',
      },
      {
        reading: '占いの館',
        kana: 'うらないのやかた',
        meaning: ['Fortune-telling house'],
        sentence: '占いの館で未来を占ってもらいました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '昔',
    onyomi: ['せき', 'しゃく', 'じゃく'],
    kunyomi: ['むかし'],
    meaning: ['Long ago'],
    examples: [
      {
        reading: '昔',
        kana: 'むかし',
        meaning: ['Long ago'],
        sentence: '昔、遠い国に美しい姫がいました。',
        type: 'main',
      },
      {
        reading: '昔話',
        kana: 'むかしばなし',
        meaning: ['Old tale'],
        sentence: '昔話を聞くのが好きです。',
        type: 'main',
      },
      {
        reading: '大昔',
        kana: 'おおむかし',
        meaning: ['Long, long ago', 'Ancient times'],
        sentence: '大昔の人々は、どのように生活していたのでしょうか。',
        type: 'secondary',
      },
      {
        reading: '昔日',
        kana: 'せきじつ',
        meaning: ['Old days'],
        sentence: '昔日を懐かしむ人が多いです。',
        type: 'secondary',
      },
      {
        reading: '昔々',
        kana: 'むかしむかし',
        meaning: ['Once upon a time'],
        sentence: '昔々、あるところにおじいさんとおばあさんがいました。',
        type: 'main',
      },
      {
        reading: '今昔',
        kana: 'こんじゃく',
        meaning: ['The changing times'],
        sentence: '今昔物語は、日本の古典文学の一つです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '借',
    onyomi: ['しゃく', 'しゃっ'],
    kunyomi: ['か'],
    meaning: ['Borrow'],
    examples: [
      {
        reading: '借りる',
        kana: 'かりる',
        meaning: ['To borrow'],
        sentence: '友達から本を借りました。',
        type: 'main',
      },
      {
        reading: '借家',
        kana: 'しゃくや',
        meaning: ['Rented house'],
        sentence: '借家に住んでいるので、家賃を払っています。',
        type: 'main',
      },
      {
        reading: '借金',
        kana: 'しゃっきん',
        meaning: ['Debt'],
        sentence: '借金を返すために、働いています。',
        type: 'main',
      },
      {
        reading: '借地',
        kana: 'しゃくち',
        meaning: ['Leased land'],
        sentence: '借地に家を建てることができます。',
        type: 'main',
      },
      {
        reading: '貸し借り',
        kana: 'かしかり',
        meaning: ['Lending and borrowing'],
        sentence: '貸し借りは、信頼関係が大切です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '代',
    onyomi: ['だい', 'たい'],
    kunyomi: ['か', 'しろ', 'よ'],
    meaning: ['Age', 'To replace'],
    examples: [
      {
        reading: '時代',
        kana: 'じだい',
        meaning: ['Era', 'Period'],
        sentence: 'この時代の文化はとても興味深いです。',
        type: 'main',
      },
      {
        reading: '電気代',
        kana: 'でんきだい',
        meaning: ['Electricity bill'],
        sentence: '今月の電気代は高かったです。',
        type: 'main',
      },
      {
        reading: '代わりに',
        kana: 'かわりに',
        meaning: ['Instead of'],
        sentence: '彼は私の代わりに会議に出席しました。',
        type: 'main',
      },
      {
        reading: '六十年代',
        kana: 'ろくじゅうねんだい',
        meaning: ['60s'],
        sentence: '六十年代の音楽は、今でも人気があります。',
        type: 'secondary',
      },
      {
        reading: '十代',
        kana: 'じゅうだい',
        meaning: ['Teenage years'],
        sentence: '十代の頃は、夢を追いかけていました。',
        type: 'secondary',
      },
      {
        reading: '代表',
        kana: 'だいひょう',
        meaning: ['Representative'],
        sentence: '彼は会社の代表として会議に出席しました。',
        type: 'secondary',
      },
      {
        reading: '現代',
        kana: 'げんだい',
        meaning: ['Modern times'],
        sentence: '現代の技術は、私たちの生活を便利にしています。',
        type: 'secondary',
      },
      {
        reading: '代金',
        kana: 'だいきん',
        meaning: ['Price', 'Charge'],
        sentence: '代金は後で支払います。',
        type: 'secondary',
      },
      {
        reading: '身代金',
        kana: 'みのしろきん',
        meaning: ['Ransom'],
        sentence: '誘拐された人質の身代金が要求されました。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '貸',
    onyomi: ['たい'],
    kunyomi: ['か'],
    meaning: ['Lend'],
    examples: [
      {
        reading: '貸す',  
        kana: 'かす',
        meaning: ['To lend'],
        sentence: '友達に本を貸しました。',
        type: 'main',
      },
      {
        reading: '貸し出し',
        kana: 'かしだし',
        meaning: ['Lending out'],
        sentence: '図書館で本の貸し出しを行っています。',
        type: 'main',
      },
      {
        reading: '貸切',
        kana: 'かしきり',
        meaning: ['Reserved'],
        sentence: 'この部屋は貸切です。',
        type: 'main',
      },
      {
        reading: '賃貸マンション',
        kana: 'ちんたいマンション',
        meaning: ['Apartment for rent'],
        sentence: '賃貸マンションを探しています。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '地',
    onyomi: ['ち', 'じ'],
    kunyomi: [],
    meaning: ['Land'],
    examples: [
      {
        reading: '地理',  
        kana: 'ちり',
        meaning: ['Geography'],
        sentence: '地理の授業で世界の国々を学びました。',
        type: 'main',
      },
      {
        reading: '地下',
        kana: 'ちか',
        meaning: ['Underground'],
        sentence: '地下鉄は便利な交通手段です。',
        type: 'main',
      },
      {
        reading: '地下鉄',
        kana: 'ちかてつ',
        meaning: ['Subway'],
        sentence: '地下鉄で駅まで行きます。',
        type: 'main',
      },
      {
        reading: '地震',
        kana: 'じしん',
        meaning: ['Earthquake'],
        sentence: '地震が起きたとき、すぐに避難しました。',
        type: 'main',
      },
      {
        reading: '意地悪な',
        kana: 'いじわるな',
        meaning: ['Mean-spirited'],
        sentence: '彼は意地悪なことを言う人です。',
        type: 'secondary',
      },
      {
        reading: '地方',
        kana: 'ちほう',
        meaning: ['Region', 'Countryside'],
        sentence: '地方の特産品を買いました。',
        type: 'secondary',
      },
      {
        reading: '地球',
        kana: 'ちきゅう',
        meaning: ['Earth'],
        sentence: '地球は太陽系の惑星の一つです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '世',
    onyomi: ['せ', 'せい'],
    kunyomi: ['よ'],
    meaning: ['World'],
    examples: [
      {
        reading: '世界',
        kana: 'せかい',
        meaning: ['World'],
        sentence: '世界中の人々が集まるイベントです。',
        type: 'main',
      },
      {
        reading: '世話',
        kana: 'せわ',
        meaning: ['Care', 'Assistance'],
        sentence: '彼は高齢者の世話をしています。',
        type: 'main',
      },
      {
        reading: '世紀',
        kana: 'せいき',
        meaning: ['Century'],
        sentence: '21世紀は、技術の進化が著しい時代です。',
        type: 'main',
      },
      {
        reading: '世間',
        kana: 'せけん',
        meaning: ['Society', 'Public'],
        sentence: '世間の目を気にせずに、自分らしく生きたいです。',
        type: 'main',
      },
      {
        reading: '世代',
        kana: 'せだい',
        meaning: ['Generation'],
        sentence: '世代を超えた交流が大切です。',
        type: 'main',
      },
      {
        reading: '世の中',
        kana: 'よのなか',
        meaning: ['The world', 'Society'],
        sentence: '世の中には様々な人がいます。',
        type: 'main',
      },
      {
        reading: '世論',
        kana: 'せろん・よろん',
        meaning: ['Public opinion'],
        sentence: '世論を反映した政策が求められています。',
        type: 'main',
      },
      {
        reading: 'お世辞',
        kana: 'おせじ',
        meaning: ['Flattery'],
        sentence: 'お世辞を言うのは苦手です。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '界',
    onyomi: ['かい'],
    kunyomi: [],
    meaning: ['Boundary'],
    examples: [
      {
        reading: '世界',
        kana: 'せかい',
        meaning: ['World'],
        sentence: '世界中の人々が集まるイベントです。',
        type: 'main',
      },
      {
        reading: '限界',
        kana: 'げんかい',
        meaning: ['Limit'],
        sentence: '自分の限界を超えることが大切です。',
        type: 'secondary',
      },
      {
        reading: '境界',
        kana: 'きょうかい',
        meaning: ['Boundary'],
        sentence: '国と国の境界線があります。',
        type: 'secondary',
      },
      {
        reading: '政界',
        kana: 'せいかい',
        meaning: ['Political world'],
        sentence: '政界の動向に注目しています。',
        type: 'secondary',
      },
      {
        reading: '視界',
        kana: 'しかい',
        meaning: ['Field of vision', 'Visibility'],
        sentence: '霧で視界が悪くなっています。',
        type: 'main',
      },
      {
        reading: '業界',
        kana: 'ぎょうかい',
        meaning: ['Industry'],
        sentence: 'この業界は競争が激しいです。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '度',
    onyomi: ['ど', 'と', 'たく'],
    kunyomi: ['たび'],
    meaning: ['Degrees', 'Times'],
    examples: [
      {
        reading: '一度',
        kana: 'いちど',
        meaning: ['Once'],
        sentence: '一度行ってみたい場所です。',
        type: 'main',
      },
      {
        reading: '今度',
        kana: 'こんど',
        meaning: ['Next time'],
        sentence: '今度の週末に遊びに行きます。',
        type: 'main',
      },
      {
        reading: '三十度',
        kana: 'さんじゅうど',
        meaning: ['Thirty degrees'],
        sentence: '今日は三十度の暑さです。',
        type: 'main',
      },
      {
        reading: '温度',
        kana: 'おんど',
        meaning: ['Temperature'],
        sentence: '温度が高くなると、氷が溶けます。',
        type: 'main',
      },
      {
        reading: '度々',
        kana: 'たびたび',
        meaning: ['Repeatedly', 'Often'],
        sentence: '度々お世話になっています。',
        type: 'main',
      },
      {
        reading: '支度する',
        kana: 'したくする',
        meaning: ['To prepare'],
        sentence: '旅行の支度をしています。',
        type: 'secondary',
      },
      {
        reading: '速度',
        kana: 'そくど',
        meaning: ['Speed'],
        sentence: '車の速度を落として運転してください。',
        type: 'main',
      },
      {
        reading: '限度',
        kana: 'げんど',
        meaning: ['Limit'],
        sentence: '限度を超えないように注意してください。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '回',
    onyomi: ['かい', 'え'],
    kunyomi: ['まわ'],
    meaning: ['Times', 'To turn around'],
    examples: [
      {
        reading: '一回',
        kana: 'いっかい',
        meaning: ['Once'],
        sentence: '一回だけのチャンスです。',
        type: 'main',
      },
      {
        reading: '何回',
        kana: 'なんかい',
        meaning: ['How many times'],
        sentence: '何回も同じことを言わないでください。',
        type: 'main',
      },
      {
        reading: '回る',
        kana: 'まわる',
        meaning: ['To turn', 'To revolve'],
        sentence: '地球は太陽の周りを回っています。',
        type: 'main',
      },
      {
        reading: '回数券',
        kana: 'かいすうけん',
        meaning: ['Coupon tickets'],
        sentence: '回数券を買うと、少しお得です。',
        type: 'secondary',
      },
      {
        reading: '今回',
        kana: 'こんかい',
        meaning: ['This time'],
        sentence: '今回のイベントは特別です。',
        type: 'main',
      },
      {
        reading: '回答',
        kana: 'かいとう',
        meaning: ['Answer', 'Response'],
        sentence: '質問に対する回答を考えています。',
        type: 'secondary',
      },
      {
        reading: '回復',
        kana: 'かいふく',
        meaning: ['Recovery'],
        sentence: '体調が回復してきました。',
        type: 'secondary',
      },
      {
        reading: '回転',
        kana: 'かいてん',
        meaning: ['Rotation'],
        sentence: '回転寿司は楽しい食事スタイルです。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '用',
    onyomi: ['よう'],
    kunyomi: ['もち'],
    meaning: ['Use'],
    examples: [
      {
        reading: '用事',
        kana: 'ようじ',
        meaning: ['Errand', 'Business'],
        sentence: '今日は用事があるので、行けません。',
        type: 'main',
      },
      {
        reading: '用意する',
        kana: 'よういする',
        meaning: ['To prepare'],
        sentence: '旅行のために用意をしています。',
        type: 'main',
      },
      {
        reading: '利用する',
        kana: 'りようする',
        meaning: ['To utilize'],
        sentence: 'このサービスを利用するには、登録が必要です。',
        type: 'secondary',
      },
      {
        reading: '用語',
        kana: 'ようご',
        meaning: ['Techinical term'],
        sentence: '専門用語を理解するのは難しいです。',
        type: 'secondary',
      },
      {
        reading: '用紙',
        kana: 'ようし',
        meaning: ['Form', 'Sheet'],
        sentence: '申請用紙に必要事項を記入してください。',
        type: 'main',
      },
      {
        reading: '使用する',
        kana: 'しようする',
        meaning: ['To use'],
        sentence: 'このアプリを使用するには、インターネット接続が必要です。',
        type: 'secondary',
      },
      {
        reading: '費用',
        kana: 'ひよう',
        meaning: ['Cost', 'Expense'],
        sentence: '旅行の費用を計算しています。',
        type: 'secondary',
      },
      {
        reading: '用いる',
        kana: 'もちいる',
        meaning: ['To use'],
        sentence: 'この方法を用いて問題を解決します。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '民',
    onyomi: ['みん'],
    kunyomi: ['たみ'],
    meaning: ['People'],
    examples: [
      {
        reading: '市民',
        kana: 'しみん',
        meaning: ['Citizen'],
        sentence: '市民としての義務を果たすことが大切です。',
        type: 'main',
      },
      {
        reading: '国民',
        kana: 'こくみん',
        meaning: ['Nationals', 'Citizens'],
        sentence: '国民の権利を守ることが重要です。',
        type: 'main',
      },
      {
        reading: '住民',
        kana: 'じゅうみん',
        meaning: ['Resident'],
        sentence: '住民の意見を聞くことが大切です。',
        type: 'main',
      },
      {
        reading: '民主主義',
        kana: 'みんしゅしゅぎ',
        meaning: ['Democracy'],
        sentence: '民主主義は国民の意志を反映する政治体制です。',
        type: 'secondary',
      },
      {
        reading: '民族',
        kana: 'みんぞく',
        meaning: ['Ethnic group'],
        sentence: '民族の多様性を尊重することが大切です。',
        type: 'secondary',
      },
      {
        reading: '難民',
        kana: 'なんみん',
        meaning: ['Refugee'],
        sentence: '難民の支援が必要です。',
        type: 'secondary',
      },
      {
        reading: '民',
        kana: 'たみ',
        meaning: ['People'],
        sentence: '民の声を大切にする政治が求められています。',
        type: 'main',
      },
      {
        reading: '民間',
        kana: 'みんかん',
        meaning: ['Private', 'Civilian'],
        sentence: '民間企業が新しい技術を開発しています。',
        type: 'secondary',
      },
    ],
  },
  {
    kanji: '注',
    onyomi: ['ちゅう'],
    kunyomi: ['そそ'],
    meaning: ['To pour'],
    examples: [
      {
        reading: '注意する',
        kana: 'ちゅういする',
        meaning: ['To be careful', 'To watch out'],
        sentence: '運転中は注意してください。',
        type: 'main',
      },
      {
        reading: '注文する',
        kana: 'ちゅうもんする',
        meaning: ['To order'],
        sentence: 'レストランで料理を注文しました。',
        type: 'main',
      },
      {
        reading: '注射',
        kana: 'ちゅうしゃ',
        meaning: ['Injection'],
        sentence: '注射を受けるのは少し怖いです。',
        type: 'secondary',
      },
      {
        reading: '注目',
        kana: 'ちゅうもく',
        meaning: ['Attention'],
        sentence: '注目のイベントが開催されます。',
        type: 'main',
      },
      {
        reading: '発注する',
        kana: 'はっちゅうする',
        meaning: ['To place an order'],
        sentence: '新しい商品を発注しました。',
        type: 'main',
      },
      {
        reading: '不注意',
        kana: 'ふちゅうい',
        meaning: ['Carelessness'],
        sentence: '不注意で事故を起こしてしまいました。',
        type: 'secondary',
      },
      {
        reading: '注ぐ',
        kana: 'そそぐ',
        meaning: ['To pour'],
        sentence: 'お茶を注ぐときは、丁寧に注ぎます。',
        type: 'main',
      },
    ],
  },
  {
    kanji: '意',
    onyomi: ['い'],
    kunyomi: [],
    meaning: ['Mind'],
    examples: [
      {
        reading: '意味',
        kana: 'いみ',
        meaning: ['Meaning'],
        sentence: 'この言葉の意味を教えてください。',
        type: 'main',
      },
      {
        reading: '注意する',
        kana: 'ちゅういする',
        meaning: ['To be careful', 'To watch out'],
        sentence: '運転中は注意してください。',
        type: 'main',
      },
      {
        reading: '意見',
        kana: 'いけん',
        meaning: ['Opinion'],
        sentence: 'あなたの意見を聞かせてください。',
        type: 'main',
      },
      {
        reading: '用意する',
        kana: 'よういする',
        meaning: ['To prepare'],
        sentence: '旅行のために用意をしています。',
        type: 'main',
      },
      {
        reading: '好意',
        kana: 'こうい',
        meaning: ['Goodwill'],
        sentence: '彼女の好意に感謝しています。',
        type: 'secondary',
      },
      {
        reading: '意外な',
        kana: 'いがいな',
        meaning: ['Unexpected'],
        sentence: '意外な結果に驚きました。',
        type: 'secondary',
      },
      {
        reading: '意思',
        kana: 'いし',
        meaning: ['Will', 'Intention'],
        sentence: '彼の意思を尊重します。',
        type: 'secondary',
      },
    ],
  },
]